### ISSUE TITLE
ClassicUI: "TypeError: Cannot read property 'id' of null"

### ISSUE THREAD

**Issue by watou** [eclipse/smarthome#1102]
In browser console, this continues to occur every minute or so:
```
TypeError: Cannot read property 'id' of null
    at _TT (http://localhost:8080/classicui/WebApp/Action/Logic.js:176:76)
    at http://localhost:8080/classicui/WebApp/Action/Logic.js:166:67
    at _VV (http://localhost:8080/classicui/WebApp/Action/Logic.js:189:47)
    at XMLHttpRequest.c (http://localhost:8080/classicui/WebApp/Action/Logic.js:17:169)
```

It appears to be the same as https://github.com/openhab/openhab/issues/1662#issuecomment-67457354.

**Comment by triller-telekom** [comment]
@watou is this issue still valid for you? I just opened the developer tools in chromium and clicked through the demo sitemap in classicui but I did not get such an error message. Can you still reproduce it? And if so can you please provide some details about your `.items` and `.sitemap` files?

**Comment by kaikreuzer** [comment]
Well, we have the sources of the framework in our repo, so we could potentially fix it.
But as the Classic UI is rather legacy, I also doubt that it would be worth the effort.
