### ISSUE TITLE
Problem compiling smarthome on my macosx

### ISSUE THREAD

**Issue by jrcourtois** [eclipse/smarthome#1130]
I tried to compile smarthome from the git repository and got this issue

```
[INFO] Eclipse SmartHome Automation Core ................. SUCCESS [0.630s]
[INFO] Eclipse SmartHome Automation Core Tests ........... FAILURE [4.374s]

```
The log file 
[error.txt](https://github.com/eclipse/smarthome/files/157238/error.txt)

I am working on a mac version 10.8.5

**Comment by maggu2810** [comment]
I will test a clean checkout and a fresh build, now.

**Comment by maggu2810** [comment]
Another one here:
```text
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.eclipse.smarthome.core.thing.internal.ChannelStateDescriptionProviderOSGiTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.674 sec - in org.eclipse.smarthome.core.thing.internal.ChannelStateDescriptionProviderOSGiTest
assert that item's state description is present(org.eclipse.smarthome.core.thing.internal.ChannelStateDescriptionProviderOSGiTest)  Time elapsed: 1.23 sec
Running org.eclipse.smarthome.core.thing.internal.ThingManagerOSGiTest
Tests run: 15, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.013 sec - in org.eclipse.smarthome.core.thing.internal.ThingManagerOSGiTest
ThingManager complains if the managed thing provider cannot handle thing updates(org.eclipse.smarthome.core.thing.internal.ThingManagerOSGiTest)  Time elapsed: 0.136 sec
ThingManager calls initialize for added Thing correctly(org.eclipse.smarthome.core.thing.internal.ThingManagerOSGiTest)  Time elapsed: 0.294 sec
ThingManager handles thing status updates uninitialized and initializing correctly(org.eclipse.smarthome.core.thing.internal.ThingManagerOSGiTest)  Time elapsed: 0.099 sec
ThingManager handles state updates correctly(org.eclipse.smarthome.core.thing.internal.ThingManagerOSGiTest)  Time elapsed: 0.261 sec
ThingManager posts thing status events if the status of a thing is updated(org.eclipse.smarthome.core.thing.internal.ThingManagerOSGiTest)  Time elapsed: 0.12 sec
ThingManager posts thing status changed events if the status of a thing is changed(org.eclipse.smarthome.core.thing.internal.ThingManagerOSGiTest)  Time elapsed: 0.227 sec
ThingManager handles bridge status updates online and offline correctly(org.eclipse.smarthome.core.thing.internal.ThingManagerOSGiTest)  Time elapsed: 0.15 sec
ThingManager calls unregisterHandler for removed Thing(org.eclipse.smarthome.core.thing.internal.ThingManagerOSGiTest)  Time elapsed: 0.06 sec
ThingManager handles thing updates correctly(org.eclipse.smarthome.core.thing.internal.ThingManagerOSGiTest)  Time elapsed: 0.03 sec
ThingManager handles thing status updates online and offline correctly(org.eclipse.smarthome.core.thing.internal.ThingManagerOSGiTest)  Time elapsed: 0.063 sec
ThingManager does not delegate update events to its source(org.eclipse.smarthome.core.thing.internal.ThingManagerOSGiTest)  Time elapsed: 1.095 sec
ThingManager calls bridgeInitialized for added Bridge and Thing correctly(org.eclipse.smarthome.core.thing.internal.ThingManagerOSGiTest)  Time elapsed: 0.198 sec
ThingManager handles post command correctly(org.eclipse.smarthome.core.thing.internal.ThingManagerOSGiTest)  Time elapsed: 0.059 sec
ThingManager calls registerHandler for added Thing(org.eclipse.smarthome.core.thing.internal.ThingManagerOSGiTest)  Time elapsed: 0.035 sec
ThingManager handles thing status update uninitialized with an exception correctly(org.eclipse.smarthome.core.thing.internal.ThingManagerOSGiTest)  Time elapsed: 0.105 sec
Running org.eclipse.smarthome.core.thing.internal.ThingRegistryOSGiTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.133 sec - in org.eclipse.smarthome.core.thing.internal.ThingRegistryOSGiTest
assert that ThingRegistry delegates config update to thing handler(org.eclipse.smarthome.core.thing.internal.ThingRegistryOSGiTest)  Time elapsed: 0.05 sec
assert that ThingRegistry throws Exception for config update of non existing thing(org.eclipse.smarthome.core.thing.internal.ThingRegistryOSGiTest)  Time elapsed: 0.007 sec
assert that ThingRegistryEventSubscribers receive events about thing changes(org.eclipse.smarthome.core.thing.internal.ThingRegistryOSGiTest)  Time elapsed: 0.044 sec
Running org.eclipse.smarthome.core.thing.internal.ThingLinkManagerOSGiTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.36 sec - in org.eclipse.smarthome.core.thing.internal.ThingLinkManagerOSGiTest
assert that existing things are linked(org.eclipse.smarthome.core.thing.internal.ThingLinkManagerOSGiTest)  Time elapsed: 0.173 sec
assert that item update for items which are linked to things works(org.eclipse.smarthome.core.thing.internal.ThingLinkManagerOSGiTest)  Time elapsed: 0.092 sec
assert that items are unlinked(org.eclipse.smarthome.core.thing.internal.ThingLinkManagerOSGiTest)  Time elapsed: 0.042 sec
assert that channelLinked and channelUnlinked at ThingHandler is called(org.eclipse.smarthome.core.thing.internal.ThingLinkManagerOSGiTest) skipped
assert that items are linked to thing and channel(org.eclipse.smarthome.core.thing.internal.ThingLinkManagerOSGiTest)  Time elapsed: 0.038 sec
Running org.eclipse.smarthome.core.thing.link.ItemChannelLinkOSGiTest
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.242 sec - in org.eclipse.smarthome.core.thing.link.ItemChannelLinkOSGiTest
assert getBoundThings returns empty set(org.eclipse.smarthome.core.thing.link.ItemChannelLinkOSGiTest)  Time elapsed: 0.062 sec
assert getBoundThings returns thing(org.eclipse.smarthome.core.thing.link.ItemChannelLinkOSGiTest)  Time elapsed: 0.023 sec
assert getBoundChannels returns channel(org.eclipse.smarthome.core.thing.link.ItemChannelLinkOSGiTest)  Time elapsed: 0.032 sec
assert isLinked returns false(org.eclipse.smarthome.core.thing.link.ItemChannelLinkOSGiTest)  Time elapsed: 0.013 sec
assert ItemChannelLink is present in ItemChannelLinkRegistry when added to ManagedItemChannelLinkProvider(org.eclipse.smarthome.core.thing.link.ItemChannelLinkOSGiTest)  Time elapsed: 0.013 sec
assert getBoundChannels returns empty set(org.eclipse.smarthome.core.thing.link.ItemChannelLinkOSGiTest)  Time elapsed: 0.035 sec
assert isLinked returns true(org.eclipse.smarthome.core.thing.link.ItemChannelLinkOSGiTest)  Time elapsed: 0.012 sec
Running org.eclipse.smarthome.core.thing.link.LinkEventOSGiTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.121 sec - in org.eclipse.smarthome.core.thing.link.LinkEventOSGiTest
assert item thing link events are sent(org.eclipse.smarthome.core.thing.link.LinkEventOSGiTest)  Time elapsed: 0.088 sec
assert item channel link events are sent(org.eclipse.smarthome.core.thing.link.LinkEventOSGiTest)  Time elapsed: 0.026 sec
Running org.eclipse.smarthome.core.thing.binding.BindingBaseClassesOSGiTest
Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.779 sec - in org.eclipse.smarthome.core.thing.binding.BindingBaseClassesOSGiTest
assert BaseThingHandlerFactory registers config status provider(org.eclipse.smarthome.core.thing.binding.BindingBaseClassesOSGiTest)  Time elapsed: 0.088 sec
assert configuration is rolled-back on error(org.eclipse.smarthome.core.thing.binding.BindingBaseClassesOSGiTest)  Time elapsed: 0.092 sec
assert properties can be updated from ThingHandler(org.eclipse.smarthome.core.thing.binding.BindingBaseClassesOSGiTest)  Time elapsed: 0.112 sec
assert BaseThingHandlerFactory registers handler and BaseThingHandlers getBridge works(org.eclipse.smarthome.core.thing.binding.BindingBaseClassesOSGiTest)  Time elapsed: 0.036 sec
assert thing can be updated from ThingHandler(org.eclipse.smarthome.core.thing.binding.BindingBaseClassesOSGiTest)  Time elapsed: 0.047 sec
assert configuration parameters are validated(org.eclipse.smarthome.core.thing.binding.BindingBaseClassesOSGiTest)  Time elapsed: 0.041 sec
assert config status is propagated(org.eclipse.smarthome.core.thing.binding.BindingBaseClassesOSGiTest)  Time elapsed: 0.231 sec
assert configuration will be updated by default implementation(org.eclipse.smarthome.core.thing.binding.BindingBaseClassesOSGiTest)  Time elapsed: 0.04 sec
assert BaseThingHandler notifies ThingManager about configuration updates(org.eclipse.smarthome.core.thing.binding.BindingBaseClassesOSGiTest)  Time elapsed: 0.067 sec
Running org.eclipse.smarthome.core.thing.binding.ChangeThingTypeOSGiTest
Generic Handle Command
Specific Handle Command
Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 4.515 sec <<< FAILURE! - in org.eclipse.smarthome.core.thing.binding.ChangeThingTypeOSGiTest
assert loading specialized thing type works directly(org.eclipse.smarthome.core.thing.binding.ChangeThingTypeOSGiTest)  Time elapsed: 0.251 sec
assert changing thing type within initialize works(org.eclipse.smarthome.core.thing.binding.ChangeThingTypeOSGiTest)  Time elapsed: 4.106 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: is an instance of org.eclipse.smarthome.core.thing.binding.ChangeThingTypeOSGiTest$SpecificThingHandler
     but: <org.eclipse.smarthome.core.thing.binding.ChangeThingTypeOSGiTest$GenericThingHandler@2c2c2ef9> is a org.eclipse.smarthome.core.thing.binding.ChangeThingTypeOSGiTest$GenericThingHandler
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:865)
	at org.junit.Assert.assertThat(Assert.java:832)
	at org.junit.Assert$assertThat.callStatic(Unknown Source)
	at org.eclipse.smarthome.core.thing.binding.ChangeThingTypeOSGiTest$_assertThingWasChanged_closure16.doCall(ChangeThingTypeOSGiTest.groovy:320)
	at org.eclipse.smarthome.core.thing.binding.ChangeThingTypeOSGiTest$_assertThingWasChanged_closure16.doCall(ChangeThingTypeOSGiTest.groovy)
	at sun.reflect.GeneratedMethodAccessor83.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:278)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at org.eclipse.smarthome.test.OSGiTest.waitForAssert(OSGiTest.groovy:181)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:207)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:149)
	at org.eclipse.smarthome.core.thing.binding.ChangeThingTypeOSGiTest.assertThingWasChanged(ChangeThingTypeOSGiTest.groovy:319)
	at org.eclipse.smarthome.core.thing.binding.ChangeThingTypeOSGiTest.this$3$assertThingWasChanged(ChangeThingTypeOSGiTest.groovy)

assert changing the ThingType works(org.eclipse.smarthome.core.thing.binding.ChangeThingTypeOSGiTest)  Time elapsed: 0.091 sec
Running org.eclipse.smarthome.core.thing.binding.ThingFactoryTest
Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.145 sec - in org.eclipse.smarthome.core.thing.binding.ThingFactoryTest
create Thing with different default value types(org.eclipse.smarthome.core.thing.binding.ThingFactoryTest)  Time elapsed: 0.047 sec
create Thing with Default values(org.eclipse.smarthome.core.thing.binding.ThingFactoryTest)  Time elapsed: 0.031 sec
create Thing with Bridge(org.eclipse.smarthome.core.thing.binding.ThingFactoryTest)  Time elapsed: 0.003 sec
create Bridge with properties(org.eclipse.smarthome.core.thing.binding.ThingFactoryTest)  Time elapsed: 0.004 sec
create Thing with channels groups(org.eclipse.smarthome.core.thing.binding.ThingFactoryTest)  Time elapsed: 0.027 sec
create simple Thing(org.eclipse.smarthome.core.thing.binding.ThingFactoryTest)  Time elapsed: 0.001 sec
create Thing with Channels(org.eclipse.smarthome.core.thing.binding.ThingFactoryTest)  Time elapsed: 0.021 sec
create simple Bridge(org.eclipse.smarthome.core.thing.binding.ThingFactoryTest)  Time elapsed: 0.002 sec
create Thing with properties(org.eclipse.smarthome.core.thing.binding.ThingFactoryTest)  Time elapsed: 0.001 sec
Running org.eclipse.smarthome.core.thing.events.ThingEventFactoryTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.094 sec - in org.eclipse.smarthome.core.thing.events.ThingEventFactoryTest
ThingEventFactory creates ThingAddedEvent correctly(org.eclipse.smarthome.core.thing.events.ThingEventFactoryTest)  Time elapsed: 0.007 sec
ThingEventFactory creates ThingStatusInfoEvent correctly(org.eclipse.smarthome.core.thing.events.ThingEventFactoryTest)  Time elapsed: 0.005 sec
ThingEventFactory creates Event as ThingAddedEvent correctly(org.eclipse.smarthome.core.thing.events.ThingEventFactoryTest)  Time elapsed: 0.002 sec
ThingEventFactory creates Event as ThingStatusInfoEvent correctly(org.eclipse.smarthome.core.thing.events.ThingEventFactoryTest)  Time elapsed: 0.001 sec
Running org.eclipse.smarthome.core.thing.setup.RemovalTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.665 sec - in org.eclipse.smarthome.core.thing.setup.RemovalTest
remove Bridge with Things recursively(org.eclipse.smarthome.core.thing.setup.RemovalTest)  Time elapsed: 0.294 sec
removeThing(org.eclipse.smarthome.core.thing.setup.RemovalTest)  Time elapsed: 0.241 sec
synchronous remove Thing terminates fast (no deadlock)(org.eclipse.smarthome.core.thing.setup.RemovalTest)  Time elapsed: 0.112 sec
Running org.eclipse.smarthome.core.thing.setup.ThingSetupManagerOSGiTest
Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.599 sec - in org.eclipse.smarthome.core.thing.setup.ThingSetupManagerOSGiTest
enableAndDisableChannel(org.eclipse.smarthome.core.thing.setup.ThingSetupManagerOSGiTest)  Time elapsed: 0.085 sec
remove Bridge with Things recursively(org.eclipse.smarthome.core.thing.setup.ThingSetupManagerOSGiTest)  Time elapsed: 0.176 sec
addAndRemoveFromHomeGroup(org.eclipse.smarthome.core.thing.setup.ThingSetupManagerOSGiTest)  Time elapsed: 0.051 sec
removeThing(org.eclipse.smarthome.core.thing.setup.ThingSetupManagerOSGiTest)  Time elapsed: 0.04 sec
addAndRemoveHomeGroup(org.eclipse.smarthome.core.thing.setup.ThingSetupManagerOSGiTest)  Time elapsed: 0.102 sec
addThingWithoutChannelsItems(org.eclipse.smarthome.core.thing.setup.ThingSetupManagerOSGiTest)  Time elapsed: 0.021 sec
addThingWithChannelsGroups(org.eclipse.smarthome.core.thing.setup.ThingSetupManagerOSGiTest)  Time elapsed: 0.035 sec
setLabel(org.eclipse.smarthome.core.thing.setup.ThingSetupManagerOSGiTest)  Time elapsed: 0.039 sec
addThingWithChannelsItems(org.eclipse.smarthome.core.thing.setup.ThingSetupManagerOSGiTest)  Time elapsed: 0.039 sec
Running org.eclipse.smarthome.core.thing.util.ThingHelperTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.038 sec - in org.eclipse.smarthome.core.thing.util.ThingHelperTest
Two things are different after channels were modified(org.eclipse.smarthome.core.thing.util.ThingHelperTest)  Time elapsed: 0.024 sec
Two things are different after properties were modified(org.eclipse.smarthome.core.thing.util.ThingHelperTest)  Time elapsed: 0.003 sec
Two technical equal Thing instances are detected as "equal"(org.eclipse.smarthome.core.thing.util.ThingHelperTest)  Time elapsed: 0.001 sec
Running org.eclipse.smarthome.core.thing.factory.ManagedThingProviderOSGiTest
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.128 sec - in org.eclipse.smarthome.core.thing.factory.ManagedThingProviderOSGiTest
assert that added thing is returned by getThings(org.eclipse.smarthome.core.thing.factory.ManagedThingProviderOSGiTest)  Time elapsed: 0.02 sec
assert that twice added thing throws exception(org.eclipse.smarthome.core.thing.factory.ManagedThingProviderOSGiTest)  Time elapsed: 0.006 sec
assert that removed thing is not returned by getThings(org.eclipse.smarthome.core.thing.factory.ManagedThingProviderOSGiTest)  Time elapsed: 0.007 sec
assert that ThingsChangeListener is notified about added thing(org.eclipse.smarthome.core.thing.factory.ManagedThingProviderOSGiTest)  Time elapsed: 0.047 sec
assert that ThingsChangeListener is notified about updated thing(org.eclipse.smarthome.core.thing.factory.ManagedThingProviderOSGiTest)  Time elapsed: 0.012 sec
assert that createThing delegates to registered ThingHandlerFactory(org.eclipse.smarthome.core.thing.factory.ManagedThingProviderOSGiTest)  Time elapsed: 0.032 sec
Running org.eclipse.smarthome.core.thing.ThingUIDTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.007 sec - in org.eclipse.smarthome.core.thing.ThingUIDTest
read properties for 3 segments(org.eclipse.smarthome.core.thing.ThingUIDTest)  Time elapsed: 0.001 sec
read properties for 2 segments(org.eclipse.smarthome.core.thing.ThingUIDTest)  Time elapsed: 0.003 sec
Running org.eclipse.smarthome.core.thing.UIDTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.021 sec - in org.eclipse.smarthome.core.thing.UIDTest
UID cannot be constructed with invalid charaters(org.eclipse.smarthome.core.thing.UIDTest)  Time elapsed: 0 sec
channel UID with group(org.eclipse.smarthome.core.thing.UIDTest)  Time elapsed: 0.001 sec
valid UIDs(org.eclipse.smarthome.core.thing.UIDTest)  Time elapsed: 0 sec
Running org.eclipse.smarthome.core.thing.ThingPropertiesTest
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.02 sec - in org.eclipse.smarthome.core.thing.ThingPropertiesTest
test set property with null name(org.eclipse.smarthome.core.thing.ThingPropertiesTest)  Time elapsed: 0 sec
test get property(org.eclipse.smarthome.core.thing.ThingPropertiesTest)  Time elapsed: 0.001 sec
test set new property value(org.eclipse.smarthome.core.thing.ThingPropertiesTest)  Time elapsed: 0.001 sec
test set property with empty name(org.eclipse.smarthome.core.thing.ThingPropertiesTest)  Time elapsed: 0.001 sec
test remove property(org.eclipse.smarthome.core.thing.ThingPropertiesTest)  Time elapsed: 0 sec
test set new property(org.eclipse.smarthome.core.thing.ThingPropertiesTest)  Time elapsed: 0.001 sec

Results :

Failed tests: 
  ChangeThingTypeOSGiTest.assert changing thing type within initialize works:272->this$3$assertThingWasChanged:-1->assertThingWasChanged:319->OSGiTest.waitForAssert:181 
Expected: is an instance of org.eclipse.smarthome.core.thing.binding.ChangeThingTypeOSGiTest$SpecificThingHandler
     but: <org.eclipse.smarthome.core.thing.binding.ChangeThingTypeOSGiTest$GenericThingHandler@2c2c2ef9> is a org.eclipse.smarthome.core.thing.binding.ChangeThingTypeOSGiTest$GenericThingHandler

Tests run: 90, Failures: 1, Errors: 0, Skipped: 1

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Eclipse SmartHome .................................. SUCCESS [ 22.365 s]
[INFO] Eclipse SmartHome Bundles .......................... SUCCESS [  0.043 s]
[INFO] Eclipse SmartHome Test Components .................. SUCCESS [  0.044 s]
[INFO] Eclipse SmartHome Core Components .................. SUCCESS [  0.044 s]
[INFO] Eclipse SmartHome Core ............................. SUCCESS [  7.409 s]
[INFO] Eclipse SmartHome Configurations ................... SUCCESS [  0.016 s]
[INFO] Eclipse SmartHome Configuration Core ............... SUCCESS [  1.325 s]
[INFO] Eclipse SmartHome Configuration XML ................ SUCCESS [  1.443 s]
[INFO] Eclipse SmartHome AutoUpdate Binding ............... SUCCESS [  0.574 s]
[INFO] Eclipse SmartHome Test ............................. SUCCESS [  2.479 s]
[INFO] Eclipse SmartHome Configuration Dispatcher ......... SUCCESS [  0.397 s]
[INFO] Eclipse SmartHome Configuration Core Tests ......... SUCCESS [  5.040 s]
[INFO] Eclipse SmartHome I/O Components ................... SUCCESS [  0.012 s]
[INFO] Eclipse SmartHome Console .......................... SUCCESS [  0.343 s]
[INFO] Eclipse SmartHome Thing ............................ SUCCESS [  1.137 s]
[INFO] Eclipse SmartHome Configuration Discovery .......... SUCCESS [  0.556 s]
[INFO] Eclipse SmartHome Configuration Discovery Tests .... SUCCESS [ 10.384 s]
[INFO] Eclipse SmartHome Config XML Tests ................. SUCCESS [  7.796 s]
[INFO] Eclipse SmartHome Sample Extension Service ......... SUCCESS [  0.427 s]
[INFO] Eclipse SmartHome mDNS Service ..................... SUCCESS [  0.699 s]
[INFO] Eclipse SmartHome REST Interface ................... SUCCESS [  0.954 s]
[INFO] Eclipse SmartHome Core ID .......................... SUCCESS [  0.557 s]
[INFO] Eclipse SmartHome Thing Tests ...................... SUCCESS [  5.878 s]
[INFO] Eclipse SmartHome Core Tests ....................... SUCCESS [ 10.667 s]
[INFO] Eclipse SmartHome Thing Tests ...................... FAILURE [ 19.930 s]
[INFO] Eclipse SmartHome Core Persistence ................. SKIPPED
[INFO] Eclipse SmartHome Core Scheduler Service ........... SKIPPED
[INFO] Eclipse SmartHome Network I/O ...................... SKIPPED
[INFO] Eclipse SmartHome Models ........................... SKIPPED
[INFO] Eclipse SmartHome Model Core ....................... SKIPPED
[INFO] Eclipse SmartHome Model Lazy Generation ............ SKIPPED
```

**Comment by jrcourtois** [comment]
I manage to compile smarthome by updating my maven version...
