### ISSUE TITLE
Exceptions relative to persistence at first OH2 startup

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#1270]
Starting the first time the last OH2 offline distribution, I got few exceptions relative to persistence.
First one:
```
2016-03-26 12:17:18.711 [ERROR] [.eclipse.smarthome.model.persistence] - [org.eclipse.smarthome.core.persistence.manager(120)] The setModelRepository method has thrown an exception
java.lang.ClassCastException: org.eclipse.smarthome.model.persistence.persistence.impl.PersistenceModelImpl cannot be cast to org.eclipse.smarthome.model.persistence.persistence.PersistenceModel
        at org.eclipse.smarthome.model.persistence.internal.PersistenceManager.startEventHandling(PersistenceManager.java:175)
        at org.eclipse.smarthome.model.persistence.internal.PersistenceManager.setModelRepository(PersistenceManager.java:117)
...
```
Second one:
```
2016-03-26 12:19:14.915 [ERROR] [.eclipse.smarthome.model.persistence] - [org.eclipse.smarthome.core.persistence.manager(120)] The addPersistenceService method has thrown an exception
java.lang.ClassCastException: org.eclipse.smarthome.model.persistence.persistence.impl.PersistenceModelImpl cannot be cast to org.eclipse.smarthome.model.persistence.persistence.PersistenceModel
        at org.eclipse.smarthome.model.persistence.internal.PersistenceManager.startEventHandling(PersistenceManager.java:175)
        at org.eclipse.smarthome.model.persistence.internal.PersistenceManager.addPersistenceService(PersistenceManager.java:144)
```
After a restart, these errors do not occur.

**Comment by kaikreuzer** [comment]
I do not see these messages anymore on the latest OH2 distro - so I assume it is fixed with #1407.

Feel free to re-open this issue in case you still come across it.
