### ISSUE TITLE
Empty string in configuration should set property to null and not to ""

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#1301]
If a value is deleted in a configuration, the updated configuration contains an empty string instead of a null value. This results in exceptions like
```
2016-03-31 21:59:56.691 [WARN ] [.e.s.config.core.Configuration:94   ] - Could not set field value for field 'callbackPort': Can not set int field org.openhab.binding.homematic.internal.common.HomematicConfig.callbackPort to java.lang.Stringjava.lang.IllegalArgumentException: Can not set int field org.openhab.binding.homematic.internal.common.HomematicConfig.callbackPort to java.lang.String
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
	at sun.reflect.UnsafeIntegerFieldAccessorImpl.set(UnsafeIntegerFieldAccessorImpl.java:98)
	at java.lang.reflect.Field.set(Field.java:758)
	at org.apache.commons.lang.reflect.FieldUtils.writeField(FieldUtils.java:523)
	at org.apache.commons.lang.reflect.FieldUtils.writeField(FieldUtils.java:500)
	at org.apache.commons.lang.reflect.FieldUtils.writeField(FieldUtils.java:560)
	at org.eclipse.smarthome.config.core.Configuration.as(Configuration.java:91)
	at org.openhab.binding.homematic.handler.HomematicBridgeHandler.createHomematicConfig(HomematicBridgeHandler.java:169)
```
and problems like https://github.com/eclipse/smarthome/issues/1294.

**Comment by aounhaider1** [comment]
Setting values to null returns a 500 internal server error. Here is the log from console:
````
2016-04-01 12:18:49.700 [DEBUG] [r.JSONResponse$ExceptionMapper:158  ] - exception during REST Handlingjava.lang.NullPointerException: null value
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:204)
	at com.google.common.collect.ImmutableMap.entryOf(ImmutableMap.java:139)
	at com.google.common.collect.ImmutableMap.copyOf(ImmutableMap.java:263)
	at org.eclipse.smarthome.config.core.Configuration.getProperties(Configuration.java:145)
	at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.updateConfiguration(BaseThingHandler.java:395)
	at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.handleConfigurationUpdate(BaseThingHandler.java:130)
	at org.eclipse.smarthome.core.thing.internal.ThingRegistryImpl.updateConfiguration(ThingRegistryImpl.java:87)
	at org.eclipse.smarthome.io.rest.core.thing.ThingResource.updateConfiguration(ThingResource.java:407)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
````

**Comment by kaikreuzer** [comment]
@sjka Could you check and fix the server side of it?

**Comment by sjka** [comment]
yepp, will do

**Comment by kaikreuzer** [comment]
Reopening as I expect that we also need some code change in the Paper UI.
