### ISSUE TITLE
Test failure(s): automation.module.script.ScriptRuleTest: fails sometimes

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#1327]
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.eclipse.smarthome.automation.module.script.ScriptRuleTest
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 3.314 sec <<< FAILURE! - in org.eclipse.smarthome.automation.module.script.ScriptRuleTest
testPredefinedRule(org.eclipse.smarthome.automation.module.script.ScriptRuleTest)  Time elapsed: 2.278 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: not null
     but: was null
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:865)
	at org.junit.Assert.assertThat(Assert.java:832)
	at org.junit.Assert$assertThat.callStatic(Unknown Source)
	at org.eclipse.smarthome.automation.module.script.ScriptRuleTest$_testPredefinedRule_closure12.doCall(ScriptRuleTest.groovy:130)
	at org.eclipse.smarthome.automation.module.script.ScriptRuleTest$_testPredefinedRule_closure12.doCall(ScriptRuleTest.groovy)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:278)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at org.eclipse.smarthome.test.OSGiTest.waitForAssert(OSGiTest.groovy:181)
	at org.eclipse.smarthome.test.OSGiTest.waitForAssert(OSGiTest.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:207)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:141)
	at org.eclipse.smarthome.automation.module.script.ScriptRuleTest.testPredefinedRule(ScriptRuleTest.groovy:129)


Results :

Failed tests: 
  ScriptRuleTest.testPredefinedRule:129->OSGiTest.waitForAssert:-1->OSGiTest.waitForAssert:181 
Expected: not null
     but: was null

Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
```

**Comment by maggu2810** [comment]
A second <code>mvn clean install</code> is working. So perhaps more a wired behavior / timing issue / ...

**Comment by kaikreuzer** [comment]
It seems so. I also cannot make it fail when running it locally from the IDE.

**Comment by llamahunter** [comment]
I see this as well.  Will try doing another 'mvn clean install' to see if it self corrects.

**Comment by llamahunter** [comment]
Did a `mvn clean install` but it still failed. Then did a `git pull` and another `mvn clean install` and it worked.  Looks like the github repo may have been in a transient bad state.

**Comment by kaikreuzer** [comment]
Ok, let's close it for now and feel free to re-open if it occurs again.

**Comment by maggu2810** [comment]
https://hudson.eclipse.org/smarthome/job/SmartHomeDistribution-Nightly/957/changes

```text
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.eclipse.smarthome.automation.module.script.ScriptRuleTest
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 29.675 sec <<< FAILURE! - in org.eclipse.smarthome.automation.module.script.ScriptRuleTest
testPredefinedRule(org.eclipse.smarthome.automation.module.script.ScriptRuleTest)  Time elapsed: 29.011 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: is <false>
     but: was <true>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:865)
	at org.junit.Assert.assertThat(Assert.java:832)
	at org.junit.Assert$assertThat.callStatic(Unknown Source)
	at org.eclipse.smarthome.automation.module.script.ScriptRuleTest$_testPredefinedRule_closure8.doCall(ScriptRuleTest.groovy:97)
	at org.eclipse.smarthome.automation.module.script.ScriptRuleTest$_testPredefinedRule_closure8.doCall(ScriptRuleTest.groovy)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:278)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at org.eclipse.smarthome.test.OSGiTest.waitForAssert(OSGiTest.groovy:181)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:207)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:149)
	at org.eclipse.smarthome.automation.module.script.ScriptRuleTest.testPredefinedRule(ScriptRuleTest.groovy:96)


Results :

Failed tests: 
  ScriptRuleTest.testPredefinedRule:96->OSGiTest.waitForAssert:181 
Expected: is <false>
     but: was <true>

Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
```

**Comment by maggu2810** [comment]
My machine succeeded, Hudson failed.
So no general failure but perhaps also some wired behaviour.

**Comment by sjka** [comment]
Jenkins here just failed with the same issue

**Comment by maggu2810** [comment]
@sjka Have you seen this error again after the latest changes (drop of lazy activation, ...)?

WDYT about closing this one and open it again, if it occurs again?

**Comment by sjka** [comment]
No, it hasn't. 
Agreed.

**Comment by maggu2810** [comment]
```-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.eclipse.smarthome.automation.module.script.ScriptRuleTest
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 3.13 sec <<< FAILURE! - in org.eclipse.smarthome.automation.module.script.ScriptRuleTest
testPredefinedRule(org.eclipse.smarthome.automation.module.script.ScriptRuleTest)  Time elapsed: 2.219 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: not null
     but: was null
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:865)
	at org.junit.Assert.assertThat(Assert.java:832)
	at org.junit.Assert$assertThat.callStatic(Unknown Source)
	at org.eclipse.smarthome.automation.module.script.ScriptRuleTest$_testPredefinedRule_closure12.doCall(ScriptRuleTest.groovy:130)
	at org.eclipse.smarthome.automation.module.script.ScriptRuleTest$_testPredefinedRule_closure12.doCall(ScriptRuleTest.groovy)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:278)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at org.eclipse.smarthome.test.OSGiTest.waitForAssert(OSGiTest.groovy:181)
	at org.eclipse.smarthome.test.OSGiTest.waitForAssert(OSGiTest.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:207)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:141)
	at org.eclipse.smarthome.automation.module.script.ScriptRuleTest.testPredefinedRule(ScriptRuleTest.groovy:129)


Results :

Failed tests: 
  ScriptRuleTest.testPredefinedRule:129->OSGiTest.waitForAssert:-1->OSGiTest.waitForAssert:181 
Expected: not null
     but: was null

Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
```

```
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   targetplatform/SmartHome Runtime.launch

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	distribution/smarthome/userdata/

no changes added to commit (use "git add" and/or "git commit -a")
$ git rev-parse HEAD
0b3f1768168f5ceb1e76f42c1ed9bda66918b90c
```

**Comment by maggu2810** [comment]
Will give it a try and assume it has been solved now.
