### ISSUE TITLE
Test failure(s): Hue: HueLightHandlerOSGiTest

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#1334]
My intention was to check if #1327 does not occur anymore on my system.
I have created a new branch to test the build
* git fetch origin
* git checkout -b test origin/master

Now I run a clean build loop until an error occurred.
```bash
(i=0; while true; do printf "Start the %d. iteration.\n" $((++i)); git reset --hard origin/master; git clean -x -d -f; mvn clean install || break; done; printf "Failed at the %d. iteration.\n" ${i})
```

Perhaps we (the developers on our local machines) could start such loops from time to time. WDYT?

The iteration number does not really matter, but it shows that there are failures that are raised under some special conditions.
The error below occurs e.g. at the 4. iteration.

<code>git rev-parse HEAD</code>
```text
86f316b034129cb2d6e3ca64b068593c418e73de
```

<code>mvn --version</code>
```text
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)
Maven home: /usr/share/maven-bin-3.3
Java version: 1.8.0_74, vendor: Oracle Corporation
Java home: /opt/oracle-jdk-bin-1.8.0.74/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.3.0-gentoo", arch: "amd64", family: "unix"
```

```text
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest
Tests run: 28, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 50.156 sec <<< FAILURE! - in org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest
assert command for brightness channel: on(org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest)  Time elapsed: 1.481 sec
assert command for color channel: black(org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest)  Time elapsed: 1.172 sec
assert command for color channel: white(org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest)  Time elapsed: 1.142 sec
assert command for color channel: increase(org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest)  Time elapsed: 12.336 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: is null
     but: was <org.eclipse.smarthome.core.thing.internal.BridgeImpl@586b17e7>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:865)
	at org.junit.Assert.assertThat(Assert.java:832)
	at org.junit.Assert$assertThat.callStatic(Unknown Source)
	at org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest$_assertSendCommand_closure10.doCall(HueLightHandlerOSGiTest.groovy:449)
	at org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest$_assertSendCommand_closure10.doCall(HueLightHandlerOSGiTest.groovy)
	at sun.reflect.GeneratedMethodAccessor23.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:278)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at org.eclipse.smarthome.test.OSGiTest.waitForAssert(OSGiTest.groovy:181)
	at org.eclipse.smarthome.test.OSGiTest.waitForAssert(OSGiTest.groovy)
	at sun.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:207)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:145)
	at org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest.assertSendCommand(HueLightHandlerOSGiTest.groovy:447)
	at org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest.this$3$assertSendCommand(HueLightHandlerOSGiTest.groovy)

assert command for osram par16 50 for color temperature channel: off(org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest)  Time elapsed: 1.133 sec
assert command for color channel: decrease(org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest)  Time elapsed: 2.26 sec
assert command for osram par16 50 for brightness channel: off(org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest)  Time elapsed: 1.135 sec
assert that HueLightHandler is registered and unregistered(org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest)  Time elapsed: 0.015 sec
assert command for osram par16 50 for color temperature channel: on(org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest)  Time elapsed: 1.128 sec
assert command for color temperature channel: 0%(org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest)  Time elapsed: 1.139 sec
assert command for color temperature channel: on(org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest)  Time elapsed: 1.138 sec
assert command for color channel: 0%(org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest)  Time elapsed: 1.123 sec
assert command for color channel: on(org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest)  Time elapsed: 1.121 sec
assert command for brightness channel: 50%(org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest)  Time elapsed: 1.125 sec
assert command for brightness channel: off(org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest)  Time elapsed: 1.125 sec
assert command for color temperature channel: 50%(org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest)  Time elapsed: 1.138 sec
assert command for color temperature channel: off(org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest)  Time elapsed: 1.076 sec
assert command for color channel: 50%(org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest)  Time elapsed: 1.124 sec
assert command for color channel: off(org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest)  Time elapsed: 1.126 sec
assert command for color channel: red(org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest)  Time elapsed: 1.127 sec
assert command for brightness channel: increase(org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest)  Time elapsed: 3.352 sec
assert command for alert channel(org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest)  Time elapsed: 3.359 sec
assert command for brightness channel: decrease(org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest)  Time elapsed: 2.189 sec
assert command for color temperature channel: 100%(org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest)  Time elapsed: 1.12 sec
assert command for osram par16 50 for brightness channel: on(org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest)  Time elapsed: 1.12 sec
assert command for color channel: 100%(org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest)  Time elapsed: 1.127 sec
assert command for color channel: blue(org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest)  Time elapsed: 1.124 sec
assert command for effect channel(org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest)  Time elapsed: 2.247 sec
Running org.eclipse.smarthome.binding.hue.test.HueBridgeHandlerOSGiTest
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.132 sec - in org.eclipse.smarthome.binding.hue.test.HueBridgeHandlerOSGiTest
assert that HueBridgeHandler is registered and unregistered(org.eclipse.smarthome.binding.hue.test.HueBridgeHandlerOSGiTest)  Time elapsed: 0.017 sec
assert that an existing user is used if authentication was successful(org.eclipse.smarthome.binding.hue.test.HueBridgeHandlerOSGiTest)  Time elapsed: 0.03 sec
assert correct status if authentication failed for old user(org.eclipse.smarthome.binding.hue.test.HueBridgeHandlerOSGiTest)  Time elapsed: 0.024 sec
verify status if link button is not pressed(org.eclipse.smarthome.binding.hue.test.HueBridgeHandlerOSGiTest)  Time elapsed: 0.016 sec
assert that a new user is added to config if not existing yet(org.eclipse.smarthome.binding.hue.test.HueBridgeHandlerOSGiTest)  Time elapsed: 0.026 sec
verify status if new user cannot be created(org.eclipse.smarthome.binding.hue.test.HueBridgeHandlerOSGiTest)  Time elapsed: 0.012 sec
Running org.eclipse.smarthome.binding.hue.test.HueLightDiscoveryServiceOSGITest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.138 sec - in org.eclipse.smarthome.binding.hue.test.HueLightDiscoveryServiceOSGITest
assert hue light registration(org.eclipse.smarthome.binding.hue.test.HueLightDiscoveryServiceOSGITest)  Time elapsed: 0.092 sec
assert startSearch is called(org.eclipse.smarthome.binding.hue.test.HueLightDiscoveryServiceOSGITest)  Time elapsed: 1.028 sec
Running org.eclipse.smarthome.binding.hue.test.HueBridgeDiscoveryParticipantOSGITest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.049 sec - in org.eclipse.smarthome.binding.hue.test.HueBridgeDiscoveryParticipantOSGITest
assert no discovery result for unknown device(org.eclipse.smarthome.binding.hue.test.HueBridgeDiscoveryParticipantOSGITest)  Time elapsed: 0.03 sec
assert correct thing UID(org.eclipse.smarthome.binding.hue.test.HueBridgeDiscoveryParticipantOSGITest)  Time elapsed: 0.001 sec
assert no thing UID for unknown device(org.eclipse.smarthome.binding.hue.test.HueBridgeDiscoveryParticipantOSGITest)  Time elapsed: 0 sec
assert correct supported types(org.eclipse.smarthome.binding.hue.test.HueBridgeDiscoveryParticipantOSGITest)  Time elapsed: 0.004 sec
assert valid DiscoveryResult(org.eclipse.smarthome.binding.hue.test.HueBridgeDiscoveryParticipantOSGITest)  Time elapsed: 0.003 sec

Results :

Failed tests: 
  HueLightHandlerOSGiTest.assert command for color channel: increase:286->this$3$assertSendCommandForColor:-1->assertSendCommandForColor:382->this$3$assertSendCommand:-1->assertSendCommand:447->OSGiTest.waitForAssert:-1->OSGiTest.waitForAssert:181 
Expected: is null
     but: was <org.eclipse.smarthome.core.thing.internal.BridgeImpl@586b17e7>

Tests run: 41, Failures: 1, Errors: 0, Skipped: 0
```

**Comment by kaikreuzer** [comment]
Have a try with https://github.com/eclipse/smarthome/pull/1337, I would assume that this heavily improves the situation.

**Comment by maggu2810** [comment]
Thanks, will do so and re-run the test loop.

**Comment by maggu2810** [comment]
The fourth iteration is running. So, three times without failure. Will reopen if the error is raised again. Thanks.
