### ISSUE TITLE
thing factory helper: default values

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#1400]
I see this warning on thing creation of a third party bundle:

```text
2016-04-18 20:41:35,928 | WARN  | qtp478243416-738 | ThingFactory                     | 172 - org.eclipse.smarthome.core.thing - 0.8.0.a11 | Could not parse default value '' as type 'INTEGER': null
java.lang.NumberFormatException
	at java.math.BigDecimal.<init>(BigDecimal.java:596)[:1.8.0_74]
	at java.math.BigDecimal.<init>(BigDecimal.java:383)[:1.8.0_74]
	at java.math.BigDecimal.<init>(BigDecimal.java:806)[:1.8.0_74]
	at org.eclipse.smarthome.core.thing.internal.ThingFactoryHelper.getDefaultValueAsCorrectType(ThingFactoryHelper.java:155)
	at org.eclipse.smarthome.core.thing.internal.ThingFactoryHelper.applyDefaultConfiguration(ThingFactoryHelper.java:189)
	at org.eclipse.smarthome.core.thing.binding.ThingFactory.createThing(ThingFactory.java:98)
	at org.eclipse.smarthome.core.thing.binding.BaseThingHandlerFactory.createThing(BaseThingHandlerFactory.java:263)
	at org.eclipse.smarthome.core.thing.binding.ThingFactory.createThing(ThingFactory.java:110)
	at org.eclipse.smarthome.core.thing.setup.ThingSetupManager.addThing(ThingSetupManager.java:582)
	at org.eclipse.smarthome.core.thing.setup.ThingSetupManager.addThing(ThingSetupManager.java:198)
	at org.eclipse.smarthome.io.rest.core.thing.setup.ThingSetupManagerResource.addThing(ThingSetupManagerResource.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)[:1.8.0_74]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)[:1.8.0_74]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[:1.8.0_74]
	at java.lang.reflect.Method.invoke(Method.java:498)[:1.8.0_74]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)[14:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)[14:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)[14:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)[14:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)[14:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)[14:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)[14:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)[14:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)[14:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)[14:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)[14:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)[14:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)[14:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)[14:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)[14:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)[14:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)[14:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:471)[14:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:425)[14:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:383)[14:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:336)[14:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:223)[14:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at com.eclipsesource.jaxrs.publisher.internal.ServletContainerBridge.service(ServletContainerBridge.java:76)[17:com.eclipsesource.jaxrs.publisher:5.3.0.201512270850]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)[136:org.eclipse.jetty.servlet:9.2.14.v20151106]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)[136:org.eclipse.jetty.servlet:9.2.14.v20151106]
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:70)[227:org.ops4j.pax.web.pax-web-jetty:4.2.4]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)[135:org.eclipse.jetty.server:9.2.14.v20151106]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)[134:org.eclipse.jetty.security:9.2.14.v20151106]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)[135:org.eclipse.jetty.server:9.2.14.v20151106]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)[135:org.eclipse.jetty.server:9.2.14.v20151106]
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:271)[227:org.ops4j.pax.web.pax-web-jetty:4.2.4]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)[136:org.eclipse.jetty.servlet:9.2.14.v20151106]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)[135:org.eclipse.jetty.server:9.2.14.v20151106]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)[135:org.eclipse.jetty.server:9.2.14.v20151106]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)[135:org.eclipse.jetty.server:9.2.14.v20151106]
	at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:80)[227:org.ops4j.pax.web.pax-web-jetty:4.2.4]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)[135:org.eclipse.jetty.server:9.2.14.v20151106]
	at org.eclipse.jetty.server.Server.handle(Server.java:499)[135:org.eclipse.jetty.server:9.2.14.v20151106]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)[135:org.eclipse.jetty.server:9.2.14.v20151106]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)[135:org.eclipse.jetty.server:9.2.14.v20151106]
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)[127:org.eclipse.jetty.io:9.2.14.v20151106]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)[138:org.eclipse.jetty.util:9.2.14.v20151106]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)[138:org.eclipse.jetty.util:9.2.14.v20151106]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_74]
2016-04-18 20:41:35,933 | WARN  | qtp478243416-738 | ThingFactory                     | 172 - org.eclipse.smarthome.core.thing - 0.8.0.a11 | Could not parse default value '' as type 'INTEGER': null
java.lang.NumberFormatException
	at java.math.BigDecimal.<init>(BigDecimal.java:596)[:1.8.0_74]
	at java.math.BigDecimal.<init>(BigDecimal.java:383)[:1.8.0_74]
	at java.math.BigDecimal.<init>(BigDecimal.java:806)[:1.8.0_74]
	at org.eclipse.smarthome.core.thing.internal.ThingFactoryHelper.getDefaultValueAsCorrectType(ThingFactoryHelper.java:155)
	at org.eclipse.smarthome.core.thing.internal.ThingFactoryHelper.applyDefaultConfiguration(ThingFactoryHelper.java:189)
	at org.eclipse.smarthome.core.thing.binding.ThingFactory.createThing(ThingFactory.java:98)
	at org.eclipse.smarthome.core.thing.binding.BaseThingHandlerFactory.createThing(BaseThingHandlerFactory.java:263)
	at org.eclipse.smarthome.core.thing.binding.ThingFactory.createThing(ThingFactory.java:110)
	at org.eclipse.smarthome.core.thing.setup.ThingSetupManager.addThing(ThingSetupManager.java:582)
	at org.eclipse.smarthome.core.thing.setup.ThingSetupManager.addThing(ThingSetupManager.java:198)
	at org.eclipse.smarthome.io.rest.core.thing.setup.ThingSetupManagerResource.addThing(ThingSetupManagerResource.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)[:1.8.0_74]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)[:1.8.0_74]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[:1.8.0_74]
	at java.lang.reflect.Method.invoke(Method.java:498)[:1.8.0_74]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)[14:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)[14:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)[14:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)[14:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)[14:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)[14:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)[14:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)[14:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)[14:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)[14:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)[14:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)[14:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)[14:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)[14:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)[14:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)[14:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)[14:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:471)[14:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:425)[14:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:383)[14:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:336)[14:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:223)[14:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at com.eclipsesource.jaxrs.publisher.internal.ServletContainerBridge.service(ServletContainerBridge.java:76)[17:com.eclipsesource.jaxrs.publisher:5.3.0.201512270850]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)[136:org.eclipse.jetty.servlet:9.2.14.v20151106]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)[136:org.eclipse.jetty.servlet:9.2.14.v20151106]
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:70)[227:org.ops4j.pax.web.pax-web-jetty:4.2.4]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)[135:org.eclipse.jetty.server:9.2.14.v20151106]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)[134:org.eclipse.jetty.security:9.2.14.v20151106]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)[135:org.eclipse.jetty.server:9.2.14.v20151106]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)[135:org.eclipse.jetty.server:9.2.14.v20151106]
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:271)[227:org.ops4j.pax.web.pax-web-jetty:4.2.4]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)[136:org.eclipse.jetty.servlet:9.2.14.v20151106]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)[135:org.eclipse.jetty.server:9.2.14.v20151106]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)[135:org.eclipse.jetty.server:9.2.14.v20151106]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)[135:org.eclipse.jetty.server:9.2.14.v20151106]
	at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:80)[227:org.ops4j.pax.web.pax-web-jetty:4.2.4]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)[135:org.eclipse.jetty.server:9.2.14.v20151106]
	at org.eclipse.jetty.server.Server.handle(Server.java:499)[135:org.eclipse.jetty.server:9.2.14.v20151106]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)[135:org.eclipse.jetty.server:9.2.14.v20151106]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)[135:org.eclipse.jetty.server:9.2.14.v20151106]
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)[127:org.eclipse.jetty.io:9.2.14.v20151106]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)[138:org.eclipse.jetty.util:9.2.14.v20151106]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)[138:org.eclipse.jetty.util:9.2.14.v20151106]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_74]
2016-04-18 20:41:35,938 | WARN  | qtp478243416-738 | ThingFactory                     | 172 - org.eclipse.smarthome.core.thing - 0.8.0.a11 | Could not parse default value '' as type 'INTEGER': null
java.lang.NumberFormatException
	at java.math.BigDecimal.<init>(BigDecimal.java:596)[:1.8.0_74]
	at java.math.BigDecimal.<init>(BigDecimal.java:383)[:1.8.0_74]
	at java.math.BigDecimal.<init>(BigDecimal.java:806)[:1.8.0_74]
	at org.eclipse.smarthome.core.thing.internal.ThingFactoryHelper.getDefaultValueAsCorrectType(ThingFactoryHelper.java:155)
	at org.eclipse.smarthome.core.thing.internal.ThingFactoryHelper.applyDefaultConfiguration(ThingFactoryHelper.java:189)
	at org.eclipse.smarthome.core.thing.binding.ThingFactory.createThing(ThingFactory.java:98)
	at org.eclipse.smarthome.core.thing.binding.BaseThingHandlerFactory.createThing(BaseThingHandlerFactory.java:263)
	at org.eclipse.smarthome.core.thing.binding.ThingFactory.createThing(ThingFactory.java:110)
	at org.eclipse.smarthome.core.thing.setup.ThingSetupManager.addThing(ThingSetupManager.java:582)
	at org.eclipse.smarthome.core.thing.setup.ThingSetupManager.addThing(ThingSetupManager.java:198)
	at org.eclipse.smarthome.io.rest.core.thing.setup.ThingSetupManagerResource.addThing(ThingSetupManagerResource.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)[:1.8.0_74]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)[:1.8.0_74]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[:1.8.0_74]
	at java.lang.reflect.Method.invoke(Method.java:498)[:1.8.0_74]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)[14:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)[14:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)[14:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)[14:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)[14:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)[14:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)[14:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)[14:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)[14:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)[14:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)[14:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)[14:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)[14:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)[14:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)[14:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)[14:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)[14:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:471)[14:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:425)[14:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:383)[14:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:336)[14:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:223)[14:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at com.eclipsesource.jaxrs.publisher.internal.ServletContainerBridge.service(ServletContainerBridge.java:76)[17:com.eclipsesource.jaxrs.publisher:5.3.0.201512270850]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)[136:org.eclipse.jetty.servlet:9.2.14.v20151106]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)[136:org.eclipse.jetty.servlet:9.2.14.v20151106]
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:70)[227:org.ops4j.pax.web.pax-web-jetty:4.2.4]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)[135:org.eclipse.jetty.server:9.2.14.v20151106]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)[134:org.eclipse.jetty.security:9.2.14.v20151106]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)[135:org.eclipse.jetty.server:9.2.14.v20151106]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)[135:org.eclipse.jetty.server:9.2.14.v20151106]
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:271)[227:org.ops4j.pax.web.pax-web-jetty:4.2.4]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)[136:org.eclipse.jetty.servlet:9.2.14.v20151106]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)[135:org.eclipse.jetty.server:9.2.14.v20151106]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)[135:org.eclipse.jetty.server:9.2.14.v20151106]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)[135:org.eclipse.jetty.server:9.2.14.v20151106]
	at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:80)[227:org.ops4j.pax.web.pax-web-jetty:4.2.4]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)[135:org.eclipse.jetty.server:9.2.14.v20151106]
	at org.eclipse.jetty.server.Server.handle(Server.java:499)[135:org.eclipse.jetty.server:9.2.14.v20151106]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)[135:org.eclipse.jetty.server:9.2.14.v20151106]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)[135:org.eclipse.jetty.server:9.2.14.v20151106]
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)[127:org.eclipse.jetty.io:9.2.14.v20151106]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)[138:org.eclipse.jetty.util:9.2.14.v20151106]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)[138:org.eclipse.jetty.util:9.2.14.v20151106]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_74]
```

I assume this warning is correct and thrown if there is a default value missing. Is this correct?
Should a configuration contain a default value?

**Comment by kaikreuzer** [comment]
This reminds me of https://github.com/eclipse/smarthome/issues/1301 - if there is no default value, there should be a null value and not an empty string in the config (at least not for an INTEGER).

**Comment by maggu2810** [comment]
The XML of the bindings has been changed.
