### ISSUE TITLE
java.lang.NoSuchMethodError: org.eclipse.smarthome.config.core.Configuration.get(Ljava/lang/String;)Ljava/lang/Object;

### ISSUE THREAD

**Issue by kgoderis** [eclipse/smarthome#1437]
I get the above error based on the latest snapshot. 

The line of code triggering this is as follows:

`        String address = ((String) configuration.get(SwitchThingHandler.SWITCH_GA));`

with configuration being a Configuration instance.

2016-04-30 11:32:25.432 [DEBUG] [e.s.m.t.i.GenericThingProvider:228  ] - Read things from model 'knx.things'

!ENTRY org.eclipse.equinox.cm 4 0 2016-04-30 11:32:25.532
!MESSAGE org.eclipse.smarthome.config.core.Configuration.get(Ljava/lang/String;)Ljava/lang/Object;
!STACK 0
java.lang.NoSuchMethodError: org.eclipse.smarthome.config.core.Configuration.get(Ljava/lang/String;)Ljava/lang/Object;
	at org.openhab.binding.knx.internal.factory.KNXHandlerFactory.getSwitchThingUID(KNXHandlerFactory.java:192)
	at org.openhab.binding.knx.internal.factory.KNXHandlerFactory.createThing(KNXHandlerFactory.java:97)
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider.getThingFromThingHandlerFactory(GenericThingProvider.java:429)
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider.getThingFromThingHandlerFactories(GenericThingProvider.java:419)
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider.createThing(GenericThingProvider.java:330)

**Comment by kaikreuzer** [comment]
Looks as if this is due to https://github.com/eclipse/smarthome/pull/1433 - could you adapt the KNX binding accordingly? Thanks!

**Comment by kgoderis** [comment]
I propose to continue the discussion in @1433 because it is not resolved. the KNX binding was already using String keys, so it was/is not necessarily related to that binding

**Comment by kaikreuzer** [comment]
I just noticed that it is unlikely related to #1433, since this was not yet even in the stable ESH release and thus not part of OH2.
It rather sounds to me like a some broken binaries - we had that recently in another situation with ZWave.
I am just running a new stable build (which then includes #1433) and we can see if this error is solved then.

**Comment by kgoderis** [comment]
Ok tx - hope you can resolve the issue quickly as it blocks everything for the time being

**Comment by kaikreuzer** [comment]
It seems to be resolved. I just tried a OH IDE (with latest target platform and without ESH bundles in the workspace) and am able to run the KNX bindings without this exception.

If the problem still exists for you, feel free to re-open the issue!

**Comment by lsafelix75** [comment]
OK, great to hear that.  How should i fix this on Distro? :)  The Eclipse IDE that i am running seems ok but not on distro build #273

**Comment by lsafelix75** [comment]
Unfortunately,  with the latest offline distro #276. I am still hitting the same issue: 

2016-05-02 13:25:07.503 [ERROR] [ome.core.thing.internal.ThingManager] - Exception occured while initializing handler of thing 'xxxxxx:broker:mygateway1': java.lang.NoSuchMethodError: org.eclipse.smarthome.config.core.Configuration.get(Ljava/lang/Object;)Ljava/lang/Object;
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: org.eclipse.smarthome.config.core.Configuration.get(Ljava/lang/Object;)Ljava/lang/Object;
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)[:1.8.0]
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)[:1.8.0]
	at org.eclipse.smarthome.core.common.SafeMethodCaller.callAsynchronous(SafeMethodCaller.java:179)[96:org.eclipse.smarthome.core:0.8.0.201604302105]
	at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:72)[96:org.eclipse.smarthome.core:0.8.0.201604302105]
	at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:56)[96:org.eclipse.smarthome.core:0.8.0.201604302105]
	at org.eclipse.smarthome.core.thing.internal.ThingManager$7.run(ThingManager.java:659)[102:org.eclipse.smarthome.core.thing:0.8.0.201604302105]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)[:1.8.0]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)[:1.8.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0]
	at java.lang.Thread.run(Thread.java:744)[:1.8.0]
Caused by: java.lang.NoSuchMethodError: org.eclipse.smarthome.config.core.Configuration.get(Ljava/lang/Object;)Ljava/lang/Object;
	at org.openhab.binding.talentswitchmqtt.handler.BrokerHandler.initialize(BrokerHandler.java:82)
	at org.eclipse.smarthome.core.thing.internal.ThingManager$7$1.call(ThingManager.java:662)
	at org.eclipse.smarthome.core.thing.internal.ThingManager$7$1.call(ThingManager.java:1)
	at org.eclipse.smarthome.core.common.SafeMethodCaller$CallableWrapper.call(SafeMethodCaller.java:170)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0]
	... 3 more

**Comment by maggu2810** [comment]
So, it needs to be checked why the distro packs a talentswitchmqtt binding that is using an older targetplatform.
I don't think that this is ESH related anymore, if the bundles has been build against the correct version the problem should not occur. Sure, the change has been introduced in the ESH framework, but such changes could be done all the time in the development cycle.

**Comment by kgoderis** [comment]
Solved with the 20160430 snapshot.

**Comment by kaikreuzer** [comment]
Glad to hear, thanks for the feedback!

**Comment by thopiekar** [comment]
Is there a way to reinstall the runtime like a binding?

I've done:
```
feature:uninstall openhab-runtime-base
feature:repo-refresh
feature:install openhab-runtime-base
```
.. but it does not take any effect.

**Comment by cdjackson** [comment]
You need to download the runtime (i.e. the OH2 distribution) and reinstall it manually.

**Comment by thopiekar** [comment]
Ok, thank you for the quick reply :+1:
