### ISSUE TITLE
Designer 0.8.0 won't start - stack trace

### ISSUE THREAD

**Issue by xsnrg** [eclipse/smarthome#1442]
version:  Current nightly snapshot
OS/Arch: Linux/64 - likely broken elsewhere too
possible cause: xtext 2.9.2 changes

current log attached.
[1462021857850.txt](https://github.com/eclipse/smarthome/files/243614/1462021857850.txt)

**Comment by xsnrg** [comment]
latest still will not start, exception is a bit different:

```
!ENTRY org.eclipse.osgi 4 0 2016-05-07 11:21:38.453
!MESSAGE Application error
!STACK 1
java.lang.IllegalStateException: Unable to acquire application service. Ensure that the org.eclipse.core.runtime bundle is resolved and started (see config.ini).
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:78)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:382)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:236)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1438)
```

**Comment by maggu2810** [comment]
The error is above that lines.
I think the first log file shows it already.
I see the error, too. But I don't know anything about that Eclipse Product setup.

**Comment by xsnrg** [comment]
designer still is not working for me.  I am trying .9 now, so will open a new ticket
