### ISSUE TITLE
jetty 2 not supporting events?

### ISSUE THREAD

**Issue by cdjackson** [eclipse/smarthome#1462]
I'm currently seeing the following errors with both PaperUI and HABmin - it seems to occur a number of times per second and seems to be choking the system.  This is using the runtime downloaded yesterday with very few additional bundles (basically just ZWave).

If I run PaperUI the errors start, and when I remove PaperUI from the browser, they stop (same with HABmin but I removed HABmin bundle to have a clean install and make sure it wasn't that).

```
17:39:30.897 [WARN ] [org.eclipse.jetty.server.HttpChannel] - /rest/events
javax.servlet.ServletException: javax.servlet.ServletException: java.lang.UnsupportedOperationException: Asynchronous processing not supported on Servlet 2.x container.
        at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:88)[166:org.ops4j.pax.web.pax-web-jetty:4.2.4]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)[81:org.eclipse.jetty.server:9.2.14.v20151106]
        at org.eclipse.jetty.server.Server.handle(Server.java:499)[81:org.eclipse.jetty.server:9.2.14.v20151106]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)[81:org.eclipse.jetty.server:9.2.14.v20151106]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)[81:org.eclipse.jetty.server:9.2.14.v20151106]
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)[73:org.eclipse.jetty.io:9.2.14.v20151106]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)[84:org.eclipse.jetty.util:9.2.14.v20151106]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)[84:org.eclipse.jetty.util:9.2.14.v20151106]
        at java.lang.Thread.run(Thread.java:745)[:1.8.0_60]
Caused by: javax.servlet.ServletException: java.lang.UnsupportedOperationException: Asynchronous processing not supported on Servlet 2.x container.
        at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:489)[151:org.glassfish.jersey.containers.jersey-container-servlet-core:2.22.2]
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)[151:org.glassfish.jersey.containers.jersey-container-servlet-core:2.22.2]
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)[151:org.glassfish.jersey.containers.jersey-container-servlet-core:2.22.2]
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)[151:org.glassfish.jersey.containers.jersey-container-servlet-core:2.22.2]
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)[151:org.glassfish.jersey.containers.jersey-container-servlet-core:2.22.2]
        at com.eclipsesource.jaxrs.publisher.internal.ServletContainerBridge.service(ServletContainerBridge.java:76)[15:com.eclipsesource.jaxrs.publisher:5.3.1.201602281253]
```

**Comment by maggu2810** [comment]
See #1448 and links.
Can you test if you are using this patch already?

**Comment by cdjackson** [comment]
Thanks. This is running the runtime from CBs from yesterday so it seems the patch is probably not included (?)…

This seems quite a severe issue as it makes the CPU go to 100% on my NAS...

**Comment by maggu2810** [comment]
You can also set the start-level of all jersey bundles (IIRC version 2.22.2) to 30 manually and restart your Karaf container.
I added the command lines to community.openhab.org but there seems to be something wrong with the server ATM.

**Comment by cdjackson** [comment]
Well, it seemed to work, but I’m a bit confused… I changed the start level of the bundles, but they seemed to disappear from the ‘list’ command. When I restart the container though, I don’t get the error any more, so clearly they are running...

**Comment by maggu2810** [comment]
bundle:list -t 0

**Comment by cdjackson** [comment]
Ta - that sorts it :)

So, yep, it seems to solve the issue here...
