### ISSUE TITLE
Rule failure

### ISSUE THREAD

**Issue by feens** [eclipse/smarthome#1517]
Anytime a rule is to be run in OH2, I'm getting a NPE exception.  I even cleared out my rules folder and just put in one super simple rule that merely logs.

Here's the log:

```
14:56:17.396 [ERROR] [ore.internal.events.OSGiEventManager] - Dispatching/filtering event for subscriber 'org.eclipse.smarthome.core.events.EventSubscriber' failed: java.lang.NullPointerException
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)[:1.8.0_65]
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)[:1.8.0_65]
	at org.eclipse.smarthome.core.common.SafeMethodCaller.callAsynchronous(SafeMethodCaller.java:179)[97:org.eclipse.smarthome.core:0.8.0.201605141733]
	at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:72)[97:org.eclipse.smarthome.core:0.8.0.201605141733]
	at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:56)[97:org.eclipse.smarthome.core:0.8.0.201605141733]
	at org.eclipse.smarthome.core.internal.events.OSGiEventManager.dispatchESHEvent(OSGiEventManager.java:188)[97:org.eclipse.smarthome.core:0.8.0.201605141733]
	at org.eclipse.smarthome.core.internal.events.OSGiEventManager.handleEvent(OSGiEventManager.java:163)[97:org.eclipse.smarthome.core:0.8.0.201605141733]
	at org.eclipse.smarthome.core.internal.events.OSGiEventManager.handleEvent(OSGiEventManager.java:146)[97:org.eclipse.smarthome.core:0.8.0.201605141733]
	at org.apache.felix.eventadmin.impl.handler.EventHandlerProxy.sendEvent(EventHandlerProxy.java:415)[3:org.apache.karaf.services.eventadmin:4.0.4]
	at org.apache.felix.eventadmin.impl.tasks.HandlerTask.run(HandlerTask.java:90)[3:org.apache.karaf.services.eventadmin:4.0.4]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_65]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_65]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_65]
Caused by: java.lang.NullPointerException
	at org.eclipse.smarthome.model.rule.runtime.internal.engine.RuleContextHelper.getContext(RuleContextHelper.java:64)[122:org.eclipse.smarthome.model.rule.runtime:0.8.0.201605141733]
	at org.eclipse.smarthome.model.rule.runtime.internal.engine.RuleEngineImpl.executeRule(RuleEngineImpl.java:304)[122:org.eclipse.smarthome.model.rule.runtime:0.8.0.201605141733]
	at org.eclipse.smarthome.model.rule.runtime.internal.engine.RuleEngineImpl.executeRules(RuleEngineImpl.java:329)[122:org.eclipse.smarthome.model.rule.runtime:0.8.0.201605141733]
	at org.eclipse.smarthome.model.rule.runtime.internal.engine.RuleEngineImpl.stateChanged(RuleEngineImpl.java:198)[122:org.eclipse.smarthome.model.rule.runtime:0.8.0.201605141733]
	at org.eclipse.smarthome.core.items.GenericItem.notifyListeners(GenericItem.java:220)[97:org.eclipse.smarthome.core:0.8.0.201605141733]
	at org.eclipse.smarthome.core.items.GenericItem.setState(GenericItem.java:195)[97:org.eclipse.smarthome.core:0.8.0.201605141733]
	at org.eclipse.smarthome.core.internal.items.ItemUpdater.receiveUpdate(ItemUpdater.java:70)[97:org.eclipse.smarthome.core:0.8.0.201605141733]
	at org.eclipse.smarthome.core.items.events.AbstractItemEventSubscriber.receive(AbstractItemEventSubscriber.java:44)[97:org.eclipse.smarthome.core:0.8.0.201605141733]
	at org.eclipse.smarthome.core.internal.events.OSGiEventManager$1.call(OSGiEventManager.java:192)[97:org.eclipse.smarthome.core:0.8.0.201605141733]
	at org.eclipse.smarthome.core.internal.events.OSGiEventManager$1.call(OSGiEventManager.java:1)[97:org.eclipse.smarthome.core:0.8.0.201605141733]
	at org.eclipse.smarthome.core.common.SafeMethodCaller$CallableWrapper.call(SafeMethodCaller.java:170)[97:org.eclipse.smarthome.core:0.8.0.201605141733]
	... 4 more
```

**Comment by kaikreuzer** [comment]
NPE is definitely not good. In this line, it tries to log a warning like "Variable '{}' on rule file '{}' cannot be initialized with value '{}': {}".

Could you please also paste your "super simple rule that merely logs", so that I can easily reproduce it?

**Comment by feens** [comment]
I did manage to fix this, and I'm pretty sure it's going to be difficult to reproduce.  But here's some more info.  The rule looked like this:

`
rule "Test"
when
    Switch_Family_Room changed
then
    logInfo(SWFR, "This is a rule")
end
`

However, the error was originally firing when any of my pre-existing rules fired.  I had everything working, but was adding some new items to the system and ended up needing to restart and that's when the issues began.  I originally had the "script interpreter can not be obtained" errors for them, so I upgraded my OH install and was greeted with this error.  In order to fix it, I ended up first moving all of my rule files.  When that didn't work, I restarted again with them removed, and that's what got things going.  I've since added them back, one at a time, and they all seem to be working.

It's almost like some bad data got stuck in the rule pipeline.  I know that's not very helpful for hunting down the bug...and feel free to close it now that it's working again.

**Comment by maggu2810** [comment]
That sound like the comment of @shorty707 here https://github.com/eclipse/smarthome/issues/1393#issuecomment-219270462

> I took a while to find because altering the file - or even delete the whole rule file did not stop the rule to be executed in openhab... that seemed very odd and only a restart of openhab made it work.... 
but nevertheless ... that issue here I think is now osolete?

**Comment by kaikreuzer** [comment]
Yes, but imho we should in any case fix the NPE that occurred here.

**Comment by s-simma** [comment]
I have the same problem.
Using the latest snapshot with my old "conf" folder i get the same error. The last snapshot where everything is ok is from april. Nothing changed in my configuration. Simply unziped the snapshot and replaced the "conf" folder.

Even this simple rule throws an exception. Some are ok. Some not.

var Number Window_FF_OfficeG_ok = 0

rule "window2 state"
    when 
        Item Window_FF_OfficeG received update  
    then
        Window_FF_OfficeG_ok = 1
end
-----------------

2016-05-22 08:30:36.449 [INFO ] [ome.event.GroupItemStateChangedEvent] - gContact changed from NULL to OPEN through Window_FF_OfficeG
2016-05-22 08:30:36.450 [ERROR] [ore.internal.events.OSGiEventManager] - Dispatching/filtering event for subscriber 'org.eclipse.smarthome.core.events.EventSubscriber' failed: java.lang.NullPointerException
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)[:1.8.0_65]
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)[:1.8.0_65]
	at org.eclipse.smarthome.core.common.SafeMethodCaller.callAsynchronous(SafeMethodCaller.java:179)[98:org.eclipse.smarthome.core:0.8.0.201605191852]
	at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:72)[98:org.eclipse.smarthome.core:0.8.0.201605191852]
	at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:56)[98:org.eclipse.smarthome.core:0.8.0.201605191852]
	at org.eclipse.smarthome.core.internal.events.OSGiEventManager.dispatchESHEvent(OSGiEventManager.java:188)[98:org.eclipse.smarthome.core:0.8.0.201605191852]
	at org.eclipse.smarthome.core.internal.events.OSGiEventManager.handleEvent(OSGiEventManager.java:163)[98:org.eclipse.smarthome.core:0.8.0.201605191852]
	at org.eclipse.smarthome.core.internal.events.OSGiEventManager.handleEvent(OSGiEventManager.java:146)[98:org.eclipse.smarthome.core:0.8.0.201605191852]
	at org.apache.felix.eventadmin.impl.handler.EventHandlerProxy.sendEvent(EventHandlerProxy.java:415)[3:org.apache.karaf.services.eventadmin:4.0.4]
	at org.apache.felix.eventadmin.impl.tasks.HandlerTask.run(HandlerTask.java:90)[3:org.apache.karaf.services.eventadmin:4.0.4]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_65]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_65]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_65]
Caused by: java.lang.NullPointerException
	at org.eclipse.smarthome.model.rule.runtime.internal.engine.RuleContextHelper.getContext(RuleContextHelper.java:64)[123:org.eclipse.smarthome.model.rule.runtime:0.8.0.201605191852]
	at org.eclipse.smarthome.model.rule.runtime.internal.engine.RuleEngineImpl.executeRule(RuleEngineImpl.java:304)[123:org.eclipse.smarthome.model.rule.runtime:0.8.0.201605191852]
	at org.eclipse.smarthome.model.rule.runtime.internal.engine.RuleEngineImpl.executeRules(RuleEngineImpl.java:313)[123:org.eclipse.smarthome.model.rule.runtime:0.8.0.201605191852]
	at org.eclipse.smarthome.model.rule.runtime.internal.engine.RuleEngineImpl.stateUpdated(RuleEngineImpl.java:209)[123:org.eclipse.smarthome.model.rule.runtime:0.8.0.201605191852]

**Comment by feens** [comment]
A bit more info on this.  I've noticed that any time I restart OH2 with my rules in place, I'll get that error.  If I move out my rules, start OH2, and then move them back in after it's running, all is well.

**Comment by smar000** [comment]
I can also confirm that I'm seeing exactly the same behaviour as @feens. I wonder though why other users don't appear to be reporting the same issue and whether there is some other underlying cause in our specific cases - i.e. version of linux/jre etc?

**Comment by s-simma** [comment]
The problem seems to be a startup problem.
I have the same problem running OH in the IDE.

One way where all rules work as expected:
1. stop debuger
2. delete rule file (in IDE)
3. start debuger
4. copy rule file during debugger running into IDE
-> all rules work fine.
But restarting the debugger gives again NPE.

**Comment by feens** [comment]
I had some time so I did a bit more digging and was able to isolate things a bit more.

The following rule works when present during restart:

`
rule "Family Room Switch"
when
        Item Switch_Family_Room changed or
        Item Switch_Family_Room received command
then
        logInfo("FR_Switch", "Family room switch turned "+Switch_Family_Room.state)
        if(Switch_Family_Room.state == ON){
                sendCommand(Outlet_Family_Room_2, ON)
                sendCommand(Outlet_Family_Room_1, ON)
                sendCommand(Outlet_Family_Room_3, ON)
        }else{
                sendCommand(Outlet_Family_Room_2, OFF)
                sendCommand(Outlet_Family_Room_1, OFF)
                sendCommand(Outlet_Family_Room_3, OFF)
        }
end
`


The following does not:

`
import org.joda.time.*
import org.eclipse.smarthome.core.types.RefreshType

var boolean turningKitchenOn = false
var boolean turningKitchenOff = false
var boolean refreshKitchenAnyway = false

var boolean turningTableOn = false
var boolean turningTableOff = false
var boolean refreshTableAnyway = false

when
        Item Dimmer_Kitchen changed
then
        logInfo("Dimmer", "Dimmer changed to "+Dimmer_Kitchen.state)

        if(!turningKitchenOn && previousState < Dimmer_Kitchen.state){
                sendCommand(Dimmer_Sink, ON)
                turningKitchenOn = true
                logInfo("DDT", "Turning kitchen on")
        }else if(turningKitchenOn == true && Dimmer_Kitchen.state > previousState){
                logInfo("DDT", "Double tap kitchen on")
                turningKitchenOn = false
#               sendCommand(Dimmer_Island, ON)
        }else if(!turningKitchenOff && previousState > Dimmer_Kitchen.state){
                sendCommand(Dimmer_Sink, OFF)
                turningKitchenOff = true
                logInfo("DDT", "Turning kitchen off")
        }else if(turningKitchenOff == true && Dimmer_Kitchen.state < previousState){
                logInfo("DDT", "Double tap kitchen off")
                turningKitchenOff = false
#               sendCommand(Dimmer_Island, OFF)
        } else {
                refreshKitchenAnyway = true
        }

        if(turningKitchenOn || turningKitchenOff || refreshKitchenAnyway){
                var Timer timerResetDimmer = createTimer(now.plusSeconds(2)) [|
                        turningKitchenOn = false
                        turningKitchenOff = false
                        refreshKitchenAnyway = false
                ]

                var Timer timerRefreshDimmer = createTimer(now.plusSeconds(5)) [|
                        logInfo("Refresh", "Refresh dimmer")
#                       sendCommand(Dimmer_Kitchen, RefreshType.REFRESH)
                ]
        }
end
`

And removing the import statements doesn't seem to make a difference.  Hopefully that's helpful.

**Comment by maggu2810** [comment]
Why do you start three of your lines with a hash symbol? Has this bash based comment style been allowed?

**Comment by feens** [comment]
Well, that commenting style seems to work.  To be honest, I'm not sure where I picked it up (aside from being a Ruby programmer).  I probably should look at changing those though...but I don't think they're the cause of the errors here.

**Comment by s-simma** [comment]
@kaikreuzer. Could it be that rule engine is startet before all items/things are initalized?

**Comment by kaikreuzer** [comment]
Yes, that's the normal behaviour. The rule engine can be there before the items are created.
But it listens to newly added items and should re-run any startup rule that previously failed because of missing items.

**Comment by s-simma** [comment]
@kaikreuzer 
How to reproduce this problem:
1. Install latest offline version as demo
2. put the following rule into rule file
rule "test"
	when
		Item Scene_General changed
	then
    		var Number test1 = 0
end
3. Goto "Dicrete widgets" and change "TV/DINNER/READING"

**Comment by kaikreuzer** [comment]
@s-simma 
```
09:22:16.976 [DEBUG] [ntime.internal.engine.RuleEngineImpl] - Executing rule 'test 2'
09:22:16.977 [INFO ] [marthome.event.ItemStateChangedEvent] - Scene_General changed from 2 to 1
```
Not possible to reproduce for me :-/

**Comment by derkens** [comment]
I found this issue when having the same problem, I remembered before the errors, I have changed the system locale. 
I'm running archlinuxarm on a raspberrypi 2 with OH2 Beta 3.
I had two locales in /etc/locale.gen:
`en_US.UTF-8 UTF-8`
`nl_NL.UTF-8 UTF-8`
I have removed `nl_NL.UTF-8 UTF-8`, regenerated locales, and restarted OH2.
I now no longer have the errors.
My NPE was right after an update of the astro binding (sun elevation).
This also could be totally unrelated ofcourse... :smile:

**Comment by s-simma** [comment]
@kaikreuzer 
updated yesterday to the latest version -> no idea what happened -> problem is gone. Can't reproduce it any more too.

**Comment by feens** [comment]
I update today, same results.  I think it's fair to mark this as closed.

**Comment by pabloNZ** [comment]
I'm having this issue occur on the latest snapshot #405. Can anyone else confirm?

**Comment by kaikreuzer** [comment]
@pabloNZ If you do, please enter a new issue with a details exception. Best if you can provide a modified demo.rules file with which it can be reproduced.
