### ISSUE TITLE
Issues installing Eclipse SmartHome IDE

### ISSUE THREAD

**Issue by apuder** [eclipse/smarthome#1564]
I followed these instructions:
http://www.eclipse.org/smarthome/documentation/development/ide.html

But at the end I have compile errors:
`
47544 [main] ERROR mf.mwe2.launch.runtime.Mwe2Launcher  - Problems running workflow all: 
[ERROR]: GeneratorException: (Element: -UNKNOWN-; Reported by: LazyGenerator)
	 java.lang.IllegalStateException: Duplicate adapter
	at org.eclipse.xtext.xtext.RuleNames.installAdapterIfMissing(RuleNames.java:180)
	at org.eclipse.xtext.xtext.RuleNames.<init>(RuleNames.java:165)
	at org.eclipse.xtext.xtext.RuleNames.getRuleNames(RuleNames.java:94)
	at org.eclipse.xtext.xtext.RuleNames.ensureAdapterInstalled(RuleNames.java:118)
	at org.eclipse.xtext.generator.grammarAccess.GrammarAccessFragment.generate(GrammarAccessFragment.java:84)
	at org.eclipse.xtext.generator.DefaultGeneratorFragment.generate(DefaultGeneratorFragment.java:167)
	at org.eclipse.xtext.generator.CompositeGeneratorFragment.generate(CompositeGeneratorFragment.java:163)
	at org.eclipse.smarthome.model.lazygen.LazyLanguageConfig.generate(LazyLanguageConfig.java:71)
	at org.eclipse.xtext.generator.Generator.generate(Generator.java:600)
	at org.eclipse.xtext.generator.Generator.invokeInternal(Generator.java:178)
	at org.eclipse.smarthome.model.lazygen.LazyGenerator.invokeInternal(LazyGenerator.java:32)
	at org.eclipse.emf.mwe.core.lib.AbstractWorkflowComponent.invoke(AbstractWorkflowComponent.java:126)
	at org.eclipse.emf.mwe.core.lib.Mwe2Bridge.invoke(Mwe2Bridge.java:34)
	at org.eclipse.emf.mwe.core.lib.AbstractWorkflowComponent.invoke(AbstractWorkflowComponent.java:201)
	at org.eclipse.emf.mwe2.runtime.workflow.AbstractCompositeWorkflowComponent.invoke(AbstractCompositeWorkflowComponent.java:35)
	at org.eclipse.emf.mwe2.runtime.workflow.AbstractCompositeWorkflowComponent.invoke(AbstractCompositeWorkflowComponent.java:35)
	at org.eclipse.emf.mwe2.runtime.workflow.Workflow.run(Workflow.java:19)
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:102)
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:62)
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:52)
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Launcher.run(Mwe2Launcher.java:78)
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Launcher.main(Mwe2Launcher.java:36)

[ERROR]: GeneratorException: (Element: -UNKNOWN-; Reported by: LazyGenerator)
	 java.lang.NullPointerException
	at org.eclipse.xtext.xtext.RuleNames.getAntlrRuleName(RuleNames.java:205)
	at org.eclipse.xtext.xtext.FlattenedGrammarAccess.copyRuleStubs(FlattenedGrammarAccess.java:462)
	at org.eclipse.xtext.xtext.FlattenedGrammarAccess.<init>(FlattenedGrammarAccess.java:99)
	at org.eclipse.xtext.serializer.analysis.GrammarPDAProvider.getGrammarPDAs(GrammarPDAProvider.java:181)
	at org.eclipse.xtext.serializer.analysis.ContextPDAProvider.getContextPDAs(ContextPDAProvider.java:193)
	at org.eclipse.xtext.serializer.analysis.ContextTypePDAProvider.getContextTypePDAs(ContextTypePDAProvider.java:254)
	at org.eclipse.xtext.serializer.analysis.SyntacticSequencerPDAProvider.getSyntacticSequencerPDAs(SyntacticSequencerPDAProvider.java:597)
	at org.eclipse.xtext.serializer.analysis.SemanticSequencerNfaProvider.getSemanticSequencerNFAs(SemanticSequencerNfaProvider.java:242)
	at org.eclipse.xtext.serializer.analysis.GrammarConstraintProvider.getConstraints(GrammarConstraintProvider.java:519)
	at org.eclipse.xtext.xtext.generator.serializer.SemanticSequencerExtensions.getGrammarConstraints(SemanticSequencerExtensions.java:142)
	at org.eclipse.xtext.xtext.generator.serializer.SerializerFragment2.generateAbstractSemanticSequencer(SerializerFragment2.java:497)
	at org.eclipse.xtext.xtext.generator.serializer.SerializerFragment2.generate(SerializerFragment2.java:244)
	at org.eclipse.xtext.generator.serializer.SerializerFragment.generate(SerializerFragment.java:176)
	at org.eclipse.xtext.generator.Xtend2GeneratorFragment.generate(Xtend2GeneratorFragment.java:75)
	at org.eclipse.xtext.generator.Xtend2GeneratorFragment.generate(Xtend2GeneratorFragment.java:68)
	at org.eclipse.xtext.generator.DefaultGeneratorFragment.generate(DefaultGeneratorFragment.java:167)
	at org.eclipse.xtext.generator.serializer.SerializerFragment.generate(SerializerFragment.java:159)
	at org.eclipse.xtext.generator.CompositeGeneratorFragment.generate(CompositeGeneratorFragment.java:163)
	at org.eclipse.smarthome.model.lazygen.LazyLanguageConfig.generate(LazyLanguageConfig.java:71)
	at org.eclipse.xtext.generator.Generator.generate(Generator.java:600)
	at org.eclipse.xtext.generator.Generator.invokeInternal(Generator.java:178)
	at org.eclipse.smarthome.model.lazygen.LazyGenerator.invokeInternal(LazyGenerator.java:32)
	at org.eclipse.emf.mwe.core.lib.AbstractWorkflowComponent.invoke(AbstractWorkflowComponent.java:126)
	at org.eclipse.emf.mwe.core.lib.Mwe2Bridge.invoke(Mwe2Bridge.java:34)
	at org.eclipse.emf.mwe.core.lib.AbstractWorkflowComponent.invoke(AbstractWorkflowComponent.java:201)
	at org.eclipse.emf.mwe2.runtime.workflow.AbstractCompositeWorkflowComponent.invoke(AbstractCompositeWorkflowComponent.java:35)
	at org.eclipse.emf.mwe2.runtime.workflow.AbstractCompositeWorkflowComponent.invoke(AbstractCompositeWorkflowComponent.java:35)
	at org.eclipse.emf.mwe2.runtime.workflow.Workflow.run(Workflow.java:19)
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:102)
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:62)
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:52)
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Launcher.run(Mwe2Launcher.java:78)
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Launcher.main(Mwe2Launcher.java:36)
`

**Comment by maggu2810** [comment]
See #1505

**Comment by apuder** [comment]
Thanks. That worked.
