### ISSUE TITLE
[Sonos] Fatal error playlist channel

### ISSUE THREAD

**Issue by rtvb** [eclipse/smarthome#1600]
I tried to play playlist "Robert" for a String item:

    sendCommand(Sonos_Living_PlayList, "Robert")

version:

    194 | Active   |  80 | 0.8.0.201605191852    | org.eclipse.smarthome.binding.sonos

debugging:

    log:set DEBUG org.eclipse.smarthome.binding.sonos

logging:
```
06:37:44.953 [INFO ] [smarthome.event.ItemCommandEvent    ] - Item 'Sonos_Living_PlayList' received command Robert
[Fatal Error] :1:1: Premature end of file.
06:37:44.997 [DEBUG] [inding.sonos.internal.SonosXMLParser] - Failed to parse embeded
org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1239)[:1.8.0_91]
	at org.eclipse.smarthome.binding.sonos.internal.SonosXMLParser.getResourceMetaData(SonosXMLParser.java:132)[194:org.eclipse.smarthome.binding.sonos:0.8.0.201605191852]
	at org.eclipse.smarthome.binding.sonos.internal.SonosXMLParser$EntryHandler.endElement(SonosXMLParser.java:338)[194:org.eclipse.smarthome.binding.sonos:0.8.0.201605191852]
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)[:1.8.0_91]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1783)[:1.8.0_91]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2970)[:1.8.0_91]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)[:1.8.0_91]
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:118)[:1.8.0_91]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)[:1.8.0_91]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)[:1.8.0_91]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)[:1.8.0_91]
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)[:1.8.0_91]
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)[:1.8.0_91]
	at org.eclipse.smarthome.binding.sonos.internal.SonosXMLParser.getEntriesFromString(SonosXMLParser.java:109)[194:org.eclipse.smarthome.binding.sonos:0.8.0.201605191852]
	at org.eclipse.smarthome.binding.sonos.handler.ZonePlayerHandler.getEntries(ZonePlayerHandler.java:987)[194:org.eclipse.smarthome.binding.sonos:0.8.0.201605191852]
	at org.eclipse.smarthome.binding.sonos.handler.ZonePlayerHandler.getPlayLists(ZonePlayerHandler.java:947)[194:org.eclipse.smarthome.binding.sonos:0.8.0.201605191852]
	at org.eclipse.smarthome.binding.sonos.handler.ZonePlayerHandler.playPlayList(ZonePlayerHandler.java:2172)[194:org.eclipse.smarthome.binding.sonos:0.8.0.201605191852]
	at org.eclipse.smarthome.binding.sonos.handler.ZonePlayerHandler.handleCommand(ZonePlayerHandler.java:268)[194:org.eclipse.smarthome.binding.sonos:0.8.0.201605191852]
	at org.eclipse.smarthome.core.thing.internal.ThingManager$2.call(ThingManager.java:371)[102:org.eclipse.smarthome.core.thing:0.8.0.201605191852]
	at org.eclipse.smarthome.core.thing.internal.ThingManager$2.call(ThingManager.java:1)[102:org.eclipse.smarthome.core.thing:0.8.0.201605191852]
	at org.eclipse.smarthome.core.common.SafeMethodCaller$CallableWrapper.call(SafeMethodCaller.java:170)[96:org.eclipse.smarthome.[Fatal Error] :1:1: Premature end of file.
core:0.8.0.201605191852]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_91]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_91]
06:37:45.000 [DEBUG] [inding.sonos.internal.SonosXMLParser] - Failed to parse embeded
org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1239)[:1.8.0_91]
	at org.eclipse.smarthome.binding.sonos.internal.SonosXMLParser.getResourceMetaData(SonosXMLParser.java:132)[194:org.eclipse.smarthome.binding.sonos:0.8.0.201605191852]
	at org.eclipse.smarthome.binding.sonos.internal.SonosXMLParser$EntryHandler.endElement(SonosXMLParser.java:338)[194:org.eclipse.smarthome.binding.sonos:0.8.0.201605191852]
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)[:1.8.0_91]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1783)[:1.8.0_91]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2970)[:1.8.0_91]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)[:1.8.0_91]
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:118)[:1.8.0_91]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)[:1.8.0_91]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)[:1.8.0_91]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)[:1.8.0_91]
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)[:1.8.0_91]
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)[:1.8.0_91]
	at org.eclipse.smarthome.binding.sonos.internal.SonosXMLParser.getEntriesFromString(SonosXMLParser.java:109)[194:org.eclipse.smarthome.binding.sonos:0.8.0.201605191852]
	at org.eclipse.smarthome.binding.sonos.handler.ZonePlayerHandler.getEntries(ZonePlayerHandler.java:987)[194:org.eclipse.smarthome.binding.sonos:0.8.0.201605191852]
	at org.eclipse.smarthome.binding.sonos.handler.ZonePlayerHandler.getPlayLists(ZonePlayerHandler.java:947)[194:org.eclipse.smarthome.binding.sonos:0.8.0.201605191852]
	at org.eclipse.smarthome.binding.sonos.handler.ZonePlayerHandler.playPlayList(ZonePlayerHandler.java:2172)[194:org.eclipse.smarthome.binding.sonos:0.8.0.201605191852]
	at org.eclipse.smarthome.binding.sonos.handler.ZonePlayerHandler.handleCommand(ZonePlayerHandler.java:268)[194:org.eclipse.smarthome.binding.sonos:0.8.0.201605191852]
	at org.eclipse.smarthome.core.thing.internal.ThingManager$2.call(ThingManager.java:371)[102:org.eclipse.smarthome.core.thing:0.8.0.201605191852]
	at org.eclipse.smarthome.core.thing.internal.ThingManager$2.call(ThingManager.java:1)[102:org.eclipse.smarthome.core.thing:0.8.0.201605191852]
	at org.eclipse.smarthome.core.common.SafeMethodCaller$CallableWrapper.call(SafeMethodCaller.java:170)[96:org.eclipse.smarthome.core:0.8.0.201605191852]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_91]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_91]
[Fatal Error] :1:1: Premature end of file.
06:37:45.002 [DEBUG] [inding.sonos.internal.SonosXMLParser] - Failed to parse embeded
org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1239)[:1.8.0_91]
	at org.eclipse.smarthome.binding.sonos.internal.SonosXMLParser.getResourceMetaData(SonosXMLParser.java:132)[194:org.eclipse.smarthome.binding.sonos:0.8.0.201605191852]
	at org.eclipse.smarthome.binding.sonos.internal.SonosXMLParser$EntryHandler.endElement(SonosXMLParser.java:338)[194:org.eclipse.smarthome.binding.sonos:0.8.0.201605191852]
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)[:1.8.0_91]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1783)[:1.8.0_91]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2970)[:1.8.0_91]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)[:1.8.0_91]
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:118)[:1.8.0_91]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)[:1.8.0_91]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)[:1.8.0_91]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)[:1.8.0_91]
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)[:1.8.0_91]
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)[:1.8.0_91]
	at org.eclipse.smarthome.binding.sonos.internal.SonosXMLParser.getEntriesFromString(SonosXMLParser.java:109)[194:org.eclipse.smarthome.binding.sonos:0.8.0.201605191852]
	at org.eclipse.smarthome.binding.sonos.handler.ZonePlayerHandler.getEntries(ZonePlayerHandler.java:987)[194:org.eclipse.smarthome.binding.sonos:0.8.0.201605191852]
	at org.eclipse.smarthome.binding.sonos.handler.ZonePlayerHandler.getPlayLists(ZonePlayerHandler.java:947)[194:org.eclipse.smarthome.binding.sonos:0.8.0.201605191852]
	at org.eclipse.smarthome.binding.sonos.handler.ZonePlayerHandler.playPlayList(ZonePlayerHandler.java:2172)[194:org.eclipse.smarthome.binding.sonos:0.8.0.201605191852]
	at org.eclipse.smarthome.binding.sonos.handler.ZonePlayerHandler.handleCommand(ZonePlayerHandler.java:268)[194:org.eclipse.smarthome.binding.sonos:0.8.0.201605191852]
	at org.eclipse.smarthome.core.thing.internal.ThingManager$2.call(ThingManager.java:371)[102:org.eclipse.smarthome.core.thing:0.8.0.201605191852]
	at org.eclipse.smarthome.core.thing.internal.ThingManager$2.call(ThingManager.java:1)[102:org.eclipse.smarthome.core.thing:0.8.0.201605191852]
	at org.eclipse.smarthome.core.common.SafeMethodCaller$CallableWrapper.call(SafeMethodCaller.java:170)[96:org.eclipse.smarthome.core:0.8.0.201605191852]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_91]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_91]
```

**Comment by kgoderis** [comment]
This is similar to https://github.com/eclipse/smarthome/issues/862 which was fixed by https://github.com/eclipse/smarthome/pull/1364

Is "Robert" is non-empt playlist that was duly defined in the Sonos Controller?

I am not sure where we best handle this e.g. in the SonosXMLParser or before its get called (as in the PR 1364), because the XML string argument might not be empty/null but still contain no valid items. Maybe we should have the parser explicitly return a null List so that we can take care of this at the return

**Comment by rtvb** [comment]
The playlist "Robert" is an existing playlist that contains 4 tracks. I have created the playlist through the iOS app and can select and play it from there. When I select the playlist through OH2, the player is TRANSITIONING and then continues playing what it did (a radio station in my test scenario).

**Comment by rtvb** [comment]
Configuration

**my.things**
```
Thing sonos:PLAY1:living [ udn="RINCON_B8E937B435380xxxx", refresh=60]```
```

**sonos.items**
```
Group Sonos_Living (All)
String Sonos_Living_PlayList       "Playlist [%s]" <text> (Sonos_Living) {channel="sonos:PLAY1:living:playlist"}
Number Sonos_Living_PlayListSelect "Playlist"      <text> (Sonos_Living)
```

**sonos.rules**
```
rule "SonosSelectPlayList"
when
	Item Sonos_Living_PlayListSelect received command
then
	switch(receivedCommand) {
		case 0 : sendCommand(Sonos_Living_PlayList, "Robert")
		case 1 : sendCommand(Sonos_Living_PlayList, "Christmas")
	}
end
```

**Comment by kgoderis** [comment]
Yes, the binding is unable to fetch the items that make up the playlist. It is to be investigated as to why that is happening.

**Comment by lolodomo** [comment]
I opened the same issue few days ago: #1942.
So this issue will be fixed by my PR being in the pipe.

**Comment by lolodomo** [comment]
PR #1957 will fix this issue.

**Comment by lolodomo** [comment]
PR fixing this issue is now merged. This issue has to be closed.
