### ISSUE TITLE
OSX: Designer does not start

### ISSUE THREAD

**Issue by sja** [eclipse/smarthome#1611]
I downloaded the Designer nightly from [here](http://www.eclipse.org/smarthome/documentation/community/downloads.html) but after the splash screen, it just shows me an error `An error has occurred.` and a direction to the logfile.

/Applications/Eclipse SmartHome Designer.app/Contents/Eclipse/configuration/1465037592714.log

Content:
```
!SESSION 2016-06-04 12:53:12.535 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_74
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=de_DE
Command-line arguments:  -os macosx -ws cocoa -arch x86_64

!ENTRY org.eclipse.equinox.ds 1 0 2016-06-04 12:53:13.419
!MESSAGE Could not bind a reference of component ConfigDescriptionRegistry. The reference is: Reference[name = ConfigOptionProvider, interface = org.eclipse.smarthome.config.core.ConfigOptionProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addConfigOptionProvider, unbind = removeConfigOptionProvider]

!ENTRY org.eclipse.equinox.ds 1 0 2016-06-04 12:53:13.420
!MESSAGE Could not bind a reference of component ConfigDescriptionRegistry. The reference is: Reference[name = ConfigDescriptionProvider, interface = org.eclipse.smarthome.config.core.ConfigDescriptionProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addConfigDescriptionProvider, unbind = removeConfigDescriptionProvider]

!ENTRY org.eclipse.equinox.ds 1 0 2016-06-04 12:53:13.539
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.core.binding.BindingInfoRegistry. The reference is: Reference[name = BindingInfoProvider, interface = org.eclipse.smarthome.core.binding.BindingInfoProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addBindingInfoProvider, unbind = removeBindingInfoProvider]

!ENTRY org.eclipse.equinox.ds 1 0 2016-06-04 12:53:13.570
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.core.itemregistry. The reference is: Reference[name = ItemProvider, interface = org.eclipse.smarthome.core.items.ItemProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addProvider, unbind = removeProvider]

!ENTRY org.eclipse.equinox.ds 1 0 2016-06-04 12:53:13.571
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.core.itemregistry. The reference is: Reference[name = ManagedItemProvider, interface = org.eclipse.smarthome.core.items.ManagedItemProvider, policy = dynamic, cardinality = 0..1, target = null, bind = setManagedProvider, unbind = removeManagedProvider]

!ENTRY org.eclipse.equinox.ds 1 0 2016-06-04 12:53:13.925
!MESSAGE Could not bind a reference of component ConfigStatusService. The reference is: Reference[name = ConfigStatusProvider, interface = org.eclipse.smarthome.config.core.status.ConfigStatusProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addConfigStatusProvider, unbind = removeConfigStatusProvider]

!ENTRY org.eclipse.equinox.ds 1 0 2016-06-04 12:53:13.937
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.core.thing.ThingRegistry. The reference is: Reference[name = ThingProvider, interface = org.eclipse.smarthome.core.thing.ThingProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addProvider, unbind = removeProvider]

!ENTRY org.eclipse.equinox.ds 1 0 2016-06-04 12:53:13.937
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.core.thing.ThingRegistry. The reference is: Reference[name = ManagedThingProvider, interface = org.eclipse.smarthome.core.thing.ManagedThingProvider, policy = dynamic, cardinality = 0..1, target = null, bind = setManagedProvider, unbind = removeManagedProvider]

!ENTRY org.eclipse.equinox.ds 1 0 2016-06-04 12:53:13.943
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.core.thing.ThingRegistry. The reference is: Reference[name = ThingHandlerFactory, interface = org.eclipse.smarthome.core.thing.binding.ThingHandlerFactory, policy = dynamic, cardinality = 0..n, target = null, bind = addThingHandlerFactory, unbind = removeThingHandlerFactory]

!ENTRY org.eclipse.equinox.ds 1 0 2016-06-04 12:53:13.945
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.core.thing.link.ItemChannelLinkRegistry. The reference is: Reference[name = ItemChannelLinkProvider, interface = org.eclipse.smarthome.core.thing.link.ItemChannelLinkProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addProvider, unbind = removeProvider]

!ENTRY org.eclipse.equinox.ds 1 0 2016-06-04 12:53:13.945
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.core.thing.link.ItemChannelLinkRegistry. The reference is: Reference[name = ManagedItemChannelLinkProvider, interface = org.eclipse.smarthome.core.thing.link.ManagedItemChannelLinkProvider, policy = dynamic, cardinality = 0..1, target = null, bind = setManagedProvider, unbind = removeManagedProvider]

!ENTRY org.eclipse.equinox.ds 1 0 2016-06-04 12:53:13.953
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.core.thing.type.ThingTypeRegistry. The reference is: Reference[name = ThingTypeProvider, interface = org.eclipse.smarthome.core.thing.binding.ThingTypeProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addThingTypeProvider, unbind = removeThingTypeProvider]

!ENTRY org.eclipse.equinox.ds 1 0 2016-06-04 12:53:13.960
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.core.thing.firmware.FirmwareRegistry. The reference is: Reference[name = FirmwareProvider, interface = org.eclipse.smarthome.core.thing.firmware.FirmwareProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addFirmwareProvider, unbind = removeFirmwareProvider]

!ENTRY org.eclipse.equinox.ds 1 0 2016-06-04 12:53:13.964
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.core.thing.firmware.FirmwareUpdateService. The reference is: Reference[name = FirmwareUpdateHandler, interface = org.eclipse.smarthome.core.thing.binding.firmware.FirmwareUpdateHandler, policy = dynamic, cardinality = 0..n, target = null, bind = addFirmwareUpdateHandler, unbind = removeFirmwareUpdateHandler]

!ENTRY org.eclipse.xtext.junit4 2 0 2016-06-04 12:53:14.085
!MESSAGE Could not resolve module: org.eclipse.xtext.junit4 [281]
  Bundle was not resolved because of a uses contraint violation.
  org.osgi.service.resolver.ResolutionException: Uses constraint violation. Unable to resolve resource org.eclipse.xtext.junit4 [osgi.identity; osgi.identity="org.eclipse.xtext.junit4"; type="osgi.bundle"; version:Version="2.9.2.v201603040440"] because it is exposed to package 'org.apache.log4j.spi' from resources org.apache.log4j [osgi.identity; osgi.identity="org.apache.log4j"; type="osgi.bundle"; version:Version="1.2.15.v201012070815"] and org.slf4j.log4j [osgi.identity; osgi.identity="org.slf4j.log4j"; type="osgi.bundle"; version:Version="1.7.2.v20130115-1340"] via two dependency chains.

Chain 1:
  org.eclipse.xtext.junit4 [osgi.identity; osgi.identity="org.eclipse.xtext.junit4"; type="osgi.bundle"; version:Version="2.9.2.v201603040440"]
    require: (&(osgi.wiring.bundle=org.apache.log4j)(bundle-version>=1.2.15))
     |
    provide: osgi.wiring.bundle: org.apache.log4j
  org.apache.log4j [osgi.identity; osgi.identity="org.apache.log4j"; type="osgi.bundle"; version:Version="1.2.15.v201012070815"]

Chain 2:
  org.eclipse.xtext.junit4 [osgi.identity; osgi.identity="org.eclipse.xtext.junit4"; type="osgi.bundle"; version:Version="2.9.2.v201603040440"]
    require: (&(osgi.wiring.bundle=org.eclipse.xtext)(&(bundle-version>=2.9.0)(!(bundle-version>=3.0.0))))
     |
    provide: osgi.wiring.bundle; bundle-version:Version="2.9.2.v201603040440"; osgi.wiring.bundle="org.eclipse.xtext"; singleton:="true"
  org.eclipse.xtext.util [osgi.identity; osgi.identity="org.eclipse.xtext.util"; type="osgi.bundle"; version:Version="2.9.2.v201603040440"]
    import: (&(osgi.wiring.package=org.apache.log4j)(version>=1.2.15))
     |
    export: osgi.wiring.package: org.apache.log4j; uses:=org.apache.log4j.spi
    export: osgi.wiring.package=org.apache.log4j.spi
  org.slf4j.log4j [osgi.identity; osgi.identity="org.slf4j.log4j"; type="osgi.bundle"; version:Version="1.7.2.v20130115-1340"]

!ENTRY org.eclipse.xtext.xbase.junit 2 0 2016-06-04 12:53:14.086
!MESSAGE Could not resolve module: org.eclipse.xtext.xbase.junit [292]
  Unresolved requirement: Require-Bundle: org.eclipse.xtext.junit4; bundle-version="[2.9.0,3.0.0)"
    -> Bundle-SymbolicName: org.eclipse.xtext.junit4; bundle-version="2.9.2.v201603040440"
       org.eclipse.xtext.junit4 [281]
         Bundle was not resolved because of a uses contraint violation.
  org.osgi.service.resolver.ResolutionException: Uses constraint violation. Unable to resolve resource org.eclipse.xtext.junit4 [osgi.identity; osgi.identity="org.eclipse.xtext.junit4"; type="osgi.bundle"; version:Version="2.9.2.v201603040440"] because it is exposed to package 'org.apache.log4j.spi' from resources org.apache.log4j [osgi.identity; osgi.identity="org.apache.log4j"; type="osgi.bundle"; version:Version="1.2.15.v201012070815"] and org.slf4j.log4j [osgi.identity; osgi.identity="org.slf4j.log4j"; type="osgi.bundle"; version:Version="1.7.2.v20130115-1340"] via two dependency chains.

Chain 1:
  org.eclipse.xtext.junit4 [osgi.identity; osgi.identity="org.eclipse.xtext.junit4"; type="osgi.bundle"; version:Version="2.9.2.v201603040440"]
    require: (&(osgi.wiring.bundle=org.apache.log4j)(bundle-version>=1.2.15))
     |
    provide: osgi.wiring.bundle: org.apache.log4j
  org.apache.log4j [osgi.identity; osgi.identity="org.apache.log4j"; type="osgi.bundle"; version:Version="1.2.15.v201012070815"]

Chain 2:
  org.eclipse.xtext.junit4 [osgi.identity; osgi.identity="org.eclipse.xtext.junit4"; type="osgi.bundle"; version:Version="2.9.2.v201603040440"]
    require: (&(osgi.wiring.bundle=org.eclipse.xtext)(&(bundle-version>=2.9.0)(!(bundle-version>=3.0.0))))
     |
    provide: osgi.wiring.bundle; bundle-version:Version="2.9.2.v201603040440"; osgi.wiring.bundle="org.eclipse.xtext"; singleton:="true"
  org.eclipse.xtext.util [osgi.identity; osgi.identity="org.eclipse.xtext.util"; type="osgi.bundle"; version:Version="2.9.2.v201603040440"]
    import: (&(osgi.wiring.package=org.apache.log4j)(version>=1.2.15))
     |
    export: osgi.wiring.package: org.apache.log4j; uses:=org.apache.log4j.spi
    export: osgi.wiring.package=org.apache.log4j.spi
  org.slf4j.log4j [osgi.identity; osgi.identity="org.slf4j.log4j"; type="osgi.bundle"; version:Version="1.7.2.v20130115-1340"]

!ENTRY org.eclipse.osgi 4 0 2016-06-04 12:53:14.089
!MESSAGE Application error
!STACK 1
java.lang.IllegalStateException: Unable to acquire application service. Ensure that the org.eclipse.core.runtime bundle is resolved and started (see config.ini).
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:78)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:382)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:236)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
 
```

**Comment by kaikreuzer** [comment]
Are you sure that you already have a build that includes https://github.com/eclipse/smarthome/pull/1610?

**Comment by sja** [comment]
Ah, no. Just had a look at open issues - not already merged stuff. Thanks! Will reopen if it won't work.
