### ISSUE TITLE
ConcurrentModificationException on OSGiEventManager

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#1640]
Using ESH 893554bd646ab1d876fe0efc735ea08d05313267

``` text
!ENTRY org.eclipse.equinox.event 4 0 2016-06-08 16:16:53.938
!MESSAGE Exception while dispatching event org.osgi.service.event.Event [topic=smarthome] to handler org.eclipse.smarthome.core.internal.events.OSGiEventManager@6e866f3
!STACK 0
java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
    at java.util.HashMap$KeyIterator.next(HashMap.java:1461)
    at com.google.common.collect.AbstractMultimap$WrappedCollection$WrappedIterator.next(AbstractMultimap.java:531)
    at java.util.AbstractCollection.addAll(AbstractCollection.java:343)
    at org.eclipse.smarthome.core.internal.events.OSGiEventManager.getEventSubscribers(OSGiEventManager.java:216)
    at org.eclipse.smarthome.core.internal.events.OSGiEventManager.handleEvent(OSGiEventManager.java:159)
    at org.eclipse.smarthome.core.internal.events.OSGiEventManager.handleEvent(OSGiEventManager.java:146)
    at org.eclipse.equinox.internal.event.EventHandlerWrapper.handleEvent(EventHandlerWrapper.java:197)
    at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:197)
    at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:1)
    at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
    at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
```

**Comment by maggu2810** [comment]
Just to keep track of this bug.

**Comment by maggu2810** [comment]
Hm, about half a year without realizing this error again.
I assume it is safe to close this one.
