### ISSUE TITLE
Paper UI does not work with Edge browser under Windows 10

### ISSUE THREAD

**Issue by MHerbst** [eclipse/smarthome#1657]
I have tried to use the Paper UI with the Microsoft Edge browser under Windows 10. But it does not work at all:

![paperui_edge](https://cloud.githubusercontent.com/assets/616792/15992796/782912ae-30d5-11e6-8d5b-5214fcf77f6d.PNG)

There were also lots of error message displayed in the developer console. I think that this is the reason while Paper UI does not work:

```
ReferenceError: 'EventSource' is undefined
   at initializeEventService (http://127.0.0.1:8080/ui/js/services.min.js:716:9)
   at Anonymous function (http://127.0.0.1:8080/ui/js/services.min.js:735:5)
   at e (http://127.0.0.1:8080/ui/js/angular.min.js:39:385)
   at Anonymous function (http://127.0.0.1:8080/ui/js/angular.min.js:37:303)
   at e (http://127.0.0.1:8080/ui/js/angular.min.js:39:385)
   at Anonymous function (http://127.0.0.1:8080/ui/js/angular.min.js:41:215)
   at d (http://127.0.0.1:8080/ui/js/angular.min.js:39:60)
   at e (http://127.0.0.1:8080/ui/js/angular.min.js:39:327)
   at Anonymous function (http://127.0.0.1:8080/ui/js/angular.min.js:80:328)
   at D (http://127.0.0.1:8080/ui/js/angular.min.js:61:356)
angular.min.js (107,203)
```

BTW: Basic UI, Classic UI and Rest API are running fine.

**Comment by maggu2810** [comment]
The EventSource is necessary for the Events and used by the PaperUI.
https://github.com/eclipse/smarthome/blob/master/docs/documentation/features/rest.md#server-sent-events-sse

It seems that is not supported by the Microsoft Web Browser: http://www.w3schools.com/html/html5_serversentevents.asp

**Comment by kaikreuzer** [comment]
@aounhaider1 Just a question: I vaguely remember that there was some trick (doing SSE through some JS) to still support Paper UI on IE. If this is correct, I would expect a similar thing to be possible for Edge.
If not, we should document this as a known limitation.

**Comment by aounhaider1** [comment]
Yes, there are some polyfills available for IE. And I think this one (https://github.com/remy/polyfills/blob/master/EventSource.js) will work for Edge as well. But I will have to check.

**Comment by bdleedy** [comment]
1 mystery solved... Firefox quickly and happily installed on the server. Working now. I couldn't figure out why I could access remotely (firefox) and not locally(IE).

**Comment by dmartinpro** [comment]
I'm encountering the same issue with both Paper UI AND Habmin2. Unable to use Edge with both of them.
I didn't have a look at the root cause, but I suspect this to be easily fixed as Edge is rather good with standards (not the same with IE...).
