### ISSUE TITLE
Eclipse Installer for SmartHome IDE does not work with Neon

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#1662]
When choosing "Product Version: Neon" in the Eclipse Installer, the setup fails with this message:

```
Calculating requirements and dependencies.
Cannot complete the request.  Generating details.
ERROR: org.eclipse.equinox.p2.director code=10054 Cannot complete the install because of a conflicting dependency.
  at org.eclipse.oomph.util.OomphPlugin.coreException(OomphPlugin.java:282)
  at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl.resolve(ProfileTransactionImpl.java:413)
  at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl.commit(ProfileTransactionImpl.java:325)
  at org.eclipse.oomph.setup.p2.impl.P2TaskImpl.perform(P2TaskImpl.java:709)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:2971)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:2900)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:2881)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:2775)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:550)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:635)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
  ERROR: org.eclipse.equinox.p2.director code=0 Software being installed: artificial_root 1.0.0.v1465838156257
  ERROR: org.eclipse.equinox.p2.director code=1 Only one of the following can be installed at once: 
    ERROR: org.eclipse.equinox.p2.director code=0 Object Teams Development Tooling Core 3.12.0.v_OTDT_r250_201605311624 (org.eclipse.jdt.core 3.12.0.v_OTDT_r250_201605311624)
    ERROR: org.eclipse.equinox.p2.director code=0 Java Development Tools Core 3.11.0.xx-201604081629-e45 (org.eclipse.jdt.core 3.11.0.xx-201604081629-e45)
    ERROR: org.eclipse.equinox.p2.director code=0 Java Development Tools Core 3.12.0.v20160516-2131 (org.eclipse.jdt.core 3.12.0.v20160516-2131)
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: artificial_root 1.0.0.v1465838156257
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.codehaus.groovy.eclipse.feature.feature.group 0.0.0
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: artificial_root 1.0.0.v1465838156257
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.jdt.feature.group 0.0.0
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: Groovy-Eclipse Compilerless Feature 2.9.2.xx-201604081629-e45 (org.codehaus.groovy.compilerless.feature.feature.group 2.9.2.xx-201604081629-e45)
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.codehaus.groovy.headless.feature.feature.group [2.9.2.xx-201604081629-e45]
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: Groovy-Eclipse Feature 2.9.2.xx-201604081629-e45 (org.codehaus.groovy.eclipse.feature.feature.group 2.9.2.xx-201604081629-e45)
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.codehaus.groovy.compilerless.feature.feature.group [2.9.2.xx-201604081629-e45]
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: Groovy-Eclipse Headless Feature 2.9.2.xx-201604081629-e45 (org.codehaus.groovy.headless.feature.feature.group 2.9.2.xx-201604081629-e45)
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.codehaus.groovy.jdt.patch.feature.group [2.9.2.xx-201604081629-e45]
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: Eclipse Java Development Tools 3.12.0.v20160525-2000 (org.eclipse.jdt.feature.group 3.12.0.v20160525-2000)
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.jdt.junit [3.9.0.v20160421-1701]
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: Java Development Tools JUnit support 3.9.0.v20160421-1701 (org.eclipse.jdt.junit 3.9.0.v20160421-1701)
    ERROR: org.eclipse.equinox.p2.director code=0 To: bundle org.eclipse.jdt.core [3.12.0,4.0.0)
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From Patch: org.codehaus.groovy.jdt.patch.feature.group 2.9.2.xx-201604081629-e45 Eclipse Java Development Tools 3.12.0.v20160525-2000 (org.eclipse.jdt.feature.group 3.12.0.v20160525-2000)
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.jdt.core [3.11.0.xx-201604081629-e45]

Took 31 seconds.
There are failed tasks.
```
As Neon is about to be released on June 22, this needs to be fixed soon.

**Comment by maggu2810** [comment]
I am using the ESH Setup already (for a few weeks) with the Neon RC, it is just the Groovy repo that needs to be changed to 4.6 in the setup file.

**Comment by kaikreuzer** [comment]
Will Mars also still work with the new Groovy repo?

**Comment by maggu2810** [comment]
I don't know.
For Mars and the Groovy integration you could be interested in this bug: https://github.com/groovy/groovy-eclipse/issues/181

**Comment by maggu2810** [comment]
So, now Eclipse Neon is the "latest release".
Should we change the setup file to Groovy 4.6 Repository?

If the feature in the repository can't be installed, I think this is okay, if someone uses an older IDE.

**Comment by maggu2810** [comment]
Will do

**Comment by maggu2810** [comment]
I will do

**Comment by float2net** [comment]
Please help, I met similar problem on setup smarthome project , attached the error shot:
<img width="515" alt="2016-09-19 5 56 12" src="https://cloud.githubusercontent.com/assets/4687104/18628483/05091592-7e93-11e6-89a4-a06385d4d661.png">
<img width="502" alt="2016-09-19 5 56 36" src="https://cloud.githubusercontent.com/assets/4687104/18628482/05084e6e-7e93-11e6-8ff4-7f35269893c1.png">

**Comment by maggu2810** [comment]
I don't think your problem is similar to the other one.

Are you sure, that you have followed every point here:
https://www.eclipse.org/smarthome/documentation/development/ide.html

Also e.g. point 8?

**Comment by maggu2810** [comment]
So, as written above, there is no relationship between your problem and this original issue.
Could you create a separate one?

But I assume the error is not related to the setup file itself (but I can reinstall the IDE myself if you want).
If you cannot resolve the target platform there is a problem with the installed Eclipse IDE plugins (PDE) or you have problems to access some servers.

**Comment by kaikreuzer** [comment]
@float2net You should try to repeat the target platform resolution. This error sometimes occurs if people have slow or unreliable Internet connections or if some remote server might have been down at the moment of resolution.

**Comment by float2net** [comment]
It's java7 and java8 installed in my environment, I tried to re-install SmartHome from begin, with Eclipse Mars, has exactly the same error, from the error I assume maybe due to cannot connect to some remote server, if this is the reason, is there any alternative workaround e.g. offline setup?
@maggu2810 if it's due to my internet connection, maybe it's trivial to fork a NEW issue?

**Comment by maggu2810** [comment]
> @maggu2810 if it's due to my internet connection, maybe it's trivial to fork a NEW issue?

@float2net You have to create a new issue. There is no "fork issue" (copy, split, move) feature for Github.

> Today I tried to re-install SmartHome from begin, with Eclipse Mars

@float2net That cannot work, because part of the setup requires Neon.

> is there any alternative workaround e.g. offline setup?

@float2net There isn't (at least I don't know about). Sorry
