### ISSUE TITLE
Test failure(s): automation.integration.test

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#1681]
The Hudson instance of the Eclipse SmartHome project fails mutliple times.

| Build Nr.  | Date | Console |
| ------------- | ------------- | ------------- |
| 1116 | 15.06.2016 08:05:39 | [1116-consoleText.txt](https://github.com/eclipse/smarthome/files/318030/1116-consoleText.txt) |
| 1117 | 15.06.2016 13:05:39 | [1117-consoleText.txt](https://github.com/eclipse/smarthome/files/318032/1117-consoleText.txt) |
| 1119 | 16.06.2016 04:05:39 | [1119-consoleText.txt](https://github.com/eclipse/smarthome/files/318031/1119-consoleText.txt) |

**Comment by danchom** [comment]
It is strange because we haven't merged changes more then a week ago. The integration tests are closely related to Items implementation and events fired by them. Are there some majer changes?

**Comment by maggu2810** [comment]
Have ATM no time to further inspect the logs.
But the error could be caused by bundle resources handling.
Or because the automation tests rely on a special behavior.

```text
Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 9.444 sec <<< FAILURE! - in org.eclipse.smarthome.automation.integration.test.HostFragmentSupportTest
asserting that the update of the fragment-host provides the resources correctly(org.eclipse.smarthome.automation.integration.test.HostFragmentSupportTest)  Time elapsed: 9.314 sec
asserting that the installation of the fragment-host provides the resources correctly(org.eclipse.smarthome.automation.integration.test.HostFragmentSupportTest)  Time elapsed: 0.049 sec  <<< ERROR!
java.lang.NullPointerException: Cannot invoke method getLabel() on null object
	at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:88)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:45)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:32)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at org.eclipse.smarthome.automation.integration.test.HostFragmentSupportTest$_asserting_that_the_installation_of_the_fragment-host_provides_the_resources_correctly_closure7.doCall(HostFragmentSupportTest.groovy:206)
	at org.eclipse.smarthome.automation.integration.test.HostFragmentSupportTest$_asserting_that_the_installation_of_the_fragment-host_provides_the_resources_correctly_closure7.doCall(HostFragmentSupportTest.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:278)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:54)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at org.eclipse.smarthome.test.OSGiTest.waitForAssert(OSGiTest.groovy:174)
	at sun.reflect.GeneratedMethodAccessor33.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:207)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:149)
	at org.eclipse.smarthome.automation.integration.test.HostFragmentSupportTest.asserting that the installation of the fragment-host provides the resources correctly(HostFragmentSupportTest.groovy:202)
```

**Comment by sjka** [comment]
One to add here (based on commit 7f8693abc):

```
Tests run: 3, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 9.277 sec <<< FAILURE! - in org.eclipse.smarthome.automation.integration.test.HostFragmentSupportTest
asserting that the update of the fragment-host provides the resources correctly(org.eclipse.smarthome.automation.integration.test.HostFragmentSupportTest)  Time elapsed: 3.13 sec  <<< FAILURE!
java.lang.AssertionError:
Expected: is "Trigger 1 Label"
     but: was "Abzugshahn 1 Etikette"
    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
    at org.junit.Assert.assertThat(Assert.java:865)
    at org.junit.Assert.assertThat(Assert.java:832)
    at org.junit.Assert$assertThat.callStatic(Unknown Source)
    at org.eclipse.smarthome.automation.integration.test.HostFragmentSupportTest$_asserting_that_the_update_of_the_fragment-host_provides_the_resources_correctly_closure12.doCall(HostFragmentSupportTest.groovy:304)
    at org.eclipse.smarthome.automation.integration.test.HostFragmentSupportTest$_asserting_that_the_update_of_the_fragment-host_provides_the_resources_correctly_closure12.doCall(HostFragmentSupportTest.groovy)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
    at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:278)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
    at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
    at org.eclipse.smarthome.test.OSGiTest.waitForAssert(OSGiTest.groovy:181)
    at sun.reflect.GeneratedMethodAccessor44.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:207)
    at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:56)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:149)
    at org.eclipse.smarthome.automation.integration.test.HostFragmentSupportTest.asserting that the update of the fragment-host provides the resources correctly(HostFragmentSupportTest.groovy:300)

asserting that the installation of the fragment-host provides the resources correctly(org.eclipse.smarthome.automation.integration.test.HostFragmentSupportTest)  Time elapsed: 3.06 sec  <<< FAILURE!
java.lang.AssertionError:
Expected: is <2>
     but: was <4>
    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
    at org.junit.Assert.assertThat(Assert.java:865)
    at org.junit.Assert.assertThat(Assert.java:832)
    at org.junit.Assert$assertThat.callStatic(Unknown Source)
    at org.eclipse.smarthome.automation.integration.test.HostFragmentSupportTest$_asserting_that_the_installation_of_the_fragment-host_provides_the_resources_correctly_closure6.doCall(HostFragmentSupportTest.groovy:191)
    at org.eclipse.smarthome.automation.integration.test.HostFragmentSupportTest$_asserting_that_the_installation_of_the_fragment-host_provides_the_resources_correctly_closure6.doCall(HostFragmentSupportTest.groovy)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
    at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:278)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
    at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
    at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:54)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
    at org.eclipse.smarthome.test.OSGiTest.waitForAssert(OSGiTest.groovy:181)
    at sun.reflect.GeneratedMethodAccessor44.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:207)
    at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:56)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:149)
    at org.eclipse.smarthome.automation.integration.test.HostFragmentSupportTest.asserting that the installation of the fragment-host provides the resources correctly(HostFragmentSupportTest.groovy:190)

asserting that the installation of the host-fragment provides the resources correctly(org.eclipse.smarthome.automation.integration.test.HostFragmentSupportTest)  Time elapsed: 3.071 sec  <<< FAILURE!
java.lang.AssertionError:
Expected: is "Trigger 1 Label"
     but: was "Abzugshahn 1 Etikette"
    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
    at org.junit.Assert.assertThat(Assert.java:865)
    at org.junit.Assert.assertThat(Assert.java:832)
    at org.junit.Assert$assertThat.callStatic(Unknown Source)
    at org.eclipse.smarthome.automation.integration.test.HostFragmentSupportTest$_asserting_that_the_installation_of_the_host-fragment_provides_the_resources_correctly_closure3.doCall(HostFragmentSupportTest.groovy:123)
    at org.eclipse.smarthome.automation.integration.test.HostFragmentSupportTest$_asserting_that_the_installation_of_the_host-fragment_provides_the_resources_correctly_closure3.doCall(HostFragmentSupportTest.groovy)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
    at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:278)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
    at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
    at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:54)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
    at org.eclipse.smarthome.test.OSGiTest.waitForAssert(OSGiTest.groovy:181)
    at sun.reflect.GeneratedMethodAccessor44.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:207)
    at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:56)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:149)
    at org.eclipse.smarthome.automation.integration.test.HostFragmentSupportTest.asserting that the installation of the host-fragment provides the resources correctly(HostFragmentSupportTest.groovy:120)


Results :

Failed tests:
  HostFragmentSupportTest.asserting that the update of the fragment-host provides the resources correctly:300->OSGiTest.waitForAssert:181
Expected: is "Trigger 1 Label"
     but: was "Abzugshahn 1 Etikette"
  HostFragmentSupportTest.asserting that the installation of the fragment-host provides the resources correctly:190->OSGiTest.waitForAssert:181
Expected: is <2>
     but: was <4>
  HostFragmentSupportTest.asserting that the installation of the host-fragment provides the resources correctly:120->OSGiTest.waitForAssert:181
Expected: is "Trigger 1 Label"
     but: was "Abzugshahn 1 Etikette"

Tests run: 20, Failures: 3, Errors: 0, Skipped: 0
```

**Comment by kaikreuzer** [comment]
And three more:
https://hudson.eclipse.org/smarthome/job/SmartHomeDistribution-Stable/79/
https://hudson.eclipse.org/smarthome/job/SmartHomeDistribution-Stable/81/
https://hudson.eclipse.org/smarthome/job/SmartHomeDistribution-Stable/83/

@danchom @adimova This is now a critical issue as it prevents a successful build. The failure rate seems to be >50%. Please have a look at how they can be fixed.

**Comment by BenediktNiehues** [comment]
The current failures are resulted by a timing issues again. The ModuleType is still null. PR #1723 should solve the problem. At least waitForAssert will also wait even if there was a NPE.

**Comment by kaikreuzer** [comment]
It seems that #1723 solves the issues, so I close this now.
Many thanks for the fix, @BenediktNiehues!
