### ISSUE TITLE
NPE : ould not inform the listener 'org.eclipse.smarthome.core.thing.internal.ChannelItemProvider$2@1ba7eb61' about the 'ADDED' event!: null

### ISSUE THREAD

**Issue by kgoderis** [eclipse/smarthome#1686]
Using the latest snapshot, I get a *lot* of these at startup of the runtime:

21:29:16.869 [INFO ] [smarthome.event.ItemAddedEvent      ] - Item 'AtticOutlet2Switch' has been added.
21:29:16.870 [INFO ] [home.event.ItemChannelLinkAddedEvent] - Link 'AtticOutlet2Switch-knx:energyswitch:ip1:AtticOutlet2Switch:switch' has been added.
21:29:16.871 [ERROR] [ore.common.registry.AbstractRegistry] - Could not inform the listener 'org.eclipse.smarthome.core.thing.internal.ChannelItemProvider$2@1ba7eb61' about the 'ADDED' event!: null
java.lang.NullPointerException
	at org.eclipse.smarthome.core.thing.DefaultSystemChannelTypeProvider.getChannelType(DefaultSystemChannelTypeProvider.java:69)[110:org.eclipse.smarthome.core.thing:0.8.0.201605311814]
	at org.eclipse.smarthome.core.thing.type.ChannelTypeRegistry.getChannelType(ChannelTypeRegistry.java:67)[110:org.eclipse.smarthome.core.thing:0.8.0.201605311814]
	at org.eclipse.smarthome.core.thing.type.TypeResolver.resolve(TypeResolver.java:43)[110:org.eclipse.smarthome.core.thing:0.8.0.201605311814]
	at org.eclipse.smarthome.core.thing.internal.ChannelItemProvider.getLabel(ChannelItemProvider.java:204)[110:org.eclipse.smarthome.core.thing:0.8.0.201605311814]
	at org.eclipse.smarthome.core.thing.internal.ChannelItemProvider.createItemForLink(ChannelItemProvider.java:176)[110:org.eclipse.smarthome.core.thing:0.8.0.201605311814]
	at org.eclipse.smarthome.core.thing.internal.ChannelItemProvider.access$1(ChannelItemProvider.java:159)[110:org.eclipse.smarthome.core.thing:0.8.0.201605311814]
	at org.eclipse.smarthome.core.thing.internal.ChannelItemProvider$2.added(ChannelItemProvider.java:257)[110:org.eclipse.smarthome.core.thing:0.8.0.201605311814]
	at org.eclipse.smarthome.core.thing.internal.ChannelItemProvider$2.added(ChannelItemProvider.java:1)[110:org.eclipse.smarthome.core.thing:0.8.0.201605311814]
	at org.eclipse.smarthome.core.common.registry.AbstractRegistry.notifyListeners(AbstractRegistry.java:142)[104:org.eclipse.smarthome.core:0.8.0.201605311814]
	at org.eclipse.smarthome.core.common.registry.AbstractRegistry.notifyListeners(AbstractRegistry.java:161)[104:org.eclipse.smarthome.core:0.8.0.201605311814]
	at org.eclipse.smarthome.core.common.registry.AbstractRegistry.notifyListenersAboutAddedElement(AbstractRegistry.java:165)[104:org.eclipse.smarthome.core:0.8.0.201605311814]
	at org.eclipse.smarthome.core.thing.link.ItemChannelLinkRegistry.notifyListenersAboutAddedElement(ItemChannelLinkRegistry.java:102)[110:org.eclipse.smarthome.core.thing:0.8.0.201605311814]
	at org.eclipse.smarthome.core.thing.link.ItemChannelLinkRegistry.notifyListenersAboutAddedElement(ItemChannelLinkRegistry.java:1)[110:org.eclipse.smarthome.core.thing:0.8.0.201605311814]
	at org.eclipse.smarthome.core.common.registry.AbstractRegistry.added(AbstractRegistry.java:58)[104:org.eclipse.smarthome.core:0.8.0.201605311814]
	at org.eclipse.smarthome.core.common.registry.AbstractProvider.notifyListeners(AbstractProvider.java:51)[104:org.eclipse.smarthome.core:0.8.0.201605311814]
	at org.eclipse.smarthome.core.common.registry.AbstractProvider.notifyListeners(AbstractProvider.java:70)[104:org.eclipse.smarthome.core:0.8.0.201605311814]
	at org.eclipse.smarthome.core.common.registry.AbstractProvider.notifyListenersAboutAddedElement(AbstractProvider.java:74)[104:org.eclipse.smarthome.core:0.8.0.201605311814]
	at org.eclipse.smarthome.model.thing.internal.GenericItemChannelLinkProvider.createItemChannelLink(GenericItemChannelLinkProvider.java:102)[134:org.eclipse.smarthome.model.thing:0.8.0.201605311814]
	at org.eclipse.smarthome.model.thing.internal.GenericItemChannelLinkProvider.processBindingConfiguration(GenericItemChannelLinkProvider.java:72)[134:org.eclipse.smarthome.model.thing:0.8.0.201605311814]
	at org.eclipse.smarthome.model.item.internal.GenericItemProvider.internalDispatchBindings(GenericItemProvider.java:378)[124:org.eclipse.smarthome.model.item:0.8.0.201605311814]
	at org.eclipse.smarthome.model.item.internal.GenericItemProvider.internalDispatchBindings(GenericItemProvider.java:350)[124:org.eclipse.smarthome.model.item:0.8.0.201605311814]
	at org.eclipse.smarthome.model.item.internal.GenericItemProvider.processBindingConfigsFromModel(GenericItemProvider.java:168)[124:org.eclipse.smarthome.model.item:0.8.0.201605311814]
	at org.eclipse.smarthome.model.item.internal.GenericItemProvider.modelChanged(GenericItemProvider.java:404)[124:org.eclipse.smarthome.model.item:0.8.0.201605311814]
	at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.notifyListeners(ModelRepositoryImpl.java:201)[123:org.eclipse.smarthome.model.core:0.8.0.201605311814]
	at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.addOrRefreshModel(ModelRepositoryImpl.java:97)[123:org.eclipse.smarthome.model.core:0.8.0.201605311814]
	at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.checkFile(FolderObserver.java:240)[123:org.eclipse.smarthome.model.core:0.8.0.201605311814]
	at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.notifyUpdateToModelRepo(FolderObserver.java:169)[123:org.eclipse.smarthome.model.core:0.8.0.201605311814]
	at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.updated(FolderObserver.java:150)[123:org.eclipse.smarthome.model.core:0.8.0.201605311814]
	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updated(ManagedServiceTracker.java:189)[7:org.apache.felix.configadmin:1.8.8]
	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updateService(ManagedServiceTracker.java:152)[7:org.apache.felix.configadmin:1.8.8]
	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.provideConfiguration(ManagedServiceTracker.java:85)[7:org.apache.felix.configadmin:1.8.8]
	at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceUpdate.provide(ConfigurationManager.java:1444)[7:org.apache.felix.configadmin:1.8.8]
	at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceUpdate.run(ConfigurationManager.java:1400)[7:org.apache.felix.configadmin:1.8.8]
	at org.apache.felix.cm.impl.UpdateThread.run0(UpdateThread.java:143)[7:org.apache.felix.configadmin:1.8.8]
	at org.apache.felix.cm.impl.UpdateThread.run(UpdateThread.java:110)[7:org.apache.felix.configadmin:1.8.8]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_66]

**Comment by kgoderis** [comment]
It seems that the channelTypeUID field of the Channel that is being linked is null. Can anyone point me out what could be wrong with the Thing Type definition here below?

```
<?xml version="1.0" encoding="UTF-8"?>
<thing:thing-descriptions bindingId="knx"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:thing="http://eclipse.org/smarthome/schemas/thing-description/v1.0.0"
        xsi:schemaLocation="http://eclipse.org/smarthome/schemas/thing-description/v1.0.0 http://eclipse.org/smarthome/schemas/thing-description-1.0.0.xsd">

    <!-- Bridge Thing Type -->
    <bridge-type id="ip">
        <label>KNX/IP gateway</label>
        <description>This Bridge is for IP based KNX gateways</description>
        
        <channels>
            <channel id="errorsall" typeId="errors" />
            <channel id="errors5min" typeId="errors" />
        </channels>
        
        ....... part removed ....
        
    </bridge-type>
    
    <channel-type id="errors">
        <item-type>Number</item-type>
        <label>Number of errors</label>
        <description>The number of errors that occurred on the KNX bus since the start of the binding, during the last 5 minutes</description>
    </channel-type>
        
    <channel-type id="Switch">
		<item-type>Switch</item-type>
		<label>Input/Output Channel</label>
		<description>The IO channel allows to read/write values from/to the group address</description>
		<config-description>
			<parameter name="address" type="text">
				<label>Address</label>
				<description>The group address in x/y/z notation</description>
				<required>true</required>
			</parameter>
			<parameter name="dpt" type="text">
				<label>DPT</label>
				<description>DataPoint Type in x.y notation</description>
				<required>true</required>
			</parameter>
			<parameter name="read" type="boolean">
				<label>Read</label>
				<description>Flag to indicate if this group address should be read at startup</description>
				<required>false</required>
			</parameter>
			<parameter name="interval" type="integer">
				<label>Interval</label>
				<description>Interval between attempts to read the group address on the bus, in seconds</description>
				<required>false</required>
			</parameter>
		</config-description>
	</channel-type>
......

```
with the actual application of the definition then being:

```
Bridge knx:ip:ip1 [ .... ] 
{
...
Channels:
Switch : ga_8_5_2 [ address="8/5/2", dpt="1.001", read=true, interval=3600]
Switch : ga_8_5_3 [ address="8/5/3", dpt="1.001", read=true, interval=3600]
Switch : ga_8_5_4 [ address="8/5/4", dpt="1.001", read=true, interval=3600]
}
```

This used to work a few weeks ago, but with the latest snapshot something has changed obviously

**Comment by maggu2810** [comment]
Have you identified the error?

**Comment by kaikreuzer** [comment]
> Using the latest snapshot
> 0.8.0.201605311814

What I learn from this is that I missed to switch the openHAB distro to ESH 0.9.0-SNAPSHOT.
This is now done with https://github.com/openhab/openhab-distro/pull/232, so that @kgoderis at least again tests again the latest sources :-)

**Comment by kgoderis** [comment]
@maggu2810 yep -> https://github.com/eclipse/smarthome/issues/1687
But I will try again cfr 0.9.0
