### ISSUE TITLE
ChannelTypeUID on manually defined channels is not set -> NPE in ChannelItemProvider

### ISSUE THREAD

**Issue by kgoderis** [eclipse/smarthome#1687]
When creating channels manually as in https://github.com/eclipse/smarthome/blob/master/docs/documentation/features/dsl.md#defining-channels, then the ChannelTypeUID of these channels is never set, and consequently, the call to ChannelItemProvider.createItemForLink() fails with an NPE because ChannelTypeRegistry.getChannelType() is getting called with null value parameter

The error thrown looks like

```
2016-06-17 10:51:05.976 [ERROR] [.c.c.registry.AbstractRegistry:154  ] - Could not inform the listener 'org.eclipse.smarthome.core.thing.internal.ChannelItemProvider$2@6cdb0d57' about the 'ADDED' event!: nulljava.lang.NullPointerException: null
	at org.eclipse.smarthome.core.thing.DefaultSystemChannelTypeProvider.getChannelType(DefaultSystemChannelTypeProvider.java:69)
	at org.eclipse.smarthome.core.thing.type.ChannelTypeRegistry.getChannelType(ChannelTypeRegistry.java:67)
	at org.eclipse.smarthome.core.thing.type.TypeResolver.resolve(TypeResolver.java:43)
	at org.eclipse.smarthome.core.thing.internal.ChannelItemProvider.getLabel(ChannelItemProvider.java:204)
	at org.eclipse.smarthome.core.thing.internal.ChannelItemProvider.createItemForLink(ChannelItemProvider.java:176)
	at org.eclipse.smarthome.core.thing.internal.ChannelItemProvider.access$1(ChannelItemProvider.java:159)
	at org.eclipse.smarthome.core.thing.internal.ChannelItemProvider$2.added(ChannelItemProvider.java:257)
	at org.eclipse.smarthome.core.thing.internal.ChannelItemProvider$2.added(ChannelItemProvider.java:1)
	at org.eclipse.smarthome.core.common.registry.AbstractRegistry.notifyListeners(AbstractRegistry.java:142)
	at org.eclipse.smarthome.core.common.registry.AbstractRegistry.notifyListeners(AbstractRegistry.java:161)
	at org.eclipse.smarthome.core.common.registry.AbstractRegistry.notifyListenersAboutAddedElement(AbstractRegistry.java:165)
```

@kaikreuzer Channels still can be created manually, or is that feature obsolete? It has a major impact on how the KNX 2.0 binding is currently working

**Comment by kaikreuzer** [comment]
> @kaikreuzer Channels still can be created manually

Yes, absolutely!

> then the ChannelTypeUID of these channels is never set

Which is correct, because no type is declared for them, right? They are simply channels without referencing a type, which is absolutely legal.

So the bug here is the NPE itself, I would say.

**Comment by kgoderis** [comment]
@kaikreuzer the problem is still there with 0.9.0

**Comment by kgoderis** [comment]
> then the ChannelTypeUID of these channels is never set
> Which is correct, because no type is declared for them, right? They are simply channels without referencing a type, which is absolutely legal.

makes me wonder why it did work a few weeks ago..... 

the DSL states that the first token in the definition is the accepted Item type for the channel, however, we could easily change that to be a channelTypeID, as defined in the ESH-INF xml, no? That way the problem is solved altogether.

**Comment by kaikreuzer** [comment]
> makes me wonder why it did work a few weeks ago.....

Most likely because the ChannelItemProvider didn't exist and hence didn't throw an NPE.

> we could easily change that to be a channelTypeID

It is right that we currently cannot define channels based on a type in the DSL. But we should imho also keep the current feature where you do not have to have a channel type at all. So we should enhance the DSL in a backward compatible way. Feel free to enter an issue for it and make a proposal about the syntax.

**Comment by kgoderis** [comment]
I made suggestion in https://github.com/eclipse/smarthome/pull/1690

**Comment by kgoderis** [comment]
@kaikreuzer @maggu2810 Pls re-open this issue, as the fix generates a lot of 

`Item 'abcd' has been removed. ` messages. It seems that Items are added, the links are created, and subsequently, the created Items are removed again for some reason.

**Comment by kgoderis** [comment]
Ok - Pls neglect the previous comment, and I now understand how the ChannelItemProvider is built. However, the fact that the message in the logs make it a  bit confusing from a end-user point of view. Maybe some additional logging code in ChannelItemProvider would be helpful to get around this.

**Comment by kaikreuzer** [comment]
Yes, I agree that the logging is a bit confusing; I actually wonder if we should completely remove those "removed/added" logging/events at startup/shutdown, because they do not make much sense anyhow. But I already feel that this will quickly become a bigger refactoring regarding startup behavior etc...

**Comment by kgoderis** [comment]
@kaikreuzer @maggu2810 Here is another location where a similar error is popping up

```
2016-06-28 18:12:35.822 [ERROR] [ore.common.registry.AbstractRegistry] - Could not inform the listener 'org.eclipse.smarthome.model.persistence.internal.PersistenceManager@14896c6' about the 'ADDED' event!: null
java.lang.NullPointerException
        at org.eclipse.smarthome.model.persistence.internal.PersistenceManager.hasStrategy(PersistenceManager.java:247)[126:org.eclipse.smarthome.model.persistence:0.9.0.201606271819]
        at org.eclipse.smarthome.model.persistence.internal.PersistenceManager.initialize(PersistenceManager.java:368)[126:org.eclipse.smarthome.model.persistence:0.9.0.201606271819]
        at org.eclipse.smarthome.model.persistence.internal.PersistenceManager.added(PersistenceManager.java:347)[126:org.eclipse.smarthome.model.persistence:0.9.0.201606271819]
        at org.eclipse.smarthome.model.persistence.internal.PersistenceManager.added(PersistenceManager.java:1)[126:org.eclipse.smarthome.model.persistence:0.9.0.201606271819]
        at org.eclipse.smarthome.core.common.registry.AbstractRegistry.notifyListeners(AbstractRegistry.java:142)[104:org.eclipse.smarthome.core:0.9.0.201606271819]
```
