### ISSUE TITLE
Missing channels stop a binding from starting

### ISSUE THREAD

**Issue by cdjackson** [eclipse/smarthome#1698]
If thing XML files for a binding contain a channel ID that doesn't exist, then there is no useful error and the binding will not start. The error that's logged is provided below, and it's extremely difficult to work out where the error lies in a large binding like ZWave.

It would be more useful to provide an error that allowed this to be debugged, such as logging the name of the missing channel.

```
2016-06-18 22:36:27.305 [ERROR] [c.x.o.XmlDocumentBundleTracker:216  ] - Could not send adding finished event for the module 'org.openhab.binding.zwave'!java.lang.IllegalArgumentException: UID must have at least 2 segments.
	at org.eclipse.smarthome.core.thing.UID.<init>(UID.java:65)
	at org.eclipse.smarthome.core.thing.UID.<init>(UID.java:43)
	at org.eclipse.smarthome.core.thing.type.ChannelTypeUID.<init>(ChannelTypeUID.java:35)
	at org.eclipse.smarthome.core.thing.xml.internal.ThingTypeXmlResult.toChannelDefinitions(ThingTypeXmlResult.java:98)
	at org.eclipse.smarthome.core.thing.xml.internal.ThingTypeXmlResult.toThingType(ThingTypeXmlResult.java:148)
	at org.eclipse.smarthome.core.thing.xml.internal.ThingTypeXmlProvider.addingFinished(ThingTypeXmlProvider.java:145)
	at org.eclipse.smarthome.config.xml.osgi.XmlDocumentBundleTracker.addingFinished(XmlDocumentBundleTracker.java:214)
	at org.eclipse.smarthome.config.xml.osgi.XmlDocumentBundleTracker.access$6(XmlDocumentBundleTracker.java:209)
	at org.eclipse.smarthome.config.xml.osgi.XmlDocumentBundleTracker$1.processBundle(XmlDocumentBundleTracker.java:140)
	at org.eclipse.smarthome.config.xml.osgi.AbstractAsyncBundleProcessor$1.run(AbstractAsyncBundleProcessor.java:246)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by cdjackson** [comment]
Actually, in addition to improving the logging, I would suggest that only things with missing channels are rejected, and the binding should then be started.

**Comment by cdjackson** [comment]
This issue seems to be resolved - it continues to work now, and the following is logged -:

```
2016-08-05 21:38:14.123 [WARN ] [.i.r.c.thing.ThingTypeResource:187  ] - Cannot find channel type: zwave:barrier_state
2016-08-05 21:38:14.124 [WARN ] [.i.r.c.thing.ThingTypeResource:222  ] - Cannot create DTO for thingType 'zwave:aeon_zw062_00_000'. Skip it.
```
