### ISSUE TITLE
Test failure(s): automation.module.timer.internal.RuntimeRuleTest

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#1757]
commit id: d279efc780f28abfeb7f906239c39c9612ac3013

```text
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 10.818 sec <<< FAILURE! - in org.eclipse.smarthome.automation.module.timer.internal.RuntimeRuleTest
assert that timerTrigger works(org.eclipse.smarthome.automation.module.timer.internal.RuntimeRuleTest)  Time elapsed: 10.462 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: is <ON>
     but: was <OFF>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:865)
	at org.junit.Assert.assertThat(Assert.java:832)
	at org.junit.Assert$assertThat.callStatic(Unknown Source)
	at org.eclipse.smarthome.automation.module.timer.internal.RuntimeRuleTest$_assert_that_timerTrigger_works_closure10.doCall(RuntimeRuleTest.groovy:120)
	at org.eclipse.smarthome.automation.module.timer.internal.RuntimeRuleTest$_assert_that_timerTrigger_works_closure10.doCall(RuntimeRuleTest.groovy)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:278)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at org.eclipse.smarthome.test.OSGiTest.waitForAssert(OSGiTest.groovy:181)
	at org.eclipse.smarthome.test.OSGiTest.waitForAssert(OSGiTest.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:207)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:141)
	at org.eclipse.smarthome.automation.module.timer.internal.RuntimeRuleTest.assert that timerTrigger works(RuntimeRuleTest.groovy:119)

check if timer trigger moduleType is registered(org.eclipse.smarthome.automation.module.timer.internal.RuntimeRuleTest)  Time elapsed: 0.012 sec

Results :

Failed tests: 
  RuntimeRuleTest.assert that timerTrigger works:119->OSGiTest.waitForAssert:-1->OSGiTest.waitForAssert:181 
Expected: is <ON>
     but: was <OFF>

Tests run: 2, Failures: 1, Errors: 0, Skipped: 0
```

[16.log.txt](https://github.com/eclipse/smarthome/files/336450/16.log.txt)

**Comment by maggu2810** [comment]
[23.log.txt](https://github.com/eclipse/smarthome/files/336453/23.log.txt)
[27.log.txt](https://github.com/eclipse/smarthome/files/336454/27.log.txt)

**Comment by maggu2810** [comment]
* Failed  #1246	Aug 15, 2016 10:05:39 AM
[SmartHomeDistribution-Nightly.1246.consoleText.txt](https://github.com/eclipse/smarthome/files/420207/SmartHomeDistribution-Nightly.1246.consoleText.txt)

* Failed  #1249	Aug 16, 2016 7:05:39 AM
[SmartHomeDistribution-Nightly.1249.consoleText.txt](https://github.com/eclipse/smarthome/files/420208/SmartHomeDistribution-Nightly.1249.consoleText.txt)
