### ISSUE TITLE
org.quartz.SchedulerException due to java.lang.RuntimeException of unresolved Item

### ISSUE THREAD

**Issue by kgoderis** [eclipse/smarthome#1770]
The following error is thrown by Quartz when a startup Rule is executed when the an Item is not yet defined:

```
2016-06-28 18:07:54.065 [ERROR] [org.quartz.core.ErrorLogger         ] - Job (DEFAULT.2016-06-28T18:07:52.168+02:00: Proxy for org.eclipse.xtext.xbase.lib.Procedures$Procedure0: [ | {
  logInfo(<XStringLiteralImpl>,<XStringLiteralImpl>)
  <XFeatureCallImplCustom>.sendCommand(<XNumberLiteralImpl>)
  logInfo(<XStringLiteralImpl>,<XStringLiteralImpl>)
  <XFeatureCallImplCustom>.sendCommand(<XNumberLiteralImpl>)
  createTimer(<XMemberFeatureCallImplCustom>,<XClosureImplCustom>)
} ] threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: java.lang.RuntimeException: The name 'openHABHostVolume' cannot be resolved to an item or type.]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213)[109:org.eclipse.smarthome.core.scheduler:0.9.0.201606271819]
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)[109:org.eclipse.smarthome.core.scheduler:0.9.0.201606271819]
Caused by: java.lang.RuntimeException: The name 'openHABHostVolume' cannot be resolved to an item or type.
        at org.eclipse.smarthome.model.script.interpreter.ScriptInterpreter.invokeFeature(ScriptInterpreter.java:112)[130:org.eclipse.smarthome.model.script:0.9.0.201606271819]
```

**Comment by kaikreuzer** [comment]
As the startup rule management has been optimized by https://github.com/eclipse/smarthome/pull/1828, I would assume that this now does not occur anymore (unless the item is really missing).
