### ISSUE TITLE
Unresponsive Karaf console

### ISSUE THREAD

**Issue by kgoderis** [eclipse/smarthome#1775]
Often, but not all the time, the Karaf console is not responsive. .e.g the session that is initiated when running the startup scripts. One can not enter commands anymore, it is a total freeze

However, ssh-ing into the runtime for a new session is working fine, and commands can be issued

Anyone seen this behaviour?

**Comment by kgoderis** [comment]
When doing a system:shutdown, the following is then thrown:

```
2016-06-30 11:17:55.476 [ERROR] [apache.karaf.shell.support.ShellUtil] - Exception caught while executing command
java.lang.UnsupportedOperationException: read() with timeout cannot be called as non-blocking operation is disabled
	at jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:132)[31:line:2.13.0]
	at jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:243)[31:line:2.13.0]
	at jline.internal.InputStreamReader.read(InputStreamReader.java:257)[31:line:2.13.0]
	at jline.internal.InputStreamReader.read(InputStreamReader.java:194)[31:line:2.13.0]
	at jline.console.ConsoleReader.readCharacter(ConsoleReader.java:2136)[31:line:2.13.0]
	at jline.console.ConsoleReader.readCharacter(ConsoleReader.java:2126)[31:line:2.13.0]
	at jline.console.ConsoleReader.readBinding(ConsoleReader.java:2211)[31:line:2.13.0]
	at jline.console.ConsoleReader.readLine(ConsoleReader.java:2460)[31:line:2.13.0]
	at jline.console.ConsoleReader.readLine(ConsoleReader.java:2372)[31:line:2.13.0]
	at jline.console.ConsoleReader.readLine(ConsoleReader.java:2360)[31:line:2.13.0]
	at org.apache.karaf.shell.impl.console.ConsoleSessionImpl.readAndParseCommand(ConsoleSessionImpl.java:369)[64:org.apache.karaf.shell.core:4.0.4]
	at org.apache.karaf.shell.impl.console.ConsoleSessionImpl.run(ConsoleSessionImpl.java:265)[64:org.apache.karaf.shell.core:4.0.4]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_66]
```

**Comment by kaikreuzer** [comment]
Nope, and again, this would be an issue for https://github.com/openhab/openhab-distro and not ESH.
