### ISSUE TITLE
ClosedSelectorException in LIFX discovery

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#1787]
I very often see this in my logs:

```
2016-07-01 12:16:58.597 [ERROR] [o.e.s.b.l.i.LifxLightDiscovery:402  ] - An exception orccurred while communicating with the bulb : 'null'java.nio.channels.ClosedSelectorException: null
	at sun.nio.ch.SelectorImpl.selectedKeys(SelectorImpl.java:74)
	at org.eclipse.smarthome.binding.lifx.internal.LifxLightDiscovery$1.run(LifxLightDiscovery.java:303)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
From the code, it is not clear to me how the selector can be closed at that point, so I don't really know how to fix it.
@kgoderis Do you have any bright idea?

**Comment by kgoderis** [comment]
mmmh... While revisiting the code I noticed that a concurrency issue on the selector exists when a number of discovery scans are fired rapidly after each other, e,g. within the 10 second timeout set in the scan loop.
