### ISSUE TITLE
Cannot create rules using Paper UI / configuration broken

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#1801]
My intention was to test #1683 but it seems it is not possible for me to use the trigger to create rules using the Paper UI.

I added two triggers (two item state change triggers on the first try, two item state update triggers on the second try) to the rule and tried to save the rule.
I see an error on the console log.

I have used the Firefox to create that rules.

```
git rev-parse HEAD
8aea602d7adee12e5008ef065d27adad8337d8eb
```

```text
22:01:32.790 INFO  smarthome.event.RuleAddedEvent[:43] - Rule 'rule_1' has been added.
22:01:32.790 DEBUG o.e.s.a.c.internal.RuleEngine[:219] - Added rule 'rule_1'
22:01:32.795 INFO  s.event.RuleStatusInfoEvent[:43] - rule_1 updated: NOT_INITIALIZED
22:01:32.795 DEBUG o.e.s.a.c.i.c.CompositeModuleHandlerFactory[:101] - create composite module:trigger_1, of rule: rule_1
22:01:32.798 WARN  o.e.s.a.c.i.ReferenceResolverUtil[:232] - Cannot find reference for ${ itemName } , it will remain the same.
22:01:32.806 DEBUG o.e.s.a.c.i.c.CompositeModuleHandlerFactory[:132] - Set handler to child module: org.eclipse.smarthome.automation.core.internal.RuntimeTrigger@2b769047  -> CompositeTriggerHandler.
22:01:32.808 DEBUG o.e.s.a.c.i.c.CompositeModuleHandlerFactory[:101] - create composite module:trigger_2, of rule: rule_1
22:01:32.809 WARN  o.e.s.a.c.i.ReferenceResolverUtil[:232] - Cannot find reference for ${ itemName } , it will remain the same.
22:01:32.810 DEBUG o.e.s.a.c.i.c.CompositeModuleHandlerFactory[:132] - Set handler to child module: org.eclipse.smarthome.automation.core.internal.RuntimeTrigger@4b13be54  -> CompositeTriggerHandler.
22:01:32.829 ERROR o.e.s.a.c.i.RuleRegistryImpl[:236] - Can't add rule: rule_1
java.lang.RuntimeException: Missing required parameter: itemName of type ItemStateChangeTrigger
	at org.eclipse.smarthome.automation.core.internal.RuleEngine.setDefaultConfigurationValues(RuleEngine.java:1290)
	at org.eclipse.smarthome.automation.core.internal.RuleEngine.setRule(RuleEngine.java:356)
	at org.eclipse.smarthome.automation.core.internal.RuleEngine.setRuleEnabled(RuleEngine.java:702)
	at org.eclipse.smarthome.automation.core.internal.RuleEngine.addRule0(RuleEngine.java:221)
	at org.eclipse.smarthome.automation.core.internal.RuleEngine.addRule(RuleEngine.java:201)
	at org.eclipse.smarthome.automation.core.internal.RuleRegistryImpl.onAddElement(RuleRegistryImpl.java:231)
	at org.eclipse.smarthome.automation.core.internal.RuleRegistryImpl.onAddElement(RuleRegistryImpl.java:1)
	at org.eclipse.smarthome.core.common.registry.AbstractRegistry.added(AbstractRegistry.java:56)
	at org.eclipse.smarthome.core.common.registry.AbstractProvider.notifyListeners(AbstractProvider.java:51)
	at org.eclipse.smarthome.core.common.registry.AbstractProvider.notifyListeners(AbstractProvider.java:70)
	at org.eclipse.smarthome.core.common.registry.AbstractProvider.notifyListenersAboutAddedElement(AbstractProvider.java:74)
22:01:32.830 DEBUG o.e.s.c.c.r.AbstractManagedProvider[:62] - Added new element rule_1 to ManagedRuleProvider.
```

```text
22:03:41.515 DEBUG o.e.s.a.c.internal.RuleEngine[:310] - Updated rule 'rule_1'.
22:03:41.516 DEBUG o.e.s.a.c.i.c.CompositeModuleHandlerFactory[:101] - create composite module:trigger_4, of rule: rule_1
22:03:41.518 DEBUG o.e.s.a.c.i.c.CompositeModuleHandlerFactory[:132] - Set handler to child module: org.eclipse.smarthome.automation.core.internal.RuntimeTrigger@35269352  -> CompositeTriggerHandler.
22:03:41.519 DEBUG o.e.s.a.c.i.c.CompositeModuleHandlerFactory[:101] - create composite module:trigger_5, of rule: rule_1
22:03:41.520 DEBUG o.e.s.a.c.i.c.CompositeModuleHandlerFactory[:132] - Set handler to child module: org.eclipse.smarthome.automation.core.internal.RuntimeTrigger@211e61a4  -> CompositeTriggerHandler.
22:03:41.523 WARN  o.e.s.c.c.r.AbstractRegistry[:104] - Could not update element: Missing required parameter: itemName of type ItemStateUpdateTrigger
java.lang.RuntimeException: Missing required parameter: itemName of type ItemStateUpdateTrigger
	at org.eclipse.smarthome.automation.core.internal.RuleEngine.setDefaultConfigurationValues(RuleEngine.java:1290)
	at org.eclipse.smarthome.automation.core.internal.RuleEngine.setRule(RuleEngine.java:356)
	at org.eclipse.smarthome.automation.core.internal.RuleEngine.updateRule(RuleEngine.java:318)
	at org.eclipse.smarthome.automation.core.internal.RuleRegistryImpl.onUpdateElement(RuleRegistryImpl.java:291)
	at org.eclipse.smarthome.automation.core.internal.RuleRegistryImpl.onUpdateElement(RuleRegistryImpl.java:1)
	at org.eclipse.smarthome.core.common.registry.AbstractRegistry.updated(AbstractRegistry.java:99)
	at org.eclipse.smarthome.core.common.registry.AbstractProvider.notifyListeners(AbstractProvider.java:57)
	at org.eclipse.smarthome.core.common.registry.AbstractProvider.notifyListenersAboutUpdatedElement(AbstractProvider.java:82)
	at org.eclipse.smarthome.core.common.registry.AbstractManagedProvider.update(AbstractManagedProvider.java:134)
	at org.eclipse.smarthome.core.common.registry.AbstractRegistry.update(AbstractRegistry.java:122)
	at org.eclipse.smarthome.automation.rest.internal.RuleResource.update(RuleResource.java:163)
22:03:41.524 DEBUG o.e.s.c.c.r.AbstractManagedProvider[:135] - Updated element rule_1 in ManagedRuleProvider.
```

**Comment by maggu2810** [comment]
That is the POST data of the PUT method: 

```text
{"tags":[],"conditions":[],"name":"Test","triggers":[{"id":"trigger_4","label":"Item State Update Trigger","description":"This triggers a rule if an items state updated","type":"ItemStateUpdateTrigger","configuration":{"properties":{},"itemName":"ITEM_SWITCH_0"}},{"id":"trigger_5","label":"Item State Update Trigger","description":"This triggers a rule if an items state updated","type":"ItemStateUpdateTrigger","configuration":{"properties":{},"itemName":"ITEM_SWITCH_1"}}],"configDescriptions":[],"actions":[],"uid":"rule_1"}
```

That is the content of the GET method:

```text
[{"enabled":true,"status":{"status":"NOT_INITIALIZED","statusDetail":"NONE"},"configuration":{},"actions":[{"id":"action_3","label":"Script action","description":"allows the execution of a user-defined script","configuration":{"properties":{}},"type":"ScriptAction"}],"conditions":[],"configDescriptions":[],"triggers":[{"id":"trigger_1","label":"Item State Change Trigger","description":"This triggers a rule if an items state changed","configuration":{"properties":{}},"type":"ItemStateChangeTrigger"},{"id":"trigger_2","label":"Item State Change Trigger","description":"This triggers a rule if an items state changed","configuration":{"properties":{}},"type":"ItemStateChangeTrigger"}],"uid":"rule_1","name":"Test","tags":[]}]
```

**Comment by maggu2810** [comment]
This format is generated by the Paper UI

```json
{
  "tags": [],
  "conditions": [],
  "name": "TEST",
  "triggers": [
    {
      "id": "trigger_1",
      "label": "Item State Change Trigger",
      "description": "This triggers a rule if an items state changed",
      "type": "ItemStateChangeTrigger",
      "configuration": {
        "properties": {},
        "itemName": "DemoSwitch"
      }
    }
  ],
  "configDescriptions": [],
  "actions": [],
  "uid": "rule_1"
}
```

If I move the itemName from "configuration" to "configuration.properties"

```json
{
  "tags": [],
  "conditions": [],
  "name": "TEST",
  "triggers": [
    {
      "id": "trigger_1",
      "label": "Item State Change Trigger",
      "description": "This triggers a rule if an items state changed",
      "type": "ItemStateChangeTrigger",
      "configuration": {
        "properties": {
          "itemName": "DemoSwitch"
        }
      }
    }
  ],
  "configDescriptions": [],
  "actions": [],
  "uid": "rule_1"
}
```

it seems to be working.

**Comment by maggu2810** [comment]
The Configuration object is used by different classes.
IIRC we never used a subelement "properties" for the configuration key value pairs.

Why do we need to use that for rules?

**Comment by aounhaider1** [comment]
PaperUI is not setting the properties field. It is returned in the response when a rule is requested. I think something is broken on the server side. I also tried posting these triggers with itemName set. The post clearly shows that itemName is posted. But on the server side it is unable to find itemName.

**Comment by maggu2810** [comment]
It seems to me, that we are using DTO objects for JSON (de)serialization.
This is not be done for the REST Rule API.

Here a map is used for the configuration and we translate between the map and the Configuration class object:
https://github.com/eclipse/smarthome/blob/master/bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/dto/ThingDTO.java#L29

For the Rule REST API the Rule class is used directly and so the Configuration class, too.
https://github.com/eclipse/smarthome/blob/master/bundles/automation/org.eclipse.smarthome.automation.rest/src/main/java/org/eclipse/smarthome/automation/rest/internal/RuleResource.java#L162

As the key value pair of the Configuration class are set in the member properties of the Configuration class I assume that causes the need of the properties field.

It seems to me that the migration of the Rule API to use the Configuration class is not finished and we are now in a state where the REST API is broken.

What to do?

**Comment by kaikreuzer** [comment]
@maggu2810 This sounds to me as if your merge of https://github.com/eclipse/smarthome/pull/1773 was a bit too optimistic...?

**Comment by maggu2810** [comment]
There is a EnrichedRuleDTO, but no rule DTO is used on add new or change existing rules.

#1773 does not break the REST API itself, but perhaps it does not fix it.
The REST API does not use a DTO object but the Rule class.
This has not been changed by #1773. Using the Rule class for JSON (de)serialization causes the error IMHO.

But you are right, it was perhaps too optimistic to think that the changes are complete.

**Comment by maggu2810** [comment]
> #1773 does not break the REST API itself, but perhaps it does not fix it.
The REST API does not use a DTO object but the Rule class.

See "Rule rule" argument here:
https://github.com/eclipse/smarthome/pull/1773/files#diff-204438a2e20a2f84ce7ddfb5194e2335L162

**Comment by kaikreuzer** [comment]
#1773 was supposed to fix https://github.com/eclipse/smarthome/issues/1724#issuecomment-229049208, but it obviously does not.

@danchom Could you please join in?

**Comment by danchom** [comment]
I'll check this

**Comment by maggu2810** [comment]
@danchom Have a look at #1816, I already implemented "something"
