### ISSUE TITLE
ModelRepository startup issue

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#1823]
Unfortunately https://github.com/eclipse/smarthome/pull/1821 didn't yet fully solve the issue.
On the latest builds, I get this exception at startup time:

```
09:06:42.729 [ERROR] [xt.xbase.jvmmodel.JvmModelAssociator] - Error calling inferrer
java.lang.IllegalStateException: ScriptServiceUtil not initialized yet!
	at org.eclipse.smarthome.model.script.ScriptServiceUtil.getInstance(ScriptServiceUtil.java:85)
	at org.eclipse.smarthome.model.script.ScriptServiceUtil.getItemRegistry(ScriptServiceUtil.java:91)
	at org.eclipse.smarthome.model.script.internal.engine.ServiceTrackerItemRegistryProvider.get(ServiceTrackerItemRegistryProvider.java:29)
	at org.eclipse.smarthome.model.script.internal.engine.ServiceTrackerItemRegistryProvider.get(ServiceTrackerItemRegistryProvider.java:1)
	at org.eclipse.smarthome.model.rule.jvmmodel.RulesJvmModelInferrer$1.apply(RulesJvmModelInferrer.java:166)
	at org.eclipse.smarthome.model.rule.jvmmodel.RulesJvmModelInferrer$1.apply(RulesJvmModelInferrer.java:1)
	at org.eclipse.xtext.xbase.jvmmodel.JvmModelAssociator$1.run(JvmModelAssociator.java:397)
	at org.eclipse.xtext.xbase.jvmmodel.JvmModelAssociator.installDerivedState(JvmModelAssociator.java:407)
	at org.eclipse.xtext.resource.DerivedStateAwareResource.installDerivedState(DerivedStateAwareResource.java:242)
	at org.eclipse.xtext.xbase.resource.BatchLinkableResource.getContents(BatchLinkableResource.java:148)
	at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.getModel(ModelRepositoryImpl.java:61)
	at org.eclipse.smarthome.model.rule.runtime.internal.engine.RuleEngineImpl.activate(RuleEngineImpl.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)[:1.8.0_40]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)[:1.8.0_40]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[:1.8.0_40]
	at java.lang.reflect.Method.invoke(Method.java:497)[:1.8.0_40]
	at org.apache.felix.scr.impl.helper.BaseMethod.invokeMethod(BaseMethod.java:222)
	at org.apache.felix.scr.impl.helper.BaseMethod.access$500(BaseMethod.java:37)
	at org.apache.felix.scr.impl.helper.BaseMethod$Resolved.invoke(BaseMethod.java:615)
	at org.apache.felix.scr.impl.helper.BaseMethod.invoke(BaseMethod.java:499)
	at org.apache.felix.scr.impl.helper.ActivateMethod.invoke(ActivateMethod.java:295)
```

**Comment by kaikreuzer** [comment]
Why do you think it has to do with the doSetup?

I cannot really understand the exception yet. It occurs when the RuleEngineImpl is activated. As RuleEngine depends on ScriptEngine and ScriptEngine depends on ScriptServiceUtil, I would have assumed that SSU.activate() has already been executed at that point. Do you have an explanation, why this isn't the case?

**Comment by kaikreuzer** [comment]
Nonetheless, the exception also shows that ModelRepository has a (yet undeclared) dependency on SSU - but if we declare this dependency, we will end up with another cycle...

> If it is working, perhaps we should not touch them and hope that the implementation will move to be based on the automation stuff. What do you think?

Well, it is not working yet, so we have to touch the implementation :-/
And even by moving to the new rule engine, we will still need most of the services as they are needed for the Xtext processing, so I doubt that we will win much. So let's try to get this all straight.

**Comment by kaikreuzer** [comment]
FTR, I am also getting exceptions like this, where I have no clue what they mean:
```
10:41:52.939 [ERROR] [xbase.resource.BatchLinkableResource] - resolution of uriFragment '|84' failed.
java.lang.IndexOutOfBoundsException: Index: 84, Size: 84
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)[:1.8.0_40]
	at java.util.ArrayList.get(ArrayList.java:429)[:1.8.0_40]
	at org.eclipse.xtext.linking.lazy.LazyLinkingResource.hasLazyProxyInformation(LazyLinkingResource.java:502)[134:org.eclipse.xtext:2.9.2]
	at org.eclipse.xtext.linking.lazy.LazyLinkingResource.getLazyProxyInformation(LazyLinkingResource.java:509)[134:org.eclipse.xtext:2.9.2]
	at org.eclipse.xtext.linking.lazy.LazyURIEncoder.getLazyProxyInformation(LazyURIEncoder.java:148)[134:org.eclipse.xtext:2.9.2]
	at org.eclipse.xtext.linking.lazy.LazyURIEncoder.decode(LazyURIEncoder.java:127)[134:org.eclipse.xtext:2.9.2]
	at org.eclipse.xtext.xbase.resource.BatchLinkableResource.getEObject(BatchLinkableResource.java:113)[138:org.eclipse.xtext.xbase:2.9.2.v20160428-1452]
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.getEObject(ResourceSetImpl.java:223)[63:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
	at org.eclipse.emf.ecore.util.EcoreUtil.resolve(EcoreUtil.java:199)[63:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
	at org.eclipse.emf.ecore.util.EcoreUtil.resolve(EcoreUtil.java:259)[63:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
	at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eResolveProxy(BasicEObjectImpl.java:1477)[63:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
	at org.eclipse.xtext.xbase.impl.XAbstractFeatureCallImplCustom.getFeature(XAbstractFeatureCallImplCustom.java:48)[138:org.eclipse.xtext.xbase:2.9.2.v20160428-1452]
	at org.eclipse.xtext.xbase.impl.XAbstractFeatureCallImplCustom.isStatic(XAbstractFeatureCallImplCustom.java:151)[138:org.eclipse.xtext.xbase:2.9.2.v20160428-1452]
	at org.eclipse.xtext.xbase.impl.XAbstractFeatureCallImplCustom.getActualReceiver(XAbstractFeatureCallImplCustom.java:167)[138:org.eclipse.xtext.xbase:2.9.2.v20160428-1452]
	at org.eclipse.xtext.xbase.impl.XMemberFeatureCallImplCustom.getActualReceiver(XMemberFeatureCallImplCustom.java:53)[138:org.eclipse.xtext.xbase:2.9.2.v20160428-1452]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.getActualReceiver(XbaseInterpreter.java:983)[138:org.eclipse.xtext.xbase:2.9.2.v20160428-1452]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter._doEvaluate(XbaseInterpreter.java:758)[138:org.eclipse.xtext.xbase:2.9.2.v20160428-1452]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.doEvaluate(XbaseInterpreter.java:219)[138:org.eclipse.xtext.xbase:2.9.2.v20160428-1452]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.internalEvaluate(XbaseInterpreter.java:203)[138:org.eclipse.xtext.xbase:2.9.2.v20160428-1452]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter._doEvaluate(XbaseInterpreter.java:759)[138:org.eclipse.xtext.xbase:2.9.2.v20160428-1452]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.doEvaluate(XbaseInterpreter.java:219)[138:org.eclipse.xtext.xbase:2.9.2.v20160428-1452]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.internalEvaluate(XbaseInterpreter.java:203)[138:org.eclipse.xtext.xbase:2.9.2.v20160428-1452]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter._doEvaluate(XbaseInterpreter.java:446)[138:org.eclipse.xtext.xbase:2.9.2.v20160428-1452]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.doEvaluate(XbaseInterpreter.java:227)[138:org.eclipse.xtext.xbase:2.9.2.v20160428-1452]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.internalEvaluate(XbaseInterpreter.java:203)[138:org.eclipse.xtext.xbase:2.9.2.v20160428-1452]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.evaluate(XbaseInterpreter.java:189)[138:org.eclipse.xtext.xbase:2.9.2.v20160428-1452]
	at org.eclipse.smarthome.model.script.runtime.internal.engine.ScriptImpl.execute(ScriptImpl.java:77)[123:org.eclipse.smarthome.model.script.runtime:0.9.0.201607061527]
	at org.eclipse.smarthome.model.rule.runtime.internal.engine.RuleEngineImpl.runStartupRules(RuleEngineImpl.java:276)[121:org.eclipse.smarthome.model.rule.runtime:0.9.0.201607061527]
```

**Comment by maggu2810** [comment]
> RuleEngine depends on ScriptEngine

You know that it is a dynamic one?

**Comment by kaikreuzer** [comment]
1..1 - doesn't that also mean that it has to be set before activate is called, even in the dynamic case?

**Comment by kaikreuzer** [comment]
Ok, so this is indeed a wrong order:
```
10:50:35.021 [DEBUG] [org.eclipse.smarthome.model.core    ] - ServiceEvent REGISTERED - {org.eclipse.smarthome.model.core.ModelRepository}={component.name=org.eclipse.smarthome.model.core.repository, component.id=180, service.id=297, service.bundleid=115, service.scope=bundle} - org.eclipse.smarthome.model.core
10:50:35.398 [DEBUG] [eclipse.smarthome.model.rule.runtime] - ServiceEvent REGISTERED - {org.eclipse.smarthome.core.events.EventSubscriber, org.eclipse.smarthome.model.rule.runtime.RuleEngine}={component.name=org.eclipse.smarthome.model.ruleengine, component.id=81, service.id=307, service.bundleid=121, service.scope=bundle} - org.eclipse.smarthome.model.rule.runtime
10:50:35.398 [DEBUG] [lipse.smarthome.model.script.runtime] - ServiceEvent REGISTERED - {org.eclipse.smarthome.model.script.engine.ScriptEngine}={component.name=org.eclipse.smarthome.model.script, component.id=87, service.id=306, service.bundleid=123, service.scope=bundle} - org.eclipse.smarthome.model.script.runtime
10:50:35.401 [DEBUG] [org.eclipse.smarthome.model.script  ] - ServiceEvent REGISTERED - {org.eclipse.smarthome.io.console.extensions.ConsoleCommandExtension}={component.name=org.eclipse.smarthome.model.script.engine.consolecommandextension, component.id=85, service.id=308, service.bundleid=122, service.scope=bundle} - org.eclipse.smarthome.model.script
10:50:35.403 [DEBUG] [org.eclipse.smarthome.model.script  ] - ServiceEvent REGISTERED - {org.eclipse.smarthome.model.script.ScriptServiceUtil}={component.name=org.eclipse.smarthome.model.script.ScriptServiceUtil, component.id=84, service.id=305, service.bundleid=122, service.scope=bundle} - org.eclipse.smarthome.model.script
```

RuleEngine is started before ScriptEngine - so you think changing dynamic to static would solve this?

**Comment by maggu2810** [comment]
I have read the section in the compendium spec. I would assume that it should be set before the activate method is called. But the spec starts with "The dynamic policy is slightly more complex", so perhaps I need some more rounds of reading. :wink:

**Comment by kaikreuzer** [comment]
Yeah, the spec isn't really clear - but I understand it the way that dynamic only means that you might get another service being set when you are already activated. Well, but in any case, switching to static won't hurt...

**Comment by Marty56** [comment]
I do not know whether this is related. I have 8 different rule files and I am seeing that randomly two rules are never been loaded. It seems like the old OP1.x bugs which could be worked arround by touching the rule files with a script.
If this is not related then I would open a different issue.

**Comment by kaikreuzer** [comment]
I cannot tell. But please only open a new issue, if you have an easy way to reproduce it (e.g. provide some dummy rules that can be dropped in the system and which only do logging and thus show, which ones are loaded/executed and which ones aren't.
