### ISSUE TITLE
SmartHome Runtime error: unresolved compilation problems

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#1884]
Have not used the "SmartHome Runtime" in the IDE for a while.
Is this (see log) a local error on my machine or does this occur on other systems, too?

```text
19:12:00.416 DEBUG o.e.s.m.i.r.i.ItemRuntimeActivator[:21] - Registered 'item' configuration parser
19:12:00.466 INFO  o.q.impl.StdSchedulerFactory[:1184] - Using default implementation for ThreadExecutor
19:12:00.469 INFO  o.q.simpl.SimpleThreadPool[:268] - Job execution threads will use class loader of thread: Component Resolve Thread
19:12:00.499 INFO  o.q.core.SchedulerSignalerImpl[:61] - Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
19:12:00.500 INFO  o.quartz.core.QuartzScheduler[:240] - Quartz Scheduler v.2.2.1 created.
19:12:00.501 INFO  org.quartz.simpl.RAMJobStore[:155] - RAMJobStore initialized.
19:12:00.502 INFO  o.quartz.core.QuartzScheduler[:305] - Scheduler meta-data: Quartz Scheduler (v2.2.1) 'DefaultQuartzScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 10 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.

19:12:00.502 INFO  o.q.impl.StdSchedulerFactory[:1339] - Quartz scheduler 'DefaultQuartzScheduler' initialized from default resource file in Quartz package: 'quartz.properties'
19:12:00.502 INFO  o.q.impl.StdSchedulerFactory[:1343] - Quartz scheduler version: 2.2.1
!SESSION 2016-07-19 19:11:58.538 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_92
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -application 
Command-line arguments:  -application  -data /home/rathgeb/bin/pkgs/eclipse/esh/ws/../smarthome-runtime -dev file:/home/rathgeb/bin/pkgs/eclipse/esh/ws/.metadata/.plugins/org.eclipse.pde.core/SmartHome Runtime/dev.properties -os linux -ws gtk -arch x86_64 -consoleLog -console

!ENTRY org.eclipse.equinox.ds 1 0 2016-07-19 19:12:00.506
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.core.persistence.manager. The reference is: Reference[name = ModelRepository, interface = org.eclipse.smarthome.model.core.ModelRepository, policy = dynamic, cardinality = 0..1, target = null, bind = setModelRepository, unbind = unsetModelRepository]

!ENTRY org.eclipse.equinox.ds 1 0 2016-07-19 19:12:00.506
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.core.persistence.manager. The reference is: Reference[name = PersistenceService, interface = org.eclipse.smarthome.core.persistence.PersistenceService, policy = dynamic, cardinality = 0..n, target = null, bind = addPersistenceService, unbind = removePersistenceService]

!ENTRY org.eclipse.equinox.ds 1 0 2016-07-19 19:12:00.507
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.core.persistence.manager. The reference is: Reference[name = ItemRegistry, interface = org.eclipse.smarthome.core.items.ItemRegistry, policy = dynamic, cardinality = 0..1, target = null, bind = setItemRegistry, unbind = unsetItemRegistry]

!ENTRY org.eclipse.equinox.ds 1 0 2016-07-19 19:12:00.513
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.model.persistence.extensions. The reference is: Reference[name = PersistenceService, interface = org.eclipse.smarthome.core.persistence.PersistenceService, policy = dynamic, cardinality = 0..n, target = null, bind = addPersistenceService, unbind = removePersistenceService]
19:12:00.673 DEBUG o.e.s.m.p.r.i.PersistenceRuntimeActivator[:21] - Registered 'persistence' configuration parser
19:12:01.499 DEBUG o.e.s.m.r.r.i.RuleRuntimeActivator[:27] - Registered 'rule' configuration parser
19:12:01.575 DEBUG o.e.s.m.s.r.i.SitemapRuntimeActivator[:21] - Registered 'sitemap' configuration parser
19:12:01.619 DEBUG o.e.s.m.t.r.i.ThingRuntimeActivator[:21] - Registered 'thing' configuration parser
osgi> 
!ENTRY org.eclipse.equinox.ds 1 0 2016-07-19 19:12:02.556
!MESSAGE Could not bind a reference of component ConfigDescriptionRegistry. The reference is: Reference[name = ConfigOptionProvider, interface = org.eclipse.smarthome.config.core.ConfigOptionProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addConfigOptionProvider, unbind = removeConfigOptionProvider]

!ENTRY org.eclipse.equinox.ds 1 0 2016-07-19 19:12:02.557
!MESSAGE Could not bind a reference of component ConfigDescriptionRegistry. The reference is: Reference[name = ConfigDescriptionProvider, interface = org.eclipse.smarthome.config.core.ConfigDescriptionProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addConfigDescriptionProvider, unbind = removeConfigDescriptionProvider]

!ENTRY org.eclipse.equinox.ds 1 0 2016-07-19 19:12:02.570
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.config.discovery.internal.DiscoveryServiceRegistry. The reference is: Reference[name = DiscoveryService, interface = org.eclipse.smarthome.config.discovery.DiscoveryService, policy = dynamic, cardinality = 0..n, target = null, bind = addDiscoveryService, unbind = removeDiscoveryService]
19:12:02.599 ERROR o.e.s.c.d.i.ConfigDispatcher[:98] - Cannot activate folder watcher for folder 'conf/services': conf/services
19:12:02.599 DEBUG o.e.s.c.d.i.ConfigDispatcher[:222] - Processing config file 'smarthome.cfg'
19:12:02.745 DEBUG o.e.s.c.d.i.ConfigDispatcher[:203] - Configuration folder 'conf/services' does not exist.
19:12:02.964 DEBUG o.e.s.c.i.PortableBase64[:172] - PortableBase64 class is running on JavaSE >=8
19:12:02.965 DEBUG o.e.s.c.internal.CoreActivator[:31] - Core bundle has been started.

!ENTRY org.eclipse.equinox.ds 1 0 2016-07-19 19:12:03.013
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.core.binding.BindingInfoRegistry. The reference is: Reference[name = BindingInfoProvider, interface = org.eclipse.smarthome.core.binding.BindingInfoProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addBindingInfoProvider, unbind = removeBindingInfoProvider]

!ENTRY org.eclipse.equinox.ds 1 0 2016-07-19 19:12:03.037
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.core.itemregistry. The reference is: Reference[name = ItemProvider, interface = org.eclipse.smarthome.core.items.ItemProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addProvider, unbind = removeProvider]

!ENTRY org.eclipse.equinox.ds 1 0 2016-07-19 19:12:03.038
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.core.itemregistry. The reference is: Reference[name = ManagedItemProvider, interface = org.eclipse.smarthome.core.items.ManagedItemProvider, policy = dynamic, cardinality = 0..1, target = null, bind = setManagedProvider, unbind = removeManagedProvider]
19:12:03.048 DEBUG o.e.s.c.i.i.LocaleProviderImpl[:47] - No language set, fallback to default system locale
19:12:03.186 DEBUG o.e.s.c.c.ThreadPoolManager[:145] - Created thread pool 'ConfigStatusService' with size 5

!ENTRY org.eclipse.equinox.ds 1 0 2016-07-19 19:12:03.187
!MESSAGE Could not bind a reference of component ConfigStatusService. The reference is: Reference[name = ConfigStatusProvider, interface = org.eclipse.smarthome.config.core.status.ConfigStatusProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addConfigStatusProvider, unbind = removeConfigStatusProvider]
19:12:03.192 WARN  o.e.s.c.c.ThreadPoolManager[:88] - Ignoring invalid configuration for pool 'safeCall': 3,10 - value must be an integer
19:12:03.197 DEBUG o.e.s.c.a.i.AutoUpdateActivator[:29] - AutoUpdate binding has been started.
19:12:03.203 DEBUG o.e.s.c.x.o.XmlDocumentBundleTracker[:126] - Reading the XML document '/ESH-INF/config/locale.xml' in module 'org.eclipse.smarthome.core'...
19:12:03.281 DEBUG o.e.s.c.x.o.XmlDocumentBundleTracker[:177] - Create an empty XmlDocumentProvider for the module 'org.eclipse.smarthome.core'.

!ENTRY org.eclipse.smarthome.core.scheduler 4 0 2016-07-19 19:12:03.377
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Error starting module.
	at org.eclipse.osgi.container.Module.doStart(Module.java:580)
	at org.eclipse.osgi.container.Module.start(Module.java:439)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1562)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1476)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
Caused by: java.lang.Error: Unresolved compilation problems: 
	The type org.slf4j.Logger cannot be resolved. It is indirectly referenced from required .class files
	The import org.osgi cannot be resolved
	The import org.osgi cannot be resolved
	The import org.slf4j.Logger cannot be resolved
	The import org.slf4j.LoggerFactory cannot be resolved
	BundleActivator cannot be resolved to a type
	Logger cannot be resolved to a type
	LoggerFactory cannot be resolved
	BundleContext cannot be resolved to a type
	BundleContext cannot be resolved to a type
	BundleContext cannot be resolved to a type
	Logger cannot be resolved to a type
	Logger cannot be resolved to a type
	BundleContext cannot be resolved to a type
	BundleContext cannot be resolved to a type
	Logger cannot be resolved to a type
	Logger cannot be resolved to a type
	BundleContext cannot be resolved to a type
	BundleContext cannot be resolved to a type

	at org.eclipse.smarthome.core.scheduler.internal.SchedulerActivator.<init>(SchedulerActivator.java:1)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.loadBundleActivator(BundleContextImpl.java:755)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:706)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:936)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:319)
	at org.eclipse.osgi.container.Module.doStart(Module.java:571)
	... 8 more
Root exception:
java.lang.Error: Unresolved compilation problems: 
	The type org.slf4j.Logger cannot be resolved. It is indirectly referenced from required .class files
	The import org.osgi cannot be resolved
	The import org.osgi cannot be resolved
	The import org.slf4j.Logger cannot be resolved
	The import org.slf4j.LoggerFactory cannot be resolved
	BundleActivator cannot be resolved to a type
	Logger cannot be resolved to a type
	LoggerFactory cannot be resolved
	BundleContext cannot be resolved to a type
	BundleContext cannot be resolved to a type
	BundleContext cannot be resolved to a type
	Logger cannot be resolved to a type
	Logger cannot be resolved to a type
	BundleContext cannot be resolved to a type
	BundleContext cannot be resolved to a type
	Logger cannot be resolved to a type
	Logger cannot be resolved to a type
	BundleContext cannot be resolved to a type
	BundleContext cannot be resolved to a type

	at org.eclipse.smarthome.core.scheduler.internal.SchedulerActivator.<init>(SchedulerActivator.java:1)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.loadBundleActivator(BundleContextImpl.java:755)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:706)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:936)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:319)
	at org.eclipse.osgi.container.Module.doStart(Module.java:571)
	at org.eclipse.osgi.container.Module.start(Module.java:439)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1562)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1476)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)

!ENTRY org.eclipse.equinox.ds 1 0 2016-07-19 19:12:03.397
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.core.thing.type.ChannelTypeRegistry. The reference is: Reference[name = ChannelTypeProvider, interface = org.eclipse.smarthome.core.thing.type.ChannelTypeProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addChannelTypeProvider, unbind = removeChannelTypeProvider]

!ENTRY org.eclipse.equinox.ds 1 0 2016-07-19 19:12:03.408
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.core.thing.firmware.FirmwareRegistry. The reference is: Reference[name = FirmwareProvider, interface = org.eclipse.smarthome.core.thing.firmware.FirmwareProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addFirmwareProvider, unbind = removeFirmwareProvider]
19:12:03.410 DEBUG o.e.s.c.c.ThreadPoolManager[:115] - Created scheduled thread pool 'FirmwareUpdateService' of size 5

!ENTRY org.eclipse.equinox.ds 1 0 2016-07-19 19:12:03.412
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.core.thing.firmware.FirmwareUpdateService. The reference is: Reference[name = FirmwareUpdateHandler, interface = org.eclipse.smarthome.core.thing.binding.firmware.FirmwareUpdateHandler, policy = dynamic, cardinality = 0..n, target = null, bind = addFirmwareUpdateHandler, unbind = removeFirmwareUpdateHandler]
19:12:03.412 DEBUG o.e.s.c.t.f.FirmwareUpdateService[:67] - Running firmware status check.

!ENTRY org.eclipse.equinox.ds 1 0 2016-07-19 19:12:03.414
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.core.thing.internal.console.FirmwareUpdateConsoleCommandExtension. The reference is: Reference[name = FirmwareUpdateHandler, interface = org.eclipse.smarthome.core.thing.binding.firmware.FirmwareUpdateHandler, policy = dynamic, cardinality = 0..n, target = null, bind = addFirmwareUpdateHandler, unbind = removeFirmwareUpdateHandler]

!ENTRY org.eclipse.equinox.ds 1 0 2016-07-19 19:12:03.421
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.core.thing.ThingRegistry. The reference is: Reference[name = ThingProvider, interface = org.eclipse.smarthome.core.thing.ThingProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addProvider, unbind = removeProvider]

!ENTRY org.eclipse.equinox.ds 1 0 2016-07-19 19:12:03.421
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.core.thing.ThingRegistry. The reference is: Reference[name = ManagedThingProvider, interface = org.eclipse.smarthome.core.thing.ManagedThingProvider, policy = dynamic, cardinality = 0..1, target = null, bind = setManagedProvider, unbind = removeManagedProvider]

!ENTRY org.eclipse.equinox.ds 1 0 2016-07-19 19:12:03.423
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.core.thing.ThingRegistry. The reference is: Reference[name = ThingHandlerFactory, interface = org.eclipse.smarthome.core.thing.binding.ThingHandlerFactory, policy = dynamic, cardinality = 0..n, target = null, bind = addThingHandlerFactory, unbind = removeThingHandlerFactory]

!ENTRY org.eclipse.equinox.ds 1 0 2016-07-19 19:12:03.425
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.core.thing.link.ItemChannelLinkRegistry. The reference is: Reference[name = ItemChannelLinkProvider, interface = org.eclipse.smarthome.core.thing.link.ItemChannelLinkProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addProvider, unbind = removeProvider]

!ENTRY org.eclipse.equinox.ds 1 0 2016-07-19 19:12:03.425
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.core.thing.link.ItemChannelLinkRegistry. The reference is: Reference[name = ManagedItemChannelLinkProvider, interface = org.eclipse.smarthome.core.thing.link.ManagedItemChannelLinkProvider, policy = dynamic, cardinality = 0..1, target = null, bind = setManagedProvider, unbind = removeManagedProvider]
19:12:03.428 DEBUG o.e.s.c.t.i.ChannelItemProvider[:144] - Enabling channel item provider.
19:12:03.429 DEBUG o.e.s.c.c.r.AbstractRegistry[:192] - Provider 'org.eclipse.smarthome.core.thing.internal.ChannelItemProvider' has been added.

!ENTRY org.eclipse.equinox.ds 1 0 2016-07-19 19:12:03.431
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.core.thing.type.ThingTypeRegistry. The reference is: Reference[name = ThingTypeProvider, interface = org.eclipse.smarthome.core.thing.binding.ThingTypeProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addThingTypeProvider, unbind = removeThingTypeProvider]
19:12:03.439 DEBUG o.e.s.c.x.o.XmlDocumentBundleTracker[:126] - Reading the XML document '/ESH-INF/config/config.xml' in module 'org.eclipse.smarthome.core.thing'...
19:12:03.442 DEBUG o.e.s.c.x.o.XmlDocumentBundleTracker[:177] - Create an empty XmlDocumentProvider for the module 'org.eclipse.smarthome.core.thing'.
19:12:03.482 DEBUG o.e.s.c.t.i.TransformationActivator[:34] - Transformation Service has been started.
19:12:03.515 DEBUG o.e.s.i.r.i.RESTActivator[:72] - REST API has been started.

!ENTRY org.eclipse.equinox.ds 1 0 2016-07-19 19:12:03.525
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.io.rest.root. The reference is: Reference[name = RESTResource, interface = org.eclipse.smarthome.io.rest.RESTResource, policy = dynamic, cardinality = 0..n, target = null, bind = addRESTResource, unbind = removeRESTResource]

!ENTRY org.eclipse.equinox.ds 1 0 2016-07-19 19:12:03.555
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.core.persistence.internal.rest. The reference is: Reference[name = PersistenceService, interface = org.eclipse.smarthome.core.persistence.PersistenceService, policy = dynamic, cardinality = 0..n, target = null, bind = addPersistenceService, unbind = removePersistenceService]
19:12:03.564 DEBUG o.e.s.i.r.s.i.SseActivator[:46] - SSE API - SseFeature registered.
19:12:03.566 DEBUG o.e.s.i.r.s.i.SseActivator[:55] - SSE API has been started.
19:12:03.667 DEBUG o.e.s.s.m.MapDbStorageService[:50] - Opened MapDB file at '/home/rathgeb/bin/pkgs/eclipse/esh/git/smarthome/distribution/smarthome/userdata/mapdb/storage.mapdb'.
19:12:03.710 DEBUG o.e.s.c.c.r.AbstractRegistry[:192] - Provider 'org.eclipse.smarthome.core.items.ManagedItemProvider' has been added.
19:12:03.738 DEBUG o.e.s.c.c.r.AbstractRegistry[:192] - Provider 'org.eclipse.smarthome.core.thing.link.ManagedItemChannelLinkProvider' has been added.
19:12:03.753 DEBUG o.e.s.c.c.r.AbstractRegistry[:192] - Provider 'org.eclipse.smarthome.core.thing.ManagedThingProvider' has been added.

!ENTRY org.eclipse.equinox.ds 1 0 2016-07-19 19:12:03.762
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.config.discovery.inbox.Inbox. The reference is: Reference[name = ThingHandlerFactory, interface = org.eclipse.smarthome.core.thing.binding.ThingHandlerFactory, policy = dynamic, cardinality = 0..n, target = null, bind = addThingHandlerFactory, unbind = removeThingHandlerFactory]
19:12:03.764 DEBUG o.e.s.c.c.ThreadPoolManager[:115] - Created scheduled thread pool 'discovery' of size 3
19:12:03.809 DEBUG o.e.s.c.c.ThreadPoolManager[:115] - Created scheduled thread pool 'thingManager' of size 5

!ENTRY org.eclipse.equinox.ds 1 0 2016-07-19 19:12:03.811
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.core.thing.internal.ThingManager. The reference is: Reference[name = ThingHandlerFactory, interface = org.eclipse.smarthome.core.thing.binding.ThingHandlerFactory, policy = dynamic, cardinality = 0..n, target = null, bind = addThingHandlerFactory, unbind = removeThingHandlerFactory]

!ENTRY org.eclipse.equinox.ds 1 0 2016-07-19 19:12:03.869
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.ui. The reference is: Reference[name = ItemUIProvider, interface = org.eclipse.smarthome.ui.items.ItemUIProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addItemUIProvider, unbind = removeItemUIProvider]

!ENTRY org.eclipse.equinox.ds 1 0 2016-07-19 19:12:03.870
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.io.rest.sitemap. The reference is: Reference[name = SitemapProvider, interface = org.eclipse.smarthome.model.sitemap.SitemapProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addSitemapProvider, unbind = removeSitemapProvider]

!ENTRY org.eclipse.equinox.ds 1 0 2016-07-19 19:12:03.880
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.ui.chart. The reference is: Reference[name = ChartProvider, interface = org.eclipse.smarthome.ui.chart.ChartProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addChartProvider, unbind = removeChartProvider]
19:12:03.881 DEBUG o.e.s.u.i.chart.ChartServlet[:119] - Starting up chart servlet at /chart

!ENTRY org.eclipse.equinox.ds 1 0 2016-07-19 19:12:03.886
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.ui.chart.defaultprovider. The reference is: Reference[name = PersistenceService, interface = org.eclipse.smarthome.core.persistence.PersistenceService, policy = dynamic, cardinality = 0..n, target = null, bind = addPersistenceService, unbind = removePersistenceService]
19:12:03.886 DEBUG o.e.s.u.i.c.DefaultChartProvider[:97] - Starting up default chart provider.
19:12:03.911 DEBUG o.e.s.u.b.i.servlet.CmdServlet[:56] - Starting up CMD servlet at /basicui/CMD
19:12:03.952 DEBUG o.e.s.c.x.o.XmlDocumentBundleTracker[:126] - Reading the XML document '/ESH-INF/config/config.xml' in module 'org.eclipse.smarthome.ui.basic'...
19:12:03.957 DEBUG o.e.s.c.x.o.XmlDocumentBundleTracker[:177] - Create an empty XmlDocumentProvider for the module 'org.eclipse.smarthome.ui.basic'.

!ENTRY org.eclipse.equinox.ds 1 0 2016-07-19 19:12:03.979
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.ui.classic.pagerenderer. The reference is: Reference[name = WidgetRenderer, interface = org.eclipse.smarthome.ui.classic.render.WidgetRenderer, policy = dynamic, cardinality = 0..n, target = null, bind = addWidgetRenderer, unbind = removeWidgetRenderer]
19:12:03.981 DEBUG o.e.s.u.c.i.servlet.CmdServlet[:56] - Starting up CMD servlet at /classicui/CMD
19:12:04.042 DEBUG o.e.s.c.x.o.XmlDocumentBundleTracker[:126] - Reading the XML document '/ESH-INF/config/config.xml' in module 'org.eclipse.smarthome.ui.classic'...
19:12:04.044 DEBUG o.e.s.c.x.o.XmlDocumentBundleTracker[:177] - Create an empty XmlDocumentProvider for the module 'org.eclipse.smarthome.ui.classic'.
19:12:04.045 DEBUG o.e.s.u.i.internal.IconServlet[:76] - Starting up icon servlet at /icon
19:12:04.073 INFO  o.e.s.u.p.internal.PaperUIApp[:31] - Started Paper UI at /ui
19:12:04.149 DEBUG o.e.s.c.c.r.AbstractRegistry[:192] - Provider 'org.eclipse.smarthome.model.item.internal.GenericItemProvider' has been added.
19:12:04.376 DEBUG o.e.s.m.s.r.i.e.ScriptEngineImpl[:60] - Registered 'script' configuration parser
19:12:04.384 INFO  o.quartz.core.QuartzScheduler[:2311] - JobFactory set to: org.eclipse.smarthome.model.rule.runtime.internal.engine.GuiceAwareJobFactory@27f8546c
19:12:04.385 DEBUG o.e.s.m.r.r.i.e.RuleEngineImpl[:96] - Started rule engine
19:12:04.393 INFO  o.e.s.u.b.i.s.WebAppServlet[:88] - Started Basic UI at /basicui/app
19:12:04.398 INFO  o.e.s.u.c.i.s.WebAppServlet[:84] - Started Classic UI at /classicui/app
19:12:04.401 DEBUG o.e.s.c.c.r.AbstractRegistry[:192] - Provider 'org.eclipse.smarthome.model.thing.internal.GenericItemChannelLinkProvider' has been added.

!ENTRY org.eclipse.equinox.ds 1 0 2016-07-19 19:12:04.411
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.model.thing.internal.genericthingprovider. The reference is: Reference[name = ThingHandlerFactory, interface = org.eclipse.smarthome.core.thing.binding.ThingHandlerFactory, policy = dynamic, cardinality = 0..n, target = null, bind = addThingHandlerFactory, unbind = removeThingHandlerFactory]
19:12:04.412 DEBUG o.e.s.c.c.r.AbstractRegistry[:192] - Provider 'org.eclipse.smarthome.model.thing.internal.GenericThingProvider' has been added.
19:12:04.423 DEBUG o.e.s.u.i.proxy.ProxyServlet[:94] - Starting up proxy servlet at /proxy
19:12:04.452 WARN  o.e.s.m.c.i.f.FolderObserver[:171] - Directory 'scripts' does not exist in 'conf'. Please check your configuration settings!
19:12:04.537 INFO  o.e.s.m.c.i.ModelRepositoryImpl[:92] - Loading model 'demo.sitemap'
19:12:04.704 INFO  o.e.s.m.c.i.ModelRepositoryImpl[:92] - Loading model 'demo.things'
19:12:04.744 DEBUG o.e.s.m.t.i.GenericThingProvider[:232] - Read things from model 'demo.things'
19:12:04.776 INFO  o.e.s.m.c.i.ModelRepositoryImpl[:92] - Loading model 'logging.persist'
19:12:04.801 INFO  o.e.s.m.c.i.ModelRepositoryImpl[:92] - Loading model 'demo.rules'
19:12:04.994 INFO  o.e.s.m.c.i.ModelRepositoryImpl[:92] - Loading model 'demo.items'
19:12:05.008 DEBUG o.e.s.m.i.i.GenericItemProvider[:151] - Processing binding configs for items from model 'demo.items'
19:12:05.021 DEBUG o.e.s.m.i.i.GenericItemProvider[:130] - Read items from model 'demo.items'
19:12:05.039 DEBUG o.e.s.c.c.ThreadPoolManager[:145] - Created thread pool 'safeCall' with size 5
19:12:05.040 INFO  s.e.ItemChannelLinkAddedEvent[:43] - Link 'Weather_Temperature-yahooweather:weather:berlin:temperature' has been added.
19:12:10.026 DEBUG o.e.s.m.r.r.i.e.RuleEngineImpl[:268] - Executing startup rule 'Initialize demo items'
19:12:10.502 INFO  smarthome.event.ItemStateEvent[:43] - DemoLocation updated to 52,9
19:12:10.505 DEBUG o.e.s.c.c.ThreadPoolManager[:145] - Created thread pool 'items' with size 5
19:12:10.509 INFO  smarthome.event.ItemStateEvent[:43] - DemoContact updated to OPEN
19:12:10.511 INFO  smarthome.event.ItemStateEvent[:43] - DemoString updated to Hello SmartHome!
19:12:10.515 INFO  smarthome.event.ItemStateEvent[:43] - DemoDateTime updated to 2016-07-19T19:12:10.504+0200
19:12:10.518 INFO  s.event.ItemStateChangedEvent[:43] - DemoLocation changed from NULL to 52,9
19:12:10.521 INFO  s.event.ItemStateChangedEvent[:43] - DemoContact changed from NULL to OPEN
19:12:10.521 INFO  s.event.ItemStateChangedEvent[:43] - DemoString changed from NULL to Hello SmartHome!
19:12:10.524 INFO  s.event.ItemStateChangedEvent[:43] - DemoDateTime changed from NULL to 2016-07-19T19:12:10.504+0200
```

**Comment by kaikreuzer** [comment]
It works for me. Your log looks to me as if some of the projects are not built (or possibly cleaned/built by Maven). Did you try to re-compile all projects in the workspace?

**Comment by maggu2810** [comment]
> It works for me.

Okay, fine. Then I will try to clean up my local environment.
I already run the "perform setup task" and cleaned (and build) all projects in the IDE.

If it is working on your machine, I am pretty sure that the repo is in a good shape.
Thanks for your feedback.
