### ISSUE TITLE
XmlDocumentBundleTracker exception at startup

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#1926]
Using offline snapshot 426, I got this error at startup:
```
22:15:32.272 [ERROR] [ig.xml.osgi.XmlDocumentBundleTracker] - Could not send adding finished event for the module 'org.eclipse.smarthome.binding.hue'!
java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)[:1.8.0]
        at java.util.HashMap$EntryIterator.next(HashMap.java:1463)[:1.8.0]
        at java.util.HashMap$EntryIterator.next(HashMap.java:1461)[:1.8.0]
        at org.eclipse.smarthome.core.thing.xml.internal.XmlChannelTypeProvider.removeCachedChannelTypes(XmlChannelTypeProvider.java:382)[104:org.eclipse.smarthome.core.thing.xml:0.9.0.201607221840]
        at org.eclipse.smarthome.core.thing.xml.internal.XmlChannelTypeProvider.addChannelType(XmlChannelTypeProvider.java:130)[104:org.eclipse.smarthome.core.thing.xml:0.9.0.201607221840]
        at org.eclipse.smarthome.core.thing.xml.internal.ThingTypeXmlProvider.addingFinished(ThingTypeXmlProvider.java:135)[104:org.eclipse.smarthome.core.thing.xml:0.9.0.201607221840]
        at org.eclipse.smarthome.config.xml.osgi.XmlDocumentBundleTracker.addingFinished(XmlDocumentBundleTracker.java:220)[96:org.eclipse.smarthome.config.xml:0.9.0.201607221840]
        at org.eclipse.smarthome.config.xml.osgi.XmlDocumentBundleTracker.access$6(XmlDocumentBundleTracker.java:215)[96:org.eclipse.smarthome.config.xml:0.9.0.201607221840]
        at org.eclipse.smarthome.config.xml.osgi.XmlDocumentBundleTracker$1.processBundle(XmlDocumentBundleTracker.java:141)[96:org.eclipse.smarthome.config.xml:0.9.0.201607221840]
        at org.eclipse.smarthome.config.xml.osgi.AbstractAsyncBundleProcessor$1.run(AbstractAsyncBundleProcessor.java:231)[96:org.eclipse.smarthome.config.xml:0.9.0.201607221840]
        at java.lang.Thread.run(Thread.java:744)[:1.8.0]
```

**Comment by lolodomo** [comment]
It is not systematic.
