### ISSUE TITLE
Sonos binding: playing a playlist failed

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#1942]
Here is the exception:
```
14:16:12.930 [DEBUG] [.io.transport.upnp.UpnpIOServiceImpl] - Invoking Action 'Browse' of service 'ContentDirectory' for participant 'RINCON_000E588EAE6601400'
[Fatal Error] :1:1: Fin prÃ©maturÃ©e du fichier.
14:16:12.988 [DEBUG] [inding.sonos.internal.SonosXMLParser] - Failed to parse embeded
org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Fin prÃ©maturÃ©e du fichier.
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1239)[:1.8.0]
        at org.eclipse.smarthome.binding.sonos.internal.SonosXMLParser.getResourceMetaData(SonosXMLParser.java:131)[207:org.eclipse.smarthome.binding.sonos:0.9.0.201607301055]
        at org.eclipse.smarthome.binding.sonos.internal.SonosXMLParser$EntryHandler.endElement(SonosXMLParser.java:337)[207:org.eclipse.smarthome.binding.sonos:0.9.0.201607301055]
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)[:1.8.0]
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1781)[:1.8.0]
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2957)[:1.8.0]
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)[:1.8.0]
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)[:1.8.0]
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)[:1.8.0]
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)[:1.8.0]
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)[:1.8.0]
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)[:1.8.0]
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)[:1.8.0]
        at org.eclipse.smarthome.binding.sonos.internal.SonosXMLParser.getEntriesFromString(SonosXMLParser.java:108)[207:org.eclipse.smarthome.binding.sonos:0.9.0.201607301055]
        at org.eclipse.smarthome.binding.sonos.handler.ZonePlayerHandler.getEntries(ZonePlayerHandler.java:1036)[207:org.eclipse.smarthome.binding.sonos:0.9.0.201607301055]
        at org.eclipse.smarthome.binding.sonos.handler.ZonePlayerHandler.getPlayLists(ZonePlayerHandler.java:996)[207:org.eclipse.smarthome.binding.sonos:0.9.0.201607301055]
        at org.eclipse.smarthome.binding.sonos.handler.ZonePlayerHandler.playPlayList(ZonePlayerHandler.java:2279)[207:org.eclipse.smarthome.binding.sonos:0.9.0.201607301055]
        at org.eclipse.smarthome.binding.sonos.handler.ZonePlayerHandler.handleCommand(ZonePlayerHandler.java:274)[207:org.eclipse.smarthome.binding.sonos:0.9.0.201607301055]
        at org.eclipse.smarthome.core.thing.internal.ThingManager$2.call(ThingManager.java:395)[102:org.eclipse.smarthome.core.thing:0.9.0.201607271614]
        at org.eclipse.smarthome.core.thing.internal.ThingManager$2.call(ThingManager.java:1)[102:org.eclipse.smarthome.core.thing:0.9.0.201607271614]
        at org.eclipse.smarthome.core.common.SafeMethodCaller$CallableWrapper.call(SafeMethodCaller.java:177)[96:org.eclipse.smarthome.core:0.9.0.201607271614]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0]
        at java.lang.Thread.run(Thread.java:744)[:1.8.0]
```

**Comment by lolodomo** [comment]
Probably due to escaped characters ?

**Comment by lolodomo** [comment]
Items are added in the queue but mixed with the items already present in the queue.

And these items are not readable. When playing the item from the Sonos application, the track is read less than one second and then it goes to the next item.

**Comment by kgoderis** [comment]
We already has a similar issue in the past. It was solved but it seems it occurs again at other places

**Comment by lolodomo** [comment]
The items are finally added at the beginning of the queue. Random playback was enabled, that explained the random order I saw..

If I used a playlist with only classic characters, I get the exception but finally the items are added to the queue and the playback is started as expected.

So the only problem seems to be with playlists containing special characters.

**Comment by lolodomo** [comment]
@kgoderis : it is something I already fought with when updating the Vera Sonos plugin.
I will take a look.

**Comment by lolodomo** [comment]
The exception was the same as the one described in issue #1944.

The other problem I fixed is that it is necessary to change the current URI to switch to the queue. If not it was working only if current URI was pointing to the queue.

I will provide a PR when my previous PR is merged.

**Comment by lolodomo** [comment]
PR #1957 will fix this issue.

**Comment by lolodomo** [comment]
PR fixing this issue is now merged.
