### ISSUE TITLE
Sonos binding: playing a radio leads to an exception (XML parsing error)

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#1944]
Here is the exception:
```
2016-07-30 14:27:17.131 [DEBUG] [.io.transport.upnp.UpnpIOServiceImpl] - Invoking Action 'Browse' of service 'ContentDirectory' for participant 'RINCON_000E588EAE6601400'
2016-07-30 14:27:17.190 [DEBUG] [inding.sonos.internal.SonosXMLParser] - Failed to parse embeded
org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Fin prÃ©maturÃ©e du fichier.
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1239)[:1.8.0]
        at org.eclipse.smarthome.binding.sonos.internal.SonosXMLParser.getResourceMetaData(SonosXMLParser.java:131)[207:org.eclipse.smarthome.binding.sonos:0.9.0.201607301055]
        at org.eclipse.smarthome.binding.sonos.internal.SonosXMLParser$EntryHandler.endElement(SonosXMLParser.java:337)[207:org.eclipse.smarthome.binding.sonos:0.9.0.201607301055]
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)[:1.8.0]
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1781)[:1.8.0]
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2957)[:1.8.0]
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)[:1.8.0]
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)[:1.8.0]
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)[:1.8.0]
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)[:1.8.0]
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)[:1.8.0]
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)[:1.8.0]
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)[:1.8.0]
        at org.eclipse.smarthome.binding.sonos.internal.SonosXMLParser.getEntriesFromString(SonosXMLParser.java:108)[207:org.eclipse.smarthome.binding.sonos:0.9.0.201607301055]
        at org.eclipse.smarthome.binding.sonos.handler.ZonePlayerHandler.getEntries(ZonePlayerHandler.java:1036)[207:org.eclipse.smarthome.binding.sonos:0.9.0.201607301055]
        at org.eclipse.smarthome.binding.sonos.handler.ZonePlayerHandler.getFavoriteRadios(ZonePlayerHandler.java:1004)[207:org.eclipse.smarthome.binding.sonos:0.9.0.201607301055]
        at org.eclipse.smarthome.binding.sonos.handler.ZonePlayerHandler.playRadio(ZonePlayerHandler.java:2174)[207:org.eclipse.smarthome.binding.sonos:0.9.0.201607301055]
        at org.eclipse.smarthome.binding.sonos.handler.ZonePlayerHandler.handleCommand(ZonePlayerHandler.java:250)[207:org.eclipse.smarthome.binding.sonos:0.9.0.201607301055]
        at org.eclipse.smarthome.core.thing.internal.ThingManager$2.call(ThingManager.java:395)[102:org.eclipse.smarthome.core.thing:0.9.0.201607271614]
        at org.eclipse.smarthome.core.thing.internal.ThingManager$2.call(ThingManager.java:1)[102:org.eclipse.smarthome.core.thing:0.9.0.201607271614]
        at org.eclipse.smarthome.core.common.SafeMethodCaller$CallableWrapper.call(SafeMethodCaller.java:177)[96:org.eclipse.smarthome.core:0.9.0.201607271614]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0]
        at java.lang.Thread.run(Thread.java:744)[:1.8.0]
```

**Comment by lolodomo** [comment]
Probably due to escaped characters ?
The name of one of my radios has a non ASCII character.

**Comment by lolodomo** [comment]
I fixed this issue, there was a missing catch for the exception.
Will provide a PR when my previous PR is merged.

I am still having a problem to select a radio with special characters (accents) in the name. But maybe that is more a problem in my rule ? Here is my rule code:
```
SonosChambreRadio2.sendCommand("OÛI FM")
```
There is no matching, maybe a question of encoding ?

**Comment by lolodomo** [comment]
Regarding my problem of accents, I checked that this call returns true (as expected) :
```
someStation.getTitle().equals("OÜI FM")
```
But this one returns false:
```
String station = command.toString();
station.equals("OÜI FM")
```
So I don't think the problem is inside the binding but how you have to handle non ASCII character sin rule when setting an item.

**Comment by lolodomo** [comment]
If I change my rule like that:
```
		SonosChambreRadio2.sendCommand("OÛI FM".encode("UTF-8"))
```
Then the following code:
```
            String station = command.toString();
            logger.debug("playRadio searched station {} {}", station, station.equals("OÜI FM"));
```
returns:
```
11:48:52.577 [DEBUG] [ding.sonos.handler.ZonePlayerHandler] - playRadio searched station O%C3%9BI+FM false
```

**Comment by lolodomo** [comment]
Is the problem with "command.toString()" that will not build a string independently of its original encoding ?

PS: Command object is coming from handleCommand

**Comment by lolodomo** [comment]
What stupid I am, I was not using the right letter in the rule !
I suppressed my previous messages.

**Comment by lolodomo** [comment]
PR #1957 will fix this issue.

**Comment by lolodomo** [comment]
PR fixing this issue is now merged.
