### ISSUE TITLE
Build broken since Aug 11

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#2003]
The ESH nightly build is broken since Aug 11, see https://hudson.eclipse.org/smarthome/job/SmartHomeDistribution-Nightly/buildTimeTrend

@maggu2810 & @sjka, did you already analyze what exactly is wrong?
It seems that many failures are due to FirmwareUpdateServiceOSGiTest - @tomhoefer maybe you could check why this is failing?

**Comment by tomhoefer** [comment]
@maggu2810 has already created #1992 for this purpose... I will check why the test fails

**Comment by kaikreuzer** [comment]
Thanks @tomhoefer, the firmware tests seem to pass now.

Now there is a problem with io.net.tests. The log entry is:
```
!SESSION 2016-08-16 06:15:13.597 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.7.0_80
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -application org.eclipse.tycho.surefire.osgibooter.headlesstest -testproperties /jobs/genie.smarthome/SmartHomeDistribution-Nightly/workspace/bundles/io/org.eclipse.smarthome.io.net.test/target/surefire.properties
Command-line arguments:  -data /jobs/genie.smarthome/SmartHomeDistribution-Nightly/workspace/bundles/io/org.eclipse.smarthome.io.net.test/target/work/data -application org.eclipse.tycho.surefire.osgibooter.headlesstest -testproperties /jobs/genie.smarthome/SmartHomeDistribution-Nightly/workspace/bundles/io/org.eclipse.smarthome.io.net.test/target/surefire.properties

!ENTRY org.eclipse.jetty.util 2 0 2016-08-16 06:15:17.723
!MESSAGE Could not resolve module: org.eclipse.jetty.util [76]
  Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=1.8))"


!ENTRY org.eclipse.smarthome.io.net 2 0 2016-08-16 06:15:17.725
!MESSAGE Could not resolve module: org.eclipse.smarthome.io.net [82]
  Unresolved requirement: Import-Package: org.eclipse.jetty.client
    -> Export-Package: org.eclipse.jetty.client; bundle-version="9.3.9.v20160517"; bundle-symbolic-name="org.eclipse.jetty.client"; version="9.3.9"; uses:="org.eclipse.jetty.client.api,org.eclipse.jetty.client.util,org.eclipse.jetty.http,org.eclipse.jetty.io,org.eclipse.jetty.util,org.eclipse.jetty.util.annotation,org.eclipse.jetty.util.component,org.eclipse.jetty.util.log,org.eclipse.jetty.util.ssl,org.eclipse.jetty.util.thread"
       org.eclipse.jetty.client [73]
         Unresolved requirement: Import-Package: org.eclipse.jetty.http; version="[9.3.9,9.3.10)"
           -> Export-Package: org.eclipse.jetty.http; bundle-version="9.3.9.v20160517"; bundle-symbolic-name="org.eclipse.jetty.http"; version="9.3.9"; uses:="org.eclipse.jetty.util,org.eclipse.jetty.util.log,org.eclipse.jetty.util.resource"
              org.eclipse.jetty.http [74]
                Unresolved requirement: Import-Package: org.eclipse.jetty.util; version="[9.3.9,9.3.10)"
                  -> Export-Package: org.eclipse.jetty.util; bundle-version="9.3.9.v20160517"; bundle-symbolic-name="org.eclipse.jetty.util"; version="9.3.9"; uses:="javax.servlet,javax.servlet.http,org.eclipse.jetty.util.annotation,org.eclipse.jetty.util.component,org.eclipse.jetty.util.log,org.eclipse.jetty.util.resource,org.eclipse.jetty.util.thread"
                     org.eclipse.jetty.util [76]
                       Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=1.8))"


!ENTRY org.eclipse.jetty.client 2 0 2016-08-16 06:15:17.725
!MESSAGE Could not resolve module: org.eclipse.jetty.client [73]
  Unresolved requirement: Import-Package: org.eclipse.jetty.http; version="[9.3.9,9.3.10)"
    -> Export-Package: org.eclipse.jetty.http; bundle-version="9.3.9.v20160517"; bundle-symbolic-name="org.eclipse.jetty.http"; version="9.3.9"; uses:="org.eclipse.jetty.util,org.eclipse.jetty.util.log,org.eclipse.jetty.util.resource"
       org.eclipse.jetty.http [74]
         Unresolved requirement: Import-Package: org.eclipse.jetty.util; version="[9.3.9,9.3.10)"
           -> Export-Package: org.eclipse.jetty.util; bundle-version="9.3.9.v20160517"; bundle-symbolic-name="org.eclipse.jetty.util"; version="9.3.9"; uses:="javax.servlet,javax.servlet.http,org.eclipse.jetty.util.annotation,org.eclipse.jetty.util.component,org.eclipse.jetty.util.log,org.eclipse.jetty.util.resource,org.eclipse.jetty.util.thread"
              org.eclipse.jetty.util [76]
                Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=1.8))"


!ENTRY org.eclipse.jetty.http 2 0 2016-08-16 06:15:17.726
!MESSAGE Could not resolve module: org.eclipse.jetty.http [74]
  Unresolved requirement: Import-Package: org.eclipse.jetty.util; version="[9.3.9,9.3.10)"
    -> Export-Package: org.eclipse.jetty.util; bundle-version="9.3.9.v20160517"; bundle-symbolic-name="org.eclipse.jetty.util"; version="9.3.9"; uses:="javax.servlet,javax.servlet.http,org.eclipse.jetty.util.annotation,org.eclipse.jetty.util.component,org.eclipse.jetty.util.log,org.eclipse.jetty.util.resource,org.eclipse.jetty.util.thread"
       org.eclipse.jetty.util [76]
         Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=1.8))"


!ENTRY org.eclipse.jetty.io 2 0 2016-08-16 06:15:17.726
!MESSAGE Could not resolve module: org.eclipse.jetty.io [75]
  Unresolved requirement: Import-Package: org.eclipse.jetty.util; version="[9.3.9,9.3.10)"
    -> Export-Package: org.eclipse.jetty.util; bundle-version="9.3.9.v20160517"; bundle-symbolic-name="org.eclipse.jetty.util"; version="9.3.9"; uses:="javax.servlet,javax.servlet.http,org.eclipse.jetty.util.annotation,org.eclipse.jetty.util.component,org.eclipse.jetty.util.log,org.eclipse.jetty.util.resource,org.eclipse.jetty.util.thread"
       org.eclipse.jetty.util [76]
         Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=1.8))"


!ENTRY org.eclipse.smarthome.io.net.test 2 0 2016-08-16 06:15:17.726
!MESSAGE Could not resolve module: org.eclipse.smarthome.io.net.test [86]
  Unresolved requirement: Fragment-Host: org.eclipse.smarthome.io.net
    -> Bundle-SymbolicName: org.eclipse.smarthome.io.net; bundle-version="0.9.0.201608161007"
       org.eclipse.smarthome.io.net [82]
         Unresolved requirement: Import-Package: org.eclipse.jetty.client
           -> Export-Package: org.eclipse.jetty.client; bundle-version="9.3.9.v20160517"; bundle-symbolic-name="org.eclipse.jetty.client"; version="9.3.9"; uses:="org.eclipse.jetty.client.api,org.eclipse.jetty.client.util,org.eclipse.jetty.http,org.eclipse.jetty.io,org.eclipse.jetty.util,org.eclipse.jetty.util.annotation,org.eclipse.jetty.util.component,org.eclipse.jetty.util.log,org.eclipse.jetty.util.ssl,org.eclipse.jetty.util.thread"
              org.eclipse.jetty.client [73]
                Unresolved requirement: Import-Package: org.eclipse.jetty.http; version="[9.3.9,9.3.10)"
                  -> Export-Package: org.eclipse.jetty.http; bundle-version="9.3.9.v20160517"; bundle-symbolic-name="org.eclipse.jetty.http"; version="9.3.9"; uses:="org.eclipse.jetty.util,org.eclipse.jetty.util.log,org.eclipse.jetty.util.resource"
                     org.eclipse.jetty.http [74]
                       Unresolved requirement: Import-Package: org.eclipse.jetty.util; version="[9.3.9,9.3.10)"
                         -> Export-Package: org.eclipse.jetty.util; bundle-version="9.3.9.v20160517"; bundle-symbolic-name="org.eclipse.jetty.util"; version="9.3.9"; uses:="javax.servlet,javax.servlet.http,org.eclipse.jetty.util.annotation,org.eclipse.jetty.util.component,org.eclipse.jetty.util.log,org.eclipse.jetty.util.resource,org.eclipse.jetty.util.thread"
                            org.eclipse.jetty.util [76]
                              Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=1.8))"


!ENTRY org.eclipse.osgi 4 0 2016-08-16 06:15:17.727
!MESSAGE Application error
!STACK 1
java.lang.RuntimeException: Bundle org.eclipse.smarthome.io.net.test is not found
	at org.eclipse.tycho.surefire.osgibooter.OsgiSurefireBooter.getBundleClassLoader(OsgiSurefireBooter.java:162)
	at org.eclipse.tycho.surefire.osgibooter.OsgiSurefireBooter.createCombinedClassLoader(OsgiSurefireBooter.java:98)
	at org.eclipse.tycho.surefire.osgibooter.OsgiSurefireBooter.run(OsgiSurefireBooter.java:91)
	at org.eclipse.tycho.surefire.osgibooter.HeadlessTestApplication.run(HeadlessTestApplication.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.eclipse.equinox.internal.app.EclipseAppContainer.callMethodWithException(EclipseAppContainer.java:587)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:198)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:382)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:236)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1438)
```

@svilenvul I would assume this is related to the Jetty HTTP client PR. Is the test execution through Maven working for you? Could you please check how it could be fixed?

**Comment by tomhoefer** [comment]
I just recognized that the fix is not complete... I have to provide an additional PR

**Comment by tomhoefer** [comment]
Ah... it is complete... the failing local test was because of a PR to be contribuetd for initial determination of the firmware status...

**Comment by svilenvul** [comment]
@kaikreuzer 
Locally in Maven there are no problems. We had no problems in the integration build as well...
I guess this is the reason - https://www.eclipse.org/jetty/documentation/9.3.x/what-jetty-version.html.  Jetty 9.3 requires Java 1.8 at runtime.
Should I change to version in the target platform to 9.2 ?

**Comment by maggu2810** [comment]
> Now there is a problem with io.net.tests

The automation module timer test is still present, too. See https://github.com/eclipse/smarthome/issues/1757#issuecomment-240083571

**Comment by kaikreuzer** [comment]
> Should I change to version in the target platform to 9.2 ?

@svilenvul, Hoping that all code still compiles (i.e. you do not use any 9.3 features), this is probably the best thing to do, yes.

**Comment by maggu2810** [comment]
And another one: #2011

**Comment by kaikreuzer** [comment]
[Build 1253](https://hudson.eclipse.org/smarthome/job/SmartHomeDistribution-Nightly/1253/) is green again, so I am closing this issue.
