### ISSUE TITLE
Test failure(s): automation.integration.test.AutomationIntegrationTest.assert that a rule based on a composite modules is initialized and executed correctly

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#2011]
``` text
assert that a rule based on a composite modules is initialized and executed correctly(org.eclipse.smarthome.automation.integration.test.AutomationIntegrationTest)  Time elapsed: 10.742 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: is <IDLE>
     but: was <NOT_INITIALIZED>
    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
    at org.junit.Assert.assertThat(Assert.java:865)
    at org.junit.Assert.assertThat(Assert.java:832)
    at org.junit.Assert$assertThat.callStatic(Unknown Source)
    at org.eclipse.smarthome.automation.integration.test.AutomationIntegrationTest$_assert_that_a_rule_based_on_a_composite_modules_is_initialized_and_executed_correctly_closure22.doCall(AutomationIntegrationTest.groovy:363)
    at org.eclipse.smarthome.automation.integration.test.AutomationIntegrationTest$_assert_that_a_rule_based_on_a_composite_modules_is_initialized_and_executed_correctly_closure22.doCall(AutomationIntegrationTest.groovy)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
    at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:278)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
    at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
    at org.eclipse.smarthome.test.OSGiTest.waitForAssert(OSGiTest.groovy:181)
    at org.eclipse.smarthome.test.OSGiTest.waitForAssert(OSGiTest.groovy)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:207)
    at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:56)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:141)
    at org.eclipse.smarthome.automation.integration.test.AutomationIntegrationTest.assert that a rule based on a composite modules is initialized and executed correctly(AutomationIntegrationTest.groovy:362)
```

`Hudson, SmartHomeDistribution-Nightly: Failed Build #1252 (Aug 17, 2016 11:01:41 AM)`

[SmartHomeDistribution-Nightly.1252.consoleText.txt](https://github.com/eclipse/smarthome/files/422951/SmartHomeDistribution-Nightly.1252.consoleText.txt)

**Comment by kaikreuzer** [comment]
@BenediktNiehues & @marinmitev As you are the two authors mentioned in this test, could you please help fixing it asap? Note that #2003 depends on it.

**Comment by kaikreuzer** [comment]
FTR: Latest build is green again, so this does not seem to be a blocking, but an irregularly occurring test failure - I hence reduced the urgency of it.
