### ISSUE TITLE
Hue: handling of "Umlaut" not correct

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#2177]
I connected a Hue bridge to an ESH system.
Instead of "Küche" (the german word for Kitchen) I see `K��che`.

So I assume the reading is not done using the correct charset.

**Comment by tomhoefer** [comment]
@maggu2810 can you pls explain for which entity you receive the "wrong" kitchen value? For the name of a light?

**Comment by maggu2810** [comment]
Yes, it has been the name.
I tried to do the same again:

Hi, I am using a slightly modified the normal SmartHome launch configuration
* add plugin: org.eclipse.smarthome.binding.hue
* add plugin: org.eclipse.smarthome.io.transport.upnp
* add plugin: org.jupnp (set auto-start to default)

* open Paper UI in the browser
* the "Hue Bridge" has been detected
* Add as Thing
* Press link button on the bridge
* There are new entries in the Inbox
* The entry in the inbox shows correct "Umlaut"
* Apply the inbox entry also shows the "Umlaut" correct for the name

I don't know if there has been some changes but now it seems to work.
Tested it using Chrome and Firefox and "gulp serve --development" for the Paper UI.

I don't remember if I detected the error on a RPi system or on my local machine.
I will check the RPi system again, if the error depends on the system locale.

FYI:
After adding the Hue bridge as thing (immediately, so before I can press the link button) I also received an Stacktrace (I can open another issue if this should be fixed).
```text
10:02:31.909 DEBUG o.e.s.b.h.h.HueBridgeHandler[:222] - Initializing hue bridge handler.
10:02:32.131 DEBUG o.e.s.c.d.i.DiscoveryServiceRegistryImpl[:353] - Trying to start 2 scans with an aggregating listener.
10:02:32.132 DEBUG o.e.s.c.d.i.DiscoveryServiceRegistryImpl[:378] - Triggering scan for thing types '[hue:bridge]' on 'UpnpDiscoveryService'...
10:02:32.134 DEBUG o.e.s.c.d.i.PersistentInbox[:194] - Discovery result with thing 'hue:bridge:001788280c33' not added as inbox entry. It is already present as thing in the ThingRegistry.
10:02:32.144 DEBUG o.e.s.c.d.i.DiscoveryServiceRegistryImpl[:378] - Triggering scan for thing types '[hue:0200, hue:0100, hue:0210, hue:0220, hue:0000]' on 'HueLightDiscoveryService'...
10:02:32.145 INFO  o.e.s.b.h.h.HueBridgeHandler[:327] - Creating new user on Hue bridge 10.10.10.72 - please press the pairing button on the bridge.
10:02:32.168 DEBUG o.e.s.b.h.h.HueBridgeHandler[:355] - Failed creating new user on Hue bridge: link button not pressed
10:02:32.170 INFO  s.event.ThingStatusInfoEvent[:43] - 'hue:bridge:001788280c33' updated: OFFLINE (CONFIGURATION_ERROR): Not authenticated - press pairing button on the bridge.
10:02:32.174 INFO  s.e.ThingStatusInfoChangedEvent[:43] - 'hue:bridge:001788280c33' changed from INITIALIZING to OFFLINE (CONFIGURATION_ERROR): Not authenticated - press pairing button on the bridge.
10:02:32.195 ERROR o.e.s.b.h.h.HueBridgeHandler[:405] - Bridge cannot search for new lights.
java.lang.IllegalStateException: linking is required before interacting with the bridge
	at nl.q42.jue.HueBridge.requireAuthentication(HueBridge.java:783)
	at nl.q42.jue.HueBridge.getFullConfig(HueBridge.java:771)
	at org.eclipse.smarthome.binding.hue.handler.HueBridgeHandler.getFullLights(HueBridgeHandler.java:402)
	at org.eclipse.smarthome.binding.hue.internal.discovery.HueLightDiscoveryService.startScan(HueLightDiscoveryService.java:83)
	at org.eclipse.smarthome.config.discovery.AbstractDiscoveryService.startScan(AbstractDiscoveryService.java:199)
	at org.eclipse.smarthome.config.discovery.internal.DiscoveryServiceRegistryImpl.startScan(DiscoveryServiceRegistryImpl.java:381)
	at org.eclipse.smarthome.config.discovery.internal.DiscoveryServiceRegistryImpl.startScans(DiscoveryServiceRegistryImpl.java:357)
	at org.eclipse.smarthome.config.discovery.internal.DiscoveryServiceRegistryImpl.startScan(DiscoveryServiceRegistryImpl.java:216)
	at org.eclipse.smarthome.io.rest.core.discovery.DiscoveryResource.scan(DiscoveryResource.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
10:02:32.200 ERROR o.e.s.b.h.h.HueBridgeHandler[:416] - Bridge cannot start search mode
java.lang.IllegalStateException: linking is required before interacting with the bridge
	at nl.q42.jue.HueBridge.requireAuthentication(HueBridge.java:783)
	at nl.q42.jue.HueBridge.startSearch(HueBridge.java:155)
	at org.eclipse.smarthome.binding.hue.handler.HueBridgeHandler.startSearch(HueBridgeHandler.java:414)
	at org.eclipse.smarthome.binding.hue.internal.discovery.HueLightDiscoveryService.startScan(HueLightDiscoveryService.java:90)
	at org.eclipse.smarthome.config.discovery.AbstractDiscoveryService.startScan(AbstractDiscoveryService.java:199)
	at org.eclipse.smarthome.config.discovery.internal.DiscoveryServiceRegistryImpl.startScan(DiscoveryServiceRegistryImpl.java:381)
	at org.eclipse.smarthome.config.discovery.internal.DiscoveryServiceRegistryImpl.startScans(DiscoveryServiceRegistryImpl.java:357)
	at org.eclipse.smarthome.config.discovery.internal.DiscoveryServiceRegistryImpl.startScan(DiscoveryServiceRegistryImpl.java:216)
	at org.eclipse.smarthome.io.rest.core.discovery.DiscoveryResource.scan(DiscoveryResource.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
10:02:32.920 INFO  o.e.s.b.h.h.HueBridgeHandler[:327] - Creating new user on Hue bridge 10.10.10.72 - please press the pairing button on the bridge.
10:02:32.931 DEBUG o.e.s.b.h.h.HueBridgeHandler[:355] - Failed creating new user on Hue bridge: link button not pressed
10:02:32.932 INFO  s.event.ThingStatusInfoEvent[:43] - 'hue:bridge:001788280c33' updated: OFFLINE (CONFIGURATION_ERROR): Not authenticated - press pairing button on the bridge.
10:02:37.135 DEBUG o.e.s.c.d.i.DiscoveryServiceRegistryImpl[:78] - Finished 1 of 2 discovery services.
10:02:42.095 INFO  s.event.ThingStatusInfoEvent[:43] - 'yahooweather:weather:berlin' updated: ONLINE
10:02:42.097 INFO  smarthome.event.ItemStateEvent[:43] - Weather_Temperature updated to 12
10:02:42.920 INFO  o.e.s.b.h.h.HueBridgeHandler[:327] - Creating new user on Hue bridge 10.10.10.72 - please press the pairing button on the bridge.
10:02:42.931 DEBUG o.e.s.b.h.h.HueBridgeHandler[:355] - Failed creating new user on Hue bridge: link button not pressed
10:02:42.932 INFO  s.event.ThingStatusInfoEvent[:43] - 'hue:bridge:001788280c33' updated: OFFLINE (CONFIGURATION_ERROR): Not authenticated - press pairing button on the bridge.
10:02:52.920 INFO  o.e.s.b.h.h.HueBridgeHandler[:327] - Creating new user on Hue bridge 10.10.10.72 - please press the pairing button on the bridge.
10:02:52.931 DEBUG o.e.s.b.h.h.HueBridgeHandler[:355] - Failed creating new user on Hue bridge: link button not pressed
10:02:52.932 INFO  s.event.ThingStatusInfoEvent[:43] - 'hue:bridge:001788280c33' updated: OFFLINE (CONFIGURATION_ERROR): Not authenticated - press pairing button on the bridge.
10:03:02.919 INFO  o.e.s.b.h.h.HueBridgeHandler[:327] - Creating new user on Hue bridge 10.10.10.72 - please press the pairing button on the bridge.
10:03:02.930 DEBUG o.e.s.b.h.h.HueBridgeHandler[:355] - Failed creating new user on Hue bridge: link button not pressed
10:03:02.931 INFO  s.event.ThingStatusInfoEvent[:43] - 'hue:bridge:001788280c33' updated: OFFLINE (CONFIGURATION_ERROR): Not authenticated - press pairing button on the bridge.
```

**Comment by tomhoefer** [comment]
Ok. Thx for the information. I will try to reproduce and fix the issue

**Comment by tomhoefer** [comment]
I cannot reproduce the issue... Tested as mentioned above and the umlauts are displayed properly

**Comment by maggu2810** [comment]
Thanks. Will reopen (hopefully not necessary) if I run into again.
