### ISSUE TITLE
Paper UI: Cannot read property 'getItem' of null

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#2197]
I received an error message if I visit the Paper UI.
To get a more meaningful trace I replaced the content of angular.min.js with the non-minimized version.

```text
I/chromium: [INFO:CONSOLE(4458)] "Uncaught Error: [$injector:modulerr] Failed to instantiate module PaperUI due to:
            Error: [$injector:modulerr] Failed to instantiate module PaperUI.services due to:
            TypeError: Cannot read property 'getItem' of null
                at http://10.10.10.14:3000/js/services.js:2:32
                at Object.invoke (http://10.10.10.14:3000/js/angular.min.js:4523:17)
                at runInvokeQueue (http://10.10.10.14:3000/js/angular.min.js:4429:35)
                at http://10.10.10.14:3000/js/angular.min.js:4438:11
                at forEach (http://10.10.10.14:3000/js/angular.min.js:340:20)
                at loadModules (http://10.10.10.14:3000/js/angular.min.js:4419:5)
                at http://10.10.10.14:3000/js/angular.min.js:4436:40
                at forEach (http://10.10.10.14:3000/js/angular.min.js:340:20)
                at loadModules (http://10.10.10.14:3000/js/angular.min.js:4419:5)
                at createInjector (http://10.10.10.14:3000/js/angular.min.js:4344:11)
            http://errors.angularjs.org/1.4.8/$injector/modulerr?p0=PaperUI.services&p1=TypeError%3A%20Cannot%20read%20property%20'getItem'%20of%20null%0A%20%20%20%20at%20http%3A%2F%2F10.10.10.14%3A3000%2Fjs%2Fservices.js%3A2%3A32%0A%20%20%20%20at%20Object.invoke%20(http%3A%2F%2F10.10.10.14%3A3000%2Fjs%2Fangular.min.js%3A4523%3A17)%0A%20%20%20%20at%20runInvokeQueue%20(http%3A%2F%2F10.10.10.14%3A3000%2Fjs%2Fangular.min.js%3A4429%3A35)%0A%20%20%20%20at%20http%3A%2F%2F10.10.10.14%3A3000%2Fjs%2Fangular.min.js%3A4438%3A11%0A%20%20%20%20at%20forEach%20(http%3A%2F%2F10.10.10.14%3A3000%2Fjs%2Fangular.min.js%3A340%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2F10.10.10.14%3A3000%2Fjs%2Fangular.min.js%3A4419%3A5)%0A%20%20%20%20at%20http%3A%2F%2F10.10.10.14%3A3000%2Fjs%2Fangular.min.js%3A4436%3A40%0A%20%20%20%20at%20forEach%20(http%3A%2F%2F10.10.10.14%3A3000%2Fjs%2Fangular.min.js%3A340%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2F10.10.10.14%3A3000%2Fjs%2Fangular.min.js%3A4419%3A5)%0A%20%20%20%20at%20createInjector%20(http%3A%2F%2F10.10.10.14%3A3000%2Fjs%2Fangular.min.js%3A4344%3A11)
                at http://10.10.10.14:3000/js/angular.min.js:68:12
                at http://10.10.10.14:3000/js/angular.min.js:4458:15
                at forEach (http://10.10.10.14:3000/js/angular.min.js:340:20)
                at loadModules (http://10.10.10.14:3000/js/angular.min.js:4419:5)
                at http://10.10.10.14:3000/js/angular.min.js:4436:40
                at forEach (http://10.10.10.14:3000/js/angular.min.js:340:20)
                at loadModules (http://10.10.10.14:3000/js/angular.min.js:4419:5)
                at createInjector (http://10.10.10.14:3000/js/angular.min.js:4344:11)
                at doBootstrap (http://10.10.10.14:3000/js/angular.min.js:1676:20)
                at bootstrap (http://10.10.10.14:3000/js/angular.min.js:1697:12)
            http://errors.angularjs.org/1.4.8/$injector/modulerr?p0=PaperUI&p1=Error%3A%20%5B%24injector%3Amodulerr%5D%20Failed%20to%20instantiate%20module%20PaperUI.services%20due%20to%3A%0ATypeError%3A%20Cannot%20read%20property%20'getItem'%20of%20null%0A%20%20%20%20at%20http%3A%2F%2F10.10.10.14%3A3000%2Fjs%2Fservices.js%3A2%3A32%0A%20%20%20%20at%20Object.invoke%20(http%3A%2F%2F10.10.10.14%3A3000%2Fjs%2Fangular.min.js%3A4523%3A17)%0A%20%20%20%20at%20runInvokeQueue%20(http%3A%2F%2F10.10.10.14%3A3000%2Fjs%2Fangular.min.js%3A4429%3A35)%0A%20%20%20%20at%20http%3A%2F%2F10.10.10.14%3A3000%2Fjs%2Fangular.min.js%3A4438%3A11%0A%20%20%20%20at%20forEach%20(http%3A%2F%2F10.10.10.14%3A3000%2Fjs%2Fangular.min.js%3A340%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2F10.10.10.14%3A3000%2Fjs%2Fangular.min.js%3A4419%3A5)%0A%20%20%20%20at%20http%3A%2F%2F10.10.10.14%3A3000%2Fjs%2Fangular.min.js%3A4436%3A40%0A%20%20%20%20at%20forEach%20(http%3A%2F%2F10.10.10.14%3A3000%2Fjs%2Fangular.min.js%3A340%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2F10.10.10.14%3A3000%2Fjs%2Fangular.min.js%3A4419%3A5)%0A%20%20%20%20at%20createInjector%20(http%3A%2F%2F10.10.10.14%3A3000%2Fjs%2Fangular.min.js%3A4344%3A11)%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.4.8%2F%24injector%2Fmodulerr%3Fp0%3DPaperUI.services%26p1%3DTypeError%253A%2520Cannot%2520read%2520property%2520'getItem'%2520of%2520null%250A%2520%2520%2520%2520at%2520http%253A%252F%252F1
```

**Comment by maggu2810** [comment]
Sorry, it seems I am missing the local storage.
