### ISSUE TITLE
Unset a setting value in the paper ui

### ISSUE THREAD

**Issue by digitaldan** [eclipse/smarthome#2238]
I just noticed that when using the configuration forms in Configurations -> Services -> .... that I can set a string value for a configuration option, but I can not set it empty or blank.  Since configuration options can be optional, it would be nice to be able to unset or at least send a blank entry for values.

**Comment by kaikreuzer** [comment]
@aounhaider1 I thought that once worked. Could you have a look, please?

**Comment by aounhaider1** [comment]
There is indeed this bug in PaperUI but sending null values for parameters is giving 500 internal server error. As far as I remember null values are allowed, right?

**Comment by kaikreuzer** [comment]
Yes, null values should be allowed in order to unset a value.

**Comment by aounhaider1** [comment]
Here is the log from console:
````
2016-10-04 16:44:26.081 [DEBUG] [r.JSONResponse$ExceptionMapper:160  ] - exception during REST Handlingjava.lang.NullPointerException: null
	at org.eclipse.equinox.internal.cm.ConfigurationDictionary.put(ConfigurationDictionary.java:106)
	at org.eclipse.equinox.internal.cm.ConfigurationDictionary.put(ConfigurationDictionary.java:1)
	at org.eclipse.smarthome.io.rest.core.config.ConfigurationService.update(ConfigurationService.java:83)
	at org.eclipse.smarthome.io.rest.core.config.ConfigurationService.update(ConfigurationService.java:56)
	at org.eclipse.smarthome.io.rest.core.service.ConfigurableServiceResource.updateConfiguration(ConfigurableServiceResource.java:136)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)

````

**Comment by digitaldan** [comment]
Many thanks!
