### ISSUE TITLE
Test failure(s): esh.core.thing: FirmwareUpdateServiceOSGiTest

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#2282]
* Commit: 2538c1d
* Travis job: https://travis-ci.org/eclipse/smarthome/builds/166162273
* raw console log: https://s3.amazonaws.com/archive.travis-ci.org/jobs/166162274/log.txt

Excerpt(s):
```text
Failed tests: 
  FirmwareUpdateServiceOSGiTest.setup:237->OSGiTest.waitForAssert:-1->OSGiTest.waitForAssert:181 
Expected: is <3>
     but: was <2>
```
```text
java.lang.AssertionError: 
Expected: is <3>
     but: was <2>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:865)
	at org.junit.Assert.assertThat(Assert.java:832)
	at org.junit.Assert$assertThat.callStatic(Unknown Source)
	at org.eclipse.smarthome.core.thing.firmware.FirmwareUpdateServiceOSGiTest$_setup_closure4.doCall(FirmwareUpdateServiceOSGiTest.groovy:242)
	at org.eclipse.smarthome.core.thing.firmware.FirmwareUpdateServiceOSGiTest$_setup_closure4.doCall(FirmwareUpdateServiceOSGiTest.groovy)
	at sun.reflect.GeneratedMethodAccessor45.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:292)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1015)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at org.eclipse.smarthome.test.OSGiTest.waitForAssert(OSGiTest.groovy:181)
	at org.eclipse.smarthome.test.OSGiTest.waitForAssert(OSGiTest.groovy)
	at sun.reflect.GeneratedMethodAccessor27.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:207)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:141)
	at org.eclipse.smarthome.core.thing.firmware.FirmwareUpdateServiceOSGiTest.setup(FirmwareUpdateServiceOSGiTest.groovy:237)
```

IIRC I already seen this error some days ago on my machine. My working copy has been a master with some changes, so I didn't report it. It also worked again...
But if Travis fails now, too, I assume the test itself is a little bit unstable.

I will rebuild the respective commit on my machine. If it does not build I assume the last merges broke the build. If it builds successfully I assume the tests needs to be hardened.

**Comment by maggu2810** [comment]
Build succeeded, so perhaps a timing problem.

**Comment by tomhoefer** [comment]
The only thing that we can change here is to separate the assertions for wait for things became online and the initial propagation of a fw status..

**Comment by maggu2810** [comment]
Thanks @tomhoefer, let's see if #2301 solve the problem. Will reopen this issue is the problem still remains (sometime).
