### ISSUE TITLE
[Test Failures] WemoLinkDiscoveryServiceOSGiTest

### ISSUE THREAD

**Issue by sjka** [eclipse/smarthome#2392]
I know my build server is not the fastest, but nevertheless I just ran into this one:

```
00:12:41.053 -------------------------------------------------------
00:12:41.053  T E S T S
00:12:41.053 -------------------------------------------------------
00:12:41.132 Running org.eclipse.smarthome.binding.wemo.discovery.test.WemoDiscoveryParticipantTest
00:12:41.613 Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.458 sec - in org.eclipse.smarthome.binding.wemo.discovery.test.WemoDiscoveryParticipantTest
00:12:41.614 assert discovery result for Maker is correct(org.eclipse.smarthome.binding.wemo.discovery.test.WemoDiscoveryParticipantTest)  Time elapsed: 0.18 sec
00:12:41.614 assert discovery result for Motion is correct(org.eclipse.smarthome.binding.wemo.discovery.test.WemoDiscoveryParticipantTest)  Time elapsed: 0.001 sec
00:12:41.614 assert discovery result for Bridge is correct(org.eclipse.smarthome.binding.wemo.discovery.test.WemoDiscoveryParticipantTest)  Time elapsed: 0.001 sec
00:12:41.614 assert discovery result for Insight is correct(org.eclipse.smarthome.binding.wemo.discovery.test.WemoDiscoveryParticipantTest)  Time elapsed: 0.001 sec
00:12:41.614 assert discovery result for Lightswitch is correct(org.eclipse.smarthome.binding.wemo.discovery.test.WemoDiscoveryParticipantTest)  Time elapsed: 0.001 sec
00:12:41.614 assert discovery result for Socket is correct(org.eclipse.smarthome.binding.wemo.discovery.test.WemoDiscoveryParticipantTest)  Time elapsed: 0.001 sec
00:12:41.614 Running org.eclipse.smarthome.binding.wemo.discovery.test.WemoLinkDiscoveryServiceOSGiTest
00:12:48.260 Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 6.626 sec <<< FAILURE! - in org.eclipse.smarthome.binding.wemo.discovery.test.WemoLinkDiscoveryServiceOSGiTest
00:12:48.260 assert supported thing is discovered(org.eclipse.smarthome.binding.wemo.discovery.test.WemoLinkDiscoveryServiceOSGiTest)  Time elapsed: 6.601 sec  <<< FAILURE!
00:12:48.260 java.lang.AssertionError: No Thing with UID wemo:MZ100:bridge:Test-1_0-22124 in inbox. However found:[]
00:12:48.260 	at org.junit.Assert.fail(Assert.java:88)
00:12:48.260 	at org.junit.Assert.assertTrue(Assert.java:41)
00:12:48.260 	at org.junit.Assert.assertFalse(Assert.java:64)
00:12:48.260 	at org.junit.Assert$assertFalse$0.callStatic(Unknown Source)
00:12:48.260 	at org.eclipse.smarthome.binding.wemo.discovery.test.WemoLinkDiscoveryServiceOSGiTest$_assert_supported_thing_is_discovered_closure1.doCall(WemoLinkDiscoveryServiceOSGiTest.groovy:80)
00:12:48.260 	at org.eclipse.smarthome.binding.wemo.discovery.test.WemoLinkDiscoveryServiceOSGiTest$_assert_supported_thing_is_discovered_closure1.doCall(WemoLinkDiscoveryServiceOSGiTest.groovy)
00:12:48.260 	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
00:12:48.260 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:12:48.260 	at java.lang.reflect.Method.invoke(Method.java:606)
00:12:48.260 	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
00:12:48.260 	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
00:12:48.260 	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:292)
00:12:48.260 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1015)
00:12:48.260 	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
00:12:48.260 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
00:12:48.260 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
00:12:48.260 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
00:12:48.260 	at org.eclipse.smarthome.test.OSGiTest.waitForAssert(OSGiTest.groovy:181)
00:12:48.260 	at org.eclipse.smarthome.test.OSGiTest.waitForAssert(OSGiTest.groovy)
00:12:48.260 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:12:48.260 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
00:12:48.260 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:12:48.260 	at java.lang.reflect.Method.invoke(Method.java:606)
00:12:48.260 	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:207)
00:12:48.260 	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:56)
00:12:48.260 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
00:12:48.260 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
00:12:48.260 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:145)
00:12:48.260 	at org.eclipse.smarthome.binding.wemo.discovery.test.WemoLinkDiscoveryServiceOSGiTest.assert supported thing is discovered(WemoLinkDiscoveryServiceOSGiTest.groovy:78)
00:12:48.260 
00:12:48.260 Running org.eclipse.smarthome.binding.wemo.discovery.test.WemoDiscoveryOSGiTest
00:12:49.293 Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.032 sec - in org.eclipse.smarthome.binding.wemo.discovery.test.WemoDiscoveryOSGiTest
00:12:49.293 assert supported thing is discovered(org.eclipse.smarthome.binding.wemo.discovery.test.WemoDiscoveryOSGiTest)  Time elapsed: 1.021 sec
00:12:49.293 Running org.eclipse.smarthome.binding.wemo.internal.http.test.WemoHttpCallOSGiTest
00:12:49.356 Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.056 sec - in org.eclipse.smarthome.binding.wemo.internal.http.test.WemoHttpCallOSGiTest
00:12:49.356 assert post request contains correct content header(org.eclipse.smarthome.binding.wemo.internal.http.test.WemoHttpCallOSGiTest)  Time elapsed: 0.049 sec
00:12:49.356 Running org.eclipse.smarthome.binding.wemo.handler.test.WemoLightHandlerOSGiTest
00:12:57.975 Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 8.612 sec - in org.eclipse.smarthome.binding.wemo.handler.test.WemoLightHandlerOSGiTest
00:12:57.975 handle Increase command for BRIGHTNESS channel(org.eclipse.smarthome.binding.wemo.handler.test.WemoLightHandlerOSGiTest)  Time elapsed: 1.329 sec
00:12:57.976 assert that thing updates channels at start(org.eclipse.smarthome.binding.wemo.handler.test.WemoLightHandlerOSGiTest)  Time elapsed: 1.292 sec
00:12:57.976 handle Percent command for BRIGHTNESS channel(org.eclipse.smarthome.binding.wemo.handler.test.WemoLightHandlerOSGiTest)  Time elapsed: 1.256 sec
00:12:57.976 handle ON command for BRIGHTNESS channel(org.eclipse.smarthome.binding.wemo.handler.test.WemoLightHandlerOSGiTest)  Time elapsed: 1.151 sec
00:12:57.976 handle Decrease command for BRIGHTNESS channel(org.eclipse.smarthome.binding.wemo.handler.test.WemoLightHandlerOSGiTest)  Time elapsed: 1.142 sec
00:12:57.976 handle On command for STATE channel(org.eclipse.smarthome.binding.wemo.handler.test.WemoLightHandlerOSGiTest)  Time elapsed: 1.207 sec
00:12:57.976 handle REFRESH command for channel STATE(org.eclipse.smarthome.binding.wemo.handler.test.WemoLightHandlerOSGiTest)  Time elapsed: 1.215 sec
00:12:57.976 Running org.eclipse.smarthome.binding.wemo.handler.test.WemoHandlerOSGiTest
00:12:58.500 Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.515 sec - in org.eclipse.smarthome.binding.wemo.handler.test.WemoHandlerOSGiTest
00:12:58.500 assert that thing handles OnOff command correctly(org.eclipse.smarthome.binding.wemo.handler.test.WemoHandlerOSGiTest)  Time elapsed: 0.131 sec
00:12:58.500 assert that thing updates channels states at start(org.eclipse.smarthome.binding.wemo.handler.test.WemoHandlerOSGiTest)  Time elapsed: 0.193 sec
00:12:58.500 assert that thing handles REFRESH command correctly(org.eclipse.smarthome.binding.wemo.handler.test.WemoHandlerOSGiTest)  Time elapsed: 0.173 sec
00:12:58.500 Running org.eclipse.smarthome.binding.wemo.handler.test.WemoHandlerTest
00:12:58.562 Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.053 sec - in org.eclipse.smarthome.binding.wemo.handler.test.WemoHandlerTest
00:12:58.562 assert that channel AVERAGEPOWER is updated on recevied value(org.eclipse.smarthome.binding.wemo.handler.test.WemoHandlerTest)  Time elapsed: 0.025 sec
00:12:58.562 assert that channel ONTOTAL is updated on recevied value(org.eclipse.smarthome.binding.wemo.handler.test.WemoHandlerTest)  Time elapsed: 0.002 sec
00:12:58.562 assert that channel ONTODAY is updated on recevied value(org.eclipse.smarthome.binding.wemo.handler.test.WemoHandlerTest)  Time elapsed: 0.001 sec
00:12:58.562 assert that channel LASTONFOR is updated on recevied value(org.eclipse.smarthome.binding.wemo.handler.test.WemoHandlerTest)  Time elapsed: 0.001 sec
00:12:58.562 assert that channel STATE is updated on recevied value(org.eclipse.smarthome.binding.wemo.handler.test.WemoHandlerTest)  Time elapsed: 0.001 sec
00:12:58.562 assert that channel TIMESPAN is updated on recevied value(org.eclipse.smarthome.binding.wemo.handler.test.WemoHandlerTest)  Time elapsed: 0.001 sec
00:12:58.562 Running org.eclipse.smarthome.binding.wemo.handler.test.WemoMakerHandlerOSGiTest
00:12:59.219 Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.651 sec - in org.eclipse.smarthome.binding.wemo.handler.test.WemoMakerHandlerOSGiTest
00:12:59.219 assert that thing updates channels at start(org.eclipse.smarthome.binding.wemo.handler.test.WemoMakerHandlerOSGiTest)  Time elapsed: 0.281 sec
00:12:59.219 assert that thing handles OnOff command correctly(org.eclipse.smarthome.binding.wemo.handler.test.WemoMakerHandlerOSGiTest)  Time elapsed: 0.115 sec
00:12:59.219 assert that thing handles REFRESH command(org.eclipse.smarthome.binding.wemo.handler.test.WemoMakerHandlerOSGiTest)  Time elapsed: 0.239 sec
00:12:59.219 
00:12:59.219 Results :
00:12:59.219 
00:12:59.219 Failed tests: 
00:12:59.219   WemoLinkDiscoveryServiceOSGiTest.assert supported thing is discovered:78->OSGiTest.waitForAssert:-1->OSGiTest.waitForAssert:181 No Thing with UID wemo:MZ100:bridge:Test-1_0-22124 in inbox. However found:[]
00:12:59.219 
00:12:59.219 Tests run: 28, Failures: 1, Errors: 0, Skipped: 0
00:12:59.219 
```

**Comment by sjka** [comment]
@svilenvul could you please have a look?

**Comment by svilenvul** [comment]
Yes, I will definitely take a look.
