### ISSUE TITLE
Maven: Could not find "org.codehaus.groovy23.feature.feature.group/2.9.2.xx-201611092339-e46"

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#2450]
Strange behavior. If I compile the smarthome from the top, no problem. If I move to extensions/binding/org.eclipse.smarthome.binding.sonos and run maven, I got this error:
```
[ERROR] Failed to resolve target definition C:\Documents and Settings\Administrateur\.m2\repository\org\eclipse\smarthome\targetplatform\0.9.0-SNAPSHOT\targetplatform-0.9.0-SNAPSHOT-smarthome.target: Could not find "org.codehaus.groovy23.feature.feature.group/2.9.2.xx-201611092339-e46" in the repositories of the current location -> [Help 1]
org.apache.maven.MavenExecutionException: Failed to resolve target definition C:\Documents and Settings\Administrateur\.m2\repository\org\eclipse\smarthome\targetplatform\0.9.0-SNAPSHOT\targetplatform-0.9.0-SNAPSHOT-smarthome.target: Could not find "org.codehaus.groovy23.feature.feature.group/2.9.2.xx-201611092339-e46" in the repositories of the current location
        at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.afterProjectsRead(TychoMavenLifecycleParticipant.java:100)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:266)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.eclipse.tycho.core.shared.BuildFailureException: Failed to resolve target definition C:\Documents and Settings\Administrateur\.m2\repository\org\eclipse\smarthome\targetplatform\0.9.0-SNAPSHOT\targetplatform-0.9.0-SNAPSHOT-smarthome.target: Could not find "org.codehaus.groovy23.feature.feature.group/2.9.2.xx-201611092339-e46" in the repositories of the current location
        at org.eclipse.tycho.p2.target.TargetDefinitionResolver.resolveContent(TargetDefinitionResolver.java:99)
        at org.eclipse.tycho.p2.target.TargetDefinitionResolverService.resolveFromArguments(TargetDefinitionResolverService.java:70)
        at org.eclipse.tycho.p2.target.TargetDefinitionResolverService.getTargetDefinitionContent(TargetDefinitionResolverService.java:60)
        at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.resolveTargetDefinitions(TargetPlatformFactoryImpl.java:214)
        at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.createTargetPlatform(TargetPlatformFactoryImpl.java:155)
        at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.createTargetPlatform(TargetPlatformFactoryImpl.java:128)
        at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.createTargetPlatform(TargetPlatformFactoryImpl.java:1)
        at org.eclipse.tycho.p2.manager.ReactorRepositoryManagerImpl.computePreliminaryTargetPlatform(ReactorRepositoryManagerImpl.java:84)
        at org.eclipse.tycho.p2.resolver.P2DependencyResolver.computePreliminaryTargetPlatform(P2DependencyResolver.java:223)
        at org.eclipse.tycho.core.resolver.DefaultTychoResolver.resolveProject(DefaultTychoResolver.java:109)
        at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.afterProjectsRead(TychoMavenLifecycleParticipant.java:95)
        ... 14 more
Caused by: org.eclipse.tycho.p2.target.facade.TargetDefinitionResolutionException: Could not find "org.codehaus.groovy23.feature.feature.group/2.9.2.xx-201611092339-e46" in the repositories of the current location
        at org.eclipse.tycho.p2.target.TargetDefinitionResolver$LoadedIULocation.findUnitInThisLocation(TargetDefinitionResolver.java:313)
        at org.eclipse.tycho.p2.target.TargetDefinitionResolver$LoadedIULocation.getRootIUs(TargetDefinitionResolver.java:303)
        at org.eclipse.tycho.p2.target.TargetDefinitionResolver$ResolverRun.addLocation(TargetDefinitionResolver.java:155)
        at org.eclipse.tycho.p2.target.TargetDefinitionResolver.resolveContentWithExceptions(TargetDefinitionResolver.java:121)
        at org.eclipse.tycho.p2.target.TargetDefinitionResolver.resolveContent(TargetDefinitionResolver.java:94)
        ... 24 more
```
I removed my .m2\repository earlier today.

**Comment by kaikreuzer** [comment]
You should rebase on the current master - https://github.com/eclipse/smarthome/pull/2441 has already fixed that issue.

**Comment by lolodomo** [comment]
@kaikreuzer : sorry but even when being identical to master, I encounter this problem.
If I compile everything, no error.
If I compile only the Sonos binding, it fails with this error.

**Comment by kaikreuzer** [comment]
> If I compile only the Sonos binding, it fails with this error.

Which means that it picks up an old version of the target platform in that case.
Always run the build from the root of the repo - all other ways are on your own risk ;-)

**Comment by lolodomo** [comment]
It has always worked until mow !
Running mvn on root is not a usable alternative as it takes ages on my slow PC.
Please reopen the issue.

**Comment by maggu2810** [comment]
Maven resolve Snapshots from the external repo all 24h (let's assume you do not use offline builds, as it is not supported by the current upstream ESH configuration).
As long as the external targetplatform snapshot is not the correct one, you will run into this error.

Instead of building the Sonos artifact only, you should build the targetplatform and the sonos artifact in one run.

If you use
```java
 mvn clean install -pl targetplatform/ -pl extensions/binding/org.eclipse.smarthome.binding.sonos/
```
in the root path of your working copy it will build the targetplatform and the Sonos binding only.
It should make no big different as building the Sonos binding only.

But the whole problematic is also valid for other dependent bundles that breaks compatibility some time.
As long as we are using the Tycho plugin "-am" will not work as expected.

**Comment by lolodomo** [comment]
@maggu2810 : thank you for your help.
I tried your command and I got that new error:
```
[WARNING] Target location type 'Directory' is not supported
[INFO] Resolving dependencies of MavenProject: org.eclipse.smarthome.binding:org.eclipse.smarthome.binding.sonos:0.9.0-SNAPSHOT @ F:\Dev\openhab2-master\git\smarthome\extensions\binding\org.eclipse.smarthome.binding.sonos\pom.xml
[INFO] {osgi.os=linux, osgi.ws=gtk, org.eclipse.update.install.features=true, osgi.arch=x86}
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: org.eclipse.smarthome.binding.sonos 0.9.0.qualifier
[ERROR]   Missing requirement: org.eclipse.smarthome.binding.sonos 0.9.0.qualifier requires 'package org.eclipse.smarthome.config.core 0.0.0' but it could not be found
[ERROR]
```
If I correctly understood, I should wait for one day to have this problem automatically resolved.

**Comment by maggu2810** [comment]
> If I correctly understood, I should wait for one day to have this problem automatically resolved.

It is a little bit more complicated.
In this special case it depends if a new official snapshot build is done.

**Comment by lolodomo** [comment]
@maggu2810 : this time, after updating my repository, even with Maven calling at top, it fails ! I can no more compile ! I already tried to delete my ".m2\repository" folder. Any help would be really appreciated.
```
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Unresolveable build extension: Plugin org.eclipse.tycho:tycho-maven-plugin:0.23.1 or one of its dependencies could not be resolved: Failed to collect dependencies at org.eclipse.tycho:tycho-maven-plugin:jar:0.23.1 -> org.eclipse.tycho:tycho-core:jar:0.23.1 -> org.apache.maven:maven-core:jar:3.0 @
 @
[ERROR] The build could not read 1 project -> [Help 1]
org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
[ERROR] Unresolveable build extension: Plugin org.eclipse.tycho:tycho-maven-plugin:0.23.1 or one of its dependencies could not be resolved: Failed to collect dependencies at org.eclipse.tycho:tycho-maven-plugin:jar:0.23.1 -> org.eclipse.tycho:tycho-core:jar:0.23.1 -> org.apache.maven:maven-core:jar:3.0 @

        at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:422)
        at org.apache.maven.graph.DefaultGraphBuilder.collectProjects(DefaultGraphBuilder.java:419)
        at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor(DefaultGraphBuilder.java:410)
        at org.apache.maven.graph.DefaultGraphBuilder.build(DefaultGraphBuilder.java:83)
        at org.apache.maven.DefaultMaven.buildGraph(DefaultMaven.java:491)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:219)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR]
[ERROR]   The project org.eclipse.smarthome:smarthome:0.9.0-SNAPSHOT (F:\dev\openhab2-master\git\smarthome\pom.xml) has 1 error
[ERROR]     Unresolveable build extension: Plugin org.eclipse.tycho:tycho-maven-plugin:0.23.1 or one of its dependencies could not be resolved: Failed to collect dependencies at org.eclipse.tycho:tycho-maven-plugin:jar:0.23.1 -> org.eclipse.tycho:tycho-core:jar:0.23.1 -> org.apache.maven:maven-core:jar:3.0: Failed to read artifact descriptor for org.apache.maven:maven-core:jar:3.0: Could not transfer artifact org.apache.maven:maven-core:pom:3.0 from/to central (https://repo.maven.apache.org/maven2): hostname in certificate didn't match: <repo.maven.apache.org> != <repo1.maven.org> OR <repo1.maven.org> -> [Help 2]
org.apache.maven.plugin.PluginManagerException: Plugin org.eclipse.tycho:tycho-maven-plugin:0.23.1 or one of its dependencies could not be resolved: Failed to collect dependencies at org.eclipse.tycho:tycho-maven-plugin:jar:0.23.1 -> org.eclipse.tycho:tycho-core:jar:0.23.1 -> org.apache.maven:maven-core:jar:3.0
        at org.apache.maven.plugin.internal.DefaultMavenPluginManager.setupExtensionsRealm(DefaultMavenPluginManager.java:846)
        at org.apache.maven.project.DefaultProjectBuildingHelper.createProjectRealm(DefaultProjectBuildingHelper.java:196)
        at org.apache.maven.project.DefaultModelBuildingListener.buildExtensionsAssembled(DefaultModelBuildingListener.java:99)
        at org.apache.maven.model.building.ModelBuildingEventCatapult$1.fire(ModelBuildingEventCatapult.java:44)
        at org.apache.maven.model.building.DefaultModelBuilder.fireEvent(DefaultModelBuilder.java:1295)
        at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:441)
        at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:421)
        at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:620)
        at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:411)
        at org.apache.maven.graph.DefaultGraphBuilder.collectProjects(DefaultGraphBuilder.java:419)
        at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor(DefaultGraphBuilder.java:410)
        at org.apache.maven.graph.DefaultGraphBuilder.build(DefaultGraphBuilder.java:83)
        at org.apache.maven.DefaultMaven.buildGraph(DefaultMaven.java:491)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:219)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginResolutionException: Plugin org.eclipse.tycho:tycho-maven-plugin:0.23.1 or one of its dependencies could not be resolved: Failed to collect dependencies at org.eclipse.tycho:tycho-maven-plugin:jar:0.23.1 -> org.eclipse.tycho:tycho-core:jar:0.23.1 -> org.apache.maven:maven-core:jar:3.0
        at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolveInternal(DefaultPluginDependenciesResolver.java:214)
        at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve(DefaultPluginDependenciesResolver.java:149)
        at org.apache.maven.plugin.internal.DefaultMavenPluginManager.resolveExtensionArtifacts(DefaultMavenPluginManager.java:908)
        at org.apache.maven.plugin.internal.DefaultMavenPluginManager.setupExtensionsRealm(DefaultMavenPluginManager.java:839)
        ... 26 more
Caused by: org.eclipse.aether.collection.DependencyCollectionException: Failed to collect dependencies at org.eclipse.tycho:tycho-maven-plugin:jar:0.23.1 -> org.eclipse.tycho:tycho-core:jar:0.23.1 -> org.apache.maven:maven-core:jar:3.0
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:291)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.collectDependencies(DefaultRepositorySystem.java:316)
        at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolveInternal(DefaultPluginDependenciesResolver.java:202)
        ... 29 more
Caused by: org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for org.apache.maven:maven-core:jar:3.0
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:282)
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:198)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.resolveCachedArtifactDescriptor(DefaultDependencyCollector.java:535)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.getArtifactDescriptorResult(DefaultDependencyCollector.java:519)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:409)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:363)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.process(DefaultDependencyCollector.java:351)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.doRecurse(DefaultDependencyCollector.java:504)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:458)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:363)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.process(DefaultDependencyCollector.java:351)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:254)
        ... 31 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact org.apache.maven:maven-core:pom:3.0 from/to central (https://repo.maven.apache.org/maven2): hostname in certificate didn't match: <repo.maven.apache.org> != <repo1.maven.org> OR <repo1.maven.org>
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223)
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:267)
        ... 42 more
Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact org.apache.maven:maven-core:pom:3.0 from/to central (https://repo.maven.apache.org/maven2): hostname in certificate didn't match: <repo.maven.apache.org> != <repo1.maven.org> OR <repo1.maven.org>
        at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:43)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:355)
        at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:581)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:249)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:520)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
        ... 45 more
Caused by: org.apache.maven.wagon.TransferFailedException: hostname in certificate didn't match: <repo.maven.apache.org> != <repo1.maven.org> OR <repo1.maven.org>
        at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:1066)
        at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:960)
        at org.apache.maven.wagon.StreamWagon.getInputStream(StreamWagon.java:116)
        at org.apache.maven.wagon.StreamWagon.getIfNewer(StreamWagon.java:88)
        at org.apache.maven.wagon.StreamWagon.get(StreamWagon.java:61)
        at org.eclipse.aether.transport.wagon.WagonTransporter$GetTaskRunner.run(WagonTransporter.java:560)
        at org.eclipse.aether.transport.wagon.WagonTransporter.execute(WagonTransporter.java:427)
        at org.eclipse.aether.transport.wagon.WagonTransporter.get(WagonTransporter.java:404)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:447)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:350)
        ... 50 more
Caused by: javax.net.ssl.SSLException: hostname in certificate didn't match: <repo.maven.apache.org> != <repo1.maven.org> OR <repo1.maven.org>
        at org.apache.maven.wagon.providers.http.httpclient.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:238)
        at org.apache.maven.wagon.providers.http.httpclient.conn.ssl.BrowserCompatHostnameVerifier.verify(BrowserCompatHostnameVerifier.java:54)
        at org.apache.maven.wagon.providers.http.httpclient.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:159)
        at org.apache.maven.wagon.providers.http.httpclient.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:140)
        at org.apache.maven.wagon.providers.http.httpclient.conn.ssl.SSLConnectionSocketFactory.verifyHostname(SSLConnectionSocketFactory.java:286)
        at org.apache.maven.wagon.providers.http.httpclient.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:276)
        at org.apache.maven.wagon.providers.http.httpclient.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:254)
        at org.apache.maven.wagon.providers.http.httpclient.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:123)
        at org.apache.maven.wagon.providers.http.httpclient.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:318)
        at org.apache.maven.wagon.providers.http.httpclient.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:363)
        at org.apache.maven.wagon.providers.http.httpclient.impl.execchain.MainClientExec.execute(MainClientExec.java:219)
        at org.apache.maven.wagon.providers.http.httpclient.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
        at org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec.execute(RetryExec.java:86)
        at org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
        at org.apache.maven.wagon.providers.http.httpclient.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
        at org.apache.maven.wagon.providers.http.httpclient.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.execute(AbstractHttpClientWagon.java:832)
        at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:983)
        ... 59 more
[ERROR]
```

**Comment by MHerbst** [comment]
This seems to be a Maven problem. Some hours ago there was a modification in Maven to use https instead of http. Unfortunately the certificate on repo.maven.apache.org does not match the hostname.
You can find more information and a bypass here: https://issues.sonatype.org/browse/MVNCENTRAL-1369

**Comment by maggu2810** [comment]
Hi @lolodomo, I think about your concerns again and tried to find a solution.
There is something you can do... But you should know that this is unsupported and my break your machine, your home or the whole universe (okay, I don't think so) :wink: 
IIRC there is no official support to build only a subset and not the whole reactor using Maven.

I tried it myself with an empty local maven repo and it was able to build only the resp. projects (see above).

I can show you how you can do that, but you should try to understand yourself what are you doing with that changes, as I don't offer any support if something goes wrong / don't work / break anything.

So, enough "perhaps you shouldn't do it advices"...

Copy your ESH targetplatform:
```sh
cp -ax targetplatform targetplatform.esh-nightly-ext
```

Change the copied targetplatform using the given patch to include the remote nightly p2 repo: 
```diff
diff --git a/targetplatform.esh-nightly-ext/smarthome.target b/targetplatform.esh-nightly-ext/smarthome.target
--- a/targetplatform.esh-nightly-ext/smarthome.target
+++ b/targetplatform.esh-nightly-ext/smarthome.target
@@ -162,5 +162,13 @@
 <repository location="http://download.eclipse.org/jetty/updates/jetty-bundles-9.x/9.2.9.v20150224"/>
 </location>
 <location path="${project_loc:targetplatform}/third-party" type="Directory"/>
+<location includeAllPlatforms="false" includeConfigurePhase="false" includeMode="planner" includeSource="true" type="InstallableUnit">
+<unit id="org.eclipse.smarthome.feature.runtime.core.feature.group" version="0.0.0"/>
+<unit id="org.eclipse.smarthome.feature.runtime.binding.feature.group" version="0.0.0"/>
+<unit id="org.eclipse.smarthome.feature.runtime.console.equinox.feature.group" version="0.0.0"/>
+<unit id="org.eclipse.smarthome.feature.runtime.rest.feature.group" version="0.0.0"/>
+<unit id="org.eclipse.smarthome.feature.test.feature.group" version="0.0.0"/>
+<repository location="http://download.eclipse.org/smarthome/updates-nightly/"/>
+</location>
 </locations>
 </target>
```

After that you can build e.g. the modified targetplatform reference file:
```sh
cd targetplatform.esh-nightly-ext/
mvn clean install
```

After you have build the targetplatform file using the external nightly ESH repo you should be able to build the Sonos binding alone:

```sh
mvn -Dmaven.repo.local=/home/maggu2810/tmp/empty-repo -pl extensions/binding/org.eclipse.smarthome.binding.sonos/ clean install
```

**Comment by lolodomo** [comment]
The Maven problem that occured yesterday has been fixed, I can again compile everything from the root.

@maggu2810 : thanks, I will try that later.
