### ISSUE TITLE
Classic UI no more able to open certain frames

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#2454]
With snapshot 583, I discovered that few of my frames cannot be opened in Classic UI. I got this error:
```
22:57:49.814 [WARN ] [eclipse.jetty.servlet.ServletHandler] - /classicui/app
java.lang.NullPointerException
        at org.eclipse.smarthome.ui.classic.internal.render.AbstractWidgetRenderer.getStateAsNumber(AbstractWidgetRenderer.java:192)[184:org.eclipse.smarthome.ui.classic:0.9.0.201611102032]
        at org.eclipse.smarthome.ui.classic.internal.render.SliderRenderer.renderWidget(SliderRenderer.java:59)[184:org.eclipse.smarthome.ui.classic:0.9.0.201611102032]
        at org.eclipse.smarthome.ui.classic.internal.render.PageRenderer.renderWidget(PageRenderer.java:166)[184:org.eclipse.smarthome.ui.classic:0.9.0.201611102032]
        at org.eclipse.smarthome.ui.classic.internal.render.PageRenderer.processChildren(PageRenderer.java:123)[184:org.eclipse.smarthome.ui.classic:0.9.0.201611102032]
        at org.eclipse.smarthome.ui.classic.internal.render.PageRenderer.processPage(PageRenderer.java:86)[184:org.eclipse.smarthome.ui.classic:0.9.0.201611102032]
        at org.eclipse.smarthome.ui.classic.internal.servlet.WebAppServlet.service(WebAppServlet.java:160)[184:org.eclipse.smarthome.ui.classic:0.9.0.201611102032]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)[79:org.eclipse.jetty.servlet:9.2.14.v20151106]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)[79:org.eclipse.jetty.servlet:9.2.14.v20151106]
        at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:70)[170:org.ops4j.pax.web.pax-web-jetty:4.2.4]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)[78:org.eclipse.jetty.server:9.2.14.v20151106]
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)[77:org.eclipse.jetty.security:9.2.14.v20151106]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)[78:org.eclipse.jetty.server:9.2.14.v20151106]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)[78:org.eclipse.jetty.server:9.2.14.v20151106]
        at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:271)[170:org.ops4j.pax.web.pax-web-jetty:4.2.4]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)[79:org.eclipse.jetty.servlet:9.2.14.v20151106]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)[78:org.eclipse.jetty.server:9.2.14.v20151106]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)[78:org.eclipse.jetty.server:9.2.14.v20151106]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)[78:org.eclipse.jetty.server:9.2.14.v20151106]
        at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:80)[170:org.ops4j.pax.web.pax-web-jetty:4.2.4]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)[78:org.eclipse.jetty.server:9.2.14.v20151106]
        at org.eclipse.jetty.server.Server.handle(Server.java:499)[78:org.eclipse.jetty.server:9.2.14.v20151106]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)[78:org.eclipse.jetty.server:9.2.14.v20151106]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)[78:org.eclipse.jetty.server:9.2.14.v20151106]
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)[70:org.eclipse.jetty.io:9.2.14.v20151106]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)[81:org.eclipse.jetty.util:9.2.14.v20151106]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)[81:org.eclipse.jetty.util:9.2.14.v20151106]
        at java.lang.Thread.run(Thread.java:745)[:1.8.0_65]
```
PS: it was working well whith my previous snapshot (554).

**Comment by lolodomo** [comment]
For information, Basic UI and HABdroid are still able to open these frames. So the issue is really only for Classic UI.
Last thing, it is a frame attached to a group item, I don't know if it is important.

**Comment by kaikreuzer** [comment]
Could you come up with a very simple sitemap that has this problem? Or is it possibly even happening on the demo.sitemap?

**Comment by lolodomo** [comment]
I doubt because I have several frames in my sitemap and only two of them which are similar are failing to load. I can tell you that this frame is attached to a group item and this group has 30 items including a Player item.
I have another frame with more items that can be displayed. And I have another frame with a Player but less items that can be displayed too.
