### ISSUE TITLE
Bridge.getHandler() cause NoSuchMethodError exception

### ISSUE THREAD

**Issue by paulianttila** [eclipse/smarthome#2455]
I tested rfxcom binding changes with latest smarthome sources. I meet weird behaviour with bridge handler

```
2016-11-13 00:21:27.232 [ERROR] [.c.thing.internal.ThingManager:776  ] - Exception occured while initializing handler of thing 'rfxcom:lighting2:usb0:100001_1': java.lang.NoSuchMethodError: org.eclipse.smarthome.core.thing.Bridge.getHandler()Lorg/eclipse/smarthome/core/thing/binding/BridgeHandler;java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: org.eclipse.smarthome.core.thing.Bridge.getHandler()Lorg/eclipse/smarthome/core/thing/binding/BridgeHandler;
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at org.eclipse.smarthome.core.common.SafeMethodCaller.callAsynchronous(SafeMethodCaller.java:186)
	at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:79)
	at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:63)
	at org.eclipse.smarthome.core.thing.internal.ThingManager$9.run(ThingManager.java:761)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
Caused by: java.lang.NoSuchMethodError: org.eclipse.smarthome.core.thing.Bridge.getHandler()Lorg/eclipse/smarthome/core/thing/binding/BridgeHandler;
	at org.openhab.binding.rfxcom.handler.RFXComHandler.initialize(RFXComHandler.java:110)
	at org.eclipse.smarthome.core.thing.internal.ThingManager$9$1.call(ThingManager.java:764)
	at org.eclipse.smarthome.core.thing.internal.ThingManager$9$1.call(ThingManager.java:1)
	at org.eclipse.smarthome.core.common.SafeMethodCaller$CallableWrapper.call(SafeMethodCaller.java:177)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 common frames omitted

```

I recognised massive refactoring for bridge/thing handling by commit #2087. Is this know change/behaviour or a bug somewhere?

More complete log:
```
2016-11-13 00:21:26.814 [DEBUG] [.c.thing.internal.ThingManager:504  ] - Thing 'rfxcom:bridge:usb0' is tracked by ThingManager.
2016-11-13 00:21:26.814 [INFO ] [marthome.event.ThingAddedEvent:43   ] - Thing 'rfxcom:bridge:usb0' has been added.
2016-11-13 00:21:26.814 [DEBUG] [.c.thing.internal.ThingManager:630  ] - Calling 'RFXComHandlerFactory.registerHandler()' for thing 'rfxcom:bridge:usb0'.
2016-11-13 00:21:26.815 [DEBUG] [.c.thing.internal.ThingManager:758  ] - Calling initialize handler for thing 'ntp:ntp:demo' at 'org.eclipse.smarthome.binding.ntp.handler.NtpHandler@e6e1c05'.
2016-11-13 00:21:26.816 [DEBUG] [binding.ntp.handler.NtpHandler:108  ] - Initializing NTP handler for 'ntp:ntp:demo'.
2016-11-13 00:21:26.818 [DEBUG] [binding.ntp.handler.NtpHandler:120  ] - ntp:ntp:demo using default TZ: sun.util.calendar.ZoneInfo[id="Europe/Helsinki",offset=7200000,dstSavings=3600000,useDaylight=true,transitions=118,lastRule=java.util.SimpleTimeZone[id=Europe/Helsinki,offset=7200000,dstSavings=3600000,useDaylight=true,startYear=0,startMode=2,startMonth=2,startDay=-1,startDayOfWeek=1,startTime=3600000,startTimeMode=2,endMode=2,endMonth=9,endDay=-1,endDayOfWeek=1,endTime=3600000,endTimeMode=2]]
2016-11-13 00:21:26.819 [DEBUG] [binding.ntp.handler.NtpHandler:128  ] - ntp:ntp:demo using default locale: en_US
2016-11-13 00:21:26.820 [DEBUG] [binding.ntp.handler.NtpHandler:138  ] - Could not format ntp:ntp:demo with DateFormat 'yyyy-MM-dd HH:mm:ss z', using default format.
2016-11-13 00:21:26.820 [DEBUG] [binding.ntp.handler.NtpHandler:149  ] - Initialized NTP handler 'ntp:ntp:demo' with configuration: host 'nl.pool.ntp.org', refresh interval 60, timezone sun.util.calendar.ZoneInfo[id="Europe/Helsinki",offset=7200000,dstSavings=3600000,useDaylight=true,transitions=118,lastRule=java.util.SimpleTimeZone[id=Europe/Helsinki,offset=7200000,dstSavings=3600000,useDaylight=true,startYear=0,startMode=2,startMonth=2,startDay=-1,startDayOfWeek=1,startTime=3600000,startTimeMode=2,endMode=2,endMonth=9,endDay=-1,endDayOfWeek=1,endTime=3600000,endTimeMode=2]], locale en_US.
2016-11-13 00:21:26.827 [DEBUG] [.c.thing.internal.ThingManager:117  ] - Thing handler for thing 'rfxcom:bridge:usb0' added.
2016-11-13 00:21:26.828 [DEBUG] [.c.thing.internal.ThingManager:290  ] - Assigning handler for thing 'rfxcom:bridge:usb0'.
2016-11-13 00:21:26.828 [DEBUG] [.c.thing.internal.ThingManager:697  ] - Finished loading meta-data of bundle 'org.openhab.binding.rfxcom'
2016-11-13 00:21:26.830 [INFO ] [ome.event.ThingStatusInfoEvent:43   ] - 'rfxcom:bridge:usb0' updated: INITIALIZING
2016-11-13 00:21:26.830 [DEBUG] [.c.thing.internal.ThingManager:754  ] - All data has been loaded, going to initialize 'rfxcom:bridge:usb0'.
2016-11-13 00:21:26.831 [INFO ] [nt.ThingStatusInfoChangedEvent:43   ] - 'rfxcom:bridge:usb0' changed from UNINITIALIZED to INITIALIZING
2016-11-13 00:21:26.834 [DEBUG] [.c.thing.internal.ThingManager:758  ] - Calling initialize handler for thing 'rfxcom:bridge:usb0' at 'org.openhab.binding.rfxcom.handler.RFXComBridgeHandler@7aab754e'.
2016-11-13 00:21:26.835 [DEBUG] [.r.handler.RFXComBridgeHandler:103  ] - Initializing RFXCOM bridge handler
2016-11-13 00:21:26.835 [DEBUG] [.c.thing.internal.ThingManager:504  ] - Thing 'rfxcom:lighting2:usb0:100001_1' is tracked by ThingManager.
2016-11-13 00:21:26.835 [INFO ] [marthome.event.ThingAddedEvent:43   ] - Thing 'rfxcom:lighting2:usb0:100001_1' has been added.
2016-11-13 00:21:26.836 [INFO ] [ome.event.ThingStatusInfoEvent:43   ] - 'rfxcom:bridge:usb0' updated: OFFLINE
2016-11-13 00:21:26.837 [INFO ] [nt.ThingStatusInfoChangedEvent:43   ] - 'rfxcom:bridge:usb0' changed from INITIALIZING to OFFLINE
2016-11-13 00:21:26.835 [DEBUG] [.c.thing.internal.ThingManager:630  ] - Calling 'RFXComHandlerFactory.registerHandler()' for thing 'rfxcom:lighting2:usb0:100001_1'.
2016-11-13 00:21:26.839 [DEBUG] [.e.s.config.core.Configuration:94   ] - Setting value (String) /dev/tty.usbserial-A1LPSOQ to field 'serialPort' in configuration class org.openhab.binding.rfxcom.internal.config.RFXComBridgeConfiguration
2016-11-13 00:21:26.843 [DEBUG] [.c.thing.internal.ThingManager:117  ] - Thing handler for thing 'rfxcom:lighting2:usb0:100001_1' added.
2016-11-13 00:21:26.844 [DEBUG] [.c.thing.internal.ThingManager:290  ] - Assigning handler for thing 'rfxcom:lighting2:usb0:100001_1'.
2016-11-13 00:21:26.844 [DEBUG] [.c.thing.internal.ThingManager:697  ] - Finished loading meta-data of bundle 'org.openhab.binding.rfxcom'
2016-11-13 00:21:26.847 [DEBUG] [.c.thing.internal.ThingManager:754  ] - All data has been loaded, going to initialize 'rfxcom:lighting2:usb0:100001_1'.
2016-11-13 00:21:26.847 [INFO ] [ome.event.ThingStatusInfoEvent:43   ] - 'rfxcom:lighting2:usb0:100001_1' updated: INITIALIZING
2016-11-13 00:21:26.848 [INFO ] [nt.ThingStatusInfoChangedEvent:43   ] - 'rfxcom:lighting2:usb0:100001_1' changed from UNINITIALIZED to INITIALIZING
2016-11-13 00:21:26.854 [DEBUG] [.e.s.config.core.Configuration:74   ] - Skipping field 'port', because it's primitive data type and value is not set
2016-11-13 00:21:26.854 [DEBUG] [.e.s.config.core.Configuration:94   ] - Setting value (String) 433.92MHz to field 'transceiverType' in configuration class org.openhab.binding.rfxcom.internal.config.RFXComBridgeConfiguration
2016-11-13 00:21:26.854 [DEBUG] [.e.s.config.core.Configuration:94   ] - Setting value (boolean) true to field 'ignoreConfig' in configuration class org.openhab.binding.rfxcom.internal.config.RFXComBridgeConfiguration
2016-11-13 00:21:26.854 [DEBUG] [.e.s.config.core.Configuration:94   ] - Setting value (boolean) false to field 'enableUndecoded' in configuration class org.openhab.binding.rfxcom.internal.config.RFXComBridgeConfiguration
2016-11-13 00:21:26.854 [DEBUG] [.e.s.config.core.Configuration:94   ] - Setting value (boolean) false to field 'enableImagintronixOpus' in configuration class org.openhab.binding.rfxcom.internal.config.RFXComBridgeConfiguration
2016-11-13 00:21:26.855 [DEBUG] [.e.s.config.core.Configuration:94   ] - Setting value (boolean) false to field 'enableByronSX' in configuration class org.openhab.binding.rfxcom.internal.config.RFXComBridgeConfiguration
2016-11-13 00:21:26.855 [DEBUG] [.e.s.config.core.Configuration:94   ] - Setting value (boolean) false to field 'enableRSL' in configuration class org.openhab.binding.rfxcom.internal.config.RFXComBridgeConfiguration
2016-11-13 00:21:26.855 [DEBUG] [.e.s.config.core.Configuration:94   ] - Setting value (boolean) false to field 'enableLighting4' in configuration class org.openhab.binding.rfxcom.internal.config.RFXComBridgeConfiguration
2016-11-13 00:21:26.855 [DEBUG] [.e.s.config.core.Configuration:94   ] - Setting value (boolean) false to field 'enableFineOffsetViking' in configuration class org.openhab.binding.rfxcom.internal.config.RFXComBridgeConfiguration
2016-11-13 00:21:26.855 [DEBUG] [.e.s.config.core.Configuration:94   ] - Setting value (boolean) false to field 'enableRubicson' in configuration class org.openhab.binding.rfxcom.internal.config.RFXComBridgeConfiguration
2016-11-13 00:21:26.855 [DEBUG] [.e.s.config.core.Configuration:94   ] - Setting value (boolean) false to field 'enableAEBlyss' in configuration class org.openhab.binding.rfxcom.internal.config.RFXComBridgeConfiguration
2016-11-13 00:21:26.856 [DEBUG] [.e.s.config.core.Configuration:94   ] - Setting value (boolean) false to field 'enableBlindsT1T2T3T4' in configuration class org.openhab.binding.rfxcom.internal.config.RFXComBridgeConfiguration
2016-11-13 00:21:26.856 [DEBUG] [.e.s.config.core.Configuration:94   ] - Setting value (boolean) false to field 'enableBlindsT0' in configuration class org.openhab.binding.rfxcom.internal.config.RFXComBridgeConfiguration
2016-11-13 00:21:26.856 [DEBUG] [.e.s.config.core.Configuration:94   ] - Setting value (boolean) false to field 'enableProGuard' in configuration class org.openhab.binding.rfxcom.internal.config.RFXComBridgeConfiguration
2016-11-13 00:21:26.856 [DEBUG] [.e.s.config.core.Configuration:94   ] - Setting value (boolean) false to field 'enableFS20' in configuration class org.openhab.binding.rfxcom.internal.config.RFXComBridgeConfiguration
2016-11-13 00:21:26.856 [DEBUG] [.e.s.config.core.Configuration:94   ] - Setting value (boolean) false to field 'enableLaCrosse' in configuration class org.openhab.binding.rfxcom.internal.config.RFXComBridgeConfiguration
2016-11-13 00:21:26.856 [DEBUG] [.e.s.config.core.Configuration:94   ] - Setting value (boolean) false to field 'enableHidekiUPM' in configuration class org.openhab.binding.rfxcom.internal.config.RFXComBridgeConfiguration
2016-11-13 00:21:26.857 [DEBUG] [.e.s.config.core.Configuration:94   ] - Setting value (boolean) false to field 'enableADLightwaveRF' in configuration class org.openhab.binding.rfxcom.internal.config.RFXComBridgeConfiguration
2016-11-13 00:21:26.857 [DEBUG] [.e.s.config.core.Configuration:94   ] - Setting value (boolean) false to field 'enableMertik' in configuration class org.openhab.binding.rfxcom.internal.config.RFXComBridgeConfiguration
2016-11-13 00:21:26.857 [DEBUG] [.e.s.config.core.Configuration:94   ] - Setting value (boolean) false to field 'enableVisonic' in configuration class org.openhab.binding.rfxcom.internal.config.RFXComBridgeConfiguration
2016-11-13 00:21:26.857 [DEBUG] [.e.s.config.core.Configuration:94   ] - Setting value (boolean) false to field 'enableATI' in configuration class org.openhab.binding.rfxcom.internal.config.RFXComBridgeConfiguration
2016-11-13 00:21:26.857 [DEBUG] [.e.s.config.core.Configuration:94   ] - Setting value (boolean) false to field 'enableOregonScientific' in configuration class org.openhab.binding.rfxcom.internal.config.RFXComBridgeConfiguration
2016-11-13 00:21:26.857 [DEBUG] [.e.s.config.core.Configuration:94   ] - Setting value (boolean) false to field 'enableMeiantech' in configuration class org.openhab.binding.rfxcom.internal.config.RFXComBridgeConfiguration
2016-11-13 00:21:26.858 [DEBUG] [.e.s.config.core.Configuration:94   ] - Setting value (boolean) false to field 'enableHomeEasyEU' in configuration class org.openhab.binding.rfxcom.internal.config.RFXComBridgeConfiguration
2016-11-13 00:21:26.858 [DEBUG] [.e.s.config.core.Configuration:94   ] - Setting value (boolean) false to field 'enableAC' in configuration class org.openhab.binding.rfxcom.internal.config.RFXComBridgeConfiguration
2016-11-13 00:21:26.858 [DEBUG] [.e.s.config.core.Configuration:94   ] - Setting value (boolean) false to field 'enableARC' in configuration class org.openhab.binding.rfxcom.internal.config.RFXComBridgeConfiguration
2016-11-13 00:21:26.858 [DEBUG] [.e.s.config.core.Configuration:94   ] - Setting value (boolean) false to field 'enableX10' in configuration class org.openhab.binding.rfxcom.internal.config.RFXComBridgeConfiguration
2016-11-13 00:21:26.860 [INFO ] [marthome.event.ThingAddedEvent:43   ] - Thing 'rfxcom:temperaturehumidity:usb0:Test' has been added.
2016-11-13 00:21:26.860 [DEBUG] [.r.handler.RFXComBridgeHandler:113  ] - Checking RFXCOM transceiver connection, thing status = OFFLINE
2016-11-13 00:21:26.860 [DEBUG] [.r.handler.RFXComBridgeHandler:143  ] - Connecting to RFXCOM transceiver
2016-11-13 00:21:26.861 [DEBUG] [.c.thing.internal.ThingManager:504  ] - Thing 'rfxcom:temperaturehumidity:usb0:Test' is tracked by ThingManager.
2016-11-13 00:21:26.863 [DEBUG] [.c.thing.internal.ThingManager:630  ] - Calling 'RFXComHandlerFactory.registerHandler()' for thing 'rfxcom:temperaturehumidity:usb0:Test'.
2016-11-13 00:21:26.864 [DEBUG] [.c.thing.internal.ThingManager:117  ] - Thing handler for thing 'rfxcom:temperaturehumidity:usb0:Test' added.
2016-11-13 00:21:26.865 [DEBUG] [.c.thing.internal.ThingManager:290  ] - Assigning handler for thing 'rfxcom:temperaturehumidity:usb0:Test'.
2016-11-13 00:21:26.865 [DEBUG] [.c.thing.internal.ThingManager:697  ] - Finished loading meta-data of bundle 'org.openhab.binding.rfxcom'
2016-11-13 00:21:26.867 [DEBUG] [.c.thing.internal.ThingManager:758  ] - Calling initialize handler for thing 'rfxcom:lighting2:usb0:100001_1' at 'org.openhab.binding.rfxcom.handler.RFXComHandler@6867e7dc'.
2016-11-13 00:21:26.868 [INFO ] [ome.event.ThingStatusInfoEvent:43   ] - 'rfxcom:temperaturehumidity:usb0:Test' updated: INITIALIZING
2016-11-13 00:21:26.868 [DEBUG] [.c.thing.internal.ThingManager:754  ] - All data has been loaded, going to initialize 'rfxcom:temperaturehumidity:usb0:Test'.
2016-11-13 00:21:26.870 [INFO ] [nt.ThingStatusInfoChangedEvent:43   ] - 'rfxcom:temperaturehumidity:usb0:Test' changed from UNINITIALIZED to INITIALIZING
2016-11-13 00:21:26.871 [DEBUG] [b.rfxcom.handler.RFXComHandler:109  ] - Initializing thing rfxcom:lighting2:usb0:100001_1
2016-11-13 00:21:26.873 [DEBUG] [.c.thing.internal.ThingManager:758  ] - Calling initialize handler for thing 'rfxcom:temperaturehumidity:usb0:Test' at 'org.openhab.binding.rfxcom.handler.RFXComHandler@225ba83b'.
2016-11-13 00:21:26.874 [DEBUG] [.b.r.i.c.RFXComSerialConnector:84   ] - Disconnecting
2016-11-13 00:21:26.874 [DEBUG] [b.rfxcom.handler.RFXComHandler:109  ] - Initializing thing rfxcom:temperaturehumidity:usb0:Test
2016-11-13 00:21:26.874 [DEBUG] [.b.r.i.c.RFXComSerialConnector:115  ] - Closed
2016-11-13 00:21:26.895 [INFO ] [.e.s.m.c.i.ModelRepositoryImpl:92   ] - Loading model 'logging.persist'
2016-11-13 00:21:26.918 [DEBUG] [binding.ntp.handler.NtpHandler:220  ] - ntp:ntp:demo Got time update from: nl.pool.ntp.org : 2016-11-13 00:21:26 EET
2016-11-13 00:21:26.919 [DEBUG] [binding.ntp.handler.NtpHandler:189  ] - ntp:ntp:demo delta system time: -2
2016-11-13 00:21:26.920 [INFO ] [ome.event.ThingStatusInfoEvent:43   ] - 'ntp:ntp:demo' updated: ONLINE
2016-11-13 00:21:26.921 [INFO ] [nt.ThingStatusInfoChangedEvent:43   ] - 'ntp:ntp:demo' changed from INITIALIZING to ONLINE
2016-11-13 00:21:26.925 [INFO ] [.e.s.m.c.i.ModelRepositoryImpl:92   ] - Loading model 'rrd4j.persist'
2016-11-13 00:21:26.934 [INFO ] [.e.s.m.c.i.ModelRepositoryImpl:92   ] - Loading model 'demo.rules'
2016-11-13 00:21:27.220 [INFO ] [ome.event.ThingStatusInfoEvent:43   ] - 'rfxcom:lighting2:usb0:100001_1' updated: UNINITIALIZED (HANDLER_INITIALIZING_ERROR): org.eclipse.smarthome.core.thing.Bridge.getHandler()Lorg/eclipse/smarthome/core/thing/binding/BridgeHandler;
2016-11-13 00:21:27.220 [INFO ] [nt.ThingStatusInfoChangedEvent:43   ] - 'rfxcom:lighting2:usb0:100001_1' changed from INITIALIZING to UNINITIALIZED (HANDLER_INITIALIZING_ERROR): org.eclipse.smarthome.core.thing.Bridge.getHandler()Lorg/eclipse/smarthome/core/thing/binding/BridgeHandler;
2016-11-13 00:21:27.232 [ERROR] [.c.thing.internal.ThingManager:776  ] - Exception occured while initializing handler of thing 'rfxcom:lighting2:usb0:100001_1': java.lang.NoSuchMethodError: org.eclipse.smarthome.core.thing.Bridge.getHandler()Lorg/eclipse/smarthome/core/thing/binding/BridgeHandler;java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: org.eclipse.smarthome.core.thing.Bridge.getHandler()Lorg/eclipse/smarthome/core/thing/binding/BridgeHandler;
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at org.eclipse.smarthome.core.common.SafeMethodCaller.callAsynchronous(SafeMethodCaller.java:186)
	at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:79)
	at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:63)
	at org.eclipse.smarthome.core.thing.internal.ThingManager$9.run(ThingManager.java:761)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
Caused by: java.lang.NoSuchMethodError: org.eclipse.smarthome.core.thing.Bridge.getHandler()Lorg/eclipse/smarthome/core/thing/binding/BridgeHandler;
	at org.openhab.binding.rfxcom.handler.RFXComHandler.initialize(RFXComHandler.java:110)
	at org.eclipse.smarthome.core.thing.internal.ThingManager$9$1.call(ThingManager.java:764)
	at org.eclipse.smarthome.core.thing.internal.ThingManager$9$1.call(ThingManager.java:1)
	at org.eclipse.smarthome.core.common.SafeMethodCaller$CallableWrapper.call(SafeMethodCaller.java:177)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 common frames omitted

2016-11-13 00:21:27.290 [INFO ] [ome.event.ThingStatusInfoEvent:43   ] - 'rfxcom:temperaturehumidity:usb0:Test' updated: UNINITIALIZED (HANDLER_INITIALIZING_ERROR): org.eclipse.smarthome.core.thing.Bridge.getHandler()Lorg/eclipse/smarthome/core/thing/binding/BridgeHandler;
2016-11-13 00:21:27.291 [INFO ] [nt.ThingStatusInfoChangedEvent:43   ] - 'rfxcom:temperaturehumidity:usb0:Test' changed from INITIALIZING to UNINITIALIZED (HANDLER_INITIALIZING_ERROR): org.eclipse.smarthome.core.thing.Bridge.getHandler()Lorg/eclipse/smarthome/core/thing/binding/BridgeHandler;
2016-11-13 00:21:27.295 [ERROR] [.c.thing.internal.ThingManager:776  ] - Exception occured while initializing handler of thing 'rfxcom:temperaturehumidity:usb0:Test': java.lang.NoSuchMethodError: org.eclipse.smarthome.core.thing.Bridge.getHandler()Lorg/eclipse/smarthome/core/thing/binding/BridgeHandler;java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: org.eclipse.smarthome.core.thing.Bridge.getHandler()Lorg/eclipse/smarthome/core/thing/binding/BridgeHandler;
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at org.eclipse.smarthome.core.common.SafeMethodCaller.callAsynchronous(SafeMethodCaller.java:186)
	at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:79)
	at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:63)
	at org.eclipse.smarthome.core.thing.internal.ThingManager$9.run(ThingManager.java:761)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
Caused by: java.lang.NoSuchMethodError: org.eclipse.smarthome.core.thing.Bridge.getHandler()Lorg/eclipse/smarthome/core/thing/binding/BridgeHandler;
	at org.openhab.binding.rfxcom.handler.RFXComHandler.initialize(RFXComHandler.java:110)
	at org.eclipse.smarthome.core.thing.internal.ThingManager$9$1.call(ThingManager.java:764)
	at org.eclipse.smarthome.core.thing.internal.ThingManager$9$1.call(ThingManager.java:1)
	at org.eclipse.smarthome.core.common.SafeMethodCaller$CallableWrapper.call(SafeMethodCaller.java:177)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 common frames omitted

```

**Comment by kaikreuzer** [comment]
@paulianttila If you are working on the latest source of ESH, you will also have to pull https://github.com/openhab/openhab2-addons/pull/1394, which adapts the OH2 bindings to this refactoring. You can find the details of this change in https://github.com/eclipse/smarthome/pull/2087.
