### ISSUE TITLE
NPE when starting the ThingManager

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#2481]
I just came across this in my log file during startup:

```
Caused by: java.lang.NullPointerException
	at org.eclipse.smarthome.core.thing.internal.ThingManager.isVetoed(ThingManager.java:656)
	at org.eclipse.smarthome.core.thing.internal.ThingManager.doInitializeHandler(ThingManager.java:640)
	at org.eclipse.smarthome.core.thing.internal.ThingManager.initializeHandler(ThingManager.java:631)
	at org.eclipse.smarthome.core.thing.internal.ThingManager.thingAdded(ThingManager.java:440)
	at org.eclipse.smarthome.core.thing.internal.ThingRegistryImpl.notifyTrackerAboutAllThingsAdded(ThingRegistryImpl.java:240)
	at org.eclipse.smarthome.core.thing.internal.ThingRegistryImpl.addThingTracker(ThingRegistryImpl.java:60)
	at org.eclipse.smarthome.core.thing.internal.ThingManager.activate(ThingManager.java:1012)
	... 54 more
```

The NPE occurs because the handler is null (which might be due to the fact that I have Things for which no binding bundle is started).

**Comment by kaikreuzer** [comment]
@sbussweiler Very likely related to https://github.com/eclipse/smarthome/pull/2087 - may I ask you to have a look?

**Comment by kaikreuzer** [comment]
Further investigation showed that I had a binding, which declared a certain Thing type to be a bridge, but instantiated a ThingHandler and not a BridgeHandler for it - as a result, [this code](https://github.com/eclipse/smarthome/blob/master/bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/BridgeImpl.java#L69) returned null, although a handler was set in the Thing.

So two options:
1. Either continue to allow ThingHandlers instead of BridgeHandlers for Bridges.
2. Enforce ThingHandlerFactories to return BridgeHandlers for Bridges.

Probably (1) will cause issues as the framework expects at many places the specific handlers, so (2) is likely the better solution.

@sbussweiler, would you agree? Maybe the documentation needs to be more clear on that point as well?

**Comment by maggu2810** [comment]
I would prefer option 2 but perhaps instead of simple return null we should also write a log message.

**Comment by sbussweiler** [comment]
I will provide a proposal for solution 2 ;-)

**Comment by sbussweiler** [comment]
See #2487

**Comment by kaikreuzer** [comment]
Fixed by https://github.com/eclipse/smarthome/pull/2487
