### ISSUE TITLE
BaseThingHandler:channelLinked() called frequently / too much

### ISSUE THREAD

**Issue by kgoderis** [eclipse/smarthome#2491]
In a simple setup with a single Item -> Channel definition in the DSL, the above method is called three times (for the given channel) at startup of the runtime, twice triggered by ThingManager.added() and once by ItemRegistry.allItemsChanged(). 

Expected behaviour would be that the method is called once for each time an Item definition is parsed, taking into account the fact that "temporary" items are created. 

In my use case the channelLinked() triggers a read request on a bus (e.g. KNX), which is not designed to be flooded in this way, especially when reading out the same value multiple times.

**Comment by kaikreuzer** [comment]
I agree, this is an unwanted behavior. Maybe this is something that is also related to https://github.com/eclipse/smarthome/issues/1896 and should be considered in that context.

**Comment by sjka** [comment]
Are you sure it's not the auto-linking in "simple mode" of the ChannelItemProvider? As long as I have it enabled, I see two (not three) calls in total, which I understood is expected because it might be faster than the loading of the item files, gracefully cleaning up after itself once the DSL is loaded. Without the ChannelItemProvider, there is only one call.

**Comment by kgoderis** [comment]
@sjka mmh... even then, wouldn't it still be more logical to have a single call off channelLinked()? I presume you do not have the ItemRegistry originated call in your test?

**Comment by sjka** [comment]
Okay, when I run Eclipse SmartHome "as it is", I see those two calls:

1) originating from the ChannelItemProvider, because it created one of these dynamic items while my sjka.items file was not yet loaded:

```
java.lang.RuntimeException: stacktrace
    at de.sjka.binding.test.internal.ThingThingHandler.channelLinked(ThingThingHandler.java:75)
    at org.eclipse.smarthome.core.thing.link.ThingLinkManager.informHandlerAboutLinkedChannel(ThingLinkManager.java:263)
    at org.eclipse.smarthome.core.thing.link.ThingLinkManager.access$3(ThingLinkManager.java:254)
    at org.eclipse.smarthome.core.thing.link.ThingLinkManager$1.added(ThingLinkManager.java:124)
    at org.eclipse.smarthome.core.thing.link.ThingLinkManager$1.added(ThingLinkManager.java:1)
    at org.eclipse.smarthome.core.common.registry.AbstractRegistry.notifyListeners(AbstractRegistry.java:207)
    at org.eclipse.smarthome.core.common.registry.AbstractRegistry.notifyListeners(AbstractRegistry.java:226)
    at org.eclipse.smarthome.core.common.registry.AbstractRegistry.notifyListenersAboutAddedElement(AbstractRegistry.java:230)
    at org.eclipse.smarthome.core.internal.items.ItemRegistryImpl.notifyListenersAboutAddedElement(ItemRegistryImpl.java:385)
    at org.eclipse.smarthome.core.internal.items.ItemRegistryImpl.notifyListenersAboutAddedElement(ItemRegistryImpl.java:1)
    at org.eclipse.smarthome.core.common.registry.AbstractRegistry.added(AbstractRegistry.java:123)
    at org.eclipse.smarthome.core.thing.internal.ChannelItemProvider.createItemForLink(ChannelItemProvider.java:229)
    at org.eclipse.smarthome.core.thing.internal.ChannelItemProvider.access$1(ChannelItemProvider.java:198)
    at org.eclipse.smarthome.core.thing.internal.ChannelItemProvider$2.added(ChannelItemProvider.java:305)
    at org.eclipse.smarthome.core.thing.internal.ChannelItemProvider$2.added(ChannelItemProvider.java:1)
    at org.eclipse.smarthome.core.common.registry.AbstractRegistry.notifyListeners(AbstractRegistry.java:207)
    at org.eclipse.smarthome.core.common.registry.AbstractRegistry.notifyListeners(AbstractRegistry.java:226)
    at org.eclipse.smarthome.core.common.registry.AbstractRegistry.notifyListenersAboutAddedElement(AbstractRegistry.java:230)
    at org.eclipse.smarthome.core.thing.link.ItemChannelLinkRegistry.notifyListenersAboutAddedElement(ItemChannelLinkRegistry.java:144)
    at org.eclipse.smarthome.core.thing.link.ItemChannelLinkRegistry.notifyListenersAboutAddedElement(ItemChannelLinkRegistry.java:1)
    at org.eclipse.smarthome.core.common.registry.AbstractRegistry.added(AbstractRegistry.java:123)
    at org.eclipse.smarthome.core.common.registry.AbstractProvider.notifyListeners(AbstractProvider.java:51)
    at org.eclipse.smarthome.core.common.registry.AbstractProvider.notifyListeners(AbstractProvider.java:70)
    at org.eclipse.smarthome.core.common.registry.AbstractProvider.notifyListenersAboutAddedElement(AbstractProvider.java:74)
    at org.eclipse.smarthome.model.thing.internal.GenericItemChannelLinkProvider.createItemChannelLink(GenericItemChannelLinkProvider.java:102)
    at org.eclipse.smarthome.model.thing.internal.GenericItemChannelLinkProvider.processBindingConfiguration(GenericItemChannelLinkProvider.java:72)
    at org.eclipse.smarthome.model.item.internal.GenericItemProvider.internalDispatchBindings(GenericItemProvider.java:312)
    at org.eclipse.smarthome.model.item.internal.GenericItemProvider.internalDispatchBindings(GenericItemProvider.java:284)
    at org.eclipse.smarthome.model.item.internal.GenericItemProvider.processBindingConfigsFromModel(GenericItemProvider.java:167)
    at org.eclipse.smarthome.model.item.internal.GenericItemProvider.modelChanged(GenericItemProvider.java:338)
    at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.notifyListeners(ModelRepositoryImpl.java:207)
    at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.addOrRefreshModel(ModelRepositoryImpl.java:99)
    at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.checkFile(FolderObserver.java:267)
    at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.notifyUpdateToModelRepo(FolderObserver.java:195)
    at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.updated(FolderObserver.java:176)
    at org.eclipse.equinox.internal.cm.ManagedServiceTracker$1.run(ManagedServiceTracker.java:276)
    at org.eclipse.equinox.internal.cm.SerializedTaskQueue$1.run(SerializedTaskQueue.java:36)
```

One of the next log entries indicate that now my items file got loaded:

```
10:59:54.449 DEBUG o.e.s.m.i.i.GenericItemProvider[:129] - Read items from model 'sjka.items'
```

2) As a result, we have another channelLinked call, this time originating from the ItemRegistry because it refreshes all items which now come from the GenericItemProvider, i.e. from the DSL:

```
java.lang.RuntimeException: stacktrace
    at de.sjka.binding.test.internal.ThingThingHandler.channelLinked(ThingThingHandler.java:75)
    at org.eclipse.smarthome.core.thing.link.ThingLinkManager.informHandlerAboutLinkedChannel(ThingLinkManager.java:263)
    at org.eclipse.smarthome.core.thing.link.ThingLinkManager.access$3(ThingLinkManager.java:254)
    at org.eclipse.smarthome.core.thing.link.ThingLinkManager$1.added(ThingLinkManager.java:124)
    at org.eclipse.smarthome.core.thing.link.ThingLinkManager$1.added(ThingLinkManager.java:1)
    at org.eclipse.smarthome.core.internal.items.ItemRegistryImpl.allItemsChanged(ItemRegistryImpl.java:105)
    at org.eclipse.smarthome.model.item.internal.GenericItemProvider.modelChanged(GenericItemProvider.java:341)
    at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.notifyListeners(ModelRepositoryImpl.java:207)
    at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.addOrRefreshModel(ModelRepositoryImpl.java:99)
    at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.checkFile(FolderObserver.java:267)
    at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.notifyUpdateToModelRepo(FolderObserver.java:195)
    at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.updated(FolderObserver.java:176)
    at org.eclipse.equinox.internal.cm.ManagedServiceTracker$1.run(ManagedServiceTracker.java:276)
    at org.eclipse.equinox.internal.cm.SerializedTaskQueue$1.run(SerializedTaskQueue.java:36)
```

When I now disable the ChannelItemProvider (so that it cannot create those dynamic items anymore), I only see the second call, i.e. the one originating from the GenericItemProvider/ItemRegistry:

```
java.lang.RuntimeException: stacktrace
    at de.sjka.binding.test.internal.ThingThingHandler.channelLinked(ThingThingHandler.java:75)
    at org.eclipse.smarthome.core.thing.link.ThingLinkManager.informHandlerAboutLinkedChannel(ThingLinkManager.java:263)
    at org.eclipse.smarthome.core.thing.link.ThingLinkManager.access$3(ThingLinkManager.java:254)
    at org.eclipse.smarthome.core.thing.link.ThingLinkManager$1.added(ThingLinkManager.java:124)
    at org.eclipse.smarthome.core.thing.link.ThingLinkManager$1.added(ThingLinkManager.java:1)
    at org.eclipse.smarthome.core.internal.items.ItemRegistryImpl.allItemsChanged(ItemRegistryImpl.java:105)
    at org.eclipse.smarthome.model.item.internal.GenericItemProvider.modelChanged(GenericItemProvider.java:341)
    at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.notifyListeners(ModelRepositoryImpl.java:207)
    at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.addOrRefreshModel(ModelRepositoryImpl.java:99)
    at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.checkFile(FolderObserver.java:267)
    at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.notifyUpdateToModelRepo(FolderObserver.java:195)
    at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.updated(FolderObserver.java:176)
    at org.eclipse.equinox.internal.cm.ManagedServiceTracker$1.run(ManagedServiceTracker.java:276)
    at org.eclipse.equinox.internal.cm.SerializedTaskQueue$1.run(SerializedTaskQueue.java:36)
```

So, to me this still looks exactly like how this dynamic item creation stuff was intended to work. The only thing that we now could discuss if this actually is good or not, i.e. that we prefer to postpone the dynamic item creation until all known item files have been loaded completely in order to avoid these link-unlink-link steps.

**Comment by kgoderis** [comment]
FYI, I do have  a ItemRegistry.allItemsChanged() triggered call as well. Will provide a log of that, but that as such does not change the question/issue as you summarise here above. 

The link-unlink-link behaviour is a bit confusing, and there is no good way to deal with it in a binding.

**Comment by lolodomo** [comment]
To fix the Sonos binding, I traced all calls to handleCommand with a REFRESH command (meaning called by channelLinked) and I can see only one call per channel at startup.
