### ISSUE TITLE
ERROR in log after adding a hue bridge

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#2517]
When I approve a newly discovered hue bridge, the light discovery service tries to read the connected lights, but fails, since the bridge has not yet been paired at that moment:

```
2016-11-22 15:31:15.899 [DEBUG] [b.hue.handler.HueBridgeHandler:358  ] - Failed creating new user on Hue bridge: link button not pressed
2016-11-22 15:31:15.901 [INFO ] [ome.event.ThingStatusInfoEvent:43   ] - 'hue:bridge:001788141b41' updated: OFFLINE (CONFIGURATION_ERROR): Not authenticated - press pairing button on the bridge.
2016-11-22 15:31:15.909 [ERROR] [b.hue.handler.HueBridgeHandler:408  ] - Bridge cannot search for new lights.java.lang.IllegalStateException: linking is required before interacting with the bridge
	at nl.q42.jue.HueBridge.requireAuthentication(HueBridge.java:783)
	at nl.q42.jue.HueBridge.getFullConfig(HueBridge.java:771)
	at org.eclipse.smarthome.binding.hue.handler.HueBridgeHandler.getFullLights(HueBridgeHandler.java:405)
	at org.eclipse.smarthome.binding.hue.internal.discovery.HueLightDiscoveryService.startScan(HueLightDiscoveryService.java:83)
	at org.eclipse.smarthome.config.discovery.AbstractDiscoveryService.startScan(AbstractDiscoveryService.java:199)
	at org.eclipse.smarthome.config.discovery.internal.DiscoveryServiceRegistryImpl.startScan(DiscoveryServiceRegistryImpl.java:381)
	at org.eclipse.smarthome.config.discovery.internal.DiscoveryServiceRegistryImpl.startScans(DiscoveryServiceRegistryImpl.java:357)
	at org.eclipse.smarthome.config.discovery.internal.DiscoveryServiceRegistryImpl.startScan(DiscoveryServiceRegistryImpl.java:216)
	at org.eclipse.smarthome.io.rest.core.discovery.DiscoveryResource.scan(DiscoveryResource.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```

As this is a standard situation, there must not be any error logging.

**Comment by sjka** [comment]
fixed with #3621
