### ISSUE TITLE
Test failure(s): Hue: nupnp discovery

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#2530]
The Hue test fails with the recent master (at the time of writing -- rev is stated below).

```sh
git reset --hard eclipse/heads/master
```

```sh
git clean -x -d -f
```

```sh
git rev-parse HEAD
0051cfc229de51575f752ad67a42e49eecae0be0
```

```-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.eclipse.smarthome.binding.hue.test.HueLightDiscoveryServiceOSGITest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.215 sec - in org.eclipse.smarthome.binding.hue.test.HueLightDiscoveryServiceOSGITest
assert hue light registration(org.eclipse.smarthome.binding.hue.test.HueLightDiscoveryServiceOSGITest)  Time elapsed: 1.333 sec
assert startSearch is called(org.eclipse.smarthome.binding.hue.test.HueLightDiscoveryServiceOSGITest)  Time elapsed: 1.151 sec
Running org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest
Tests run: 31, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 39.881 sec - in org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest
assert command for brightness channel: on(org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest)  Time elapsed: 1.433 sec
assert command for color channel: black(org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest)  Time elapsed: 1.19 sec
assert command for color channel: white(org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest)  Time elapsed: 1.145 sec
assert command for color channel: increase(org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest)  Time elapsed: 3.395 sec
assert command for osram par16 50 for color temperature channel: off(org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest)  Time elapsed: 1.163 sec
assert command for color channel: decrease(org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest)  Time elapsed: 2.214 sec
assert command for osram par16 50 for brightness channel: off(org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest)  Time elapsed: 1.082 sec
assert command for osram par16 50 for color temperature channel: on(org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest)  Time elapsed: 1.086 sec
assert percentage value of color temperature when ct: 153(org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest)  Time elapsed: 0.016 sec
assert percentage value of color temperature when ct: 326(org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest)  Time elapsed: 0.009 sec
assert percentage value of color temperature when ct: 500(org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest)  Time elapsed: 0.009 sec
assert command for color temperature channel: 0%(org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest)  Time elapsed: 1.086 sec
assert command for color temperature channel: on(org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest)  Time elapsed: 1.09 sec
assert command for color channel: 0%(org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest)  Time elapsed: 1.096 sec
assert command for color channel: on(org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest)  Time elapsed: 1.084 sec
assert command for brightness channel: 50%(org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest)  Time elapsed: 1.089 sec
assert command for brightness channel: off(org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest)  Time elapsed: 1.081 sec
assert command for color temperature channel: 50%(org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest)  Time elapsed: 1.084 sec
assert command for color temperature channel: off(org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest)  Time elapsed: 1.086 sec
assert command for color channel: 50%(org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest)  Time elapsed: 1.08 sec
assert command for color channel: off(org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest)  Time elapsed: 1.082 sec
assert command for color channel: red(org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest)  Time elapsed: 1.083 sec
assert command for brightness channel: increase(org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest)  Time elapsed: 3.218 sec
assert command for alert channel(org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest)  Time elapsed: 3.232 sec
assert command for brightness channel: decrease(org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest)  Time elapsed: 2.154 sec
assert command for color temperature channel: 100%(org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest)  Time elapsed: 1.086 sec
assert that HueLightHandler status detail is set to bridge offline when the bridge is offline(org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest)  Time elapsed: 0.032 sec
assert command for osram par16 50 for brightness channel: on(org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest)  Time elapsed: 1.086 sec
assert command for color channel: 100%(org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest)  Time elapsed: 1.085 sec
assert command for color channel: blue(org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest)  Time elapsed: 1.082 sec
assert command for effect channel(org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest)  Time elapsed: 2.17 sec
Running org.eclipse.smarthome.binding.hue.test.HueBridgeHandlerOSGiTest
Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.171 sec - in org.eclipse.smarthome.binding.hue.test.HueBridgeHandlerOSGiTest
verify offline is set without bridge offline status(org.eclipse.smarthome.binding.hue.test.HueBridgeHandlerOSGiTest)  Time elapsed: 0.016 sec
assert that a status configuration message for missing bridge IP is properly returned (IP is an empty string)(org.eclipse.smarthome.binding.hue.test.HueBridgeHandlerOSGiTest)  Time elapsed: 0.022 sec
assert that an existing user is used if authentication was successful(org.eclipse.smarthome.binding.hue.test.HueBridgeHandlerOSGiTest)  Time elapsed: 0.021 sec
assert correct status if authentication failed for old user(org.eclipse.smarthome.binding.hue.test.HueBridgeHandlerOSGiTest)  Time elapsed: 0.033 sec
verify status if link button is not pressed(org.eclipse.smarthome.binding.hue.test.HueBridgeHandlerOSGiTest)  Time elapsed: 0.022 sec
assert that a status configuration message for missing bridge IP is properly returned (IP is null)(org.eclipse.smarthome.binding.hue.test.HueBridgeHandlerOSGiTest)  Time elapsed: 0.013 sec
assert that a new user is added to config if not existing yet(org.eclipse.smarthome.binding.hue.test.HueBridgeHandlerOSGiTest)  Time elapsed: 0.02 sec
verify status if new user cannot be created(org.eclipse.smarthome.binding.hue.test.HueBridgeHandlerOSGiTest)  Time elapsed: 0.019 sec
Running org.eclipse.smarthome.binding.hue.test.HueBridgeDiscoveryParticipantOSGITest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.088 sec - in org.eclipse.smarthome.binding.hue.test.HueBridgeDiscoveryParticipantOSGITest
assert no discovery result for unknown device(org.eclipse.smarthome.binding.hue.test.HueBridgeDiscoveryParticipantOSGITest)  Time elapsed: 0.053 sec
assert correct thing UID(org.eclipse.smarthome.binding.hue.test.HueBridgeDiscoveryParticipantOSGITest)  Time elapsed: 0.002 sec
assert no thing UID for unknown device(org.eclipse.smarthome.binding.hue.test.HueBridgeDiscoveryParticipantOSGITest)  Time elapsed: 0.004 sec
assert correct supported types(org.eclipse.smarthome.binding.hue.test.HueBridgeDiscoveryParticipantOSGITest)  Time elapsed: 0.003 sec
assert valid DiscoveryResult(org.eclipse.smarthome.binding.hue.test.HueBridgeDiscoveryParticipantOSGITest)  Time elapsed: 0.003 sec
Running org.eclipse.smarthome.binding.hue.test.HueBridgeNupnpDiscoveryOSGITest
Tests run: 4, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 30.339 sec <<< FAILURE! - in org.eclipse.smarthome.binding.hue.test.HueBridgeNupnpDiscoveryOSGITest
assert that invalid bridges are not discovered(org.eclipse.smarthome.binding.hue.test.HueBridgeNupnpDiscoveryOSGITest)  Time elapsed: 10.122 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: is <0>
     but: was <1>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:865)
	at org.junit.Assert.assertThat(Assert.java:832)
	at org.junit.Assert$assertThat.callStatic(Unknown Source)
	at org.eclipse.smarthome.binding.hue.test.HueBridgeNupnpDiscoveryOSGITest$_assert_that_invalid_bridges_are_not_discovered_closure23.doCall(HueBridgeNupnpDiscoveryOSGITest.groovy:242)
	at org.eclipse.smarthome.binding.hue.test.HueBridgeNupnpDiscoveryOSGITest$_assert_that_invalid_bridges_are_not_discovered_closure23.doCall(HueBridgeNupnpDiscoveryOSGITest.groovy)
	at sun.reflect.GeneratedMethodAccessor122.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:278)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at org.eclipse.smarthome.test.OSGiTest.waitForAssert(OSGiTest.groovy:181)
	at org.eclipse.smarthome.test.OSGiTest.waitForAssert(OSGiTest.groovy)
	at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:207)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:141)
	at org.eclipse.smarthome.binding.hue.test.HueBridgeNupnpDiscoveryOSGITest.assert that invalid bridges are not discovered(HueBridgeNupnpDiscoveryOSGITest.groovy:241)

assert that bridge thing type is supported(org.eclipse.smarthome.binding.hue.test.HueBridgeNupnpDiscoveryOSGITest)  Time elapsed: 0.009 sec
assert that valid bridges are discovered using the background discovery(org.eclipse.smarthome.binding.hue.test.HueBridgeNupnpDiscoveryOSGITest)  Time elapsed: 10.106 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: is <2>
     but: was <3>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:865)
	at org.junit.Assert.assertThat(Assert.java:832)
	at org.junit.Assert$assertThat.callStatic(Unknown Source)
	at org.eclipse.smarthome.binding.hue.test.HueBridgeNupnpDiscoveryOSGITest$_assert_that_valid_bridges_are_discovered_using_the_background_discovery_closure5.doCall(HueBridgeNupnpDiscoveryOSGITest.groovy:148)
	at org.eclipse.smarthome.binding.hue.test.HueBridgeNupnpDiscoveryOSGITest$_assert_that_valid_bridges_are_discovered_using_the_background_discovery_closure5.doCall(HueBridgeNupnpDiscoveryOSGITest.groovy)
	at sun.reflect.GeneratedMethodAccessor129.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:278)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:54)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at org.eclipse.smarthome.test.OSGiTest.waitForAssert(OSGiTest.groovy:181)
	at org.eclipse.smarthome.test.OSGiTest.waitForAssert(OSGiTest.groovy)
	at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:207)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:141)
	at org.eclipse.smarthome.binding.hue.test.HueBridgeNupnpDiscoveryOSGITest.assert that valid bridges are discovered using the background discovery(HueBridgeNupnpDiscoveryOSGITest.groovy:141)

assert that valid bridges are discovered(org.eclipse.smarthome.binding.hue.test.HueBridgeNupnpDiscoveryOSGITest)  Time elapsed: 10.09 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: is <2>
     but: was <3>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:865)
	at org.junit.Assert.assertThat(Assert.java:832)
	at org.junit.Assert$assertThat.callStatic(Unknown Source)
	at org.eclipse.smarthome.binding.hue.test.HueBridgeNupnpDiscoveryOSGITest$_assert_that_valid_bridges_are_discovered_closure10.doCall(HueBridgeNupnpDiscoveryOSGITest.groovy:179)
	at org.eclipse.smarthome.binding.hue.test.HueBridgeNupnpDiscoveryOSGITest$_assert_that_valid_bridges_are_discovered_closure10.doCall(HueBridgeNupnpDiscoveryOSGITest.groovy)
	at sun.reflect.GeneratedMethodAccessor134.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:278)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:54)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at org.eclipse.smarthome.test.OSGiTest.waitForAssert(OSGiTest.groovy:181)
	at org.eclipse.smarthome.test.OSGiTest.waitForAssert(OSGiTest.groovy)
	at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:207)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:141)
	at org.eclipse.smarthome.binding.hue.test.HueBridgeNupnpDiscoveryOSGITest.assert that valid bridges are discovered(HueBridgeNupnpDiscoveryOSGITest.groovy:172)


Results :

Failed tests: 
  HueBridgeNupnpDiscoveryOSGITest.assert that invalid bridges are not discovered:241->OSGiTest.waitForAssert:-1->OSGiTest.waitForAssert:181 
Expected: is <0>
     but: was <1>
  HueBridgeNupnpDiscoveryOSGITest.assert that valid bridges are discovered using the background discovery:141->OSGiTest.waitForAssert:-1->OSGiTest.waitForAssert:181 
Expected: is <2>
     but: was <3>
  HueBridgeNupnpDiscoveryOSGITest.assert that valid bridges are discovered:172->OSGiTest.waitForAssert:-1->OSGiTest.waitForAssert:181 
Expected: is <2>
     but: was <3>

Tests run: 50, Failures: 3, Errors: 0, Skipped: 0
```

**Comment by maggu2810** [comment]
Is this related to #2526?

As it seems not every machine is involved, its perhaps timing related.

**Comment by kaikreuzer** [comment]
https://github.com/eclipse/smarthome/pull/2526 isn't merged, so it cannot be related, can it?
On Travis, #2526 has succeeded.

**Comment by maggu2810** [comment]
> #2526 isn't merged, so it cannot be related, can it?

Why? If #2526 solved this error, it could be related.

**Comment by kaikreuzer** [comment]
Ok, related in a positive sense then. I read it as "failing tests could be due to #2526"...

**Comment by maggu2810** [comment]
> Ok, related in a positive sense then. I read it as "failing tests could be due to #2526"...

Yes, "positive sense" was the intention. I am not a pessimist :wink:

**Comment by sjka** [comment]
let's ask @chriskn to have a look anyway...

**Comment by chriskn** [comment]
Seems like an additional bridge is discovered which was not included in the test. I will add a inbox cleanup to the test asap

**Comment by maggu2810** [comment]
Fixed by: 2531
