### ISSUE TITLE
LIFX throws NPE

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#2551]
Trying to control a LIFX bulb (where the Thing is set to OFFLINE, whyever), I get this exception in the log:

```
17:11:03.513 [INFO ] [smarthome.event.ItemCommandEvent    ] - Item 'LIFX' received command 274,100,87
17:11:03.514 [ERROR] [inding.lifx.handler.LifxLightHandler] - Error while updating bulb: null
java.lang.NullPointerException
        at org.eclipse.smarthome.binding.lifx.internal.LifxUtils.percentTypeToKelvin(LifxUtils.java:83)[231:org.eclipse.smarthome.binding.lifx:0.9.0.201611272028]
        at org.eclipse.smarthome.binding.lifx.internal.LifxLightStateChanger.addSetColorRequestToMap(LifxLightStateChanger.java:232)[231:org.eclipse.smarthome.binding.lifx:0.9.0.201611272028]
        at org.eclipse.smarthome.binding.lifx.internal.LifxLightStateChanger.handleHSBChange(LifxLightStateChanger.java:213)[231:org.eclipse.smarthome.binding.lifx:0.9.0.201611272028]
        at org.eclipse.smarthome.binding.lifx.internal.LifxLightState.setHSB(LifxLightState.java:57)[231:org.eclipse.smarthome.binding.lifx:0.9.0.201611272028]
        at org.eclipse.smarthome.binding.lifx.handler.LifxLightHandler.handleHSBCommand(LifxLightHandler.java:328)[231:org.eclipse.smarthome.binding.lifx:0.9.0.201611272028]
        at org.eclipse.smarthome.binding.lifx.handler.LifxLightHandler.handleCommand(LifxLightHandler.java:273)[231:org.eclipse.smarthome.binding.lifx:0.9.0.201611272028]
        at org.eclipse.smarthome.core.thing.internal.ThingManager$3.call(ThingManager.java:355)[103:org.eclipse.smarthome.core.thing:0.9.0.201611272028]
        at org.eclipse.smarthome.core.thing.internal.ThingManager$3.call(ThingManager.java:1)[103:org.eclipse.smarthome.core.thing:0.9.0.201611272028]
        at org.eclipse.smarthome.core.common.SafeMethodCaller$CallableWrapper.call(SafeMethodCaller.java:177)[96:org.eclipse.smarthome.core:0.9.0.201611272028]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_101]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_101]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_101]
        at java.lang.Thread.run(Thread.java:745)[:1.8.0_101]
```

**Comment by kaikreuzer** [comment]
@wborn & @kgoderis Could you have a look?

**Comment by wborn** [comment]
Light temperature and HSB values will remain null unless they are received from the light itself. When the light has never been online they will thus remain null.

Both values are required when updating one of them because they are updated using the same packet. This exception does not occur when I disconnect power from one of my lights that has been online.

Solutions could be:

1. use a fallback in case values are null, this may cause unexpected changes to light HSB or temperature
2. ignore command (log warning) whenever one of the values is null
3. apply the last command(s) as soon as the light is online and proper values have been retrieved

I would either go with 2 or 3. End users will probably like 3, but it introduces more complexity.

**Comment by kaikreuzer** [comment]
Not sure that I can follow you.
As you can see, I tried to send a HSB command, i.e. I specifically defined all details (hue, saturation, brightness) and I simply expect the bulb to switch to this color - regardless whether there has been any communication before. There should be no information missing to send the appropriate request.
If the bulb expects a value for the temperature although I am sending HSB, I'd think we can clearly go for a default (thus your option 1) and likewise for sending a temperature without having a prior HSB value.

**Comment by wborn** [comment]
Thats right, the LIFX bulbs also expect a temperature value even though you only change HSB. And vice versa when you only change the temperature while HSB is null.

I checked some more code and we already use `HSBType.WHITE` as color default in `CurrentLightState.setPowerState` (see #2318). Do you have a preference for the temperature default? The range is from 2500K (warm) to 9000K (cool).

**Comment by kaikreuzer** [comment]
> I checked some more code and we already use HSBType.WHITE as color default in CurrentLightState.setPowerState 

That makes sense.

> Do you have a preference for the temperature default? The range is from 2500K (warm) to 9000K (cool).

My point is that it should not matter. "red" color has a fixed color temperature and it simply is not possible to set it to 2500K-9000K. Color temperature really only makes sense for different tones of white. Afaik, LIFX only uses this value as a starting point, if you switch their app to "white tones" control. In this app, they seem to set 3000K as a default, which they also call "neutral". So I would assume that this is the best default to use then.
