### ISSUE TITLE
Exception (TimeoutException) for Sonos thing

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#2585]
Here is the exception I got at first startup of snapshot 627:
```
2016-12-01 23:07:03.682 [INFO ] [core.karaf.internal.FeatureInstaller] - Installed 'openhab-binding-sonos'
2016-12-01 23:07:09.502 [ERROR] [ome.core.thing.internal.ThingManager] - Exception occured while calling thing updated at ThingHandler 'org.eclipse.smarthome.binding.sonos.handler.ZonePlayerHandler@16c2232': null
java.util.concurrent.TimeoutException
        at java.util.concurrent.FutureTask.get(FutureTask.java:205)[:1.8.0_65]
        at org.eclipse.smarthome.core.common.SafeMethodCaller.callAsynchronous(SafeMethodCaller.java:186)[96:org.eclipse.smarthome.core:0.9.0.201612010841]
        at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:79)[96:org.eclipse.smarthome.core:0.9.0.201612010841]
        at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:63)[96:org.eclipse.smarthome.core:0.9.0.201612010841]
        at org.eclipse.smarthome.core.thing.internal.ThingManager.thingUpdated(ThingManager.java:500)[103:org.eclipse.smarthome.core.thing:0.9.0.201612010841]
        at org.eclipse.smarthome.core.thing.internal.ThingRegistryImpl.notifyTrackers(ThingRegistryImpl.java:226)[103:org.eclipse.smarthome.core.thing:0.9.0.201612010841]
        at org.eclipse.smarthome.core.thing.internal.ThingRegistryImpl.notifyListenersAboutUpdatedElement(ThingRegistryImpl.java:149)[103:org.eclipse.smarthome.core.thing:0.9.0.201612010841]
        at org.eclipse.smarthome.core.thing.internal.ThingRegistryImpl.notifyListenersAboutUpdatedElement(ThingRegistryImpl.java:1)[103:org.eclipse.smarthome.core.thing:0.9.0.201612010841]
        at org.eclipse.smarthome.core.common.registry.AbstractRegistry.updated(AbstractRegistry.java:167)[96:org.eclipse.smarthome.core:0.9.0.201612010841]
        at org.eclipse.smarthome.core.common.registry.AbstractProvider.notifyListeners(AbstractProvider.java:57)[96:org.eclipse.smarthome.core:0.9.0.201612010841]
        at org.eclipse.smarthome.core.common.registry.AbstractProvider.notifyListenersAboutUpdatedElement(AbstractProvider.java:82)[96:org.eclipse.smarthome.core:0.9.0.201612010841]
        at org.eclipse.smarthome.model.thing.internal.GenericThingProvider.access$3(GenericThingProvider.java:1)[131:org.eclipse.smarthome.model.thing:0.9.0.201612010841]
        at org.eclipse.smarthome.model.thing.internal.GenericThingProvider$1$2.apply(GenericThingProvider.java:985)[131:org.eclipse.smarthome.model.thing:0.9.0.201612010841]
        at org.eclipse.smarthome.model.thing.internal.GenericThingProvider$1$2.apply(GenericThingProvider.java:1)[131:org.eclipse.smarthome.model.thing:0.9.0.201612010841]
        at org.eclipse.xtext.xbase.lib.IteratorExtensions.forEach(IteratorExtensions.java:363)[144:org.eclipse.xtext.xbase.lib:2.9.2]
        at org.eclipse.xtext.xbase.lib.IterableExtensions.forEach(IterableExtensions.java:333)[144:org.eclipse.xtext.xbase.lib:2.9.2]
        at org.eclipse.smarthome.model.thing.internal.GenericThingProvider$1.run(GenericThingProvider.java:994)[131:org.eclipse.smarthome.model.thing:0.9.0.201612010841]
        at java.lang.Thread.run(Thread.java:745)[:1.8.0_65]
2016-12-01 23:07:09.662 [WARN ] [ome.core.thing.internal.ThingManager] - Disposing handler for thing 'sonos:PLAY5:chambre' takes more than 5000ms.
2016-12-01 23:07:09.842 [WARN ] [ome.core.thing.internal.ThingManager] - Thing handler for thing 'sonos:CONNECTAMP:salon' already registered
2016-12-01 23:07:09.843 [WARN ] [ome.core.thing.internal.ThingManager] - Thing handler for thing 'sonos:PLAY5:chambre' already registered
```

**Comment by lolodomo** [comment]
I don't know if there is a link but when exiting from OH, I got this:
```
2016-12-01 23:26:02.360 [WARN ] [ome.core.thing.internal.ThingManager] - Cannot unregister handler. No handler factory for thing 'sonos:CONNECTAMP:salon' found.
2016-12-01 23:26:02.361 [WARN ] [ome.core.thing.internal.ThingManager] - Cannot unregister handler. No handler factory for thing 'sonos:PLAY5:chambre' found.
```

**Comment by lolodomo** [comment]
The error occurs at each startup.

**Comment by lolodomo** [comment]
As a result, the Sonos binding is not working well.

**Comment by kaikreuzer** [comment]
@sjka & @sbussweiler, Might this be a side effect of https://github.com/eclipse/smarthome/pull/2568?

**Comment by sjka** [comment]
> Might this be a side effect of #2568?

Doesn't look like it, as this is not about handler registration, but simply a call to ThingHandler.thingUpdated() only. So it seems this indeed took too long. This rather looks like an issue with sonos, especially as it's not usable afterwards. The TimeoutException keeps the thread running, so it should become usable eventually. We are once again not logging the execution point of the "hanging" thread in this place, so it's really hard to tell what might have gone wrong.

**Comment by sjka** [comment]
No, wait, hang on a second... @lolodomo could you please search your logs again for a line like this?

```Timeout of {}ms exceeded, thread {} ({}) in state {} is at {}.{}({}:{}).```

That should at least tell us where the sonos handler is hanging so long.

**Comment by sjka** [comment]
btw, the "Cannot unregister handler" during shutdown of course it not nice, but rather harmless and unrelated to this. I created #2586 to fix it.

**Comment by kaikreuzer** [comment]
Just tested with a Sonos speaker and it works for me, so there does not seem to be a general issue with the Sonos binding.
@lolodomo It seems you have defined it in a things file, is that right?

> btw, the "Cannot unregister handler" during shutdown of course it not nice

@sjka Note that this log is from the system startup. So it is not the shutdown of the system, where this occurs, but when disposing the handler because it didn't initialize correcty, which is a bit unexpected to me here as well...

**Comment by lolodomo** [comment]
@sjka : no such log entry

@kaikreuzer : yes of course my Sonos are defined in a thing file like this:
```
Thing sonos:CONNECTAMP:salon "Sonos Salon" [ udn="RINCON_XXXXXXXXXXXX01400" ]
Thing sonos:PLAY5:chambre "Sonos Chambre" [ udn="RINCON_XXXXXXXXXXXX01400" ]
```

**Comment by kaikreuzer** [comment]
Works for me as well with a things file. Here are my logs:
```
09:02:44.576 [DEBUG] [g.sonos.internal.SonosHandlerFactory] - Creating a sonos thing with ID 'sonos:PLAY1:chambre'
09:02:44.638 [DEBUG] [ome.core.thing.internal.ThingManager] - Thing 'sonos:PLAY1:chambre' is tracked by ThingManager.
09:02:44.639 [DEBUG] [ome.core.thing.internal.ThingManager] - Calling 'SonosHandlerFactory.registerHandler()' for thing 'sonos:PLAY1:chambre'.
09:02:44.640 [DEBUG] [g.sonos.internal.SonosHandlerFactory] - Creating a ZonePlayerHandler for thing 'sonos:PLAY1:chambre' with UDN 'RINCON_XXX'
09:02:44.641 [INFO ] [smarthome.event.ThingAddedEvent     ] - Thing 'sonos:PLAY1:chambre' has been added.
09:02:44.652 [DEBUG] [ding.sonos.handler.ZonePlayerHandler] - Creating a ZonePlayerHandler for thing 'sonos:PLAY1:chambre'
09:02:44.656 [DEBUG] [org.eclipse.smarthome.binding.sonos ] - ServiceEvent REGISTERED - {org.eclipse.smarthome.core.audio.AudioSink}={service.id=300, service.bundleid=202, service.scope=singleton} - org.eclipse.smarthome.binding.sonos
09:02:44.658 [DEBUG] [ome.core.thing.internal.ThingManager] - Finished loading meta-data of bundle 'org.eclipse.smarthome.binding.sonos'
09:02:44.661 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'sonos:PLAY1:chambre' changed from UNINITIALIZED to INITIALIZING
09:02:44.661 [DEBUG] [ome.core.thing.internal.ThingManager] - Calling initialize handler for thing 'sonos:PLAY1:chambre' at 'org.eclipse.smarthome.binding.sonos.handler.ZonePlayerHandler@86baa70'.
09:02:44.662 [DEBUG] [ding.sonos.handler.ZonePlayerHandler] - initializing handler for thing sonos:PLAY1:chambre
09:02:44.673 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'sonos:PLAY1:chambre' changed from INITIALIZING to ONLINE
09:02:44.673 [DEBUG] [ding.sonos.handler.ZonePlayerHandler] - Polling job
09:02:44.674 [DEBUG] [ding.sonos.handler.ZonePlayerHandler] - UPnP device RINCON_XXX not yet registered
09:02:44.676 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'sonos:PLAY1:chambre' changed from ONLINE to OFFLINE
09:02:44.825 [DEBUG] [overy.ZonePlayerDiscoveryParticipant] - Discovered a Sonos 'sonos:PLAY1' thing with UDN 'RINCON_XXX'
09:02:44.855 [DEBUG] [overy.ZonePlayerDiscoveryParticipant] - Created a DiscoveryResult for device '192.168.0.135 - Sonos PLAY:1' with UDN 'RINCON_XXX'
09:03:44.673 [DEBUG] [ding.sonos.handler.ZonePlayerHandler] - Polling job
09:03:44.699 [DEBUG] [ding.sonos.handler.ZonePlayerHandler] - Sonos player PLAY:1 has been found in local network
09:03:44.699 [DEBUG] [ding.sonos.handler.ZonePlayerHandler] - RINCON_XXX: Subscribing to service DeviceProperties...
09:03:44.700 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'sonos:PLAY1:chambre' changed from OFFLINE to ONLINE
```

Unrelated to your problem, what I observe is that the Thing is OFFLINE for one minute as it seems to fail to get the UPnP notification that the speaker is found in the network (you can see that the inbox correctly notices it). @kgoderis Is this something you could check if it can be improved?

**Comment by lolodomo** [comment]
This is something else we discussed several months ago. There is probably a bug in jupnp. I am the one who implemented the retry mechanism in the Sonos binding.

**Comment by lolodomo** [comment]
The "cannot unregister handler" is at shutdown not at startup.
The timeout exception is at startup.

**Comment by kaikreuzer** [comment]
```
2016-12-01 23:07:09.662 [WARN ] [ome.core.thing.internal.ThingManager] - Disposing handler for thing 'sonos:PLAY5:chambre' takes more than 5000ms.
```
23:07:09.662 minus 5 seconds is 23:07:04:662. So your shutdown happens already 1 second after the startup at 
```
2016-12-01 23:07:03.682 [INFO ] [core.karaf.internal.FeatureInstaller] - Installed 'openhab-binding-sonos'
```
?

**Comment by lolodomo** [comment]
Ok, there is apparently a "dispose" called but it was not me shutting down openHAB.
In the next startups, I don't think that I have this warning about disposing handler that takes more than 5000 ms. I will check.
```
2016-12-01 23:07:03.682 [INFO ] [core.karaf.internal.FeatureInstaller] - Installed 'openhab-binding-sonos'
```
It does just show that the binding has just been installed. Remember it was my first startup.
Maybe after the install, the bundle is stopped before being restarting. It could explain the "displse handler" ?

**Comment by lolodomo** [comment]
I can confirm that the "disposing handler takes more than 5000ms" only occured once for the Sonos binding. The next time, I got the exception without this warning.

**Comment by lolodomo** [comment]
I can confirm that the exception is not systematic. New start and this time, it was ok. That looks clearly as a timing issue.

**Comment by sjka** [comment]
FYI, regarding the question where it's hanging: I just noticed that the log entry I was asking for is on DEBUG level, so you would need to enable DEBUG logging for the `org.eclipse.smarthome.core.common` package if you wanted to find that out.

**Comment by lolodomo** [comment]
Unfortunately, I installed an updated version of the Sonos binding and now, even after installing again the version packaged with the snapshot 627, I am no more able to reproduce the exception. With my install/uninstall, I probably changed timings and order things are started.
I will let you know what happens when I install a new fresh snapshot from scratch.

**Comment by lolodomo** [comment]
With the snapshot 636, I only get the exception at the first startup, unfortunately before I can set the DEBUG logs.

**Comment by lolodomo** [comment]
Got it finally:
```
10:52:30.928 [DEBUG] [arthome.core.common.SafeMethodCaller] - Timeout of 5000ms exceeded, thread safeCall-22 (879) in state BLOCKED is at org.jupnp.controlpoint.SubscriptionCallback.end(SubscriptionCallback.java:250).
10:52:30.932 [ERROR] [ome.core.thing.internal.ThingManager] - Exception occured while calling thing updated at ThingHandler 'org.eclipse.smarthome.binding.sonos.handler.ZonePlayerHandler@1ad0bfa': null
java.util.concurrent.TimeoutException
        at java.util.concurrent.FutureTask.get(FutureTask.java:205)[:1.8.0_65]
        at org.eclipse.smarthome.core.common.SafeMethodCaller.callAsynchronous(SafeMethodCaller.java:188)[96:org.eclipse.smarthome.core:0.9.0.201612091054]
        at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:81)[96:org.eclipse.smarthome.core:0.9.0.201612091054]
        at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:65)[96:org.eclipse.smarthome.core:0.9.0.201612091054]
        at org.eclipse.smarthome.core.thing.internal.ThingManager.thingUpdated(ThingManager.java:513)[103:org.eclipse.smarthome.core.thing:0.9.0.201612091054]
        at org.eclipse.smarthome.core.thing.internal.ThingRegistryImpl.notifyTrackers(ThingRegistryImpl.java:226)[103:org.eclipse.smarthome.core.thing:0.9.0.201612091054]
        at org.eclipse.smarthome.core.thing.internal.ThingRegistryImpl.notifyListenersAboutUpdatedElement(ThingRegistryImpl.java:149)[103:org.eclipse.smarthome.core.thing:0.9.0.201612091054]
        at org.eclipse.smarthome.core.thing.internal.ThingRegistryImpl.notifyListenersAboutUpdatedElement(ThingRegistryImpl.java:1)[103:org.eclipse.smarthome.core.thing:0.9.0.201612091054]
        at org.eclipse.smarthome.core.common.registry.AbstractRegistry.updated(AbstractRegistry.java:167)[96:org.eclipse.smarthome.core:0.9.0.201612091054]
        at org.eclipse.smarthome.core.common.registry.AbstractProvider.notifyListeners(AbstractProvider.java:57)[96:org.eclipse.smarthome.core:0.9.0.201612091054]
        at org.eclipse.smarthome.core.common.registry.AbstractProvider.notifyListenersAboutUpdatedElement(AbstractProvider.java:82)[96:org.eclipse.smarthome.core:0.9.0.201612091054]
        at org.eclipse.smarthome.model.thing.internal.GenericThingProvider.access$3(GenericThingProvider.java:1)[131:org.eclipse.smarthome.model.thing:0.9.0.201612091054]
        at org.eclipse.smarthome.model.thing.internal.GenericThingProvider$1$2.apply(GenericThingProvider.java:985)[131:org.eclipse.smarthome.model.thing:0.9.0.201612091054]
        at org.eclipse.smarthome.model.thing.internal.GenericThingProvider$1$2.apply(GenericThingProvider.java:1)[131:org.eclipse.smarthome.model.thing:0.9.0.201612091054]
        at org.eclipse.xtext.xbase.lib.IteratorExtensions.forEach(IteratorExtensions.java:363)[144:org.eclipse.xtext.xbase.lib:2.9.2]
        at org.eclipse.xtext.xbase.lib.IterableExtensions.forEach(IterableExtensions.java:333)[144:org.eclipse.xtext.xbase.lib:2.9.2]
        at org.eclipse.smarthome.model.thing.internal.GenericThingProvider$1.run(GenericThingProvider.java:994)[131:org.eclipse.smarthome.model.thing:0.9.0.201612091054]
        at java.lang.Thread.run(Thread.java:745)[:1.8.0_65]
10:52:30.961 [INFO ] [smarthome.event.ThingUpdatedEvent   ] - Thing 'sonos:CONNECTAMP:salon' has been updated.
10:52:31.031 [INFO ] [smarthome.event.ThingUpdatedEvent   ] - Thing 'sonos:PLAY5:chambre' has been updated.
10:52:41.033 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'sonos:PLAY5:chambre' changed from ONLINE to OFFLINE
```

**Comment by lolodomo** [comment]
I think I have the explanation. We have a lock to avoid removing GENA suscriptions while they are being added.
If the thing is updated while GENA subscriptions are being added, handler disposing will be locked and this could probably explain the timeout.
No clear udea how to fix that.
What is the reason of this thing update just after the thing handler initialization?

**Comment by lolodomo** [comment]
In fact, didpise() first cancel the polling job before remving GENA subscription.
Does the cancel only cancel the next scheduling of the job or does it interrupt the current running of the job too?

**Comment by lolodomo** [comment]
Cancel with true as parameter normally interrupts the running task. So my analysis was probably wrong.
So anyone to help me analysing why there is a thing update and it ends in timeout?

**Comment by kaikreuzer** [comment]
Your thing comes from a things file. @sjka Do you know why the GenericThingProvider causes a thing update here and not merely adds it once?

**Comment by maggu2810** [comment]
Has this issue been solved?

**Comment by lolodomo** [comment]
Don't know but I have not encountered it recently (but I don't restart OH very often too).

**Comment by maggu2810** [comment]
WDYT could we close it for now and reopen if it is still present?

**Comment by lolodomo** [comment]
Ok
