### ISSUE TITLE
[Test Failures] FirmwareUpdateServiceOSGiTest setup

### ISSUE THREAD

**Issue by sjka** [eclipse/smarthome#2770]
Happend at  https://github.com/eclipse/smarthome/commit/1a12e3b4e0fa6c370c4940d515a048f841e41b19 on [Travis](https://travis-ci.org/eclipse/smarthome/builds/189453129):

```
assert that progress info and result events are sent(org.eclipse.smarthome.core.thing.firmware.FirmwareUpdateServiceOSGiTest)  Time elapsed: 10.186 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: is <3>
     but: was <2>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:865)
	at org.junit.Assert.assertThat(Assert.java:832)
	at org.junit.Assert$assertThat.callStatic(Unknown Source)
	at org.eclipse.smarthome.core.thing.firmware.FirmwareUpdateServiceOSGiTest$_setup_closure5.doCall(FirmwareUpdateServiceOSGiTest.groovy:246)
	at org.eclipse.smarthome.core.thing.firmware.FirmwareUpdateServiceOSGiTest$_setup_closure5.doCall(FirmwareUpdateServiceOSGiTest.groovy)
	at sun.reflect.GeneratedMethodAccessor87.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:278)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at org.eclipse.smarthome.test.OSGiTest.waitForAssert(OSGiTest.groovy:199)
	at org.eclipse.smarthome.test.OSGiTest.waitForAssert(OSGiTest.groovy)
	at sun.reflect.GeneratedMethodAccessor49.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:207)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:141)
	at org.eclipse.smarthome.core.thing.firmware.FirmwareUpdateServiceOSGiTest.setup(FirmwareUpdateServiceOSGiTest.groovy:245)
```

@tomhoefer @chriskn could you please have a look?

**Comment by tomhoefer** [comment]
I will have a look

**Comment by tomhoefer** [comment]
did it fail only once or have you seen it more often?

The only thing I could do is to increase the timeout from 10 sec to e.g. 30 sec....

**Comment by sjka** [comment]
I personally have seen it twice: One on Travis (as linked above) and once on my mac.

**Comment by tomhoefer** [comment]
Hmmm.. on your mac? Increasing the timeout will not help here...

**Comment by maggu2810** [comment]
@sjka Are you willing to close this issue? It's an old one...

**Comment by sjka** [comment]
it's old but not really fixed afaik. Nevertheless I'm happy to close until it happens again.
