### ISSUE TITLE
[yahooweather] Changing the refresh interval in Paper UI leads to message about an invalid WOEID

### ISSUE THREAD

**Issue by MHerbst** [eclipse/smarthome#2779]
This maybe a general problem in Paper UI but right now I only saw it in the Yahoo Binding.

I have edited the thing configuration and modified the refresh interval (from 60 to 67):
![image](https://cloud.githubusercontent.com/assets/616792/21745147/ebdc849e-d524-11e6-8f9d-9f8faddc4894.png)

After I pressed the save button I got the following messages in the Karaf console:
```
21:59:12.364 [INFO ] [marthome.event.ConfigStatusInfoEvent] - ConfigStatusInfo [configStatusMessages=[]]
21:59:12.365 [INFO ] [marthome.event.ConfigStatusInfoEvent] - ConfigStatusInfo [configStatusMessages=[ConfigStatusMessage [parameterName=location, type=ERROR, messageKey=null, arguments=null, message=Der Ort f³r die WOEID 641.311 konnte nicht gefunden werden., statusCode=null]]]
```
Please note the decimal point in the WOEID.

This is not really a problem because the binding works as before. But something happend with the content of the WOEID that is probably not desired.

**Comment by sjka** [comment]
Just did a quick debugging on it: The format of the WEOID in the log seems to be a pure formatting issue when writing the log output. At least it is correct in the query. 

However, the fact that this log message gets written _at all_ points to an error with the yahoo API. I can reproduce it as well - the first call after updating the WEOID raises an error. Could it be that we hit some quota limits on Yahoo side?

**Comment by sjka** [comment]
One update: I noticed that if some configuration change is done, the binding fetches the weather data 3 times in a row from Yahoo:

```
java.lang.RuntimeException: I was here
	at org.eclipse.smarthome.binding.yahooweather.handler.YahooWeatherHandler.getWeatherData(YahooWeatherHandler.java:174)
	at org.eclipse.smarthome.binding.yahooweather.handler.YahooWeatherHandler.getConfigStatus(YahooWeatherHandler.java:143)
	at org.eclipse.smarthome.config.core.status.ConfigStatusService.getConfigStatus(ConfigStatusService.java:100)
	at org.eclipse.smarthome.config.core.status.ConfigStatusService.getConfigStatus(ConfigStatusService.java:70)
	at org.eclipse.smarthome.config.core.status.ConfigStatusService$1.run(ConfigStatusService.java:84)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
java.lang.RuntimeException: I was here
	at org.eclipse.smarthome.binding.yahooweather.handler.YahooWeatherHandler.getWeatherData(YahooWeatherHandler.java:174)
	at org.eclipse.smarthome.binding.yahooweather.handler.YahooWeatherHandler.getConfigStatus(YahooWeatherHandler.java:143)
	at org.eclipse.smarthome.config.core.status.ConfigStatusService.getConfigStatus(ConfigStatusService.java:100)
	at org.eclipse.smarthome.config.core.status.ConfigStatusService.getConfigStatus(ConfigStatusService.java:70)
	at org.eclipse.smarthome.config.core.status.ConfigStatusService$1.run(ConfigStatusService.java:84)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
java.lang.RuntimeException: I was here
	at org.eclipse.smarthome.binding.yahooweather.handler.YahooWeatherHandler.getWeatherData(YahooWeatherHandler.java:174)
	at org.eclipse.smarthome.binding.yahooweather.handler.YahooWeatherHandler.updateWeatherData(YahooWeatherHandler.java:159)
	at org.eclipse.smarthome.binding.yahooweather.handler.YahooWeatherHandler.access$0(YahooWeatherHandler.java:157)
	at org.eclipse.smarthome.binding.yahooweather.handler.YahooWeatherHandler$1.run(YahooWeatherHandler.java:98)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

The first two are to check if the configuration is valid, the last one to actually fetch the data. Doesn't sound too optimal to me...
