### ISSUE TITLE
Exception in thread “Dir Watcher”

### ISSUE THREAD

**Issue by jackdewinter** [eclipse/smarthome#2827]
When trying to develop my rules, I am getting the following quite frequently now. Once I hit this, I need to reboot OpenHab to get it working again.

Is there any more information I can provide? I can get this to repro by saving my .things, .items, and .rules files, changing each one and cycling back. Usually happens by the second or third cycle. Note that the uid issue does not show up in the logs until this happens.

```
11:26:32.832 [INFO ] [el.core.internal.ModelRepositoryImpl] - Refreshing model '
demo.things'
Exception in thread "Dir Watcher" java.lang.IllegalArgumentException: Given uid
must not be null.
at org.eclipse.smarthome.core.thing.UID.splitToSegments(UID.java:48)
at org.eclipse.smarthome.core.thing.UID.(UID.java:43)
at org.eclipse.smarthome.core.thing.ThingUID.(ThingUID.java:139)
at org.eclipse.smarthome.model.thing.internal.GenericThingProvider$14$1.
apply(GenericThingProvider.java:808)
at org.eclipse.smarthome.model.thing.internal.GenericThingProvider$14$1.
apply(GenericThingProvider.java:1)
at org.eclipse.xtext.xbase.lib.internal.FunctionDelegate.apply(FunctionD
elegate.java:42)
at com.google.common.collect.Lists$TransformingRandomAccessList$1.transf
orm(Lists.java:617)
at com.google.common.collect.TransformedIterator.next(TransformedIterato
r.java:48)
at java.util.AbstractCollection.contains(AbstractCollection.java:106)
at org.eclipse.smarthome.model.thing.internal.GenericThingProvider$14.ap
ply(GenericThingProvider.java:813)
at org.eclipse.smarthome.model.thing.internal.GenericThingProvider$14.ap
ply(GenericThingProvider.java:1)
at org.eclipse.xtext.xbase.lib.internal.BooleanFunctionDelegate.apply(Bo
oleanFunctionDelegate.java:41)
at com.google.common.collect.Iterators$7.computeNext(Iterators.java:652)
at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.j
ava:138)
at org.eclipse.xtext.xbase.lib.IteratorExtensions.forEach(IteratorExtens
ions.java:362)
at org.eclipse.xtext.xbase.lib.IterableExtensions.forEach(IterableExtens
ions.java:333)
at org.eclipse.smarthome.model.thing.internal.GenericThingProvider.model
Changed(GenericThingProvider.java:824)
at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.notifyL
isteners(ModelRepositoryImpl.java:207)
at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.addOrRe
freshModel(ModelRepositoryImpl.java:120)
at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.check
File(FolderObserver.java:270)
at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.acces
s$1(FolderObserver.java:264)
at org.eclipse.smarthome.model.core.internal.folder.FolderObserver$Watch
QueueReader.processWatchEvent(FolderObserver.java:145)
at org.eclipse.smarthome.core.service.AbstractWatchQueueReader.run(Abstr
actWatchQueueReader.java:122)
at java.lang.Thread.run(Thread.java:745)
```

**Comment by kaikreuzer** [comment]
Clearly, the FolderObserver should catch such exceptions and it should not cause it to crash.
