### ISSUE TITLE
Astro binding throws NPE

### ISSUE THREAD

**Issue by J-N-K** [eclipse/smarthome#2868]
`12:43:00.002 [ERROR] [org.quartz.core.JobRunShell         ] - Job astro:sun:local.job-event-start-noon#event threw an unhandled Exception:
java.lang.NullPointerException
        at org.openhab.binding.astro.handler.AstroThingHandler.triggerEvent(AstroThingHandler.java:304)[185:org.openhab.binding.astro:2.0.0.201701121723]
        at org.openhab.binding.astro.internal.job.EventJob.executeJob(EventJob.java:32)[185:org.openhab.binding.astro:2.0.0.201701121723]
        at org.openhab.binding.astro.internal.job.AbstractBaseJob.execute(AbstractBaseJob.java:39)[185:org.openhab.binding.astro:2.0.0.201701121723]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)[105:org.eclipse.smarthome.core.scheduler:0.9.0.201701091847]
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)[105:org.eclipse.smarthome.core.scheduler:0.9.0.201701091847]
12:43:00.006 [ERROR] [org.quartz.core.ErrorLogger         ] - Job (astro:sun:local.job-event-start-noon#event threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: java.lang.NullPointerException]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213)[105:org.eclipse.smarthome.core.scheduler:0.9.0.201701091847]
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)[105:org.eclipse.smarthome.core.scheduler:0.9.0.201701091847]
Caused by: java.lang.NullPointerException
        at org.openhab.binding.astro.handler.AstroThingHandler.triggerEvent(AstroThingHandler.java:304)[185:org.openhab.binding.astro:2.0.0.201701121723]
        at org.openhab.binding.astro.internal.job.EventJob.executeJob(EventJob.java:32)[185:org.openhab.binding.astro:2.0.0.201701121723]
        at org.openhab.binding.astro.internal.job.AbstractBaseJob.execute(AbstractBaseJob.java:39)[185:org.openhab.binding.astro:2.0.0.201701121723]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)[105:org.eclipse.smarthome.core.scheduler:0.9.0.201701091847]
        ... 1 more
12:44:00.001 [ERROR] [org.quartz.core.JobRunShell         ] - Job astro:sun:local.job-event-end-noon#event threw an unhandled Exception:
java.lang.NullPointerException
        at org.openhab.binding.astro.handler.AstroThingHandler.triggerEvent(AstroThingHandler.java:304)[185:org.openhab.binding.astro:2.0.0.201701121723]
        at org.openhab.binding.astro.internal.job.EventJob.executeJob(EventJob.java:32)[185:org.openhab.binding.astro:2.0.0.201701121723]
        at org.openhab.binding.astro.internal.job.AbstractBaseJob.execute(AbstractBaseJob.java:39)[185:org.openhab.binding.astro:2.0.0.201701121723]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)[105:org.eclipse.smarthome.core.scheduler:0.9.0.201701091847]
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)[105:org.eclipse.smarthome.core.scheduler:0.9.0.201701091847]
12:44:00.003 [ERROR] [org.quartz.core.ErrorLogger         ] - Job (astro:sun:local.job-event-end-noon#event threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: java.lang.NullPointerException]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213)[105:org.eclipse.smarthome.core.scheduler:0.9.0.201701091847]
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)[105:org.eclipse.smarthome.core.scheduler:0.9.0.201701091847]
Caused by: java.lang.NullPointerException
        at org.openhab.binding.astro.handler.AstroThingHandler.triggerEvent(AstroThingHandler.java:304)[185:org.openhab.binding.astro:2.0.0.201701121723]
        at org.openhab.binding.astro.internal.job.EventJob.executeJob(EventJob.java:32)[185:org.openhab.binding.astro:2.0.0.201701121723]
        at org.openhab.binding.astro.internal.job.AbstractBaseJob.execute(AbstractBaseJob.java:39)[185:org.openhab.binding.astro:2.0.0.201701121723]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)[105:org.eclipse.smarthome.core.scheduler:0.9.0.201701091847]
        ... 1 more
`

I don't use noon. This happens in intervals of around 40 min, with varying jobs. sometimes it's sun:noon, sometimes sun:rise, sun:set or moon:set. There is no clear pattern. But if it happens, it always happens to start and end.

Expected: at least catch NPE.

**Comment by kaikreuzer** [comment]
Sorry, Astro binding is not here but at https://github.com/openhab/openhab2-addons
