### ISSUE TITLE
Stacktrace when adding "but only if" condition in OH2

### ISSUE THREAD

**Issue by mkotsbak** [eclipse/smarthome#2919]
When I try to add a "but only if" "an item has a given state", I get the following stacktrace when trying to save it. I'm not sure the issue is in Smarthome or OpenHab2:

```
2017-01-30 08:21:44.297 [ERROR] [ore.common.registry.AbstractProvider] - Could not inform the listener 'org.eclipse.smarthome.automation.core.internal.RuleRegistryImpl@f3aad3' about the 'UPDATED' event!: org.eclipse.smarthome.automation.Rule cannot be cast to org.eclipse.smarthome.automation.Rule
java.lang.ClassCastException: org.eclipse.smarthome.automation.Rule cannot be cast to org.eclipse.smarthome.automation.Rule
        at org.eclipse.smarthome.automation.core.internal.RuleRegistryImpl.updated(RuleRegistryImpl.java:1)
        at org.eclipse.smarthome.core.common.registry.AbstractProvider.notifyListeners(AbstractProvider.java:57)
        at org.eclipse.smarthome.core.common.registry.AbstractProvider.notifyListenersAboutUpdatedElement(AbstractProvider.java:82)
        at org.eclipse.smarthome.core.common.registry.AbstractManagedProvider.update(AbstractManagedProvider.java:134)
        at org.eclipse.smarthome.core.common.registry.AbstractRegistry.update(AbstractRegistry.java:187)
        at org.eclipse.smarthome.automation.rest.internal.RuleResource.update(RuleResource.java:167)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)[:1.8.0_121]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)[:1.8.0_121]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[:1.8.0_121]
        at java.lang.reflect.Method.invoke(Method.java:498)[:1.8.0_121]
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)[158:org.glassfish.jersey.core.jersey-server:2.22.2]
```

**Comment by sjka** [comment]
Thanks for this report. 

> I'm not sure the issue is in Smarthome or OpenHab2

Neither do I, hard to tell without further info. Let's figure it out... 

It smells like classloader trouble. Question is: Two bundle instances, or a cached class reference.
Could you please paste the output of bundle:list here, just to exclude the first alternative?

**Comment by mkotsbak** [comment]
Where do I type "bundle:list"?

I tried in the console:

```
openhab> bundle:list
[org.apache.karaf.shell.support.ShellUtil] : Unknown command entered
org.apache.felix.gogo.runtime.CommandNotFoundException: Command not found: bundle:list
```

Got the shell from running /usr/share/openhab2/runtime/bin/shell

**Comment by mkotsbak** [comment]
Found it here: http://docs.openhab.org/administration/console.html

There is a lot there. What should I look for. Regarding rule engine I find:
```
127 | Active   |  80 | 0.9.0.201701192225    | Eclipse SmartHome Rule Model
128 | Active   |  80 | 0.9.0.201701192225    | Eclipse SmartHome Rule Runtime
```

**Comment by mkotsbak** [comment]
Upgraded and restarted Openhab2 now and seems like I can't reproduce it anymore.
