### ISSUE TITLE
Sonos populating opml configuration

### ISSUE THREAD

**Issue by rgerrans** [eclipse/smarthome#2998]
I've had the issue a couple of times now where the Sonos binding is populating the OPML configuration field with a url and then generating the following error.  I've deleted the OPML configuration parameter a few days ago.  Uninstalled the binding, deleted the .cfg file and reinstalled and it was fine.  Just uploaded to the latest snapshot and it populated it again.

```
2017-02-10 17:21:46.324 [ERROR] [.io.transport.upnp.UpnpIOServiceImpl] - Participant threw an exception onValueReceived
java.lang.IllegalArgumentException: Malformed escape pair at index 75: http://opml.radiotime.com/Describe.ashx?c=nowplaying&partnerId=IAeIhU42&id=%id&serial=00:0E:58:AE:CB:56
	at java.net.URI.create(URI.java:852)[:1.8.0_121]
	at org.eclipse.jetty.client.HttpClient.newRequest(HttpClient.java:404)[69:org.eclipse.jetty.client:9.2.19.v20160908]
	at org.eclipse.smarthome.io.net.http.HttpUtil.executeUrl(HttpUtil.java:185)[113:org.eclipse.smarthome.io.net:0.9.0.201702100936]
	at org.eclipse.smarthome.io.net.http.HttpUtil.executeUrl(HttpUtil.java:130)[113:org.eclipse.smarthome.io.net:0.9.0.201702100936]
	at org.eclipse.smarthome.io.net.http.HttpUtil.executeUrl(HttpUtil.java:86)[113:org.eclipse.smarthome.io.net:0.9.0.201702100936]
	at org.eclipse.smarthome.io.net.http.HttpUtil.executeUrl(HttpUtil.java:65)[113:org.eclipse.smarthome.io.net:0.9.0.201702100936]
	at org.eclipse.smarthome.binding.sonos.handler.ZonePlayerHandler.updateMediaInformation(ZonePlayerHandler.java:929)[188:org.eclipse.smarthome.binding.sonos:0.9.0.201702100936]
	at org.eclipse.smarthome.binding.sonos.handler.ZonePlayerHandler.onValueReceived(ZonePlayerHandler.java:388)[188:org.eclipse.smarthome.binding.sonos:0.9.0.201702100936]
	at org.eclipse.smarthome.io.transport.upnp.UpnpIOServiceImpl$UpnpSubscriptionCallback.eventReceived(UpnpIOServiceImpl.java:144)[189:org.eclipse.smarthome.io.transport.upnp:0.9.0.201702100936]
	at org.jupnp.controlpoint.SubscriptionCallback$2.eventReceived(SubscriptionCallback.java:222)[162:org.jupnp:2.2.0]
	at org.jupnp.model.gena.RemoteGENASubscription.receive(RemoteGENASubscription.java:114)[162:org.jupnp:2.2.0]
	at org.jupnp.protocol.sync.ReceivingEvent$2.run(ReceivingEvent.java:130)[162:org.jupnp:2.2.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_121]
Caused by: java.net.URISyntaxException: Malformed escape pair at index 75: http://opml.radiotime.com/Describe.ashx?c=nowplaying&partnerId=IAeIhU42&id=%id&serial=00:0E:58:AE:CB:56
	at java.net.URI$Parser.fail(URI.java:2848)[:1.8.0_121]
	at java.net.URI$Parser.scanEscape(URI.java:2978)[:1.8.0_121]
	at java.net.URI$Parser.scan(URI.java:3001)[:1.8.0_121]
	at java.net.URI$Parser.checkChars(URI.java:3019)[:1.8.0_121]
	at java.net.URI$Parser.parseHierarchical(URI.java:3111)[:1.8.0_121]
	at java.net.URI$Parser.parse(URI.java:3053)[:1.8.0_121]
	at java.net.URI.<init>(URI.java:588)[:1.8.0_121]
	at java.net.URI.create(URI.java:850)[:1.8.0_121]
	... 14 more
```

**Comment by kaikreuzer** [comment]
@kgoderis Looks as if the `%id` placeholder has not been correctly replaced. Looking at the code, I cannot immediately see any reason why that could happen. Do you have any idea?

**Comment by lolodomo** [comment]
@rgerrans : to reproduce your problem, please tell us what was the tune-in radio station you were listening when it happened.

**Comment by rgerrans** [comment]
I don't use TuneIn and had never configured my system to use it.  The OPML url go injected into the system when I did an update.

**Comment by lolodomo** [comment]
Interesting, this URL should be used only when you listen a tunein station.
Please restore the binding. OPML URL setting and then tell us what music service you are listening when you trigger the exception ?
Apparently this service is using the same kind of URI as tunein.
A simple fix would be to avoid requesting the OPML URL when we can't extract a station ID from the URI.

**Comment by rgerrans** [comment]
Palm to forehead.... Just dawned on me that my wife listens to a local station.  I bet that is where it is coming from.  I'll look when I get home to verify.

Thanks

**Comment by rgerrans** [comment]
@lolodomo It looks like the stations she's been listening to are coming off iHeart radio.  But if I run one of those stations, and stop/start openhab it isn't populating the OPML URL setting.    When the next update gets pushed out I'll see if that triggers the writing to the cfg file.

**Comment by lolodomo** [comment]
OK, let us know when you can test again.
Maybe we are not making a difference between TuneIn radio and iHeart radio.
By the way, if that is really the problem, I see how it can be fixed easily.

**Comment by rgerrans** [comment]
It won't be until the next build for the snapshot runs since that seems to correspond to the OPML config getting repopulated.

**Comment by lolodomo** [comment]
If you want to test without waiting for an update, here is the value of the binding setting you can set with Paper UI: http://opml.radiotime.com/Describe.ashx?c=nowplaying&partnerId=IAeIhU42&id=%id&serial=%serial
When you encounter the problem again, please tell us what value you get in channel "currenttransporturi".

**Comment by rgerrans** [comment]
@lolodomo Sorry, got tied up.  Here is teh errors I got when I put in the test string:
```
2017-02-22 20:48:45.581 [ERROR] [.io.transport.upnp.UpnpIOServiceImpl] - Participant threw an exception onValueReceived
java.lang.IllegalArgumentException: Malformed escape pair at index 75: http://opml.radiotime.com/Describe.ashx?c=nowplaying&partnerId=IAeIhU42&id=%id&serial=00:0E:58:AE:CB:56
	at java.net.URI.create(URI.java:852)[:1.8.0_121]
	at org.eclipse.jetty.client.HttpClient.newRequest(HttpClient.java:404)[69:org.eclipse.jetty.client:9.2.19.v20160908]
	at org.eclipse.smarthome.io.net.http.HttpUtil.executeUrl(HttpUtil.java:185)[113:org.eclipse.smarthome.io.net:0.9.0.201702100936]
	at org.eclipse.smarthome.io.net.http.HttpUtil.executeUrl(HttpUtil.java:130)[113:org.eclipse.smarthome.io.net:0.9.0.201702100936]
	at org.eclipse.smarthome.io.net.http.HttpUtil.executeUrl(HttpUtil.java:86)[113:org.eclipse.smarthome.io.net:0.9.0.201702100936]
	at org.eclipse.smarthome.io.net.http.HttpUtil.executeUrl(HttpUtil.java:65)[113:org.eclipse.smarthome.io.net:0.9.0.201702100936]
	at org.eclipse.smarthome.binding.sonos.handler.ZonePlayerHandler.updateMediaInformation(ZonePlayerHandler.java:929)[188:org.eclipse.smarthome.binding.sonos:0.9.0.201702100936]
	at org.eclipse.smarthome.binding.sonos.handler.ZonePlayerHandler.onValueReceived(ZonePlayerHandler.java:388)[188:org.eclipse.smarthome.binding.sonos:0.9.0.201702100936]
	at org.eclipse.smarthome.io.transport.upnp.UpnpIOServiceImpl$UpnpSubscriptionCallback.eventReceived(UpnpIOServiceImpl.java:144)[189:org.eclipse.smarthome.io.transport.upnp:0.9.0.201702100936]
	at org.jupnp.controlpoint.SubscriptionCallback$2.eventReceived(SubscriptionCallback.java:222)[162:org.jupnp:2.2.0]
	at org.jupnp.model.gena.RemoteGENASubscription.receive(RemoteGENASubscription.java:114)[162:org.jupnp:2.2.0]
	at org.jupnp.protocol.sync.ReceivingEvent$2.run(ReceivingEvent.java:130)[162:org.jupnp:2.2.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_121]
Caused by: java.net.URISyntaxException: Malformed escape pair at index 75: http://opml.radiotime.com/Describe.ashx?c=nowplaying&partnerId=IAeIhU42&id=%id&serial=00:0E:58:AE:CB:56
	at java.net.URI$Parser.fail(URI.java:2848)[:1.8.0_121]
	at java.net.URI$Parser.scanEscape(URI.java:2978)[:1.8.0_121]
	at java.net.URI$Parser.scan(URI.java:3001)[:1.8.0_121]
	at java.net.URI$Parser.checkChars(URI.java:3019)[:1.8.0_121]
	at java.net.URI$Parser.parseHierarchical(URI.java:3111)[:1.8.0_121]
	at java.net.URI$Parser.parse(URI.java:3053)[:1.8.0_121]
	at java.net.URI.<init>(URI.java:588)[:1.8.0_121]
	at java.net.URI.create(URI.java:850)[:1.8.0_121]
	... 14 more
2017-02-22 20:48:45.665 [ERROR] [.io.transport.upnp.UpnpIOServiceImpl] - Participant threw an exception onValueReceived
java.lang.IllegalArgumentException: Malformed escape pair at index 75: http://opml.radiotime.com/Describe.ashx?c=nowplaying&partnerId=IAeIhU42&id=%id&serial=00:0E:58:AE:CB:56
	at java.net.URI.create(URI.java:852)[:1.8.0_121]
	at org.eclipse.jetty.client.HttpClient.newRequest(HttpClient.java:404)[69:org.eclipse.jetty.client:9.2.19.v20160908]
	at org.eclipse.smarthome.io.net.http.HttpUtil.executeUrl(HttpUtil.java:185)[113:org.eclipse.smarthome.io.net:0.9.0.201702100936]
	at org.eclipse.smarthome.io.net.http.HttpUtil.executeUrl(HttpUtil.java:130)[113:org.eclipse.smarthome.io.net:0.9.0.201702100936]
	at org.eclipse.smarthome.io.net.http.HttpUtil.executeUrl(HttpUtil.java:86)[113:org.eclipse.smarthome.io.net:0.9.0.201702100936]
	at org.eclipse.smarthome.io.net.http.HttpUtil.executeUrl(HttpUtil.java:65)[113:org.eclipse.smarthome.io.net:0.9.0.201702100936]
	at org.eclipse.smarthome.binding.sonos.handler.ZonePlayerHandler.updateMediaInformation(ZonePlayerHandler.java:929)[188:org.eclipse.smarthome.binding.sonos:0.9.0.201702100936]
	at org.eclipse.smarthome.binding.sonos.handler.ZonePlayerHandler.onValueReceived(ZonePlayerHandler.java:428)[188:org.eclipse.smarthome.binding.sonos:0.9.0.201702100936]
	at org.eclipse.smarthome.io.transport.upnp.UpnpIOServiceImpl$UpnpSubscriptionCallback.eventReceived(UpnpIOServiceImpl.java:144)[189:org.eclipse.smarthome.io.transport.upnp:0.9.0.201702100936]
	at org.jupnp.controlpoint.SubscriptionCallback$2.eventReceived(SubscriptionCallback.java:222)[162:org.jupnp:2.2.0]
	at org.jupnp.model.gena.RemoteGENASubscription.receive(RemoteGENASubscription.java:114)[162:org.jupnp:2.2.0]
	at org.jupnp.protocol.sync.ReceivingEvent$2.run(ReceivingEvent.java:130)[162:org.jupnp:2.2.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_121]
Caused by: java.net.URISyntaxException: Malformed escape pair at index 75: http://opml.radiotime.com/Describe.ashx?c=nowplaying&partnerId=IAeIhU42&id=%id&serial=00:0E:58:AE:CB:56
	at java.net.URI$Parser.fail(URI.java:2848)[:1.8.0_121]
	at java.net.URI$Parser.scanEscape(URI.java:2978)[:1.8.0_121]
	at java.net.URI$Parser.scan(URI.java:3001)[:1.8.0_121]
	at java.net.URI$Parser.checkChars(URI.java:3019)[:1.8.0_121]
	at java.net.URI$Parser.parseHierarchical(URI.java:3111)[:1.8.0_121]
	at java.net.URI$Parser.parse(URI.java:3053)[:1.8.0_121]
	at java.net.URI.<init>(URI.java:588)[:1.8.0_121]
	at java.net.URI.create(URI.java:850)[:1.8.0_121]
	... 14 more

```

I'm going to need a little guidance on how to pull the currenttransporturi channel value since it's not exposed in the PaperUI

**Comment by lolodomo** [comment]
The fix is not yet available in the snapshots.

**Comment by rgerrans** [comment]
That makes sense.  I was afraid it was closed because I hadn't responded back.  Glad you guys figured it out.

**Comment by Snicka** [comment]
Did this ever get merged into the mainline? I still see this issue with 0.9.0.201704261358 and clearing the OPML uri is the only fix. iHeartRadio is used on the system occasionally which causes all Text to Speech to stop working.

**Comment by sjka** [comment]
No, there never was a PR to fix this. So we better re-open this.

**Comment by kaikreuzer** [comment]
@sjka & @lolodomo: What was https://github.com/eclipse/smarthome/pull/3037 about then?

**Comment by sjka** [comment]
ouch, good fooled by the missing auto-linking... So indeed, it _should_ be fixed. 
Nevertheless, I can't explain why @Snicka still sees this. @lolodomo do you?

**Comment by Snicka** [comment]
Not sure why I'm seeing this but I updated my OH2 snapshot yesterday and I still have to clear the OPML string to get TTS to work. My current version is:
191 | Active   |  80 | 0.9.0.201706091022     | Sonos Binding

**Comment by kaikreuzer** [comment]
Should be fixed by https://github.com/eclipse/smarthome/pull/3037.
If anyone still sees this issue, please re-open or file a new report.
