### ISSUE TITLE
[Reopen Distro #306] - SafeMethodCaller time-outs

### ISSUE THREAD

**Issue by kgoderis** [eclipse/smarthome#3032]
@kaikreuzer I refer to your post in the above (closed) Issue #306 (https://github.com/openhab/openhab-distro/issues/306#issuecomment-280598506). 

I notice a lot of SMC Time-outs in the core when I start up my operational environment (It runs on a Mac mini (so decent hardware), but I have about 15-ish binding including a few heavy ones running)

But I also observed another issue with the ThreadPool scheduler (ESH-ThingHandler pool): when all the threads of the pool are in a BLOCKED state (I came across this due to a buggy binding I am testing), I have the impression (unable to pinpoint however) that somehow (long-running) ESH-ThingHandler threads are silently terminated after a while. I can not remember that we have this in our implementation of the scheduler, so I am quite puzzled as to what is leading to these terminations. 

```
2017-02-17 13:19:40.532 [DEBUG] [arthome.core.common.SafeMethodCaller] - Timeout of 5000ms exceeded, thread safeCall-1 (112) in state RUNNABLE is at org.eclipse.smarthome.core.internal.items.ItemRegistryImpl.get(ItemRegistryImpl.java:86).
2017-02-17 13:19:40.805 [DEBUG] [arthome.core.common.SafeMethodCaller] - Timeout of 5000ms exceeded, thread safeCall-6 (203) in state RUNNABLE is at org.eclipse.smarthome.core.internal.items.ItemRegistryImpl.get(ItemRegistryImpl.java:86).
2017-02-17 13:19:45.878 [DEBUG] [arthome.core.common.SafeMethodCaller] - Timeout of 5000ms exceeded, thread safeCall-5 (187) in state RUNNABLE is at org.eclipse.smarthome.core.internal.items.ItemRegistryImpl.get(ItemRegistryImpl.java:86).
2017-02-17 13:19:46.009 [DEBUG] [arthome.core.common.SafeMethodCaller] - Timeout of 5000ms exceeded, thread safeCall-8 (408) in state RUNNABLE is at org.eclipse.smarthome.core.internal.items.ItemRegistryImpl.get(ItemRegistryImpl.java:86).
2017-02-17 13:19:51.079 [DEBUG] [arthome.core.common.SafeMethodCaller] - Timeout of 5000ms exceeded, thread safeCall-3 (132) in state RUNNABLE is at org.eclipse.smarthome.core.internal.items.ItemRegistryImpl.get(ItemRegistryImpl.java:85).
2017-02-17 13:19:51.350 [DEBUG] [arthome.core.common.SafeMethodCaller] - Timeout of 5000ms exceeded, thread safeCall-4 (183) in state BLOCKED is at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.updateState(BaseThingHandler.java:264).
2017-02-17 13:19:56.416 [DEBUG] [arthome.core.common.SafeMethodCaller] - Timeout of 5000ms exceeded, thread safeCall-8 (408) in state RUNNABLE is at org.eclipse.smarthome.core.internal.items.ItemRegistryImpl.get(ItemRegistryImpl.java:86).
2017-02-17 13:19:56.549 [DEBUG] [arthome.core.common.SafeMethodCaller] - Timeout of 5000ms exceeded, thread safeCall-6 (203) in state RUNNABLE is at org.eclipse.smarthome.core.internal.items.ItemRegistryImpl.get(ItemRegistryImpl.java:86).
2017-02-17 13:20:58.894 [DEBUG] [arthome.core.common.SafeMethodCaller] - Timeout of 5000ms exceeded, thread safeCall-8 (408) in state BLOCKED is at org.eclipse.smarthome.model.rule.runtime.internal.engine.RuleEngineImpl.executeRules(RuleEngineImpl.java:329).
2017-02-17 13:20:58.894 [DEBUG] [arthome.core.common.SafeMethodCaller] - Timeout of 5000ms exceeded, thread safeCall-3 (132) in state BLOCKED is at org.eclipse.smarthome.model.rule.runtime.internal.engine.RuleEngineImpl.executeRules(RuleEngineImpl.java:329).
2017-02-17 13:21:04.195 [DEBUG] [arthome.core.common.SafeMethodCaller] - Timeout of 5000ms exceeded, thread safeCall-4 (183) in state BLOCKED is at org.eclipse.smarthome.model.rule.runtime.internal.engine.RuleEngineImpl.executeRules(RuleEngineImpl.java:329).
2017-02-17 13:21:04.195 [DEBUG] [arthome.core.common.SafeMethodCaller] - Timeout of 5000ms exceeded, thread safeCall-5 (187) in state BLOCKED is at org.eclipse.smarthome.model.rule.runtime.internal.engine.RuleEngineImpl.executeRules(RuleEngineImpl.java:329).
2017-02-17 13:21:09.441 [DEBUG] [arthome.core.common.SafeMethodCaller] - Timeout of 5000ms exceeded, thread safeCall-1 (112) in state BLOCKED is at org.eclipse.smarthome.model.rule.runtime.internal.engine.RuleEngineImpl.executeRules(RuleEngineImpl.java:329).
2017-02-17 13:21:09.454 [DEBUG] [arthome.core.common.SafeMethodCaller] - Timeout of 5000ms exceeded, thread safeCall-9 (412) in state BLOCKED is at org.eclipse.smarthome.model.rule.runtime.internal.engine.RuleEngineImpl.executeRules(RuleEngineImpl.java:329).
```

**Comment by kgoderis** [comment]
> But I also observed another issue with the ThreadPool scheduler (ESH-ThingHandler pool): when all the threads of the pool are in a BLOCKED state (I came across this due to a buggy binding I am testing), I have the impression (unable to pinpoint however) that somehow (long-running) ESH-ThingHandler threads are silently terminated after a while. I can not remember that we have this in our implementation of the scheduler, so I am quite puzzled as to what is leading to these terminations.

This was a silent exit due to a OutOfMemory on the JVM Heap.

**Comment by kaikreuzer** [comment]
> This was a silent exit due to a OutOfMemory on the JVM Heap.

Ok, this explains it, because I would not even know of a way to kill any running thread...
I hope the OutOfMemory was also due to some buggy binding and not a problem in the core?

Your blocking threads look really weird. The ones about the ItemRegistryImpl are within the get() method, which retrieves an Item instance from its name - this is unlikely to be blocking, but maybe your setup is so huge that the whole processing takes long and this method simply is called many times so that the likelyhood that it is caught by the logging is high? Probably some profiling might help on that.

Likewise the logs about the RuleEngineImpl: This only prepares the scripts before scheduling threads to execute them. That itself should not take long.

Does this all only appear once at startup or regularly during runtime?

**Comment by kaikreuzer** [comment]
@kgoderis Can this issue be closed or do you still experience such issues?
