### ISSUE TITLE
Basic UI: Hangs when going back to Home screen

### ISSUE THREAD

**Issue by UdoK** [eclipse/smarthome#3041]
Basic UI hangs occasionally when going back from a screen to the home screen.
Here what openhab.log shows:
2017-02-19 11:31:05.991 [WARN ] [basic.internal.servlet.WebAppServlet] - Basic UI requested a non-existing event subscription id (084fdd27-f67d-4d9a-9881-e31b4676c544)
2017-02-19 11:31:07.954 [WARN ] [eclipse.jetty.servlet.ServletHandler] - /basicui/app
java.lang.IllegalArgumentException: Subscription 084fdd27-f67d-4d9a-9881-e31b4676c544 does not exist!
	at org.eclipse.smarthome.io.rest.sitemap.SitemapSubscriptionService.setPageId(SitemapSubscriptionService.java:172)[117:org.eclipse.smarthome.io.rest.sitemap:0.9.0.b4]
	at org.eclipse.smarthome.ui.basic.internal.servlet.WebAppServlet.service(WebAppServlet.java:147)[197:org.eclipse.smarthome.ui.basic:0.9.0.b4]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)[81:org.eclipse.jetty.servlet:9.2.19.v20160908]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)[81:org.eclipse.jetty.servlet:9.2.19.v20160908]
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:71)[172:org.ops4j.pax.web.pax-web-jetty:4.3.0]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)[80:org.eclipse.jetty.server:9.2.19.v20160908]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)[79:org.eclipse.jetty.security:9.2.19.v20160908]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)[80:org.eclipse.jetty.server:9.2.19.v20160908]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)[80:org.eclipse.jetty.server:9.2.19.v20160908]
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:287)[172:org.ops4j.pax.web.pax-web-jetty:4.3.0]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)[81:org.eclipse.jetty.servlet:9.2.19.v20160908]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)[80:org.eclipse.jetty.server:9.2.19.v20160908]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)[80:org.eclipse.jetty.server:9.2.19.v20160908]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)[80:org.eclipse.jetty.server:9.2.19.v20160908]
	at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:80)[172:org.ops4j.pax.web.pax-web-jetty:4.3.0]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)[80:org.eclipse.jetty.server:9.2.19.v20160908]
	at org.eclipse.jetty.server.Server.handle(Server.java:499)[80:org.eclipse.jetty.server:9.2.19.v20160908]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)[80:org.eclipse.jetty.server:9.2.19.v20160908]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)[80:org.eclipse.jetty.server:9.2.19.v20160908]
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)[72:org.eclipse.jetty.io:9.2.19.v20160908]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)[83:org.eclipse.jetty.util:9.2.19.v20160908]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)[83:org.eclipse.jetty.util:9.2.19.v20160908]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_121]

**Comment by lolodomo** [comment]
@resetnow : with all my short sessions using Basic UI from a server started by Eclipse, I have encountered several hangs of Basic UI when changing page. So I think there is probably a problem.

**Comment by resetnow** [comment]
By hang you mean it's no longer receiving updates or it's impossible to navigate to other pages?

**Comment by lolodomo** [comment]
I mean the requested page is not displayed immediately. You have to reload or wait for a long time. To be clear, it happens when changing page and I think in particular when going back to the parent page.
I will try to identify more precisely when it happens.

**Comment by triller-telekom** [comment]
@lolodomo Any news on this one? At least I haven't experienced such a problem that the site hangs while changing...

**Comment by lolodomo** [comment]
My current hypothesis is that Basic UI is hanging while there is a rule running. Would it be possible that few rules are bloacking Basic UI until run finished ?

**Comment by lolodomo** [comment]
This would require more investigation but it happens sometimes when using Basic UI through Eclipse with the demo setup.
