### ISSUE TITLE
Test failure(s): Wemo tests

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#3070]
After switching to Java 8 and also updating the Tycho plugin etc. it seems that the Wemo tests failed on Hudson.

It seems that the `Failed` is first caused by `org.eclipse.smarthome.binding.wemo.handler.test.WemoHandlerOSGiTest.assert that thing handles OnOff command correctly`

```text
Error Message

Expected: is <0>
     but: was <2>
```

```text
Stacktrace

java.lang.AssertionError: 
Expected: is <0>
     but: was <2>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:865)
	at org.junit.Assert.assertThat(Assert.java:832)
	at org.junit.Assert$assertThat.callStatic(Unknown Source)
	at org.eclipse.smarthome.binding.wemo.handler.test.WemoHandlerOSGiTest$_removeThing_closure12.doCall(WemoHandlerOSGiTest.groovy:176)
	at org.eclipse.smarthome.binding.wemo.handler.test.WemoHandlerOSGiTest$_removeThing_closure12.doCall(WemoHandlerOSGiTest.groovy)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:278)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at org.eclipse.smarthome.test.OSGiTest.waitForAssert(OSGiTest.groovy:199)
	at org.eclipse.smarthome.test.OSGiTest.waitForAssert(OSGiTest.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:207)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:141)
	at org.eclipse.smarthome.binding.wemo.handler.test.WemoHandlerOSGiTest.removeThing(WemoHandlerOSGiTest.groovy:175)
	at org.eclipse.smarthome.binding.wemo.handler.test.WemoHandlerOSGiTest.tearDown(WemoHandlerOSGiTest.groovy:62)
```

The tests does not fail on my machine using the Eclipse IDE and the tests does not fail using Maven.

The assert below (line 175 in the stack trace above) seems to raise the failure.

```
        itemRegistry.remove(DEFAULT_TEST_ITEM_NAME)
        waitForAssert {
            assertThat itemRegistry.getAll().items.size(), is(0)
        }
```

I am currently running a test on Hudson that shows the item names that are part of the item registry...
Perhaps this will give us more insights.

**Comment by maggu2810** [comment]
@kaikreuzer As you complained about that errors on your machine, too:
Have you ever tried to clean out your working copy before?
The "test" job on Hudson does not fail on the Wemo test.

**Comment by maggu2810** [comment]
Hudson was able to build the whole test job, so it looks like an unclean setup.
WDYT?

I could try to change the nightly build configuration to do a "git clean -x -d -f" or something similar in front of the build.
Should I give it a try?

**Comment by kaikreuzer** [comment]
Let me simply delete the workspace for a test, which will automatically lead to a fresh clean checkout.

**Comment by maggu2810** [comment]
The only code change I have done in the branch I tested to build on Hudson are added prints to get the content of the Item registry on the assert (and the call to add the item).
See: https://github.com/eclipse/smarthome/compare/master...maggu2810:wemo-test?expand=1

**Comment by kaikreuzer** [comment]
> Let me simply delete the workspace for a test, which will automatically lead to a fresh clean checkout.

Didn't help...

**Comment by svilenvul** [comment]
I have tried to reproduce the failure on my machine without a success. Sorry for wasting your time with this one.. , I don't believe it is caused from the @maggu2810's changes.

Unfortunately I don't have an idea now what causes the issue.

I can invest some time to rewrite part of the tests, include more logging and try to make them more stable.

Feel free to ignore the tests, if the failures are continuing until I create a PR for them.

**Comment by maggu2810** [comment]
@kaikreuzer Can you give https://github.com/maggu2810/smarthome/tree/wemo-test a try and send me the output of the Wemo test (if it fails)?

**Comment by maggu2810** [comment]
> Sorry for wasting your time with this one..

@svilenvul All fine

I added some changes to get the items in registry (the result says there are two but there should be zero).

Here the result:

```
Running org.eclipse.smarthome.binding.wemo.handler.test.WemoHandlerOSGiTest
add item to registry: testItem
item in registry: name=wemo_insight_Test_1_0_22124_state, type=Switch, state=NULL
item in registry: name=wemo_insight_Test_1_0_22124_currentPower, type=Number, state=NULL
item in registry: name=wemo_insight_Test_1_0_22124_state, type=Switch, state=NULL
item in registry: name=wemo_insight_Test_1_0_22124_currentPower, type=Number, state=NULL
item in registry: name=wemo_insight_Test_1_0_22124_state, type=Switch, state=NULL
item in registry: name=wemo_insight_Test_1_0_22124_currentPower, type=Number, state=NULL
Tests run: 5, Failures: 3, Errors: 2, Skipped: 0, Time elapsed: 30.625 sec <<< FAILURE! - in org.eclipse.smarthome.binding.wemo.handler.test.WemoHandlerOSGiTest
assert that thing handles OnOff command correctly(org.eclipse.smarthome.binding.wemo.handler.test.WemoHandlerOSGiTest)  Time elapsed: 10.445 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: is <0>
     but: was <2>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:865)
	at org.junit.Assert.assertThat(Assert.java:832)
	at org.junit.Assert$assertThat.callStatic(Unknown Source)
	at org.eclipse.smarthome.binding.wemo.handler.test.WemoHandlerOSGiTest$_removeThing_closure12.doCall(WemoHandlerOSGiTest.groovy:177)
	at org.eclipse.smarthome.binding.wemo.handler.test.WemoHandlerOSGiTest$_removeThing_closure12.doCall(WemoHandlerOSGiTest.groovy)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:278)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at org.eclipse.smarthome.test.OSGiTest.waitForAssert(OSGiTest.groovy:218)
	at org.eclipse.smarthome.test.OSGiTest.waitForAssert(OSGiTest.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:207)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:145)
	at org.eclipse.smarthome.binding.wemo.handler.test.WemoHandlerOSGiTest.removeThing(WemoHandlerOSGiTest.groovy:176)
	at org.eclipse.smarthome.binding.wemo.handler.test.WemoHandlerOSGiTest.tearDown(WemoHandlerOSGiTest.groovy:63)
```

**Comment by maggu2810** [comment]
@svilenvul Where are this items coming from:

```
item in registry: name=wemo_insight_Test_1_0_22124_state, type=Switch, state=NULL
item in registry: name=wemo_insight_Test_1_0_22124_currentPower, type=Number, state=NULL
```

**Comment by maggu2810** [comment]
Is the default for the "simple mode" true and the items are created because you create such a thing in your test.
As you already create an item yourself, perhaps you should disable the simple mode for this test.

**Comment by kaikreuzer** [comment]
@maggu2810 Many thanks for looking into this and coming up with a fix 👍

**Comment by svilenvul** [comment]
@maggu2810 many thanks too for identifying the problem and solving it.
