### ISSUE TITLE
Test failure(s): NTP: communication error

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#3073]
Sometimes I get this error on compilation:

```text
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.eclipse.smarthome.binding.ntp.test.NtpOSGiTest
Tests run: 16, Failures: 1, Errors: 0, Skipped: 2, Time elapsed: 22.053 sec <<< FAILURE! - in org.eclipse.smarthome.binding.ntp.test.NtpOSGiTest
the dateTime channel is updated with the right time zone(org.eclipse.smarthome.binding.ntp.test.NtpOSGiTest) skipped
time is refreshed when string channel is linked(org.eclipse.smarthome.binding.ntp.test.NtpOSGiTest)  Time elapsed: 0.261 sec
if no time zone is set in the configuration, the dateTime channel is updated with the default one(org.eclipse.smarthome.binding.ntp.test.NtpOSGiTest)  Time elapsed: 0.141 sec
time is refreshed when dateTime channel is linked(org.eclipse.smarthome.binding.ntp.test.NtpOSGiTest)  Time elapsed: 0.045 sec
the status of a thing with string channel is updated with communication error, when unknown host is set in the configuraion(org.eclipse.smarthome.binding.ntp.test.NtpOSGiTest)  Time elapsed: 10.169 sec  <<< FAILURE!
java.lang.AssertionError: The thing status was not communication error
Expected: is <COMMUNICATION_ERROR>
     but: was <NONE>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:865)
	at org.junit.Assert$assertThat$0.callStatic(Unknown Source)
	at org.eclipse.smarthome.binding.ntp.test.NtpOSGiTest$_assertCommunicationError_closure8.doCall(NtpOSGiTest.groovy:516)
	at org.eclipse.smarthome.binding.ntp.test.NtpOSGiTest$_assertCommunicationError_closure8.doCall(NtpOSGiTest.groovy)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:278)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at org.eclipse.smarthome.test.OSGiTest.waitForAssert(OSGiTest.groovy:218)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:207)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:61)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:153)
	at org.eclipse.smarthome.test.OSGiTest.waitForAssert(OSGiTest.groovy:189)
	at org.eclipse.smarthome.test.OSGiTest.waitForAssert(OSGiTest.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:207)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:141)
	at org.eclipse.smarthome.binding.ntp.test.NtpOSGiTest.assertCommunicationError(NtpOSGiTest.groovy:513)

the string channel is updated with the right formatting(org.eclipse.smarthome.binding.ntp.test.NtpOSGiTest)  Time elapsed: 0.121 sec
if the property for formatting in the configuration of the string channel is null, the default formatting is used(org.eclipse.smarthome.binding.ntp.test.NtpOSGiTest)  Time elapsed: 0.116 sec
if no property for formatting is set in the configuration of the string channel, the default formatting is used(org.eclipse.smarthome.binding.ntp.test.NtpOSGiTest)  Time elapsed: 0.112 sec
if the property for formatting in the configuration of the string channel is empty string, the default formatting is used(org.eclipse.smarthome.binding.ntp.test.NtpOSGiTest)  Time elapsed: 0.114 sec
the calendar of the dateTime channel is updated with the right time zone(org.eclipse.smarthome.binding.ntp.test.NtpOSGiTest) skipped
the string channel is updated with the right time zone(org.eclipse.smarthome.binding.ntp.test.NtpOSGiTest)  Time elapsed: 0.125 sec
if no time zone is set in the configuration, the string channel is updated with the default one(org.eclipse.smarthome.binding.ntp.test.NtpOSGiTest)  Time elapsed: 0.113 sec
the string channel is updated on handleCommand(org.eclipse.smarthome.binding.ntp.test.NtpOSGiTest)  Time elapsed: 0.105 sec
the dateTime channel is updated on handleCommand(org.eclipse.smarthome.binding.ntp.test.NtpOSGiTest)  Time elapsed: 0.091 sec
if no time zone is set in the configuration, the calendar of the dateTime channel is updated with the default one(org.eclipse.smarthome.binding.ntp.test.NtpOSGiTest)  Time elapsed: 0.217 sec
the status of a thing with dateTime channel is updated with communication error, when unknown host is set in the configuraion(org.eclipse.smarthome.binding.ntp.test.NtpOSGiTest)  Time elapsed: 10.024 sec

Results :

Failed tests: 
  NtpOSGiTest.the status of a thing with string channel is updated with communication error, when unknown host is set in the configuraion:344->assertCommunicationError:513->OSGiTest.waitForAssert:-1->OSGiTest.waitForAssert:189->OSGiTest.waitForAssert:218 The thing status was not communication error
Expected: is <COMMUNICATION_ERROR>
     but: was <NONE>

Tests run: 16, Failures: 1, Errors: 0, Skipped: 2
```

**Comment by petarnv** [comment]
@maggu2810, I intend to refactor these tests soon, because we can now use Java 8 date time API, which is much more convenient than the Java 7 one. When I refactor them, I will take into consideration this failing test. You can help me, if you tell me on what operating system are you running the tests. In the meantime, if the tests are failing a lot, we can ignore them.

**Comment by maggu2810** [comment]
With respect to the Java 8 migration and the usage of closures, I give it a try and converted the NTP test to a plain Java test (instead a Groovy one): https://github.com/eclipse/smarthome/pull/3078
This showed me e.g. usage of private API in that test...
What do you think about using pure Java?

**Comment by petarnv** [comment]
I'm fine with NTP tests being pure Java.

**Comment by maggu2810** [comment]
The test has been changed from Groovy to pure Java and some stuff has been changed.
Will reopen the issue if the problem raises again.
