### ISSUE TITLE
Audio tests are failing

### ISSUE THREAD

**Issue by aisebastian** [eclipse/smarthome#3239]
Compiling from current master, the following tests fail:
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.eclipse.smarthome.core.audio.test.AudioManagerTest
Tests run: 23, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 30.853 sec <<< FAILURE! - in org.eclipse.smarthome.core.audio.test.AudioManagerTest
audio manager plays stream from mp3 audio files(org.eclipse.smarthome.core.audio.test.AudioManagerTest)  Time elapsed: 0.134 sec
audio manager plays mp3 audio files(org.eclipse.smarthome.core.audio.test.AudioManagerTest)  Time elapsed: 0.004 sec
sink is registered(org.eclipse.smarthome.core.audio.test.AudioManagerTest)  Time elapsed: 0.009 sec
audio manager sets the volume of not registered sink to zero(org.eclipse.smarthome.core.audio.test.AudioManagerTest)  Time elapsed: 0.013 sec
the volume of a null sink is zero(org.eclipse.smarthome.core.audio.test.AudioManagerTest)  Time elapsed: 0 sec
source is added in parameter options(org.eclipse.smarthome.core.audio.test.AudioManagerTest)  Time elapsed: 0.033 sec
setVolume method handles IOException(org.eclipse.smarthome.core.audio.test.AudioManagerTest)  Time elapsed: 0.005 sec
audio manager does not process streams if there is no registered sink(org.eclipse.smarthome.core.audio.test.AudioManagerTest)  Time elapsed: 10.137 sec  <<< FAILURE!
java.lang.AssertionError: Could not find AudioServlet
Expected: is not null
     but: was null
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:865)
	at org.junit.Assert$assertThat$0.callStatic(Unknown Source)
	at org.eclipse.smarthome.core.audio.test.AudioOSGiTest$_initializeAudioServlet_closure4.doCall(AudioOSGiTest.groovy:136)
	at org.eclipse.smarthome.core.audio.test.AudioOSGiTest$_initializeAudioServlet_closure4.doCall(AudioOSGiTest.groovy)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:278)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at org.eclipse.smarthome.test.OSGiTest.waitForAssert(OSGiTest.groovy:218)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:207)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:61)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:153)
	at org.eclipse.smarthome.test.OSGiTest.waitForAssert(OSGiTest.groovy:189)
	at org.eclipse.smarthome.test.OSGiTest.waitForAssert(OSGiTest.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:207)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:141)
	at org.eclipse.smarthome.core.audio.test.AudioOSGiTest.initializeAudioServlet(AudioOSGiTest.groovy:132)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:207)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:137)
	at org.eclipse.smarthome.core.audio.test.AudioManagerTest.assertServedStream(AudioManagerTest.groovy:338)
```

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Eclipse SmartHome .................................. SUCCESS [  0.179 s]
[INFO] Eclipse SmartHome Bundles .......................... SUCCESS [  0.010 s]
[INFO] Eclipse SmartHome Test Components .................. SUCCESS [  0.007 s]
[INFO] Eclipse SmartHome Core Components .................. SUCCESS [  0.006 s]
[INFO] Eclipse SmartHome Core ............................. SUCCESS [  1.909 s]
[INFO] Eclipse SmartHome Configurations ................... SUCCESS [  0.007 s]
[INFO] Eclipse SmartHome Configuration Core ............... SUCCESS [  0.363 s]
[INFO] Eclipse SmartHome Configuration XML ................ SUCCESS [  0.191 s]
[INFO] Eclipse SmartHome AutoUpdate Binding ............... SUCCESS [  0.906 s]
[INFO] Eclipse SmartHome Test ............................. SUCCESS [  0.716 s]
[INFO] Eclipse SmartHome Auth Components .................. SUCCESS [  0.007 s]
[INFO] Eclipse SmartHome JAAS Authentication .............. SUCCESS [  0.076 s]
[INFO] Eclipse SmartHome Configuration Dispatcher ......... SUCCESS [  0.107 s]
[INFO] Eclipse SmartHome Configuration Dispatcher Tests ... SUCCESS [ 11.067 s]
[INFO] Eclipse SmartHome Configuration Core Tests ......... SUCCESS [  2.990 s]
[INFO] Eclipse SmartHome I/O Components ................... SUCCESS [  0.010 s]
[INFO] Eclipse SmartHome Console .......................... SUCCESS [  0.104 s]
[INFO] Eclipse SmartHome Thing ............................ SUCCESS [  0.548 s]
[INFO] Eclipse SmartHome Configuration Discovery .......... SUCCESS [  0.224 s]
[INFO] Eclipse SmartHome Configuration Discovery Tests .... SUCCESS [ 15.297 s]
[INFO] Eclipse SmartHome Config XML Tests ................. SUCCESS [  4.514 s]
[INFO] Eclipse SmartHome Core Audio ....................... SUCCESS [  0.125 s]
[INFO] Eclipse SmartHome Core Binding XML ................. SUCCESS [  0.126 s]
[INFO] Eclipse SmartHome Core Thing XML ................... SUCCESS [  0.173 s]
[INFO] Eclipse Smarthome Audio Test ....................... FAILURE [01:54 min]
[INFO] Eclipse SmartHome Sample Extension Service ......... SKIPPED
[INFO] Eclipse SmartHome REST Interface ................... SKIPPED
[INFO] Eclipse SmartHome Core ID .......................... SKIPPED
[INFO] Eclipse SmartHome ID Tests ......................... SKIPPED
[INFO] Eclipse SmartHome Core Tests ....................... SKIPPED
[INFO] Eclipse SmartHome Thing Tests ...................... SKIPPED
```

**Comment by maggu2810** [comment]
Thanks for your report.
Does it fail all the time or sometimes?

Please use the "pre-formatted text" indications

```
log output should be formatted this way
```

**Comment by aisebastian** [comment]
Hello,

For me they fail every time. I don't know what those tests do and what other info might be needed from me.

P.S. I attempted to format it but failed. Got the hang of it now.

**Comment by htreu** [comment]
Fails for me too. Running macOS 10.12.3, Java 1.8.0_121, maven 3.3.9.

**Comment by htreu** [comment]
The tests fail due to an already blocked port 8080. Please check if any process is using this port. I had an orphan ESH instance running in the background. Killing it will result in passing tests again.

**Comment by aisebastian** [comment]
Indeed I had an 8080 process, but I failed to realize that was the culprit. Thanks!
