### ISSUE TITLE
Error building p2 repository

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#3291]
Using Maven, the build of p2 repository is systematically failing.
Here are my logs:
```
[INFO] ------------------------------------------------------------------------
[INFO] Building Eclipse SmartHome p2 Repository 0.9.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ org.eclipse.smarthome.repo ---
[INFO] Deleting F:\Dev\openhab2-master\git\smarthome\products\org.eclipse.smarthome.repo\target
[INFO]
[INFO] --- tycho-packaging-plugin:1.0.0:build-qualifier-aggregator (default-build-qualifier-aggregator) @ org.eclipse.smarthrepo ---
[INFO] The project's OSGi version is 0.9.0.201704221139
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean-1) @ org.eclipse.smarthome.repo ---
[INFO]
[INFO] --- build-helper-maven-plugin:1.8:add-source (add-source) @ org.eclipse.smarthome.repo ---
[INFO] Source directory: F:\Dev\openhab2-master\git\smarthome\products\org.eclipse.smarthome.repo\src\main\groovy added.
[INFO]
[INFO] --- maven-resources-plugin:2.4.3:resources (default-resources) @ org.eclipse.smarthome.repo ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory F:\Dev\openhab2-master\git\smarthome\products\org.eclipse.smarthome.repo\src\mainources
[INFO]
[INFO] --- maven-compiler-plugin:3.6.1:compile (default) @ org.eclipse.smarthome.repo ---
[INFO] No sources to compile
[INFO]
[INFO] --- build-helper-maven-plugin:1.8:add-test-source (add-test-source) @ org.eclipse.smarthome.repo ---
[INFO] Test Source directory: F:\Dev\openhab2-master\git\smarthome\products\org.eclipse.smarthome.repo\src\test\groovy added
[INFO]
[INFO] --- target-platform-configuration:1.0.0:target-platform (default-target-platform) @ org.eclipse.smarthome.repo ---
[INFO]
[INFO] --- tycho-p2-publisher-plugin:1.0.0:publish-products (default-publish-products) @ org.eclipse.smarthome.repo ---
[INFO]
[INFO] --- tycho-p2-publisher-plugin:1.0.0:publish-categories (default-publish-categories) @ org.eclipse.smarthome.repo ---
[INFO]
[INFO] --- tycho-p2-publisher-plugin:1.0.0:attach-artifacts (default-attach-artifacts) @ org.eclipse.smarthome.repo ---
[INFO]
[INFO] --- tycho-p2-repository-plugin:1.0.0:assemble-repository (default-assemble-repository) @ org.eclipse.smarthome.repo -
[INFO] ------------------------------------------------------------------------
```
and
```
[INFO] Eclipse SmartHome p2 Repository .................... FAILURE [ 49.063 s]
```

**Comment by kaikreuzer** [comment]
Please check your log for the real error message  - the first excerpt above does not show any problem, the second line only the final report.

**Comment by lolodomo** [comment]
Memory problem:
```
[ERROR] Java heap space -> [Help 1]
java.lang.OutOfMemoryError: Java heap space
        at org.tukaani.xz.lz.BT4.<init>(Unknown Source)
        at org.tukaani.xz.lz.LZEncoder.getInstance(Unknown Source)
        at org.tukaani.xz.lzma.LZMAEncoderNormal.<init>(Unknown Source)
        at org.tukaani.xz.lzma.LZMAEncoder.getInstance(Unknown Source)
        at org.tukaani.xz.LZMA2OutputStream.<init>(Unknown Source)
        at org.tukaani.xz.LZMA2Options.getOutputStream(Unknown Source)
        at org.tukaani.xz.LZMA2Encoder.getOutputStream(Unknown Source)
        at org.tukaani.xz.BlockOutputStream.<init>(Unknown Source)
        at org.tukaani.xz.XZOutputStream.write(Unknown Source)
        at org.eclipse.equinox.p2.internal.repository.tools.XZCompressor.compressFile(XZCompressor.java:153)
        at org.eclipse.equinox.p2.internal.repository.tools.XZCompressor.compressRepo(XZCompressor.java:116)
        at org.eclipse.tycho.p2.tools.mirroring.MirrorApplicationServiceImpl.mirrorReactor(MirrorApplicationServiceImpl.java                    :182)
        at org.eclipse.tycho.plugins.p2.repository.AssembleRepositoryMojo.execute(AssembleRepositoryMojo.java:144)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java                    :51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
```
How can I solve that ?

**Comment by maggu2810** [comment]
Have you set the maven option correctly?

```
set MAVEN_OPTS to "-Xms512m -Xmx1024m -XX:PermSize=256m -XX:MaxPermSize=512m"" in order to avoid memory problems during the build process.
```

**Comment by lolodomo** [comment]
My current value was "-Xmx512m -XX:MaxPermSize=128m". I changed to your value and restarted. I came back when finished.

Is this documented somewhere ?

**Comment by lolodomo** [comment]
Problem solved when using the new maven options.
@maggu2810 : thanks a lot.

**Comment by maggu2810** [comment]
I don't know if it is part of the documentation. Cannot search the source tree as I am on a trip.

It couldbe found there:
https://wiki.eclipse.org/EclipseSmartHome/Development/Build#Building_with_Maven

If the documentation is missing, we should add it.

**Comment by kaikreuzer** [comment]
> Is this documented somewhere ?

Right here: https://github.com/eclipse/smarthome#3-building-with-maven

**Comment by maggu2810** [comment]
@kaikreuzer Sholdn't we add it to some section in "documentation, development" (e.g. https://github.com/eclipse/smarthome/blob/master/docs/documentation/development/notes.md).
To use a single source of information we could move the whole "Building with Maven" section to that file (or a separate one) and refer in the main README.md to that section.
WDYT?

**Comment by kaikreuzer** [comment]
Yes, probably makes sense to have that covered in the documentation. Currently, I do not see a good page for it, though (I doubt that anybody will find it on "notes.md"...).
I am anyhow now happy with the current docs structure (e.g. the "Thing definition" is much too big by now), we should probably come up with some restructuring.
