### ISSUE TITLE
Astro binding: Null Pointer exception

### ISSUE THREAD

**Issue by sihui62** [eclipse/smarthome#3460]
Since around a couple of days the Astro binding is throwing a Null Pointer exception. It started already before moving the extension to eclipse smarthome.
Related community thread:
https://community.openhab.org/t/astrobinding-throws-an-nullpointer-error/27790
openhab.log:
```
2017-05-16 00:00:00.209 [ERROR] [org.quartz.core.JobRunShell         ] - Job astro:sun:shutterkitchen.job-daily-sun threw an unhandled Exception: 
java.lang.NullPointerException
	at org.eclipse.smarthome.binding.astro.internal.util.DateTimeUtils.applyConfig(DateTimeUtils.java:180)[187:org.eclipse.smarthome.binding.astro:0.9.0.201705120951]
	at org.eclipse.smarthome.binding.astro.internal.job.AbstractDailyJob.scheduleEvent(AbstractDailyJob.java:71)[187:org.eclipse.smarthome.binding.astro:0.9.0.201705120951]
	at org.eclipse.smarthome.binding.astro.internal.job.AbstractDailyJob.scheduleRange(AbstractDailyJob.java:58)[187:org.eclipse.smarthome.binding.astro:0.9.0.201705120951]
	at org.eclipse.smarthome.binding.astro.internal.job.DailyJobSun.schedulePlanetEvents(DailyJobSun.java:35)[187:org.eclipse.smarthome.binding.astro:0.9.0.201705120951]
	at org.eclipse.smarthome.binding.astro.internal.job.AbstractDailyJob.executeJob(AbstractDailyJob.java:47)[187:org.eclipse.smarthome.binding.astro:0.9.0.201705120951]
	at org.eclipse.smarthome.binding.astro.internal.job.AbstractBaseJob.execute(AbstractBaseJob.java:40)[187:org.eclipse.smarthome.binding.astro:0.9.0.201705120951]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)[105:org.eclipse.smarthome.core.scheduler:0.9.0.201705120951]
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)[105:org.eclipse.smarthome.core.scheduler:0.9.0.201705120951]
2017-05-16 00:00:00.218 [ERROR] [org.quartz.core.ErrorLogger         ] - Job (astro:sun:shutterkitchen.job-daily-sun threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: java.lang.NullPointerException]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)[105:org.eclipse.smarthome.core.scheduler:0.9.0.201705120951]
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)[105:org.eclipse.smarthome.core.scheduler:0.9.0.201705120951]
Caused by: java.lang.NullPointerException
	at org.eclipse.smarthome.binding.astro.internal.util.DateTimeUtils.applyConfig(DateTimeUtils.java:180)[187:org.eclipse.smarthome.binding.astro:0.9.0.201705120951]
	at org.eclipse.smarthome.binding.astro.internal.job.AbstractDailyJob.scheduleEvent(AbstractDailyJob.java:71)[187:org.eclipse.smarthome.binding.astro:0.9.0.201705120951]
	at org.eclipse.smarthome.binding.astro.internal.job.AbstractDailyJob.scheduleRange(AbstractDailyJob.java:58)[187:org.eclipse.smarthome.binding.astro:0.9.0.201705120951]
	at org.eclipse.smarthome.binding.astro.internal.job.DailyJobSun.schedulePlanetEvents(DailyJobSun.java:35)[187:org.eclipse.smarthome.binding.astro:0.9.0.201705120951]
	at org.eclipse.smarthome.binding.astro.internal.job.AbstractDailyJob.executeJob(AbstractDailyJob.java:47)[187:org.eclipse.smarthome.binding.astro:0.9.0.201705120951]
	at org.eclipse.smarthome.binding.astro.internal.job.AbstractBaseJob.execute(AbstractBaseJob.java:40)[187:org.eclipse.smarthome.binding.astro:0.9.0.201705120951]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)[105:org.eclipse.smarthome.core.scheduler:0.9.0.201705120951]
	... 1 more
```

**Comment by sjka** [comment]
Indeed, it looks like something goes wrong when calculating the night range: 

```
        SunCalc sunCalc = new SunCalc();
        Calendar cal = Calendar.getInstance();
        cal.set(2017, 4, 4, 7, 49, 3);
        Sun sun = sunCalc.getSunInfo(cal, 58.32292, 15.03335, 100);
        System.out.println(sun.getNight());
```

gives

```
Range[start=<null>,end=<null>]
```

**Comment by sjka** [comment]
@gerrieg will you have a look at this?

**Comment by sjka** [comment]
@gerrieg Nevermind, I proposed #3461 to fix it. You may still look at it, of course... 😄

**Comment by sihui62** [comment]
Thx for the amazing fast support, @sjka

**Comment by sihui62** [comment]
Unfortunately the fix does not seem to work or there is a new issue:

https://community.openhab.org/t/astrobinding-throws-an-nullpointer-error/27790/15?u=sihui

**Comment by sjka** [comment]
Please bear in mind that openHAB does not use the Eclipse SmartHome master branch directly, but only consumes the latest "stable" build. Here you can see when it was built the last time and what it included: https://hudson.eclipse.org/smarthome/job/SmartHomeDistribution-Stable/changes 

As you can see, my fix didn't make it into stable, hence also not into openHAB yet.

**Comment by sihui62** [comment]
>As you can see, my fix didn't make it into stable, hence also not into openHAB yet.

Thx for clarification. As a non programmer those details are not easy to catch ;-)

**Comment by maggu2810** [comment]
> Please bear in mind that openHAB does not use the Eclipse SmartHome master branch directly, but only consumes the latest "stable" build. Here you can see when it was built the last time and what it included: https://hudson.eclipse.org/smarthome/job/SmartHomeDistribution-Stable/changes

Perhaps we could create a wiki page for that information (similar to e.g. https://github.com/eclipse/smarthome/wiki/ESH-used-in-openHAB) and only add a link to that one in the comments. It seems that this information is added to multiple issues the last days (IMHO).

**Comment by sjka** [comment]
Thanks for pointing me to it. Somewhere in my head I knew we had it, but didn't remember to look it up.

> Perhaps we could create a wiki page [...]

No need, the one you referenced already contained the missing piece of information. 

> [...] and only add a link to that one in the comments

That's all it would have needed.
