### ISSUE TITLE
FolderObserverTest fails in project org.eclipse.smarthome.model.core.test

### ISSUE THREAD

**Issue by frhei** [eclipse/smarthome#3481]
Build of latest commit ea5b67372d8a7dd00c52e8d41c699e4a440a5d72 fails in test case FolderObserverTest of test project org.eclipse.smarthome.model.core.test:

```
Running org.eclipse.smarthome.model.core.internal.folder.test.FolderObserverTest
Tests run: 10, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 12.955 sec <<< FAILURE! - in org.eclipse.smarthome.model.core.internal.folder.test.FolderObserverTest
test the updating of the configuration with a non existing subdirectory(org.eclipse.smarthome.model.core.internal.folder.test.FolderObserverTest)  Time elapsed: 0.461 sec
test modification of file with valid extension in an existing subdirectory(org.eclipse.smarthome.model.core.internal.folder.test.FolderObserverTest)  Time elapsed: 2.147 sec
test that an exception does not kill the watcher(org.eclipse.smarthome.model.core.internal.folder.test.FolderObserverTest)  Time elapsed: 2.055 sec
test ignore hidden files with extension that is registered(org.eclipse.smarthome.model.core.internal.folder.test.FolderObserverTest)  Time elapsed: 1.234 sec  <<< ERROR!
groovy.lang.MissingPropertyException: No such property: set for class: java.nio.file.Files
        at groovy.lang.MetaClassImpl.invokeStaticMissingProperty(MetaClassImpl.java:996)
        at groovy.lang.MetaClassImpl.getProperty(MetaClassImpl.java:1851)
        at groovy.lang.MetaClassImpl.getProperty(MetaClassImpl.java:1827)
        at groovy.lang.MetaClassImpl.getProperty(MetaClassImpl.java:3690)
        at org.codehaus.groovy.runtime.callsite.ClassMetaClassGetPropertySite.getProperty(ClassMetaClassGetPropertySite.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:227)
        at org.eclipse.smarthome.model.core.internal.folder.test.FolderObserverTest.test ignore hidden files with extension that is registered(FolderObserverTest.groovy:521)

test deletion of a folder-extensions pair from the configuration properties when folderFileExtMap remains non-empty(org.eclipse.smarthome.model.core.internal.folder.test.FolderObserverTest)  Time elapsed: 1.279 sec
test deletion of a folder-extensions pair from the configuration properties when folderFileExtMap becomes empty(org.eclipse.smarthome.model.core.internal.folder.test.FolderObserverTest)  Time elapsed: 0.439 sec
test creation of file with valid extension in an existing subdirectory(org.eclipse.smarthome.model.core.internal.folder.test.FolderObserverTest)  Time elapsed: 1.25 sec
test creation of file with extension which is not in the configuration properties in an existing subdirectory(org.eclipse.smarthome.model.core.internal.folder.test.FolderObserverTest)  Time elapsed: 1.232 sec
test creation of file in subdirectory with no declared extensions(org.eclipse.smarthome.model.core.internal.folder.test.FolderObserverTest)  Time elapsed: 1.247 sec
test creation of file with extension which does not have a registered ModelParser in an existing subdirectory(org.eclipse.smarthome.model.core.internal.folder.test.FolderObserverTest)  Time elapsed: 1.223 sec

Results :

Tests in error:
  FolderObserverTest.test ignore hidden files with extension that is registered:521 ╗ MissingProperty

Tests run: 10, Failures: 0, Errors: 1, Skipped: 0
```

Build Environment:
```
mvn -v
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T21:39:06+02:00)
Maven home: C:\Tools\apache-maven-3.5.0\bin\..
Java version: 1.8.0_131, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jre1.8.0_131
Default locale: de_DE, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

JAVA_HOME="C:\Programme\Java\jdk1.8.0_131"

mvn clean install
```
            

A property of the Files class in code line `Files.set.setAttribute (mockFileWithValidExt.toPath(), "dos:hidden", true);` is not found.
Code is only extecuted on windows system and a remark says             
`//windows needs a filesystem property set for a file to be hidden (untested)
`

No additional information in log file:
[org.eclipse.smarthome.model.core.internal.folder.test.FolderObserverTest.txt](https://github.com/eclipse/smarthome/files/1009836/org.eclipse.smarthome.model.core.internal.folder.test.FolderObserverTest.txt)

**Comment by sjka** [comment]
Thanks for reporting this, there indeed was a typo in the groovy test-case.
How about #3483, does it fix it (sorry, I can't try it out myself right now...)? 

You can try it out by [checking out this PR locally](https://help.github.com/articles/checking-out-pull-requests-locally/):

```
git fetch origin pull/3483/head:pr3483
git checkout pr3483
```

**Comment by frhei** [comment]
Thanks for solving quickly!
Test executes now, but unveils more general problem with windows hidden files.
Please see PR #3490.
