### ISSUE TITLE
[Scheduler] ConcurrentModificationException in ExpressionThreadPoolManager

### ISSUE THREAD

**Issue by sjka** [eclipse/smarthome#3504]
When testing #3501 the log showed plenty of these:

```
Exception in thread "ESH-astro-7" java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1461)
	at org.eclipse.smarthome.core.scheduler.ExpressionThreadPoolManager$ExpressionThreadPoolExecutor.afterExecute(ExpressionThreadPoolManager.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1150)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by sjka** [comment]
@kgoderis could you please have a look?
