### ISSUE TITLE
[Scheduler] ArrayIndexOutOfBoundsException in scheduler

### ISSUE THREAD

**Issue by sjka** [eclipse/smarthome#3505]
When trying it out #3501, I ran into this here:

```
14:08:37.864 ERROR o.e.s.b.a.h.AstroThingHandler[:234] - 853
java.lang.ArrayIndexOutOfBoundsException: 853
	at sun.util.calendar.BaseCalendar.getCalendarDateFromFixedDate(BaseCalendar.java:453)
	at java.util.GregorianCalendar.computeFields(GregorianCalendar.java:2397)
	at java.util.GregorianCalendar.computeFields(GregorianCalendar.java:2312)
	at java.util.Calendar.setTimeInMillis(Calendar.java:1804)
	at java.util.Calendar.setTime(Calendar.java:1770)
	at java.text.SimpleDateFormat.format(SimpleDateFormat.java:943)
	at java.text.SimpleDateFormat.format(SimpleDateFormat.java:936)
	at java.text.DateFormat.format(DateFormat.java:345)
	at org.eclipse.smarthome.core.scheduler.AbstractExpression.applyExpressionParts(AbstractExpression.java:202)
	at org.eclipse.smarthome.core.scheduler.AbstractExpression.parseExpression(AbstractExpression.java:176)
	at org.eclipse.smarthome.core.scheduler.AbstractExpression.parseExpression(AbstractExpression.java:144)
```

**Comment by sjka** [comment]
@kgoderis could you please have a look?

**Comment by sjka** [comment]
Having discovered #3506 I suppose this could be the root cause: It's using a static (!) SimpleDateFormat. And this class is well-known for not being thread-safe as much as it could get...
