### ISSUE TITLE
NullPointerException on groups as switches in sitemaps

### ISSUE THREAD

**Issue by antares2001** [eclipse/smarthome#3530]
Referencing the discussion here https://community.openhab.org/t/null-pointer-exception-on-group-items/28167/10 I currently experience the following issue (copying the forum post) running the version 2017-05-28 of OpenHAB (unstable, from jfrog apt repository on Debian 8).:

I have the following line in my sitemap:

`Switch item=gFensterRollos label="Fensterrolläden" icon="rollershutter"`

and items like

`Rollershutter ROLL_WZ_Fenster "Wohnzimmer Fenster" (gFensterRollos) { channel="rfxcom:rfy:2ac13127:shutter" }`

that leads when opening it in Basic UI to the following stacktrace:

```
==> /var/log/openhab2/openhab.log <==
2017-05-28 12:35:57.112 [WARN ] [eclipse.jetty.servlet.ServletHandler] - /basicui/app
java.lang.NullPointerException
	at org.eclipse.smarthome.core.items.GenericItem.getStateAs(GenericItem.java:93)[99:org.eclipse.smarthome.core:0.9.0.201705261932]
	at org.eclipse.smarthome.core.items.GroupItem.getStateAs(GroupItem.java:264)[99:org.eclipse.smarthome.core:0.9.0.201705261932]
	at org.eclipse.smarthome.ui.internal.items.ItemUIRegistryImpl.convertState(ItemUIRegistryImpl.java:510)[137:org.eclipse.smarthome.ui:0.9.0.201705261932]
	at org.eclipse.smarthome.ui.internal.items.ItemUIRegistryImpl.getState(ItemUIRegistryImpl.java:485)[137:org.eclipse.smarthome.ui:0.9.0.201705261932]
	at org.eclipse.smarthome.ui.basic.internal.render.SwitchRenderer.renderWidget(SwitchRenderer.java:74)[199:org.eclipse.smarthome.ui.basic:0.9.0.201705261932]
	at org.eclipse.smarthome.ui.basic.internal.render.PageRenderer.renderWidget(PageRenderer.java:167)[199:org.eclipse.smarthome.ui.basic:0.9.0.201705261932]
	at org.eclipse.smarthome.ui.basic.internal.render.PageRenderer.processChildren(PageRenderer.java:129)[199:org.eclipse.smarthome.ui.basic:0.9.0.201705261932]
	at org.eclipse.smarthome.ui.basic.internal.render.PageRenderer.processChildren(PageRenderer.java:150)[199:org.eclipse.smarthome.ui.basic:0.9.0.201705261932]
	at org.eclipse.smarthome.ui.basic.internal.render.PageRenderer.processPage(PageRenderer.java:92)[199:org.eclipse.smarthome.ui.basic:0.9.0.201705261932]
	at org.eclipse.smarthome.ui.basic.internal.servlet.WebAppServlet.service(WebAppServlet.java:175)[199:org.eclipse.smarthome.ui.basic:0.9.0.201705261932]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)[82:org.eclipse.jetty.servlet:9.2.19.v20160908]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)[82:org.eclipse.jetty.servlet:9.2.19.v20160908]
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:71)[173:org.ops4j.pax.web.pax-web-jetty:4.3.0]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)[81:org.eclipse.jetty.server:9.2.19.v20160908]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)[80:org.eclipse.jetty.security:9.2.19.v20160908]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)[81:org.eclipse.jetty.server:9.2.19.v20160908]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)[81:org.eclipse.jetty.server:9.2.19.v20160908]
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:287)[173:org.ops4j.pax.web.pax-web-jetty:4.3.0]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)[82:org.eclipse.jetty.servlet:9.2.19.v20160908]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)[81:org.eclipse.jetty.server:9.2.19.v20160908]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)[81:org.eclipse.jetty.server:9.2.19.v20160908]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)[81:org.eclipse.jetty.server:9.2.19.v20160908]
	at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:80)[173:org.ops4j.pax.web.pax-web-jetty:4.3.0]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)[81:org.eclipse.jetty.server:9.2.19.v20160908]
	at org.eclipse.jetty.server.Server.handle(Server.java:499)[81:org.eclipse.jetty.server:9.2.19.v20160908]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)[81:org.eclipse.jetty.server:9.2.19.v20160908]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)[81:org.eclipse.jetty.server:9.2.19.v20160908]
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)[72:org.eclipse.jetty.io:9.2.19.v20160908]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)[84:org.eclipse.jetty.util:9.2.19.v20160908]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)[84:org.eclipse.jetty.util:9.2.19.v20160908]
	at java.lang.Thread.run(Thread.java:748)[:1.8.0_131]
```

**Comment by kaikreuzer** [comment]
@triller-telekom Could you please have a look?

**Comment by sjka** [comment]
could be related to #3520

**Comment by antares2001** [comment]
@kaikreuzer, @sjka, @triller-telekom
Question: if a certain item returns null, which obviously leads to this exception, why is the exception not caught where the UI is generated / the item placed in to the UI, so that the item simply does not appear in the UI, but sitemap shows all the other valid items? Currently, the sitemap does not function at all (i.e., does not load) when this happens which makes OpenHAB unusable in this case. I'd rather prefer a working UI and a log entry that there was something wrong, than a totally not working sitemap that stops working just because of one element.

What do you guys think?

**Comment by maggu2810** [comment]
I agree

**Comment by kaikreuzer** [comment]
> if a certain item returns null, which obviously leads to this exception

No, it does not return null, but it internally has a null state which is a fatal illegal system state. This needs to be fixed again and then this will never happen.

I don't think that UIs can/should catch any RuntimeExceptions as if they were expected.
