### ISSUE TITLE
[Astro] NPE in SunCalc.setPositionalInfo()

### ISSUE THREAD

**Issue by sjka** [eclipse/smarthome#3610]
Just saw this here in my logs:

```
2017-06-06 08:40:45.136 [ERROR] [org.quartz.core.JobRunShell         ] - Job astro:sun:gdhsn.job-positional threw an unhandled Exception:
java.lang.NullPointerException
        at org.eclipse.smarthome.binding.astro.internal.calc.SunCalc.setPositionalInfo(SunCalc.java:75)[189:org.eclipse.smarthome.binding.astro:0.9.0.201705301617]
        at org.eclipse.smarthome.binding.astro.handler.SunHandler.publishPositionalInfo(SunHandler.java:57)[189:org.eclipse.smarthome.binding.astro:0.9.0.201705301617]
        at org.eclipse.smarthome.binding.astro.internal.job.PositionalJob.executeJob(PositionalJob.java:25)[189:org.eclipse.smarthome.binding.astro:0.9.0.201705301617]
        at org.eclipse.smarthome.binding.astro.internal.job.AbstractBaseJob.execute(AbstractBaseJob.java:39)[189:org.eclipse.smarthome.binding.astro:0.9.0.201705301617]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)[105:org.eclipse.smarthome.core.scheduler:0.9.0.201705301617]
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)[105:org.eclipse.smarthome.core.scheduler:0.9.0.201705301617]
```

**Comment by triller-telekom** [comment]
This is fixed in PR #3503
