### ISSUE TITLE
Bug in parameter value normalization

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#3678]
Just found that in my log using the most recent code:

```
17:27:57.440 [WARN ] [.smarthome.config.core.Configuration] - Could not set field value for field 'id': Can not set java.lang.Integer field org.eclipse.smarthome.binding.tradfri.DeviceConfig.id to java.lang.String
java.lang.IllegalArgumentException: Can not set java.lang.Integer field org.eclipse.smarthome.binding.tradfri.DeviceConfig.id to java.lang.String
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)[:1.8.0_112]
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)[:1.8.0_112]
	at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)[:1.8.0_112]
	at java.lang.reflect.Field.set(Field.java:764)[:1.8.0_112]
	at org.apache.commons.lang.reflect.FieldUtils.writeField(FieldUtils.java:523)[31:org.apache.commons.lang:2.6.0]
	at org.apache.commons.lang.reflect.FieldUtils.writeField(FieldUtils.java:500)[31:org.apache.commons.lang:2.6.0]
	at org.apache.commons.lang.reflect.FieldUtils.writeField(FieldUtils.java:560)[31:org.apache.commons.lang:2.6.0]
	at org.eclipse.smarthome.config.core.Configuration.as(Configuration.java:96)[95:org.eclipse.smarthome.config.core:0.9.0.201706161358]
	at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.getConfigAs(BaseThingHandler.java:248)[106:org.eclipse.smarthome.core.thing:0.9.0.201706161358]
	at org.eclipse.smarthome.binding.tradfri.handler.TradfriLightHandler.initialize(TradfriLightHandler.java:69)[184:org.eclipse.smarthome.binding.tradfri:0.9.0.201706161358]
	at org.eclipse.smarthome.core.thing.internal.ThingManager$9.call(ThingManager.java:741)[106:org.eclipse.smarthome.core.thing:0.9.0.201706161358]
	at org.eclipse.smarthome.core.thing.internal.ThingManager$9.call(ThingManager.java:1)[106:org.eclipse.smarthome.core.thing:0.9.0.201706161358]
	at org.eclipse.smarthome.core.common.SafeMethodCaller$CallableWrapper.call(SafeMethodCaller.java:181)[99:org.eclipse.smarthome.core:0.9.0.201706161358]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_112]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_112]
```

Not sure what is causing this, but my suspicion is that it might be related to https://github.com/eclipse/smarthome/pull/3662. @sjka wdyt?

**Comment by sjka** [comment]
Ha. Yes it is. And it's even correct:

```
<parameter name="id" type="text" required="true">
```
