### ISSUE TITLE
io.rest uses gson 2.5.0, although we so far only support gson 2.3.1

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#3680]
I found this in my logs:

```
Exception in thread "Thread-65" java.lang.IllegalAccessError: tried to access method com.google.gson.Gson.newJsonWriter(Ljava/io/Writer;)Lcom/google/gson/stream/JsonWriter; from class org.eclipse.smarthome.io.rest.JSONResponse
        at org.eclipse.smarthome.io.rest.JSONResponse.lambda$0(JSONResponse.java:162)
        at java.lang.Thread.run(Thread.java:745)
```
A closer analysis shows that this method is only publicly available in gson 2.5, while my setup only has gson 2.3.1 available.

Interestingly, our smarthome.target resolves 2.2.4 AND 2.5.0, so the IDE picks up 2.5.0 and compiles against it.

As far as I remember, we wanted to be compatible with gson 2.3.1, but it all seems to be a bit messed up right now...

**Comment by sjka** [comment]
it's probably the jax-rs adapter which brings the newest gson version. Looking into it, it's so dead-simple that we could bring our own instead easily and remove it from our target scope.
