### ISSUE TITLE
Binding configuration could not be parsed correctly : No active update transaction

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#3689]
Using snapshot 950, I got tons of errors of the same type at startup:
```
2017-06-17 08:45:33.577 [ERROR] [el.item.internal.GenericItemProvider] - Binding configuration of type 'channel' of item 'WUForecastTempMin' could not be parsed correctly.
java.lang.IllegalStateException: No active update transaction
        at org.eclipse.smarthome.model.thing.internal.GenericItemChannelLinkProvider.processBindingConfiguration(GenericItemChannelLinkProvider.java:62)
        at org.eclipse.smarthome.model.item.internal.GenericItemProvider.internalDispatchBindings(GenericItemProvider.java:325)
        at org.eclipse.smarthome.model.item.internal.GenericItemProvider.dispatchBindingsPerType(GenericItemProvider.java:281)
        at org.eclipse.smarthome.model.item.internal.GenericItemProvider.addBindingConfigReader(GenericItemProvider.java:119)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)[:1.8.0_121]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)[:1.8.0_121]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[:1.8.0_121]
        at java.lang.reflect.Method.invoke(Method.java:498)[:1.8.0_121]
...
```
Probably for all my channels.
As a probable consequence, lots of bindings are not working.
Waiting for a fix, I switch back to snapshot 937.

**Comment by lolodomo** [comment]
Duplication of #3686
