### ISSUE TITLE
 [FS Internetradio] OutOfMemory Leaks with openHAB 2?

### ISSUE THREAD

**Issue by bytedealer** [eclipse/smarthome#3711]
I am using openHAB 2 on a DS214play (2.0.0.001-DSM6) and bought some Silvercrest SMRS 35 A1 and a SMRB 40 A1 with FS chip. Everything is starting and being controlled perfectly. But after a couple of hours, less than one day, there is an interruption and errors coming up.

First:

```
2017-06-18 14:09:48.268 [ERROR] [ore.internal.events.OSGiEventManager] - Dispatching/filtering event for subscriber 'org.eclipse.smarthome.core.events.EventSubscriber' failed: java.lang.OutOfMemoryError: unable to create new native thread
java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: unable to create new native thread
at java.util.concurrent.FutureTask.report(FutureTask.java:122)[:1.8.0_91]
at java.util.concurrent.FutureTask.get(FutureTask.java:206)[:1.8.0_91]
at org.eclipse.smarthome.core.common.SafeMethodCaller.callAsynchronous(SafeMethodCaller.java:188)[98:org.eclipse.smarthome.core:0.9.0.b4]
at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:81)[98:org.eclipse.smarthome.core:0.9.0.b4]
at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:65)[98:org.eclipse.smarthome.core:0.9.0.b4]
at org.eclipse.smarthome.core.internal.events.OSGiEventManager.dispatchESHEvent(OSGiEventManager.java:188)[98:org.eclipse.smarthome.core:0.9.0.b4]
at org.eclipse.smarthome.core.internal.events.OSGiEventManager.handleEvent(OSGiEventManager.java:163)[98:org.eclipse.smarthome.core:0.9.0.b4]
at org.eclipse.smarthome.core.internal.events.OSGiEventManager.handleEvent(OSGiEventManager.java:146)[98:org.eclipse.smarthome.core:0.9.0.b4]
at org.apache.felix.eventadmin.impl.handler.EventHandlerProxy.sendEvent(EventHandlerProxy.java:415)[6:org.apache.karaf.services.eventadmin:4.0.8]
at org.apache.felix.eventadmin.impl.tasks.HandlerTask.run(HandlerTask.java:90)[6:org.apache.karaf.services.eventadmin:4.0.8]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_91]
at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_91]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_91]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_91]
at java.lang.Thread.run(Thread.java:745)[:1.8.0_91]
Caused by: java.lang.OutOfMemoryError: unable to create new native thread
at java.lang.Thread.start0(Native Method)[:1.8.0_91]
at java.lang.Thread.start(Thread.java:714)[:1.8.0_91]
at org.eclipse.smarthome.core.common.QueueingThreadPoolExecutor.addToQueue(QueueingThreadPoolExecutor.java:115)
at org.eclipse.smarthome.core.common.QueueingThreadPoolExecutor.execute(QueueingThreadPoolExecutor.java:156)
at org.eclipse.smarthome.core.items.GenericItem.notifyListeners(GenericItem.java:235)
at org.eclipse.smarthome.core.items.GenericItem.applyState(GenericItem.java:213)
at org.eclipse.smarthome.core.items.GenericItem.setState(GenericItem.java:199)
at org.eclipse.smarthome.core.internal.items.ItemUpdater.receiveUpdate(ItemUpdater.java:70)
at org.eclipse.smarthome.core.items.events.AbstractItemEventSubscriber.receive(AbstractItemEventSubscriber.java:44)
at org.eclipse.smarthome.core.internal.events.OSGiEventManager$1.call(OSGiEventManager.java:192)
at org.eclipse.smarthome.core.internal.events.OSGiEventManager$1.call(OSGiEventManager.java:1)
at org.eclipse.smarthome.core.common.SafeMethodCaller$CallableWrapper.call(SafeMethodCaller.java:179)
... 4 more
```
and later I get a lot of them:

```
2017-06-18 14:10:45.534 [WARN ] [tty.util.component.AbstractLifeCycle] - FAILED HttpClient@1002072{FAILED,8<=1<=200,i=1,q=0}: java.lang.OutOfMemoryError: unable to create new native thread
java.lang.OutOfMemoryError: unable to create new native thread
at java.lang.Thread.start0(Native Method)[:1.8.0_91]
at java.lang.Thread.start(Thread.java:714)[:1.8.0_91]
at org.eclipse.jetty.util.thread.QueuedThreadPool.startThreads(QueuedThreadPool.java:447)[83:org.eclipse.jetty.util:9.2.19.v20160908]
at org.eclipse.jetty.util.thread.QueuedThreadPool.doStart(QueuedThreadPool.java:106)[83:org.eclipse.jetty.util:9.2.19.v20160908]
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)[83:org.eclipse.jetty.util:9.2.19.v20160908]
at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)[83:org.eclipse.jetty.util:9.2.19.v20160908]
at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)[83:org.eclipse.jetty.util:9.2.19.v20160908]
at org.eclipse.jetty.client.HttpClient.doStart(HttpClient.java:229)[69:org.eclipse.jetty.client:9.2.19.v20160908]
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)[83:org.eclipse.jetty.util:9.2.19.v20160908]
at org.eclipse.smarthome.binding.fsinternetradio.internal.radio.FrontierSiliconRadioConnection.startHttpClient(FrontierSiliconRadioConnection.java:205)[210:org.eclipse.smarthome.binding.fsinternetradio:0.9.0.b4]
at org.eclipse.smarthome.binding.fsinternetradio.internal.radio.FrontierSiliconRadioConnection.doLogin(FrontierSiliconRadioConnection.java:81)[210:org.eclipse.smarthome.binding.fsinternetradio:0.9.0.b4]
at org.eclipse.smarthome.binding.fsinternetradio.internal.radio.FrontierSiliconRadio.login(FrontierSiliconRadio.java:64)[210:org.eclipse.smarthome.binding.fsinternetradio:0.9.0.b4]
at org.eclipse.smarthome.binding.fsinternetradio.handler.FSInternetRadioHandler$2.run(FSInternetRadioHandler.java:144)[210:org.eclipse.smarthome.binding.fsinternetradio:0.9.0.b4]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_91]
at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_91]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)[:1.8.0_91]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)[:1.8.0_91]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_91]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_91]
at java.lang.Thread.run(Thread.java:745)[:1.8.0_91]
```

until openHAB crashes (because the system does not respond anymore).

I asked @paphko at openHAB community and he had a first guess:
https://community.openhab.org/t/fs-internetradio-outofmemory-leaks-with-openhab-2/30229

I saw @svilenvul, @kaikreuzer, @m-memova, @maggu2810 were the contributors. Does anybody of you understand what is happening?

**Comment by svilenvul** [comment]
I have a guess : 
 - In the [periodic refresh job](https://github.com/eclipse/smarthome/blob/master/extensions/binding/org.eclipse.smarthome.binding.fsinternetradio/src/main/java/org/eclipse/smarthome/binding/fsinternetradio/handler/FSInternetRadioHandler.java#L53) we have a call to [radioLogin()](https://github.com/eclipse/smarthome/blob/master/extensions/binding/org.eclipse.smarthome.binding.fsinternetradio/src/main/java/org/eclipse/smarthome/binding/fsinternetradio/handler/FSInternetRadioHandler.java#L128) which **creates a new instance of "FrontierSiliconRadio" at each attempt** and then tries to login using new "FrontierSiliconRadioConnection";
- this connection creates new instance of the [Jetty HttpClient](https://github.com/eclipse/smarthome/blob/master/extensions/binding/org.eclipse.smarthome.binding.fsinternetradio/src/main/java/org/eclipse/smarthome/binding/fsinternetradio/internal/radio/FrontierSiliconRadioConnection.java#L79) **which is started but not stopped**. 
- as it is written in the [Jetty documentation](https://www.eclipse.org/jetty/documentation/current/http-client.html#http-client-init) : 
> Stopping HttpClient makes sure that the memory it holds (for example, authentication credentials, cookies, etc.) is released, and that the thread pool and scheduler are properly stopped allowing all threads used by HttpClient to exit.
- after many failed login attempts we ran out of native threads or memory.

@kaikreuzer ,
do you think it makes sense to setup a test locally - start a local server which responds to the radio and monitor the memory usage and thread count using some memory profiler tool ?

**Comment by kaikreuzer** [comment]
> do you think it makes sense to setup a test locally

Depends on the effort to do so. If you have already identified a bug, you might simply go for fixing it and leave the testing to users with real devices.

**Comment by svilenvul** [comment]
Running the test (login attempt with invalid PIN) for 30 seconds results in 274 new Threads, before the changes.
