### ISSUE TITLE
CME in AbstractExpression of Scheduler

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#3719]
Just found this in my log:

```
Exception in thread "ESH-astro-Monitor-1" java.util.ConcurrentModificationException
	at java.util.ArrayList.sort(ArrayList.java:1456)
	at java.util.Collections.sort(Collections.java:141)
	at org.eclipse.smarthome.core.scheduler.AbstractExpression.applyExpressionParts(AbstractExpression.java:195)
	at org.eclipse.smarthome.core.scheduler.AbstractExpression.parseExpression(AbstractExpression.java:173)
	at org.eclipse.smarthome.core.scheduler.AbstractExpression.parseExpression(AbstractExpression.java:141)
	at org.eclipse.smarthome.core.scheduler.AbstractExpression.setStartDate(AbstractExpression.java:96)
	at org.eclipse.smarthome.core.scheduler.CronExpression.setStartDate(CronExpression.java:188)
	at org.eclipse.smarthome.core.scheduler.AbstractExpression.getTimeAfter(AbstractExpression.java:265)
	at org.eclipse.smarthome.core.scheduler.ExpressionThreadPoolManager$ExpressionThreadPoolExecutor$1.run(ExpressionThreadPoolManager.java:166)
	at java.lang.Thread.run(Thread.java:745)
```

At a first glance, I have no idea how we can run in concurrent modifications here, but there must be some situations that need to be considered.

**Comment by maggu2810** [comment]
The AbstractExpression itself is not thread safe, so we need to check if the same object is used and modified by different threads.

**Comment by sjka** [comment]
I can only see a very poor attempt of synchronization [here](https://github.com/eclipse/smarthome/blob/caa91af3c2c390afb0dc864816b9a70ddefd6fa5/bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/scheduler/AbstractExpression.java#L364). Otherwise it is completely unprotected, as the original is exposed publicly and modified in several places.
