### ISSUE TITLE
Can't build on RPi

### ISSUE THREAD

**Issue by grimace** [eclipse/smarthome#3765]
Couldn't tell from the docs if it could actually be done, but here's the error:
`
[ERROR] Internal error: java.lang.RuntimeException: Could not determine SWT implementation fragment bundle for environment {osgi.os=linux, osgi.ws=gtk, org.eclipse.update.install.features=true, osgi.arch=arm} -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.RuntimeException: Could not determine SWT implementation fragment bundle for environment {osgi.os=linux, osgi.ws=gtk, org.eclipse.update.install.features=true, osgi.arch=arm}
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:167)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.RuntimeException: Could not determine SWT implementation fragment bundle for environment {osgi.os=linux, osgi.ws=gtk, org.eclipse.update.install.features=true, osgi.arch=arm}
	at org.eclipse.tycho.p2.util.resolution.ProjectorResolutionStrategy.fixSWT(ProjectorResolutionStrategy.java:162)
	at org.eclipse.tycho.p2.util.resolution.ProjectorResolutionStrategy.resolve(ProjectorResolutionStrategy.java:96)
	at org.eclipse.tycho.p2.util.resolution.AbstractResolutionStrategy.multiPlatformResolve(AbstractResolutionStrategy.java:50)
	at org.eclipse.tycho.p2.target.TargetDefinitionResolver$ResolverRun.resolve(TargetDefinitionResolver.java:200)
	at org.eclipse.tycho.p2.target.TargetDefinitionResolver.resolveContentWithExceptions(TargetDefinitionResolver.java:136)
	at org.eclipse.tycho.p2.target.TargetDefinitionResolver.resolveContent(TargetDefinitionResolver.java:94)
	at org.eclipse.tycho.p2.target.TargetDefinitionResolverService.resolveFromArguments(TargetDefinitionResolverService.java:70)
	at org.eclipse.tycho.p2.target.TargetDefinitionResolverService.getTargetDefinitionContent(TargetDefinitionResolverService.java:60)
	at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.resolveTargetDefinitions(TargetPlatformFactoryImpl.java:214)
	at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.createTargetPlatform(TargetPlatformFactoryImpl.java:155)
	at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.createTargetPlatform(TargetPlatformFactoryImpl.java:128)
	at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.createTargetPlatform(TargetPlatformFactoryImpl.java:1)
	at org.eclipse.tycho.p2.manager.ReactorRepositoryManagerImpl.computePreliminaryTargetPlatform(ReactorRepositoryManagerImpl.java:84)
	at org.eclipse.tycho.p2.resolver.P2DependencyResolver.computePreliminaryTargetPlatform(P2DependencyResolver.java:223)
	at org.eclipse.tycho.core.resolver.DefaultTychoResolver.resolveProject(DefaultTychoResolver.java:109)
	at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.afterProjectsRead(TychoMavenLifecycleParticipant.java:95)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:318)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
`

**Comment by maggu2810** [comment]
The Designer has been moved to a separate repository, so I assume we don't need SWT at all anymore.

**Comment by sjka** [comment]
The UI _bundles_ (like e.g. org.eclipse.smarthome.designer.ui) are still here. So we still need it.
May I ask what your motivation is to _build_ ESH on a RPi?

**Comment by maggu2810** [comment]
> The UI bundles (like e.g. org.eclipse.smarthome.designer.ui) are still here.

You are right. Unfortunately there are here. :wink:

**Comment by grimace** [comment]
I'm just getting started with SH.  I wanted to run it on my RPi3.  I thought the appropriate steps would be to clone, build, and then run.  Is that not the case?

**Comment by sjka** [comment]
Eclipse SmartHome ist "just" a framework - so the build mainly produces a couple of OSGi bundles which you then have to install into an OSGi runtime, with all their required dependencies. That's why you normally don't build the stuff where you run it but rather do that on a fast(er) machine. 

Here is an example of how it could look like to assemble your own "product": https://github.com/eclipse/smarthome-packaging-sample. An open source based solution that is doing that packaging for you and makes it all nice and easy is openHAB: http://www.openhab.org/. It has several well-documented installation options (from manual installation over apt repositories up to ready-to-use RPi images) and a large community were you will get any help you need.

And you can of course install your additional or update existing bundles in there. I.e. if you want to start with development, this still is an option (and of course the IDE also contains a launch config where you get everything you need in order to run all that within the IDE for debugging etc). 

So, depending on what you're at, there is an easy way to get your smarthome running, or the "harder" way when you want to put all pieces of the puzzle together yourself.

In any way, there won't be a ready-to-use product falling out at the end of the build of this project. Therefore IMHO it is safe to say that _building_ on LINUX/ARM simply is not supported (while running of course is).
