### ISSUE TITLE
Class loading issues with JSR-223 Groovy ScriptEngine

### ISSUE THREAD

**Issue by wborn** [eclipse/smarthome#3785]
It looks like the classes from `org.eclipse.smarthome.automation.module.script.rulesupport.shared.simple` are not on the classpath of the GroovyScriptEngine because importing or extending `SimpleRule` results in class loading issues.

To reproduce:
1. Download https://dl.bintray.com/groovy/maven/apache-groovy-binary-2.4.12.zip
2. Extract  `/groovy-2.4.12/lib/groovy*.jar` to `/runtime/lib/ext`
3. Start runtime and install Rule Engine (Experimental) (Paper UI -> Add-ons -> Misc)
4. Add test.groovy file to `/conf/automation/jsr223` with the following contents:

```
import org.eclipse.smarthome.automation.*
import org.eclipse.smarthome.automation.module.script.rulesupport.shared.simple.*

scriptExtension.importPreset("RuleSupport")
scriptExtension.importPreset("RuleSimple")


class TestRule extends SimpleRule {
    Object execute(Action module, Map<String, ?> inputs) {
        println("testRule.execute()")
    }
}

def rule = new TestRule()

automationManager.addRule(rule)
```

The engine loads the script but the logging now shows:

```
10:23:41.258 [INFO ] [rt.internal.loader.ScriptFileWatcher] - Loading script 'test.groovy'
10:23:41.267 [ERROR] [ipt.internal.ScriptEngineManagerImpl] - Error during evaluation of script 'file:/etc/openhab2/automation/jsr223/test.groovy': org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
Script21.groovy: 8: unable to resolve class SimpleRule 
 @ line 8, column 1.
   class TestRule extends SimpleRule {
   ^

1 error
```

----

It looks like other packages are on the Groovy classpath because it is possible to add a rule via Groovy without using the `SimpleRule` e.g.:

```
import org.eclipse.smarthome.automation.*

scriptExtension.importPreset("RuleSupport")
scriptExtension.importPreset("RuleSimple")


class TestRule extends Rule {
}

def rule = new TestRule()

automationManager.addRule(rule)
```

**Comment by sjka** [comment]
@smerschjohann do you happen to find some time to look into this?

**Comment by thucke** [comment]
I did a short test:
Fetched the jar-File from the distribution and put it into another directory which I knew is in the CP.
Restartet OH and see .... the class could be successfully imported into my Groovy script.
I tend to assume an issue in the OSGI config for this class.

**Comment by kaikreuzer** [comment]
@wborn Did you set the OSGi parameter `-Dorg.osgi.framework.bundle.parent=ext ` as explained [here](https://github.com/eclipse/smarthome/wiki/Scripted-Rule-Support#install-in-ide)? Afair, this solved exactly such a problem for me (and yes, I am still waiting for @smerschjohann to contribute some documentation to the JSR223 support :-)).

**Comment by wborn** [comment]
The extra VM parameter does not seem to resolve the issue for me @kaikreuzer. What does fix the issue for me is when I export the package of the `SimpleRule` in the Manifest of `org.eclipse.smarthome.automation.module.script.rulesupport`:

```
Export-Package: org.eclipse.smarthome.automation.module.script.rulesupport.shared.simple
```
Would that be a good solution and should other packages also be exported? E.g. the objects in `org.eclipse.smarthome.automation.module.script.rulesupport.shared.factories`  are also referenced in `RuleSupportScriptExtension`.

With this solution a working `example.groovy` port for the documentation ;-) looks like this:
```groovy
import org.eclipse.smarthome.automation.*
import org.eclipse.smarthome.automation.module.script.rulesupport.shared.simple.*
import org.eclipse.smarthome.config.core.Configuration

scriptExtension.importPreset("RuleSupport")
scriptExtension.importPreset("RuleSimple")

def sRule = new SimpleRule() {
    Object execute(Action module, Map<String, ?> inputs) {
        println("Hello World from Groovy")
    }
}
sRule.setTriggers([new Trigger("aTimerTrigger", "timer.GenericCronTrigger", new Configuration([cronExpression: "0/15 * * * * ?"]))])

automationManager.addRule(sRule)
```

**Comment by kaikreuzer** [comment]
> The extra VM parameter does not seem to resolve the issue for me @kaikreuzer. 

Ok, this was a bad suggestion then.

As the package is not an "internal" one, it should be exported in any case - so if it helps, that's good.
@smerschjohann & @lewie Any further comments from your side? Otherwise I'd say that exporting all mentioned non-internal packages should be the right thing to do.

**Comment by lewie** [comment]
Tested current nightly build with groovy installed as @wborn described with `-Dorg.osgi.framework.bundle.parent=ext` is set.

In JavaScript:
```
'use strict';
se.importPreset("RuleSupport");
se.importPreset("RuleSimple");

print("SimpleRule"+ SimpleRule);
var sRule = new SimpleRule(){
	execute: function( module, input){
		print("################ Line: "+__LINE__+" in sRule");
	}
};
sRule.setTriggers([ new Trigger( "aTimerTrigger",  "timer.GenericCronTrigger", 
	new Configuration({ "cronExpression": "0/15 * * * * ?" }) )
]);
automationManager.addRule(sRule); 
```
works well.

In Groovy, see my comments:

```
import org.eclipse.smarthome.automation.*
import org.eclipse.smarthome.automation.module.script.rulesupport.shared.simple.*
import org.eclipse.smarthome.config.core.Configuration

se.importPreset("RuleSupport")
se.importPreset("RuleSimple")
se.importPreset("RuleFactories")
se.importPreset("default")

println("SimpleRule"+ SimpleRule); //No error, it is found
println("SimpleRuleActionHandler"+ SimpleRuleActionHandler); //Error: No such property: SimpleRuleActionHandler for class: Script3
def sRule;// = new SimpleRule()

/* Error with: unable to resolve class SimpleRule
def sRule = new SimpleRule(){
    Object execute(Action module, Map<String, ?> inputs) {
        println("######################### mySimpleRule.execute()")
    }
}
*/


/* No Error but does not execute
def sRule = new Rule() {
    Object execute(Action module, Map<String, ?> inputs) {
        println("Hello World from Groovy")
    }
}
*/

/* Tried to rebuild the Java SimpleRule class error: "unable to resolve class SimpleRuleActionHandler"
class mySimpleRule extends Rule implements SimpleRuleActionHandler {
    Object execute(Action module, Map<String, ?> inputs) {
        println("######################### mySimpleRule.execute()")
    }
}

def sRule = new mySimpleRule()
*/

sRule.setTriggers([new Trigger("aTimerTrigger", "timer.GenericCronTrigger", new Configuration([cronExpression: "0/15 * * * * ?"]))])

automationManager.addRule(sRule)
```

It is hard for me to test with the current build. There is still a bug to remove/re-registering scripts. A script is "registered/provided" well. But when a rule is changed/commented and the file is saved: A null pointer prevents the deletion, with the result the Script is re-registered as an new one. The old orphaned scripts continue running until openHAB is terminated. @kaikreuzer, @smerschjohann, @steve-bate, have I overlooked in the discussion possibly a mechanism to initialize scripts more clean?


```
7:38:45.003 [INFO ] [smarthome.event.RuleStatusInfoEvent ] - rule_1 updated: RUNNING
17:38:45.004 [INFO ] [smarthome.event.RuleStatusInfoEvent ] - rule_3 updated: RUNNING
17:38:45.004 [INFO ] [smarthome.event.RuleStatusInfoEvent ] - rule_1 updated: IDLE
17:38:45.004 [INFO ] [smarthome.event.RuleStatusInfoEvent ] - rule_2 updated: RUNNING
17:38:45.005 [INFO ] [smarthome.event.RuleStatusInfoEvent ] - rule_4 updated: RUNNING
17:38:45.058 [INFO ] [smarthome.event.RuleStatusInfoEvent ] - rule_3 updated: IDLE
17:38:45.059 [INFO ] [smarthome.event.RuleStatusInfoEvent ] - rule_4 updated: IDLE
17:38:45.064 [INFO ] [smarthome.event.RuleStatusInfoEvent ] - rule_2 updated: IDLE
17:38:51.123 [INFO ] [ort.shared.ScriptedAutomationManager] - removeAll added handlers
17:38:51.124 [WARN ] [ore.common.registry.AbstractRegistry] - Could not remove element: null
java.lang.NullPointerException
        at java.lang.String.replace(String.java:2240)[:1.8.0_131]
        at org.eclipse.smarthome.automation.events.RuleEventFactory.buildTopic(RuleEventFactory.java:167)[181:org.eclipse.smarthome.automation.api:0.9.0.201706270841]
        at org.eclipse.smarthome.automation.events.RuleEventFactory.buildTopic(RuleEventFactory.java:171)[181:org.eclipse.smarthome.automation.api:0.9.0.201706270841]
        at org.eclipse.smarthome.automation.events.RuleEventFactory.createRuleRemovedEvent(RuleEventFactory.java:146)[181:org.eclipse.smarthome.automation.api:0.9.0.201706270841]
        at org.eclipse.smarthome.automation.core.internal.RuleRegistryImpl.postRuleRemovedEvent(RuleRegistryImpl.java:303)[183:org.eclipse.smarthome.automation.core:0.9.0.201706270841]
        at org.eclipse.smarthome.automation.core.internal.RuleRegistryImpl.notifyListenersAboutRemovedElement(RuleRegistryImpl.java:365)[183:org.eclipse.smarthome.automation.core:0.9.0.201706270841]
        at org.eclipse.smarthome.automation.core.internal.RuleRegistryImpl.notifyListenersAboutRemovedElement(RuleRegistryImpl.java:1)[183:org.eclipse.smarthome.automation.core:0.9.0.201706270841]
        at org.eclipse.smarthome.core.common.registry.AbstractRegistry.removed(AbstractRegistry.java:157)[98:org.eclipse.smarthome.core:0.9.0.201706270841]
        at org.eclipse.smarthome.automation.module.script.rulesupport.shared.ScriptedRuleProvider.removeRule(ScriptedRuleProvider.java:59)[188:org.eclipse.smarthome.automation.module.script.rulesupport:0.9.0.201706270841]
        at org.eclipse.smarthome.automation.module.script.rulesupport.shared.ScriptedRuleProvider.removeRule(ScriptedRuleProvider.java:54)[188:org.eclipse.smarthome.automation.module.script.rulesupport:0.9.0.201706270841]
        at org.eclipse.smarthome.automation.module.script.rulesupport.shared.RuleSupportRuleRegistryDelegate.removeAllAddedByScript(RuleSupportRuleRegistryDelegate.java:118)[188:org.eclipse.smarthome.automation.module.script.rulesupport:0.9.0.201706270841]
        at org.eclipse.smarthome.automation.module.script.rulesupport.shared.ScriptedAutomationManager.removeAll(ScriptedAutomationManager.java:99)[188:org.eclipse.smarthome.automation.module.script.rulesupport:0.9.0.201706270841]
        at org.eclipse.smarthome.automation.module.script.rulesupport.internal.RuleSupportScriptExtension.unload(RuleSupportScriptExtension.java:197)[188:org.eclipse.smarthome.automation.module.script.rulesupport:0.9.0.201706270841]
        at org.eclipse.smarthome.automation.module.script.internal.ScriptExtensionManager.dispose(ScriptExtensionManager.java:110)[186:org.eclipse.smarthome.automation.module.script:0.9.0.201706270841]
        at org.eclipse.smarthome.automation.module.script.internal.ScriptEngineManagerImpl.removeScriptExtensions(ScriptEngineManagerImpl.java:147)[186:org.eclipse.smarthome.automation.moduleSimpleRule[JavaClass org.eclipse.smarthome.automation.module.script.rulesupport.shared.simple.SimpleRule]
.script:0.9.0.201706270841]
        at org.eclipse.smarthome.automation.module.script.internal.ScriptEngineManagerImpl.removeEngine(ScriptEngineManagerImpl.java:141)[186:org.eclipse.smarthome.automation.module.script:0.9.0.201706270841]
        at org.eclipse.smarthome.automation.module.script.rulesupport.internal.loader.ScriptFileWatcher.removeFile(ScriptFileWatcher.java:133)[188:org.eclipse.smarthome.automation.module.script.rulesupport:0.9.0.201706270841]
        at org.eclipse.smarthome.automation.module.script.rulesupport.internal.loader.ScriptFileWatcher.importFile(ScriptFileWatcher.java:140)[188:org.eclipse.smarthome.automation.module.script.rulesupport:0.9.0.201706270841]
        at org.eclipse.smarthome.automation.module.script.rulesupport.internal.loader.ScriptFileWatcher.processWatchEvent(ScriptFileWatcher.java:123)[188:org.eclipse.smarthome.automation.module.script.rulesupport:0.9.0.201706270841]
        at org.eclipse.smarthome.core.service.WatchQueueReader.run(WatchQueueReader.java:206)[98:org.eclipse.smarthome.core:0.9.0.201706270841]
        at java.lang.Thread.run(Thread.java:748)[:1.8.0_131]
17:38:51.125 [INFO ] [rt.internal.loader.ScriptFileWatcher] - Loading script 'SimpleRule.js'
17:38:51.256 [INFO ] [smarthome.event.RuleAddedEvent      ] - Rule 'rule_5' has been added.
17:38:51.257 [INFO ] [smarthome.event.RuleStatusInfoEvent ] - rule_5 updated: INITIALIZING
```

**Comment by steve-bate** [comment]
There is a related pull request #3773 that was recently merged, but I didn't know about it until now so I haven't tried it yet in my local environment. Have you pulled that change already?

**Comment by steve-bate** [comment]
@lewie Did you try the change from #3773? I've tried it and it seems to work (thanks @smerschjohann).

**Comment by wborn** [comment]
There's now a PR #3819 with the proposed fix. :-)

**Comment by lewie** [comment]
@wborn, should your script really work with PR #3819?

```groovy
import org.eclipse.smarthome.automation.*
import org.eclipse.smarthome.automation.module.script.rulesupport.shared.simple.*
import org.eclipse.smarthome.config.core.Configuration

scriptExtension.importPreset("RuleSupport")
scriptExtension.importPreset("RuleSimple")

def sRule = new SimpleRule(){
    Object execute(Action module, Map<String, ?> inputs) {
        println("Hello World from Groovy")
    }
}
sRule.setTriggers([new Trigger("aTimerTrigger", "timer.GenericCronTrigger", new Configuration([cronExpression: "0/15 * * * * ?"]))])

automationManager.addRule(sRule)
```

I still get this error:
```
13:59:51.765 [ERROR] [ipt.internal.ScriptEngineManagerImpl] - Error during evaluation of script 'file:test3.groovy': org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
Script42.groovy: 8: unable to resolve class SimpleRule
 @ line 8, column 29.
   def sRule = new SimpleRule(){
                               ^

1 error
```
