### ISSUE TITLE
NullPointerException when updating contents of sitemap

### ISSUE THREAD

**Issue by mhilbush** [eclipse/smarthome#3820]
I see this NPE when I edit the contents of my sitemap file.
```
2017-07-09 08:35:52.874 [ERROR] [.core.internal.folder.FolderObserver] - Error handling update of file '/opt/openhab2/conf/sitemaps/1410r.sitemap': null.
java.lang.NullPointerException
        at org.eclipse.smarthome.io.rest.sitemap.internal.PageChangeListener.getAllItems(PageChangeListener.java:125)[121:org.eclipse.smarthome.io.rest.sitemap:0.9.0.201706270841]
        at org.eclipse.smarthome.io.rest.sitemap.internal.PageChangeListener.updateItemsAndWidgets(PageChangeListener.java:75)[121:org.eclipse.smarthome.io.rest.sitemap:0.9.0.201706270841]
        at org.eclipse.smarthome.io.rest.sitemap.internal.PageChangeListener.sitemapContentChanged(PageChangeListener.java:217)[121:org.eclipse.smarthome.io.rest.sitemap:0.9.0.201706270841]
        at org.eclipse.smarthome.io.rest.sitemap.SitemapSubscriptionService.modelChanged(SitemapSubscriptionService.java:277)[121:org.eclipse.smarthome.io.rest.sitemap:0.9.0.201706270841]
        at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.notifyListeners(ModelRepositoryImpl.java:286)[126:org.eclipse.smarthome.model.core:0.9.0.201706270841]
        at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.addOrRefreshModel(ModelRepositoryImpl.java:136)[126:org.eclipse.smarthome.model.core:0.9.0.201706270841]
        at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.checkFile(FolderObserver.java:234)[126:org.eclipse.smarthome.model.core:0.9.0.201706270841]
        at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.processWatchEvent(FolderObserver.java:297)[126:org.eclipse.smarthome.model.core:0.9.0.201706270841]
        at org.eclipse.smarthome.core.service.WatchQueueReader.run(WatchQueueReader.java:206)[102:org.eclipse.smarthome.core:0.9.0.201706270841]
        at java.lang.Thread.run(Thread.java:748)[:1.8.0_131]
```
Here's what I've been able to determine so far:

- If I edit the sitemap file (using vi) when ssh'ed into my openhab box, the exception DOES NOT occur.  In the log I see this:
```
2017-07-09 08:49:04.147 [INFO ] [el.core.internal.ModelRepositoryImpl] - Loading model '1410r.sitemap'
2017-07-09 08:49:04.207 [INFO ] [el.core.internal.ModelRepositoryImpl] - Refreshing model '1410r.sitemap'
2017-07-09 08:49:04.265 [INFO ] [el.core.internal.ModelRepositoryImpl] - Refreshing model '1410r.sitemap'
```

- If I edit the sitemap file (using notepad++ and VS Code) from another box where the file is exposed through a Samba share, the exception DOES occur.  In the log I see this:
```
2017-07-09 08:50:23.768 [INFO ] [el.core.internal.ModelRepositoryImpl] - Refreshing model '1410r.sitemap'
2017-07-09 08:50:23.769 [WARN ] [el.core.internal.ModelRepositoryImpl] - Configuration model '1410r.sitemap' is either empty or cannot be parsed correctly!
2017-07-09 08:50:23.770 [ERROR] [.core.internal.folder.FolderObserver] - Error handling update of file '/opt/openhab2/conf/sitemaps/1410r.sitemap': null.
java.lang.NullPointerException
        at org.eclipse.smarthome.io.rest.sitemap.internal.PageChangeListener.getAllItems(PageChangeListener.java:125)[121:org.eclipse.smarthome.io.rest.sitemap:0.9.0.201706270841]
        at org.eclipse.smarthome.io.rest.sitemap.internal.PageChangeListener.updateItemsAndWidgets(PageChangeListener.java:75)[121:org.eclipse.smarthome.io.rest.sitemap:0.9.0.201706270841]
        at org.eclipse.smarthome.io.rest.sitemap.internal.PageChangeListener.sitemapContentChanged(PageChangeListener.java:217)[121:org.eclipse.smarthome.io.rest.sitemap:0.9.0.201706270841]
        at org.eclipse.smarthome.io.rest.sitemap.SitemapSubscriptionService.modelChanged(SitemapSubscriptionService.java:277)[121:org.eclipse.smarthome.io.rest.sitemap:0.9.0.201706270841]
        at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.notifyListeners(ModelRepositoryImpl.java:286)[126:org.eclipse.smarthome.model.core:0.9.0.201706270841]
        at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.addOrRefreshModel(ModelRepositoryImpl.java:136)[126:org.eclipse.smarthome.model.core:0.9.0.201706270841]
        at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.checkFile(FolderObserver.java:234)[126:org.eclipse.smarthome.model.core:0.9.0.201706270841]
        at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.processWatchEvent(FolderObserver.java:297)[126:org.eclipse.smarthome.model.core:0.9.0.201706270841]
        at org.eclipse.smarthome.core.service.WatchQueueReader.run(WatchQueueReader.java:206)[102:org.eclipse.smarthome.core:0.9.0.201706270841]
        at java.lang.Thread.run(Thread.java:748)[:1.8.0_131]
2017-07-09 08:50:23.909 [WARN ] [el.core.internal.ModelRepositoryImpl] - Configuration model '1410r.sitemap' has errors, therefore ignoring it: [627,134]: mismatched input '<EOF>' expecting '}'

2017-07-09 08:50:23.931 [WARN ] [el.core.internal.ModelRepositoryImpl] - Configuration model '1410r.sitemap' has errors, therefore ignoring it: [627,134]: mismatched input '<EOF>' expecting '}'

2017-07-09 08:50:23.971 [INFO ] [el.core.internal.ModelRepositoryImpl] - Loading model '1410r.sitemap'
2017-07-09 08:50:24.112 [INFO ] [el.core.internal.ModelRepositoryImpl] - Refreshing model '1410r.sitemap'
```

Using inotifywait on the conf/sitemaps directory, I can see that the file is updated differently depending on whether it's edited locally versus through samba.  I suppose this difference is what's causing the issue.

**Comment by neupertd** [comment]
Same Issue on edit with Eclipse-Smart-Home-Designer
No Different between NFS and Samba on W10

`
ava.lang.NullPointerException
        at org.eclipse.smarthome.io.rest.sitemap.internal.PageChangeListener.getAllItems(PageChangeListener.java:125)[117:org.eclipse.smarthome.io.rest.sitemap:0.9.0.b5]
        at org.eclipse.smarthome.io.rest.sitemap.internal.PageChangeListener.updateItemsAndWidgets(PageChangeListener.java:75)[117:org.eclipse.smarthome.io.rest.sitemap:0.9.0.b5]
        at org.eclipse.smarthome.io.rest.sitemap.internal.PageChangeListener.sitemapContentChanged(PageChangeListener.java:217)[117:org.eclipse.smarthome.io.rest.sitemap:0.9.0.b5]
        at org.eclipse.smarthome.io.rest.sitemap.SitemapSubscriptionService.modelChanged(SitemapSubscriptionService.java:277)[117:org.eclipse.smarthome.io.rest.sitemap:0.9.0.b5]
        at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.notifyListeners(ModelRepositoryImpl.java:286)[122:org.eclipse.smarthome.model.core:0.9.0.b5]
        at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.addOrRefreshModel(ModelRepositoryImpl.java:136)[122:org.eclipse.smarthome.model.core:0.9.0.b5]
        at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.checkFile(FolderObserver.java:234)[122:org.eclipse.smarthome.model.core:0.9.0.b5]
        at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.processWatchEvent(FolderObserver.java:297)[122:org.eclipse.smarthome.model.core:0.9.0.b5]
        at org.eclipse.smarthome.core.service.WatchQueueReader.run(WatchQueueReader.java:206)[98:org.eclipse.smarthome.core:0.9.0.b5]
        at java.lang.Thread.run(Thread.java:745)[:1.8.0_121]
`

**Comment by sjka** [comment]
The problem with the remote access apparently is that the files get changed multiple times under the hood, being empty for a (very short) moment. And then the sitemap subscription service runs into this bug. There needs to be an active subscription (i.e. basic UI opened), but then you can also reproduce it locally by emptying a sitemap file.
#3834 is gonna fix it.
