### ISSUE TITLE
Test failure(s): JSonStorageTest failed

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#3854]
Full log: https://travis-ci.org/eclipse/smarthome/builds/255223132?utm_source=github_status&utm_medium=notification

```text
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.eclipse.smarthome.storage.json.JSonStorageTest
Tests run: 5, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.182 sec <<< FAILURE! - in org.eclipse.smarthome.storage.json.JSonStorageTest
testIntegerScale_fromCache(org.eclipse.smarthome.storage.json.JSonStorageTest)  Time elapsed: 0.052 sec
allInsertedNumbersAreLoadedAsBigDecimal_fromCache(org.eclipse.smarthome.storage.json.JSonStorageTest)  Time elapsed: 0.003 sec
testStableOutput(org.eclipse.smarthome.storage.json.JSonStorageTest)  Time elapsed: 0.081 sec
allInsertedNumbersAreLoadedAsBigDecimal_fromDisk(org.eclipse.smarthome.storage.json.JSonStorageTest)  Time elapsed: 0.005 sec  <<< ERROR!
java.lang.NullPointerException: null
	at org.eclipse.smarthome.storage.json.JSonStorageTest$DummyObject.access$0(JSonStorageTest.java:120)
	at org.eclipse.smarthome.storage.json.JSonStorageTest.allInsertedNumbersAreLoadedAsBigDecimal_fromDisk(JSonStorageTest.java:67)
testIntegerScale_fromDisk(org.eclipse.smarthome.storage.json.JSonStorageTest)  Time elapsed: 0.003 sec  <<< ERROR!
java.lang.NullPointerException: null
	at org.eclipse.smarthome.storage.json.JSonStorageTest$DummyObject.access$0(JSonStorageTest.java:120)
	at org.eclipse.smarthome.storage.json.JSonStorageTest.testIntegerScale_fromDisk(JSonStorageTest.java:95)
Running org.eclipse.smarthome.storage.json.JsonStorageServiceOSGiTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.021 sec - in org.eclipse.smarthome.storage.json.JsonStorageServiceOSGiTest
testSerialization(org.eclipse.smarthome.storage.json.JsonStorageServiceOSGiTest)  Time elapsed: 0.01 sec
testClassloader(org.eclipse.smarthome.storage.json.JsonStorageServiceOSGiTest)  Time elapsed: 0.004 sec
testConfiguration(org.eclipse.smarthome.storage.json.JsonStorageServiceOSGiTest)  Time elapsed: 0.002 sec
testOverride(org.eclipse.smarthome.storage.json.JsonStorageServiceOSGiTest)  Time elapsed: 0.002 sec
Results :
Tests in error: 
  JSonStorageTest.allInsertedNumbersAreLoadedAsBigDecimal_fromDisk:67 » NullPointer
  JSonStorageTest.testIntegerScale_fromDisk:95 » NullPointer
Tests run: 9, Failures: 0, Errors: 2, Skipped: 0
```

**Comment by maggu2810** [comment]
Another one:
https://travis-ci.org/eclipse/smarthome/builds/255194360?utm_source=github_status&utm_medium=notification

**Comment by sjka** [comment]
Boah, that sucks: It is...

1. writing the content of the database to a file (inside a try-with block, i.e. it is closing it)
2. writing the backup file (i.e. spending some additional time)
3. trying to read the first file

As it seems, the file system is somehow strange, i.e. consistent only with a delay. I hate cloud...
