### ISSUE TITLE
Harmony binding - not authenticated

### ISSUE THREAD

**Issue by chimeranzl** [eclipse/smarthome#3864]
Latest binding as of yesterday... (also tested deleting cache and tmp, restarting OH to allow it to update) 

openhab> bundle:list | grep HarmonyHub
187 | Active | 80 | 2.2.0.201707190537 | HarmonyHub Binding

On startup of OH, generates an error mentioning "not-authenticated"...

2017-07-20 19:31:20.995 [WARN ] [oftware.smack.AbstractXMPPConnection] - Connection HarmonyXMPPTCPConnection[not-authenticated] (1) closed with error
java.io.EOFException: no more data available - expected end tag </stream:stream> to close start tag <stream:stream> from line 1, parser stopped on END_TAG seen ...</mechanisms></stream:features>... @1:307
        at org.xmlpull.mxp1.MXParser.fillBuf(MXParser.java:3035)[187:org.openhab.binding.harmonyhub:2.2.0.201707190537]
        at org.xmlpull.mxp1.MXParser.more(MXParser.java:3046)[187:org.openhab.binding.harmonyhub:2.2.0.201707190537]
        at org.xmlpull.mxp1.MXParser.nextImpl(MXParser.java:1144)[187:org.openhab.binding.harmonyhub:2.2.0.201707190537]
        at org.xmlpull.mxp1.MXParser.next(MXParser.java:1093)[187:org.openhab.binding.harmonyhub:2.2.0.201707190537]
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1228)[187:org.openhab.binding.harmonyhub:2.2.0.201707190537]
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:980)[187:org.openhab.binding.harmonyhub:2.2.0.201707190537]
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:996)[187:org.openhab.binding.harmonyhub:2.2.0.201707190537]
        at java.lang.Thread.run(Thread.java:748)[:1.8.0_131]

**Comment by kaikreuzer** [comment]
Sorry, this does not seem to be ESH related. Please report as a bug in the binding at https://github.com/openhab/openhab2-addons/issues.
