### ISSUE TITLE
OpenHAB stop running with a Visu

### ISSUE THREAD

**Issue by pirndi** [eclipse/smarthome#3875]
Hello!

If i start a Visu on my Wall Tablet (Basic UI or HabPanel) OH crash down after one Day
My Log:
2017-07-17 11:39:31.782 [WARN ] [eclipse.jetty.server.ServerConnector] - 
java.io.IOException: Zu viele offene Dateien
	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)[:1.8.0_131]
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422)[:1.8.0_131]
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)[:1.8.0_131]
	at org.eclipse.jetty.server.ServerConnector.accept(ServerConnector.java:377)[80:org.eclipse.jetty.server:9.2.19.v20160908]
	at org.eclipse.jetty.server.AbstractConnector$Acceptor.run(AbstractConnector.java:500)[80:org.eclipse.jetty.server:9.2.19.v20160908]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)[83:org.eclipse.jetty.util:9.2.19.v20160908]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)[83:org.eclipse.jetty.util:9.2.19.v20160908]
	at java.lang.Thread.run(Thread.java:748)[:1.8.0_131]

I Get 10 Log files and OH stop working

**Comment by kaikreuzer** [comment]
Please check for help at https://community.openhab.org/ - this is most likely no bug in ESH.
