### ISSUE TITLE
Regression: MQTT transport broken - again

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#3949]
The issue #3856 that has been fixed by #3857 is now present again.
It seems the fix has been reverted by #3835.

**Comment by maggu2810** [comment]
@davidgraeff: What's the reason for the removal of javax.naming: https://github.com/eclipse/smarthome/pull/3835/files#diff-14f7b6770342b2fe60be508b7ee9cbc5L9

**Comment by maggu2810** [comment]
And another one caused ba the removal of the `javax.net` import

```
java.lang.NoClassDefFoundError: javax/net/SocketFactory
	at org.eclipse.smarthome.io.transport.mqtt.MqttService.addBrokerConnection(MqttService.java:222) ~[?:?]
	at org.eclipse.smarthome.io.transport.mqtt.MqttService.updated(MqttService.java:110) ~[?:?]
	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updated(ManagedServiceTracker.java:189) ~[7:org.apache.felix.configadmin:1.8.14]
	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updateService(ManagedServiceTracker.java:152) [7:org.apache.felix.configadmin:1.8.14]
	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.provideConfiguration(ManagedServiceTracker.java:85) [7:org.apache.felix.configadmin:1.8.14]
	at org.apache.felix.cm.impl.ConfigurationManager$UpdateConfiguration.run(ConfigurationManager.java:1776) [7:org.apache.felix.configadmin:1.8.14]
	at org.apache.felix.cm.impl.UpdateThread.run0(UpdateThread.java:141) [7:org.apache.felix.configadmin:1.8.14]
	at org.apache.felix.cm.impl.UpdateThread.run(UpdateThread.java:109) [7:org.apache.felix.configadmin:1.8.14]
	at java.lang.Thread.run(Thread.java:748) [?:?]
Caused by: java.lang.ClassNotFoundException: javax.net.SocketFactory not found by org.eclipse.smarthome.io.transport.mqtt [206]
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1550) ~[?:?]
	at org.apache.felix.framework.BundleWiringImpl.access$200(BundleWiringImpl.java:79) ~[?:?]
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1958) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:?]
	... 9 more
```

**Comment by davidgraeff** [comment]
@maggu2810 must have been a rebase conflict that I resolved in a wrong way. Because I test locally before pushing, it must have worked on my side but my eclipse installation is confused anyway I guess.
