### ISSUE TITLE
Maven build failing in Eclipse SmartHome Core Tests

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#3952]
With the current master branch on a Windows 10 Pro 64 bits, a "mvn clean install" is failing in Eclipse SmartHome Core Tests with the following errors:
```
Running org.eclipse.smarthome.core.service.AbstractWatchServiceTest
Tests run: 8, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 51.021 sec <<< FAILURE! - in org.eclipse.smarthome.core.service.AbstractWatchServiceTest
AbstractWatchQueueReader processWatchEvent path in subsubdir provided with correct arguments(org.eclipse.smarthome.core.service.AbstractWatchServiceTest)  Time elapsed: 0.625 sec
subdirs are registered and modifications are watched(org.eclipse.smarthome.core.service.AbstractWatchServiceTest)  Time elapsed: 30.081 sec  <<< FAILURE!
java.lang.AssertionError: Exactly 2 watch events were expected, but were: [Watch Event: count 1; kind: ENTRY_CREATE; path: watchDirectory\correctlyWatchedSubDir\correctSubDirInnerFile]
Expected: is <2>
     but: was <1>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.junit.Assert.assertThat(Assert.java:865)
        at org.junit.Assert$assertThat$3.callStatic(Unknown Source)
        at org.eclipse.smarthome.core.service.AbstractWatchServiceTest$_assertAllEventsAreProcessed_closure9.doCall(AbstractWatchServiceTest.groovy:254)
        at org.eclipse.smarthome.core.service.AbstractWatchServiceTest$_assertAllEventsAreProcessed_closure9.doCall(AbstractWatchServiceTest.groovy)
        at sun.reflect.GeneratedMethodAccessor43.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:278)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
        at org.eclipse.smarthome.test.OSGiTest.waitForAssert(OSGiTest.groovy:220)
        at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrap.invoke(PogoMetaMethodSite.java:187)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:56)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:61)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:153)
        at org.eclipse.smarthome.test.OSGiTest.waitForAssert(OSGiTest.groovy:191)
        at org.eclipse.smarthome.test.OSGiTest.waitForAssert(OSGiTest.groovy)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:207)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:56)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:145)
        at org.eclipse.smarthome.core.service.AbstractWatchServiceTest.assertAllEventsAreProcessed(AbstractWatchServiceTest.groovy:254)

AbstractWatchQueueReader processWatchEvent path in root provided with correct arguments(org.eclipse.smarthome.core.service.AbstractWatchServiceTest)  Time elapsed: 0.578 sec
same file names in root and subdir are correctly processed(org.eclipse.smarthome.core.service.AbstractWatchServiceTest)  Time elapsed: 3.001 sec
AbstractWatchQueueReader processWatchEvent path in subdir provided with correct arguments(org.eclipse.smarthome.core.service.AbstractWatchServiceTest)  Time elapsed: 0.64 sec
subdirs are not registered, but dirs modifications are watched(org.eclipse.smarthome.core.service.AbstractWatchServiceTest)  Time elapsed: 10.064 sec  <<< FAILURE!
java.lang.AssertionError: Exactly 1 watch events were expected, but were: []
Expected: is <1>
     but: was <0>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.junit.Assert.assertThat(Assert.java:865)
        at org.junit.Assert$assertThat$3.callStatic(Unknown Source)
        at org.eclipse.smarthome.core.service.AbstractWatchServiceTest$_assertDirectoryModifyEventIsProcessed_closure12.doCall(AbstractWatchServiceTest.groovy:300)
        at org.eclipse.smarthome.core.service.AbstractWatchServiceTest$_assertDirectoryModifyEventIsProcessed_closure12.doCall(AbstractWatchServiceTest.groovy)
        at sun.reflect.GeneratedMethodAccessor47.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:278)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:54)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
        at org.eclipse.smarthome.test.OSGiTest.waitForAssert(OSGiTest.groovy:220)
        at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrap.invoke(PogoMetaMethodSite.java:187)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:56)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:61)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:153)
        at org.eclipse.smarthome.test.OSGiTest.waitForAssert(OSGiTest.groovy:191)
        at org.eclipse.smarthome.test.OSGiTest.waitForAssert(OSGiTest.groovy)
        at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:207)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:56)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:141)
        at org.eclipse.smarthome.core.service.AbstractWatchServiceTest.assertDirectoryModifyEventIsProcessed(AbstractWatchServiceTest.groovy:300)

subdirs are not registered and modifications are not watched(org.eclipse.smarthome.core.service.AbstractWatchServiceTest)  Time elapsed: 3 sec
subdirs are registered, but dirs modifications are not watched(org.eclipse.smarthome.core.service.AbstractWatchServiceTest)  Time elapsed: 3.016 sec
Running org.eclipse.smarthome.core.storage.ManagedItemProviderOSGiTest
Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.078 sec - in org.eclipse.smarthome.core.storage.ManagedItemProviderOSGiTest
assert two items with same name can not be added(org.eclipse.smarthome.core.storage.ManagedItemProviderOSGiTest)  Time elapsed: 0.015 sec
assert items are there once the factory gets added(org.eclipse.smarthome.core.storage.ManagedItemProviderOSGiTest)  Time elapsed: 0.016 sec
assert items are added as group members on deferred creation(org.eclipse.smarthome.core.storage.ManagedItemProviderOSGiTest)  Time elapsed: 0.016 sec
assert group functions are stored and retrieved as well(org.eclipse.smarthome.core.storage.ManagedItemProviderOSGiTest)  Time elapsed: 0 sec
assert getItems returns item from registered ManagedItemProvider(org.eclipse.smarthome.core.storage.ManagedItemProviderOSGiTest)  Time elapsed: 0 sec
assert removal returns old value(org.eclipse.smarthome.core.storage.ManagedItemProviderOSGiTest)  Time elapsed: 0 sec
assert tags are stored and retrieve as well(org.eclipse.smarthome.core.storage.ManagedItemProviderOSGiTest)  Time elapsed: 0 sec
updating existing item returns old value(org.eclipse.smarthome.core.storage.ManagedItemProviderOSGiTest)  Time elapsed: 0 sec
assert remove recursively works(org.eclipse.smarthome.core.storage.ManagedItemProviderOSGiTest)  Time elapsed: 0.015 sec
assert functions are stored and retrieved as well(org.eclipse.smarthome.core.storage.ManagedItemProviderOSGiTest)  Time elapsed: 0 sec

Results :

Failed tests:
  AbstractWatchServiceTest.subdirs are registered and modifications are watched:164->assertAllEventsAreProcessed:254->OSGiTest.waitForAssert:-1->OSGiTest.waitForAssert:191->OSGiTest.waitForAssert:220 Exactly 2 watch events were expected, but were: [Watch Event: count 1; kind: ENTRY_CREATE; path: watchDirectory\correctlyWatchedSubDir\correctSubDirInnerFile]
Expected: is <2>
     but: was <1>
  AbstractWatchServiceTest.subdirs are not registered, but dirs modifications are watched:234->assertDirectoryModifyEventIsProcessed:300->OSGiTest.waitForAssert:-1->OSGiTest.waitForAssert:191->OSGiTest.waitForAssert:220 Exactly 1 watch events were expected, but were: []
Expected: is <1>
     but: was <0>

Tests run: 289, Failures: 2, Errors: 0, Skipped: 1
```

**Comment by J-N-K** [comment]
I have seen one of these (or another of the watchService tests) failing yesterday. This stopped after I closed Eclipse, SourceTree and the gitShell. After that this never failed again.

**Comment by lolodomo** [comment]
If I close my Eclipse and my Git console, then run "mvn clean install" in a Windows PowerShell, I got the same errors.

**Comment by lolodomo** [comment]
Any other advice for this issue ?

**Comment by maggu2810** [comment]
@lolodomo Sorry, I have no time to test it this week.
Perhaps I can give it a try next week.

**Comment by kaikreuzer** [comment]
Afaik, this has been fixed by now.

**Comment by lolodomo** [comment]
I cannot confirm because it is now failing earlier in the build process in Eclipse SmartHome Configuration Dispatcher Tests !
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest
Tests run: 27, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 30.05 sec <<< FAILURE! - in org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest
allConfigurationFilesWithGlobalPIDsAreProcessedAndConfigurationIsUpdated(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 1.063 sec
whenExclusivePIDFileIsDeleted_DeleteTheConfiguration(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.563 sec
propertiesForTheSameGlobalPIDInDifferentFilesMustBeOverriddenInTheOrderTheyWereLastModified(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.906 sec
ifThereIsNoPropertyValuePairForGlobalPIDAConfigurationWithTheGivenPIDWillNotExist(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.5 sec
valueIsStillValidIfItIsLeftEmpty(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.641 sec
PropertyValuePairsForALocalPIDInDifferentFilesAreStillAssociatedWithThatPID(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.687 sec
allConfigurationFilesWithLocalPIDsAreProcessedAndConfigurationIsUpdated(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.735 sec
propertiesForLocalPIDCanBeOverridden(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.609 sec
whenExclusivePIDisDefinedInlineFromDifferentFile_skipTheLine(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.516 sec
IfNoPIDIsDefinedInConfigurationFileWithNo_dotNameTheDefaultNamespacePlusTheFileNameBecomesPID(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.594 sec
localPIDIsOverriddenByGlobalPIDInDifferentFileIfTheFileWithTheGlobalOneIsModifiedLast(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.719 sec
whenPropertyValuePairsForAGlobalPIDAreInDifferentFilesPropertiesWillNotBeMerged(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.61 sec
whenTheConfigurationFileNameContainsDotAndNoPIDIsDefinedTheFileNameBecomesPID(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.703 sec
whenLocalPIDIsDefinedForGlobalPIDFile_AbortParsing(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.515 sec
whenLocalPIDIsAnEmptyStringTheDefaultNamespacePlusDotIsTheOverallPID(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.938 sec
ifPropertyIsLeftEmptyAConfigurationWithTheGivenPIDWillNotExist(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.469 sec
whenLocalPIDDoesNotContainDotTheDefaultNamespacePlusThatPIDIsTheOverallPID(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.797 sec
whenExclusiveConfigFileIsDeleted_shouldRemoveConfigFromConfigAdmin(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 13.064 sec  <<< FAILURE!
java.lang.AssertionError: The configuration with properties for the given pid was found but should have been removed.
Expected: is null
     but: was <org.eclipse.equinox.internal.cm.ConfigurationDictionary@babafc2>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest.lambda$1(ConfigDispatcherOSGiTest.java:587)

propertiesForTheSameLocalPIDInDifferentFilesMustBeOverriddenInTheOrderTheyWereLastModified(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.656 sec
ifThePropertyIsNotPrefixedWithLocalPIDTheLastPIDBecomesPIDForThatProperty(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.828 sec
ifThePropertyValuePairIsPrefixedWithLocalPIDInTheSameFileTheGlobalPIDIsIgnored(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.61 sec
commentLinesAreNotProcessed(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.453 sec
whenGlobalPIDIsEmptyStringItRemainsAnEmptyString(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.531 sec
propertiesForPIDInFilesInServicesDirectoryMustOverrideDefaultProperties(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.641 sec
globalPIDIsOverriddenByLocalPIDInDifferentFileIfTheFileWithTheLocalOneIsModifiedLast(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.531 sec
txtFilesAreNotProcessed(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.516 sec
whenExclusiveConfigIsTruncated_OverrideReducedConfig(org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest)  Time elapsed: 0.609 sec

Results :

Failed tests:
  ConfigDispatcherOSGiTest.whenExclusiveConfigFileIsDeleted_shouldRemoveConfigFromConfigAdmin:581->JavaTest.waitForAssert:64->JavaTest.waitForAssert:111->JavaTest.waitForAssert:143->lambda$1:587 The configuration with properties for the given pid was found but should have been removed.
Expected: is null
     but: was <org.eclipse.equinox.internal.cm.ConfigurationDictionary@babafc2>

Tests run: 27, Failures: 1, Errors: 0, Skipped: 0
```

**Comment by sjka** [comment]
> Afaik, this has been fixed by now.

Nope - it's [still](https://github.com/eclipse/smarthome/commits/9aeae79edebd82283b812ffb41fdcf19f6f4d88e) there:

```
AbstractWatchQueueReader processWatchEvent path in subsubdir provided with correct arguments(org.eclipse.smarthome.core.service.AbstractWatchServiceTest)  Time elapsed: 0.657 sec
subdirs are registered and modifications are watched(org.eclipse.smarthome.core.service.AbstractWatchServiceTest)  Time elapsed: 30.04 sec  <<< FAILURE!
java.lang.AssertionError: Exactly 2 watch events were expected, but were: [Watch Event: count 1; kind: ENTRY_CREATE; path: watchDirectory\correctlyWatchedSubDir\correctSubDirInnerFile]
Expected: is <2>
     but: was <1>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert$assertThat$3.callStatic(Unknown Source)
        at org.eclipse.smarthome.core.service.AbstractWatchServiceTest$_assertAllEventsAreProcessed_closure9.doCall(AbstractWatchServiceTest.groovy:259)
        at org.eclipse.smarthome.core.service.AbstractWatchServiceTest$_assertAllEventsAreProcessed_closure9.doCall(AbstractWatchServiceTest.groovy)
        at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:278)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
        at org.eclipse.smarthome.test.OSGiTest.waitForAssert(OSGiTest.groovy:242)
        at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrap.invoke(PogoMetaMethodSite.java:187)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:56)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:61)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:153)
        at org.eclipse.smarthome.test.OSGiTest.waitForAssert(OSGiTest.groovy:213)
        at org.eclipse.smarthome.test.OSGiTest.waitForAssert(OSGiTest.groovy)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:207)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:56)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:145)
        at org.eclipse.smarthome.core.service.AbstractWatchServiceTest.assertAllEventsAreProcessed(AbstractWatchServiceTest.groovy:259)

AbstractWatchQueueReader processWatchEvent path in root provided with correct arguments(org.eclipse.smarthome.core.service.AbstractWatchServiceTest)  Time elapsed: 0.557 sec
same file names in root and subdir are correctly processed(org.eclipse.smarthome.core.service.AbstractWatchServiceTest)  Time elapsed: 3.023 sec
AbstractWatchQueueReader processWatchEvent path in subdir provided with correct arguments(org.eclipse.smarthome.core.service.AbstractWatchServiceTest)  Time elapsed: 0.561 sec
subdirs are not registered, but dirs modifications are watched(org.eclipse.smarthome.core.service.AbstractWatchServiceTest)  Time elapsed: 10.058 sec  <<< FAILURE!
java.lang.AssertionError: Exactly 1 watch events were expected, but were: []
Expected: is <1>
     but: was <0>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert$assertThat$3.callStatic(Unknown Source)
        at org.eclipse.smarthome.core.service.AbstractWatchServiceTest$_assertDirectoryModifyEventIsProcessed_closure12.doCall(AbstractWatchServiceTest.groovy:305)
        at org.eclipse.smarthome.core.service.AbstractWatchServiceTest$_assertDirectoryModifyEventIsProcessed_closure12.doCall(AbstractWatchServiceTest.groovy)
        at sun.reflect.GeneratedMethodAccessor60.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:278)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:54)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
        at org.eclipse.smarthome.test.OSGiTest.waitForAssert(OSGiTest.groovy:242)
        at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrap.invoke(PogoMetaMethodSite.java:187)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:56)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:61)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:153)
        at org.eclipse.smarthome.test.OSGiTest.waitForAssert(OSGiTest.groovy:213)
        at org.eclipse.smarthome.test.OSGiTest.waitForAssert(OSGiTest.groovy)
        at sun.reflect.GeneratedMethodAccessor12.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:207)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:56)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:141)
        at org.eclipse.smarthome.core.service.AbstractWatchServiceTest.assertDirectoryModifyEventIsProcessed(AbstractWatchServiceTest.groovy:305)

subdirs are not registered and modifications are not watched(org.eclipse.smarthome.core.service.AbstractWatchServiceTest)  Time elapsed: 3.009 sec
subdirs are registered, but dirs modifications are not watched(org.eclipse.smarthome.core.service.AbstractWatchServiceTest)  Time elapsed: 3.015 sec
Running org.eclipse.smarthome.core.storage.ManagedItemProviderOSGiTest
Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.098 sec - in org.eclipse.smarthome.core.storage.ManagedItemProviderOSGiTest
assert two items with same name can not be added(org.eclipse.smarthome.core.storage.ManagedItemProviderOSGiTest)  Time elapsed: 0.017 sec
assert items are there once the factory gets added(org.eclipse.smarthome.core.storage.ManagedItemProviderOSGiTest)  Time elapsed: 0.024 sec
assert items are added as group members on deferred creation(org.eclipse.smarthome.core.storage.ManagedItemProviderOSGiTest)  Time elapsed: 0.01 sec
assert group functions are stored and retrieved as well(org.eclipse.smarthome.core.storage.ManagedItemProviderOSGiTest)  Time elapsed: 0.009 sec
assert getItems returns item from registered ManagedItemProvider(org.eclipse.smarthome.core.storage.ManagedItemProviderOSGiTest)  Time elapsed: 0.002 sec
assert removal returns old value(org.eclipse.smarthome.core.storage.ManagedItemProviderOSGiTest)  Time elapsed: 0.002 sec
assert tags are stored and retrieve as well(org.eclipse.smarthome.core.storage.ManagedItemProviderOSGiTest)  Time elapsed: 0.003 sec
updating existing item returns old value(org.eclipse.smarthome.core.storage.ManagedItemProviderOSGiTest)  Time elapsed: 0.003 sec
assert remove recursively works(org.eclipse.smarthome.core.storage.ManagedItemProviderOSGiTest)  Time elapsed: 0.004 sec
assert functions are stored and retrieved as well(org.eclipse.smarthome.core.storage.ManagedItemProviderOSGiTest)  Time elapsed: 0.006 sec

Results :

Failed tests:
  AbstractWatchServiceTest.subdirs are registered and modifications are watched:169->assertAllEventsAreProcessed:259->OSGiTest.waitForAssert:-1->OSGiTest.waitForAssert:213->OSGiTest.waitForAssert:242 Exactly 2 watch events were expected, but were: [Watch Event: count 1; kind: ENTRY_CREATE; path: watchDirectory\correctlyWatchedSubDir\correctSubDirInnerFile]
Expected: is <2>
     but: was <1>
  AbstractWatchServiceTest.subdirs are not registered, but dirs modifications are watched:239->assertDirectoryModifyEventIsProcessed:305->OSGiTest.waitForAssert:-1->OSGiTest.waitForAssert:213->OSGiTest.waitForAssert:242 Exactly 1 watch events were expected, but were: []
Expected: is <1>
     but: was <0>

Tests run: 361, Failures: 2, Errors: 0, Skipped: 1
```
