### ISSUE TITLE
[Test Failures] Wemo Binding

### ISSUE THREAD

**Issue by sjka** [eclipse/smarthome#4071]
Happend here: https://travis-ci.org/eclipse/smarthome/builds/265218318?utm_source=github_status&utm_medium=notification

```
assert that thing handles OnOff command correctly(org.eclipse.smarthome.binding.wemo.handler.test.WemoHandlerOSGiTest)  Time elapsed: 10.16 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: is <0>
     but: was <1>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:865)
	at org.junit.Assert.assertThat(Assert.java:832)
	at org.junit.Assert$assertThat.callStatic(Unknown Source)
	at org.eclipse.smarthome.binding.wemo.handler.test.WemoHandlerOSGiTest$_removeThing_closure11.doCall(WemoHandlerOSGiTest.groovy:172)
	at org.eclipse.smarthome.binding.wemo.handler.test.WemoHandlerOSGiTest$_removeThing_closure11.doCall(WemoHandlerOSGiTest.groovy)
	at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:278)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at org.eclipse.smarthome.test.OSGiTest.waitForAssert(OSGiTest.groovy:220)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrap.invoke(PogoMetaMethodSite.java:187)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:61)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:153)
	at org.eclipse.smarthome.test.OSGiTest.waitForAssert(OSGiTest.groovy:191)
	at org.eclipse.smarthome.test.OSGiTest.waitForAssert(OSGiTest.groovy)
	at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:207)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:141)
	at org.eclipse.smarthome.binding.wemo.handler.test.WemoHandlerOSGiTest.removeThing(WemoHandlerOSGiTest.groovy:171)
	at org.eclipse.smarthome.binding.wemo.handler.test.WemoHandlerOSGiTest.tearDown(WemoHandlerOSGiTest.groovy:63)
```

**Comment by maggu2810** [comment]
There are also other errors on the Wemo test execution that prevent the Travis CI to do its job:
* https://travis-ci.org/eclipse/smarthome/builds/326858924
* https://travis-ci.org/eclipse/smarthome/builds/326521295
* https://travis-ci.org/eclipse/smarthome/builds/326465095
* https://travis-ci.org/eclipse/smarthome/builds/326388663
* https://travis-ci.org/eclipse/smarthome/builds/326789286
* https://travis-ci.org/eclipse/smarthome/builds/327146591
* https://travis-ci.org/eclipse/smarthome/builds/327215998
* https://travis-ci.org/eclipse/smarthome/builds/327218022

**Comment by sjka** [comment]
@svilenvul as the original author of the tests, may I ask you to have a look please? These tests tend to fail quite often lately (see the the links above).

**Comment by sjka** [comment]
Just for the record - I have `@Ignore` annotated the failing `WemoLinkDiscoveryServiceOSGiTest` with #4889, just to get the builds working again. This issue remains valid nevertheless.
