### ISSUE TITLE
[Sonos] Error when using setpoint for volume in sitemap

### ISSUE THREAD

**Issue by metbril** [eclipse/smarthome#4095]
I use a setpoint for my volume and found that (since openHAB 2.1?) this no longer is working.
As a workaround I can use a slider, that has less finegrained control for me. I am sure that the setpoint has worked with OH2.0, build don't know when it broke.

Running OH2.1 Stable on a RPi3B/openhabian

sonos.items
```
Dimmer Sonos_Living_Volume  "Volume [%.0f %%]" <soundvolume>      (Sonos_Living) { channel="sonos:PLAY1:living:volume" }
```

default.sitemap
```
Slider item=Sonos_Living_Volume
Setpoint item=Sonos_Living_Volume minValue=0 maxValue=100 step=5
```
openhab.log
```
17:14:31.601 [INFO ] [smarthome.event.ItemCommandEvent    ] - Item 'Sonos_Living_Volume' received command 10.0
17:14:31.618 [ERROR] [ome.core.thing.internal.ThingManager] - Exception occurred while calling handler: org.jupnp.model.types.InvalidValueException: Can't convert string to number or not in range: 10.0
java.util.concurrent.ExecutionException: org.jupnp.model.types.InvalidValueException: Can't convert string to number or not in range: 10.0
	at org.eclipse.smarthome.core.common.SafeMethodCaller.executeDirectly(SafeMethodCaller.java:220)[99:org.eclipse.smarthome.core:0.9.0.b5]
	at org.eclipse.smarthome.core.common.SafeMethodCaller.callAsynchronous(SafeMethodCaller.java:189)[99:org.eclipse.smarthome.core:0.9.0.b5]
	at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:83)[99:org.eclipse.smarthome.core:0.9.0.b5]
	at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:67)[99:org.eclipse.smarthome.core:0.9.0.b5]
	at org.eclipse.smarthome.core.thing.internal.ThingManager.receiveCommand(ThingManager.java:374)[106:org.eclipse.smarthome.core.thing:0.9.0.b5]
	at org.eclipse.smarthome.core.items.events.AbstractItemEventSubscriber.receive(AbstractItemEventSubscriber.java:47)[99:org.eclipse.smarthome.core:0.9.0.b5]
	at org.eclipse.smarthome.core.internal.events.OSGiEventManager$1.call(OSGiEventManager.java:192)[99:org.eclipse.smarthome.core:0.9.0.b5]
	at org.eclipse.smarthome.core.internal.events.OSGiEventManager$1.call(OSGiEventManager.java:1)[99:org.eclipse.smarthome.core:0.9.0.b5]
	at org.eclipse.smarthome.core.common.SafeMethodCaller$CallableWrapper.call(SafeMethodCaller.java:181)[99:org.eclipse.smarthome.core:0.9.0.b5]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_121]
Caused by: org.jupnp.model.types.InvalidValueException: Can't convert string to number or not in range: 10.0
	at org.jupnp.model.types.UnsignedIntegerTwoBytesDatatype.valueOf(UnsignedIntegerTwoBytesDatatype.java:27)[163:org.jupnp:2.2.0]
	at org.jupnp.model.types.UnsignedIntegerTwoBytesDatatype.valueOf(UnsignedIntegerTwoBytesDatatype.java:1)[163:org.jupnp:2.2.0]
	at org.jupnp.model.VariableValue.<init>(VariableValue.java:54)[163:org.jupnp:2.2.0]
	at org.jupnp.model.action.ActionArgumentValue.<init>(ActionArgumentValue.java:32)[163:org.jupnp:2.2.0]
	at org.jupnp.model.action.ActionInvocation.setInput(ActionInvocation.java:130)[163:org.jupnp:2.2.0]
	at org.eclipse.smarthome.io.transport.upnp.UpnpIOServiceImpl.invokeAction(UpnpIOServiceImpl.java:296)[184:org.eclipse.smarthome.io.transport.upnp:0.9.0.b5]
	at org.eclipse.smarthome.binding.sonos.handler.ZonePlayerHandler.setVolume(ZonePlayerHandler.java:1406)[183:org.eclipse.smarthome.binding.sonos:0.9.0.b5]
	at org.eclipse.smarthome.binding.sonos.handler.ZonePlayerHandler.setVolumeForGroup(ZonePlayerHandler.java:1422)[183:org.eclipse.smarthome.binding.sonos:0.9.0.b5]
	at org.eclipse.smarthome.binding.sonos.handler.ZonePlayerHandler.handleCommand(ZonePlayerHandler.java:243)[183:org.eclipse.smarthome.binding.sonos:0.9.0.b5]
	at org.eclipse.smarthome.core.thing.internal.ThingManager$4.call(ThingManager.java:377)[106:org.eclipse.smarthome.core.thing:0.9.0.b5]
	at org.eclipse.smarthome.core.thing.internal.ThingManager$4.call(ThingManager.java:1)[106:org.eclipse.smarthome.core.thing:0.9.0.b5]
	at org.eclipse.smarthome.core.common.SafeMethodCaller.executeDirectly(SafeMethodCaller.java:218)[99:org.eclipse.smarthome.core:0.9.0.b5]
	... 12 more
Caused by: java.lang.NumberFormatException: For input string: "10.0"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)[:1.8.0_121]
	at java.lang.Long.parseLong(Long.java:589)[:1.8.0_121]
	at java.lang.Long.parseLong(Long.java:631)[:1.8.0_121]
	at org.jupnp.model.types.UnsignedVariableInteger.<init>(UnsignedVariableInteger.java:62)[163:org.jupnp:2.2.0]
	at org.jupnp.model.types.UnsignedIntegerTwoBytes.<init>(UnsignedIntegerTwoBytes.java:27)[163:org.jupnp:2.2.0]
	at org.jupnp.model.types.UnsignedIntegerTwoBytesDatatype.valueOf(UnsignedIntegerTwoBytesDatatype.java:25)[163:org.jupnp:2.2.0]
	... 23 more
```

**Comment by kaikreuzer** [comment]
That's interesting, because afaics, none of the related code has been touched since 2015...
But the exception speaks for itself.
@lolodomo Would you want to have a look at that (and can you confirm to see the same)?

**Comment by lolodomo** [comment]
@metbril : can you tell us with what UI you have this problem ? All UIs ?

**Comment by metbril** [comment]
@kaikreuzer Perhaps I'm mistaken and hasn't it been working at all. 

I will try multiple UI's and report back asap: basic, classic and iOS.

**Comment by metbril** [comment]
The issue does NOT occur with basic UI.
It DOES occur with both iOS and classic UI.

I noticed that basic ui send this event:

```
Item 'Sonos_Living_Volume' received command 20
```

Both other UIs send

```
Item 'Sonos_Living_Volume' received command 15.0
```

It appears that basic send an integer without decimals and the other send a number with 1 decimal. The latter raises the issue.

**Comment by lolodomo** [comment]
I will fix that, the binding is handling DecimalType value but without any rounding.

**Comment by lolodomo** [comment]
I am not able to reproduce the issue with Classic UI ! Are you sure that the issue is not only with iOS app ?
So I can provide a fix but I will not be able to test it.

**Comment by metbril** [comment]
I was running 2.1 stable at the time and now on 2.2 snaphot. I currently can't see the error with classic ui either. I don't have the means to go back simply, so it might already be fixed in the current snapshot?

**Comment by lolodomo** [comment]
Ok. By the way, I fixed the binding to use an integer even if a decimal value is provided. So it should work in iOS app too.
