### ISSUE TITLE
Cannot notify InboxListener about thing added event.

### ISSUE THREAD

**Issue by mherwege** [eclipse/smarthome#4107]
NPE in a recent build of OH2.

Here is the log:

```
2017-08-22 12:12:59.229 [ERROR] [g.discovery.internal.PersistentInbox] - Cannot notify the InboxListener 'org.eclipse.smarthome.config.discovery.internal.AutomaticInboxProcessor' about a Thing added event!
java.lang.NullPointerException: null
	at org.eclipse.smarthome.config.discovery.internal.AutomaticInboxProcessor.getRepresentationPropertyValueForThing(AutomaticInboxProcessor.java:146) ~[?:?]
	at org.eclipse.smarthome.config.discovery.internal.AutomaticInboxProcessor.lambda$0(AutomaticInboxProcessor.java:85) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) [?:?]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) [?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) [?:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270) [?:?]
	at java.util.concurrent.ConcurrentHashMap$ValueSpliterator.tryAdvance(ConcurrentHashMap.java:3574) [?:?]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) [?:?]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498) [?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485) [?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) [?:?]
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152) [?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) [?:?]
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464) [?:?]
	at org.eclipse.smarthome.config.discovery.internal.AutomaticInboxProcessor.thingAdded(AutomaticInboxProcessor.java:86) [95:org.eclipse.smarthome.config.discovery:0.9.0.201708151402]
	at org.eclipse.smarthome.config.discovery.internal.PersistentInbox.notifyListeners(PersistentInbox.java:429) [95:org.eclipse.smarthome.config.discovery:0.9.0.201708151402]
	at org.eclipse.smarthome.config.discovery.internal.PersistentInbox.add(PersistentInbox.java:175) [95:org.eclipse.smarthome.config.discovery:0.9.0.201708151402]
	at org.eclipse.smarthome.config.discovery.internal.PersistentInbox.thingDiscovered(PersistentInbox.java:311) [95:org.eclipse.smarthome.config.discovery:0.9.0.201708151402]
	at org.eclipse.smarthome.config.discovery.internal.DiscoveryServiceRegistryImpl$2.run(DiscoveryServiceRegistryImpl.java:276) [95:org.eclipse.smarthome.config.discovery:0.9.0.201708151402]
	at org.eclipse.smarthome.config.discovery.internal.DiscoveryServiceRegistryImpl$2.run(DiscoveryServiceRegistryImpl.java:1) [95:org.eclipse.smarthome.config.discovery:0.9.0.201708151402]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at org.eclipse.smarthome.config.discovery.internal.DiscoveryServiceRegistryImpl.thingDiscovered(DiscoveryServiceRegistryImpl.java:273) [95:org.eclipse.smarthome.config.discovery:0.9.0.201708151402]
	at org.eclipse.smarthome.config.discovery.AbstractDiscoveryService.thingDiscovered(AbstractDiscoveryService.java:254) [95:org.eclipse.smarthome.config.discovery:0.9.0.201708151402]
	at org.openhab.binding.nikohomecontrol.internal.discovery.NikoHomeControlDiscoveryService.addDevice(NikoHomeControlDiscoveryService.java:108) [206:org.openhab.binding.nikohomecontrol:2.2.0.201708201100]
	at org.openhab.binding.nikohomecontrol.internal.discovery.NikoHomeControlDiscoveryService.discoverDevices(NikoHomeControlDiscoveryService.java:85) [206:org.openhab.binding.nikohomecontrol:2.2.0.201708201100]
	at org.openhab.binding.nikohomecontrol.handler.NikoHomeControlBridgeHandler$1.run(NikoHomeControlBridgeHandler.java:112) [206:org.openhab.binding.nikohomecontrol:2.2.0.201708201100]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:?]
2017-08-22 12:12:59.250 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'nikohomecontrol:onOff:440e003a24e6:23' to inbox.
```
I have seen this NPE with multiple bindings now, so not specific to the nikohomecontrol binding. Is the representationProperty new? If so, it is not set in the bindings generating this error. Should the framework work when no representationProperty is set? If not, I suspect many bindings need to be adapted to make this work.
I tried switching Inbox - Auto Ignore off. The error does not appear anymore in that case.

**Comment by kaikreuzer** [comment]
This should be already fixed with https://github.com/eclipse/smarthome/commit/04c173aad7a3cc34b053cc7ea0eb7c25f67a8aa6#diff-a96a064a67dc0ee07f84307c7b2c33caR85 - will try to do a new stable release soon!
