### ISSUE TITLE
NullPointerException error in logs

### ISSUE THREAD

**Issue by Dan1001** [eclipse/smarthome#4144]
I updated yesterday to the 2.2 snapshot. Everything seems to be working fine, but I'm getting the following error in the logs every 40 minutes or so:

`2017-08-28 12:27:28.326 [ERROR] [ore.internal.events.OSGiEventManager] - Dispatching/filtering event for subscriber 'org.eclipse.smarthome.core.events.EventSubscriber' failed: java.lang.NullPointerException
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) [?:?]
	at java.util.concurrent.FutureTask.get(FutureTask.java:206) [?:?]
	at org.eclipse.smarthome.core.common.SafeMethodCaller.callAsynchronous(SafeMethodCaller.java:194) [99:org.eclipse.smarthome.core:0.9.0.201708151402]
	at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:83) [99:org.eclipse.smarthome.core:0.9.0.201708151402]
	at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:67) [99:org.eclipse.smarthome.core:0.9.0.201708151402]
	at org.eclipse.smarthome.core.internal.events.OSGiEventManager.dispatchESHEvent(OSGiEventManager.java:189) [99:org.eclipse.smarthome.core:0.9.0.201708151402]
	at org.eclipse.smarthome.core.internal.events.OSGiEventManager.handleEvent(OSGiEventManager.java:164) [99:org.eclipse.smarthome.core:0.9.0.201708151402]
	at org.eclipse.smarthome.core.internal.events.OSGiEventManager.handleEvent(OSGiEventManager.java:147) [99:org.eclipse.smarthome.core:0.9.0.201708151402]
	at org.apache.felix.eventadmin.impl.handler.EventHandlerProxy.sendEvent(EventHandlerProxy.java:415) [3:org.apache.karaf.services.eventadmin:4.1.2]
	at org.apache.felix.eventadmin.impl.tasks.HandlerTask.run(HandlerTask.java:90) [3:org.apache.karaf.services.eventadmin:4.1.2]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
Caused by: java.lang.NullPointerException
	at org.eclipse.smarthome.config.discovery.internal.AutomaticInboxProcessor.getRepresentationPropertyValueForThing(AutomaticInboxProcessor.java:146) ~[?:?]
	at org.eclipse.smarthome.config.discovery.internal.AutomaticInboxProcessor.checkAndIgnoreInInbox(AutomaticInboxProcessor.java:119) ~[?:?]
	at org.eclipse.smarthome.config.discovery.internal.AutomaticInboxProcessor.autoIgnore(AutomaticInboxProcessor.java:111) ~[?:?]
	at org.eclipse.smarthome.config.discovery.internal.AutomaticInboxProcessor.receiveTypedEvent(AutomaticInboxProcessor.java:76) ~[?:?]
	at org.eclipse.smarthome.config.discovery.internal.AutomaticInboxProcessor.receiveTypedEvent(AutomaticInboxProcessor.java:1) ~[?:?]
	at org.eclipse.smarthome.core.events.AbstractTypedEventSubscriber.receive(AbstractTypedEventSubscriber.java:50) ~[?:?]
	at org.eclipse.smarthome.core.internal.events.OSGiEventManager$1.call(OSGiEventManager.java:193) ~[?:?]
	at org.eclipse.smarthome.core.internal.events.OSGiEventManager$1.call(OSGiEventManager.java:1) ~[?:?]
	at org.eclipse.smarthome.core.common.SafeMethodCaller$CallableWrapper.call(SafeMethodCaller.java:181) ~[?:?]
	... 4 more
`

It doesn't seem tied to any of my rules, or (so far as I can see) any events.

**Comment by kaikreuzer** [comment]
This has already been fixed with https://github.com/eclipse/smarthome/pull/4079/files#diff-a96a064a67dc0ee07f84307c7b2c33caR150. Will be part of the next ESH stable build.

**Comment by Dan1001** [comment]
thanks
