### ISSUE TITLE
Circular Reference in Automation Component

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#4151]
Similar to #4143, the now used DS implementation from Felix provoked yet another circular dependency:

```
!MESSAGE Circular reference detected trying to get service {org.eclipse.smarthome.automation.module.script.ScriptExtensionProvider}={service.id=136, service.bundleid=88, service.scope=bundle, component.name=org.eclipse.smarthome.automation.module.script.rulesupport.internal.LoaderScriptExtension, component.id=129}
 stack of references: ServiceReference: {org.eclipse.smarthome.automation.module.script.ScriptExtensionProvider}={service.id=136, service.bundleid=88, service.scope=bundle, component.name=org.eclipse.smarthome.automation.module.script.rulesupport.internal.LoaderScriptExtension, component.id=129}
ServiceReference: {org.eclipse.smarthome.automation.module.script.internal.ScriptExtensionManager}={service.id=139, service.bundleid=104, service.scope=bundle, component.name=org.eclipse.smarthome.automation.module.script.internal.ScriptExtensionManager, component.id=137}
```

Checking the code, I do not find any real issue. What looks suspicious is that in the exception, there are two places with:
```
	at com.eclipsesource.jaxrs.publisher.internal.ResourceTracker.addingService(ResourceTracker.java:39)
...
	at com.eclipsesource.jaxrs.publisher.internal.ResourceTracker.addingService(ResourceTracker.java:39)
```

This might be a hint that in fact the OSGi JAX-RS Connector is causing the issue as it activates all services (in order to check whether they have JAX-RS annotations or not).

**Comment by kaikreuzer** [comment]
@sjka just pointed me to https://github.com/hstaudacher/osgi-jax-rs-connector/blob/master/bundles/com.eclipsesource.jaxrs.publisher/src/com/eclipsesource/jaxrs/publisher/ResourceFilter.java - I would assume implementing our own filter will solve many of the issues that we regularly see regarding cyclic dependencies.
