### ISSUE TITLE
NPE in GenericItemProvider

### ISSUE THREAD

**Issue by htreu** [eclipse/smarthome#4162]
I got this NPE in the logs:

```
15:52:09.793 INFO  o.e.s.m.c.i.ModelRepositoryImpl[:130] - Refreshing model 'demo.items'
15:52:09.805 ERROR o.e.s.m.c.i.f.FolderObserver[:246] - Error handling update of file '/Users/henning/work/smarthome-master2/git/smarthome/distribution/smarthome/conf/items/demo.items': null.
java.lang.NullPointerException: null
	at org.eclipse.smarthome.model.item.internal.GenericItemProvider.toItemMap(GenericItemProvider.java:388)
	at org.eclipse.smarthome.model.item.internal.GenericItemProvider.modelChanged(GenericItemProvider.java:354)
	at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.notifyListeners(ModelRepositoryImpl.java:287)
	at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.addOrRefreshModel(ModelRepositoryImpl.java:136)
	at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.checkFile(FolderObserver.java:234)
	at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.processWatchEvent(FolderObserver.java:297)
	at org.eclipse.smarthome.core.service.WatchQueueReader.run(WatchQueueReader.java:204)
	at java.lang.Thread.run(Thread.java:745)
```

Steps to reproduce:

- Start ESH in the IDE using `SmartHome-Runtime.launch`
- Edit `distribution/smarthome/conf/items/demo.items`
- add a label to one of the items like `String DemoString "Demo String"`
- save file

--> NPE

**Comment by htreu** [comment]
This is an excerpt from my log starting the framework when the error later occurs:

```
16:22:43.600 INFO  o.e.s.m.c.i.ModelRepositoryImpl[:110] - Loading model 'demo.items'
16:22:43.601 ERROR o.e.s.m.c.i.ModelRepositoryImpl[:121] - --> sending model added event
16:22:43.619 DEBUG o.e.s.u.i.p.ProxyServletService[:153] - Starting up 'Proxy (async)' servlet  at /proxy
16:22:44.116 DEBUG o.e.s.c.t.i.ChannelItemProvider[:197] - Enabling channel item provider.
16:22:48.768 INFO  o.e.s.u.b.i.s.WebAppServlet[:84] - Started Basic UI at /basicui/app
16:22:48.775 INFO  o.e.s.u.c.i.s.WebAppServlet[:87] - Started Classic UI at /classicui/app
16:22:48.782 DEBUG o.e.s.m.s.ScriptServiceUtil[:55] - ScriptServiceUtil started
16:22:49.468 DEBUG o.e.s.m.s.r.i.e.ScriptEngineImpl[:61] - Registered 'script' configuration parser
16:22:49.692 DEBUG o.e.s.m.r.r.i.RuleRuntimeActivator[:28] - Registered 'rule' configuration parser
16:22:49.701 INFO  o.quartz.core.QuartzScheduler[:2311] - JobFactory set to: org.eclipse.smarthome.model.rule.runtime.internal.engine.GuiceAwareJobFactory@119d6fda
16:22:49.701 INFO  o.quartz.core.QuartzScheduler[:613] - Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED paused.
16:22:49.702 DEBUG o.e.s.m.r.r.i.e.RuleEngineImpl[:107] - Started rule engine
16:22:49.708 DEBUG o.e.s.m.t.i.GenericThingProvider[:806] - ThingHandlerFactory added org.eclipse.smarthome.binding.ntp.internal.NtpHandlerFactory@73988906
16:22:49.709 DEBUG o.e.s.m.t.i.GenericThingProvider[:806] - ThingHandlerFactory added org.eclipse.smarthome.binding.yahooweather.internal.YahooWeatherHandlerFactory@228c1f4c
16:22:49.715 DEBUG o.e.s.c.c.r.AbstractRegistry[:291] - Provider 'org.eclipse.smarthome.model.thing.internal.GenericThingProvider' has been added.
16:22:49.721 DEBUG o.e.s.m.i.i.GenericItemProvider[:143] - Read items from model 'demo.items'
16:22:49.724 DEBUG o.e.s.c.c.r.AbstractRegistry[:291] - Provider 'org.eclipse.smarthome.model.item.internal.GenericItemProvider' has been added.
16:22:49.725 INFO  smarthome.event.ItemAddedEvent[:47] - Item 'DemoString' has been added.
16:22:54.726 INFO  o.quartz.core.QuartzScheduler[:575] - Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.
16:23:03.623 INFO  o.e.s.m.c.i.ModelRepositoryImpl[:133] - Refreshing model 'demo.items'
16:23:03.625 ERROR o.e.s.m.c.i.ModelRepositoryImpl[:140] - --> sending model modified event
16:23:03.630 ERROR o.e.s.m.c.i.f.FolderObserver[:246] - Error handling update of file '/Users/henning/work/smarthome-master2/git/smarthome/distribution/smarthome/conf/items/demo.items': null.
java.lang.NullPointerException: null
	at org.eclipse.smarthome.model.item.internal.GenericItemProvider.toItemMap(GenericItemProvider.java:389)
	at org.eclipse.smarthome.model.item.internal.GenericItemProvider.modelChanged(GenericItemProvider.java:355)
	at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.notifyListeners(ModelRepositoryImpl.java:293)
	at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.addOrRefreshModel(ModelRepositoryImpl.java:142)
	at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.checkFile(FolderObserver.java:234)
	at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.processWatchEvent(FolderObserver.java:297)
	at org.eclipse.smarthome.core.service.WatchQueueReader.run(WatchQueueReader.java:204)
	at java.lang.Thread.run(Thread.java:745)
```

notice the extra logging `--> sending model added event` I added when the `ModelRepositoryImpl` does load the model.
In `GenericItemProvider` is a corresponding extra logging on processing the `ADDED` event which is absent here. I will provide the same excerpt for the situation when the error does _not_ occur.

My guess: The time the model is loaded the GenericItemProvider is not started yet. See time `16:22:43.601` for the model loading vs. `16:22:49.724`  when the provider is added.
