### ISSUE TITLE
Running the build "mvn clean install"  fails on window 10

### ISSUE THREAD

**Issue by Jianfeili** [eclipse/smarthome#4370]
Hi, 

I have tried this multiple times. The behavior is consistent on window 10.

ailed tests:
  ConfigDispatcherOSGiTest.whenExclusiveConfigFileIsDeleted_shouldRemoveConfigFromConfigAdmin:581->JavaTest.waitForAssert:64->JavaTest.waitForAssert:111->JavaTest.waitForAssert:143->lambda$1:587 The configuration with properties for the given pid was found but should have been removed.
Expected: is null
     but: was <org.eclipse.equinox.internal.cm.ConfigurationDictionary@600b9d27>

Tests run: 27, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Eclipse SmartHome .................................. SUCCESS [  2.415 s]
[INFO] Eclipse SmartHome Bundles .......................... SUCCESS [  0.932 s]
[INFO] Eclipse SmartHome Test Components .................. SUCCESS [  0.201 s]
[INFO] Eclipse SmartHome Core Components .................. SUCCESS [  0.140 s]
[INFO] Eclipse SmartHome Core ............................. SUCCESS [01:34 min]
[INFO] Eclipse SmartHome Configurations ................... SUCCESS [  0.129 s]
[INFO] Eclipse SmartHome Configuration Core ............... SUCCESS [ 18.202 s]
[INFO] Eclipse SmartHome Configuration XML ................ SUCCESS [ 13.551 s]
[INFO] Eclipse SmartHome AutoUpdate Binding ............... SUCCESS [  7.918 s]
[INFO] Eclipse SmartHome Test ............................. SUCCESS [ 22.072 s]
[INFO] Eclipse SmartHome I/O Components ................... SUCCESS [  0.093 s]
[INFO] Eclipse SmartHome Console .......................... SUCCESS [  9.940 s]
[INFO] Eclipse SmartHome Thing ............................ SUCCESS [ 28.708 s]
[INFO] Magic Bundle ....................................... SUCCESS [  9.462 s]
[INFO] Magic Bundle Tests ................................. SUCCESS [ 14.991 s]
[INFO] Eclipse SmartHome Auth Components .................. SUCCESS [  0.078 s]
[INFO] Eclipse SmartHome JAAS Authentication .............. SUCCESS [  7.635 s]
[INFO] Eclipse SmartHome Configuration Dispatcher ......... SUCCESS [  8.886 s]
[INFO] Eclipse SmartHome Configuration Dispatcher Tests ... FAILURE [ 38.266 s]
[INFO] Eclipse SmartHome Configuration Core Tests ......... SKIPPED
[INFO] Eclipse SmartHome Configuration Discovery .......... SKIPPED
[INFO] Eclipse SmartHome Core Thing XML ................... SKIPPED
[INFO] Eclipse SmartHome Configuration Discovery Tests .... SKIPPED
[INFO] Eclipse SmartHome Config XML Tests ................. SKIPPED

Thanks 
Jeff

**Comment by Jianfeili** [comment]
"mvn  -DskipTests clean install" failed  as well.

 Eclipse SmartHome Paper UI ......................... FAILURE [ 22.701 s]
Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.0:npm (npm install) on project org.eclipse.smarthome.ui.paper: Failed to run task: 'npm install' failed. (error code 1)
[npm-debug.log](https://github.com/eclipse/smarthome/files/1352921/npm-debug.log)

**Comment by hreichert** [comment]
Yesterday some Travis builds failed on the same step due to connection problems, if I see this correctly.
Can you try to run the build again?

**Comment by Jianfeili** [comment]
Hi, 

I ran this morning and just now. It encountered the same issue and failed in the project paper ui, Please see the npm-debug.log that I attached to the last message. There are many errors in the log, such as 

582 verbose cloneResolved error: refs/heads/master does not point to a valid object!
582 verbose cloneResolved error: refs/pull/10/head does not point to a valid object!
582 verbose cloneResolved error: refs/pull/10/merge does not point to a valid object!
582 verbose cloneResolved error: refs/pull/12/head does not point to a valid object!
582 verbose cloneResolved error: refs/pull/14/head does not point to a valid object!
582 verbose cloneResolved error: refs/pull/14/merge does not point to a valid object!
582 verbose cloneResolved error: refs/pull/17/head does not point to a valid object!
582 verbose cloneResolved error: refs/pull/17/merge does not point to a valid object!
582 verbose cloneResolved error: refs/pull/6/head does not point to a valid object!
582 verbose cloneResolved error: refs/pull/6/merge does not point to a valid object!
582 verbose cloneResolved error: refs/pull/7/head does not point to a valid object!
582 verbose cloneResolved error: refs/tags/v0.9.1 does not point to a valid object!
582 verbose cloneResolved error: refs/tags/v0.9.2 does not point to a valid object!
582 verbose cloneResolved error: refs/tags/v0.9.3 does not point to a valid object!
582 verbose cloneResolved error: refs/tags/v0.9.4 does not point to a valid object!
582 verbose cloneResolved error: refs/tags/v0.9.5 does not point to a valid object!
582 verbose cloneResolved error: refs/tags/v0.9.6 does not point to a valid object!
582 verbose cloneResolved error: refs/tags/v0.9.7 does not point to a valid object!

604 error git clone 

637 verbose stack Error: Command failed: git -c core.longpaths=true clone --template=C:\jli\Projects\HomeAutomation\Workspace\smarthome-master\git\smarthome\extensions\ui\org.eclipse.smarthome.ui.paper\npm_cache\_git-remotes\_templates --mirror git@github.com:jquery/jquery-ui.git C:\jli\Projects\HomeAutomation\Workspace\smarthome-master\git\smarthome\extensions\ui\org.eclipse.smarthome.ui.paper\npm_cache\_git-remotes\git-github-com-jquery-jquery-ui-git-1-11-2-d6651efbf77bb17d6689d2baba584d93
637 verbose stack Cloning into bare repository 'C:\jli\Projects\HomeAutomation\Workspace\smarthome-master\git\smarthome\extensions\ui\org.eclipse.smarthome.ui.paper\npm_cache\_git-remotes\git-github-com-jquery-jquery-ui-git-1-11-2-d6651efbf77bb17d6689d2baba584d93'...
637 verbose stack Host key verification failed.
637 verbose stack fatal: Could not read from remote repository.
637 verbose stack
637 verbose stack Please make sure you have the correct access rights
637 verbose stack and the repository exists.

Thanks.

**Comment by triller-telekom** [comment]
@Jianfeili from your posted debug logfile I see a lot of cache errors on the file system. have you tried it with a blank new checkout and setup of the project? How do you install the setup on your system? I assume you are using the Eclipse installer? Does it work if you have cleaned up the files on your local filesystem and restarted from scratch?

**Comment by lpapazow** [comment]
Hi, 

I am also trying to build smarthome and I get the same error as well. 

When I run the ConfigDispatcherOSGITests in Eclipse I get the same error. This is the stacktrace:

java.lang.AssertionError: The configuration with properties for the given pid was found but should have been removed.
Expected: is null
     but: was <org.eclipse.equinox.internal.cm.ConfigurationDictionary@49b2a47d>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:865)
	at org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest.lambda$1(ConfigDispatcherOSGiTest.java:587)
	at org.eclipse.smarthome.test.java.JavaTest.waitForAssert(JavaTest.java:143)
	at org.eclipse.smarthome.test.java.JavaTest.waitForAssert(JavaTest.java:111)
	at org.eclipse.smarthome.test.java.JavaTest.waitForAssert(JavaTest.java:64)
	at org.eclipse.smarthome.config.dispatch.test.ConfigDispatcherOSGiTest.whenExclusiveConfigFileIsDeleted_shouldRemoveConfigFromConfigAdmin(ConfigDispatcherOSGiTest.java:581)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.pde.internal.junit.runtime.RemotePluginTestRunner.main(RemotePluginTestRunner.java:66)
	at org.eclipse.pde.internal.junit.runtime.CoreTestApplication.run(CoreTestApplication.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.internal.app.EclipseAppContainer.callMethodWithException(EclipseAppContainer.java:587)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:198)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)


@htreu I think you added this test, maybe you might shed light on this issue?

**Comment by htreu** [comment]
I will have a look, stay tuned.

**Comment by htreu** [comment]
Since I don´t have a Windows 10 device to test, please try to apply this patch https://gist.github.com/htreu/dd62e38c35aa88bef2cc9b52d0b993fe using `git apply confDispatcher-win10-fix.patch` from the root of the git repo. Then run the test again.

**Comment by lpapazow** [comment]
Hi,

Unfortunately, applying the patch did not fix the test for me.

**Comment by htreu** [comment]
This PR https://github.com/eclipse/smarthome/pull/4685 will decouple the file watcher from the ConfigDispatcher which should make the tests much more reliable. Stay tuned for it to be merged, should fix this.
