### ISSUE TITLE
Jetty service locator error on start up

### ISSUE THREAD

**Issue by ghohuser** [eclipse/smarthome#4559]
This error appears in the log when location is not set in OpenHAB and you bring up a browser that does not have location permissions to view  openhab:8080. The browser prompts for location and, in my case, I ignored this. The issue was resolved by manually going to Paper UI / Configuration / System / Regional and adding location latitude and longitude,  country setting, language (not sure if all 3 are required, but issue went away after they were set).

error messages in log:

[WARN ] [org.eclipse.jetty.server.HttpChannel] - /rest/sitemaps/default/default?_=392a7a8d87607
javax.servlet.ServletException: javax.servlet.ServletException: A MultiException has 1 exceptions. They are:

    java.lang.IllegalStateException: ServiceLocatorImpl(__HK2_Generated_1,2,950579) has been shut down

    at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:88)[172:org.ops4j.pax.web.pax-web-jetty:4.3.0]
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)[80:org.eclipse.jetty.server:9.2.19.v20160908]
    at org.eclipse.jetty.server.Server.handle(Server.java:499)[80:org.eclipse.jetty.server:9.2.19.v20160908]
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)[80:org.eclipse.jetty.server:9.2.19.v20160908]
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)[80:org.eclipse.jetty.server:9.2.19.v20160908]
    at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)[71:org.eclipse.jetty.io:9.2.19.v20160908]

. . .

[WARN ] [org.eclipse.jetty.server.HttpChannel] - Could not send response error 500: javax.servlet.ServletException: javax.servlet.ServletException: A MultiException has 1 exceptions. They are:

    java.lang.IllegalStateException: ServiceLocatorImpl(__HK2_Generated_1,2,950579) has been shut down

**Comment by maggu2810** [comment]
> and you bring up a browser that does not have location permissions to view openhab:8080

Hi @ghohuser, I tried to understand what you mean, but I don't really understand, what I need to do to reproduce that error.

**Comment by ghohuser** [comment]
Hi, sorry it was unclear. I brought up the webpage http://<myopenhabIP>:8080 in MS Edge. The browser popped up a message that the website wanted my location and that I needed to change the browser settings to be able to deliver it. I ignored the message. The error appeared in my log file until I manually set location, etc., in the Paper UI

**Comment by kaikreuzer** [comment]
If this is triggered by the browser trying to set the location, this is a feature of the [openHAB Dashboard](https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.ui.dashboard/web/js/geolocation.js) and thus not related to ESH. Feel free to open the issue at https://github.com/openhab/openhab-core/issues.
