### ISSUE TITLE
Startup exceptions and warnings

### ISSUE THREAD

**Issue by mstormi** [eclipse/smarthome#4586]
Since openHAB snapshot #1084 / ESH #236, I'm getting a couple of exceptions and warnings on startup that I haven't seen before.

This is for more or less every bundle:

2017-11-19 08:48:05.345 [INFO ] [g.apache.aries.spifly.dynamic.bundle] - Bundle Considered for SPI providers: org.eclipse.smarthome.ui.iconset.classic
2017-11-19 08:48:05.352 [INFO ] [g.apache.aries.spifly.dynamic.bundle] - No 'SPI-Provider' Manifest header. Skipping bundle: org.eclipse.smarthome.ui.iconset.classic
2017-11-19 08:48:05.480 [DEBUG] [mpl.info.InfoBundleTrackerCustomizer] - Ignore incorrect info null provided by bundle org.eclipse.smarthome.ui.iconset.classic
2017-11-19 08:48:05.482 [INFO ] [internal.service.FeaturesServiceImpl] -   org.eclipse.smarthome.io.rest.mdns/0.9.0.201711182209
2017-11-19 08:48:05.488 [INFO ] [g.apache.aries.spifly.dynamic.bundle] - Bundle Considered for SPI providers: org.eclipse.smarthome.io.rest.mdns
2017-11-19 08:48:05.492 [INFO ] [g.apache.aries.spifly.dynamic.bundle] - No 'SPI-Provider' Manifest header. Skipping bundle: org.eclipse.smarthome.io.rest.mdns
2017-11-19 08:48:05.550 [DEBUG] [mpl.info.InfoBundleTrackerCustomizer] - Ignore incorrect info null provided by bundle org.eclipse.smarthome.io.rest.mdns
2017-11-19 08:48:05.553 [INFO ] [internal.service.FeaturesServiceImpl] -   org.eclipse.smarthome.io.rest.optimize/0.9.0.201711182209
2017-11-19 08:48:05.657 [INFO ] [g.apache.aries.spifly.dynamic.bundle] - Bundle Considered for SPI providers: org.eclipse.smarthome.model.item.runtime
2017-11-19 08:48:05.666 [INFO ] [g.apache.aries.spifly.dynamic.bundle] - No 'SPI-Provider' Manifest header. Skipping bundle: org.eclipse.smarthome.model.item.runtime

and there's many of these:

2017-11-19 08:48:03.812 [ERROR] [org.eclipse.smarthome.core.id       ] - FrameworkEvent ERROR - org.eclipse.smarthome.core.id
org.osgi.framework.ServiceException: Exception in org.apache.felix.scr.impl.manager.SingleComponentManager.getService()
        at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.factoryGetService(ServiceFactoryUse.java:222) ~[?:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.getService(ServiceFactoryUse.java:111) ~[?:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceConsumer$2.getService(ServiceConsumer.java:45) ~[?:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.getService(ServiceRegistrationImpl.java:496) ~[?:?]
[...]
        ... 49 more
Caused by: java.lang.ClassNotFoundException: org.eclipse.smarthome.io.rest.RESTResource cannot be found by org.eclipse.smarthome.core.id_0.9.0.201711182209
        at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:461) ~[?:?]
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:372) ~[?:?]

**Comment by kaikreuzer** [comment]
The aries.spifly logs are not ESH related - this is a bundle that is used by Karaf, which hence has nothing to do with ESH, but with openHAB as it uses Karaf. I have not seen those in openHAB either and it feels to me that you have some custom logging configuration that you should simply reconfigure in order to exclude those (uncritical DEBUG and INFO) logs.

> `java.lang.ClassNotFoundException: org.eclipse.smarthome.io.rest.RESTResource cannot be found by org.eclipse.smarthome.core.id_0.9.0.201711182209`

This is indeed an issue with ESH as io.rest is an optional import and thus you seem to be in a situation where it hasn't been resolved when `core.id` has been started.
We will have to look at some better way to structure that code.

**Comment by kaikreuzer** [comment]
I have created https://github.com/eclipse/smarthome/issues/4590 for the core.id issue.

**Comment by mstormi** [comment]
Regarding aries.spifly logs, yes this is from org.apache.karaf = DEBUG, but it's new since Karaf 4.1.3.
Shouldn't you create those 'SPI-Provider' Manifest headers ? Or open a Karaf issue for it if you feel this is in error.

**Comment by maggu2810** [comment]
SPI Fly itself is not new in Karaf 4.1.3. And IIRC in a standard Karaf distributions the SPI Fly logs has been visible in every 4.x Karaf version.
Why should we add SPI headers if we don't use SPI at all?

**Comment by mstormi** [comment]
Hadn't seen those messages in Karaf <= 4.1.2. Agree you shouldn't need to add headers, but then it's a Karaf bug (well, or at least "inconsistency") to mock those missing. Surely not the most important of issues, but for sake of sanity I'd suggest you give them a wink.

**Comment by maggu2810** [comment]
It is not an error or warning it is an information (log level). So I don't the any "inconsistency".
"SPI Fly" is not part of the standard feature set but installed if you install a feature that brings "SPI Fly" in the game.
So, the only valid report that I see is to discuss if the standard Karaf distribution should change the default log level for "SPI Fly". But IIRC the Karaf distribution is using log level info for the most part and for a non-customized distribution it is IMHO okay.
If you don't want to see such messages in your custom distribution you should change your logging configuration (but this is a topic that should be done by every custom distribution to fit its need and nothing that a non-customized Karaf standard distribution should / can care of <-- IMHO).
If you (and all the installed bundles) don't need SPI Fly at all, you can also blacklist it.
But all that topics are very unrelated to ESH but to your custom distribution.
