### ISSUE TITLE
Can't access list of voices or use 'say' command

### ISSUE THREAD

**Issue by kubawolanin** [eclipse/smarthome#4632]
openHAB 2.2.0 Build # 1099

In `runtime.cfg` I've declared the following:
```
org.eclipse.smarthome.voice:defaultTTS=pollytts
```
It's a [Polly TTS](https://github.com/openhab/openhab2-addons/pull/2374) add-on, but tried this with `voicerss` as well.

I can't see any configuration parameters for Voice in Paper UI.

What's more, when I do:
```
openhab> smarthome:voice voices
An unexpected error occurred during execution.
```

I get the following error:
```
2017-11-26 13:41:10.805 [ERROR] [rthome.io.console.ConsoleInterpreter] - An error occurred while executing the console command.
java.lang.NullPointerException: null
	at java.util.AbstractCollection.addAll(AbstractCollection.java:343) [?:?]
	at org.eclipse.smarthome.core.voice.internal.VoiceManagerImpl.getAllVoices(VoiceManagerImpl.java:569) [127:org.eclipse.smarthome.core.voice:0.9.0.201711242229]
	at org.eclipse.smarthome.core.voice.internal.VoiceConsoleCommandExtension.execute(VoiceConsoleCommandExtension.java:76) [127:org.eclipse.smarthome.core.voice:0.9.0.201711242229]
	at org.eclipse.smarthome.io.console.ConsoleInterpreter.execute(ConsoleInterpreter.java:57) [128:org.eclipse.smarthome.io.console:0.9.0.201711242229]
	at org.eclipse.smarthome.io.console.karaf.internal.CommandWrapper.execute(CommandWrapper.java:79) [129:org.eclipse.smarthome.io.console.karaf:0.9.0.201711242229]
	at org.apache.karaf.shell.impl.console.osgi.secured.SecuredCommand.execute(SecuredCommand.java:68) [15:org.apache.karaf.shell.core:4.1.3]
	at org.apache.karaf.shell.impl.console.osgi.secured.SecuredCommand.execute(SecuredCommand.java:86) [15:org.apache.karaf.shell.core:4.1.3]
	at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:571) [15:org.apache.karaf.shell.core:4.1.3]
	at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:497) [15:org.apache.karaf.shell.core:4.1.3]
	at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:386) [15:org.apache.karaf.shell.core:4.1.3]
	at org.apache.felix.gogo.runtime.Pipe.doCall(Pipe.java:417) [15:org.apache.karaf.shell.core:4.1.3]
	at org.apache.felix.gogo.runtime.Pipe.call(Pipe.java:229) [15:org.apache.karaf.shell.core:4.1.3]
	at org.apache.felix.gogo.runtime.Pipe.call(Pipe.java:59) [15:org.apache.karaf.shell.core:4.1.3]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
```

Thanks in advance.

**Comment by kubawolanin** [comment]
Turns out it was an issue with the Polly TTS add-on.
Removing the JAR from Add-ons folder resolved the issue.
cc: @hillmanr

**Comment by hillmanr** [comment]
I'm looking at it.
