### ISSUE TITLE
Empty item drop  down list in PaperUI

### ISSUE THREAD

**Issue by idkpmiller** [eclipse/smarthome#4648]
Platform information:
Hardware: CPUArchitecture/RAM/storage
Raspberry Pi 3 (standard)

OS:
Openhabian (Raspbian??)

Java Runtime Environment:
openjdk version "1.8.0_152"
OpenJDK Runtime Environment (Zulu Embedded 8.25.0.76-linux-aarch32hf) (build 1.8.0_152-b76)
OpenJDK Client VM (Zulu Embedded 8.25.0.76-linux-aarch32hf) (build 25.152-b76, mixed mode, Evaluation)

openHAB version:
2.1.0 Release Build

ISSUE:
When adding a binding such as ‘Chromecast’ or iCloud using the PaperUI AddOns.
I get the discovered Things in my inbox which I then ‘Add as things’.

Using PaperUI I then go to the Configurations > Things and try and create a new item for the link but I get an empty pull down list instead, see screen shot.

I have captured what may be the error in the logs at the time but it means nothing to me.

Possible LOG ERROR of event?
```

15:46:27.178 [ERROR] [ersey.server.ServerRuntime$Responder] - An I/O error has occurred while writing a response message entity to the container output stream.
org.glassfish.jersey.server.internal.process.MappableException: java.util.IllegalFormatConversionException: d != java.lang.String
        at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:92)[158:org.glassfish.jersey.core.jersey-server:2.22.2]
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162)[157:org.glassfish.jersey.core.jersey-common:2.22.2]
        at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1130)[157:org.glassfish.jersey.core.jersey-common:2.22.2]
        at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:711)[158:org.glassfish.jersey.core.jersey-server:2.22.2]
        at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:444)[158:org.glassfish.jersey.core.jersey-server:2.22.2]
        at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:434)[158:org.glassfish.jersey.core.jersey-server:2.22.2]
        at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:329)[158:org.glassfish.jersey.core.jersey-server:2.22.2]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)[157:org.glassfish.jersey.core.jersey-common:2.22.2]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)[157:org.glassfish.jersey.core.jersey-common:2.22.2]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)[157:org.glassfish.jersey.core.jersey-common:2.22.2]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)[157:org.glassfish.jersey.core.jersey-common:2.22.2]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267)[157:org.glassfish.jersey.core.jersey-common:2.22.2]
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)[157:org.glassfish.jersey.core.jersey-common:2.22.2]
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)[158:org.glassfish.jersey.core.jersey-server:2.22.2]
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)[158:org.glassfish.jersey.core.jersey-server:2.22.2]
        at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)[155:org.glassfish.jersey.containers.jersey-container-servlet-core:2.22.2]
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)[155:org.glassfish.jersey.containers.jersey-container-servlet-core:2.22.2]
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)[155:org.glassfish.jersey.containers.jersey-container-servlet-core:2.22.2]
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)[155:org.glassfish.jersey.containers.jersey-container-servlet-core:2.22.2]
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)[155:org.glassfish.jersey.containers.jersey-container-servlet-core:2.22.2]
        at com.eclipsesource.jaxrs.publisher.internal.ServletContainerBridge.service(ServletContainerBridge.java:76)[9:com.eclipsesource.jaxrs.publisher:5.3.1.201602281253]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)[81:org.eclipse.jetty.servlet:9.2.19.v20160908]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)[81:org.eclipse.jetty.servlet:9.2.19.v20160908]
        at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:71)[172:org.ops4j.pax.web.pax-web-jetty:4.3.0]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)[80

```

<img width="920" alt="2017-11-26" src="https://user-images.githubusercontent.com/3002745/33359010-27ec5b28-d531-11e7-8bdd-7899af58b7c0.png">

**Comment by maggu2810** [comment]
Thank you for your detailed description.
You are using "2.1.0 Release Build". Isn't it rather old?

There is "org.eclipse.jetty.servlet" in the version "9.2.19.v20160908" part of your stack trace.
ESH is using 9.3.15 in its targetplaform.
openHAB will move to 9.3.22 ...

Can you try to reproduce that error with a more up to date version?

**Comment by idkpmiller** [comment]
My OpenHab version is the latest stable release and it is 2.1.0
I am not aware of the ESH version that is being used, if youwant me to advise please provide instruction on how to obtain this information.
It seems you have the actual ESH version that OH2 has been built upon from the stack trace.

I am not even sure if I can upgrade the ESH underneath OpenHab or if that involves a new build from the OH maintainers.

Regards
Paul

**Comment by maggu2810** [comment]
> I am not aware of the ESH version that is being used, if you want me to advise please provide instruction on how to obtain this information.

Sure, have a look at this one: [Which ESH base is used in my openHAB instance]

Perhaps you are willing to test the most recent openHAB snapshot as it is using a much more recent ESH version (and Jetty one, ...).

It is hard to tell you if it is really an issue that is still present in the Eclipse SmartHome framework as long as you test against an old one that is used by your openHAB release (the last official release).

I could try to reproduce this error using a recent Eclipse SmartHome.

[Which ESH base is used in my openHAB instance]: https://github.com/eclipse/smarthome/wiki/ESH-used-in-openHAB

**Comment by maggu2810** [comment]
* I have used "Apache Karaf (4.2.0.M1)" and Eclipse SmartHome build from the current master sources.
* Turn off the item linking's simple mode
  Paper UI, Configuration, System, Item Linking, Simple Mode: Off
* Install the Sonos binding by using the respective Karaf feature
  `feature:install esh-binding-sonos`
* Add a discovered Sonos thing that is part of the Inbox now (using the Paper UI)
* Paper UI, Configuration, Things, "the sonos thing", click on a non-linked channel
* I see a folded drop-down-menu with a gray text "Item". If I click on the drop-down-menu, I see a italic black text "+ Create new item..."

**Comment by idkpmiller** [comment]
So you are unable to replicate the issue using those versions that does not surprise me, as I am not convinced that it is a simple issue it could be a specific configuration or even combinations of events that have led to corruption.
I should point out that I have been on OH 2.1.0 for some time and this has not happened until very recently.
I am currently backing up the RPi SD card so I can try an upgrade to the latest 2.2 snapshot and see if that cleans out the issue. I will advise results when done.

If this resolves the issue I am ok to carry on with OH 2.2
if it does not resolve the issue then we need to discuss what files should be checked for corruption, remembering this is a RPi and they have been known to have data corruption on SD cards although I am seeing no other evidence of corruption. It could still be a bug of course ;-)

**Comment by idkpmiller** [comment]
before upgrading I took a look ariound an there is evidence of a bigger proble.
This install has many working items yet the configuration > Items section is empty. see the screen shot.

<img width="921" alt="2017-12-01 1" src="https://user-images.githubusercontent.com/3002745/33463640-95dd0aba-d6a3-11e7-9509-0ce21ff34281.png">

**Comment by sjka** [comment]
That's not very helpful either...

**Comment by idkpmiller** [comment]
If you would like to ask for a particular output to assist in understanding the problem then I will certianly try and assist.

The Openhab system is currently functioning and if I use the console I can see Things, Links, Items etc all fine but PaperUI has thrown a wobbly and any assistance is greatly appreciated.

I am currently thinking that an upgrade will not cut it, but will certainly give it a go.
There are a number of time I have seen the PaperUI stall when performing many iterations of the same task such as unlinking 20 items and then removing them and then removing the Things thay once connect too. perhaps there is  a use case where the cleanup/removal is not quite done and it ends up in a situation where the files cannot be loaded???? I really do not know and that is why I raised the issue here.

**Comment by idkpmiller** [comment]
I have upgraded to unstable 2.2 using the openhabian scripts.
First impression is good.

I can now see the items in PaperUI

see screen shot. I will do some testing and see if this upgrade returned the install beck to normal, but of course still no idea why it failed in the first place.

<img width="921" alt="2017-12-02" src="https://user-images.githubusercontent.com/3002745/33509098-a58c7afc-d763-11e7-9974-200206acb7b6.png">

**Comment by idkpmiller** [comment]
After only a small amount of testing it has become obvious that there is still an issue going on.

1. I can now see a list of Items - GOOD
2. Using PaperUI > Configurations > Things I cannot scroll with my mouse; using search filters it looks like the elements are there but not sure why I cannot scroll down the list. - ISSUE
3.  In PaperUI adding the ChromeCast binging does not result in auto-discovery and the finding of my chromecast devices in the Inbox - ISSUE
4. In PaperUI Addons add the iCloud binding, add OK - GOOD
5. Next, in PaperUI Configurations > Things, scroll still not working (see #2) and pressing the + button to add pulls up the Inbox > Choose Binding; again no scroll capability. - ISSUE

Seems there is still an issue that the upgrade cannot really solve.
Please advise what next step is recommended for troubleshooting.

**Comment by idkpmiller** [comment]
I decided the next step was for me to reboot, staying on unstable 2.2 OH2 version.
After rebooting some behaviour changes were noted.

1. I can still see a list of Items - GOOD
2. Using PaperUI > Configurations > Things I can now scroll with my mouse- GOOD
3. In PaperUI > Things the ChromeCast binging is showing as uninitilised and it is not listed as installed under Add-ons. - Issuedoes not result in auto-discovery and the finding of my chromecast devices in the Inbox - ISSUE
4. In PaperUI Addons  the iCloud binding, is still showing as INSTALL - GOOD
5. Next, in PaperUI Configurations > Things, scroll is working (see #2) and pressing the + button to add pulls up the Inbox > Choose Binding now I can scroll and I see the icloud bindingy - GOOD

This is looking much better, I will need to test more to confirm

**Comment by idkpmiller** [comment]
I have no reason as to why the issue began, but the upgrade to the latest unstable release corrected the problem, well at least after a reboot.
