### ISSUE TITLE
[LIFX] LifxLightCommunicationHandler causing high CPU load

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#4665]
I just observed a permanent 100% CPU load that has been caused by the LIFX binding.
The thread dump gave me the following culprit:
```
"ESH-thingHandler-3" #156 daemon prio=5 os_prio=31 tid=0x00007fccc54a4800 nid=0x11c03 runnable [0x00007000079a9000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
	at sun.nio.ch.KQueueArrayWrapper.poll(KQueueArrayWrapper.java:198)
	at sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:117)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x0000000785808378> (a sun.nio.ch.Util$2)
	- locked <0x0000000785808388> (a java.util.Collections$UnmodifiableSet)
	- locked <0x0000000785808328> (a sun.nio.ch.KQueueSelectorImpl)
	at sun.nio.ch.SelectorImpl.selectNow(SelectorImpl.java:105)
	at org.eclipse.smarthome.binding.lifx.internal.LifxLightCommunicationHandler.sendPacket(LifxLightCommunicationHandler.java:444)
	at org.eclipse.smarthome.binding.lifx.internal.LifxLightCommunicationHandler.sendPacket(LifxLightCommunicationHandler.java:410)
	at org.eclipse.smarthome.binding.lifx.internal.LifxLightCurrentStateUpdater.sendLightStateRequests(LifxLightCurrentStateUpdater.java:129)
	at org.eclipse.smarthome.binding.lifx.internal.LifxLightCurrentStateUpdater.handleResponsePacket(LifxLightCurrentStateUpdater.java:162)
	at org.eclipse.smarthome.binding.lifx.internal.LifxLightCurrentStateUpdater$$Lambda$395/728137441.handleResponsePacket(Unknown Source)
	at org.eclipse.smarthome.binding.lifx.internal.LifxLightCommunicationHandler.lambda$2(LifxLightCommunicationHandler.java:374)
	at org.eclipse.smarthome.binding.lifx.internal.LifxLightCommunicationHandler$$Lambda$404/466964589.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at org.eclipse.smarthome.binding.lifx.internal.LifxLightCommunicationHandler.lambda$1(LifxLightCommunicationHandler.java:374)
	at org.eclipse.smarthome.binding.lifx.internal.LifxLightCommunicationHandler$$Lambda$403/535484232.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
It seems it went into an endless loop. Even stopping the LIFX bundle didn't make it stop, I had to restart my whole system.

**Comment by kaikreuzer** [comment]
@wborn Could you maybe have a look at this? I cannot tell you how to reproduce it, though :-(

**Comment by wborn** [comment]
After looking at the code an explanation could be that [selector.selectNow()](https://github.com/eclipse/smarthome/blob/d3a693a1cbc28c4b34d676d662b19473aadbf5bb/extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/internal/LifxLightCommunicationHandler.java#L444) kept returning an empty list (or the keys were not valid and writable) while the selector was not closed. That could create an endless loop.

We could prevent such behavior by adding a timeout to the select operation and by limiting the maximum number of iterations before giving up.

**Comment by kaikreuzer** [comment]
Could you give it a try in a PR?

**Comment by wborn** [comment]
Yes I'm also seeing this issue frequently after just starting the runtime with OH build # 1103.
