### ISSUE TITLE
LSP error when stopping OH

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#4667]
Running OH snapshot 1104, I got this error when stopping OH:
```
2017-12-02 09:21:24.729 [ERROR] [thome.model.lsp.internal.ModelServer] - Error accepting the client connection
java.net.SocketException: Socket closed
        at java.net.PlainSocketImpl.socketAccept(Native Method) ~[?:?]
        at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409) ~[?:?]
        at java.net.ServerSocket.implAccept(ServerSocket.java:545) ~[?:?]
        at java.net.ServerSocket.accept(ServerSocket.java:513) ~[?:?]
        at org.eclipse.smarthome.model.lsp.internal.ModelServer.listen(ModelServer.java:80) ~[?:?]
        at org.eclipse.smarthome.model.lsp.internal.ModelServer.lambda$0(ModelServer.java:58) ~[?:?]
        at java.lang.Thread.run(Thread.java:745) [?:?]
```

**Comment by mherwege** [comment]
I have the same error on shutdown with the latest build, OH #1130.
