### ISSUE TITLE
java.lang.ClassCastException in DiscoveryServiceRegistryImpl

### ISSUE THREAD

**Issue by kgoderis** [eclipse/smarthome#4672]
In build 2.2.0~20171203035709-1, with 

openhab> bundle:list | grep LIF
212 │ Active   │  80 │ 0.9.0.201712011551     │ Eclipse SmartHome LIFX Binding

One get these:
```
2017-12-03 10:39:53.658 [ERROR] [nternal.DiscoveryServiceRegistryImpl] - Cannot notify the DiscoveryListener org.eclipse.smarthome.config.discovery.internal.PersistentInbox on Thing discovered event!
java.lang.ClassCastException: org.eclipse.smarthome.config.discovery.internal.DiscoveryResultImpl cannot be cast to org.eclipse.smarthome.config.discovery.DiscoveryResult
	at org.eclipse.smarthome.config.discovery.internal.PersistentInbox.get(PersistentInbox.java:396) ~[?:?]
	at org.eclipse.smarthome.config.discovery.internal.PersistentInbox.add(PersistentInbox.java:182) ~[?:?]
	at org.eclipse.smarthome.config.discovery.internal.PersistentInbox.thingDiscovered(PersistentInbox.java:322) ~[?:?]
	at org.eclipse.smarthome.config.discovery.internal.DiscoveryServiceRegistryImpl$2.run(DiscoveryServiceRegistryImpl.java:291) ~[?:?]
	at org.eclipse.smarthome.config.discovery.internal.DiscoveryServiceRegistryImpl$2.run(DiscoveryServiceRegistryImpl.java:1) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at org.eclipse.smarthome.config.discovery.internal.DiscoveryServiceRegistryImpl.thingDiscovered(DiscoveryServiceRegistryImpl.java:288) ~[?:?]
	at org.eclipse.smarthome.config.discovery.AbstractDiscoveryService.thingDiscovered(AbstractDiscoveryService.java:291) ~[?:?]
	at org.eclipse.smarthome.binding.lifx.internal.LifxLightDiscovery.handlePacket(LifxLightDiscovery.java:440) ~[?:?]
	at org.eclipse.smarthome.binding.lifx.internal.LifxLightDiscovery.receiveAndHandlePackets(LifxLightDiscovery.java:350) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
```

**Comment by kaikreuzer** [comment]
Is that an installation from scratch or do you maybe have some old bundles in there?

Btw, could you please always use code fences when posting logs? It makes reading it sooooo much easier!

**Comment by kgoderis** [comment]
@kaikreuzer That was after an upgrade through "apt-get install openhab2=[version]". I would expect all bundles to be upgraded to their latest versions, but you hint that this is not the case then?

**Comment by kaikreuzer** [comment]
No, I am not hinting at that. But it would be the best explanation for me for a ClassCastException - I would not know how else this could possibly happen here.

**Comment by kgoderis** [comment]
@kaikreuzer Weird because the exception occurs when converting between classes that are part of the same bundle. I am not an expert in bundle management, but that should not be possible by definition, no?

**Comment by maggu2810** [comment]
The BSN is not marked as singleton, so there could be different ones available.
Can you try to start with an empty Karaf data directory and without any old discovery results?
Also the output of `bundle:list -t 0 -l` could be interesting (if the error is still be present).

**Comment by triller-telekom** [comment]
@kgoderis Were you able to reproduce this in the meantime? Otherwise I would also blame it to an update issue and maybe you can close this (old) issue?
