### ISSUE TITLE
IllegalStateException in ScriptServiceUtil

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#4730]
On a very slow system, I just found this in the log during startup:

```
2017-12-13 13:44:17.536 [ERROR] [xt.xbase.jvmmodel.JvmModelAssociator] - Error calling inferrer
java.lang.IllegalStateException: ScriptServiceUtil not initialized yet!
	at org.eclipse.smarthome.model.script.ScriptServiceUtil.getInstance(ScriptServiceUtil.java:82)
	at org.eclipse.smarthome.model.script.ScriptServiceUtil.getItemRegistry(ScriptServiceUtil.java:97)
	at org.eclipse.smarthome.model.script.internal.engine.ServiceTrackerItemRegistryProvider.get(ServiceTrackerItemRegistryProvider.java:29)
	at org.eclipse.smarthome.model.script.internal.engine.ServiceTrackerItemRegistryProvider.get(ServiceTrackerItemRegistryProvider.java:1)
	at org.eclipse.smarthome.model.rule.jvmmodel.RulesJvmModelInferrer.lambda$0(RulesJvmModelInferrer.java:175)
	at org.eclipse.xtext.xbase.jvmmodel.JvmModelAssociator$1.run(JvmModelAssociator.java:397)
	at org.eclipse.xtext.xbase.jvmmodel.JvmModelAssociator.installDerivedState(JvmModelAssociator.java:407)
	at org.eclipse.xtext.resource.DerivedStateAwareResource.installDerivedState(DerivedStateAwareResource.java:242)
	at org.eclipse.xtext.xbase.resource.BatchLinkableResource.getContents(BatchLinkableResource.java:148)[145:org.eclipse.xtext.xbase:2.9.2.v20160428-1452]
	at org.eclipse.xtext.linking.lazy.LazyURIEncoder.resolveShortFragment(LazyURIEncoder.java:168)[141:org.eclipse.xtext:2.9.2]
	at org.eclipse.xtext.linking.lazy.LazyURIEncoder.decode(LazyURIEncoder.java:130)[141:org.eclipse.xtext:2.9.2]
	at org.eclipse.xtext.xbase.resource.BatchLinkableResource.getEObject(BatchLinkableResource.java:113)[145:org.eclipse.xtext.xbase:2.9.2.v20160428-1452]
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.getEObject(ResourceSetImpl.java:223)
	at org.eclipse.emf.ecore.util.EcoreUtil.resolve(EcoreUtil.java:199)
	at org.eclipse.emf.ecore.util.EcoreUtil.resolve(EcoreUtil.java:259)
	at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eResolveProxy(BasicEObjectImpl.java:1477)
	at org.eclipse.xtext.xbase.impl.XAbstractFeatureCallImplCustom.getFeature(XAbstractFeatureCallImplCustom.java:48)
	at org.eclipse.xtext.xbase.validation.XbaseValidator.checkReferInvalidTypes(XbaseValidator.java:1904)
	at sun.reflect.GeneratedMethodAccessor34.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[:1.8.0_152]
	at java.lang.reflect.Method.invoke(Method.java:498)[:1.8.0_152]
	at org.eclipse.xtext.validation.AbstractDeclarativeValidator$MethodWrapper.invoke(AbstractDeclarativeValidator.java:118)[141:org.eclipse.xtext:2.9.2]
	at org.eclipse.xtext.validation.AbstractDeclarativeValidator.internalValidate(AbstractDeclarativeValidator.java:312)[141:org.eclipse.xtext:2.9.2]
	at org.eclipse.xtext.validation.AbstractInjectableValidator.validate(AbstractInjectableValidator.java:71)[141:org.eclipse.xtext:2.9.2]
	at org.eclipse.xtext.validation.CompositeEValidator.validate(CompositeEValidator.java:151)[141:org.eclipse.xtext:2.9.2]
	at org.eclipse.emf.ecore.util.Diagnostician.doValidate(Diagnostician.java:171)[64:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:158)[64:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:137)[64:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
	at org.eclipse.emf.ecore.util.Diagnostician.doValidateContents(Diagnostician.java:181)[64:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:161)[64:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:137)[64:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
	at org.eclipse.emf.ecore.util.Diagnostician.doValidateContents(Diagnostician.java:181)[64:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:161)[64:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:137)[64:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
	at org.eclipse.emf.ecore.util.Diagnostician.doValidateContents(Diagnostician.java:181)[64:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:161)[64:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:137)[64:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
	at org.eclipse.emf.ecore.util.Diagnostician.doValidateContents(Diagnostician.java:185)[64:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:161)[64:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:137)[64:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
	at org.eclipse.emf.ecore.util.Diagnostician.doValidateContents(Diagnostician.java:185)[64:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:161)[64:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:137)[64:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
	at org.eclipse.emf.ecore.util.Diagnostician.doValidateContents(Diagnostician.java:181)[64:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:161)[64:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:137)[64:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
	at org.eclipse.emf.ecore.util.Diagnostician.doValidateContents(Diagnostician.java:185)[64:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:161)[64:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:137)[64:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
	at org.eclipse.emf.ecore.util.Diagnostician.doValidateContents(Diagnostician.java:185)[64:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:161)[64:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:137)[64:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:108)[64:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
	at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.validateModel(ModelRepositoryImpl.java:265)[122:org.eclipse.smarthome.model.core:0.9.0.b5]
	at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.addOrRefreshModel(ModelRepositoryImpl.java:90)[122:org.eclipse.smarthome.model.core:0.9.0.b5]
	at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.checkFile(FolderObserver.java:234)[122:org.eclipse.smarthome.model.core:0.9.0.b5]
	at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.processWatchEvent(FolderObserver.java:297)[122:org.eclipse.smarthome.model.core:0.9.0.b5]
	at org.eclipse.smarthome.core.service.WatchQueueReader.run(WatchQueueReader.java:206)[98:org.eclipse.smarthome.core:0.9.0.b5]
	at java.lang.Thread.run(Thread.java:748)[:1.8.0_152]
2017-12-13 13:44:18.141 [ERROR] [xbase.resource.BatchLinkableResource] - resolution of uriFragment '|::0.2.1.2.0.0.2.1.0.0.0.6::0::/1' failed.
java.lang.IllegalStateException: ScriptServiceUtil not initialized yet!
	at org.eclipse.smarthome.model.script.ScriptServiceUtil.getInstance(ScriptServiceUtil.java:82)
	at org.eclipse.smarthome.model.script.ScriptServiceUtil.getActionServices(ScriptServiceUtil.java:117)
	at org.eclipse.smarthome.model.script.internal.engine.ServiceTrackerActionServiceProvider.get(ServiceTrackerActionServiceProvider.java:21)
	at org.eclipse.smarthome.model.script.internal.engine.ServiceTrackerActionServiceProvider.get(ServiceTrackerActionServiceProvider.java:1)
	at org.eclipse.smarthome.model.script.scoping.ScriptImplicitlyImportedTypes.getActionClasses(ScriptImplicitlyImportedTypes.java:100)
	at org.eclipse.smarthome.model.script.scoping.ScriptImplicitlyImportedTypes.getStaticImportClasses(ScriptImplicitlyImportedTypes.java:94)
	at org.eclipse.xtext.xbase.scoping.batch.ImplicitlyImportedFeatures.getStaticImportClasses(ImplicitlyImportedFeatures.java:66)
	at org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider.newSession(XbaseBatchScopeProvider.java:112)
	at org.eclipse.xtext.xbase.typesystem.internal.DefaultReentrantTypeResolver.resolve(DefaultReentrantTypeResolver.java:162)
	at org.eclipse.xtext.xbase.typesystem.internal.DefaultReentrantTypeResolver.reentrantResolve(DefaultReentrantTypeResolver.java:139)
	at org.eclipse.xtext.xbase.typesystem.internal.CachingBatchTypeResolver$LazyResolvedTypes.resolveTypes(CachingBatchTypeResolver.java:80)
	at org.eclipse.xtext.xbase.typesystem.internal.CachingBatchTypeResolver$2.process(CachingBatchTypeResolver.java:57)
	at org.eclipse.xtext.xbase.typesystem.internal.CachingBatchTypeResolver$2.process(CachingBatchTypeResolver.java:1)
	at org.eclipse.xtext.util.concurrent.IUnitOfWork$Void.exec(IUnitOfWork.java:37)
	at org.eclipse.xtext.util.OnChangeEvictingCache.execWithoutCacheClear(OnChangeEvictingCache.java:129)
	at org.eclipse.xtext.xbase.typesystem.internal.CachingBatchTypeResolver.doResolveTypes(CachingBatchTypeResolver.java:53)
	at org.eclipse.xtext.xbase.typesystem.internal.AbstractBatchTypeResolver.resolveTypes(AbstractBatchTypeResolver.java:69)
	at org.eclipse.xtext.xbase.resource.BatchLinkingService.resolveBatched(BatchLinkingService.java:60)
	at org.eclipse.xtext.xbase.resource.BatchLinkingService.resolveBatched(BatchLinkingService.java:41)
	at org.eclipse.xtext.xbase.resource.BatchLinkableResource.getEObject(BatchLinkableResource.java:117)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.getEObject(ResourceSetImpl.java:223)
	at org.eclipse.emf.ecore.util.EcoreUtil.resolve(EcoreUtil.java:199)
	at org.eclipse.emf.ecore.util.EcoreUtil.resolve(EcoreUtil.java:259)
	at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eResolveProxy(BasicEObjectImpl.java:1477)
	at org.eclipse.xtext.xbase.impl.XAbstractFeatureCallImplCustom.getFeature(XAbstractFeatureCallImplCustom.java:48)
	at org.eclipse.xtext.xbase.validation.XbaseValidator.checkReferInvalidTypes(XbaseValidator.java:1904)
	at sun.reflect.GeneratedMethodAccessor34.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[:1.8.0_152]
	at java.lang.reflect.Method.invoke(Method.java:498)[:1.8.0_152]
	at org.eclipse.xtext.validation.AbstractDeclarativeValidator$MethodWrapper.invoke(AbstractDeclarativeValidator.java:118)[141:org.eclipse.xtext:2.9.2]
	at org.eclipse.xtext.validation.AbstractDeclarativeValidator.internalValidate(AbstractDeclarativeValidator.java:312)[141:org.eclipse.xtext:2.9.2]
	at org.eclipse.xtext.validation.AbstractInjectableValidator.validate(AbstractInjectableValidator.java:71)[141:org.eclipse.xtext:2.9.2]
	at org.eclipse.xtext.validation.CompositeEValidator.validate(CompositeEValidator.java:151)[141:org.eclipse.xtext:2.9.2]
	at org.eclipse.emf.ecore.util.Diagnostician.doValidate(Diagnostician.java:171)[64:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:158)[64:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:137)[64:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
	at org.eclipse.emf.ecore.util.Diagnostician.doValidateContents(Diagnostician.java:181)[64:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:161)[64:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:137)[64:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
	at org.eclipse.emf.ecore.util.Diagnostician.doValidateContents(Diagnostician.java:181)[64:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:161)[64:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:137)[64:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
	at org.eclipse.emf.ecore.util.Diagnostician.doValidateContents(Diagnostician.java:181)[64:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:161)[64:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:137)[64:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
	at org.eclipse.emf.ecore.util.Diagnostician.doValidateContents(Diagnostician.java:185)[64:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:161)[64:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:137)[64:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
	at org.eclipse.emf.ecore.util.Diagnostician.doValidateContents(Diagnostician.java:185)[64:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:161)[64:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:137)[64:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
	at org.eclipse.emf.ecore.util.Diagnostician.doValidateContents(Diagnostician.java:181)[64:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:161)[64:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:137)[64:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
	at org.eclipse.emf.ecore.util.Diagnostician.doValidateContents(Diagnostician.java:185)[64:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:161)[64:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:137)[64:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
	at org.eclipse.emf.ecore.util.Diagnostician.doValidateContents(Diagnostician.java:185)[64:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:161)[64:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:137)[64:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:108)[64:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
	at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.validateModel(ModelRepositoryImpl.java:265)[122:org.eclipse.smarthome.model.core:0.9.0.b5]
	at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.addOrRefreshModel(ModelRepositoryImpl.java:90)[122:org.eclipse.smarthome.model.core:0.9.0.b5]
	at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.checkFile(FolderObserver.java:234)[122:org.eclipse.smarthome.model.core:0.9.0.b5]
	at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.processWatchEvent(FolderObserver.java:297)[122:org.eclipse.smarthome.model.core:0.9.0.b5]
	at org.eclipse.smarthome.core.service.WatchQueueReader.run(WatchQueueReader.java:206)[98:org.eclipse.smarthome.core:0.9.0.b5]
	at java.lang.Thread.run(Thread.java:748)[:1.8.0_152]
```

**Comment by kaikreuzer** [comment]
And on a closer look I see `0.9.0.b5` in that trace - so definitely outdated, closing the issue!
