### ISSUE TITLE
NPE while determining the correct profile for a channel

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#4733]
The latest ESH stable broke the openHAB build as some tests now fail with NPEs like:
```
java.lang.NullPointerException: null
	at org.eclipse.smarthome.core.thing.DefaultSystemChannelTypeProvider.getChannelType(DefaultSystemChannelTypeProvider.java:202)
	at org.eclipse.smarthome.core.thing.type.ChannelTypeRegistry.getChannelType(ChannelTypeRegistry.java:78)
	at org.eclipse.smarthome.core.thing.type.ChannelTypeRegistry.getChannelType(ChannelTypeRegistry.java:67)
	at org.eclipse.smarthome.core.thing.internal.profiles.SystemProfileFactory.getSuggestedProfileTypeUID(SystemProfileFactory.java:115)
	at org.eclipse.smarthome.core.thing.internal.CommunicationManager.determineProfileTypeUID(CommunicationManager.java:167)
	at org.eclipse.smarthome.core.thing.internal.CommunicationManager.getProfile(CommunicationManager.java:131)
	at org.eclipse.smarthome.core.thing.internal.CommunicationManager.lambda$11(CommunicationManager.java:322)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.concurrent.ConcurrentHashMap$ValueSpliterator.forEachRemaining(ConcurrentHashMap.java:3566)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.eclipse.smarthome.core.thing.internal.CommunicationManager.stateUpdated(CommunicationManager.java:319)
	at org.eclipse.smarthome.core.thing.internal.ThingManager$1.stateUpdated(ThingManager.java:140)
	at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.updateState(BaseThingHandler.java:301)
	at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.updateState(BaseThingHandler.java:322)
	at org.openhab.binding.feed.handler.FeedHandler.publishChannelIfLinked(FeedHandler.java:170)
	at org.openhab.binding.feed.handler.FeedHandler.handleCommand(FeedHandler.java:283)
	at org.eclipse.smarthome.core.thing.binding.ThingHandler$handleCommand.call(Unknown Source)
	at org.openhab.binding.feed.test.FeedHandlerTest.testIfThingStatusIsUpdated(FeedHandlerTest.groovy:341)```

Imho the test is correct - it IS possible to have channels without a type. So we must handle that case accordingly.

**Comment by kaikreuzer** [comment]
@martinvw FYI, in case you wonder why we do not have an openHAB build right now...

**Comment by sjka** [comment]
FTR: it got broken by #4680 - and as annoying the null-annotations are, this would have become obvious if the ChannelTypeRegistry had such annotations. I added them in #4735.
