### ISSUE TITLE
NPE in addDiscoveryService at startup

### ISSUE THREAD

**Issue by mhilbush** [eclipse/smarthome#4751]
Build 1140

I see this consistently at the very beginning of startup.

```
2017-12-15 10:19:43.443 [INFO ] [voicerss.internal.VoiceRSSTTSService] - Using VoiceRSS cache folder /opt/openhab2/userdata/voicerss/cache
2017-12-15 10:19:44.836 [INFO ] [.core.internal.i18n.I18nProviderImpl] - Locale set to en_US, Location set to XX.263122,-YY.742618, Time zone set to America/New_York
2017-12-15 10:19:45.706 [ERROR] [g.eclipse.smarthome.config.discovery] - [org.eclipse.smarthome.config.discovery.internal.DiscoveryServiceRegistryImpl(42)] The addDiscoveryService method has thrown an exception
java.lang.NullPointerException: null
	at org.eclipse.smarthome.config.discovery.internal.DiscoveryServiceRegistryImpl.addDiscoveryService(DiscoveryServiceRegistryImpl.java:453) [104:org.eclipse.smarthome.config.discovery:0.10.0.b1]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
	at org.apache.felix.scr.impl.inject.BaseMethod.invokeMethod(BaseMethod.java:229) [42:org.apache.felix.scr:2.0.12]
	at org.apache.felix.scr.impl.inject.BaseMethod.access$500(BaseMethod.java:39) [42:org.apache.felix.scr:2.0.12]
	at org.apache.felix.scr.impl.inject.BaseMethod$Resolved.invoke(BaseMethod.java:650) [42:org.apache.felix.scr:2.0.12]
	at org.apache.felix.scr.impl.inject.BaseMethod.invoke(BaseMethod.java:506) [42:org.apache.felix.scr:2.0.12]
	at org.apache.felix.scr.impl.inject.BindMethod.invoke(BindMethod.java:658) [42:org.apache.felix.scr:2.0.12]
	at org.apache.felix.scr.impl.manager.DependencyManager.doInvokeBindMethod(DependencyManager.java:1722) [42:org.apache.felix.scr:2.0.12]
	at org.apache.felix.scr.impl.manager.DependencyManager.open(DependencyManager.java:1556) [42:org.apache.felix.scr:2.0.12]
	at org.apache.felix.scr.impl.manager.SingleComponentManager.createImplementationObject(SingleComponentManager.java:261) [42:org.apache.felix.scr:2.0.12]
	at org.apache.felix.scr.impl.manager.SingleComponentManager.createComponent(SingleComponentManager.java:109) [42:org.apache.felix.scr:2.0.12]
	at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:906) [42:org.apache.felix.scr:2.0.12]
	at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:879) [42:org.apache.felix.scr:2.0.12]
	at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:823) [42:org.apache.felix.scr:2.0.12]
	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse$1.run(ServiceFactoryUse.java:212) [?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.factoryGetService(ServiceFactoryUse.java:210) [?:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.getService(ServiceFactoryUse.java:111) [?:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceConsumer$2.getService(ServiceConsumer.java:45) [?:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.getService(ServiceRegistrationImpl.java:496) [?:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.getService(ServiceRegistry.java:461) [?:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.getService(BundleContextImpl.java:619) [?:?]
	at com.eclipsesource.jaxrs.publisher.internal.ResourceTracker.addingService(ResourceTracker.java:39) [15:com.eclipsesource.jaxrs.publisher:5.3.1.201602281253]
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:941) [?:?]
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:870) [?:?]
	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256) [?:?]
	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229) [?:?]
	at org.osgi.util.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:901) [?:?]
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:109) [?:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:915) [?:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) [?:?]
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148) [?:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:862) [?:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:801) [?:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:127) [?:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:225) [?:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:464) [?:?]
	at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:887) [42:org.apache.felix.scr:2.0.12]
	at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:874) [42:org.apache.felix.scr:2.0.12]
	at org.apache.felix.scr.impl.manager.RegistrationManager.changeRegistration(RegistrationManager.java:132) [42:org.apache.felix.scr:2.0.12]
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.registerService(AbstractComponentManager.java:941) [42:org.apache.felix.scr:2.0.12]
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:741) [42:org.apache.felix.scr:2.0.12]
	at org.apache.felix.scr.impl.manager.DependencyManager$SingleStaticCustomizer.addedService(DependencyManager.java:1012) [42:org.apache.felix.scr:2.0.12]
	at org.apache.felix.scr.impl.manager.DependencyManager$SingleStaticCustomizer.addedService(DependencyManager.java:968) [42:org.apache.felix.scr:2.0.12]
	at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.customizerAdded(ServiceTracker.java:1215) [42:org.apache.felix.scr:2.0.12]
	at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.customizerAdded(ServiceTracker.java:1136) [42:org.apache.felix.scr:2.0.12]
	at org.apache.felix.scr.impl.manager.ServiceTracker$AbstractTracked.trackAdding(ServiceTracker.java:945) [42:org.apache.felix.scr:2.0.12]
	at org.apache.felix.scr.impl.manager.ServiceTracker$AbstractTracked.track(ServiceTracker.java:881) [42:org.apache.felix.scr:2.0.12]
	at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:1167) [42:org.apache.felix.scr:2.0.12]
	at org.apache.felix.scr.impl.BundleComponentActivator$ListenerInfo.serviceChanged(BundleComponentActivator.java:127) [42:org.apache.felix.scr:2.0.12]
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:109) [?:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:915) [?:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) [?:?]
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148) [?:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:862) [?:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:801) [?:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:127) [?:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:225) [?:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:464) [?:?]
	at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:887) [42:org.apache.felix.scr:2.0.12]
	at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:874) [42:org.apache.felix.scr:2.0.12]
	at org.apache.felix.scr.impl.manager.RegistrationManager.changeRegistration(RegistrationManager.java:132) [42:org.apache.felix.scr:2.0.12]
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.registerService(AbstractComponentManager.java:941) [42:org.apache.felix.scr:2.0.12]
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:741) [42:org.apache.felix.scr:2.0.12]
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.enableInternal(AbstractComponentManager.java:675) [42:org.apache.felix.scr:2.0.12]
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.enable(AbstractComponentManager.java:430) [42:org.apache.felix.scr:2.0.12]
	at org.apache.felix.scr.impl.manager.ConfigurableComponentHolder.enableComponents(ConfigurableComponentHolder.java:657) [42:org.apache.felix.scr:2.0.12]
	at org.apache.felix.scr.impl.BundleComponentActivator.initialEnable(BundleComponentActivator.java:341) [42:org.apache.felix.scr:2.0.12]
	at org.apache.felix.scr.impl.Activator.loadComponents(Activator.java:390) [42:org.apache.felix.scr:2.0.12]
	at org.apache.felix.scr.impl.Activator.access$200(Activator.java:54) [42:org.apache.felix.scr:2.0.12]
	at org.apache.felix.scr.impl.Activator$ScrExtension.start(Activator.java:265) [42:org.apache.felix.scr:2.0.12]
	at org.apache.felix.utils.extender.AbstractExtender.createExtension(AbstractExtender.java:254) [42:org.apache.felix.scr:2.0.12]
	at org.apache.felix.utils.extender.AbstractExtender.modifiedBundle(AbstractExtender.java:227) [42:org.apache.felix.scr:2.0.12]
	at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:482) [?:?]
	at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:415) [?:?]
	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:232) [?:?]
	at org.osgi.util.tracker.BundleTracker$Tracked.bundleChanged(BundleTracker.java:444) [?:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:903) [?:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) [?:?]
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148) [?:?]
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEventPrivileged(EquinoxEventPublisher.java:213) [?:?]
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:120) [?:?]
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:112) [?:?]
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor.publishModuleEvent(EquinoxContainerAdaptor.java:156) [?:?]
	at org.eclipse.osgi.container.Module.publishEvent(Module.java:476) [?:?]
	at org.eclipse.osgi.container.Module.start(Module.java:467) [?:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1620) [?:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1600) [?:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1571) [?:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1514) [?:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1) [?:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) [?:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340) [?:?]
```

**Comment by sjka** [comment]
@kaikreuzer @maggu2810: are we back at the hilarious discussion from #3617, or can you otherwise make some sense of this?

**Comment by kaikreuzer** [comment]
If I am not mistaken, it is easy to make sense out of it: A dynamic dependency can be injected at any time - before or after activation.
So in this case here, the discoveryService is injected before the safeCaller, which leads to the NPE - clearly a bug.
We don't really need the safe caller here at all, do we? After all, you call `addDiscoveryListener` without a safe call as well.

**Comment by mhilbush** [comment]
My binding has code like this:
```
    @Override
    public void setDiscoveryServiceCallback(DiscoveryServiceCallback callback) {
        this.callback = callback;
    }
```
In my testing today, I'm seeing `this.callback == null`

Would the above issue cause `this.callback` to be null?

The scenario is that my binding:
- discovers a device
- uses `this.callback` to determine if there already is a thing or inbox entry for this device
- if there isn't a thing or inbox entry, it adds the thing to the inbox

**Comment by maggu2810** [comment]
> A dynamic dependency can be injected at any time - before or after activation.
So in this case here, the discoveryService is injected before the safeCaller, which leads to the NPE - clearly a bug.

Yes, that is the point.
A mandatory component is set or unset as long as the component is not active.
A dynamic component can be set / unset all the time, it does not matter if the component is active or not.
So, if we don't need the safe caller, we should simply remove that usage.

If we need the safe caller, we need to differ between active and inactive component. And queue the handling of bound services while inactive to the activate method...

**Comment by maggu2810** [comment]
> Not sure if you had a chance to look at my question above

Not sure if you understand what @kaikreuzer and me has been written.
`addDiscoveryListener` has been called on a deactivated component and the safe caller has not been injected, yet. So, looking at the code, if safeCall is null, the `setDiscoveryServiceCallback` will not be called.

**Comment by mhilbush** [comment]
Obviously, I didn't understand what had been written.  Sorry for being so dense.

**Comment by maggu2810** [comment]
No prob. Has it been clear now? I will try to have a look at.

**Comment by sjka** [comment]
To be honest, I also don't see a real need to use the safeCaller for this use-case at all. I wouldn't expect the implementations to do more than simply accepting the given reference, i.e. that they _really are_ only setters with no potential to block anything. Therefore I'd rather vote for dropping the safeCaller usage at this place (and therefore from the entire `DiscoveryServiceRegistryImpl`) instead.

**Comment by kaikreuzer** [comment]
I was thinking about that answer as well on #4766, but then again I think #4766 brings additional value: Currently, the Registry service (`this`) is added to the discoveryService as a listener at a moment when it itself isn't activated yet - so there can be potentially calls coming in, which is rather unexpected. Imho, the logic in static setters should really be the bare minimum and most of it should be rather done in activate.

**Comment by maggu2810** [comment]
Also (as noted in #4766) in deactivate the list of discovery services is only cleared without any remove handling. That seems to be wrong.

**Comment by mhilbush** [comment]
In build 1187, while the NPE no longer occurs, in several bindings that use `setDiscoveryServiceCallback`, I am not seeing that method being called.

See community post [here](https://community.openhab.org/t/first-major-update-in-2-3-0-snapshot/38801/9) for more information.

**Comment by kaikreuzer** [comment]
@mhilbush Looking at the code in those discovery services, I wonder why the DiscoveryServiceCallback is used at all - it was only introduced if a bindings is able to do incremental discovery, but it should not be used to check whether a result is already there or not. I would claim that you could simply remove the whole if-statement. (But yes, this obviously does not explain why the callback isn't injected, so that needs to be investigated nonetheless).

**Comment by kaikreuzer** [comment]
No, the inbox itself checks if a Thing with the give id already exists and won't create an inbox entry in that case.

**Comment by mhilbush** [comment]
Ok, thanks. Has it always been that way?  I don't recall it being like that when I developed the bindings. But, I'm getting old and my memory is not what it used to be.  LOL

In any event, I removed that if-statement.  For the case where the thing doesn't exist already and there's no inbox entry already, I'm not getting anything in the inbox even though I'm calling `thingDiscovered`.  Ugh.

**Comment by kaikreuzer** [comment]
Yes, it has always been like that. Note that the callback was only introduced later upon request of the Z-Wave binding, which does incremental discovery.

**Comment by mhilbush** [comment]
Ok, I'll can submit a PR to remove that from both bindings.  

Unfortunately, I can't test because nothing is being added to the inbox.  Perhaps the same root cause as the discoveryServiceCallback?  Should this issue be reopened, or would you prefer I open a separate issue?

**Comment by mhilbush** [comment]
@kai  I can see in the IDE that my binding's discovery service starts before the PersistentInbox and DiscoveryServiceRegistry have started.  So when the binding calls thingDiscovered, there are no listeners registered, and the discovery result is not processed.  I have no clue why this would be the case.

I'll also caveat this with the fact that my ESH sources are out of date in the IDE.  I'm going to attempt to update them.

**Comment by mhilbush** [comment]
@kaikreuzer 

I updated to the latest sources.  No luck!

Then I looked at why the NTP binding's discovery service was working correctly.  It's defined like this.
```
@Component(service = DiscoveryService.class, immediate = true, configurationPid = "discovery.ntp")
public class NtpDiscovery extends AbstractDiscoveryService {
```

My binding is defined like this.
```
@Component(service = ExtendedDiscoveryService.class, immediate = true)
public class GlobalCacheDiscoveryService extends AbstractDiscoveryService implements ExtendedDiscoveryService {
```
I replaced it with this, and the inbox is now being populated.
```
@Component(service = DiscoveryService.class, immediate = true)
public class GlobalCacheDiscoveryService extends AbstractDiscoveryService {
```
I then did this and, not only is the inbox being populated, but setDiscoveryServiceCallback is being called. So it seems like the problem is setting `service = ExtendedDiscoveryService.class`  
```
@Component(service = DiscoveryService.class, immediate = true)
public class GlobalCacheDiscoveryService extends AbstractDiscoveryService implements ExtendedDiscoveryService {
```

That would suggest to me that it might've been broken since this commit?
https://github.com/openhab/openhab2-addons/commit/52f768a3f8f80ac30d98dfb286bac134116baf99#diff-20d869adac9ab48b4a6bfc46a34d68ae

WDYT?

**Comment by sjka** [comment]
Indeed, very good analysis! Looks like PR #2559 was not really precise in that respect: Subclasses of a service won't be injected as their superclasses.

**Comment by kaikreuzer** [comment]
Good finding indeed, @mhilbush!

**Comment by mhilbush** [comment]
Thanks. It took quite a few hours of digging to track this down.  At least now I have a somewhat better understanding of how discovery works. :-)
