### ISSUE TITLE
Maven build failed on Paper UI: Cannot find module 'internal/fs'

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#4863]
```
[INFO] ------------------------------------------------------------------------
[INFO] Building Eclipse SmartHome Paper UI 0.10.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ org.eclipse.smarthome.ui.paper ---
[INFO]
[INFO] --- tycho-packaging-plugin:1.0.0:build-qualifier (default-build-qualifier) @ org.eclipse.smarthome.ui.paper ---
[INFO] The project's OSGi version is 0.10.0.201801061155
[INFO]
[INFO] --- tycho-packaging-plugin:1.0.0:validate-id (default-validate-id) @ org.eclipse.smarthome.ui.paper ---
[INFO]
[INFO] --- tycho-packaging-plugin:1.0.0:validate-version (default-validate-version) @ org.eclipse.smarthome.ui.paper ---
[INFO]
[INFO] --- directory-maven-plugin:0.2:highest-basedir (directories) @ org.eclipse.smarthome.ui.paper ---
[INFO] Highest basedir set to: D:\dev\openhab2\git\smarthome
[INFO]
[INFO] --- build-helper-maven-plugin:1.8:add-source (add-source) @ org.eclipse.smarthome.ui.paper ---
[INFO] Source directory: D:\dev\openhab2\git\smarthome\extensions\ui\org.eclipse.smarthome.ui.paper\src\main\groovy added.
[INFO]
[INFO] --- frontend-maven-plugin:1.0:install-node-and-npm (Install node and npm) @ org.eclipse.smarthome.ui.paper ---
[INFO] Node v8.1.2 is already installed.
[INFO] NPM 5.0.3 is already installed.
[INFO]
[INFO] --- frontend-maven-plugin:1.0:npm (npm install) @ org.eclipse.smarthome.ui.paper ---
[INFO] Running 'npm install' in D:\dev\openhab2\git\smarthome\extensions\ui\org.eclipse.smarthome.ui.paper
[ERROR] npm ERR! code MODULE_NOT_FOUND
[ERROR] npm ERR! Cannot find module 'internal/fs'
[ERROR]
[ERROR] npm ERR! A complete log of this run can be found in:
[ERROR] npm ERR!     D:\dev\openhab2\git\smarthome\extensions\ui\org.eclipse.smarthome.ui.paper\npm_cache\_logs\2018-01-06T12_15_03_404Z-debug.log
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Eclipse SmartHome .................................. SUCCESS [  0.282 s]
[INFO] Eclipse SmartHome Bundles .......................... SUCCESS [  0.093 s]
[INFO] Eclipse SmartHome Test Components .................. SUCCESS [  0.016 s]
[INFO] Eclipse SmartHome Core Components .................. SUCCESS [  0.031 s]
[INFO] Eclipse SmartHome Core ............................. SUCCESS [ 24.065 s]
[INFO] Eclipse SmartHome Configurations ................... SUCCESS [  0.016 s]
[INFO] Eclipse SmartHome Configuration Core ............... SUCCESS [  6.797 s]
[INFO] Eclipse SmartHome Configuration XML ................ SUCCESS [  5.876 s]
[INFO] Eclipse SmartHome AutoUpdate Binding ............... SUCCESS [  4.079 s]
[INFO] Eclipse SmartHome Test ............................. SUCCESS [  6.250 s]
[INFO] Eclipse SmartHome I/O Components ................... SUCCESS [  0.031 s]
[INFO] Eclipse SmartHome Console .......................... SUCCESS [  4.204 s]
[INFO] Eclipse SmartHome Thing ............................ SUCCESS [ 10.486 s]
[INFO] Magic Bundle ....................................... SUCCESS [  4.422 s]
[INFO] Magic Bundle Tests ................................. SUCCESS [  3.782 s]
[INFO] Eclipse SmartHome Auth Components .................. SUCCESS [  0.015 s]
[INFO] Eclipse SmartHome JAAS Authentication .............. SUCCESS [  3.782 s]
[INFO] Eclipse SmartHome Configuration Dispatcher ......... SUCCESS [  4.453 s]
[INFO] Eclipse SmartHome Configuration Dispatcher Tests ... SUCCESS [  4.235 s]
[INFO] Eclipse SmartHome Configuration Core Tests ......... SUCCESS [  5.657 s]
[INFO] Eclipse SmartHome Configuration Discovery .......... SUCCESS [  5.610 s]
[INFO] Eclipse SmartHome mDNS Service ..................... SUCCESS [  3.766 s]
[INFO] Eclipse SmartHome Configuration mDNS Discovery ..... SUCCESS [  5.594 s]
[INFO] Eclipse SmartHome Core Thing XML ................... SUCCESS [  5.735 s]
[INFO] Eclipse SmartHome Configuration Discovery Tests .... SUCCESS [  7.439 s]
[INFO] Eclipse SmartHome Configuration UPnP Discovery ..... SUCCESS [  3.891 s]
[INFO] Eclipse SmartHome Configuration Serial ............. SUCCESS [  3.328 s]
[INFO] Eclipse SmartHome Config XML Tests ................. SUCCESS [  5.016 s]
[INFO] Eclipse SmartHome Core Audio ....................... SUCCESS [  4.891 s]
[INFO] Eclipse SmartHome Core Binding XML ................. SUCCESS [  4.282 s]
[INFO] Eclipse Smarthome Audio Test ....................... SUCCESS [  5.079 s]
[INFO] Eclipse SmartHome Sample Extension Service ......... SUCCESS [  3.531 s]
[INFO] Eclipse SmartHome REST Interface ................... SUCCESS [  4.766 s]
[INFO] Eclipse SmartHome Core ID .......................... SUCCESS [  3.579 s]
[INFO] Eclipse SmartHome ID Tests ......................... SUCCESS [  3.657 s]
[INFO] Eclipse SmartHome Core Tests ....................... SUCCESS [  9.501 s]
[INFO] Eclipse SmartHome Thing Tests ...................... SUCCESS [ 14.923 s]
[INFO] Eclipse SmartHome Core Persistence ................. SUCCESS [  5.110 s]
[INFO] Eclipse SmartHome Core Scheduler Service ........... SUCCESS [  3.750 s]
[INFO] Eclipse SmartHome Core Transformation Service ...... SUCCESS [  4.516 s]
[INFO] Eclipse SmartHome Core Binding XML Tests ........... SUCCESS [  4.907 s]
[INFO] Eclipse SmartHome Core Thing XML Tests ............. SUCCESS [  6.282 s]
[INFO] Eclipse SmartHome Core Voice ....................... SUCCESS [  6.079 s]
[INFO] Eclipse SmartHome Core Voice Test .................. SUCCESS [  4.875 s]
[INFO] Eclipse SmartHome Automation ....................... SUCCESS [  0.032 s]
[INFO] Eclipse SmartHome Automation API ................... SUCCESS [  5.250 s]
[INFO] Eclipse SmartHome Automation Commands .............. SUCCESS [  5.485 s]
[INFO] Eclipse SmartHome Automation Parser GSON ........... SUCCESS [  5.079 s]
[INFO] Eclipse SmartHome Automation Providers ............. SUCCESS [  5.110 s]
[INFO] Eclipse SmartHome Automation Provider File ......... SUCCESS [  4.297 s]
[INFO] Eclipse SmartHome Automation Core .................. SUCCESS [  6.079 s]
[INFO] Eclipse SmartHome Automation Core Tests ............ SUCCESS [  4.453 s]
[INFO] Eclipse SmartHome Automation Sample JSON ........... SUCCESS [  4.032 s]
[INFO] Eclipse SmartHome Automation Core Modules .......... SUCCESS [  4.594 s]
[INFO] Eclipse SmartHome Automation Core Module Tests ..... SUCCESS [  4.329 s]
[INFO] Eclipse SmartHome Automation Script Modules ........ SUCCESS [  4.453 s]
[INFO] Eclipse SmartHome Automation Media Modules ......... SUCCESS [  4.235 s]
[INFO] Eclipse SmartHome Automation Timer Modules ......... SUCCESS [  4.188 s]
[INFO] Eclipse SmartHome Automation Module Timer Tests .... SUCCESS [  5.048 s]
[INFO] Eclipse SmartHome Automation Script Default Scope .. SUCCESS [  4.203 s]
[INFO] Eclipse SmartHome Automation Script RuleSupport .... SUCCESS [  5.595 s]
[INFO] Eclipse SmartHome Automation Script Module Tests ... SUCCESS [  4.719 s]
[INFO] Eclipse SmartHome Automation Event Tests ........... SUCCESS [  5.094 s]
[INFO] Eclipse SmartHome Automation Integration Tests ..... SUCCESS [  8.688 s]
[INFO] Eclipse SmartHome Automation Sample Extension Java . SUCCESS [  5.423 s]
[INFO] Eclipse SmartHome Automation REST API .............. SUCCESS [  4.922 s]
[INFO] Eclipse SmartHome Automation Sample REST API ....... SUCCESS [  4.126 s]
[INFO] Eclipse SmartHome Automation Java Demo ............. SUCCESS [  3.656 s]
[INFO] Eclipse SmartHome Automation Json Demo ............. SUCCESS [  1.688 s]
[INFO] Eclipse SmartHome Automation Module Type Demo ...... SUCCESS [  4.735 s]
[INFO] Eclipse SmartHome Console for OSGi framework Eclipse Equinox SUCCESS [  4.188 s]
[INFO] Eclipse SmartHome Console for OSGi Console RFC 147 . SUCCESS [  6.219 s]
[INFO] Eclipse SmartHome Console for OSGi runtime Karaf ... SUCCESS [  3.907 s]
[INFO] Eclipse SmartHome Monitor .......................... SUCCESS [  3.485 s]
[INFO] Eclipse SmartHome Network I/O ...................... SUCCESS [  5.281 s]
[INFO] Eclipse SmartHome Network I/O Tests ................ SUCCESS [  3.782 s]
[INFO] Eclipse SmartHome IO REST Tests .................... SUCCESS [  4.469 s]
[INFO] Eclipse SmartHome Authentication Support for the REST Interface SUCCESS [  3.344 s]
[INFO] Eclipse SmartHome Basic Auth for the REST Interface  SUCCESS [  3.313 s]
[INFO] Eclipse SmartHome Core REST Interface .............. SUCCESS [  6.157 s]
[INFO] Eclipse SmartHome IO REST Core Tests ............... SUCCESS [  4.204 s]
[INFO] Eclipse SmartHome REST mDNS Announcer .............. SUCCESS [  3.359 s]
[INFO] Eclipse SmartHome REST JAX-RS Optimizations ........ SUCCESS [  3.454 s]
[INFO] Eclipse SmartHome SSE Interface .................... SUCCESS [  4.625 s]
[INFO] Eclipse SmartHome IO SSE Tests ..................... SUCCESS [  3.985 s]
[INFO] Eclipse SmartHome Models ........................... SUCCESS [  2.344 s]
[INFO] Eclipse SmartHome Model Core ....................... SUCCESS [  6.360 s]
[INFO] Eclipse SmartHome Model Lazy Generation ............ SUCCESS [  5.220 s]
[INFO] Eclipse SmartHome Model Sitemap .................... SUCCESS [ 33.597 s]
[INFO] Eclipse SmartHome Model Items ...................... SUCCESS [ 15.705 s]
[INFO] Eclipse SmartHome UIs .............................. SUCCESS [  0.031 s]
[INFO] Eclipse SmartHome UI ............................... SUCCESS [  6.704 s]
[INFO] Eclipse SmartHome Sitemap REST Interface ........... SUCCESS [  5.750 s]
[INFO] Eclipse SmartHome Core REST UI Logging Module ...... SUCCESS [  3.985 s]
[INFO] Eclipse SmartHome Voice REST Interface ............. SUCCESS [  3.938 s]
[INFO] Eclipse SmartHome DBus Transport ................... SUCCESS [  1.672 s]
[INFO] Eclipse SmartHome MQTT Transport ................... SUCCESS [  5.360 s]
[INFO] Eclipse SmartHome Mqtt Transport I/O Tests ......... SUCCESS [  4.532 s]
[INFO] Eclipse SmartHome UPnP Transport ................... SUCCESS [  4.969 s]
[INFO] Eclipse SmartHome IO UPnP Tests .................... SUCCESS [  4.954 s]
[INFO] Eclipse SmartHome Model Core Tests ................. SUCCESS [  6.063 s]
[INFO] Eclipse SmartHome Model Item IDE ................... SUCCESS [ 10.251 s]
[INFO] Eclipse SmartHome Model Items Runtime .............. SUCCESS [  4.172 s]
[INFO] Eclipse SmartHome Items Model Tests ................ SUCCESS [  5.532 s]
[INFO] Eclipse SmartHome Model Persistence ................ SUCCESS [ 14.439 s]
[INFO] Eclipse SmartHome Model Persistence IDE ............ SUCCESS [  9.157 s]
[INFO] Eclipse SmartHome Model Script ..................... SUCCESS [ 30.206 s]
[INFO] Eclipse SmartHome Model Rules ...................... SUCCESS [ 34.363 s]
[INFO] Eclipse SmartHome Model Rule IDE ................... SUCCESS [ 21.706 s]
[INFO] Eclipse SmartHome Model Script IDE ................. SUCCESS [ 17.439 s]
[INFO] Eclipse SmartHome Model Sitemap IDE ................ SUCCESS [ 19.705 s]
[INFO] Eclipse SmartHome Thing Model ...................... SUCCESS [ 19.831 s]
[INFO] Eclipse SmartHome Model Thing IDE .................. SUCCESS [  9.719 s]
[INFO] Eclipse SmartHome Language Server .................. SUCCESS [  5.720 s]
[INFO] Eclipse SmartHome Language Server Tests ............ SUCCESS [  5.688 s]
[INFO] Eclipse SmartHome Model Persistence Runtime ........ SUCCESS [  4.328 s]
[INFO] Eclipse SmartHome Model Persistence Tests .......... SUCCESS [  5.407 s]
[INFO] Eclipse SmartHome Model Rules Runtime .............. SUCCESS [  7.735 s]
[INFO] Eclipse SmartHome Model Rules Tests ................ SUCCESS [  1.719 s]
[INFO] Eclipse SmartHome Model Script Runtime ............. SUCCESS [  4.985 s]
[INFO] Eclipse SmartHome Model Script Tests ............... SUCCESS [  5.095 s]
[INFO] Eclipse SmartHome Model Sitemap Runtime ............ SUCCESS [  4.234 s]
[INFO] Eclipse SmartHome Thing Model Runtime .............. SUCCESS [  4.204 s]
[INFO] Eclipse SmartHome Thing Model Tests ................ SUCCESS [ 10.767 s]
[INFO] Eclipse SmartHome UI Tests ......................... SUCCESS [  4.844 s]
[INFO] Eclipse SmartHome UI Icon Support .................. SUCCESS [  4.782 s]
[INFO] Eclipse SmartHome UI Icon Tests .................... SUCCESS [  5.531 s]
[INFO] Eclipse SmartHome Storages ......................... SUCCESS [  0.032 s]
[INFO] Eclipse SmartHome JSON Storage ..................... SUCCESS [  5.625 s]
[INFO] Eclipse SmartHome Storage JSON Tests ............... SUCCESS [  5.157 s]
[INFO] Eclipse SmartHome MapDB Storage .................... SUCCESS [  5.266 s]
[INFO] Eclipse SmartHome Storage MapDB Tests .............. SUCCESS [  5.423 s]
[INFO] Eclipse SmartHome Extensions ....................... SUCCESS [  0.031 s]
[INFO] Eclipse SmartHome Bindings ......................... SUCCESS [  0.031 s]
[INFO] Eclipse SmartHome Astro Binding .................... SUCCESS [  8.392 s]
[INFO] Eclipse SmartHome Astro Binding Tests .............. SUCCESS [  6.579 s]
[INFO] Eclipse SmartHome DigitalSTROM Binding ............. SUCCESS [ 17.064 s]
[INFO] Eclipse Smarthome DMX Binding ...................... SUCCESS [  8.110 s]
[INFO] Eclipse Smarthome DMX Binding Tests ................ SUCCESS [  5.844 s]
[INFO] Eclipse SmartHome hue Binding ...................... SUCCESS [  7.626 s]
[INFO] Eclipse SmartHome hue Binding Tests ................ SUCCESS [  8.095 s]
[INFO] Eclipse SmartHome FSInternetRadio Binding .......... SUCCESS [  6.235 s]
[INFO] Eclipse Smarthome FSInternetRadio Binding Test ..... SUCCESS [  6.891 s]
[INFO] Eclipse SmartHome LIFX Binding ..................... SUCCESS [ 10.814 s]
[INFO] Eclipse SmartHome LIRC Binding ..................... SUCCESS [  6.626 s]
[INFO] Eclipse SmartHome NTP Binding ...................... SUCCESS [  5.719 s]
[INFO] Eclipse SmartHome NTP Binding Tests ................ SUCCESS [  6.407 s]
[INFO] SerialButton Binding ............................... SUCCESS [  4.860 s]
[INFO] Eclipse SmartHome Sonos Binding .................... SUCCESS [ 10.048 s]
[INFO] TR▒DFRI Binding .................................... SUCCESS [  7.422 s]
[INFO] TR▒DFRI Binding Tests .............................. SUCCESS [  5.657 s]
[INFO] WeatherUnderground Binding ......................... SUCCESS [  6.970 s]
[INFO] Eclipse SmartHome WeMo Binding ..................... SUCCESS [  8.079 s]
[INFO] Eclipse SmartHome Wemo Binding Tests ............... SUCCESS [ 10.329 s]
[INFO] Eclipse SmartHome YahooWeather Binding ............. SUCCESS [  5.563 s]
[INFO] Eclipse SmartHome Extension Service Extensions ..... SUCCESS [  0.031 s]
[INFO] Eclipse SmartHome IoT Marketplace Extension Service  SUCCESS [  6.470 s]
[INFO] Eclipse SmartHome IoT Marketplace Extension Automation Support SUCCESS [  4.844 s]
[INFO] Eclipse SmartHome IoT Marketplace Extension Service Test SUCCESS [  4.407 s]
[INFO] Eclipse SmartHome I/O Services ..................... SUCCESS [  0.031 s]
[INFO] Eclipse SmartHome JavaSound I/O .................... SUCCESS [  5.266 s]
[INFO] Eclipse SmartHome Web Audio Support ................ SUCCESS [  4.610 s]
[INFO] Eclipse SmartHome Transformation Services .......... SUCCESS [  0.031 s]
[INFO] Eclipse SmartHome Exec Transformation Service ...... SUCCESS [  4.282 s]
[INFO] Eclipse SmartHome Javascript Transformation Service  SUCCESS [  4.328 s]
[INFO] Eclipse SmartHome Map Transformation Service ....... SUCCESS [  4.626 s]
[INFO] Eclipse SmartHome Map Transformation Service Tests . SUCCESS [  5.125 s]
[INFO] Eclipse SmartHome Scale Transformation Service ..... SUCCESS [  5.798 s]
[INFO] Eclipse SmartHome Scale Transformation Service Tests SUCCESS [  5.000 s]
[INFO] Eclipse SmartHome RegEx Transformation Service ..... SUCCESS [  4.454 s]
[INFO] Eclipse SmartHome RegEx Transformation Service Tests SUCCESS [  4.375 s]
[INFO] Eclipse SmartHome XPath Transformation Service ..... SUCCESS [  4.313 s]
[INFO] Eclipse SmartHome XPath Transformation Service Tests SUCCESS [  4.282 s]
[INFO] Eclipse SmartHome JSonPath Transformation Service .. SUCCESS [  4.454 s]
[INFO] Eclipse SmartHome JSonPath Transformation Service Tests SUCCESS [  4.438 s]
[INFO] Eclipse SmartHome Xslt Transformation Service ...... SUCCESS [  5.063 s]
[INFO] Eclipse SmartHome Xslt Transformation Service Tests  SUCCESS [  4.281 s]
[INFO] Eclipse SmartHome UI Extensions .................... SUCCESS [  0.032 s]
[INFO] Eclipse SmartHome Icon Sets ........................ SUCCESS [  0.015 s]
[INFO] Eclipse SmartHome Classic Icon Set ................. SUCCESS [  5.813 s]
[INFO] Eclipse SmartHome Basic UI ......................... SUCCESS [ 15.377 s]
[INFO] Eclipse SmartHome Classic UI ....................... SUCCESS [  6.219 s]
[INFO] Eclipse SmartHome Paper UI ......................... FAILURE [  0.922 s]
[INFO] Eclipse SmartHome Voice Services ................... SKIPPED
[INFO] Eclipse SmartHome MacOS TTS ........................ SKIPPED
[INFO] Eclipse SmartHome Mac TTS Tests .................... SKIPPED
[INFO] Eclipse SmartHome Features ......................... SKIPPED
[INFO] Eclipse SmartHome Runtime Core Feature ............. SKIPPED
[INFO] Eclipse SmartHome Runtime Model Feature ............ SKIPPED
[INFO] Eclipse SmartHome Runtime UI Feature ............... SKIPPED
[INFO] Eclipse SmartHome Runtime REST Feature ............. SKIPPED
[INFO] Eclipse SmartHome Runtime Automation Feature ....... SKIPPED
[INFO] Eclipse SmartHome Runtime Equinox Console Feature .. SKIPPED
[INFO] Eclipse SmartHome Runtime RfC147 Console Feature ... SKIPPED
[INFO] Eclipse SmartHome Runtime Binding Feature .......... SKIPPED
[INFO] Eclipse SmartHome Test Dependencies ................ SKIPPED
[INFO] Eclipse SmartHome Karaf Features ................... SKIPPED
[INFO] Eclipse SmartHome Target Platform Feature .......... SKIPPED
[INFO] Eclipse SmartHome Core Feature ..................... SKIPPED
[INFO] Eclipse SmartHome Extensions Feature ............... SKIPPED
[INFO] Eclipse SmartHome Karaf Feature Verification ....... SKIPPED
[INFO] Eclipse SmartHome Products ......................... SKIPPED
[INFO] Eclipse SmartHome p2 Repository .................... SKIPPED
[INFO] Eclipse SmartHome Tools ............................ SKIPPED
[INFO] Eclipse SmartHome Archetypes ....................... SKIPPED
[INFO] Eclipse Smarthome Binding Archetype ................ SKIPPED
[INFO] Eclipse Smarthome Binding Archetype Testsuite ...... SKIPPED
[INFO] Eclipse SmartHome Target Platform .................. SKIPPED
[INFO] Eclipse SmartHome Distribution ..................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 19:09 min
[INFO] Finished at: 2018-01-06T13:15:03+01:00
[INFO] Final Memory: 465M/965M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.0:npm (npm install) on project org.eclipse.smarthome.ui.paper: Failed to run task: 'npm install' failed. (error code 1) -> [Help 1]
```

**Comment by lolodomo** [comment]
Here is my detailed logs:
```
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\dev\\openhab2\\git\\smarthome\\extensions\\ui\\org.eclipse.smarthome.ui.paper\\node\\node.exe',
1 verbose cli   'D:\\dev\\openhab2\\git\\smarthome\\extensions\\ui\\org.eclipse.smarthome.ui.paper\\node\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@5.0.3
3 info using node@v8.1.2
4 verbose npm-session b3d51170c6b550bc
5 verbose stack Error: Cannot find module 'internal/fs'
5 verbose stack     at Function.Module._resolveFilename (module.js:485:15)
5 verbose stack     at Function.Module._load (module.js:437:25)
5 verbose stack     at Module.require (module.js:513:17)
5 verbose stack     at require (internal/module.js:11:18)
5 verbose stack     at evalmachine.<anonymous>:40:20
5 verbose stack     at Object.<anonymous> (D:\dev\openhab2\git\smarthome\extensions\ui\org.eclipse.smarthome.ui.paper\node\node_modules\npm\node_modules\cmd-shim\node_modules\graceful-fs\fs.js:11:1)
5 verbose stack     at Module._compile (module.js:569:30)
5 verbose stack     at Object.Module._extensions..js (module.js:580:10)
5 verbose stack     at Module.load (module.js:503:32)
5 verbose stack     at tryModuleLoad (module.js:466:12)
5 verbose stack     at Function.Module._load (module.js:458:3)
5 verbose stack     at Module.require (module.js:513:17)
5 verbose stack     at require (internal/module.js:11:18)
5 verbose stack     at Object.<anonymous> (D:\dev\openhab2\git\smarthome\extensions\ui\org.eclipse.smarthome.ui.paper\node\node_modules\npm\node_modules\cmd-shim\node_modules\graceful-fs\graceful-fs.js:3:27)
5 verbose stack     at Module._compile (module.js:569:30)
5 verbose stack     at Object.Module._extensions..js (module.js:580:10)
6 verbose cwd D:\dev\openhab2\git\smarthome\extensions\ui\org.eclipse.smarthome.ui.paper
7 verbose Windows_NT 10.0.15063
8 verbose argv "D:\\dev\\openhab2\\git\\smarthome\\extensions\\ui\\org.eclipse.smarthome.ui.paper\\node\\node.exe" "D:\\dev\\openhab2\\git\\smarthome\\extensions\\ui\\org.eclipse.smarthome.ui.paper\\node\\node_modules\\npm\\bin\\npm-cli.js" "install"
9 verbose node v8.1.2
10 verbose npm  v5.0.3
11 error code MODULE_NOT_FOUND
12 error Cannot find module 'internal/fs'
13 verbose exit [ 1, true ]
```

**Comment by maggu2810** [comment]
I checked out the current master and did a full build -- no problem.

Then I did the following:

```sh
cd extensions/ui/org.eclipse.smarthome.ui.paper/
git clean -x -d -f .
mvn clean install
```

This triggers the rebuild of the Paper UI using a clean working copy and so should trigger all the npm / nodejs stuff to be fetched.

It ended up in a successful build, too.

**Comment by kaikreuzer** [comment]
@maggu2810 I wouldn't rule out that the problem only exists on Windows. @sjka wanted to test that today as well.

**Comment by lolodomo** [comment]
My PC runs Windows 10.

**Comment by lolodomo** [comment]
Any chance to fix the build on Windows ?

**Comment by maggu2810** [comment]
As I don't use Windows I can't help.

**Comment by lolodomo** [comment]
Still not work.
Maybe my nodejs version is too old ?
What nodejs and npm versions are recommended ?

**Comment by htreu** [comment]
When you run the maven build a local node & npm version is installed:

> 9 verbose node v8.1.2
10 verbose npm  v5.0.3

This works on travis/jenkins/<my machine> just fine.

**Comment by htreu** [comment]
You could actually try to build with your local npm as well: just run `npm install` in the paper ui root folder. I guess its always a good idea to clean at least the `node_modules` folder before doing so.

**Comment by sjka** [comment]
I just did a build on Windows with a clean repository (see https://github.com/eclipse/smarthome/issues/4863#issuecomment-355967082) and it also ran through. 

Although the NPM repository has been a bit flaky at times, I can't confirm that there is a general issue with the Paper UI build on Windows. Really, try cleaning your git workspace (or manually delete all the `node*` & `npm*` folders and `package-lock.json` and then build it again.

**Comment by lolodomo** [comment]
Sorry, I did not understand that the files to clean up were in my git repository but only searched in the folders that were mentioned in the link provided by @htreu.
I will try again this week-end.

**Comment by sjka** [comment]
Alternatively 

```sh
git clean -dfx extensions/ui/org.eclipse.smarthome.ui.paper
``` 

also does the trick - just note that you'll lose all uncommitted changes from the Paper UI and not only the cache stuff.

**Comment by lolodomo** [comment]
Thank you a lot, it is now working after running the git clean command that removed npm files I have not found (not searched at the right place).

**Comment by sjka** [comment]
Great! 
Thanks for the feedback.
