### ISSUE TITLE
[LSP] Many test failures from invalid URIs

### ISSUE THREAD

**Issue by 9037568** [eclipse/smarthome#4868]
20 tests fail due to invalid URIs in org.eclipse.smarthome.model.lsp.test.

Like this one:

````
Tests run: 24, Failures: 0, Errors: 20, Skipped: 0, Time elapsed: 0.136 sec <<< FAILURE! - in org.eclipse.smarthome.model.lsp.internal.MappingUriExtensionsTest
testGuessClientPath[0](org.eclipse.smarthome.model.lsp.internal.MappingUriExtensionsTest)  Time elapsed: 0.008 sec
testToPath_emfURI[0](org.eclipse.smarthome.model.lsp.internal.MappingUriExtensionsTest)  Time elapsed: 0.006 sec  <<< ERROR!
java.lang.IllegalArgumentException: Illegal character in authority at index 7: file://C:\Users\me\AppData\Local\Temp\junit7939295565267433128\conf
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.parseAuthority(URI.java:3186)
	at java.net.URI$Parser.parseHierarchical(URI.java:3097)
	at java.net.URI$Parser.parse(URI.java:3053)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URI.create(URI.java:850)
	at org.eclipse.smarthome.model.lsp.internal.MappingUriExtensions.toURI(MappingUriExtensions.java:170)
	at org.eclipse.smarthome.model.lsp.internal.MappingUriExtensions.map(MappingUriExtensions.java:160)
	at org.eclipse.smarthome.model.lsp.internal.MappingUriExtensions.toUri(MappingUriExtensions.java:93)
	at org.eclipse.smarthome.model.lsp.internal.MappingUriExtensionsTest.testToPath_emfURI(MappingUriExtensionsTest.java:122)
````

**Comment by kaikreuzer** [comment]
Might be related to different path separators on Windows - the official CI build (on Linux) does not show any such problems: https://ci.eclipse.org/smarthome/job/SmartHomeDistribution-Nightly/2416/

@sjka Could you check?

**Comment by lolodomo** [comment]
I can confirm this issue on Windows.
