### ISSUE TITLE
Circular reference detected trying to get service {org.eclipse.smarthome.core.audio.AudioSink}

### ISSUE THREAD

**Issue by cdjackson** [eclipse/smarthome#4955]
I'm trying to reinstall the IDE and can't get a fresh install to run. 
System is MacOS, Java 8 - everything has been updated to latest and p2 m2 caches cleaned. System starts, then there is this circular reference, and the system appears to hang. Terminating the execution doesn't work - it needs to be terminated with the Mac activity monitor.

```
2018-01-19 22:09:49.238 [DEBUG] [s.m.i.r.i.ItemRuntimeActivator:26   ] - Registered 'item' configuration parser
2018-01-19 22:09:49.274 [INFO ] [org.eclipse.jetty.util.log    :192  ] - Logging initialized @3132ms
2018-01-19 22:09:49.285 [INFO ] [.DefaultJettyAtJettyHomeHelper:159  ] - Configuring the default jetty server with [file:/Users/chris/Development/openHAB-2/git/openhab-distro/launch/home/./etc/jetty.xml, file:/Users/chris/Development/openHAB-2/git/openhab-distro/launch/home/./etc/jetty-http.xml, file:/Users/chris/Development/openHAB-2/git/openhab-distro/launch/home/./etc/jetty-deployer.xml]
2018-01-19 22:09:49.286 [INFO ] [.DefaultJettyAtJettyHomeHelper:164  ] - JETTY.HOME=/Users/chris/Development/openHAB-2/git/openhab-distro/launch/home/.
2018-01-19 22:09:49.286 [INFO ] [.DefaultJettyAtJettyHomeHelper:165  ] - JETTY.BASE=/Users/chris/Development/openHAB-2/git/openhab-distro/launch/home/.
2018-01-19 22:09:49.482 [INFO ] [rg.eclipse.jetty.server.Server:346  ] - jetty-9.3.22.v20171030
2018-01-19 22:09:49.556 [INFO ] [tty.util.ssl.SslContextFactory:290  ] - x509=X509@38fce59b(mykey,h=[openhab.org],w=[]) for SslContextFactory@784bf330(file:///Users/chris/Development/openHAB-2/git/openhab-distro/launch/home/etc/keystore,file:///Users/chris/Development/openHAB-2/git/openhab-distro/launch/home/etc/keystore)
2018-01-19 22:09:49.765 [INFO ] [jetty.server.AbstractConnector:278  ] - Started 0.0.0.0:8443@7be530f7{SSL,[ssl, http/1.1]}{0.0.0.0:8443}
2018-01-19 22:09:49.767 [INFO ] [jetty.server.AbstractConnector:278  ] - Started ServerConnector@d94394f{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2018-01-19 22:09:49.768 [INFO ] [rg.eclipse.jetty.server.Server:414  ] - Started @3626ms
2018-01-19 22:09:49.768 [INFO ] [.DefaultJettyAtJettyHomeHelper:185  ] - Default jetty server configured
2018-01-19 22:09:49.950 [DEBUG] [.s.r.i.SitemapRuntimeActivator:26   ] - Registered 'sitemap' configuration parser
2018-01-19 22:09:50.029 [DEBUG] [.m.t.r.i.ThingRuntimeActivator:26   ] - Registered 'thing' configuration parser
2018-01-19 22:09:50.099 [DEBUG] [.i.PersistenceRuntimeActivator:26   ] - Registered 'persistence' configuration parser
2018-01-19 22:09:50.275 [DEBUG] [.e.s.s.m.i.MapDbStorageService:57   ] - Opened MapDB file at '/Users/chris/Development/openHAB-2/git/openhab-distro/launch/home/userdata/mapdb/storage.mapdb'.
2018-01-19 22:09:50.425 [DEBUG] [.core.common.ThreadPoolManager:121  ] - Created scheduled thread pool 'discovery' of size 5
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2018-01-19 22:09:50.833 [INFO ] [.u.d.internal.DashboardService:62   ] - Started dashboard at http://192.168.2.14:8080
2018-01-19 22:09:50.834 [INFO ] [.u.d.internal.DashboardService:66   ] - Started dashboard at https://192.168.2.14:8443
2018-01-19 22:09:50.836 [INFO ] [.server.handler.ContextHandler:781  ] - Started o.e.j.s.ServletContextHandler@38fb7c60{/,null,AVAILABLE}
2018-01-19 22:09:50.947 [DEBUG] [s.i.t.m.internal.MDNSActivator:34   ] - mDNS service has been started.
2018-01-19 22:09:51.051 [DEBUG] [.i.t.m.internal.MDNSClientImpl:83   ] - mDNS service has been started (JmDNS-IP-1 for IP 192.168.2.14)
2018-01-19 22:09:51.096 [INFO ] [s.i.GenericScriptEngineFactory:37   ] - Activated scripting support for ECMAScript
2018-01-19 22:09:51.098 [DEBUG] [s.i.GenericScriptEngineFactory:38   ] - Activated scripting support with engine Oracle Nashorn(1.8.0_60) for ECMAScript(ECMA - 262 Edition 5.1) with mimetypes [application/javascript, application/ecmascript, text/javascript, text/ecmascript] and file extensions [js]
2018-01-19 22:09:51.100 [DEBUG] [.m.s.i.ScriptEngineManagerImpl:45   ] - ScriptManager loading...
2018-01-19 22:09:51.125 [DEBUG] [.c.d.internal.ConfigDispatcher:140  ] - Error loading exclusive pids from '/Users/chris/Development/openHAB-2/ws/.metadata/.plugins/org.eclipse.pde.core/openHAB_Runtime/org.eclipse.osgi/51/data/configdispatcher_pid_list.json': /Users/chris/Development/openHAB-2/ws/.metadata/.plugins/org.eclipse.pde.core/openHAB_Runtime/org.eclipse.osgi/51/data/configdispatcher_pid_list.json (No such file or directory)
2018-01-19 22:09:51.127 [DEBUG] [.c.d.internal.ConfigDispatcher:281  ] - Processing config file 'services.cfg'
2018-01-19 22:09:51.258 [DEBUG] [.core.common.ThreadPoolManager:121  ] - Created scheduled thread pool 'file-processing' of size 5
2018-01-19 22:09:51.267 [DEBUG] [.c.d.internal.ConfigDispatcher:281  ] - Processing config file 'basicui.cfg'
2018-01-19 22:09:51.273 [DEBUG] [.c.d.internal.ConfigDispatcher:281  ] - Processing config file 'classicui.cfg'
2018-01-19 22:09:51.286 [DEBUG] [.c.d.internal.ConfigDispatcher:281  ] - Processing config file 'logging.cfg'
2018-01-19 22:09:51.298 [DEBUG] [.c.t.i.TransformationActivator:39   ] - Transformation Service has been started.
2018-01-19 22:09:51.334 [DEBUG] [o.e.s.c.s.i.SchedulerActivator:39   ] - Scheduler has been started.
2018-01-19 22:09:51.370 [INFO ] [uartz.impl.StdSchedulerFactory:1184 ] - Using default implementation for ThreadExecutor
2018-01-19 22:09:51.427 [INFO ] [rtz.core.SchedulerSignalerImpl:61   ] - Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
2018-01-19 22:09:51.431 [INFO ] [rg.quartz.core.QuartzScheduler:240  ] - Quartz Scheduler v.2.2.1 created.
2018-01-19 22:09:51.432 [INFO ] [org.quartz.simpl.RAMJobStore  :155  ] - RAMJobStore initialized.
2018-01-19 22:09:51.433 [INFO ] [rg.quartz.core.QuartzScheduler:305  ] - Scheduler meta-data: Quartz Scheduler (v2.2.1) 'openHAB-job-scheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 2 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.

2018-01-19 22:09:51.434 [INFO ] [uartz.impl.StdSchedulerFactory:1339 ] - Quartz scheduler 'openHAB-job-scheduler' initialized from specified file: 'quartz.properties'
2018-01-19 22:09:51.434 [INFO ] [uartz.impl.StdSchedulerFactory:1343 ] - Quartz scheduler version: 2.2.1
2018-01-19 22:09:51.437 [INFO ] [rg.quartz.core.QuartzScheduler:575  ] - Scheduler openHAB-job-scheduler_$_NON_CLUSTERED started.
2018-01-19 22:09:51.527 [DEBUG] [io.rest.internal.RESTActivator:77   ] - REST API has been started.
osgi> 2018-01-19 22:09:51.925 [DEBUG] [s.c.d.AbstractDiscoveryService:404  ] - Background discovery for discovery service 'org.eclipse.smarthome.config.discovery.mdns.internal.MDNSDiscoveryService' enabled.
2018-01-19 22:09:52.132 [DEBUG] [.c.c.registry.AbstractRegistry:296  ] - Provider 'org.eclipse.smarthome.core.thing.ManagedThingProvider' has been added.
2018-01-19 22:09:52.685 [DEBUG] [s.c.d.AbstractDiscoveryService:404  ] - Background discovery for discovery service 'org.eclipse.smarthome.config.discovery.upnp.internal.UpnpDiscoveryService' enabled.
2018-01-19 22:09:52.732 [INFO ] [s.ui.paper.internal.PaperUIApp:48   ] - Started Paper UI at /paperui
2018-01-19 22:09:52.808 [DEBUG] [o.e.s.s.j.i.JsonStorageService:59   ] - Json Storage Service: Activated.
!SESSION 2018-01-19 22:09:46.430 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_60
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_GB
Framework arguments:  -application org.eclipse.ui.ide.workbench
Command-line arguments:  -application org.eclipse.ui.ide.workbench -data /Users/chris/Development/openHAB-2/ws/../runtime-org.openhab.runtime.product.product -dev file:/Users/chris/Development/openHAB-2/ws/.metadata/.plugins/org.eclipse.pde.core/openHAB_Runtime/dev.properties -os macosx -ws cocoa -arch x86_64 -consoleLog -console

!ENTRY org.apache.felix.scr 4 0 2018-01-19 22:09:52.937
!MESSAGE Circular reference detected trying to get service {org.eclipse.smarthome.core.audio.AudioSink}={service.id=153, service.bundleid=111, service.scope=bundle, component.name=org.eclipse.smarthome.io.javasoundsink, component.id=163}
 stack of references: ServiceReference: {org.eclipse.smarthome.core.audio.AudioSink}={service.id=153, service.bundleid=111, service.scope=bundle, component.name=org.eclipse.smarthome.io.javasoundsink, component.id=163}
ServiceReference: {org.eclipse.smarthome.core.audio.AudioManager, org.eclipse.smarthome.config.core.ConfigOptionProvider}={service.id=154, service.bundleid=114, service.scope=bundle, service.config.category=system, service.pid=org.eclipse.smarthome.audio, service.config.label=Audio, component.name=org.eclipse.smarthome.audio, service.config.description.uri=system:audio, component.id=165}

!STACK 0
java.lang.Exception: stack trace
	at org.apache.felix.scr.impl.ComponentRegistry.enterCreate(ComponentRegistry.java:510)
	at org.apache.felix.scr.impl.BundleComponentActivator.enterCreate(BundleComponentActivator.java:809)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:817)
	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse$1.run(ServiceFactoryUse.java:212)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.factoryGetService(ServiceFactoryUse.java:210)
	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.getService(ServiceFactoryUse.java:111)
	at org.eclipse.osgi.internal.serviceregistry.ServiceConsumer$2.getService(ServiceConsumer.java:45)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.getService(ServiceRegistrationImpl.java:508)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.getService(ServiceRegistry.java:461)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.getService(BundleContextImpl.java:624)
	at org.apache.felix.scr.impl.manager.SingleRefPair.getServiceObject(SingleRefPair.java:72)
	at org.apache.felix.scr.impl.inject.BindMethod.getServiceObject(BindMethod.java:651)
	at org.apache.felix.scr.impl.manager.DependencyManager.getServiceObject(DependencyManager.java:2201)
	at org.apache.felix.scr.impl.manager.DependencyManager$MultipleDynamicCustomizer.prebind(DependencyManager.java:403)
	at org.apache.felix.scr.impl.manager.DependencyManager.prebind(DependencyManager.java:1520)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.collectDependencies(AbstractComponentManager.java:1006)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:859)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:823)
	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse$1.run(ServiceFactoryUse.java:212)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.factoryGetService(ServiceFactoryUse.java:210)
	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.getService(ServiceFactoryUse.java:111)
	at org.eclipse.osgi.internal.serviceregistry.ServiceConsumer$2.getService(ServiceConsumer.java:45)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.getService(ServiceRegistrationImpl.java:508)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.getService(ServiceRegistry.java:461)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.getService(BundleContextImpl.java:624)
	at com.eclipsesource.jaxrs.publisher.internal.ResourceTracker.addingService(ResourceTracker.java:39)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:941)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:1)
	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229)
	at org.osgi.util.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:901)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:109)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:920)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:862)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:801)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:127)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:225)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:469)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:887)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:874)
	at org.apache.felix.scr.impl.manager.RegistrationManager.changeRegistration(RegistrationManager.java:132)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.registerService(AbstractComponentManager.java:941)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:741)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.enableInternal(AbstractComponentManager.java:675)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.enable(AbstractComponentManager.java:430)
	at org.apache.felix.scr.impl.manager.ConfigurableComponentHolder.enableComponents(ConfigurableComponentHolder.java:657)
	at org.apache.felix.scr.impl.BundleComponentActivator.initialEnable(BundleComponentActivator.java:341)
	at org.apache.felix.scr.impl.Activator.loadComponents(Activator.java:390)
	at org.apache.felix.scr.impl.Activator.access$200(Activator.java:54)
	at org.apache.felix.scr.impl.Activator$ScrExtension.start(Activator.java:265)
	at org.apache.felix.utils.extender.AbstractExtender.createExtension(AbstractExtender.java:254)
	at org.apache.felix.utils.extender.AbstractExtender.modifiedBundle(AbstractExtender.java:227)
	at org.apache.felix.utils.extender.AbstractExtender.addingBundle(AbstractExtender.java:187)
	at org.osgi.util.tracker.BundleTracker$Tracked.customizerAdding(BundleTracker.java:469)
	at org.osgi.util.tracker.BundleTracker$Tracked.customizerAdding(BundleTracker.java:1)
	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229)
	at org.osgi.util.tracker.BundleTracker$Tracked.bundleChanged(BundleTracker.java:444)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:908)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEventPrivileged(EquinoxEventPublisher.java:213)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:120)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:112)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor.publishModuleEvent(EquinoxContainerAdaptor.java:168)
	at org.eclipse.osgi.container.Module.publishEvent(Module.java:476)
	at org.eclipse.osgi.container.Module.doStart(Module.java:548)
	at org.eclipse.osgi.container.Module.start(Module.java:449)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:468)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:103)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:529)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:328)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:368)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:446)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:395)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:387)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.loadClass(EquinoxBundle.java:564)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.initDependencyManagers(AbstractComponentManager.java:976)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.collectDependencies(AbstractComponentManager.java:1003)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:859)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:823)
	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse$1.run(ServiceFactoryUse.java:212)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.factoryGetService(ServiceFactoryUse.java:210)
	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.getService(ServiceFactoryUse.java:111)
	at org.eclipse.osgi.internal.serviceregistry.ServiceConsumer$2.getService(ServiceConsumer.java:45)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.getService(ServiceRegistrationImpl.java:508)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.getService(ServiceRegistry.java:461)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.getService(BundleContextImpl.java:624)
	at com.eclipsesource.jaxrs.publisher.internal.ResourceTracker.addingService(ResourceTracker.java:39)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:941)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:1)
	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229)
	at org.osgi.util.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:901)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:109)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:920)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:862)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:801)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:127)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:225)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:469)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:887)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:874)
	at org.apache.felix.scr.impl.manager.RegistrationManager.changeRegistration(RegistrationManager.java:132)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.registerService(AbstractComponentManager.java:941)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:741)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.enableInternal(AbstractComponentManager.java:675)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.enable(AbstractComponentManager.java:430)
	at org.apache.felix.scr.impl.manager.ConfigurableComponentHolder.enableComponents(ConfigurableComponentHolder.java:657)
	at org.apache.felix.scr.impl.BundleComponentActivator.initialEnable(BundleComponentActivator.java:341)
	at org.apache.felix.scr.impl.Activator.loadComponents(Activator.java:390)
	at org.apache.felix.scr.impl.Activator.access$200(Activator.java:54)
	at org.apache.felix.scr.impl.Activator$ScrExtension.start(Activator.java:265)
	at org.apache.felix.utils.extender.AbstractExtender.createExtension(AbstractExtender.java:254)
	at org.apache.felix.utils.extender.AbstractExtender.modifiedBundle(AbstractExtender.java:227)
	at org.apache.felix.utils.extender.AbstractExtender.addingBundle(AbstractExtender.java:187)
	at org.osgi.util.tracker.BundleTracker$Tracked.customizerAdding(BundleTracker.java:469)
	at org.osgi.util.tracker.BundleTracker$Tracked.customizerAdding(BundleTracker.java:1)
	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229)
	at org.osgi.util.tracker.BundleTracker$Tracked.bundleChanged(BundleTracker.java:444)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:908)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEventPrivileged(EquinoxEventPublisher.java:213)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:120)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:112)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor.publishModuleEvent(EquinoxContainerAdaptor.java:168)
	at org.eclipse.osgi.container.Module.publishEvent(Module.java:476)
	at org.eclipse.osgi.container.Module.doStart(Module.java:578)
	at org.eclipse.osgi.container.Module.start(Module.java:449)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1628)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1608)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1579)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1522)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
2018-01-19 22:09:52.998 [DEBUG] [.c.audio.internal.AudioServlet:65   ] - Starting up the audio servlet at /audio
2018-01-19 22:09:53.134 [DEBUG] [s.a.m.timer.internal.Activator:42   ] - started bundle timer.module
2018-01-19 22:09:53.156 [DEBUG] [.a.m.s.r.i.l.ScriptFileWatcher:203  ] - in queue: {js=[file:/Users/chris/Development/openHAB-2/git/openhab-distro/features/distro-resources/src/main/resources/automation/jsr223/demo.js]}
2018-01-19 22:09:53.255 [DEBUG] [.i.t.m.internal.MDNSClientImpl:111  ] - Registering new service _openhab-server._tcp.local. at 192.168.2.14:8080 (JmDNS-IP-1)
2018-01-19 22:09:53.274 [DEBUG] [.i.t.m.internal.MDNSClientImpl:111  ] - Registering new service _openhab-server-ssl._tcp.local. at 192.168.2.14:8443 (JmDNS-IP-1)
2018-01-19 22:09:53.280 [DEBUG] [.s.core.internal.CoreActivator:37   ] - Core bundle has been started.
2018-01-19 22:09:53.316 [DEBUG] [.core.common.ThreadPoolManager:86   ] - Updated scheduled thread pool 'discovery' to size 3
2018-01-19 22:09:53.317 [WARN ] [.core.common.ThreadPoolManager:94   ] - Ignoring invalid configuration for pool 'safeCall': 3,10 - value must be an integer
2018-01-19 22:09:53.500 [DEBUG] [.e.s.c.i.i18n.I18nProviderImpl:170  ] - No time zone set, falling back to the default time zone 'Europe/London'.
2018-01-19 22:09:53.501 [DEBUG] [.e.s.c.i.i18n.I18nProviderImpl:112  ] - No language set, falling back to the default locale
2018-01-19 22:09:53.686 [DEBUG] [.b.a.i.d.AstroDiscoveryService:96   ] - Scheduled astro location-changed job every 60 seconds
2018-01-19 22:09:53.687 [DEBUG] [s.c.d.AbstractDiscoveryService:404  ] - Background discovery for discovery service 'org.eclipse.smarthome.binding.astro.internal.discovery.AstroDiscoveryService' enabled.
2018-01-19 22:09:53.697 [DEBUG] [s.c.d.AbstractDiscoveryService:404  ] - Background discovery for discovery service 'org.eclipse.smarthome.binding.ntp.internal.discovery.NtpDiscovery' enabled.
2018-01-19 22:09:53.726 [DEBUG] [o.e.s.u.b.i.servlet.CmdServlet:62   ] - Starting up CMD servlet at /basicui/CMD
2018-01-19 22:09:53.761 [DEBUG] [.c.c.registry.AbstractRegistry:296  ] - Provider 'org.eclipse.smarthome.model.thing.internal.GenericItemChannelLinkProvider' has been added.
2018-01-19 22:09:53.762 [DEBUG] [.c.c.registry.AbstractRegistry:296  ] - Provider 'org.eclipse.smarthome.core.thing.link.ManagedItemChannelLinkProvider' has been added.
2018-01-19 22:09:53.780 [DEBUG] [.core.common.ThreadPoolManager:121  ] - Created scheduled thread pool 'thingLinkManager' of size 5
2018-01-19 22:09:53.798 [DEBUG] [.s.ExpressionThreadPoolManager:68   ] - Created an expression-drive scheduled thread pool 'persist' of size 5
2018-01-19 22:09:53.805 [DEBUG] [o.e.s.u.c.i.servlet.CmdServlet:62   ] - Starting up CMD servlet at /classicui/CMD
2018-01-19 22:09:53.828 [DEBUG] [.c.c.registry.AbstractRegistry:296  ] - Provider 'org.eclipse.smarthome.core.items.ManagedItemProvider' has been added.
2018-01-19 22:09:53.854 [DEBUG] [.c.c.registry.AbstractRegistry:296  ] - Provider 'org.eclipse.smarthome.core.thing.internal.ChannelItemProvider' has been added.
2018-01-19 22:09:55.856 [DEBUG] [.e.s.c.t.i.ChannelItemProvider:213  ] - Enabling channel item provider.
2018-01-19 22:10:18.164 [INFO ] [.a.m.s.r.i.l.ScriptFileWatcher:162  ] - Loading script 'demo.js'
2018-01-19 22:10:18.650 [ERROR] [.m.s.i.ScriptEngineManagerImpl:123  ] - Error during evaluation of script 'file:/Users/chris/Development/openHAB-2/git/openhab-distro/features/distro-resources/src/main/resources/automation/jsr223/demo.js': ReferenceError: "SimpleRule" is not defined in <eval> at line number 6
2018-01-19 22:10:18.650 [DEBUG] [.a.m.s.r.i.l.ScriptFileWatcher:170  ] - Script loaded: demo.js
```

**Comment by kaikreuzer** [comment]
Similar report was here: https://github.com/openhab/openhab2-addons/issues/2263#issuecomment-358778341

**Comment by kaikreuzer** [comment]
Did you already try to disable some unneeded bundles from your launch configuration (e.g. `org.eclipse.smarthome.core.audio`) and see if it starts then?

**Comment by cdjackson** [comment]
Yes - tried disabling some bundles but haven’t been able to isolate it. What I have found is if I wait a while (I think 10s of seconds, but I’ve not found the actual time) then things do seem to work, and the terminate will also work, so I guess something times out after a bit. No messages to go on though.

I’m also occasionally seeing other circular references for different services on startup.

**Comment by kaikreuzer** [comment]
Hm, sorry, I can not reproduce - it all starts up nicely in my IDE.
But I also occasionally see other circular references; I cannot tell when and how they disappeared, though :-/
My best advice would be to keep removing bundles that you do not need right now...

**Comment by ollie-dev** [comment]
@cdjackson, do you have some unusual audio interfaces installed? I have none connected right now, but used multichannel interfaces in the past. 
I disabled all audio, sound and voice bundles as well as the default bundles like hue and ntp. But I still won't get it to work - even after waiting some time. I also shut down my air-sonos service in my network to remove potential airplay issues on my MacBook Pro.

**Comment by cdjackson** [comment]
No - I only have a standard MacBook pro with no non-standard anything really.

**Comment by martinvw** [comment]
Would this maybe provide any new insights? 

https://github.com/openhab/openhab-core/issues/248

**Comment by sjka** [comment]
I also can't reproduce it here - nevertheless, if that's indeed the bugger on some systems, then we should apply the workaround here as well, but that should be confirmed first...

**Comment by soesas** [comment]
FYI I had the same problem. Uninstalling the openhabcloud Binding solved it for me - the error is gone.
