### ISSUE TITLE
D-Bus transport bundle exports missing packages

### ISSUE THREAD

**Issue by hsudbrock** [eclipse/smarthome#5159]
The manifest of the bundle `org.eclipse.smarthome.io.transport.dbus` exports the following bundles from the `cx.ath.matthew` namespace:
* `cx.ath.matthew.debug`
* `cx.ath.matthew.unix`
* `cx.ath.matthew.utils`

Since there is no source folder in this bundle, all these packages should be provided by the two jar files in the lib folder of the bundle. However, these lib files do not contain packages `cx.ath.matthew.debug` and `cx.ath.matthew.utils`, only `cx.ath.matthew.unix`.

When trying to use the dbus transport bundle, I get ClassNotFoundExceptions for the class `HexDump` from `cx.ath.matthew.utils`. This indicates that the missing packages should in fact be part of the bundle.

Is this just a faulty jar file in the lib folder? Or was there a reason to not include those packages? Or do I have a thinking error here, and those packages are not really missing but just somewhere where I did not look?

**Comment by kaikreuzer** [comment]
Good question.
@cdjackson Can you remember why these packages are not included?

**Comment by cdjackson** [comment]
If I remember correctly, they are not directly part of the dbus libs, but are separate libraries from the same author. I think it’s all under GPL, and we got permission from Matthew to use at least the dbus under EPL, but it might not have extended to the additional libraries. That said, I was just looking at the emails I exchanged with the author and it was not discussed, so I’m not 100% sure (sorry).

**Comment by kaikreuzer** [comment]
But I think to remember that you said that (at least the debug package) is also not required at runtime.
The utils package seems to be required, though.
@hsudbrock Which class do you instantiate when you see the ClassNotFoundException?

**Comment by hsudbrock** [comment]
@kaikreuzer The exception is thrown when I call `org.freedesktop.dbus.DBusResource#getConnection`, in the class `org.freedesktop.dbus.Transport$SASL`.

I looked into the most recent version of this class (cf. https://cgit.freedesktop.org/dbus/dbus-java/tree/org/freedesktop/dbus/Transport.java), and it imports classes from both `cx.ath.matthew.utils` and `cx.ath.matthew.debug`.

For completeness, here's the part of the stacktrace with the ClassNotFoundException:

```
Caused by: java.lang.NoClassDefFoundError: cx/ath/matthew/utils/Hexdump
	at org.freedesktop.dbus.Transport$SASL.stupidlyEncode(Unknown Source)
	at org.freedesktop.dbus.Transport$SASL.auth(Unknown Source)
	at org.freedesktop.dbus.Transport.connect(Unknown Source)
	at org.freedesktop.dbus.Transport.<init>(Unknown Source)
	at org.freedesktop.dbus.DBusConnection.<init>(Unknown Source)
	at org.freedesktop.dbus.DBusConnection.getConnection(Unknown Source)
	at <some.private.package>.DbusResource.activate(DbusResource.java:35)
```

**Comment by sjka** [comment]
Just for your info: Our CQ 11721 (PB 7825) for libmatthew covers the _entire_ library, not only the unix part. So from a legal point of view I don't see any issue with including it completely.

**Comment by maggu2810** [comment]
> we got permission from Matthew to use at least the dbus under EPL, but it might not have extended to the additional libraries.

@cdjackson Do you think it would be possible that Matthew dual licenses the sources of that code under the EPL, too? It would be great if the code base could be picked up and further improved (similar as jUPnP and JmDNS)
