### ISSUE TITLE
[Weather Underground] Error invoking #valueOf(String)

### ISSUE THREAD

**Issue by openhab-5iver** [eclipse/smarthome#5247]
OH 2.3.0 snapshot 1231
WU binding 0.10.0.201803161254

I don't know if this is an issue with the binding, [Units of Measurement](https://github.com/eclipse/smarthome/issues/5243), or my setup. All of my other weather items using UOM are working, but two of my items...
```
Number:Speed   Weather_Wind_Speed_Mph       "Wind Speed [%.0f mph]"	        <wind>	(gWeather)  {channel="weatherunderground:weather:71ed51c0:current#windSpeed"}
Number:Speed   Weather_Wind_Gust_Mph        "Wind Speed (gust) [%.0f mph]"	<wind>	(gWeather)  {channel="weatherunderground:weather:71ed51c0:current#windGust"}
```

... are getting values and displaying properly...
![image](https://user-images.githubusercontent.com/21967853/37562884-ffd1c598-2a48-11e8-91d2-6c2bf238199c.png)

...but appear to be occasionally causing an error:
```
2018-03-18 00:07:36.535 [ERROR] [clipse.smarthome.core.internal.events.EventHandler] - Creation of ESH-Event failed, because one of the registered event factories has thrown an exception: Error invoking #valueOf(String) on class 'org.eclipse.smarthome.core.library.types.QuantityType' with value '0E-22 mph'.
java.lang.IllegalStateException: Error invoking #valueOf(String) on class 'org.eclipse.smarthome.core.library.types.QuantityType' with value '0E-22 mph'.
        at org.eclipse.smarthome.core.items.events.ItemEventFactory.parseSimpleClassName(ItemEventFactory.java:178) ~[?:?]
        at org.eclipse.smarthome.core.items.events.ItemEventFactory.parseType(ItemEventFactory.java:146) ~[?:?]
        at org.eclipse.smarthome.core.items.events.ItemEventFactory.getState(ItemEventFactory.java:124) ~[?:?]
        at org.eclipse.smarthome.core.items.events.ItemEventFactory.createStateEvent(ItemEventFactory.java:111) ~[?:?]
        at org.eclipse.smarthome.core.items.events.ItemEventFactory.createEventByType(ItemEventFactory.java:77) ~[?:?]
        at org.eclipse.smarthome.core.events.AbstractEventFactory.createEvent(AbstractEventFactory.java:50) ~[?:?]
        at org.eclipse.smarthome.core.internal.events.EventHandler.createESHEvent(EventHandler.java:121) ~[?:?]
        at org.eclipse.smarthome.core.internal.events.EventHandler.handleEvent(EventHandler.java:95) ~[?:?]
        at org.eclipse.smarthome.core.internal.events.EventHandler.handleEvent(EventHandler.java:72) ~[?:?]
        at org.eclipse.smarthome.core.internal.events.ThreadedEventHandler.lambda$0(ThreadedEventHandler.java:71) ~[?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedMethodAccessor321.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
        at org.eclipse.smarthome.core.items.events.ItemEventFactory.parseSimpleClassName(ItemEventFactory.java:169) ~[?:?]
        ... 10 more
Caused by: java.lang.IllegalArgumentException: E not recognized (in 0 E-22 mph at index 2)
        at tec.uom.se.quantity.Quantities.getQuantity(Quantities.java:80) ~[?:?]
        at org.eclipse.smarthome.core.library.types.QuantityType.<init>(QuantityType.java:78) ~[?:?]
        at org.eclipse.smarthome.core.library.types.QuantityType.valueOf(QuantityType.java:121) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor321.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
        at org.eclipse.smarthome.core.items.events.ItemEventFactory.parseSimpleClassName(ItemEventFactory.java:169) ~[?:?]
        ... 10 more
```

**Comment by lolodomo** [comment]
@htreu : that is for you.

**Comment by htreu** [comment]
Hi @openhab-5iver thanks for reporting this issue. This indeed seems to be a Problem with the UoM support when parsing values like `0 E-22 mph`.
I will have a look.

**Comment by lolodomo** [comment]
If needed, the binding could first replace such value by 0.
