### ISSUE TITLE
core.config.ConfigurationService IllegalArgumentException with Magic binding

### ISSUE THREAD

**Issue by davidgraeff** [eclipse/smarthome#5291]
When setting the value of "Multiselect Integer - limit" of the Magic binding within PaperUI an exception is thrown.
![bildschirmfoto vom 2018-03-21 15-28-53](https://user-images.githubusercontent.com/66436/37715703-fa41a45a-2d1c-11e8-8b35-4cb7231527ee.png)

I get this stacktrace:
```
16:58:51.959 DEBUG o.e.s.i.r.JSONResponse$ExceptionMapper[:203] - exception during REST Handling
java.lang.IllegalArgumentException: java.math.BigDecimal in java.util.Vector
	at org.eclipse.equinox.internal.cm.ConfigurationDictionary.validateValue(ConfigurationDictionary.java:58)
	at org.eclipse.equinox.internal.cm.ConfigurationDictionary.put(ConfigurationDictionary.java:109)
	at org.eclipse.equinox.internal.cm.ConfigurationImpl.updateDictionary(ConfigurationImpl.java:338)
	at org.eclipse.equinox.internal.cm.ConfigurationImpl.update(ConfigurationImpl.java:310)
	at org.eclipse.smarthome.io.rest.core.config.ConfigurationService.update(ConfigurationService.java:132)
	at org.eclipse.smarthome.io.rest.core.config.ConfigurationService.update(ConfigurationService.java:71)
	at org.eclipse.smarthome.io.rest.core.internal.service.ConfigurableServiceResource.updateConfiguration(ConfigurableServiceResource.java:193)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by kaikreuzer** [comment]
@davidgraeff Has this been fixed meanwhile or is it still open? (I cannot fully interpret your commit comment on #5292...)

**Comment by davidgraeff** [comment]
I just mentioned this bug. If nobody worked on the magic binding, it may still exist. I have no Eclipse at hand right now to verify.
