### ISSUE TITLE
[test failures] NPE on JsonStorageTest

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#5352]
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.eclipse.smarthome.storage.json.internal.JsonStorageServiceOSGiTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.111 sec - in org.eclipse.smarthome.storage.json.internal.JsonStorageServiceOSGiTest
testSerialization(org.eclipse.smarthome.storage.json.internal.JsonStorageServiceOSGiTest)  Time elapsed: 0.065 sec
testClassloader(org.eclipse.smarthome.storage.json.internal.JsonStorageServiceOSGiTest)  Time elapsed: 0.001 sec
testConfiguration(org.eclipse.smarthome.storage.json.internal.JsonStorageServiceOSGiTest)  Time elapsed: 0.004 sec
testOverride(org.eclipse.smarthome.storage.json.internal.JsonStorageServiceOSGiTest)  Time elapsed: 0.002 sec
Running org.eclipse.smarthome.storage.json.internal.JSonStorageTest
Tests run: 5, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.049 sec <<< FAILURE! - in org.eclipse.smarthome.storage.json.internal.JSonStorageTest
testIntegerScaleFromDisk(org.eclipse.smarthome.storage.json.internal.JSonStorageTest)  Time elapsed: 0.022 sec
testStableOutput(org.eclipse.smarthome.storage.json.internal.JSonStorageTest)  Time elapsed: 0.004 sec  <<< ERROR!
java.lang.NullPointerException: null
	at org.eclipse.smarthome.storage.json.internal.JSonStorageTest$DummyObject.access$0(JSonStorageTest.java:131)
	at org.eclipse.smarthome.storage.json.internal.JSonStorageTest.lambda$0(JSonStorageTest.java:53)

allInsertedNumbersAreLoadedAsBigDecimalFromCache(org.eclipse.smarthome.storage.json.internal.JSonStorageTest)  Time elapsed: 0.003 sec
allInsertedNumbersAreLoadedAsBigDecimalFromDisk(org.eclipse.smarthome.storage.json.internal.JSonStorageTest)  Time elapsed: 0.007 sec
testIntegerScaleFromCache(org.eclipse.smarthome.storage.json.internal.JSonStorageTest)  Time elapsed: 0.002 sec

Results :

Tests in error: 
  JSonStorageTest.testStableOutput:119->persistAndReadAgain:50->JavaTest.waitForAssert:69->JavaTest.waitForAssert:116->JavaTest.waitForAssert:138->lambda$0:53 » NullPointer

Tests run: 9, Failures: 0, Errors: 1, Skipped: 0
```

* https://travis-ci.org/eclipse/smarthome/builds/361732358 [log-361732358.txt](https://github.com/eclipse/smarthome/files/1874945/log-361732358.txt)
* https://travis-ci.org/eclipse/smarthome/builds/361852430 [log-361852430.txt](https://github.com/eclipse/smarthome/files/1874947/log-361852430.txt)

**Comment by maggu2810** [comment]
I will provide a (potential) fix.
