### ISSUE TITLE
Maven build fails on windows in o.e.s.c.d.usbserial.linuxsysfs.test

### ISSUE THREAD

**Issue by J-N-K** [eclipse/smarthome#5369]
When run as user:

```
-------------------------------------------------------------------------------
Test set: org.eclipse.smarthome.config.discovery.usbserial.linuxsysfs.internal.SysFsUsbSerialScannerTest
-------------------------------------------------------------------------------
Tests run: 9, Failures: 0, Errors: 9, Skipped: 0, Time elapsed: 0.029 sec <<< FAILURE! - in org.eclipse.smarthome.config.discovery.usbserial.linuxsysfs.internal.SysFsUsbSerialScannerTest
testNoResultsIfNoTtyDevicesExist(org.eclipse.smarthome.config.discovery.usbserial.linuxsysfs.internal.SysFsUsbSerialScannerTest)  Time elapsed: 0.004 sec  <<< ERROR!
java.nio.file.FileSystemException: C:\Users\jnk\AppData\Local\Temp\junit7775225899746206963\aSymbolicLink: Dem Client fehlt ein erforderliches Recht.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.createSymbolicLink(WindowsFileSystemProvider.java:585)
	at java.nio.file.Files.createSymbolicLink(Files.java:1043)
	at org.eclipse.smarthome.config.discovery.usbserial.linuxsysfs.internal.SysFsUsbSerialScannerTest.systemSupportsSymLinks(SysFsUsbSerialScannerTest.java:211)
	at org.eclipse.smarthome.config.discovery.usbserial.linuxsysfs.internal.SysFsUsbSerialScannerTest.setup(SysFsUsbSerialScannerTest.java:66)

testIOExceptionIfSysfsTtyDoesNotExist(org.eclipse.smarthome.config.discovery.usbserial.linuxsysfs.internal.SysFsUsbSerialScannerTest)  Time elapsed: 0.002 sec  <<< ERROR!
java.nio.file.FileSystemException: C:\Users\jnk\AppData\Local\Temp\junit5854073097333524151\aSymbolicLink: Dem Client fehlt ein erforderliches Recht.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.createSymbolicLink(WindowsFileSystemProvider.java:585)
	at java.nio.file.Files.createSymbolicLink(Files.java:1043)
	at org.eclipse.smarthome.config.discovery.usbserial.linuxsysfs.internal.SysFsUsbSerialScannerTest.systemSupportsSymLinks(SysFsUsbSerialScannerTest.java:211)
	at org.eclipse.smarthome.config.discovery.usbserial.linuxsysfs.internal.SysFsUsbSerialScannerTest.setup(SysFsUsbSerialScannerTest.java:66)

testDeviceWithoutInterfaceNumberIsSkipped(org.eclipse.smarthome.config.discovery.usbserial.linuxsysfs.internal.SysFsUsbSerialScannerTest)  Time elapsed: 0.002 sec  <<< ERROR!
java.nio.file.FileSystemException: C:\Users\jnk\AppData\Local\Temp\junit2477551506471919703\aSymbolicLink: Dem Client fehlt ein erforderliches Recht.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.createSymbolicLink(WindowsFileSystemProvider.java:585)
	at java.nio.file.Files.createSymbolicLink(Files.java:1043)
	at org.eclipse.smarthome.config.discovery.usbserial.linuxsysfs.internal.SysFsUsbSerialScannerTest.systemSupportsSymLinks(SysFsUsbSerialScannerTest.java:211)
	at org.eclipse.smarthome.config.discovery.usbserial.linuxsysfs.internal.SysFsUsbSerialScannerTest.setup(SysFsUsbSerialScannerTest.java:66)

testNonUsbDeviceIsSkipped(org.eclipse.smarthome.config.discovery.usbserial.linuxsysfs.internal.SysFsUsbSerialScannerTest)  Time elapsed: 0.002 sec  <<< ERROR!
java.nio.file.FileSystemException: C:\Users\jnk\AppData\Local\Temp\junit3145093436986138284\aSymbolicLink: Dem Client fehlt ein erforderliches Recht.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.createSymbolicLink(WindowsFileSystemProvider.java:585)
	at java.nio.file.Files.createSymbolicLink(Files.java:1043)
	at org.eclipse.smarthome.config.discovery.usbserial.linuxsysfs.internal.SysFsUsbSerialScannerTest.systemSupportsSymLinks(SysFsUsbSerialScannerTest.java:211)
	at org.eclipse.smarthome.config.discovery.usbserial.linuxsysfs.internal.SysFsUsbSerialScannerTest.setup(SysFsUsbSerialScannerTest.java:66)

testDeviceWithoutVendorIdIsSkipped(org.eclipse.smarthome.config.discovery.usbserial.linuxsysfs.internal.SysFsUsbSerialScannerTest)  Time elapsed: 0.002 sec  <<< ERROR!
java.nio.file.FileSystemException: C:\Users\jnk\AppData\Local\Temp\junit4472392747282441051\aSymbolicLink: Dem Client fehlt ein erforderliches Recht.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.createSymbolicLink(WindowsFileSystemProvider.java:585)
	at java.nio.file.Files.createSymbolicLink(Files.java:1043)
	at org.eclipse.smarthome.config.discovery.usbserial.linuxsysfs.internal.SysFsUsbSerialScannerTest.systemSupportsSymLinks(SysFsUsbSerialScannerTest.java:211)
	at org.eclipse.smarthome.config.discovery.usbserial.linuxsysfs.internal.SysFsUsbSerialScannerTest.setup(SysFsUsbSerialScannerTest.java:66)

testNonWritableDeviceFilesAreSkipped(org.eclipse.smarthome.config.discovery.usbserial.linuxsysfs.internal.SysFsUsbSerialScannerTest)  Time elapsed: 0.002 sec  <<< ERROR!
java.nio.file.FileSystemException: C:\Users\jnk\AppData\Local\Temp\junit397327123893102222\aSymbolicLink: Dem Client fehlt ein erforderliches Recht.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.createSymbolicLink(WindowsFileSystemProvider.java:585)
	at java.nio.file.Files.createSymbolicLink(Files.java:1043)
	at org.eclipse.smarthome.config.discovery.usbserial.linuxsysfs.internal.SysFsUsbSerialScannerTest.systemSupportsSymLinks(SysFsUsbSerialScannerTest.java:211)
	at org.eclipse.smarthome.config.discovery.usbserial.linuxsysfs.internal.SysFsUsbSerialScannerTest.setup(SysFsUsbSerialScannerTest.java:66)

testNonReadableDeviceFilesAreSkipped(org.eclipse.smarthome.config.discovery.usbserial.linuxsysfs.internal.SysFsUsbSerialScannerTest)  Time elapsed: 0.002 sec  <<< ERROR!
java.nio.file.FileSystemException: C:\Users\jnk\AppData\Local\Temp\junit1111066963217495823\aSymbolicLink: Dem Client fehlt ein erforderliches Recht.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.createSymbolicLink(WindowsFileSystemProvider.java:585)
	at java.nio.file.Files.createSymbolicLink(Files.java:1043)
	at org.eclipse.smarthome.config.discovery.usbserial.linuxsysfs.internal.SysFsUsbSerialScannerTest.systemSupportsSymLinks(SysFsUsbSerialScannerTest.java:211)
	at org.eclipse.smarthome.config.discovery.usbserial.linuxsysfs.internal.SysFsUsbSerialScannerTest.setup(SysFsUsbSerialScannerTest.java:66)

testUsbSerialDevicesAreCorrectlyIdentified(org.eclipse.smarthome.config.discovery.usbserial.linuxsysfs.internal.SysFsUsbSerialScannerTest)  Time elapsed: 0.002 sec  <<< ERROR!
java.nio.file.FileSystemException: C:\Users\jnk\AppData\Local\Temp\junit1808379196483337993\aSymbolicLink: Dem Client fehlt ein erforderliches Recht.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.createSymbolicLink(WindowsFileSystemProvider.java:585)
	at java.nio.file.Files.createSymbolicLink(Files.java:1043)
	at org.eclipse.smarthome.config.discovery.usbserial.linuxsysfs.internal.SysFsUsbSerialScannerTest.systemSupportsSymLinks(SysFsUsbSerialScannerTest.java:211)
	at org.eclipse.smarthome.config.discovery.usbserial.linuxsysfs.internal.SysFsUsbSerialScannerTest.setup(SysFsUsbSerialScannerTest.java:66)

testDeviceWithoutProductIdIsSkipped(org.eclipse.smarthome.config.discovery.usbserial.linuxsysfs.internal.SysFsUsbSerialScannerTest)  Time elapsed: 0.001 sec  <<< ERROR!
java.nio.file.FileSystemException: C:\Users\jnk\AppData\Local\Temp\junit1672171452879926678\aSymbolicLink: Dem Client fehlt ein erforderliches Recht.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.createSymbolicLink(WindowsFileSystemProvider.java:585)
	at java.nio.file.Files.createSymbolicLink(Files.java:1043)
	at org.eclipse.smarthome.config.discovery.usbserial.linuxsysfs.internal.SysFsUsbSerialScannerTest.systemSupportsSymLinks(SysFsUsbSerialScannerTest.java:211)
	at org.eclipse.smarthome.config.discovery.usbserial.linuxsysfs.internal.SysFsUsbSerialScannerTest.setup(SysFsUsbSerialScannerTest.java:66)
```

as administrator:

```
-------------------------------------------------------------------------------
Test set: org.eclipse.smarthome.config.discovery.usbserial.linuxsysfs.internal.SysFsUsbSerialScannerTest
-------------------------------------------------------------------------------
Tests run: 9, Failures: 0, Errors: 9, Skipped: 0, Time elapsed: 0.279 sec <<< FAILURE! - in org.eclipse.smarthome.config.discovery.usbserial.linuxsysfs.internal.SysFsUsbSerialScannerTest
testNoResultsIfNoTtyDevicesExist(org.eclipse.smarthome.config.discovery.usbserial.linuxsysfs.internal.SysFsUsbSerialScannerTest)  Time elapsed: 0.048 sec  <<< ERROR!
java.nio.file.InvalidPathException: Illegal char <:> at index 19: sys/devices/pci0000:00/0000:00:14.0/usb1
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at sun.nio.fs.AbstractPath.resolve(AbstractPath.java:53)
	at org.eclipse.smarthome.config.discovery.usbserial.linuxsysfs.internal.SysFsUsbSerialScannerTest.setup(SysFsUsbSerialScannerTest.java:76)

testIOExceptionIfSysfsTtyDoesNotExist(org.eclipse.smarthome.config.discovery.usbserial.linuxsysfs.internal.SysFsUsbSerialScannerTest)  Time elapsed: 0.028 sec  <<< ERROR!
java.nio.file.InvalidPathException: Illegal char <:> at index 19: sys/devices/pci0000:00/0000:00:14.0/usb1
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at sun.nio.fs.AbstractPath.resolve(AbstractPath.java:53)
	at org.eclipse.smarthome.config.discovery.usbserial.linuxsysfs.internal.SysFsUsbSerialScannerTest.setup(SysFsUsbSerialScannerTest.java:76)

testDeviceWithoutInterfaceNumberIsSkipped(org.eclipse.smarthome.config.discovery.usbserial.linuxsysfs.internal.SysFsUsbSerialScannerTest)  Time elapsed: 0.027 sec  <<< ERROR!
java.nio.file.InvalidPathException: Illegal char <:> at index 19: sys/devices/pci0000:00/0000:00:14.0/usb1
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at sun.nio.fs.AbstractPath.resolve(AbstractPath.java:53)
	at org.eclipse.smarthome.config.discovery.usbserial.linuxsysfs.internal.SysFsUsbSerialScannerTest.setup(SysFsUsbSerialScannerTest.java:76)

testNonUsbDeviceIsSkipped(org.eclipse.smarthome.config.discovery.usbserial.linuxsysfs.internal.SysFsUsbSerialScannerTest)  Time elapsed: 0.027 sec  <<< ERROR!
java.nio.file.InvalidPathException: Illegal char <:> at index 19: sys/devices/pci0000:00/0000:00:14.0/usb1
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at sun.nio.fs.AbstractPath.resolve(AbstractPath.java:53)
	at org.eclipse.smarthome.config.discovery.usbserial.linuxsysfs.internal.SysFsUsbSerialScannerTest.setup(SysFsUsbSerialScannerTest.java:76)

testDeviceWithoutVendorIdIsSkipped(org.eclipse.smarthome.config.discovery.usbserial.linuxsysfs.internal.SysFsUsbSerialScannerTest)  Time elapsed: 0.026 sec  <<< ERROR!
java.nio.file.InvalidPathException: Illegal char <:> at index 19: sys/devices/pci0000:00/0000:00:14.0/usb1
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at sun.nio.fs.AbstractPath.resolve(AbstractPath.java:53)
	at org.eclipse.smarthome.config.discovery.usbserial.linuxsysfs.internal.SysFsUsbSerialScannerTest.setup(SysFsUsbSerialScannerTest.java:76)

testNonWritableDeviceFilesAreSkipped(org.eclipse.smarthome.config.discovery.usbserial.linuxsysfs.internal.SysFsUsbSerialScannerTest)  Time elapsed: 0.027 sec  <<< ERROR!
java.nio.file.InvalidPathException: Illegal char <:> at index 19: sys/devices/pci0000:00/0000:00:14.0/usb1
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at sun.nio.fs.AbstractPath.resolve(AbstractPath.java:53)
	at org.eclipse.smarthome.config.discovery.usbserial.linuxsysfs.internal.SysFsUsbSerialScannerTest.setup(SysFsUsbSerialScannerTest.java:76)

testNonReadableDeviceFilesAreSkipped(org.eclipse.smarthome.config.discovery.usbserial.linuxsysfs.internal.SysFsUsbSerialScannerTest)  Time elapsed: 0.028 sec  <<< ERROR!
java.nio.file.InvalidPathException: Illegal char <:> at index 19: sys/devices/pci0000:00/0000:00:14.0/usb1
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at sun.nio.fs.AbstractPath.resolve(AbstractPath.java:53)
	at org.eclipse.smarthome.config.discovery.usbserial.linuxsysfs.internal.SysFsUsbSerialScannerTest.setup(SysFsUsbSerialScannerTest.java:76)

testUsbSerialDevicesAreCorrectlyIdentified(org.eclipse.smarthome.config.discovery.usbserial.linuxsysfs.internal.SysFsUsbSerialScannerTest)  Time elapsed: 0.027 sec  <<< ERROR!
java.nio.file.InvalidPathException: Illegal char <:> at index 19: sys/devices/pci0000:00/0000:00:14.0/usb1
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at sun.nio.fs.AbstractPath.resolve(AbstractPath.java:53)
	at org.eclipse.smarthome.config.discovery.usbserial.linuxsysfs.internal.SysFsUsbSerialScannerTest.setup(SysFsUsbSerialScannerTest.java:76)

testDeviceWithoutProductIdIsSkipped(org.eclipse.smarthome.config.discovery.usbserial.linuxsysfs.internal.SysFsUsbSerialScannerTest)  Time elapsed: 0.026 sec  <<< ERROR!
java.nio.file.InvalidPathException: Illegal char <:> at index 19: sys/devices/pci0000:00/0000:00:14.0/usb1
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at sun.nio.fs.AbstractPath.resolve(AbstractPath.java:53)
	at org.eclipse.smarthome.config.discovery.usbserial.linuxsysfs.internal.SysFsUsbSerialScannerTest.setup(SysFsUsbSerialScannerTest.java:76)
```

**Comment by maggu2810** [comment]
IMHO the whole linux sysfs tests should not be executed on Windows at all.
If this is tests are executed on every platform at the moment, Maven profiles should be used to add that test module on OS family linux only.

**Comment by sjka** [comment]
The tests create the necessary file system structure in a subdirectory of the temp folder and operate there. So they are not necessarily bound to be executed on linux, they e.g. run perfectly fine on macOS despite that it doesn't have a `/sys/...` filesystem.
In any case, Windows disqualified itself due to the fact that `:` are not allowed in filenames because it is reserved as a drive delimiter.

**Comment by maggu2810** [comment]
Hm, then it is more complicated.
If will fail on every filesystem that does not accept `:` in its path names.
If could also fail on Unix based systems if such a filesystem has been chosen for the ESH source tree.
