### ISSUE TITLE
[test failures] HueLightHandlerOSGiTest

### ISSUE THREAD

**Issue by sjka** [eclipse/smarthome#5451]
From https://ci.eclipse.org/smarthome/job/SmartHomeDistribution-Nightly/2663:

```
java.lang.AssertionError: 
Expected: is "LCT001"
     but: was null
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.junit.Assert$assertThat.callStatic(Unknown Source)
	at org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest$_assertSendCommand_closure11$_closure21.doCall(HueLightHandlerOSGiTest.groovy:502)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:278)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
	at groovy.lang.Closure.call(Closure.java:423)
	at groovy.lang.Closure.call(Closure.java:439)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.with(DefaultGroovyMethods.java:235)
	at org.codehaus.groovy.runtime.dgm$614.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:271)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest$_assertSendCommand_closure11.doCall(HueLightHandlerOSGiTest.groovy:501)
	at org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest$_assertSendCommand_closure11.doCall(HueLightHandlerOSGiTest.groovy)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:278)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
	at groovy.lang.Closure.call(Closure.java:423)
	at groovy.lang.Closure.call(Closure.java:417)
	at groovy.lang.Closure.run(Closure.java:504)
	at org.eclipse.smarthome.test.java.JavaTest.waitForAssert(JavaTest.java:154)
	at org.eclipse.smarthome.test.java.JavaTest.waitForAssert(JavaTest.java:116)
	at org.eclipse.smarthome.test.java.JavaTest.waitForAssert(JavaTest.java:69)
	at sun.reflect.GeneratedMethodAccessor177.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:207)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:141)
	at org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest.assertSendCommand(HueLightHandlerOSGiTest.groovy:500)
	at org.eclipse.smarthome.binding.hue.test.HueLightHandlerOSGiTest.assertSendCommand(HueLightHandlerOSGiTest.groovy)
```

[consoleText.txt](https://github.com/eclipse/smarthome/files/1941834/consoleText.txt)

**Comment by sjka** [comment]
Another one (with the same stacktrace): 
https://ci.eclipse.org/smarthome/job/SmartHomeDistribution-Nightly/2690
