### ISSUE TITLE
[test failures] DiscoveryServiceRegistryOSGiTest

### ISSUE THREAD

**Issue by sjka** [eclipse/smarthome#5452]
From https://ci.eclipse.org/smarthome/job/SmartHomeDistribution-Nightly/2666:

```
org.mockito.exceptions.verification.WantedButNotInvoked: 
Wanted but not invoked:
scanListener.onFinished();
-> at org.eclipse.smarthome.config.discovery.DiscoveryServiceRegistryOSGiTest.lambda$6(DiscoveryServiceRegistryOSGiTest.java:224)
Actually, there were zero interactions with this mock.

	at org.eclipse.smarthome.config.discovery.DiscoveryServiceRegistryOSGiTest.lambda$6(DiscoveryServiceRegistryOSGiTest.java:224)
```

[consoleText.txt](https://github.com/eclipse/smarthome/files/1941984/consoleText.txt)

**Comment by sjka** [comment]
Another one  with a different error.
From https://ci.eclipse.org/smarthome/job/SmartHomeDistribution-Nightly/2693:

```
Running org.eclipse.smarthome.config.discovery.DiscoveryServiceRegistryOSGiTest
Tests run: 18, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 19.967 sec <<< FAILURE! - in org.eclipse.smarthome.config.discovery.DiscoveryServiceRegistryOSGiTest
testStan_faulty(org.eclipse.smarthome.config.discovery.DiscoveryServiceRegistryOSGiTest)  Time elapsed: 0.064 sec
testStartScan_bindingId(org.eclipse.smarthome.config.discovery.DiscoveryServiceRegistryOSGiTest)  Time elapsed: 1.077 sec
testStartScan_nonExisting(org.eclipse.smarthome.config.discovery.DiscoveryServiceRegistryOSGiTest)  Time elapsed: 0.019 sec
testAbortScan_nonExisting(org.eclipse.smarthome.config.discovery.DiscoveryServiceRegistryOSGiTest)  Time elapsed: 0.019 sec
testCache(org.eclipse.smarthome.config.discovery.DiscoveryServiceRegistryOSGiTest)  Time elapsed: 2.062 sec
testStartScan_twoDiscoveryServices(org.eclipse.smarthome.config.discovery.DiscoveryServiceRegistryOSGiTest)  Time elapsed: 0.018 sec
testRemoveOlderResults_onlyOfSpecificBridge(org.eclipse.smarthome.config.discovery.DiscoveryServiceRegistryOSGiTest)  Time elapsed: 1.039 sec
testRemoveOlderResults_works(org.eclipse.smarthome.config.discovery.DiscoveryServiceRegistryOSGiTest)  Time elapsed: 10.365 sec  <<< FAILURE!
org.mockito.exceptions.verification.TooLittleActualInvocations: 
scanListener.onFinished();
Wanted 2 times:
-> at org.eclipse.smarthome.config.discovery.DiscoveryServiceRegistryOSGiTest.lambda$7(DiscoveryServiceRegistryOSGiTest.java:234)
But was 1 time:
-> at org.eclipse.smarthome.config.discovery.AbstractDiscoveryService.stopScan(AbstractDiscoveryService.java:249)

	at org.eclipse.smarthome.config.discovery.DiscoveryServiceRegistryOSGiTest.lambda$7(DiscoveryServiceRegistryOSGiTest.java:234)

testThingDiscovered(org.eclipse.smarthome.config.discovery.DiscoveryServiceRegistryOSGiTest)  Time elapsed: 1.034 sec
testAbortScan_known(org.eclipse.smarthome.config.discovery.DiscoveryServiceRegistryOSGiTest)  Time elapsed: 0.018 sec
testRemoveOlderResults(org.eclipse.smarthome.config.discovery.DiscoveryServiceRegistryOSGiTest)  Time elapsed: 0.021 sec
testGetMaxScanTimeout(org.eclipse.smarthome.config.discovery.DiscoveryServiceRegistryOSGiTest)  Time elapsed: 0.015 sec
testGetExistingDiscoveryResult(org.eclipse.smarthome.config.discovery.DiscoveryServiceRegistryOSGiTest)  Time elapsed: 1.066 sec
testGetExistingThing(org.eclipse.smarthome.config.discovery.DiscoveryServiceRegistryOSGiTest)  Time elapsed: 0.014 sec
testThingDiscovered_removedListener(org.eclipse.smarthome.config.discovery.DiscoveryServiceRegistryOSGiTest)  Time elapsed: 1.026 sec
testRemoveOlderResults_onlySameService(org.eclipse.smarthome.config.discovery.DiscoveryServiceRegistryOSGiTest)  Time elapsed: 2.056 sec
testSupportsDiscovery(org.eclipse.smarthome.config.discovery.DiscoveryServiceRegistryOSGiTest)  Time elapsed: 0.018 sec
testStartScan_existing(org.eclipse.smarthome.config.discovery.DiscoveryServiceRegistryOSGiTest)  Time elapsed: 0.018 sec
```
