### ISSUE TITLE
Basic UI: visibility defined in sitemap partly not working

### ISSUE THREAD

**Issue by toseRN** [eclipse/smarthome#5567]
Platform information:

Hardware: RPi 3 B+
OS: raspbian stretch
openHAB version: openHAB 2.3.0 (Build #1272)
oracle java 1.8.0_65

In BasicUI the sitemap property visibility partly not working, but the classic UI works well with the same sitemap and item definitions. in example:

**item definition**
`Switch      KZ1Hide             "more"          <returnpipe>`
`Switch	    hue_1			    "hue 1"				            {channel="hue:0200:1:1:color" }`

**sitemap definition**
`Frame {`
 `       		Slider item=Licht_KZ`
`				Switch item=hue_1`
 `               Slider item=hue_1_Dimmer visibility=[hue_1==ON]`
 `               Colorpicker item=hue_1_Color visibility=[hue_1==ON]`
`            }`
`			Frame {`
`				Switch item=KZ1Hide`
`				Text label=" " icon="none" visibility=[KZ1Hide==ON]`
`				Setpoint item=TempControl_KZ1_soll label="Solltemperatur [%.1f °C]" visibility=[KZ1Hide==ON] minValue=18 maxValue=25 step=0.5`
`				Switch item=TempControl_KZ1_ label="heat control" mappings=[100="Auto",101="ON",102="OFF",103="-2°"] visibility=[KZ1Hide==ON]`
`			}`

In the first Frame with item hue_1 the slider and colorpicker are visible then hue_1 is ON. But it takes same seconds in BasicUI. (in Classic UI - immediately )

In the second frame with switch item KZ1Hide the following text, setpoint and switch items are only visible then browser tab manuell refreshed.

Hint: The switch (KZ1Hide) state will show immediatly in Basic UI then changed from another Device.

**Comment by htreu** [comment]
@lolodomo could you have a look at this? With the provided item & sitemap definitions both visibility triggers are also not working for me.
Here is a more complete item setup:
```
Switch hue_1 "hue 1"
Dimmer hue_1_Dimmer "Hue1 Dimmer"
Color hue_1_Color "Hue 1 Color"
Switch KZ1Hide "more" <returnpipe>
Number TempControl_KZ1_soll
Switch TempControl_KZ1_
```

and sitemap:

```
sitemap demo label="Demo Sitemap" {
	Frame {
        Switch item=hue_1
        Slider item=hue_1_Dimmer visibility=[hue_1==ON]
        Colorpicker item=hue_1_Color visibility=[hue_1==ON]
    }
    Frame {
        Switch item=KZ1Hide
        Text label=" " icon="none" visibility=[KZ1Hide==ON]
        Setpoint item=TempControl_KZ1_soll label="Solltemperatur [%.1f °C]" visibility=[KZ1Hide==ON] minValue=18 maxValue=25 step=0.5
        Switch item=TempControl_KZ1_ label="heat control" mappings=[100="Auto",101="ON",102="OFF",103="-2°"] visibility=[KZ1Hide==ON]
    }
}
```

**Comment by lolodomo** [comment]
I could have a look ... when I have free time for that

**Comment by lolodomo** [comment]
Tested in my production environment (snapshot 1262) and it is working perfectly.

Unfortunately, I can't test with the current ESH code in Eclipse. I have first a compile error in  class GenericMetadataProvider due to an include of org.eclipse.emf.codegen.ecore.templates.edit.ItemProvider
If I remove this include, it is replaced by this include org.eclipse.smarthome.core.items.ItemProvider
Then the code is compiling but then at running time I got this exception I don't understand:
```
!ENTRY org.eclipse.smarthome.io.rest.sitemap 4 0 2018-05-18 09:36:07.671
!MESSAGE [org.eclipse.smarthome.io.rest.sitemap.SitemapSubscriptionService(242)] The addSitemapProvider method has thrown an exception
!STACK 0
java.lang.AbstractMethodError
	at org.eclipse.smarthome.io.rest.sitemap.SitemapSubscriptionService.addSitemapProvider(SitemapSubscriptionService.java:107)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.felix.scr.impl.inject.BaseMethod.invokeMethod(BaseMethod.java:229)
	at org.apache.felix.scr.impl.inject.BaseMethod.access$500(BaseMethod.java:39)
	at org.apache.felix.scr.impl.inject.BaseMethod$Resolved.invoke(BaseMethod.java:650)
	at org.apache.felix.scr.impl.inject.BaseMethod.invoke(BaseMethod.java:506)
	at org.apache.felix.scr.impl.inject.BindMethod.invoke(BindMethod.java:658)
	at org.apache.felix.scr.impl.manager.DependencyManager.doInvokeBindMethod(DependencyManager.java:1722)
	at org.apache.felix.scr.impl.manager.DependencyManager.invokeBindMethod(DependencyManager.java:1699)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.invokeBindMethod(SingleComponentManager.java:372)
	at org.apache.felix.scr.impl.manager.DependencyManager$MultipleDynamicCustomizer.addedService(DependencyManager.java:320)
	at org.apache.felix.scr.impl.manager.DependencyManager$MultipleDynamicCustomizer.addedService(DependencyManager.java:291)
	at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.customizerAdded(ServiceTracker.java:1215)
	at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.customizerAdded(ServiceTracker.java:1136)
	at org.apache.felix.scr.impl.manager.ServiceTracker$AbstractTracked.trackAdding(ServiceTracker.java:945)
	at org.apache.felix.scr.impl.manager.ServiceTracker$AbstractTracked.track(ServiceTracker.java:881)
	at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:1167)
	at org.apache.felix.scr.impl.BundleComponentActivator$ListenerInfo.serviceChanged(BundleComponentActivator.java:127)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:109)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:920)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:862)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:801)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:127)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:225)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:469)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:887)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:874)
	at org.apache.felix.scr.impl.manager.RegistrationManager.changeRegistration(RegistrationManager.java:132)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.registerService(AbstractComponentManager.java:941)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:741)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.enableInternal(AbstractComponentManager.java:675)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.enable(AbstractComponentManager.java:430)
	at org.apache.felix.scr.impl.manager.ConfigurableComponentHolder.enableComponents(ConfigurableComponentHolder.java:657)
	at org.apache.felix.scr.impl.BundleComponentActivator.initialEnable(BundleComponentActivator.java:341)
	at org.apache.felix.scr.impl.Activator.loadComponents(Activator.java:390)
	at org.apache.felix.scr.impl.Activator.access$200(Activator.java:54)
	at org.apache.felix.scr.impl.Activator$ScrExtension.start(Activator.java:265)
	at org.apache.felix.utils.extender.AbstractExtender.createExtension(AbstractExtender.java:254)
	at org.apache.felix.utils.extender.AbstractExtender.modifiedBundle(AbstractExtender.java:227)
	at org.apache.felix.utils.extender.AbstractExtender.addingBundle(AbstractExtender.java:187)
	at org.osgi.util.tracker.BundleTracker$Tracked.customizerAdding(BundleTracker.java:469)
	at org.osgi.util.tracker.BundleTracker$Tracked.customizerAdding(BundleTracker.java:1)
	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229)
	at org.osgi.util.tracker.BundleTracker$Tracked.bundleChanged(BundleTracker.java:444)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:908)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEventPrivileged(EquinoxEventPublisher.java:213)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:120)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:112)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor.publishModuleEvent(EquinoxContainerAdaptor.java:168)
	at org.eclipse.osgi.container.Module.publishEvent(Module.java:476)
	at org.eclipse.osgi.container.Module.doStart(Module.java:578)
	at org.eclipse.osgi.container.Module.start(Module.java:449)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1628)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1608)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1579)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1522)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
```
So I can't confirm the problem but if the problem really exists, it is recent.

**Comment by htreu** [comment]
@lolodomo did you try to clean all projects? Also, on the current master you may have to run the `Generate All Models.launch` from the `org.eclipse.smarthome.model.codegen` project once to re-create all xtext models.

**Comment by lolodomo** [comment]
I have now moved my production environment to the snapshot 1281 and I can reproduce the problem.
So it was broken after 1262.
I have done a change in this part so it could be my fault.
As soon as I can get a working Eclipse environment, I will debug that.

**Comment by lolodomo** [comment]
The problem was the target platform. Moving from the OpenHAB target platform to the Eclipse smarthome target platform fixed most of the compilation errors. But now I am fighting to have Basic UI running.
I started from the only launch configuration I found which is named "SmartHome Runtime Sample Rules" and then try to add everything that is required. I have now a dashboard runniong with Paper UI but still no Basic UI. Direct link is not working too. Bundles are checked.
Is there no predefined launch configuration for a standard Eclipse configuration with Paper UI, Basic UI and the demo files ?

I will certainly forgive if I don't get help,

**Comment by lolodomo** [comment]
The problem is the target platform. I need to switch to the Eclipse Smarthome target platform to have the sources compiling.
But in this case I am not able to get a working launch configuration.
```
2018-05-18 14:43:46.912 [DEBUG] [.i.PersistenceRuntimeActivator:26   ] - Registered 'persistence' configuration parser
2018-05-18 14:43:46.972 [DEBUG] [.m.t.r.i.ThingRuntimeActivator:26   ] - Registered 'thing' configuration parser
2018-05-18 14:43:47.003 [DEBUG] [s.m.i.r.i.ItemRuntimeActivator:26   ] - Registered 'item' configuration parser
!SESSION 2018-05-18 14:43:45.584 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_131
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=fr_FR
Framework arguments:  -application org.eclipse.ui.ide.workbench
Command-line arguments:  -application org.eclipse.ui.ide.workbench -data D:\dev\openhab2\ws/../runtime-org.openhab.runtime.product.product -dev file:D:/dev/openhab2/ws/.metadata/.plugins/org.eclipse.pde.core/openHAB_Runtime/dev.properties -os win32 -ws win32 -arch x86_64 -consoleLog -console

!ENTRY org.eclipse.jetty.osgi.boot 4 0 2018-05-18 14:43:47.019
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.jetty.osgi.boot [57]
  Unresolved requirement: Import-Package: org.eclipse.jetty.annotations; version="[9.3.0,10.0.0)"; resolution:="optional"
  Unresolved requirement: Import-Package: org.eclipse.jetty.webapp; version="[9.3.0,10.0.0)"
    -> Export-Package: org.eclipse.jetty.webapp; bundle-symbolic-name="org.eclipse.jetty.webapp"; bundle-version="9.3.15.v20161220"; version="9.3.15"; uses:="javax.servlet,org.eclipse.jetty.security,org.eclipse.jetty.server,org.eclipse.jetty.server.handler,org.eclipse.jetty.server.session,org.eclipse.jetty.servlet,org.eclipse.jetty.util,org.eclipse.jetty.util.annotation,org.eclipse.jetty.util.resource,org.eclipse.jetty.xml"
       org.eclipse.jetty.webapp [108]
         Unresolved requirement: Import-Package: org.eclipse.jetty.security; version="[9.3.15,9.3.16)"
  Unresolved requirement: Import-Package: org.eclipse.jetty.deploy.bindings; version="[9.3.0,10.0.0)"
    -> Export-Package: org.eclipse.jetty.deploy.bindings; bundle-symbolic-name="org.eclipse.jetty.deploy"; bundle-version="9.3.15.v20161220"; version="9.3.15"; uses:="org.eclipse.jetty.deploy,org.eclipse.jetty.deploy.graph,org.eclipse.jetty.server"
       org.eclipse.jetty.deploy [11]
         Unresolved requirement: Import-Package: org.eclipse.jetty.jmx; version="[9.3.15,9.3.16)"; resolution:="optional"
         Unresolved requirement: Import-Package: org.eclipse.jetty.webapp; version="[9.3.15,9.3.16)"
           -> Export-Package: org.eclipse.jetty.webapp; bundle-symbolic-name="org.eclipse.jetty.webapp"; bundle-version="9.3.15.v20161220"; version="9.3.15"; uses:="javax.servlet,org.eclipse.jetty.security,org.eclipse.jetty.server,org.eclipse.jetty.server.handler,org.eclipse.jetty.server.session,org.eclipse.jetty.servlet,org.eclipse.jetty.util,org.eclipse.jetty.util.annotation,org.eclipse.jetty.util.resource,org.eclipse.jetty.xml"
  Unresolved requirement: Import-Package: org.eclipse.jetty.deploy.graph; version="[9.3.0,10.0.0)"
    -> Export-Package: org.eclipse.jetty.deploy.graph; bundle-symbolic-name="org.eclipse.jetty.deploy"; bundle-version="9.3.15.v20161220"; version="9.3.15"
  Unresolved requirement: Import-Package: org.eclipse.jetty.deploy; version="[9.3.0,10.0.0)"
    -> Export-Package: org.eclipse.jetty.deploy; bundle-symbolic-name="org.eclipse.jetty.deploy"; bundle-version="9.3.15.v20161220"; version="9.3.15"; uses:="org.eclipse.jetty.deploy.graph,org.eclipse.jetty.server,org.eclipse.jetty.server.handler,org.eclipse.jetty.util,org.eclipse.jetty.util.annotation,org.eclipse.jetty.util.component"

	at org.eclipse.osgi.container.Module.start(Module.java:444)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1628)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1608)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1579)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1522)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
2018-05-18 14:43:47.065 [WARN ] [.e.s.m.i.i.GenericItemProvider:364  ] - ModelRepository is NULL > dispatch bindings aborted!
2018-05-18 14:43:47.065 [WARN ] [.e.s.m.i.i.GenericItemProvider:364  ] - ModelRepository is NULL > dispatch bindings aborted!
2018-05-18 14:43:47.175 [DEBUG] [.s.r.i.SitemapRuntimeActivator:26   ] - Registered 'sitemap' configuration parser

!ENTRY org.eclipse.jetty.deploy 4 0 2018-05-18 14:43:47.268
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.jetty.deploy [11]
  Unresolved requirement: Import-Package: org.eclipse.jetty.jmx; version="[9.3.15,9.3.16)"; resolution:="optional"
  Unresolved requirement: Import-Package: org.eclipse.jetty.webapp; version="[9.3.15,9.3.16)"
    -> Export-Package: org.eclipse.jetty.webapp; bundle-symbolic-name="org.eclipse.jetty.webapp"; bundle-version="9.3.15.v20161220"; version="9.3.15"; uses:="javax.servlet,org.eclipse.jetty.security,org.eclipse.jetty.server,org.eclipse.jetty.server.handler,org.eclipse.jetty.server.session,org.eclipse.jetty.servlet,org.eclipse.jetty.util,org.eclipse.jetty.util.annotation,org.eclipse.jetty.util.resource,org.eclipse.jetty.xml"
       org.eclipse.jetty.webapp [108]
         Unresolved requirement: Import-Package: org.eclipse.jetty.security; version="[9.3.15,9.3.16)"

	at org.eclipse.osgi.container.Module.start(Module.java:444)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1628)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1608)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1579)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1522)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)

!ENTRY org.apache.httpcomponents.httpclient 4 0 2018-05-18 14:43:47.284
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.apache.httpcomponents.httpclient [22]
  Unresolved requirement: Import-Package: org.apache.commons.codec.binary; version="1.9.0"

	at org.eclipse.osgi.container.Module.start(Module.java:444)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1628)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1608)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1579)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1522)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)

!ENTRY org.eclipse.jetty.servlet 4 0 2018-05-18 14:43:47.284
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.jetty.servlet [23]
  Unresolved requirement: Import-Package: org.eclipse.jetty.jmx; version="[9.3.15,9.3.16)"; resolution:="optional"
  Unresolved requirement: Import-Package: org.eclipse.jetty.security; version="[9.3.15,9.3.16)"

	at org.eclipse.osgi.container.Module.start(Module.java:444)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1628)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1608)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1579)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1522)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2018-05-18 14:43:47.302 [DEBUG] [.c.t.i.TransformationActivator:39   ] - Transformation Service has been started.
2018-05-18 14:43:47.317 [DEBUG] [s.a.m.timer.internal.Activator:42   ] - started bundle timer.module
2018-05-18 14:43:47.395 [DEBUG] [.i.r.sse.internal.SseActivator:51   ] - SSE API - SseFeature registered.
2018-05-18 14:43:47.395 [DEBUG] [.i.r.sse.internal.SseActivator:60   ] - SSE API has been started.

!ENTRY org.eclipse.jetty.security 4 0 2018-05-18 14:43:47.427
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.jetty.security [48]
  Unresolved requirement: Import-Package: org.eclipse.jetty.http; version="[9.4.5,9.4.6)"

	at org.eclipse.osgi.container.Module.start(Module.java:444)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1628)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1608)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1579)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1522)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
2018-05-18 14:43:47.427 [DEBUG] [o.e.s.s.j.i.JsonStorageService:59   ] - Json Storage Service: Activated.
2018-05-18 14:43:47.442 [DEBUG] [.s.s.json.internal.JsonStorage:107  ] - Json storage file at 'D:\dev\openhab2\git\openhab-distro\launch\home\userdata\jsondb\org.eclipse.smarthome.core.thing.link.ItemChannelLink.json' does not exist - checking for a backup.
2018-05-18 14:43:47.442 [DEBUG] [.s.s.json.internal.JsonStorage:107  ] - Json storage file at 'D:\dev\openhab2\git\openhab-distro\launch\home\userdata\jsondb\org.eclipse.smarthome.core.thing.Thing.json' does not exist - checking for a backup.
2018-05-18 14:43:47.442 [DEBUG] [.c.c.registry.AbstractRegistry:311  ] - Provider 'org.eclipse.smarthome.core.thing.ManagedThingProvider' has been added.

!ENTRY org.eclipse.jetty.osgi.httpservice 4 0 2018-05-18 14:43:47.442
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.jetty.osgi.httpservice [54]
  Unresolved requirement: Import-Package: org.eclipse.jetty.servlet; version="[9.1.0,10.0.0)"
    -> Export-Package: org.eclipse.jetty.servlet; bundle-symbolic-name="org.eclipse.jetty.servlet"; bundle-version="9.3.15.v20161220"; version="9.3.15"; uses:="javax.servlet,javax.servlet.descriptor,javax.servlet.http,org.eclipse.jetty.http,org.eclipse.jetty.security,org.eclipse.jetty.server,org.eclipse.jetty.server.handler,org.eclipse.jetty.server.handler.gzip,org.eclipse.jetty.server.session,org.eclipse.jetty.util,org.eclipse.jetty.util.annotation,org.eclipse.jetty.util.component,org.eclipse.jetty.util.resource"
       org.eclipse.jetty.servlet [23]
         Unresolved requirement: Import-Package: org.eclipse.jetty.jmx; version="[9.3.15,9.3.16)"; resolution:="optional"
         Unresolved requirement: Import-Package: org.eclipse.jetty.security; version="[9.3.15,9.3.16)"

	at org.eclipse.osgi.container.Module.start(Module.java:444)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1628)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1608)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1579)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1522)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
2018-05-18 14:43:47.442 [DEBUG] [.c.d.internal.ConfigDispatcher:140  ] - Error loading exclusive pids from 'D:\dev\openhab2\ws\.metadata\.plugins\org.eclipse.pde.core\openHAB_Runtime\org.eclipse.osgi\56\data\configdispatcher_pid_list.json': D:\dev\openhab2\ws\.metadata\.plugins\org.eclipse.pde.core\openHAB_Runtime\org.eclipse.osgi\56\data\configdispatcher_pid_list.json (Le fichier spécifié est introuvable)
2018-05-18 14:43:47.442 [DEBUG] [.c.d.internal.ConfigDispatcher:280  ] - Processing config file 'services.cfg'
2018-05-18 14:43:47.942 [DEBUG] [.core.common.ThreadPoolManager:121  ] - Created scheduled thread pool 'file-processing' of size 5
2018-05-18 14:43:47.953 [DEBUG] [.c.d.internal.ConfigDispatcher:280  ] - Processing config file 'logging.cfg'
2018-05-18 14:43:47.985 [DEBUG] [.c.d.internal.ConfigDispatcher:280  ] - Processing config file 'classicui.cfg'
2018-05-18 14:43:48.032 [DEBUG] [.c.d.internal.ConfigDispatcher:280  ] - Processing config file 'basicui.cfg'
2018-05-18 14:43:48.157 [INFO ] [.e.s.m.c.i.ModelRepositoryImpl:113  ] - Loading model 'demo.sitemap'
2018-05-18 14:43:48.188 [INFO ] [.e.s.m.c.i.ModelRepositoryImpl:113  ] - Loading model 'lang_en_GB.sitemap'
2018-05-18 14:43:48.219 [INFO ] [.e.s.m.c.i.ModelRepositoryImpl:113  ] - Loading model 'demo.things'
2018-05-18 14:43:48.250 [INFO ] [.e.s.m.c.i.ModelRepositoryImpl:113  ] - Loading model 'rrd4j.persist'
2018-05-18 14:43:48.328 [INFO ] [.e.s.m.c.i.ModelRepositoryImpl:113  ] - Loading model 'demo.items'
2018-05-18 14:43:48.344 [DEBUG] [.e.s.m.i.i.GenericItemProvider:188  ] - Read items from model 'demo.items'
2018-05-18 14:43:48.360 [DEBUG] [.e.s.m.i.i.GenericItemProvider:539  ] - Couldn't find ItemFactory for item 'Lights' of type 'Switch'
2018-05-18 14:43:48.375 [DEBUG] [.e.s.m.i.i.GenericItemProvider:539  ] - Couldn't find ItemFactory for item 'Heating' of type 'Switch'
```

**Comment by lolodomo** [comment]
Is there no default launch configuration that will provide the demo files with Paper UI and Basic UI ?
I am lost.
I should probably wait for an upgrade of the openHAB target platform...

**Comment by lolodomo** [comment]
I just understood what's wrong. I am sorry for this stupid bug. I will propose a fix quickly.
