### ISSUE TITLE
[SNAPSHOT 1276] - Warning on "Members of" triggers

### ISSUE THREAD

**Issue by vzorglub** [eclipse/smarthome#5578]
Just updated to 1276
Ubuntu 16.04 intel
Repo installation

I get these warnings on ALL the rules with "Member of" triggers

==> /var/log/openhab2/openhab.log <==
```
2018-05-15 08:09:36.064 [WARN ] [pse.smarthome.core.items.GenericItem] - failed notifying listener 'org.eclipse.smarthome.model.rule.runtime.internal.engine.RuleEngineImpl@51c2828' about state update of item Bathroom_ThermostatTarget: null
java.lang.NullPointerException: null
	at org.eclipse.smarthome.model.rule.runtime.internal.engine.RuleTriggerManager.internalGetChangeRules(RuleTriggerManager.java:344) [136:org.eclipse.smarthome.model.rule.runtime:0.10.0.201805141751]
	at org.eclipse.smarthome.model.rule.runtime.internal.engine.RuleTriggerManager.internalGetRules(RuleTriggerManager.java:429) [136:org.eclipse.smarthome.model.rule.runtime:0.10.0.201805141751]
	at org.eclipse.smarthome.model.rule.runtime.internal.engine.RuleTriggerManager.getRules(RuleTriggerManager.java:198) [136:org.eclipse.smarthome.model.rule.runtime:0.10.0.201805141751]
	at org.eclipse.smarthome.model.rule.runtime.internal.engine.RuleEngineImpl.stateChanged(RuleEngineImpl.java:202) [136:org.eclipse.smarthome.model.rule.runtime:0.10.0.201805141751]
	at org.eclipse.smarthome.core.items.GenericItem$1.run(GenericItem.java:251) [101:org.eclipse.smarthome.core:0.10.0.201805141751]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
```
==> /var/log/openhab2/events.log <==

2018-05-15 08:09:36.070 [vent.ItemStateChangedEvent] - Bathroom_ThermostatTarget changed from 19.7 to 19.3

**Comment by kaikreuzer** [comment]
FTR, this bug has been introduced by https://github.com/eclipse/smarthome/pull/4383
