### ISSUE TITLE
[digitalstrom] OpenHAB 2.3

### ISSUE THREAD

**Issue by maxx92** [eclipse/smarthome#5651]
Ever since I upgraded to openhab 2.3.0-1 the digitalstrom binding ceased to work.. 
None of the devices accepts any command anymore. Instead, the status in paperUI is reported "ONLINE - CONFIGURATION_PENDING waiting for listener registration" forever. A couple of reboots did not help. Things worked quite fine until yesterday. Does anyone notice the same behavior?

**Comment by maxx92** [comment]
Update: Yesterday I did a complete new installation of OpenHAB 2.3 and only added the digitalstrom binding. This time the status is "Status: ONLINE - CONFIGURATION_PENDING Checking configuration..."

**Comment by MichaelOchel** [comment]
A parameter that we had used is removed from the digitalSTROM-API. I changed the logic to another parameter.  See #5673

**Comment by maxx92** [comment]
Hello Michael
Sorry for pointing out the other message at openhab communtiy. I did not get it that you already replied.. that is the trouble when you access forums via mobile phone.. However, what do I need to do now? Update?

**Comment by triller-telekom** [comment]
@maxx92 I have build the fixed version from @MichaelOchel s PR # 5673.

Since I do not have the hardware to test: Could you please remove the current digitalstrombindign that is shipped with OH2.3 and download the build version from the attachment from my PR, rename it to ".jar" and put it into your addons folder and then check if it works again?

[org.eclipse.smarthome.binding.digitalstrom-0.10.0-SNAPSHOT.zip](https://github.com/eclipse/smarthome/files/2068490/org.eclipse.smarthome.binding.digitalstrom-0.10.0-SNAPSHOT.zip)

**Comment by maxx92** [comment]
Just that I understand this properly: 
1) I uninstall the Digitalstrom binding
2) I rename the downloaded ...zip file to ...jar
3) I move the new jar file to the folder "openhab2-addons" on my Raspberry
just explain me what else I have to do. Sorry, I am not too experienced in Java and stuff

**Comment by maxx92** [comment]
Ok. figured it out myself. It WORKS! Thank you. Finally my home gets filled with life again..
The only thing I noticed is that I have to replace all channels "lightSwitch" into "light_switch" in my zuhause.items file. But that is fine. Will the GR-HKL230 be supported soon? It is still not showing slat angle. That would be perfect!

**Comment by maxx92** [comment]
Just an update on the situation: Since I have the beta-binding in place, my system is having a load of 25% permanently and is super slow, too. I am convinced that the binding and the slow system response are co-related. Do you have any idea?

**Comment by maxx92** [comment]
Hello

Another update. I did a clean fresh 2.3 stable install as I had many error messages. This is one I get:

**Comment by maxx92** [comment]
I did a fresh flash. Here is one of the error messages I get
`2018-06-09 11:45:42.107 [ERROR] [nal.common.AbstractInvocationHandler] - An error occurred while calling method 'ThingHandler.initialize()' on 'org.eclipse.smarthome.binding.digitalstrom.handler.DeviceHandler@1727a90': Changes must not be done on the current thing - create a copy, e.g. via editThing()`

**Comment by maxx92** [comment]
`==> /var/log/openhab2/openhab.log <==
2018-06-09 11:45:57.318 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception
java.lang.IllegalArgumentException: Changes must not be done on the current thing - create a copy, e.g. via editThing()
	at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.updateThing(BaseThingHandler.java:490) [108:org.eclipse.smarthome.core.thing:0.10.0.oh230]
	at org.eclipse.smarthome.binding.digitalstrom.handler.DeviceHandler.onSceneConfigAdded(DeviceHandler.java:933) [223:org.eclipse.smarthome.binding.digitalstrom:0.10.0.201806041347]
	at org.eclipse.smarthome.binding.digitalstrom.internal.lib.structure.devices.impl.DeviceImpl.addSceneConfig(DeviceImpl.java:903) [223:org.eclipse.smarthome.binding.digitalstrom:0.10.0.201806041347]
	at org.eclipse.smarthome.binding.digitalstrom.internal.lib.sensorjobexecutor.sensorjob.impl.SceneConfigReadingJob.execute(SceneConfigReadingJob.java:57) [223:org.eclipse.smarthome.binding.digitalstrom:0.10.0.201806041347]
	at org.eclipse.smarthome.binding.digitalstrom.internal.lib.sensorjobexecutor.AbstractSensorJobExecutor$ExecutorRunnable.run(AbstractSensorJobExecutor.java:73) [223:org.eclipse.smarthome.binding.digitalstrom:0.10.0.201806041347]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
2018-06-09 11:46:02.654 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception
java.lang.IllegalArgumentException: Changes must not be done on the current thing - create a copy, e.g. via editThing()
	at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.updateThing(BaseThingHandler.java:490) [108:org.eclipse.smarthome.core.thing:0.10.0.oh230]
	at org.eclipse.smarthome.binding.digitalstrom.handler.DeviceHandler.onSceneConfigAdded(DeviceHandler.java:933) [223:org.eclipse.smarthome.binding.digitalstrom:0.10.0.201806041347]
	at org.eclipse.smarthome.binding.digitalstrom.internal.lib.structure.devices.impl.DeviceImpl.addSceneConfig(DeviceImpl.java:903) [223:org.eclipse.smarthome.binding.digitalstrom:0.10.0.201806041347]
	at org.eclipse.smarthome.binding.digitalstrom.internal.lib.sensorjobexecutor.sensorjob.impl.SceneConfigReadingJob.execute(SceneConfigReadingJob.java:57) [223:org.eclipse.smarthome.binding.digitalstrom:0.10.0.201806041347]
	at org.eclipse.smarthome.binding.digitalstrom.internal.lib.sensorjobexecutor.AbstractSensorJobExecutor$ExecutorRunnable.run(AbstractSensorJobExecutor.java:73) [223:org.eclipse.smarthome.binding.digitalstrom:0.10.0.201806041347]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
==> /var/log/openhab2/events.log <==
2018-06-09 11:46:05.266 [me.event.ThingUpdatedEvent] - Thing 'digitalstrom:GE:302ed89f43f02ba000010414:303505d7f8000040000417a2' has been updated.
==> /var/log/openhab2/openhab.log <==
2018-06-09 11:46:05.265 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception
java.lang.IllegalArgumentException: Changes must not be done on the current thing - create a copy, e.g. via editThing()
	at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.updateThing(BaseThingHandler.java:490) [108:org.eclipse.smarthome.core.thing:0.10.0.oh230]
	at org.eclipse.smarthome.binding.digitalstrom.handler.DeviceHandler.onSceneConfigAdded(DeviceHandler.java:933) [223:org.eclipse.smarthome.binding.digitalstrom:0.10.0.201806041347]
	at org.eclipse.smarthome.binding.digitalstrom.internal.lib.structure.devices.impl.DeviceImpl.setSceneOutputValue(DeviceImpl.java:869) [223:org.eclipse.smarthome.binding.digitalstrom:0.10.0.201806041347]
	at org.eclipse.smarthome.binding.digitalstrom.internal.lib.sensorjobexecutor.sensorjob.impl.SceneOutputValueReadingJob.execute(SceneOutputValueReadingJob.java:59) [223:org.eclipse.smarthome.binding.digitalstrom:0.10.0.201806041347]
	at org.eclipse.smarthome.binding.digitalstrom.internal.lib.sensorjobexecutor.AbstractSensorJobExecutor$ExecutorRunnable.run(AbstractSensorJobExecutor.java:73) [223:org.eclipse.smarthome.binding.digitalstrom:0.10.0.201806041347]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
==> /var/log/openhab2/events.log <==
2018-06-09 11:46:09.056 [me.event.ThingUpdatedEvent] - Thing 'digitalstrom:GE:302ed89f43f02ba000010414:303505d7f8000040000436b3' has been updated.
==> /var/log/openhab2/openhab.log <==
2018-06-09 11:46:09.055 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception
java.lang.IllegalArgumentException: Changes must not be done on the current thing - create a copy, e.g. via editThing()
	at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.updateThing(BaseThingHandler.java:490) [108:org.eclipse.smarthome.core.thing:0.10.0.oh230]
	at org.eclipse.smarthome.binding.digitalstrom.handler.DeviceHandler.onSceneConfigAdded(DeviceHandler.java:933) [223:org.eclipse.smarthome.binding.digitalstrom:0.10.0.201806041347]
	at org.eclipse.smarthome.binding.digitalstrom.internal.lib.structure.devices.impl.DeviceImpl.setSceneOutputValue(DeviceImpl.java:869) [223:org.eclipse.smarthome.binding.digitalstrom:0.10.0.201806041347]
	at org.eclipse.smarthome.binding.digitalstrom.internal.lib.sensorjobexecutor.sensorjob.impl.SceneOutputValueReadingJob.execute(SceneOutputValueReadingJob.java:59) [223:org.eclipse.smarthome.binding.digitalstrom:0.10.0.201806041347]
	at org.eclipse.smarthome.binding.digitalstrom.internal.lib.sensorjobexecutor.AbstractSensorJobExecutor$ExecutorRunnable.run(AbstractSensorJobExecutor.java:73) [223:org.eclipse.smarthome.binding.digitalstrom:0.10.0.201806041347]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
2018-06-09 11:49:07.573 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception
java.lang.IllegalArgumentException: Value must be between 0 and 100
	at org.eclipse.smarthome.core.library.types.PercentType.validateValue(PercentType.java:55) [101:org.eclipse.smarthome.core:0.10.0.oh230]
	at org.eclipse.smarthome.core.library.types.PercentType.<init>(PercentType.java:40) [101:org.eclipse.smarthome.core:0.10.0.oh230]
	at org.eclipse.smarthome.binding.digitalstrom.handler.DeviceHandler.onDeviceStateChanged(DeviceHandler.java:395) [223:org.eclipse.smarthome.binding.digitalstrom:0.10.0.201806041347]
	at org.eclipse.smarthome.binding.digitalstrom.internal.lib.structure.devices.impl.DeviceImpl.informListenerAboutStateUpdate(DeviceImpl.java:1672) [223:org.eclipse.smarthome.binding.digitalstrom:0.10.0.201806041347]
	at org.eclipse.smarthome.binding.digitalstrom.internal.lib.structure.devices.impl.DeviceImpl.updateInternalDeviceState(DeviceImpl.java:1617) [223:org.eclipse.smarthome.binding.digitalstrom:0.10.0.201806041347]
	at org.eclipse.smarthome.binding.digitalstrom.internal.lib.sensorjobexecutor.sensorjob.impl.DeviceOutputValueSensorJob.execute(DeviceOutputValueSensorJob.java:75) [223:org.eclipse.smarthome.binding.digitalstrom:0.10.0.201806041347]
	at org.eclipse.smarthome.binding.digitalstrom.internal.lib.sensorjobexecutor.AbstractSensorJobExecutor$ExecutorRunnable.run(AbstractSensorJobExecutor.java:73) [223:org.eclipse.smarthome.binding.digitalstrom:0.10.0.201806041347]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]`

**Comment by maxx92** [comment]
I abandoned the newly flashed OH and went back to 2.4 
Interestingly, I can steer my DS things however, they NEVER report their status back as they used to do! For example: when I switch on a light by physical switch, OH does not log any activity. It does not see any change... What are the plans for this binding? I am more than willing to help debug it but I want to know the plan.

**Comment by Torkalis** [comment]
Hi,
i would like to help debugging the binding, too. Im able to test the service on multible dS instances, becouse i'm working in a training center for digitalStrom. I can test dss11 dss-e dss-IP and dss22.
But the true problem is my home... No music from light switch... no temperature enabled shading... 

Greetings

Torkalis

**Comment by maxx92** [comment]
Guys, I really appreciate your work on that binding but I also would appreciate if you were a bit more responsive.. It has now been more than a week without even a short note.. Please let me know whether this binding has been basically put on hold because then I need to look for a working solution.

**Comment by kaikreuzer** [comment]
@maxx92 I hope you are aware that those guys are doing this entirely in their spare time and not getting anything out of it?
I'd suggest you either be patient for people to find the time to look into it, go and get your hands dirty yourself and start debugging fixing issues or consider [posting a bounty](https://www.bountysource.com/issues/57124445-openhab2-digitalstrom-binding) to give people some incentive to treat this with some priority.

**Comment by maxx92** [comment]
I am absolutely aware... I just need to **know** whether I should spend anymore time with openHAB or look for another solution. That is fair as well.

**Comment by MichaelOchel** [comment]
Hey,

we will try to keep the binding working. That means we will update the binding if there are changes by openHAB or digitalSTROM itselfes (and we get informed by someones report). It could take some time till the update will be available. It depends on how much time we can invest.  

But we can’t provide support for every single user problem or upgrade the binding with new functionality (contemporary). If you have ideas and wishes, again the invitation to you to inform you of digitalSTROM and eclipse Smarthome and be part of the Open-Source Project!
 
**To your other problems:**
* digitalSTROM-Server is slowly: maybe it helps to set the *sensorWaitTime* higher to reduce the requests to digitalSTROM-Server. We had never problems like that.
* OH2 do not change the status if you hit e.g. a physical light-switch: We think that the scenes are not red out at the time you hit the switch, so wait some time and try it later. After the scene-value is red out, the status will change directly. See Readme *General-Informations/digitalSTROM-Scenes*. But we write it to the channel chapter too, now. Read also the part of saving scens.
*  The exception and some more we fixt in another commit in #5673 

To your GR-HKL230 #5418:
The idea is to use the new (or better newer than the implementation of the binding) API-method *getModelFeatures* [dss-json.pdf](http://developer.digitalstrom.org/Architecture/dss-json.pdf),  p. 38, to identify the functionality of the devices. For that all *ModelFeatures* have to be red out at the beginning (bridge initialization) and the device-objects have to evaluate it. For that the hardware-type have to be mapped to the “ModelFeatures” like the desciption:
>  "containing the known model features. The features are ordered according to the device’s color (e.g.“GE”, “SW”, etc.). Always the most specific model feature applies: e.g. (refer to the example below) “KM:200” from “GE” applies to a GE-KM220 device; while a “KM:2”from “GE” applies to a GE-KM210 device",
[dss-json.pdf](http://developer.digitalstrom.org/Architecture/dss-json.pdf),  getModelFeatures, p. 38,

May be you or someone else find the time to create a concept and/or implement it, or you have to wait until we find the time for that. But we can not say when that will be.


Best regards
Matthias and Michael

**Comment by maxx92** [comment]
Hello all
Thank you for your update. I understand that you will invest time as you see fit.

Just a note to dss status changes that are no longer (!) triggering in OH. They used to work fine. But now (maybe it coincided with a dss update.. I am now on V1.14.2.1) NO digitalstrom status is fed back. That means, no rule that relies on status of any dss item will work anymore. If the command to switch on or off a light came from OH, then it works. But not the other way around. No matter how often you try, it does not work anymore. It used to until 3 weeks ago.

**Comment by cradermacher** [comment]
Hi,

i have the same Problem with this Binding. I have installed the actual Snapshot, but the Binding doesn't, work. The Message is: "Online: Configuration_Pending".

The Snapshot is actual from today.

Is there everything I can do?

Regards
Christian
