### ISSUE TITLE
IllegalArgumentException in AutomaticInboxProcessor

### ISSUE THREAD

**Issue by amitjoy** [eclipse/smarthome#5660]
```java
java.lang.IllegalArgumentException: The argument 'discoveryResult' must not be null.
	at org.eclipse.smarthome.core.events.AbstractEventFactory.checkNotNull(AbstractEventFactory.java:112)
	at org.eclipse.smarthome.config.discovery.inbox.events.InboxEventFactory.assertValidArgument(InboxEventFactory.java:120)
	at org.eclipse.smarthome.config.discovery.inbox.events.InboxEventFactory.createUpdatedEvent(InboxEventFactory.java:112)
	at org.eclipse.smarthome.config.discovery.internal.PersistentInbox.postEvent(PersistentInbox.java:476)
	at org.eclipse.smarthome.config.discovery.internal.PersistentInbox.notifyListeners(PersistentInbox.java:462)
	at org.eclipse.smarthome.config.discovery.internal.PersistentInbox.setFlag(PersistentInbox.java:381)
	at org.eclipse.smarthome.config.discovery.internal.AutomaticInboxProcessor.ignoreInInbox(AutomaticInboxProcessor.java:186)
	at org.eclipse.smarthome.config.discovery.internal.AutomaticInboxProcessor.checkAndIgnoreInInbox(AutomaticInboxProcessor.java:176)
	at org.eclipse.smarthome.config.discovery.internal.AutomaticInboxProcessor.autoIgnore(AutomaticInboxProcessor.java:168)
	at org.eclipse.smarthome.config.discovery.internal.AutomaticInboxProcessor.receiveTypedEvent(AutomaticInboxProcessor.java:115)
	at org.eclipse.smarthome.config.discovery.internal.AutomaticInboxProcessor.receiveTypedEvent(AutomaticInboxProcessor.java:1)
	at org.eclipse.smarthome.core.events.AbstractTypedEventSubscriber.receive(AbstractTypedEventSubscriber.java:54)
	at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153)
	at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:53)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by maggu2810** [comment]
Had you the change to further inspect the cause of this error?

**Comment by amitjoy** [comment]
Not really but I have already talked to @afuechsel and he can give us more insight.

**Comment by maggu2810** [comment]
The argument `discoveryResult` is null on
	at org.eclipse.smarthome.config.discovery.inbox.events.InboxEventFactory.createUpdatedEvent(InboxEventFactory.java:112)

=> the argument `result` is null on
	at org.eclipse.smarthome.config.discovery.internal.PersistentInbox.postEvent(PersistentInbox.java:476)

=> the `resultForEvent` in that call is `null`
	at org.eclipse.smarthome.config.discovery.internal.PersistentInbox.notifyListeners(PersistentInbox.java:462)

We already know that the `type` is `EventType.updated`, so we know that the call `get(result.getThingUID())` returned `null`.

```Java
    /**
     * Returns the {@link DiscoveryResult} in this {@link Inbox} associated with
     * the specified {@code Thing} ID, or {@code null}, if no {@link DiscoveryResult} could be found.
     *
     * @param thingId
     *            the Thing ID to which the discovery result should be returned
     *
     * @return the discovery result associated with the specified Thing ID, or
     *         null, if no discovery result could be found
     */
    private DiscoveryResult get(ThingUID thingUID) {
        if (thingUID != null) {
            return discoveryResultStorage.get(thingUID.toString());
        }

        return null;
    }
```

Already the JavaDoc (and the implementation) states that this method will return null.

* `PersistentInbox.postEvent(DiscoveryResult result, EventType eventType)` should state that `result` and `eventType` must not be null (=> introduce nullness annotations for that class)
* `PersistentInbox.notifyListeners(DiscoveryResult result, EventType type)` should check `result` for `null` before calling `postEvent` (I assume this needs only be done if `get(...)` has been called as in the other case `notifyListeners` should also require a non null `result` -- otherwise `result.getThingUID()` will raise a NPE).
