### ISSUE TITLE
NPE when refreshing sitemap

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#5701]
I just found this in my log of an openHAB 2.3 release version when doing (potentially invalid) changes to a sitemap file:

```
22:26:40.546 [INFO ] [del.core.internal.ModelRepositoryImpl] - Loading model 'default.sitemap'
22:26:40.561 [WARN ] [del.core.internal.ModelRepositoryImpl] - Configuration model 'default.sitemap' is either empty or cannot be parsed correctly!
22:26:40.562 [ERROR] [l.core.internal.folder.FolderObserver] - Error handling update of file '/Users/kai/Documents/dev/demo/conf/sitemaps/default.sitemap': null.
java.lang.NullPointerException: null
	at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011) [?:?]
	at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006) [?:?]
	at org.eclipse.smarthome.model.sitemap.internal.SitemapProviderImpl.modelChanged(SitemapProviderImpl.java:106) [140:org.eclipse.smarthome.model.sitemap:0.10.0.oh230]
	at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.notifyListeners(ModelRepositoryImpl.java:301) [126:org.eclipse.smarthome.model.core:0.10.0.oh230]
	at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.addOrRefreshModel(ModelRepositoryImpl.java:123) [126:org.eclipse.smarthome.model.core:0.10.0.oh230]
	at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.checkFile(FolderObserver.java:227) [126:org.eclipse.smarthome.model.core:0.10.0.oh230]
	at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.processWatchEvent(FolderObserver.java:291) [126:org.eclipse.smarthome.model.core:0.10.0.oh230]
	at org.eclipse.smarthome.core.service.WatchQueueReader.run(WatchQueueReader.java:240) [101:org.eclipse.smarthome.core:0.10.0.oh230]
	at java.lang.Thread.run(Thread.java:748) [?:?]
```

**Comment by kaikreuzer** [comment]
Seems it has been introduced by https://github.com/eclipse/smarthome/pull/4785.
