### ISSUE TITLE
[Homematic] Error: rssiInfo method not found

### ISSUE THREAD

**Issue by mdicke2s** [eclipse/smarthome#5790]
_From @lampi87 on January 21, 2018 16:6_

Hello,

after OpenHAB2 restart I get an error in my logfiles
```
[WARN ] [matic.handler.HomematicBridgeHandler] - Unable to load RSSI values from bridge 'ccu'
[ERROR] [matic.handler.HomematicBridgeHandler] - -1 rssiInfo: unknown.method name (sending rssiInfo()
)
java.io.IOException: -1 rssiInfo: unknown.method name (sending rssiInfo()
)
```

## Expected Behavior
Error should not appear

## Current Behavior
Error shown in logfiles. Is something missing in my installation?

## Steps to Reproduce (for Bugs)
1. CCU2 is setup on RPI using YAHM
2. Add CCU2 to OpenHAB
3. Restart OpenHAB and watch logfile

## Your Environment
* Version used: 2.2.0 Release Build
* Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...): Openhabianpine

_Copied from original issue: openhab/openhab2-addons#3153_

**Comment by mdicke2s** [comment]
_From @MHerbst on January 24, 2018 18:45_

On a first look it seems that the message "unknown.method" is returned by CCU. But I need to have a closer look into the sources to be sure. You could try to enable the trace for the Homematic binding and restart openHAB. With the enabled trace the log file will contain more detailed information from the communication between openHAB and the CCU.

**Comment by mdicke2s** [comment]
_From @ne0h on January 31, 2018 14:19_

I have the same issue. Where exactly do I have to set logging to trace to provide more information?

**Comment by mdicke2s** [comment]
_From @maxx92 on April 24, 2018 11:56_

Same here... no solution?

**Comment by mdicke2s** [comment]
_From @maxx92 on May 13, 2018 9:38_

Still no one?

**Comment by mdicke2s** [comment]
_From @MHerbst on May 13, 2018 11:57_

Are you also using YAHM? Can you provide some more information (like a trace output)?

Maybe there is a general problem with YAHM and RSSI information. I found this entry on the Homematic forum: https://homematic-forum.de/forum/viewtopic.php?f=37&t=33522#p316388

**Comment by mdicke2s** [comment]
_From @s0170071 on May 14, 2018 8:3_

Same here. I use: 
RPi 3B+ (stretch) with 
piVCCU (lxc version of CCU) 
OH 2.2 stable
Mosquitto, influxDB, Telegraf, grafana.

**Comment by mdicke2s** [comment]
_From @gerrieg on June 11, 2018 13:56_

Issue still valid? I have tested it with a CCU and RaspberryMatic, works as expected.

**Comment by mdicke2s** [comment]
_From @maxx92 on June 11, 2018 14:44_

Unfortunately: yes. Now I use pivccu but no improvement.

`2018-06-09 15:16:05.382 [WARN ] [matic.handler.HomematicBridgeHandler] - Unable to load RSSI values from bridge 'PEQ0175517'
2018-06-09 15:16:05.384 [ERROR] [matic.handler.HomematicBridgeHandler] - -1 rssiInfo: unknown.method name (sending rssiInfo()
java.io.IOException: -1 rssiInfo: unknown.method name (sending rssiInfo()
	at org.openhab.binding.homematic.internal.communicator.client.RpcClient.loadRssiInfo(RpcClient.java:385) ~[?:?]
	at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway.loadRssiValues(AbstractHomematicGateway.java:520) ~[?:?]
`

**Comment by mdicke2s** [comment]
_From @gerrieg on June 11, 2018 14:59_

Then i think it is a pivccu issue.

**Comment by mdicke2s** [comment]
_From @s0170071 on June 11, 2018 16:43_

Probably not as pivccu runs the original CCU binary.

**Comment by mdicke2s** [comment]
_From @maxx92 on June 11, 2018 19:42_

.. I had it on a CCU2 when I originally posted..

**Comment by mdicke2s** [comment]
_From @gerrieg on June 12, 2018 16:10_

On a CCU2? I tried it yesterday on my CCU2. Hmmm, currently no idea why the gateway does not know the RPC method.

Can you please install [Homematic Manager](https://github.com/hobbyquaker/homematic-manager/releases), then click on RPC Konsole, select BidCos-RF and send the rssiInfo command.

**Comment by mdicke2s** [comment]
_From @maxx92 on June 12, 2018 16:19_

Hi Gerhard

As said, I changed from CCU2 to pivCCU about two weeks ago. However, I must add (maybe this has some importance) I use 95% Homematic IP components.. I only have 2 components that are NOT HmIP...

I installed Homematic Manager and sent the rssiInfo > send command. Here’s the output:
'{
  "OEQ0800785": {
    "PEQ0175517": [
      65536,
      -59
    ]
  },
  "OEQ0902127": {
    "PEQ0175517": [
      65536,
      -59
    ]
  },
  "PEQ0175517": {
    "OEQ0800785": [
      -59,
      65536
    ],
    "OEQ0902127": [
      -59,
      65536
    ]
  }
}
'

**Comment by mdicke2s** [comment]
_From @gerrieg on June 12, 2018 16:26_

OK, so that's a good hint with the HMIP devices. There is another issue with a HMIP only installation. As soon as i receive my new [RPI-RF-MOD](https://www.elv.at/homematic-funk-modulplatine-fuer-raspberry-pi-3-rpi-rf-mod-komplettbausatz.html), i have one Raspi free and i will setup a HMIP only system to test.

**Comment by fanavity** [comment]
is there a solution to the problem in the meantime?

**Comment by itn3rd77** [comment]
Hi,

I have seen the same error in openHAB 2.4 with RaspberryMatic 3.41.11.20181222.

```
2019-01-08 08:25:32.542 [WARN ] [matic.handler.HomematicBridgeHandler] - Unable to load RSSI values from bridge 'homematic'
2019-01-08 08:25:32.543 [ERROR] [matic.handler.HomematicBridgeHandler] - -1 rssiInfo: unknown.method name (sending rssiInfo()
)
java.io.IOException: -1 rssiInfo: unknown.method name (sending rssiInfo()
)
	at org.eclipse.smarthome.binding.homematic.internal.communicator.parser.RpcResponseParser.parse(RpcResponseParser.java:51) ~[?:?]
	at org.eclipse.smarthome.binding.homematic.internal.communicator.client.BinRpcClient.sendMessage(BinRpcClient.java:82) ~[?:?]
	at org.eclipse.smarthome.binding.homematic.internal.communicator.client.BinRpcClient.sendMessage(BinRpcClient.java:94) ~[?:?]
	at org.eclipse.smarthome.binding.homematic.internal.communicator.client.BinRpcClient.sendMessage(BinRpcClient.java:70) ~[?:?]
	at org.eclipse.smarthome.binding.homematic.internal.communicator.client.RpcClient.loadRssiInfo(RpcClient.java:448) ~[?:?]
	at org.eclipse.smarthome.binding.homematic.internal.communicator.AbstractHomematicGateway.loadRssiValues(AbstractHomematicGateway.java:534) ~[?:?]
	at org.eclipse.smarthome.binding.homematic.handler.HomematicBridgeHandler.initializeInternal(HomematicBridgeHandler.java:118) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
```

This is what I have seen on the RaspberryMatic side:

```
Jan  8 08:25:25 homematic-raspi daemon.warn cuxd[571]: 192.168.100.2 called unknown request method 'rssiInfo'
Jan  8 08:25:25 homematic-raspi daemon.warn cuxd[571]: 192.168.100.2 called unknown request method 'rssiInfo'
```

**Comment by Alestrix** [comment]
Same here using a CCU2 and OH v2.4.

**Comment by regnets** [comment]
I still got the same issue with the current 2.5 Release. It is a clean install with RaspberryMatic as CCU device.

```
2020-01-01 16:57:03.611 [ERROR] [ernal.handler.HomematicBridgeHandler] - -1 rssiInfo: unknown.method name (sending rssiInfo()
)
java.io.IOException: -1 rssiInfo: unknown.method name (sending rssiInfo()
)
	at org.openhab.binding.homematic.internal.communicator.parser.RpcResponseParser.parse(RpcResponseParser.java:51) ~[?:?]
	at org.openhab.binding.homematic.internal.communicator.client.BinRpcClient.sendMessage(BinRpcClient.java:82) ~[?:?]
	at org.openhab.binding.homematic.internal.communicator.client.BinRpcClient.sendMessage(BinRpcClient.java:94) ~[?:?]
	at org.openhab.binding.homematic.internal.communicator.client.BinRpcClient.sendMessage(BinRpcClient.java:70) ~[?:?]
	at org.openhab.binding.homematic.internal.communicator.client.RpcClient.loadRssiInfo(RpcClient.java:447) ~[?:?]
	at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway.loadRssiValues(AbstractHomematicGateway.java:534) ~[?:?]
	at org.openhab.binding.homematic.internal.handler.HomematicBridgeHandler.initializeInternal(HomematicBridgeHandler.java:120) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_232]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_232]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_232]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_232]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
```

Here is my log. if you need any further information, just ask for it.

I configured everything through textual based configuration. Here is an excerpt from my thing file.

```
Bridge homematic:bridge:RaspberryMatic "Bridge: RaspberryMatic" [gatewayAddress="10.0.0.210", callbackHost="10.0.0.220"] {
	Thing GATEWAY-EXTRAS-RASPBERRYMATIC GWE00000000	 "Homematic: Gateway Extras" @ "Allgemein"
}
```

**Comment by sidamos** [comment]
Migrated to: https://github.com/openhab/openhab-addons/issues/6743

**Comment by Alestrix** [comment]
Just revisiting this issue as I still have the same error in OH 2.5.1-2.

- using original CCU2 w/ CUx Daemon
- CCU2 has no internet connection
- using mainly Homematic but also a few Homematic IP

```
2020-01-19 22:01:04.264 [INFO ] [ommunicator.AbstractHomematicGateway] - HmGatewayInfo[id=CCU,type=CCU2,firmware=2.47.12,address=LEQ0643921,rf=true,wired=false,hmip=true,cuxd=true,group=true]
...
2020-01-19 22:01:29.312 [INFO ] [ng.homematic.internal.misc.MiscUtils] - Datapoint name '${sysVarAlarmZone1}' contains invalid characters, new Datapoint name '__sysVarAlarmZone1_'
2020-01-19 22:01:29.316 [INFO ] [ng.homematic.internal.misc.MiscUtils] - Datapoint name 'Datum_MM.TT' contains invalid characters, new Datapoint name 'Datum_MM_TT'
2020-01-19 22:01:29.326 [INFO ] [ng.homematic.internal.misc.MiscUtils] - Datapoint name 'Tageszeit_hh.mm' contains invalid characters, new Datapoint name 'Tageszeit_hh_mm'
2020-01-19 22:01:29.342 [INFO ] [ng.homematic.internal.misc.MiscUtils] - Datapoint name 'Rollo Tag/Nacht EG.Rolladen.EsszimmerSued' contains invalid characters, new Datapoint name 'Rollo_Tag_Nacht_EG_Rolladen_EsszimmerSued'
2020-01-19 22:01:29.343 [INFO ] [ng.homematic.internal.misc.MiscUtils] - Datapoint name 'Rollo Tag/Nacht EG.Rolladen.EsszimmerTerrasse' contains invalid characters, new Datapoint name 'Rollo_Tag_Nacht_EG_Rolladen_EsszimmerTerrasse'
2020-01-19 22:01:29.343 [INFO ] [ng.homematic.internal.misc.MiscUtils] - Datapoint name 'Rollo Tag/Nacht EG.Rolladen.WohnzimmerOst' contains invalid characters, new Datapoint name 'Rollo_Tag_Nacht_EG_Rolladen_WohnzimmerOst'
2020-01-19 22:01:29.344 [INFO ] [ng.homematic.internal.misc.MiscUtils] - Datapoint name 'Rollo Tag/Nacht EG.Rolladen.WohnzimmerSued' contains invalid characters, new Datapoint name 'Rollo_Tag_Nacht_EG_Rolladen_WohnzimmerSued'
2020-01-19 22:01:29.344 [INFO ] [ng.homematic.internal.misc.MiscUtils] - Datapoint name 'Tag/Nacht Definition Mo-Fr' contains invalid characters, new Datapoint name 'Tag_Nacht_Definition_Mo-Fr'
2020-01-19 22:01:29.345 [INFO ] [ng.homematic.internal.misc.MiscUtils] - Datapoint name 'Tag/Nacht Definition Sa-So' contains invalid characters, new Datapoint name 'Tag_Nacht_Definition_Sa-So'
2020-01-19 22:01:29.626 [WARN ] [ernal.handler.HomematicBridgeHandler] - Unable to load RSSI values from bridge 'ccu'
2020-01-19 22:01:29.627 [ERROR] [ernal.handler.HomematicBridgeHandler] - -1 rssiInfo: unknown.method name (sending rssiInfo()
)
java.io.IOException: -1 rssiInfo: unknown.method name (sending rssiInfo()
)
        at org.openhab.binding.homematic.internal.communicator.parser.RpcResponseParser.parse(RpcResponseParser.java:51) ~[?:?]
        at org.openhab.binding.homematic.internal.communicator.client.BinRpcClient.sendMessage(BinRpcClient.java:82) ~[?:?]
        at org.openhab.binding.homematic.internal.communicator.client.BinRpcClient.sendMessage(BinRpcClient.java:94) ~[?:?]
        at org.openhab.binding.homematic.internal.communicator.client.BinRpcClient.sendMessage(BinRpcClient.java:70) ~[?:?]
        at org.openhab.binding.homematic.internal.communicator.client.RpcClient.loadRssiInfo(RpcClient.java:447) ~[?:?]
        at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway.loadRssiValues(AbstractHomematicGateway.java:534) ~[?:?]
        at org.openhab.binding.homematic.internal.handler.HomematicBridgeHandler.initializeInternal(HomematicBridgeHandler.java:120) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_232]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_232]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_232]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_232]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_232]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_232]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
```

**Comment by MHerbst** [comment]
Can you please copy or move your post to this issue: https://github.com/openhab/openhab-addons/issues/6743 . The binding has moved back to the openHAB repo.
