### ISSUE TITLE
Cannot notify the DiscoveryListener o.e.s.config.discovery.internal.PersistentInbox on Thing discovered event

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#5815]
At the first startup of the snapshot 1305, my log file is flooded by this error:
```
2018-06-27 21:23:07.140 [ERROR] [nternal.DiscoveryServiceRegistryImpl] - Cannot notify the DiscoveryListener org.eclipse.smarthome.config.discovery.internal.PersistentInbox on Thing discovered event!
java.lang.ClassCastException: org.eclipse.smarthome.config.discovery.internal.DiscoveryResultImpl cannot be cast to org.eclipse.smarthome.config.discovery.DiscoveryResult
        at org.eclipse.smarthome.config.discovery.internal.PersistentInbox.get(PersistentInbox.java:409) ~[?:?]
        at org.eclipse.smarthome.config.discovery.internal.PersistentInbox.add(PersistentInbox.java:189) ~[?:?]
        at org.eclipse.smarthome.config.discovery.internal.PersistentInbox.thingDiscovered(PersistentInbox.java:332) ~[?:?]
        at org.eclipse.smarthome.config.discovery.internal.DiscoveryServiceRegistryImpl$2.run(DiscoveryServiceRegistryImpl.java:310) ~[?:?]
        at org.eclipse.smarthome.config.discovery.internal.DiscoveryServiceRegistryImpl$2.run(DiscoveryServiceRegistryImpl.java:1) ~[?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at org.eclipse.smarthome.config.discovery.internal.DiscoveryServiceRegistryImpl.thingDiscovered(DiscoveryServiceRegistryImpl.java:307) ~[?:?]
        at org.eclipse.smarthome.config.discovery.AbstractDiscoveryService.thingDiscovered(AbstractDiscoveryService.java:276) ~[?:?]
        at org.openhab.binding.freebox.internal.discovery.FreeboxDiscoveryService.onDataFetched(FreeboxDiscoveryService.java:141) ~[?:?]
        at org.openhab.binding.freebox.handler.FreeboxHandler.lambda$0(FreeboxHandler.java:233) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:?]
        at java.lang.Thread.run(Thread.java:745) [?:?]
```
At the second startup, I don't see these errors.
I almost certain that it was already the same case with the snapshot 1302.

**Comment by kaikreuzer** [comment]
This might be an issue in the upgrade process - I also often see problems on a first start after the upgrade, which then disappear on subsequent starts.
I am pretty sure that this isn't an issue in the ESH code itself, so I'd suggest to close this (and rather have some detailed report about update behavior in openhab-distro).

**Comment by lolodomo** [comment]
I always do an install from scratch (offline distro) without upgrading an existing one.

**Comment by kaikreuzer** [comment]
Interesting. There seem to be [some issues with the offline distro](https://github.com/openhab/openhab-distro/issues/729), though, so I would not rule out that this is somehow related...
