### ISSUE TITLE
Basic UI: exception relatiuve to favicon.ico

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#5905]
Hre is an exception logged when I open Basic UI:
```
09:21:36.982 [WARN ] [.eclipse.jetty.servlet.ServletHandler] - /basicui/favicon.ico
java.nio.channels.ClosedChannelException: null
        at org.eclipse.jetty.util.IteratingCallback.close(IteratingCallback.java:427) [80:org.eclipse.jetty.util:9.3.21.v20170918]
        at org.eclipse.jetty.server.HttpConnection.onClose(HttpConnection.java:489) [77:org.eclipse.jetty.server:9.3.21.v20170918]
        at org.eclipse.jetty.io.ssl.SslConnection.onClose(SslConnection.java:217) [69:org.eclipse.jetty.io:9.3.21.v20170918]
        at org.eclipse.jetty.io.SelectorManager.connectionClosed(SelectorManager.java:345) [69:org.eclipse.jetty.io:9.3.21.v20170918]
        at org.eclipse.jetty.io.ManagedSelector$2.run(ManagedSelector.java:442) [69:org.eclipse.jetty.io:9.3.21.v20170918]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303) [80:org.eclipse.jetty.util:9.3.21.v20170918]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148) [80:org.eclipse.jetty.util:9.3.21.v20170918]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136) [80:org.eclipse.jetty.util:9.3.21.v20170918]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671) [80:org.eclipse.jetty.util:9.3.21.v20170918]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589) [80:org.eclipse.jetty.util:9.3.21.v20170918]
        at java.lang.Thread.run(Thread.java:745) [?:?]
09:21:37.022 [WARN ] [org.eclipse.jetty.server.HttpChannel ] - https://192.168.1.36:8443/basicui/favicon.ico
javax.servlet.ServletException: java.nio.channels.ClosedChannelException
        at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:88) [175:org.ops4j.pax.web.pax-web-jetty:6.0.9]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134) [77:org.eclipse.jetty.server:9.3.21.v20170918]
        at org.eclipse.jetty.server.Server.handle(Server.java:534) [77:org.eclipse.jetty.server:9.3.21.v20170918]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:333) [77:org.eclipse.jetty.server:9.3.21.v20170918]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251) [77:org.eclipse.jetty.server:9.3.21.v20170918]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283) [69:org.eclipse.jetty.io:9.3.21.v20170918]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:108) [69:org.eclipse.jetty.io:9.3.21.v20170918]
        at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:251) [69:org.eclipse.jetty.io:9.3.21.v20170918]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283) [69:org.eclipse.jetty.io:9.3.21.v20170918]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:108) [69:org.eclipse.jetty.io:9.3.21.v20170918]
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93) [69:org.eclipse.jetty.io:9.3.21.v20170918]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303) [80:org.eclipse.jetty.util:9.3.21.v20170918]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148) [80:org.eclipse.jetty.util:9.3.21.v20170918]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136) [80:org.eclipse.jetty.util:9.3.21.v20170918]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671) [80:org.eclipse.jetty.util:9.3.21.v20170918]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589) [80:org.eclipse.jetty.util:9.3.21.v20170918]
        at java.lang.Thread.run(Thread.java:745) [?:?]
Caused by: java.nio.channels.ClosedChannelException
        at org.eclipse.jetty.util.IteratingCallback.close(IteratingCallback.java:427) ~[?:?]
        at org.eclipse.jetty.server.HttpConnection.onClose(HttpConnection.java:489) ~[?:?]
        at org.eclipse.jetty.io.ssl.SslConnection.onClose(SslConnection.java:217) ~[?:?]
        at org.eclipse.jetty.io.SelectorManager.connectionClosed(SelectorManager.java:345) ~[?:?]
        at org.eclipse.jetty.io.ManagedSelector$2.run(ManagedSelector.java:442) ~[?:?]
        ... 6 more
```

**Comment by Ghelten** [comment]
And I have the same problem. Are there any solutions?

**Comment by CWempe** [comment]
Could this be related?

https://community.openhab.org/t/favicon-in-basic-ui-welcome-page-not-working/52182

**Comment by lolodomo** [comment]
Finally that should be a different issue as there is no image path in my exception.
Please open a new issue.
