### ISSUE TITLE
UoM: Unit "One" does not support metric prefixes

### ISSUE THREAD

**Issue by alexf2015** [eclipse/smarthome#5930]
E.g. if you define the unit MetricPrefix.DECI(SmartHomeUnits.ONE) it will result in the unit-string "done" which is not known. An exception is thrown:

`2018-07-18 11:06:49.670 [ERROR] [c.internal.events.EventHandler:123 ] - Creation of ESH-Event failed, because one of the registered event factories has thrown an exception: Error invoking #valueOf(String) on class ‘org.eclipse.smarthome.core.library.types.QuantityType’ with value ‘384.0 done’.java.lang.IllegalStateException: Error invoking #valueOf(String) on class ‘org.eclipse.smarthome.core.library.types.QuantityType’ with value ‘384.0 done’.
at org.eclipse.smarthome.core.items.events.ItemEventFactory.parseSimpleClassName(ItemEventFactory.java:178)
at org.eclipse.smarthome.core.items.events.ItemEventFactory.parseType(ItemEventFactory.java:146)
at org.eclipse.smarthome.core.items.events.ItemEventFactory.getState(ItemEventFactory.java:124)
at org.eclipse.smarthome.core.items.events.ItemEventFactory.createStateEvent(ItemEventFactory.java:111)
at org.eclipse.smarthome.core.items.events.ItemEventFactory.createEventByType(ItemEventFactory.java:77)
at org.eclipse.smarthome.core.events.AbstractEventFactory.createEvent(AbstractEventFactory.java:50)
at org.eclipse.smarthome.core.internal.events.EventHandler.createESHEvent(EventHandler.java:121)
at org.eclipse.smarthome.core.internal.events.EventHandler.handleEvent(EventHandler.java:95)
at org.eclipse.smarthome.core.internal.events.EventHandler.handleEvent(EventHandler.java:72)
at org.eclipse.smarthome.core.internal.events.ThreadedEventHandler.lambda$0(ThreadedEventHandler.java:67)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException: null
at sun.reflect.GeneratedMethodAccessor79.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.eclipse.smarthome.core.items.events.ItemEventFactory.parseSimpleClassName(ItemEventFactory.java:169)
at org.eclipse.smarthome.core.items.events.ItemEventFactory.parseType(ItemEventFactory.java:146)
at org.eclipse.smarthome.core.items.events.ItemEventFactory.getState(ItemEventFactory.java:124)
at org.eclipse.smarthome.core.items.events.ItemEventFactory.createStateEvent(ItemEventFactory.java:111)
at org.eclipse.smarthome.core.items.events.ItemEventFactory.createEventByType(ItemEventFactory.java:77)
at org.eclipse.smarthome.core.events.AbstractEventFactory.createEvent(AbstractEventFactory.java:50)
at org.eclipse.smarthome.core.internal.events.EventHandler.createESHEvent(EventHandler.java:121)
at org.eclipse.smarthome.core.internal.events.EventHandler.handleEvent(EventHandler.java:95)
Caused by: java.lang.IllegalArgumentException: done not recognized (in 384.0 done at index 6)
at tec.uom.se.quantity.Quantities.getQuantity(Quantities.java:80)
at org.eclipse.smarthome.core.library.types.QuantityType.(QuantityType.java:91)
at org.eclipse.smarthome.core.library.types.QuantityType.valueOf(QuantityType.java:134)
at sun.reflect.GeneratedMethodAccessor79.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.eclipse.smarthome.core.items.events.ItemEventFactory.parseSimpleClassName(ItemEventFactory.java:169)
at org.eclipse.smarthome.core.items.events.ItemEventFactory.parseType(ItemEventFactory.java:146)
at org.eclipse.smarthome.core.items.events.ItemEventFactory.getState(ItemEventFactory.java:124)
at org.eclipse.smarthome.core.items.events.ItemEventFactory.createStateEvent(ItemEventFactory.java:111)
at org.eclipse.smarthome.core.items.events.ItemEventFactory.createEventByType(ItemEventFactory.java:77)`

**Comment by triller-telekom** [comment]
I do not understand what you mean by this issue.

The `Exception` that you posted is about that the `QuantityType` is unable to parse `384.0 done`. This is correct, because "done" is not a correct unit.

In the topic of the issue you say that the unit "ONE" does not support prefixes. "ONE" is just a placeholder for a number without any unit, that is why it cannot be converted to other units, it simply does not have a unit.

By "does not support prefixes" I understand that you wanted to have "mONE", like "milli ONE" or "kONE" like "kilo ONE", but what do you want to express with that?

BTW: Could you please format the pasted exceptions in `````` (3 ticks before and 3 after) so the code is more readable?

**Comment by triller-telekom** [comment]
Thanks for providing some more details.

So your use-case is that instead of sending 384, you want to send 38.4, right?

Is that within a binding or within a rule? Within a binding I would expect the binding to send "38.4" directly, without the need for converting it with "DECI".
