### ISSUE TITLE
Test failure: ItemRegistryOSGiTest.testItemRemovedEvent

### ISSUE THREAD

**Issue by triller-telekom** [eclipse/smarthome#5940]
Another one to our famous failing test collection :(

From https://travis-ci.org/eclipse/smarthome/builds/406133944

```
Failed tests: 
  ItemRegistryOSGiTest.testItemRemovedEvent:281->JavaTest.waitForAssert:73->JavaTest.waitForAssert:120->JavaTest.waitForAssert:152->lambda$4:281 
eventSubscriber.receive(
    <Capturing argument>
);
Wanted 1 time:
-> at org.eclipse.smarthome.core.items.ItemRegistryOSGiTest.lambda$4(ItemRegistryOSGiTest.java:281)
But was 4 times. Undesired invocation:
-> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by triller-telekom** [comment]
A related failure from https://travis-ci.org/eclipse/smarthome/builds/405878227

```
Results :

Failed tests: 
  ItemRegistryOSGiTest.testItemAddedEvent:250->JavaTest.waitForAssert:73->JavaTest.waitForAssert:120->JavaTest.waitForAssert:152->lambda$2:250 
eventSubscriber.receive(
    isA(org.eclipse.smarthome.core.items.events.ItemAddedEvent)
);
Wanted 1 time:
-> at org.eclipse.smarthome.core.items.ItemRegistryOSGiTest.lambda$2(ItemRegistryOSGiTest.java:250)
But was 5 times. Undesired invocation:
-> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by triller-telekom** [comment]
One more from https://travis-ci.org/eclipse/smarthome/builds/410925825

```
testItemRemovedEvent(org.eclipse.smarthome.core.items.ItemRegistryOSGiTest)  Time elapsed: 10.191 sec  <<< FAILURE!
org.mockito.exceptions.verification.TooManyActualInvocations: 
eventSubscriber.receive(
    <Capturing argument>
);
Wanted 1 time:
-> at org.eclipse.smarthome.core.items.ItemRegistryOSGiTest.lambda$4(ItemRegistryOSGiTest.java:297)
But was 7 times. Undesired invocation:
-> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at org.eclipse.smarthome.core.items.ItemRegistryOSGiTest.lambda$4(ItemRegistryOSGiTest.java:297)
```

**Comment by htreu** [comment]
This should be fixed by https://github.com/eclipse/smarthome/pull/6026.
