### ISSUE TITLE
[weatherunderground] Thing does not come online

### ISSUE THREAD

**Issue by chiefymuc** [eclipse/smarthome#6047]
Since the latest changes in the weatherunderground binding, I have updated my OH2.4.0.

Using the description from the readme (either by creating bridge and thing through PaperUI or *.things file).

The Bridge comes online immediately.
The Thing remains in "initializing" mode even after a long time or a reboot of the RPi3.

**Comment by htreu** [comment]
Are you able to attach/post a logfile (preferably with DEBUG or TRACE level) from the thing initialization?

**Comment by chiefymuc** [comment]
There is really not much there (unless I did something wrong):


```
openhab> log:set TRACE  org.openhab.binding.weatherunderground
openhab> bundle:list
...
221 │ Active   │  80 │ 0.10.0.201808130936    │ WeatherUnderground Binding
...
openhab> bundle:restart 221
openhab> log:get  org.openhab.binding.weatherunderground
TRACE
openhab> log:get
Logger                                             │ Level
───────────────────────────────────────────────────┼──────
ROOT                                               │ WARN
javax.jmdns                                        │ ERROR
org.apache.karaf.jaas.modules.audit                │ INFO
org.apache.karaf.kar.internal.KarServiceImpl       │ ERROR
org.apache.karaf.shell.support                     │ OFF
org.apache.sshd                                    │ ERROR
org.eclipse.smarthome                              │ INFO
org.jupnp                                          │ ERROR
org.openhab                                        │ INFO
org.openhab.binding.weatherunderground             │ TRACE
org.ops4j.pax.url.mvn.internal.AetherBasedResolver │ ERROR
org.ops4j.pax.web.pax-web-runtime                  │ OFF
smarthome.event                                    │ INFO
smarthome.event.InboxUpdatedEvent                  │ ERROR
smarthome.event.ItemAddedEvent                     │ ERROR
smarthome.event.ItemRemovedEvent                   │ ERROR
smarthome.event.ItemStateEvent                     │ ERROR
smarthome.event.ThingAddedEvent                    │ ERROR
smarthome.event.ThingRemovedEvent                  │ ERROR
smarthome.event.ThingStatusInfoEvent               │ ERROR
openhab> bundle:restart 221
openhab> log:tail
15:23:39.918 [INFO ] [ome.event.ThingStatusInfoChangedEvent] - 'weatherunderground:weather:224b466a' changed from UNINITIALIZED to INITIALIZING

```

**Comment by triller-telekom** [comment]
It is `org.eclipse.smarthome.binding.weatherunderground`, not `org.openhab.binding.weatherunderground`, can you please repeat it with the correct bundle name?

**Comment by chiefymuc** [comment]
Ok my bad. Here we go:

```
==> /var/log/openhab2/openhab.log <==

2018-08-16 17:41:25.627 [DEBUG] [smarthome.binding.weatherunderground] - BundleEvent STOPPING - org.eclipse.smarthome.binding.weatherunderground

2018-08-16 17:41:25.640 [DEBUG] [smarthome.binding.weatherunderground] - ServiceEvent UNREGISTERING - {org.eclipse.smarthome.core.thing.binding.ThingHandlerFactory}={service.id=343, service.bundleid=221, service.scope=bundle, component.name=org.eclipse.smarthome.binding.weatherunderground.internal.WeatherUndergroundHandlerFactory, component.id=217} - org.eclipse.smarthome.binding.weatherunderground

==> /var/log/openhab2/events.log <==

2018-08-16 17:41:25.664 [hingStatusInfoChangedEvent] - 'weatherunderground:weather:myAPI:Bremen' changed from INITIALIZING to UNINITIALIZED

==> /var/log/openhab2/openhab.log <==

2018-08-16 17:41:25.668 [DEBUG] [nd.handler.WeatherUndergroundHandler] - Disposing WeatherUnderground handler.

==> /var/log/openhab2/events.log <==

2018-08-16 17:41:25.685 [hingStatusInfoChangedEvent] - 'weatherunderground:weather:myAPI:Bremen' changed from UNINITIALIZED to UNINITIALIZED (HANDLER_MISSING_ERROR)

2018-08-16 17:41:25.691 [hingStatusInfoChangedEvent] - 'weatherunderground:bridge:myAPI' changed from ONLINE to UNINITIALIZED

2018-08-16 17:41:25.697 [hingStatusInfoChangedEvent] - 'weatherunderground:bridge:myAPI' changed from UNINITIALIZED to UNINITIALIZED (HANDLER_MISSING_ERROR)

==> /var/log/openhab2/openhab.log <==

2018-08-16 17:41:25.705 [DEBUG] [smarthome.binding.weatherunderground] - ServiceEvent UNREGISTERING - {org.eclipse.smarthome.config.discovery.DiscoveryService}={service.id=363, service.bundleid=221, service.scope=singleton} - org.eclipse.smarthome.binding.weatherunderground

2018-08-16 17:41:25.717 [DEBUG] [smarthome.binding.weatherunderground] - BundleEvent STOPPED - org.eclipse.smarthome.binding.weatherunderground

2018-08-16 17:41:25.722 [DEBUG] [smarthome.binding.weatherunderground] - BundleEvent STARTING - org.eclipse.smarthome.binding.weatherunderground

2018-08-16 17:41:25.756 [DEBUG] [smarthome.binding.weatherunderground] - ServiceEvent REGISTERED - {org.eclipse.smarthome.core.thing.binding.ThingHandlerFactory}={service.id=427, service.bundleid=221, service.scope=bundle, component.name=org.eclipse.smarthome.binding.weatherunderground.internal.WeatherUndergroundHandlerFactory, component.id=291} - org.eclipse.smarthome.binding.weatherunderground

2018-08-16 17:41:25.772 [DEBUG] [smarthome.binding.weatherunderground] - BundleEvent STARTED - org.eclipse.smarthome.binding.weatherunderground

==> /var/log/openhab2/events.log <==

2018-08-16 17:41:26.146 [me.event.ThingUpdatedEvent] - Thing 'network:pingdevice:sonytv' has been updated.

==> /var/log/openhab2/openhab.log <==

2018-08-16 17:41:26.762 [DEBUG] [smarthome.binding.weatherunderground] - ServiceEvent REGISTERED - {org.eclipse.smarthome.config.discovery.DiscoveryService}={service.id=428, service.bundleid=221, service.scope=singleton} - org.eclipse.smarthome.binding.weatherunderground

2018-08-16 17:41:26.783 [DEBUG] [dler.WeatherUndergroundBridgeHandler] - Initializing weatherunderground bridge handler.

==> /var/log/openhab2/events.log <==

2018-08-16 17:41:26.787 [hingStatusInfoChangedEvent] - 'weatherunderground:bridge:myAPI' changed from UNINITIALIZED (HANDLER_MISSING_ERROR) to INITIALIZING

==> /var/log/openhab2/openhab.log <==

2018-08-16 17:41:27.416 [DEBUG] [dler.WeatherUndergroundBridgeHandler] - apiResponse = 

{

  "response": {

  "version":"0.1",

  "termsofService":"http://www.wunderground.com/weather/api/d/terms.html",

  "features": {

  

  }

		

			,

	"error": {

		"type": "invalidquery"

		

			,"description": "you must supply a location query"

		

	}

		

		

	}

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

}

==> /var/log/openhab2/events.log <==

2018-08-16 17:41:27.458 [hingStatusInfoChangedEvent] - 'weatherunderground:bridge:myAPI' changed from INITIALIZING to ONLINE

==> /var/log/openhab2/openhab.log <==

2018-08-16 17:41:27.527 [DEBUG] [nd.handler.WeatherUndergroundHandler] - Initializing WeatherUnderground handler.

2018-08-16 17:41:27.531 [DEBUG] [nd.handler.WeatherUndergroundHandler] - config location = 53.0854,8.7463

2018-08-16 17:41:27.534 [DEBUG] [nd.handler.WeatherUndergroundHandler] - config language = EN

2018-08-16 17:41:27.536 [DEBUG] [nd.handler.WeatherUndergroundHandler] - config refresh = 15

2018-08-16 17:41:27.542 [DEBUG] [dler.WeatherUndergroundBridgeHandler] - Use language deduced from system locale en: null

==> /var/log/openhab2/events.log <==

2018-08-16 17:41:27.544 [hingStatusInfoChangedEvent] - 'weatherunderground:weather:myAPI:Bremen' changed from UNINITIALIZED (HANDLER_MISSING_ERROR) to INITIALIZING

==> /var/log/openhab2/openhab.log <==

2018-08-16 17:41:27.547 [DEBUG] [nd.handler.WeatherUndergroundHandler] - Exception occurred during execution: null

java.lang.NullPointerException: null

	at org.eclipse.smarthome.binding.weatherunderground.handler.WeatherUndergroundBridgeHandler.getWeatherData(WeatherUndergroundBridgeHandler.java:456) [221:org.eclipse.smarthome.binding.weatherunderground:0.10.0.201808130936]

	at org.eclipse.smarthome.binding.weatherunderground.handler.WeatherUndergroundHandler.updateWeatherData(WeatherUndergroundHandler.java:405) [221:org.eclipse.smarthome.binding.weatherunderground:0.10.0.201808130936]

	at org.eclipse.smarthome.binding.weatherunderground.handler.WeatherUndergroundHandler.access$0(WeatherUndergroundHandler.java:396) [221:org.eclipse.smarthome.binding.weatherunderground:0.10.0.201808130936]

	at org.eclipse.smarthome.binding.weatherunderground.handler.WeatherUndergroundHandler$1.run(WeatherUndergroundHandler.java:152) [221:org.eclipse.smarthome.binding.weatherunderground:0.10.0.201808130936]

	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]

	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:?]

	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:?]

	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
```

**Comment by htreu** [comment]
@GiovannaTheo could you have a look at this one please?

**Comment by openhab-5iver** [comment]
I'm also seeing this exception (OH snapshot 1330).

**Comment by vbier** [comment]
The WeatherUndergroundBridgeHandler tries to access the language configuration, which is defined in the WeatherUndergroundHandler. 

This is a regression caused by #5501. It would be nice to at least start and test things once before pushing them.

**Comment by GiovannaTheo** [comment]
Sorry, folks. I always tested the binding configuring the language option while adding new things, so it went unnoticed. The language parameter was indeed being pulled from the bridge config (which doesn't hold such parameter) instead of the thing config, which threw the exception. Fixed.

**Comment by mhilbush** [comment]
It would've been nice to log the NPE at Info level, at a minimum. That way there would be at least some indication what was wrong. There also was no clue in the list of commits for ESH #287 (Fix NPE in thing initialization wasn't very helpful, since I didn't have an NPE in the log). 

I usually don't complain, but I think the change to add the bridge functionality could've been handled better, especially the lack of backwards compatibility for the majority of users who don't need multiple weather things.

**Comment by triller-telekom** [comment]
Let me comment on your statement:

> lack of backwards compatibility for the majority of users who don't need multiple weather things

Unfortunately we added the WU binding without noticing that login credentials for webservices should be in a bridge instead of a thing. That was a mistake which has now been corrected. If we would have left it in there (maybe for backward compatibility as you say), we would have kept a bad example for a binding in the code base. ESH with version 0.10 is still away from a 1.0 where we **have to** keep the API stable and untouched.

But I agree that it is annoying for the users (including me) who now have to change their configurations.

**Comment by mhilbush** [comment]
I understand @triller-telekom. Sorry for venting.

I installed the latest build OH build (1334), which I think contains the fix, and I still think there's something wrong. When I discover a weather thing, I see this in the log.

From where is it trying to pull the language? I have my Region settings set to this.
```
org.eclipse.smarthome.core.i18nprovider:language=en
org.eclipse.smarthome.core.i18nprovider:region=US
```
But I don't have a language defined in my UI preferences.
```
2018-08-21 10:31:54.004 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'weatherunderground:weather:local' to inbox.
2018-08-21 10:31:58.237 [DEBUG] [nd.handler.WeatherUndergroundHandler] - Initializing WeatherUnderground handler.
2018-08-21 10:31:58.238 [DEBUG] [nd.handler.WeatherUndergroundHandler] - config location = xxxxxxx,yyyyyyy
2018-08-21 10:31:58.238 [DEBUG] [nd.handler.WeatherUndergroundHandler] - config language = null
2018-08-21 10:31:58.238 [DEBUG] [nd.handler.WeatherUndergroundHandler] - config refresh = 30
2018-08-21 10:31:58.239 [DEBUG] [dler.WeatherUndergroundBridgeHandler] - Use language deduced from system locale en: null
2018-08-21 10:31:58.240 [DEBUG] [nd.handler.WeatherUndergroundHandler] - Exception occurred during execution: null
java.lang.NullPointerException: null
	at org.eclipse.smarthome.binding.weatherunderground.handler.WeatherUndergroundBridgeHandler.getWeatherData(WeatherUndergroundBridgeHandler.java:452) [206:org.eclipse.smarthome.binding.weatherunderground:0.10.0.201808210705]
	at org.eclipse.smarthome.binding.weatherunderground.handler.WeatherUndergroundHandler.updateWeatherData(WeatherUndergroundHandler.java:405) [206:org.eclipse.smarthome.binding.weatherunderground:0.10.0.201808210705]
	at org.eclipse.smarthome.binding.weatherunderground.handler.WeatherUndergroundHandler.access$0(WeatherUndergroundHandler.java:396) [206:org.eclipse.smarthome.binding.weatherunderground:0.10.0.201808210705]
	at org.eclipse.smarthome.binding.weatherunderground.handler.WeatherUndergroundHandler$1.run(WeatherUndergroundHandler.java:152) [206:org.eclipse.smarthome.binding.weatherunderground:0.10.0.201808210705]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
```

**Comment by mhilbush** [comment]
So I don't see an `EN` entry in `LANG_ISO_TO_WU_CODES`. Therefore, `lang` is null at https://github.com/eclipse/smarthome/blob/b39fe45be22b7290269f1959803e49fda91cdb6a/extensions/binding/org.eclipse.smarthome.binding.weatherunderground/src/main/java/org/eclipse/smarthome/binding/weatherunderground/handler/WeatherUndergroundBridgeHandler.java#L448

**Comment by mhilbush** [comment]
I can confirm that the thing comes ONLINE when I set the language in the weather thing. So this is a different bug than what was fixed in PR #6067.

**Comment by GiovannaTheo** [comment]
@lolodomo handled this part of the code when the binding was first released so I'm not sure where to look. My guess is, since the key `EN` is not found in `LANG_ISO_TO_WU_CODES`, the `get()` returns a null value, which then triggers the NPE when `isEmpty()` is called. I believe this should fix it:

Instead of:

```java
lang = LANG_ISO_TO_WU_CODES.get(localeProvider.getLocale().getLanguage().toUpperCase());
```
Use:

```java
lang = StringUtils.trimToEmpty(LANG_ISO_TO_WU_CODES.get(localeProvider.getLocale().getLanguage().toUpperCase()));
```

The `trimToEmpty()` call will return an empty String if a null value is provided, which would then allow the code to continue its normal flow.

**Comment by mhilbush** [comment]
What about adding this to the table in addition to the above.
```
LANG_ISO_TO_WU_CODES.put("EN", "EN");
```
@lolodomo Is there a reason why this wasn't included in `LANG_ISO_TO_WU_CODES` (other than the fact that it's not included in the table [here](https://www.wunderground.com/weather/api/d/docs?d=resources/country-to-iso-matching))?

**Comment by GiovannaTheo** [comment]
Yes it needs to be added ; but rather than having an issue open for each missing language code that might arise in the future, we should also take care of the NPE itself for whenever the `get()` call returns `null`.

**Comment by lolodomo** [comment]
Yes I certainly considered only the official table from WU.

**Comment by lolodomo** [comment]
I think there is no need to add an entry. If entry is not found, simply use the ISO code. Isn't it what I first implemented ?

**Comment by mhilbush** [comment]
I don't think so.

If there's no entry in `LANG_ISO_TO_WU_CODES` [here](https://github.com/GiovannaTheo/smarthome/blob/2bb4894e2f6159f84a4e62e009dd51fc328206d3/extensions/binding/org.eclipse.smarthome.binding.weatherunderground/src/main/java/org/eclipse/smarthome/binding/weatherunderground/handler/WeatherUndergroundBridgeHandler.java#L448), `lang` is null and never gets set to the the system language. Do you need a statement to set lang?

```
if (lang == null) {
    lang = localeProvider.getLocale().getLanguage()
}
```

**Comment by mhilbush** [comment]
Or, alternatively, since auto discovery sets the location from the system configuration location information, why doesn't it also set the language?

**Comment by mhilbush** [comment]
I also noticed that even after entering a language to the auto-discovered local weather thing configuration, the thing still shows INITIALIZING. I had to stop/start the binding in order for the local weather thing to come ONLINE.

**Comment by mhilbush** [comment]
It appears to me there are multiple holes / edge cases as a result of the change to add a bridge (and auto discovery).

**Comment by lolodomo** [comment]
I just installed the snapshot 1337 and my WU things comes ONLINE but I have a warning at startup:
```
11:19:30.438 [INFO ] [del.core.internal.ModelRepositoryImpl] - Validation issues found in configuration model 'wu.things', using it anyway:
Provide a thing type ID and a thing ID in this format:
 <thingTypeId> <thingId>
11:19:30.450 [INFO ] [del.core.internal.ModelRepositoryImpl] - Loading model 'wu.things'
```
I followed the example in the documentation. Here is my file:
```
Bridge weatherunderground:bridge:API "WU API" [ apikey="xxxxxxxxxxxxxx" ] {
    Thing weatherunderground:weather:maison "WU maison" [ location="yyyyyyyyy,zzzzzzzz" ]
}
```
There is probably something wrong in the example.

**Comment by lolodomo** [comment]
Ok I found the issue and I will fix the documentation.

**Comment by lolodomo** [comment]
I changed my file like that:
```
Bridge weatherunderground:bridge:api "WU API" [ apikey="xxxxxxxxxxxxxx" ] {
    Thing weather maison "WU maison" [ location="yyyyyyyyy,zzzzzzzz" ]
}
```
But in this case, the channel links must be updated to `weatherunderground:weather:api:maison:<channel>`. That would mean all the example is wrong in the documentation.
@GiovannaTheo  ?

**Comment by lolodomo** [comment]
I got this warning:
```
2018-08-24 21:20:34.822 [WARN ] [ome.core.thing.internal.ThingManager] - Initializing handler for thing 'weatherunderground:bridge:api' takes more than 5000ms.
```
Looking at the code, I see several problems in the way the bridge/thing handling is implemented.
First, a HTTP call is run in the bridge initialize() which leads to the above warning. The HTTP calls should be done in a separate thread and initialize() should return fast.
Second, the thing initialize() is not always setting a status (I think it is necessary).
Third, the thing handler is not taking into account the state of the bridge handler. In case the bridge status is set to OFFLINE, the things should be set to OFFLINE (BRIDGE_OFFLINE) too. There is a classical pattern for doing that (example in several bindings) but it was not used here.
To be clear, the way the bridge/thing was implemented is not clean at all in my opinion.

**Comment by lolodomo** [comment]
LocaleProvider is passed to the thing handler but it should rather be passed to the bridge handler as only the bridge handler is using it.

@mhilbush : considering the system language at discovery time to search for the WU code and set the thing setting with it has no real interest as it is what will be done when fectching new data while the language is unbdefined. The interest to keep it at this place is that if you change your OH regional language, your WU language will be updated automatically when new data are fetched because no language is setup on the thing.

By the way, I will try to fix all the little weird things I can see.

**Comment by lolodomo** [comment]
I am asking myself if there is a valid reason to define and use a Gson instance for each thing ?
Are there problems if the same Gson object is used in concurrence ?
Is it too much expensive to instantiate a local Gson object in the method getWeatherData ?

**Comment by mhilbush** [comment]
> if you change your OH regional language, your WU language will be updated automatically when new data are fetched because no language is setup on the thing

That's right. And that's why I was suggesting the possibility of setting the weather Thing language during auto-discovery. By setting the weather Thing language during auto-discovery, language would work consistently with location.

In other words, once location and language are set on the weather Thing during auto-discovery, neither will be influenced by any change in the system config.

**Comment by lolodomo** [comment]
Ok, you see it in the opposite direction than me, you expect a frozen language., I don't know.

Regarding the bug with the null language, I can see in my initial code that I have a test with null. I don't know why this test was then suppressed:
https://github.com/eclipse/smarthome/pull/5074/files#diff-072956afd69376ef1581e36e431deb0dR551

If the language is not found in the table, we just have to not set any language in the request. This will return data in English by default.
If one day WU adds new language, you will be able to set it through the thing setting.

**Comment by htreu** [comment]
> By the way, I will try to fix all the little weird things I can see.

Thanks @lolodomo for taking this on. Will you provide a PR fixing the mentioned issues?

**Comment by htreu** [comment]
please forgive my ignorance, I just stumbled across #6121.
