### ISSUE TITLE
[test failures] Failure in OwserverBridgeHandlerTest

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#6070]
From https://travis-ci.org/eclipse/smarthome/builds/417144378?utm_source=github_status&utm_medium=notification:

```
Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 10.168 sec <<< FAILURE! - in org.eclipse.smarthome.binding.onewire.internal.OwserverBridgeHandlerTest
testInitializationReportsNotRefreshableOnFailedConnection(org.eclipse.smarthome.binding.onewire.internal.OwserverBridgeHandlerTest)  Time elapsed: 0.114 sec
testInitializationReportsRefreshableOnSuccessfullConnection(org.eclipse.smarthome.binding.onewire.internal.OwserverBridgeHandlerTest)  Time elapsed: 10.046 sec  <<< FAILURE!
java.lang.AssertionError: expected:<ONLINE> but was:<UNKNOWN>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.eclipse.smarthome.binding.onewire.internal.OwserverBridgeHandlerTest.lambda$3(OwserverBridgeHandlerTest.java:106)
testInitializationStartsConnectionWithOptions(org.eclipse.smarthome.binding.onewire.internal.OwserverBridgeHandlerTest)  Time elapsed: 0.003 sec
```

@J-N-K Could you check how this test could be improved?

**Comment by J-N-K** [comment]
Are there still failures of that test? I can‘t reproduce it and have not seen in failing kn any of the latest PR.

**Comment by maggu2810** [comment]
I assume we can close it and reopen if it is seen again.
