### ISSUE TITLE
delayed bridge handler creation is broken

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#6088]
Steps to reproduce:
* Use the Eclipse IDE
* remove all demo configuration from "distribution/smarthome/conf/*"
* ensure "distribution/userdata" is empty
* start the "SmartHome-Runtime" launch configuration
* wait until the system is fully up and running
* disable the MagicHandlerFactory:
`scr:disable org.eclipse.smarthome.magic.binding.internal.MagicHandlerFactory`
* use the Paper UI to add a manually a new thing of the Magic binding, choose a bridge e.g. "Magic Bridge 1"
* the thing keeps uninitialized, no handler exists
* enable the handler factory service:
`scr:enable org.eclipse.smarthome.magic.binding.internal.MagicHandlerFactory`

Expected behavior:
The thing handler for the bridge thing will be inizialized

Current behavior:
Class cast exception, see log

Log:
```text
osgi> scr:disable org.eclipse.smarthome.magic.binding.internal.MagicHandlerFactory
Component org.eclipse.smarthome.magic.binding.internal.MagicHandlerFactory disabled

14:31:10.636 DEBUG o.e.s.c.t.i.ThingManager[:1051] - Thing handler factory 'MagicHandlerFactory' removed


14:31:17.770 DEBUG o.e.s.c.d.i.DiscoveryServiceRegistryImpl[:424] - Triggering scan for thing types '[magic:configurable-thing]' on 'MagicDiscoveryService'...

14:31:17.815 INFO  o.e.s.c.d.i.PersistentInbox[:194] - Added new thing 'magic:configurable-thing:2e65f00a-1372-4097-9b8a-a2f8c5d32316' to inbox.
14:31:17.816 INFO  s.event.InboxAddedEvent[:53] - Discovery Result with UID 'magic:configurable-thing:2e65f00a-1372-4097-9b8a-a2f8c5d32316' has been added.
14:31:39.965 DEBUG o.e.s.i.r.s.i.SitemapResource[:168] - Run clean SSE subscriptions job
14:31:59.010 DEBUG o.e.s.c.t.i.ThingRegistryImpl[:247] - Creating thing for type 'magic:magic-bridge1'.
14:31:59.011 WARN  o.e.s.c.t.i.ThingRegistryImpl[:255] - Cannot create thing. No binding found that supports creating a thing of type 'magic:magic-bridge1'.
14:31:59.057 DEBUG o.e.s.c.t.i.ThingManager[:421] - Thing 'magic:magic-bridge1:3865850b' is tracked by ThingManager.
14:31:59.058 DEBUG o.e.s.c.t.i.ThingManager[:1035] - Not registering a handler at this point since no handler factory for thing 'magic:magic-bridge1:3865850b' found.
14:31:59.059 DEBUG o.e.s.c.t.i.ThingManager[:1025] - Not registering a handler at this point. No handler factory for thing 'magic:magic-bridge1:3865850b' found.
14:31:59.059 DEBUG o.e.s.c.c.r.AbstractManagedProvider[:62] - Added new element magic:magic-bridge1:3865850b to ManagedThingProvider.
14:31:59.058 INFO  s.event.ThingAddedEvent[:53] - Thing 'magic:magic-bridge1:3865850b' has been added.

osgi> scr:enable org.eclipse.smarthome.magic.binding.internal.MagicHandlerFactory

Component org.eclipse.smarthome.magic.binding.internal.MagicHandlerFactory enabled
14:33:26.711 DEBUG o.e.s.c.t.i.ThingManager[:964] - Thing handler factory 'MagicHandlerFactory' added
14:33:26.712 DEBUG o.e.s.c.t.i.ThingManager[:563] - Calling 'MagicHandlerFactory.registerHandler()' for thing 'magic:magic-bridge1:3865850b'.
14:33:26.718 INFO  s.event.ThingStatusInfoEvent[:53] - 'magic:magic-bridge1:3865850b' updated: UNINITIALIZED (HANDLER_REGISTERING_ERROR): org.eclipse.smarthome.core.thing.internal.ThingImpl cannot be cast to org.eclipse.smarthome.core.thing.Bridge
14:33:26.731 INFO  s.e.ThingStatusInfoChangedEvent[:53] - 'magic:magic-bridge1:3865850b' changed from UNINITIALIZED to UNINITIALIZED (HANDLER_REGISTERING_ERROR): org.eclipse.smarthome.core.thing.internal.ThingImpl cannot be cast to org.eclipse.smarthome.core.thing.Bridge
14:33:26.757 ERROR o.e.s.c.t.i.ThingManager[:576] - Exception occurred while calling thing handler factory 'org.eclipse.smarthome.magic.binding.internal.MagicHandlerFactory@6b1f2ff7': org.eclipse.smarthome.core.thing.internal.ThingImpl cannot be cast to org.eclipse.smarthome.core.thing.Bridge
java.lang.ClassCastException: org.eclipse.smarthome.core.thing.internal.ThingImpl cannot be cast to org.eclipse.smarthome.core.thing.Bridge
	at org.eclipse.smarthome.magic.binding.internal.MagicHandlerFactory.createHandler(MagicHandlerFactory.java:104)
	at org.eclipse.smarthome.core.thing.binding.BaseThingHandlerFactory.registerHandler(BaseThingHandlerFactory.java:119)
	at org.eclipse.smarthome.core.thing.internal.ThingManager.doRegisterHandler(ThingManager.java:566)
	at org.eclipse.smarthome.core.thing.internal.ThingManager.registerHandler(ThingManager.java:543)
	at org.eclipse.smarthome.core.thing.internal.ThingManager.registerAndInitializeHandler(ThingManager.java:1017)
	at org.eclipse.smarthome.core.thing.internal.ThingManager.lambda$9(ThingManager.java:1000)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891)
	at java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:404)
	at org.eclipse.smarthome.core.thing.internal.ThingManager.lambda$8(ThingManager.java:997)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
14:33:26.758 DEBUG o.e.s.m.t.i.GenericThingProvider[:860] - ThingHandlerFactory added org.eclipse.smarthome.magic.binding.internal.MagicHandlerFactory@6b1f2ff7
```

**Comment by maggu2810** [comment]
It is caused by the thing resources code to add a new thing:

```Java
    public Response create(@HeaderParam(HttpHeaders.ACCEPT_LANGUAGE) @ApiParam(value = "language") String language,
            @ApiParam(value = "thing data", required = true) ThingDTO thingBean) {

...

        Thing thing = thingRegistry.createThingOfType(thingTypeUID, thingUID, bridgeUID, thingBean.label,
                configuration);

... null is returned because there is no factory ...

        if (thing != null) {
...
        } else if (thingUID != null) {
            // if there wasn't any ThingFactory capable of creating the thing,
            // we create the Thing exactly the way we received it, i.e. we
            // cannot take its thing type into account for automatically
            // populating channels and properties.
            thing = ThingDTOMapper.map(thingBean);
        } else {
...
        }

        thingRegistry.add(thing);
...
    }
```

If the type itself is known and we "know" that that type is a bridge, shouldn't a bridge be created instead of a thing?
