### ISSUE TITLE
DigitalStrom Binding 2.3 NullPointerException

### ISSUE THREAD

**Issue by dylancollaud** [eclipse/smarthome#6090]
Hi, 

I recentrly install for the first time this binding on OpenHab. The system cannot find automaticaly devices. I've to add manualy with login and ip. After that, i see OH communicate with my digitalstrom but an NullPointerException appear in the console.

```
15:28:36.192 [INFO ] [smarthome.event.ExtensionEvent       ] - Extension 'binding-digitalstrom' has been installed.
15:29:56.917 [INFO ] [ome.event.ThingStatusInfoChangedEvent] - 'digitalstrom:dssBridge:5679fb7c' changed from UNINITIALIZED to INITIALIZING
15:29:56.938 [INFO ] [ome.event.ThingStatusInfoChangedEvent] - 'digitalstrom:dssBridge:5679fb7c' changed from INITIALIZING to ONLINE (CONFIGURATION_PENDING): Checking configuration...
15:29:57.534 [INFO ] [ome.event.ThingStatusInfoChangedEvent] - 'digitalstrom:dssBridge:5679fb7c' changed from ONLINE (CONFIGURATION_PENDING): Checking configuration... to OFFLINE (CONFIGURATION_ERROR): The set username or password is wrong.
15:29:58.377 [INFO ] [smarthome.event.ThingUpdatedEvent    ] - Thing 'digitalstrom:dssBridge:5679fb7c' has been updated.
15:30:14.544 [INFO ] [smarthome.event.ThingUpdatedEvent    ] - Thing 'digitalstrom:dssBridge:5679fb7c' has been updated.
15:30:14.555 [INFO ] [ome.event.ThingStatusInfoChangedEvent] - 'digitalstrom:dssBridge:5679fb7c' changed from OFFLINE (CONFIGURATION_ERROR): The set username or password is wrong. to ONLINE (CONFIGURATION_PENDING): Checking configuration...
15:30:15.876 [INFO ] [smarthome.event.ThingUpdatedEvent    ] - Thing 'digitalstrom:dssBridge:5679fb7c' has been updated.
15:30:17.784 [INFO ] [smarthome.event.ThingUpdatedEvent    ] - Thing 'digitalstrom:dssBridge:5679fb7c' has been updated.
15:30:17.804 [INFO ] [smarthome.event.ThingUpdatedEvent    ] - Thing 'digitalstrom:dssBridge:5679fb7c' has been updated.
15:30:18.366 [WARN ] [ommon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception
java.lang.NullPointerException: null
        at org.eclipse.smarthome.binding.digitalstrom.internal.lib.structure.devices.impl.DeviceImpl.<init>(DeviceImpl.java:182) [204:org.eclipse.smarthome.binding.digitalstrom:0.10.0.oh230]
        at org.eclipse.smarthome.binding.digitalstrom.internal.lib.manager.impl.DeviceStatusManagerImpl$PollingRunnable.getDetailedDevices(DeviceStatusManagerImpl.java:416) [204:org.eclipse.smarthome.binding.digitalstrom:0.10.0.oh230]
        at org.eclipse.smarthome.binding.digitalstrom.internal.lib.manager.impl.DeviceStatusManagerImpl$PollingRunnable.run(DeviceStatusManagerImpl.java:254) [204:org.eclipse.smarthome.binding.digitalstrom:0.10.0.oh230]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]
```

I check other issues but I don't found the same. What is the problem ? If you want, I can try single compilation of this binding and check if all is good.

Best regards

Dylan Collaud

**Comment by kaikreuzer** [comment]
Thanks for the report! I have created #6093, which should hopefully fix the issue.
