### ISSUE TITLE
digitalstrom binding - exception error

### ISSUE THREAD

**Issue by maxx92** [eclipse/smarthome#6122]
Hello all.
I have following error message on boot up. I can not figure out where to look to get rid of it. Anyone to the rescue?

```
2018-08-26 10:54:33.866 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception
java.lang.IllegalArgumentException: Value must be between 0 and 100
	at org.eclipse.smarthome.core.library.types.PercentType.validateValue(PercentType.java:55) [101:org.eclipse.smarthome.core:0.10.0.201805241348]
	at org.eclipse.smarthome.core.library.types.PercentType.<init>(PercentType.java:40) [101:org.eclipse.smarthome.core:0.10.0.201805241348]
	at org.eclipse.smarthome.binding.digitalstrom.handler.DeviceHandler.onDeviceStateChanged(DeviceHandler.java:396) [241:org.eclipse.smarthome.binding.digitalstrom:0.10.0.201806271317]
	at org.eclipse.smarthome.binding.digitalstrom.internal.lib.structure.devices.impl.DeviceImpl.informListenerAboutStateUpdate(DeviceImpl.java:1669) [241:org.eclipse.smarthome.binding.digitalstrom:0.10.0.201806271317]
	at org.eclipse.smarthome.binding.digitalstrom.internal.lib.structure.devices.impl.DeviceImpl.updateInternalDeviceState(DeviceImpl.java:1516) [241:org.eclipse.smarthome.binding.digitalstrom:0.10.0.201806271317]
	at org.eclipse.smarthome.binding.digitalstrom.internal.lib.sensorjobexecutor.sensorjob.impl.DeviceOutputValueSensorJob.execute(DeviceOutputValueSensorJob.java:75) [241:org.eclipse.smarthome.binding.digitalstrom:0.10.0.201806271317]
	at org.eclipse.smarthome.binding.digitalstrom.internal.lib.sensorjobexecutor.AbstractSensorJobExecutor$ExecutorRunnable.run(AbstractSensorJobExecutor.java:73) [241:org.eclipse.smarthome.binding.digitalstrom:0.10.0.201806271317]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
```

**Comment by maxx92** [comment]
Sorry, forgot to mention: I use snapshot 2.4 on a raspberry...

**Comment by maggu2810** [comment]
@maxx There is not Eclipse SmartHmoe Snapshot 2.4. :wink:
Sure, we know you refer to openHAB. "Snapshot" does not state which version of ESH you base on and not which of OH it just state it has been a snapshot at a special point of time.

The timestamped version of OH and ESH can be found using different approaches, here some info:
https://github.com/eclipse/smarthome/wiki/ESH-used-in-openHAB

If seems a percent type is created with a value that does not fit in the range [0;100].
The stack trace identifies `org.eclipse.smarthome.binding.digitalstrom.handler.DeviceHandler.onDeviceStateChanged` in its trace, so I assume the binding itself must be hardened to check the input before the creation of a `PercentType`.

(@maxx92 I edited your commen to use correct format for longer preformatted code. You need to use three instead of one apostroph.)
