### ISSUE TITLE
Exception during AutomaticInboxProcessor component activation

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#6192]
This is from my logs:
```
13:26:18.233 [ERROR] [rg.eclipse.smarthome.config.discovery] - [org.eclipse.smarthome.config.discovery.internal.AutomaticInboxProcessor(222)] The activate method has thrown an exception
java.lang.ClassCastException: org.eclipse.smarthome.config.discovery.internal.DiscoveryResultImpl cannot be cast to org.eclipse.smarthome.config.discovery.DiscoveryResult
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) [?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) [?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) [?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) [?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) [?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) [?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) [?:?]
	at org.eclipse.smarthome.config.discovery.internal.PersistentInbox.getAll(PersistentInbox.java:295) [90:org.eclipse.smarthome.config.discovery:0.10.0.201809111909]
	at org.eclipse.smarthome.config.discovery.internal.AutomaticInboxProcessor.autoApproveInboxEntries(AutomaticInboxProcessor.java:230) [90:org.eclipse.smarthome.config.discovery:0.10.0.201809111909]
	at org.eclipse.smarthome.config.discovery.internal.AutomaticInboxProcessor.activate(AutomaticInboxProcessor.java:249) [90:org.eclipse.smarthome.config.discovery:0.10.0.201809111909]
```
Looks like some lifecycle issue as this happened during bundle updates.

**Comment by kaikreuzer** [comment]
Should hopefully be fixed by https://github.com/eclipse/smarthome/pull/6237.
