### ISSUE TITLE
An error occurred while calling method 'EventSubscriber.receive()'

### ISSUE THREAD

**Issue by openhab-5iver** [eclipse/smarthome#6201]
OH snapshot 1361 (same on 1360 too)
ESH 0.10.0.201809111909 

When the Auto Update option has not been selected for a managed item, the following error will occur when manipulating the item, and any linked channels are not updated. An item can be created without choosing an Auto Update option, and it's a new field, so previously created items would not have it populated either.
```
2018-09-13 12:48:56.985 [ERROR] [org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler] - An error occurred while calling method 'EventSubscriber.receive()' on 'org.eclipse.smarthome.core.thing.internal.CommunicationManager@ad062db': null
java.lang.NullPointerException: null
        at org.eclipse.smarthome.core.thing.internal.AutoUpdateManager.receiveCommand(AutoUpdateManager.java:141) [114:org.eclipse.smarthome.core.thing:0.10.0.201809111909]
        at org.eclipse.smarthome.core.thing.internal.CommunicationManager.receiveCommand(CommunicationManager.java:266) [114:org.eclipse.smarthome.core.thing:0.10.0.201809111909]
        at org.eclipse.smarthome.core.thing.internal.CommunicationManager.receive(CommunicationManager.java:145) [114:org.eclipse.smarthome.core.thing:0.10.0.201809111909]
        at sun.reflect.GeneratedMethodAccessor16.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
        at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) [108:org.eclipse.smarthome.core:0.10.0.201809111909]
        at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:53) [108:org.eclipse.smarthome.core:0.10.0.201809111909]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]
2018-09-13 12:48:57.003 [ERROR] [org.eclipse.smarthome.core.internal.events.EventHandler] - Dispatching/filtering event for subscriber 'org.eclipse.smarthome.core.events.EventSubscriber' failed: null
java.lang.NullPointerException: null
        at org.eclipse.smarthome.core.thing.internal.AutoUpdateManager.receiveCommand(AutoUpdateManager.java:141) [114:org.eclipse.smarthome.core.thing:0.10.0.201809111909]
        at org.eclipse.smarthome.core.thing.internal.CommunicationManager.receiveCommand(CommunicationManager.java:266) [114:org.eclipse.smarthome.core.thing:0.10.0.201809111909]
        at org.eclipse.smarthome.core.thing.internal.CommunicationManager.receive(CommunicationManager.java:145) [114:org.eclipse.smarthome.core.thing:0.10.0.201809111909]
        at sun.reflect.GeneratedMethodAccessor16.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
        at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) [108:org.eclipse.smarthome.core:0.10.0.201809111909]
        at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:53) [108:org.eclipse.smarthome.core:0.10.0.201809111909]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]
```
More discussion here...
https://community.openhab.org/t/new-zwave-device-fails-attempts-to-fix-leads-to-all-new-thing-names-breaking-item-links-and-rules/51326/25?u=5iver

Possibly related to this issue, items were very laggy after an OH restart, and then all became unresponsive. After about 15 minutes, everything came back and responded as normal. Another user reported the same in the forum thread linked above.

**Comment by htreu** [comment]
I can confirm this bug. Its in Paper UI and in the item REST resource. Fix is on the way.
