### ISSUE TITLE
Circular reference detected trying to get service {org.eclipse.smarthome.config.discovery.inbox.Inbox}

### ISSUE THREAD

**Issue by cweitkamp** [eclipse/smarthome#6216]
OH 2.4.0-SNAPSHOT Build 1363

```
2018-09-16 12:47:41.808 [ERROR] [org.apache.felix.scr                ] - bundle org.apache.felix.scr:2.1.2 (39)Circular reference detected trying to get service {org.eclipse.smarthome.config.discovery.inbox.Inbox}={service.id=366, service.bundleid=96, service.scope=bundle, component.name=org.eclipse.smarthome.config.discovery.internal.PersistentInbox, component.id=220}
 stack of references: ServiceReference: {org.eclipse.smarthome.config.discovery.inbox.Inbox}={service.id=366, service.bundleid=96, service.scope=bundle, component.name=org.eclipse.smarthome.config.discovery.internal.PersistentInbox, component.id=220}
ServiceReference: {org.eclipse.smarthome.config.discovery.DiscoveryServiceRegistry}={service.id=365, service.bundleid=96, service.scope=bundle, component.name=org.eclipse.smarthome.config.discovery.internal.DiscoveryServiceRegistryImpl, component.id=221}

java.lang.Exception: stack trace
        at org.apache.felix.scr.impl.ComponentRegistry.enterCreate(ComponentRegistry.java:481) [39:org.apache.felix.scr:2.1.2]
        at org.apache.felix.scr.impl.BundleComponentActivator.enterCreate(BundleComponentActivator.java:735) [39:org.apache.felix.scr:2.1.2]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:845) [39:org.apache.felix.scr:2.1.2]
        at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse$1.run(ServiceFactoryUse.java:212) [?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.factoryGetService(ServiceFactoryUse.java:210) [?:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.getService(ServiceFactoryUse.java:111) [?:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceConsumer$2.getService(ServiceConsumer.java:45) [?:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.getService(ServiceRegistrationImpl.java:508) [?:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.getService(ServiceRegistry.java:461) [?:?]
        at org.eclipse.osgi.internal.framework.BundleContextImpl.getService(BundleContextImpl.java:624) [?:?]
        at org.apache.felix.scr.impl.manager.SingleRefPair.getServiceObject(SingleRefPair.java:73) [39:org.apache.felix.scr:2.1.2]
        at org.apache.felix.scr.impl.inject.BindParameters.getServiceObject(BindParameters.java:47) [39:org.apache.felix.scr:2.1.2]
        at org.apache.felix.scr.impl.inject.methods.BindMethod.getServiceObject(BindMethod.java:662) [39:org.apache.felix.scr:2.1.2]
        at org.apache.felix.scr.impl.manager.DependencyManager.getServiceObject(DependencyManager.java:2304) [39:org.apache.felix.scr:2.1.2]
        at org.apache.felix.scr.impl.manager.DependencyManager$SingleDynamicCustomizer.prebind(DependencyManager.java:962) [39:org.apache.felix.scr:2.1.2]
        at org.apache.felix.scr.impl.manager.DependencyManager.prebind(DependencyManager.java:1576) [39:org.apache.felix.scr:2.1.2]
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.collectDependencies(AbstractComponentManager.java:1014) [39:org.apache.felix.scr:2.1.2]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:899) [39:org.apache.felix.scr:2.1.2]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:863) [39:org.apache.felix.scr:2.1.2]
        at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse$1.run(ServiceFactoryUse.java:212) [?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.factoryGetService(ServiceFactoryUse.java:210) [?:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.getService(ServiceFactoryUse.java:111) [?:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceConsumer$2.getService(ServiceConsumer.java:45) [?:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.getService(ServiceRegistrationImpl.java:508) [?:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.getService(ServiceRegistry.java:461) [?:?]
        at org.eclipse.osgi.internal.framework.BundleContextImpl.getService(BundleContextImpl.java:624) [?:?]
        at org.apache.felix.scr.impl.manager.SingleRefPair.getServiceObject(SingleRefPair.java:73) [39:org.apache.felix.scr:2.1.2]
        at org.apache.felix.scr.impl.inject.BindParameters.getServiceObject(BindParameters.java:47) [39:org.apache.felix.scr:2.1.2]
        at org.apache.felix.scr.impl.inject.methods.BindMethod.getServiceObject(BindMethod.java:662) [39:org.apache.felix.scr:2.1.2]
        at org.apache.felix.scr.impl.manager.DependencyManager.getServiceObject(DependencyManager.java:2304) [39:org.apache.felix.scr:2.1.2]
        at org.apache.felix.scr.impl.manager.DependencyManager$SingleStaticCustomizer.prebind(DependencyManager.java:1162) [39:org.apache.felix.scr:2.1.2]
        at org.apache.felix.scr.impl.manager.DependencyManager.prebind(DependencyManager.java:1576) [39:org.apache.felix.scr:2.1.2]
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.collectDependencies(AbstractComponentManager.java:1014) [39:org.apache.felix.scr:2.1.2]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:899) [39:org.apache.felix.scr:2.1.2]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:863) [39:org.apache.felix.scr:2.1.2]
        at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse$1.run(ServiceFactoryUse.java:212) [?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.factoryGetService(ServiceFactoryUse.java:210) [?:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.getService(ServiceFactoryUse.java:111) [?:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceConsumer$2.getService(ServiceConsumer.java:45) [?:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.getService(ServiceRegistrationImpl.java:508) [?:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.getService(ServiceRegistry.java:461) [?:?]
        at org.eclipse.osgi.internal.framework.BundleContextImpl.getService(BundleContextImpl.java:624) [?:?]
        at com.eclipsesource.jaxrs.publisher.internal.ResourceTracker.addingService(ResourceTracker.java:39) [20:com.eclipsesource.jaxrs.publisher:5.3.1.201602281253]
        at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:941) [?:?]
        at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:870) [?:?]
        at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256) [?:?]
        at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229) [?:?]
        at org.osgi.util.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:901) [?:?]
        at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:109) [?:?]
        at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:920) [?:?]
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) [?:?]
        at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148) [?:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:862) [?:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:801) [?:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:127) [?:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:225) [?:?]
        at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:469) [?:?]
        at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:891) [39:org.apache.felix.scr:2.1.2]
        at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:877) [39:org.apache.felix.scr:2.1.2]
        at org.apache.felix.scr.impl.manager.RegistrationManager.changeRegistration(RegistrationManager.java:128) [39:org.apache.felix.scr:2.1.2]
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.registerService(AbstractComponentManager.java:944) [39:org.apache.felix.scr:2.1.2]
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:727) [39:org.apache.felix.scr:2.1.2]
        at org.apache.felix.scr.impl.manager.DependencyManager$SingleStaticCustomizer.addedService(DependencyManager.java:1053) [39:org.apache.felix.scr:2.1.2]
        at org.apache.felix.scr.impl.manager.DependencyManager$SingleStaticCustomizer.addedService(DependencyManager.java:1007) [39:org.apache.felix.scr:2.1.2]
        at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.customizerAdded(ServiceTracker.java:1216) [39:org.apache.felix.scr:2.1.2]
        at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.customizerAdded(ServiceTracker.java:1137) [39:org.apache.felix.scr:2.1.2]
        at org.apache.felix.scr.impl.manager.ServiceTracker$AbstractTracked.trackAdding(ServiceTracker.java:944) [39:org.apache.felix.scr:2.1.2]
        at org.apache.felix.scr.impl.manager.ServiceTracker$AbstractTracked.track(ServiceTracker.java:880) [39:org.apache.felix.scr:2.1.2]
        at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:1168) [39:org.apache.felix.scr:2.1.2]
        at org.apache.felix.scr.impl.BundleComponentActivator$ListenerInfo.serviceChanged(BundleComponentActivator.java:125) [39:org.apache.felix.scr:2.1.2]
        at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:109) [?:?]
        at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:920) [?:?]
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) [?:?]
        at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148) [?:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:862) [?:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:801) [?:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:127) [?:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:225) [?:?]
        at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:469) [?:?]
        at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:891) [39:org.apache.felix.scr:2.1.2]
        at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:877) [39:org.apache.felix.scr:2.1.2]
        at org.apache.felix.scr.impl.manager.RegistrationManager.changeRegistration(RegistrationManager.java:128) [39:org.apache.felix.scr:2.1.2]
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.registerService(AbstractComponentManager.java:944) [39:org.apache.felix.scr:2.1.2]
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:727) [39:org.apache.felix.scr:2.1.2]
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.enableInternal(AbstractComponentManager.java:661) [39:org.apache.felix.scr:2.1.2]
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.enable(AbstractComponentManager.java:427) [39:org.apache.felix.scr:2.1.2]
        at org.apache.felix.scr.impl.manager.ConfigurableComponentHolder.enableComponents(ConfigurableComponentHolder.java:665) [39:org.apache.felix.scr:2.1.2]
        at org.apache.felix.scr.impl.BundleComponentActivator.initialEnable(BundleComponentActivator.java:339) [39:org.apache.felix.scr:2.1.2]
        at org.apache.felix.scr.impl.Activator.loadComponents(Activator.java:381) [39:org.apache.felix.scr:2.1.2]
        at org.apache.felix.scr.impl.Activator.access$200(Activator.java:49) [39:org.apache.felix.scr:2.1.2]
        at org.apache.felix.scr.impl.Activator$ScrExtension.start(Activator.java:263) [39:org.apache.felix.scr:2.1.2]
        at org.apache.felix.scr.impl.AbstractExtender.createExtension(AbstractExtender.java:196) [39:org.apache.felix.scr:2.1.2]
        at org.apache.felix.scr.impl.AbstractExtender.modifiedBundle(AbstractExtender.java:169) [39:org.apache.felix.scr:2.1.2]
        at org.apache.felix.scr.impl.AbstractExtender.modifiedBundle(AbstractExtender.java:49) [39:org.apache.felix.scr:2.1.2]
        at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:482) [?:?]
        at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:415) [?:?]
        at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:232) [?:?]
        at org.osgi.util.tracker.BundleTracker$Tracked.bundleChanged(BundleTracker.java:444) [?:?]
        at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:908) [?:?]
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) [?:?]
        at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148) [?:?]
        at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEventPrivileged(EquinoxEventPublisher.java:213) [?:?]
        at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:120) [?:?]
        at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:112) [?:?]
        at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor.publishModuleEvent(EquinoxContainerAdaptor.java:168) [?:?]
        at org.eclipse.osgi.container.Module.publishEvent(Module.java:476) [?:?]
        at org.eclipse.osgi.container.Module.start(Module.java:467) [?:?]
        at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:468) [?:?]
        at org.eclipse.osgi.container.ModuleContainer.start(ModuleContainer.java:750) [?:?]
        at org.eclipse.osgi.container.ModuleContainer.applyDelta(ModuleContainer.java:741) [?:?]
        at org.eclipse.osgi.container.ModuleContainer.resolveAndApply(ModuleContainer.java:511) [?:?]
        at org.eclipse.osgi.container.ModuleContainer.resolve(ModuleContainer.java:457) [?:?]
        at org.eclipse.osgi.container.ModuleContainer.refresh(ModuleContainer.java:1001) [?:?]
        at org.eclipse.osgi.container.ModuleContainer$ContainerWiring.dispatchEvent(ModuleContainer.java:1382) [?:?]
        at org.eclipse.osgi.container.ModuleContainer$ContainerWiring.dispatchEvent(ModuleContainer.java:1) [?:?]
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) [?:?]
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340) [?:?]
```

**Comment by cweitkamp** [comment]
Additional information: I installed a blank system and after Kodi or avmfritz binding via PaperUI.

My plan was to do some research on the following two issues:

1.
```
2018-09-16 13:01:20.878 [ERROR] [nternal.DiscoveryServiceRegistryImpl] - Cannot notify the DiscoveryListener org.eclipse.smarthome.config.discovery.internal.PersistentInbox on Thing discovered event!
java.lang.ClassCastException: org.eclipse.smarthome.config.discovery.internal.DiscoveryResultImpl cannot be cast to org.eclipse.smarthome.config.discovery.DiscoveryResult
	at org.eclipse.smarthome.config.discovery.internal.PersistentInbox.get(PersistentInbox.java:422) ~[96:org.eclipse.smarthome.config.discovery:0.10.0.201809111909]
	at org.eclipse.smarthome.config.discovery.internal.PersistentInbox.notifyListeners(PersistentInbox.java:488) ~[96:org.eclipse.smarthome.config.discovery:0.10.0.201809111909]
	at org.eclipse.smarthome.config.discovery.internal.PersistentInbox.add(PersistentInbox.java:191) ~[96:org.eclipse.smarthome.config.discovery:0.10.0.201809111909]
	at org.eclipse.smarthome.config.discovery.internal.PersistentInbox.thingDiscovered(PersistentInbox.java:345) ~[96:org.eclipse.smarthome.config.discovery:0.10.0.201809111909]
	at org.eclipse.smarthome.config.discovery.internal.DiscoveryServiceRegistryImpl$2.run(DiscoveryServiceRegistryImpl.java:310) ~[96:org.eclipse.smarthome.config.discovery:0.10.0.201809111909]
	at org.eclipse.smarthome.config.discovery.internal.DiscoveryServiceRegistryImpl$2.run(DiscoveryServiceRegistryImpl.java:1) ~[96:org.eclipse.smarthome.config.discovery:0.10.0.201809111909]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at org.eclipse.smarthome.config.discovery.internal.DiscoveryServiceRegistryImpl.thingDiscovered(DiscoveryServiceRegistryImpl.java:307) [96:org.eclipse.smarthome.config.discovery:0.10.0.201809111909]
	at org.eclipse.smarthome.config.discovery.AbstractDiscoveryService.thingDiscovered(AbstractDiscoveryService.java:278) [96:org.eclipse.smarthome.config.discovery:0.10.0.201809111909]
	at org.eclipse.smarthome.config.discovery.upnp.internal.UpnpDiscoveryService.remoteDeviceAdded(UpnpDiscoveryService.java:190) [241:org.eclipse.smarthome.config.discovery.upnp:0.10.0.201809111909]
	at org.jupnp.registry.RemoteItems$1.run(RemoteItems.java:114) [243:org.jupnp:2.4.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
```

2.
```
16:12:50.578 [WARN ] [org.apache.felix.fileinstall         ] - Error while starting bundle: file:/openhab/addons/org.openhab.binding.avmfritz-2.4.0-SNAPSHOT.jar
org.osgi.framework.BundleException: Could not resolve module: org.openhab.binding.avmfritz [215]
  Unresolved requirement: Import-Package: org.eclipse.jdt.annotation; resolution:="optional"
  Unresolved requirement: Import-Package: org.eclipse.smarthome.config.discovery.upnp

	at org.eclipse.osgi.container.Module.start(Module.java:444) [?:?]
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:383) [?:?]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1260) [9:org.apache.felix.fileinstall:3.6.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1233) [9:org.apache.felix.fileinstall:3.6.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startAllBundles(DirectoryWatcher.java:1221) [9:org.apache.felix.fileinstall:3.6.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:515) [9:org.apache.felix.fileinstall:3.6.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365) [9:org.apache.felix.fileinstall:3.6.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:316) [9:org.apache.felix.fileinstall:3.6.4]
```

There is a workaround for the second issue:
> * Install another binding that uses upnp (e.g. the Hue binding)
> * Go into the Karaf console and install the dependency manually: `feature:install esh-io-transport-upnp`

**Comment by lewie** [comment]
Same behavior at OH 2.4.0-SNAPSHOT Build 1364

**Comment by kaikreuzer** [comment]
Wrt the circular dependency: I would claim that the DiscoveryServiceRegistryImpl must not have the dependencies to `Inbox` and `ThingRegistry`. Both could be removed if the `DiscoveryServiceCallback` would be declared in there, which is only used for `ExtendedDiscoveryService`s - this feature seems to be pretty flawed and we should check if we can find a better way to implement it.

**Comment by htreu** [comment]
> this feature seems to be pretty flawed and we should check if we can find a better way to implement it.

The usage of `ExtendedDiscoveryService` is indeed questionable: All occurrences merely check the existence of the discovery result or thing just to ignore the current result. This is actually a feature the persistent inbox already has, so it makes no sense to use the callback provided by the ExtendedDiscoveryService. Another use case I saw in the openhab2-addons repo is to get hold of the actual thing which is already accepted and start a discovery on the thing handler. This is also not intended and a misuse of the feature.

Instead of "resolving" the cyclic dependency like #6223 tried I suggest to completely get rid of the functionality introduced with the ExtendedDiscoveryService.
I will propose a PR which deprecates both interfaces `ExtendedDiscoveryService` and `DiscoveryServiceCallback` and introduces a default implementation for both methods `#getExistingThing` and `#getExistingDiscoveryResult` to always return `null`.

Ping @cdjackson: you are using the callback in the zwave binding. For [this feature](https://github.com/openhab/org.openhab.binding.zwave/blob/master/src/main/java/org/openhab/binding/zwave/discovery/ZWaveDiscoveryService.java#L216) (updating properties) you would have to introduce a binding locale map and cache results there.

**Comment by cdjackson** [comment]
So do I understand that you are removing the ability to check for, and get existing entries from the inbox?

**Comment by cdjackson** [comment]
> All occurrences merely check the existence of the discovery result or thing just to ignore the current result. This is actually a feature the persistent inbox already has, so it makes no sense to use the callback provided by the ExtendedDiscoveryService. 

This is not really correct that it makes no sense. The ZWave and ZigBee bindings use this to avoid having to perform lots of intensive discovery functions if they are already performed, and the thing is already in the inbox or approved. Instead of performing these functions, and then having the inbox ignore it, we check the inbox first to see if the thing already exists, and then don’t perform these intensive tasks.

I am not too keen to loose these functions, and if I understand correctly, you plan to remove them? Instead I think you propose that I need to replicate the inbox functions in the binding to know if the thing has already been added or not? It doesn’t seem very nice if this is the case, and has the potential to get out of sync. eg what if someone clears the inbox - how does the binding know this? 

Alternatively, we just have to perform the discovery every time, but that is likely to cause other problems on large networks.

It might also be worth reviewing https://github.com/eclipse/smarthome/pull/1213 <https://github.com/eclipse/smarthome/pull/1213> which was the original reason this was added. I suspect if we remove this, something will break.

**Comment by htreu** [comment]
yes, thats the plan. PersistentInbox is itself "clever" enough to deal with already existing entries. And as mentioned above, for the partial discovery you should then implement something which is binding local.

**Comment by htreu** [comment]
> perform lots of intensive discovery functions

Do you have a reference to this? I see from #1213 that this might be a problem. Although: when the binding/framework restarts and discovery starts fresh and new, how is "going back" to a raw discovery result a problem when the user didn't notice the old full fledged discovery result anyway?

**Comment by cdjackson** [comment]
No - I don’t have a reference to the intensive loading, but it came up again recently in ZigBee. Where people have large networks, it’s really useful for the binding to know if a thing is already known and included so we don’t have to blindly perform further discovery. On a Pi for example, just adding 20 or so things into the inbox, just to have them ignored was taking 20 or 30 seconds and maxing out the processor when it was otherwise meant to be doing discovery. Some people have networks with upwards of 100 devices - ok, maybe they have a better spec’d machine than a Pi, but if not, it is a big problem.

**Comment by maggu2810** [comment]
I try to understand the discussion correctly, so please let me summarize:

* If a Z*** device is discovered the binding would like to know if the device is already known.
* "Is already known" could be:
  * a thing already exists
  * there exist already a discovery entry in the inbox

Right or wrong?

If it i a common use case, couldn't we provide a `KnownChecker` that provides a method `boolean isKnown(ThingUID thingUID)`. The `KnownChecker` could inpect the inbox entries and the thing registry.
If this is not a common use case, the binding could implement that service itself (and ignore the fact that it should not use that OSGi services like thing registry).

**Comment by kaikreuzer** [comment]
My expectation of discovery + inbox is that this is a passive scanning, which is just figuring out what is available in the network - causing 20-30s full CPU load sounds very wrong to me.
As long as a result is in the inbox, the user didn't express any interest in the device, so the system should not keep itself busy with it. Only once approved (and created as a Thing) should trigger expensive operations like active querying of all kinds of details.

**Comment by cdjackson** [comment]
> If a Z*** device is discovered the binding would like to know if the device is already known.
> "Is already known" could be:
> a thing already exists
> there exist already a discovery entry in the inbox
> Right or wrong?
> 
Yes, this is part of the issue.


The other issue is that once we add a thing, if we re-add it, then it will overwrite everything that is there, so any information already known is lost. This can happen occasionally, and causes confusion to users but is otherwise only a problem to the user. This was the original reason this was added as there was a lot of confusion!


> If this is not a common use case, the binding could implement that service itself (and ignore the fact that it should not use that OSGi services like thing registry).
> 
I have already had PRs rejected and been told that this is definitely not allowed...

**Comment by cdjackson** [comment]
> 
> My expectation of discovery + inbox is that this is a passive scanning,
> 
What does “Passive" mean? I thought that we need to have enough information to provide the thing type? That is NOT passive - in ZigBee and ZWave, this requires active scanning of devices. 

>  causing 20-30s full CPU load sounds very wrong to me.
> 
In the case of ZWave, it also requires the binding to look up a database of 800 devices and this takes time even if we already know all the information about the device!

> As long as a result is in the inbox, the user didn't express any interest in the device, so the system should not keep itself busy with it. Only once approved (and created as a Thing) should trigger expensive operations like active querying of all kinds of details.
> 
As above - in order to get enough information from the device to decide the thing type, active scanning is required.

**Comment by htreu** [comment]
> in ZigBee and ZWave, this requires active scanning of devices

With the ExtendedDiscoveryService gone (deactivated and deprecated) the only disadvantage would be to start scanning all over once the bundle/system restarts. During runtime you are able to cache results in-memory by yourself. 

> look up a database of 800 devices

This should neither be time nor space consuming. I do not consider this to be a problem where the existence of the ExtendedDiscoveryService helps a lot.

**Comment by cdjackson** [comment]
> During runtime you are able to cache results in-memory by yourself.

Agreed, this is possible.

> This should neither be time nor space consuming. I do not consider this to be a problem where the existence of the ExtendedDiscoveryService helps a lot
> 
How can it not be time consuming - it takes time/processing power to search a database right? On slow computers like a Pi, it takes a lot of time to search such a database - yes, it can be done in the background (and it is done in a separate thread in ZWave), but it still maxes out the processor for a (relatively) long time and I don’t immediately see a way around this? Yes, I could likely optimise the search algorithm to improve this, but so far it’s not been required, and even with an optimised search, it’s still going to take a significant amount of time, and systems with large networks will suffer.

I feel that there should be some sort of feedback available to help the discovery system in the binding and not simply assume that this is a one way path.

**Comment by htreu** [comment]
> it takes time/processing power to search a database right?

Of cause, I was exaggerating. What I mean is that any list of `800` is a relatively low number for databases. Even an in-memory map would probably do and would be blazing fast. But as you already mentioned this would be optimising an nothing in the light of this discussion.

> Agreed, this is possible.

Thanks for your agreement. I will close #6223 and author a 2nd commit which implements the suggested solution.

**Comment by htreu** [comment]
> it takes quite a long time on a Pi to search the ZWave database

Again, w/o deeper knowledge of the ZWave protocol, just from a computing pov this sounds like too much for a query in a 800 record database. It seems to be a good candidate for optimisation.

> I was agreeing that I can implement a local cache

We have to sync on this prior to merging #6237. I will leave a note on the PR.

**Comment by kaikreuzer** [comment]
> What does “Passive" mean? I thought that we need to have enough information to provide the thing type? That is NOT passive - in ZigBee and ZWave, this requires active scanning of devices.

Yes, agreed. So let's reformulate it to "minimal effort" :-)

> I feel that there should be some sort of feedback available to help the discovery system in the binding and not simply assume that this is a one way path.

The problem at hand is that this two-way solution introduced a cycling dependency, which must be avoided in the architecture. Looking at it in detail, we also noticed that 95% of the places where `ExtendedDiscoveryService` is used, it is not done for a reason it was introduced for - so this is a clear signal that it's purpose is unclear to most people and we should clean this up.
Z-Wave is really the only remaining user of it. But I agree with you that we must come up with a decent alternative that is acceptable for you and implementable without much effort. Unnecessarily querying the Z-Wave network is to be avoided, I fully agree with you.

So I actually see two parts that you need:
1. Figure out if you have already discovered it, i.e. it is in the Inbox and update it with additional information, in case you found any.
2. Figure out if you have to care at all about it or if it already exists as a Thing and thus is irrelevant for the discovery.

For (1), the suggestion from above would be to keep a local map of previous results in the discovery service, which should make everything possible just as it is today with the sole restriction that it would be lost after a restart - but imho this is something we all could live with.

For (2), you actually do not access to all Things, but only to the Things that your `ZWaveControllerHandler` knows about - and luckily, the `ZWaveDiscoveryService` already has access to the `ZWaveControllerHandler`. Could a simple method be added to the handler that would answer whether a Z-Wave Thing of a given UID already exists or not? It seems to me as if there is no need to route this through the framework at all.

Wdyt?

**Comment by cdjackson** [comment]
> Again, w/o deeper knowledge of the ZWave protocol, just from a computing pov this sounds like too much for a query in a 800 record database. It seems to be a good candidate for optimisation
> 
I will see if I can optimise this. However note that while it’s 800 devices, the database is probably about 5 to 10 times larger as each device has multiple sets of IDs.  All I can say is that on slow computers (I say RPi,but I’m not sure it was a Pi - it was a commercial system) it was taking a long time for a small network. I will have to spend time to optimise this and see where it ends up, but it won’t be for a while unfortunately.

**Comment by cdjackson** [comment]
> So I actually see two parts that you need:
> 
There was also the original reason for adding the method - and that is to update the inbox properties so we don’t have things in the inbox seemingly disappearing. I can probably do something in the binding to reduce this issue, but it can’t be completely resolved without some knowledge of the inbox.

> 
> Could a simple method be added to the handler that would answer whether a Z-Wave Thing of a given UID already exists or not? It seems to me as if there is no need to route this through the framework at all.

Thanks Kai. So you mean add a “getChildThings” method (or whatever name) that provides a list of all things currently known by the bridge? This might solve the majority of the issues.  I will take a look at the ZigBee and ZWave bindings to see if this resolves this issue.

I’m away on holiday at the moment so probably won’t get to look at this until next week anyway.

Thanks.

**Comment by kaikreuzer** [comment]
> so we don’t have things in the inbox seemingly disappearing

This should be covered by using a cache in the discovery service. And having things disappear and rediscovered after a reboot should be acceptable.

> So you mean add a “getChildThings” method (or whatever name) that provides a list of all things currently known by the bridge? 

Yes, exactly.

FTR: I'd like to merge #6237 soon, but I think its impact is ok for the snapshot builds and I just did an OH milestone. We would therefore have about a month time until the next milestone to do the adaptions in the concerned bindings, hope that's ok.

**Comment by wborn** [comment]
Do I correctly see that with the deprecation of the `ExtendedDiscoveryService`, its methods now always return `null`? So any `DiscoveryService` still using these deprecated methods may now have severe performance issues? 

It would sure explain why my Plugwise Zigbee mesh (40+ nodes) is very unstable nowadays because the discovery service is constantly requesting data from each and every (offline) node in the mesh. :disappointed: 

Looks like the `ZWaveDiscoveryService` also didn't got updated yet. So I think you may run into the same issues with large networks @cdjackson?
