### ISSUE TITLE
IDE setup instructions: model generation

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#6221]
I don't know if this has been changed with the latest Xtext bump or if the situation has been the same before.
Some overservations...

**Comment by maggu2810** [comment]
The "Product Version" shown on the IDE setup is "Oxygen".
https://www.eclipse.org/smarthome/documentation/development/ide.html

Should be changed to "Photon".

**Comment by maggu2810** [comment]
After step "8. perform setup tasks" and "9. clean and build" there is stated in 10:
Your workspace should now fully compile.

This does not work for me:

* reinstalled the IDE using "Product Version: Photon"
* after the installation the IDE has been started
* wait after all automatic triggered action has been finished

* help, perform setup tasks: trigger "launch generate all models" only
* => ?? errors (didn't have a look at)

* clean and rebuild all projects
* => 308 errors

* execute "org.eclipse.smarthome.model.codegen" "Generate All Models.launch"
* => 0 errors

* clean and rebuild all projects
* => 0 errors

So, I need to trigger one additional "Generate All Models" execution.

**Comment by kaikreuzer** [comment]
Does this maybe mean that the "launch generate all models" from the setup tasks does not work as expected anymore? Because clearly, the code generation should only be required once.

**Comment by maggu2810** [comment]
After step "8. perform setup tasks" and "9. clean and build" there is stated in 10:
Your workspace should now fully compile.

This does not work for me:

* reinstalled the IDE using "Product Version: Photon"
* after the installation the IDE has been started
* wait after all automatic triggered action has been finished (build finished, ... - have a look at the bottom left field)
=> 463 errors

* execute "org.eclipse.smarthome.model.codegen" "Generate All Models.launch"
=> 104 errors

* clean and rebuild all projects
=> 0 errors

**Comment by maggu2810** [comment]
The only difference that comes in my mind is that while the user triggers "Generate All Models.launch" a rebuild of changed bundles (or their dependencies) is triggered async.
I don't know if this is done for the setup task execution, too.

Or the setup task execution triggered "generate all models" fails (as you asked above)...

**Comment by maggu2810** [comment]
```text
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
0    [main] INFO  text.xtext.generator.XtextGenerator  - Initializing Xtext generator
8    [main] INFO  lipse.emf.mwe.utils.StandaloneSetup  - Adding generated EPackage 'org.eclipse.xtext.common.types.TypesPackage'
421  [main] WARN  lipse.emf.mwe.utils.StandaloneSetup  - Skipping conflicting project org.objectweb.asm at 'archive:file:/home/rathgeb/bin/pkgs/eclipse/esh/ws/.metadata/.plugins/org.eclipse.pde.core/.bundle_pool/plugins/org.objectweb.asm_6.1.1.v20180414-0329.jar!/' and using 'archive:file:/home/rathgeb/bin/pkgs/eclipse/esh/ws/.metadata/.plugins/org.eclipse.pde.core/.bundle_pool/plugins/org.objectweb.asm_5.0.1.v201404251740.jar!/' instead.
434  [main] INFO  lipse.emf.mwe.utils.StandaloneSetup  - Registering project org.eclipse.smarthome.model.rule at 'file:/home/rathgeb/bin/pkgs/eclipse/esh/git/smarthome/bundles/model/org.eclipse.smarthome.model.rule/'
435  [main] INFO  lipse.emf.mwe.utils.StandaloneSetup  - Registering project org.eclipse.smarthome.model.rule.ide at 'file:/home/rathgeb/bin/pkgs/eclipse/esh/git/smarthome/bundles/model/org.eclipse.smarthome.model.rule.ide/'
444  [main] INFO  lipse.emf.mwe.utils.StandaloneSetup  - Using resourceSet registry. The registered Packages will not be registered in the global EPackage.Registry.INSTANCE!
733  [main] INFO  clipse.emf.mwe.utils.GenModelHelper  - Registered GenModel 'http://www.eclipse.org/Xtext/Xbase/XAnnotations' from 'platform:/resource/org.eclipse.xtext.xbase/model/Xbase.genmodel'
737  [main] INFO  clipse.emf.mwe.utils.GenModelHelper  - Registered GenModel 'http://www.eclipse.org/xtext/xbase/Xtype' from 'platform:/resource/org.eclipse.xtext.xbase/model/Xbase.genmodel'
754  [main] INFO  clipse.emf.mwe.utils.GenModelHelper  - Registered GenModel 'http://www.eclipse.org/xtext/xbase/Xbase' from 'platform:/resource/org.eclipse.xtext.xbase/model/Xbase.genmodel'
754  [main] INFO  clipse.emf.mwe.utils.GenModelHelper  - Registered GenModel 'http://www.eclipse.org/xtext/common/JavaVMTypes' from 'platform:/resource/org.eclipse.xtext.common.types/model/JavaVMTypes.genmodel'
755  [main] INFO  clipse.emf.mwe.utils.GenModelHelper  - Registered GenModel 'http://www.eclipse.org/smarthome/model/Script' from 'platform:/resource/org.eclipse.smarthome.model.script/model/generated/Script.genmodel'
988  [main] ERROR xt.generator.XtextGeneratorLanguage  - [XtextLinkingDiagnostic: null:1 Couldn't resolve reference to Grammar 'org.eclipse.smarthome.model.script.Script'., XtextLinkingDiagnostic: null:10 XImportSection cannot be resolved to a rule, XtextLinkingDiagnostic: null:19 JvmTypeReference cannot be resolved to a rule, XtextLinkingDiagnostic: null:19 ValidID cannot be resolved to a rule, XtextLinkingDiagnostic: null:19 ValidID cannot be resolved to a rule, XtextLinkingDiagnostic: null:19 XExpression cannot be resolved to a rule, XtextLinkingDiagnostic: null:23 STRING cannot be resolved to a rule, XtextLinkingDiagnostic: null:23 ID cannot be resolved to a rule, XtextLinkingDiagnostic: null:25 Script cannot be resolved to a rule, XtextLinkingDiagnostic: null:68 STRING cannot be resolved to a rule, XtextLinkingDiagnostic: null:68 ID cannot be resolved to a rule, XtextLinkingDiagnostic: null:73 STRING cannot be resolved to a rule, XtextLinkingDiagnostic: null:93 STRING cannot be resolved to a rule, XtextLinkingDiagnostic: null:97 STRING cannot be resolved to a rule, XtextLinkingDiagnostic: null:101 ID cannot be resolved to a rule, XtextLinkingDiagnostic: null:109 ID cannot be resolved to a rule, XtextLinkingDiagnostic: null:113 Number cannot be resolved to a rule, XtextLinkingDiagnostic: null:117 STRING cannot be resolved to a rule, XtextLinkingDiagnostic: null:125 ID cannot be resolved to a rule, XtextLinkingDiagnostic: null:129 Number cannot be resolved to a rule, XtextLinkingDiagnostic: null:133 STRING cannot be resolved to a rule, XtextLinkingDiagnostic: null:141 ID cannot be resolved to a rule, XtextLinkingDiagnostic: null:145 Number cannot be resolved to a rule, XtextLinkingDiagnostic: null:149 STRING cannot be resolved to a rule]
990  [main] ERROR mf.mwe2.launch.runtime.Mwe2Launcher  - Problems running workflow org.eclipse.smarthome.model.rule.GenerateRules: Problem parsing 'file:/home/rathgeb/bin/pkgs/eclipse/esh/git/smarthome/bundles/model/org.eclipse.smarthome.model.codegen/../org.eclipse.smarthome.model.rule/src/org/eclipse/smarthome/model/rule/Rules.xtext':
XtextLinkingDiagnostic: null:1 Couldn't resolve reference to Grammar 'org.eclipse.smarthome.model.script.Script'.
XtextLinkingDiagnostic: null:10 XImportSection cannot be resolved to a rule
XtextLinkingDiagnostic: null:19 JvmTypeReference cannot be resolved to a rule
XtextLinkingDiagnostic: null:19 ValidID cannot be resolved to a rule
XtextLinkingDiagnostic: null:19 ValidID cannot be resolved to a rule
XtextLinkingDiagnostic: null:19 XExpression cannot be resolved to a rule
XtextLinkingDiagnostic: null:23 STRING cannot be resolved to a rule
XtextLinkingDiagnostic: null:23 ID cannot be resolved to a rule
XtextLinkingDiagnostic: null:25 Script cannot be resolved to a rule
XtextLinkingDiagnostic: null:68 STRING cannot be resolved to a rule
XtextLinkingDiagnostic: null:68 ID cannot be resolved to a rule
XtextLinkingDiagnostic: null:73 STRING cannot be resolved to a rule
XtextLinkingDiagnostic: null:93 STRING cannot be resolved to a rule
XtextLinkingDiagnostic: null:97 STRING cannot be resolved to a rule
XtextLinkingDiagnostic: null:101 ID cannot be resolved to a rule
XtextLinkingDiagnostic: null:109 ID cannot be resolved to a rule
XtextLinkingDiagnostic: null:113 Number cannot be resolved to a rule
XtextLinkingDiagnostic: null:117 STRING cannot be resolved to a rule
XtextLinkingDiagnostic: null:125 ID cannot be resolved to a rule
XtextLinkingDiagnostic: null:129 Number cannot be resolved to a rule
XtextLinkingDiagnostic: null:133 STRING cannot be resolved to a rule
XtextLinkingDiagnostic: null:141 ID cannot be resolved to a rule
XtextLinkingDiagnostic: null:145 Number cannot be resolved to a rule
XtextLinkingDiagnostic: null:149 STRING cannot be resolved to a rule
java.lang.RuntimeException: Problems running workflow org.eclipse.smarthome.model.rule.GenerateRules: Problem parsing 'file:/home/rathgeb/bin/pkgs/eclipse/esh/git/smarthome/bundles/model/org.eclipse.smarthome.model.codegen/../org.eclipse.smarthome.model.rule/src/org/eclipse/smarthome/model/rule/Rules.xtext':
XtextLinkingDiagnostic: null:1 Couldn't resolve reference to Grammar 'org.eclipse.smarthome.model.script.Script'.
XtextLinkingDiagnostic: null:10 XImportSection cannot be resolved to a rule
XtextLinkingDiagnostic: null:19 JvmTypeReference cannot be resolved to a rule
XtextLinkingDiagnostic: null:19 ValidID cannot be resolved to a rule
XtextLinkingDiagnostic: null:19 ValidID cannot be resolved to a rule
XtextLinkingDiagnostic: null:19 XExpression cannot be resolved to a rule
XtextLinkingDiagnostic: null:23 STRING cannot be resolved to a rule
XtextLinkingDiagnostic: null:23 ID cannot be resolved to a rule
XtextLinkingDiagnostic: null:25 Script cannot be resolved to a rule
XtextLinkingDiagnostic: null:68 STRING cannot be resolved to a rule
XtextLinkingDiagnostic: null:68 ID cannot be resolved to a rule
XtextLinkingDiagnostic: null:73 STRING cannot be resolved to a rule
XtextLinkingDiagnostic: null:93 STRING cannot be resolved to a rule
XtextLinkingDiagnostic: null:97 STRING cannot be resolved to a rule
XtextLinkingDiagnostic: null:101 ID cannot be resolved to a rule
XtextLinkingDiagnostic: null:109 ID cannot be resolved to a rule
XtextLinkingDiagnostic: null:113 Number cannot be resolved to a rule
XtextLinkingDiagnostic: null:117 STRING cannot be resolved to a rule
XtextLinkingDiagnostic: null:125 ID cannot be resolved to a rule
XtextLinkingDiagnostic: null:129 Number cannot be resolved to a rule
XtextLinkingDiagnostic: null:133 STRING cannot be resolved to a rule
XtextLinkingDiagnostic: null:141 ID cannot be resolved to a rule
XtextLinkingDiagnostic: null:145 Number cannot be resolved to a rule
XtextLinkingDiagnostic: null:149 STRING cannot be resolved to a rule
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:104)
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:62)
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:52)
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Launcher.run(Mwe2Launcher.java:78)
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Launcher.main(Mwe2Launcher.java:36)
Caused by: java.lang.IllegalStateException: Problem parsing 'file:/home/rathgeb/bin/pkgs/eclipse/esh/git/smarthome/bundles/model/org.eclipse.smarthome.model.codegen/../org.eclipse.smarthome.model.rule/src/org/eclipse/smarthome/model/rule/Rules.xtext':
XtextLinkingDiagnostic: null:1 Couldn't resolve reference to Grammar 'org.eclipse.smarthome.model.script.Script'.
XtextLinkingDiagnostic: null:10 XImportSection cannot be resolved to a rule
XtextLinkingDiagnostic: null:19 JvmTypeReference cannot be resolved to a rule
XtextLinkingDiagnostic: null:19 ValidID cannot be resolved to a rule
XtextLinkingDiagnostic: null:19 ValidID cannot be resolved to a rule
XtextLinkingDiagnostic: null:19 XExpression cannot be resolved to a rule
XtextLinkingDiagnostic: null:23 STRING cannot be resolved to a rule
XtextLinkingDiagnostic: null:23 ID cannot be resolved to a rule
XtextLinkingDiagnostic: null:25 Script cannot be resolved to a rule
XtextLinkingDiagnostic: null:68 STRING cannot be resolved to a rule
XtextLinkingDiagnostic: null:68 ID cannot be resolved to a rule
XtextLinkingDiagnostic: null:73 STRING cannot be resolved to a rule
XtextLinkingDiagnostic: null:93 STRING cannot be resolved to a rule
XtextLinkingDiagnostic: null:97 STRING cannot be resolved to a rule
XtextLinkingDiagnostic: null:101 ID cannot be resolved to a rule
XtextLinkingDiagnostic: null:109 ID cannot be resolved to a rule
XtextLinkingDiagnostic: null:113 Number cannot be resolved to a rule
XtextLinkingDiagnostic: null:117 STRING cannot be resolved to a rule
XtextLinkingDiagnostic: null:125 ID cannot be resolved to a rule
XtextLinkingDiagnostic: null:129 Number cannot be resolved to a rule
XtextLinkingDiagnostic: null:133 STRING cannot be resolved to a rule
XtextLinkingDiagnostic: null:141 ID cannot be resolved to a rule
XtextLinkingDiagnostic: null:145 Number cannot be resolved to a rule
XtextLinkingDiagnostic: null:149 STRING cannot be resolved to a rule
	at org.eclipse.xtext.xtext.generator.XtextGeneratorLanguage.initialize(XtextGeneratorLanguage.java:278)
	at org.eclipse.xtext.xtext.generator.StandardLanguage.initialize(StandardLanguage.java:189)
	at org.eclipse.xtext.xtext.generator.XtextGenerator.initialize(XtextGenerator.java:185)
	at org.eclipse.xtext.xtext.generator.XtextGenerator.checkConfigurationInternal(XtextGenerator.java:139)
	at org.eclipse.emf.mwe.core.lib.AbstractWorkflowComponent2.checkConfiguration(AbstractWorkflowComponent2.java:21)
	at org.eclipse.emf.mwe.core.lib.Mwe2Bridge.preInvoke(Mwe2Bridge.java:65)
	at org.eclipse.emf.mwe.core.lib.AbstractWorkflowComponent.preInvoke(AbstractWorkflowComponent.java:197)
	at org.eclipse.emf.mwe2.runtime.workflow.AbstractCompositeWorkflowComponent.preInvoke(AbstractCompositeWorkflowComponent.java:29)
	at org.eclipse.emf.mwe2.runtime.workflow.Workflow.run(Workflow.java:18)
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:102)
	... 4 more
```

**Comment by maggu2810** [comment]
After step "8. perform setup tasks" and "9. clean and build" there is stated in 10:
Your workspace should now fully compile.

This does not work for me:

* reinstalled the IDE using "Product Version: Photon"
* after the installation the IDE has been started
* wait after all automatic triggered action has been finished (build finished, ... - have a look at the bottom left field)
=> 463 errors

* disable "Build Automatically

* execute "org.eclipse.smarthome.model.codegen" "Generate All Models.launch"

* same error on "Rules" as above

**Comment by maggu2810** [comment]
@kaikreuzer I see two solutions for that problem.
Both involves changes to the Oomph Eclipse SmartHome setup file.

**General**

Both solutions should add a "clean and build all" setup task to the setup file, that eliminates the point (9) of our setup instructions.


**Solution 1**

Remove the "generate all" launch and split it up to its separated 6 launches.
Between every launch trigger a rebuild of the models that has been generated.

**Solution 2**

Remove the "generate all" launch and add a launch configuration that builds the whole ESH tree using the embedded Maven (without tests and checks).
This would also solve the "you need to build the PaperUI once per Maven to get it running" problem.

**Comment by kaikreuzer** [comment]
Yes, the MWE2 workflows run asynchronously.

**Comment by maggu2810** [comment]
Hm, looks different here...
For me the setup instructions are proceeded step by step.

**Comment by maggu2810** [comment]
The following three setup tasks are executed if the previous has been done.
Also the "LaunchTask" of the "generate model" is executed synchronous.

```
    <setupTask
        xsi:type="launching:LaunchTask"
        id="launch.smarthome.1"
        excludedTriggers="STARTUP"
        predecessor="antlr-generator-3.2.0-patch"
        launcher="1 Generate Items Model"/>
    <setupTask
        xsi:type="projects:ProjectsBuildTask"
        excludedTriggers="STARTUP"
        refresh="true"
        clean="true">
      <predicate
          xsi:type="predicates:NamePredicate"
          pattern="org.eclipse.smarthome.model.item.*"/>
    </setupTask>
    <setupTask
        xsi:type="launching:LaunchTask"
        id="launch.smarthome.2"
        excludedTriggers="STARTUP"
        predecessor="antlr-generator-3.2.0-patch"
        launcher="2 Generate Sitemap Model"/>
```

**Comment by htreu** [comment]
Strangely the individual tasks listed in "Generate All Models.launch" are supposed to wait until the task has ended before the next one is launched (synchronisation). And every sub-launch config is supposed to refresh certain projects after completion. On my machine this works nicely for all model projects. I assume the refresh is done asynchronously after the tasks finished and the next tasks is already launched by the main script.

**Comment by maggu2810** [comment]
> Strangely the individual tasks listed in "Generate All Models.launch" are supposed to wait until the task has ended before the next one is launched (synchronisation).

This seems to work as expected.

> And every sub-launch config is supposed to refresh certain projects after completion. On my machine this works nicely for all model projects.

If you disable the automatic build it will fail, too.
The "build async in background" is not a setup task but an Eclipse IDE related feature.
And we cannot rely that the correct project has been already build between sub-launch config x and y.
