### ISSUE TITLE
MQTT embedded broker: NoClassDefFoundError

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#6246]
I tried to install the Karaf MQTT embedded broker feature and got this error:

```text
23:15:31.239 ERROR [features-3-thread-1] bundle org.eclipse.smarthome.io.mqttembeddedbroker:0.10.0.201809202109 (202)[org.eclipse.smarthome.io.mqttembeddedbroker.internal.EmbeddedBrokerServiceImpl(183)] : The activate method has thrown an exception
io.netty.channel.ChannelException: Unable to create Channel from class class io.netty.channel.socket.nio.NioServerSocketChannel
        at io.netty.channel.ReflectiveChannelFactory.newChannel(ReflectiveChannelFactory.java:40) ~[?:?]
        at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:320) ~[?:?]
        at io.netty.bootstrap.AbstractBootstrap.doBind(AbstractBootstrap.java:282) ~[?:?]
        at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:278) ~[?:?]
        at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:260) ~[?:?]
        at io.moquette.server.netty.NettyAcceptor.initFactory(NettyAcceptor.java:195) ~[?:?]
        at io.moquette.server.netty.NettyAcceptor.initializePlainTCPTransport(NettyAcceptor.java:214) ~[?:?]
        at io.moquette.server.netty.NettyAcceptor.initialize(NettyAcceptor.java:156) ~[?:?]
        at io.moquette.server.Server.startServer(Server.java:183) ~[?:?]
        at org.eclipse.smarthome.io.mqttembeddedbroker.internal.EmbeddedBrokerServiceImpl.startEmbeddedServer(EmbeddedBrokerServiceImpl.java:222) ~[?:?]
        at org.eclipse.smarthome.io.mqttembeddedbroker.internal.EmbeddedBrokerServiceImpl.initialize(EmbeddedBrokerServiceImpl.java:126) ~[?:?]
        at org.eclipse.smarthome.io.mqttembeddedbroker.internal.EmbeddedBrokerServiceImpl.activate(EmbeddedBrokerServiceImpl.java:103) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
        at org.apache.felix.scr.impl.inject.methods.BaseMethod.invokeMethod(BaseMethod.java:228) ~[?:?]
        at org.apache.felix.scr.impl.inject.methods.BaseMethod.access$500(BaseMethod.java:41) ~[?:?]
        at org.apache.felix.scr.impl.inject.methods.BaseMethod$Resolved.invoke(BaseMethod.java:664) ~[?:?]
        at org.apache.felix.scr.impl.inject.methods.BaseMethod.invoke(BaseMethod.java:510) ~[?:?]
        at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:317) ~[?:?]
        at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:307) ~[?:?]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.createImplementationObject(SingleComponentManager.java:334) ~[?:?]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.createComponent(SingleComponentManager.java:114) ~[?:?]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:947) ~[?:?]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:919) ~[?:?]
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:741) ~[?:?]
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.enableInternal(AbstractComponentManager.java:661) ~[?:?]
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.enable(AbstractComponentManager.java:427) ~[?:?]
        at org.apache.felix.scr.impl.manager.ConfigurableComponentHolder.enableComponents(ConfigurableComponentHolder.java:665) ~[?:?]
        at org.apache.felix.scr.impl.BundleComponentActivator.initialEnable(BundleComponentActivator.java:339) ~[?:?]
        at org.apache.felix.scr.impl.Activator.loadComponents(Activator.java:381) ~[?:?]
        at org.apache.felix.scr.impl.Activator.access$200(Activator.java:49) ~[?:?]
        at org.apache.felix.scr.impl.Activator$ScrExtension.start(Activator.java:263) ~[?:?]
        at org.apache.felix.scr.impl.AbstractExtender.createExtension(AbstractExtender.java:196) ~[?:?]
        at org.apache.felix.scr.impl.AbstractExtender.modifiedBundle(AbstractExtender.java:169) ~[?:?]
        at org.apache.felix.scr.impl.AbstractExtender.modifiedBundle(AbstractExtender.java:49) ~[?:?]
        at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:482) ~[?:?]
        at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:415) ~[?:?]
        at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:232) ~[?:?]
        at org.osgi.util.tracker.BundleTracker$Tracked.bundleChanged(BundleTracker.java:444) ~[?:?]
        at org.apache.felix.framework.EventDispatcher.invokeBundleListenerCallback(EventDispatcher.java:915) ~[?:?]
        at org.apache.felix.framework.EventDispatcher.fireEventImmediately(EventDispatcher.java:834) ~[?:?]
        at org.apache.felix.framework.EventDispatcher.fireBundleEvent(EventDispatcher.java:516) ~[?:?]
        at org.apache.felix.framework.Felix.fireBundleEvent(Felix.java:4579) ~[?:?]
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2174) ~[?:?]
        at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998) ~[?:?]
        at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:984) ~[?:?]
        at org.apache.karaf.features.internal.service.BundleInstallSupportImpl.startBundle(BundleInstallSupportImpl.java:161) ~[?:?]
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.startBundle(FeaturesServiceImpl.java:1116) ~[?:?]
        at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:997) ~[?:?]
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1025) ~[?:?]
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:964) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:?]
        at io.netty.channel.ReflectiveChannelFactory.newChannel(ReflectiveChannelFactory.java:38) ~[?:?]
        ... 56 more
Caused by: java.lang.NoClassDefFoundError: Could not initialize class io.netty.channel.DefaultChannelId
        at io.netty.channel.AbstractChannel.newId(AbstractChannel.java:111) ~[?:?]
        at io.netty.channel.AbstractChannel.<init>(AbstractChannel.java:83) ~[?:?]
        at io.netty.channel.nio.AbstractNioChannel.<init>(AbstractNioChannel.java:84) ~[?:?]
        at io.netty.channel.nio.AbstractNioMessageChannel.<init>(AbstractNioMessageChannel.java:42) ~[?:?]
        at io.netty.channel.socket.nio.NioServerSocketChannel.<init>(NioServerSocketChannel.java:86) ~[?:?]
        at io.netty.channel.socket.nio.NioServerSocketChannel.<init>(NioServerSocketChannel.java:72) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:?]
        at io.netty.channel.ReflectiveChannelFactory.newChannel(ReflectiveChannelFactory.java:38) ~[?:?]
        ... 56 more
```

**Comment by maggu2810** [comment]
The "Eclipse SmartHome Embedded MQTT broker" bundles the "netty-all-4.1.19" artifact.
Why at all?

The site "https://netty.io/wiki/new-and-noteworthy-in-4.0.html"  states:
> All artifacts (except for netty-all.jar) are now OSGi bundles and can be used in your favorite OSGi container.

So, why not adding the `Import-Package` entries for packages that are used by moquette-broker from Netty and drop the bundled one.
If other bundles in the OSGi container needs Netty bundles, we don't need to add the overhead of RAM and persistent memory to add them twice.

**Comment by kaikreuzer** [comment]
@davidgraeff Can you comment?

**Comment by davidgraeff** [comment]
When I developed this feature, Netty was not part of the target platform and the reviewers at that time agreed on bundling it.
I would highly favor the solution of not bundling Netty if possible.

**Comment by maggu2810** [comment]
The "unbundle Netty" task shouldn't be complicated:

* update target platform
  * create a CQ for the necessary separate bundles
  * add the artifacts to our 3rd party p2 repo pom and rebuild that p2 repo
* update Karaf feature

I assume (hope) that should solve the problem.
if we agree on that, I can give it a try.


But does the Embedded MQTT broker as it is works for someone?

**Comment by htreu** [comment]
> does the Embedded MQTT broker as it is works for someone?

Yes, it did for me when I reviewed #5880. The broker started right away, I could add the system-broker bridge and also add MQTT things from the proposed binding.
There where some small hick ups at first, I had to edit the Embedded Broker service once in Paper UI to make the bridge come online.

**Comment by kaikreuzer** [comment]
> create a CQ for the necessary separate bundles

This can be quite some work as there are many small bundles. For the netty-all, there was an existing CQ which we could simply piggyback. Makes future upgrades simpler as well.

> If other bundles in the OSGi container needs Netty bundles

So you would want to make it available to ESH bundles in general? So far, it is a bit "hidden", so that nobody "accidentially" starts using it, just because it is in the TP. Netty is quite huge, so imho it should not be encouraged to be used here.

I agree that having separate bundles is the cleaner OSGi way, so I am not against it. Just want to ask for the tradeoff of our benefit vs. the involved (long-term) efforts.

**Comment by maggu2810** [comment]
I can't judge how much work it's done to get the CQs approved. The netty-all artifact is AFAIK just a compound of the separate bundles. If "all" has already been approved I assume that from a legal point also the separate ones shouldn't be a problem.

The changes has been already done in a branch of mine.
See e.g. https://github.com/maggu2810/smarthome/commit/f541b41fd919d8fef200347e38cea2f05f8c548d
There are 10 artifacts that should be used instead of the "all".

I agree that as long as the Netty packages are not exported by this bundle and so hidden for other usage it could stay as it is. Perhaps it would also make "more sense" as we don't get any collision with other ones.

IMHO it is still the cleaner OSGi way (as you comment yourself). If a product uses another (non ESH) bundle that imports the Netty packages that product needs to add the Netty bundles to its runtime. This could result into a big runtime overhead as the same bytecode needs to be present twice.

There's no need to hurry, I could keep the changes in a branch and we could sometime think about...

For the moment we should just ensure that the MQTT embedded broker works as expected without any "hick ups" or exceptions.
Currently I don't understand that exception and I wonder why that ones has not been seen by others.

Just FYI: The exceptions are gone by my changes that contains:
* remove the netty-all jar from MQTT embedded broker
* add Import-Package statements
* add separate Netty bundles to the OSGi container

**Comment by kaikreuzer** [comment]
> I can't judge how much work it's done to get the CQs approved.

I can't either, but entering 10 CQs alone does not sound very thrilling...

> If "all" has already been approved I assume that from a legal point also the separate ones shouldn't be a problem.

Right, for the IP team it should not mean much effort and thus there isn't much risk that those CQs take long or would be rejected.

> There's no need to hurry, I could keep the changes in a branch and we could sometime think about...

I leave it to you - if you'd want to undergo the effort, feel free and I'll support, but I won't start any activity myself due to the low prio.

> For the moment we should just ensure that the MQTT embedded broker works as expected without any "hick ups" or exceptions.

Yes, that's what we'll have to investigate and fix indeed.
I just tried it out on the latest openHAB distro and it starts up alright:
```
10:47:27.423 [INFO ] [o.transport.mqtt.MqttBrokerConnection] - Starting MQTT broker connection to '127.0.0.1' with clientid embedded-mqtt-broker and file store '/Users/kai/Downloads/oh/userdata/mqtt/127.0.0.1'
10:47:27.433 [INFO ] [smarthome.event.ExtensionEvent       ] - Extension 'misc-mqttbroker' has been installed.
```
So I'm afraid I cannot reproduce & analyse...

**Comment by maggu2810** [comment]
I used a simple Karaf distribution that installs `esh-base` only (https://github.com/maggu2810/smarthome-packaging-sample-karaf).

After building the current ESH master (0.10.0-SNAPSHOT) on my machine, I have built that sample packaging and started it.

```
mvn clean install
target/assembly/bin/karaf
```

After that I called

```
feature:install esh-io-mqttembeddedbroker
```

and inspected the log:

```
log:tail
```
