### ISSUE TITLE
[Homematic] Lots of ClassCastException after installation of binding and first scan

### ISSUE THREAD

**Issue by MHerbst** [eclipse/smarthome#6293]
**Environment**

- VM with Ubuntu 18.04
- Zulu openJDK version 1.8.0_181
- openHAB version 2.4 M4

I have performed a fresh install of openHAB 2.4 M4 on a new VM. The I installed the HomeMatic binding. First problem was that the CCU was not automatically detected and I had to configure it manually. After the bridge went Online the binding tried to scan for things but this fails with lots of ClassCastExceptions:

```
2018-09-30 12:07:59.888 [INFO ] [ommunicator.AbstractHomematicGateway] - HmGatewayInfo[id=CCU,type=CCU2,firmware=3.37.8.20180929,address=PEQ0626674,wired=false,hmip=true,cuxd=false,group=true]
2018-09-30 12:08:10.160 [ERROR] [nternal.DiscoveryServiceRegistryImpl] - Cannot notify the DiscoveryListener org.eclipse.smarthome.config.discovery.internal.PersistentInbox on Thing discovered event!
java.lang.ClassCastException: org.eclipse.smarthome.config.discovery.internal.DiscoveryResultImpl cannot be cast to org.eclipse.smarthome.config.discovery.DiscoveryResult
	at org.eclipse.smarthome.config.discovery.internal.PersistentInbox.get(PersistentInbox.java:422) ~[?:?]
	at org.eclipse.smarthome.config.discovery.internal.PersistentInbox.notifyListeners(PersistentInbox.java:488) ~[?:?]
	at org.eclipse.smarthome.config.discovery.internal.PersistentInbox.add(PersistentInbox.java:191) ~[?:?]
	at org.eclipse.smarthome.config.discovery.internal.PersistentInbox.thingDiscovered(PersistentInbox.java:345) ~[?:?]
	at org.eclipse.smarthome.config.discovery.internal.DiscoveryServiceRegistryImpl$2.run(DiscoveryServiceRegistryImpl.java:310) ~[?:?]
	at org.eclipse.smarthome.config.discovery.internal.DiscoveryServiceRegistryImpl$2.run(DiscoveryServiceRegistryImpl.java:1) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at org.eclipse.smarthome.config.discovery.internal.DiscoveryServiceRegistryImpl.thingDiscovered(DiscoveryServiceRegistryImpl.java:307) ~[?:?]
	at org.eclipse.smarthome.config.discovery.AbstractDiscoveryService.thingDiscovered(AbstractDiscoveryService.java:278) ~[?:?]
	at org.eclipse.smarthome.binding.homematic.internal.discovery.HomematicDeviceDiscoveryService.deviceDiscovered(HomematicDeviceDiscoveryService.java:229) ~[?:?]
	at org.eclipse.smarthome.binding.homematic.handler.HomematicBridgeHandler.onDeviceLoaded(HomematicBridgeHandler.java:329) ~[?:?]
	at org.eclipse.smarthome.binding.homematic.internal.communicator.AbstractHomematicGateway.loadAllDeviceMetadata(AbstractHomematicGateway.java:412) ~[?:?]
	at org.eclipse.smarthome.binding.homematic.internal.discovery.HomematicDeviceDiscoveryService.lambda$0(HomematicDeviceDiscoveryService.java:192) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
```

Maybe this problem is related to #6192, but the stack trace is different here

**Comment by kaikreuzer** [comment]
Looks very much like https://github.com/eclipse/smarthome/issues/6266, which I'd hope has been fixed by https://github.com/eclipse/smarthome/pull/6237, which is NOT part of openHAB 2.4.0.M4, but only of the most recent snapshots. So unless you confirm this issue on the current snapshot as well, allow me to close it.

**Comment by mstormi** [comment]
Running #1379, I still keep getting this on discovery.
Is that any of the issue menioned here (believed to be fixed) or a new one ?


```2018-10-03 23:57:46.893 [ERROR] [nternal.DiscoveryServiceRegistryImpl] - Cannot notify the DiscoveryListener 'org.eclipse.smarthome.config.discovery.internal.PersistentInbox' on all things removed event!
java.lang.ClassCastException: org.eclipse.smarthome.config.discovery.internal.DiscoveryResultImpl cannot be cast to org.eclipse.smarthome.config.discovery.DiscoveryResult
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:?]
        at org.eclipse.smarthome.config.discovery.internal.PersistentInbox.getAll(PersistentInbox.java:295) ~[97:org.eclipse.smarthome.config.discovery:0.10.0.201809271800]
        at org.eclipse.smarthome.config.discovery.internal.PersistentInbox.removeOlderResults(PersistentInbox.java:359) ~[97:org.eclipse.smarthome.config.discovery:0.10.0.201809271800]
        at org.eclipse.smarthome.config.discovery.internal.DiscoveryServiceRegistryImpl$3.run(DiscoveryServiceRegistryImpl.java:315) ~[97:org.eclipse.smarthome.config.discovery:0.10.0.201809271800]
        at org.eclipse.smarthome.config.discovery.internal.DiscoveryServiceRegistryImpl$3.run(DiscoveryServiceRegistryImpl.java:1) ~[97:org.eclipse.smarthome.config.discovery:0.10.0.201809271800]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at org.eclipse.smarthome.config.discovery.internal.DiscoveryServiceRegistryImpl.removeOlderResults(DiscoveryServiceRegistryImpl.java:312) [97:org.eclipse.smarthome.config.discovery:0.10.0.201809271800]
        at org.eclipse.smarthome.config.discovery.AbstractDiscoveryService.removeOlderResults(AbstractDiscoveryService.java:352) [97:org.eclipse.smarthome.config.discovery:0.10.0.201809271800]
        at org.eclipse.smarthome.config.discovery.AbstractDiscoveryService.removeOlderResults(AbstractDiscoveryService.java:317) [97:org.eclipse.smarthome.config.discovery:0.10.0.201809271800]
        at org.openhab.binding.gpstracker.internal.discovery.TrackerDiscoveryService.stopScan(TrackerDiscoveryService.java:123) [221:org.openhab.binding.gpstracker:2.4.0.201810031340]
        at org.eclipse.smarthome.config.discovery.AbstractDiscoveryService.startScan(AbstractDiscoveryService.java:182) [97:org.eclipse.smarthome.config.discovery:0.10.0.201809271800]
        at org.eclipse.smarthome.config.discovery.internal.DiscoveryServiceRegistryImpl.startScan(DiscoveryServiceRegistryImpl.java:385) [97:org.eclipse.smarthome.config.discovery:0.10.0.201809271800]
        at org.eclipse.smarthome.config.discovery.internal.DiscoveryServiceRegistryImpl.startScans(DiscoveryServiceRegistryImpl.java:370) [97:org.eclipse.smarthome.config.discovery:0.10.0.201809271800]
        at org.eclipse.smarthome.config.discovery.internal.DiscoveryServiceRegistryImpl.startScan(DiscoveryServiceRegistryImpl.java:218) [97:org.eclipse.smarthome.config.discovery:0.10.0.201809271800]
        at org.eclipse.smarthome.io.rest.core.internal.discovery.DiscoveryResource.scan(DiscoveryResource.java:97) [117:org.eclipse.smarthome.io.rest.core:0.10.0.201809271800]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]```

**Comment by kaikreuzer** [comment]
@mstormi Already reported as https://github.com/eclipse/smarthome/issues/6295 that it still isn't fixed.
