### ISSUE TITLE
Rename MQTTMultiBrokerTopicDiscoveryTest to MQTTTopicDiscoveryServiceTest

### ISSUE THREAD

**Issue by htreu** [eclipse/smarthome#6380]
@davidgraeff please also rename the tests according to our discussion here https://github.com/eclipse/smarthome/pull/6373#issuecomment-430599635. Thanks.

**Comment by davidgraeff** [comment]
A reminder to myself: I should also check your reported failed test.
```
handlerInitializeAfterSubscribe(org.eclipse.smarthome.binding.mqtt.internal.MQTTMultiBrokerTopicDiscoveryTest)  Time elapsed: 0.007 sec
Results :
Failed tests: 
  BrokerHandlerTest.handlerInit:110 
callback.statusUpdated(
    thing,
    <Capturing argument>
);
Wanted 3 times:
-> at org.eclipse.smarthome.binding.mqtt.handler.BrokerHandlerTest.handlerInit(BrokerHandlerTest.java:110)
But was 4 times. Undesired invocation:
-> at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.updateStatus(BaseThingHandler.java:399)
```

**Comment by kaikreuzer** [comment]
> Could you please assign this issue to me, so that I don't forget? :)

Unfortunately not - we can only assign issues to ESH committers.
But we will keep reminding you!

**Comment by davidgraeff** [comment]
@htreu Fixed with the latest PR
