### ISSUE TITLE
UpnpDiscoveryService lock acquire fails

### ISSUE THREAD

**Issue by davidgraeff** [eclipse/smarthome#6422]
I get the following error each time I start my ESH instance (reproducible):

```
10:56:39.681 ERROR o.e.s.c.d.u.i.UpnpDiscoveryService[:245] - Could not retstart UPnP network components.
org.jupnp.transport.RouterException: Router wasn't available exclusively after waiting 6000ms, lock failed: WriteLock
	at org.jupnp.transport.RouterImpl.lock(RouterImpl.java:481)
	at org.jupnp.transport.RouterImpl.lock(RouterImpl.java:494)
	at org.jupnp.transport.RouterImpl.disable(RouterImpl.java:151)
	at org.eclipse.smarthome.config.discovery.upnp.internal.UpnpDiscoveryService.lambda$0(UpnpDiscoveryService.java:240)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by kaikreuzer** [comment]
It should only get in there if something about your network interfaces CHANGES. So is this really reproducible on a simple startup? Can you reproduce it in the IDE, so that you could debug, how it gets there?
In any case, restarting the UPnP framework should work, but this might probably rather be a bug for https://github.com/jupnp/jupnp/...

**Comment by davidgraeff** [comment]
I have this message in my IDE as well. I was hoping that the `UpnpDiscoveryService` maintainer could have an idea. I'll have a quick look as well.
The network is not changing during start up and while running ESH.
