### ISSUE TITLE
NPE in ThingManagerImpl during shutdown

### ISSUE THREAD

**Issue by mhilbush** [eclipse/smarthome#6466]
I see several of these during shutdown. Looks like one for each Thing.

I'm on OH build 1413, which includes the latest ESH stable. Likely due to this recent change?
https://github.com/eclipse/smarthome/commit/a0e178825541c2ba4b0424cc554fefcf5e4bac35#diff-5523918cb0a734afd589ef6edfeeced8

```
2018-11-05 16:33:34.151 [DEBUG] [core.thing.internal.ThingManagerImpl] - Thing handler factory 'AstroHandlerFactory' removed
2018-11-05 16:33:34.151 [DEBUG] [core.thing.internal.ThingManagerImpl] - Calling dispose handler for thing 'astro:sun:local' at 'org.eclipse.smarthome.binding.astro.handler.SunHandler@63667020'.
2018-11-05 16:33:34.153 [DEBUG] [core.thing.internal.ThingManagerImpl] - Calling unregisterHandler handler for thing 'astro:sun:local' at 'org.eclipse.smarthome.binding.astro.internal.AstroHandlerFactory@3c796653'.
2018-11-05 16:33:34.154 [ERROR] [nal.common.AbstractInvocationHandler] - An error occurred while calling method 'Runnable.run()' on 'org.eclipse.smarthome.core.thing.internal.ThingManagerImpl$$Lambda$404/214148930@1bfe81ed': null
java.lang.NullPointerException: null
	at org.eclipse.smarthome.core.thing.internal.ThingManagerImpl.lambda$5(ThingManagerImpl.java:828) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
	at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) [101:org.eclipse.smarthome.core:0.10.0.201811051614]
	at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:53) [101:org.eclipse.smarthome.core:0.10.0.201811051614]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
```

**Comment by kaikreuzer** [comment]
Might be related - @maggu2810, your take?

**Comment by maggu2810** [comment]
It seems to be my fault :cry: 
Will propose a fix
