### ISSUE TITLE
[digitalSTROM] NPE thrown in DeviceHandler

### ISSUE THREAD

**Issue by hmerk** [eclipse/smarthome#6488]
I am seeing the following NPE in my logs since a couple of weeks:
`2018-11-09 00:20:36.437 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 
java.lang.NullPointerException: null
	at org.eclipse.smarthome.binding.digitalstrom.handler.DeviceHandler.onDeviceConfigChanged(DeviceHandler.java:948) ~[?:?]
	at org.eclipse.smarthome.binding.digitalstrom.internal.lib.structure.devices.impl.DeviceImpl.informListenerAboutConfigChange(DeviceImpl.java:1687) ~[?:?]
	at org.eclipse.smarthome.binding.digitalstrom.internal.lib.structure.devices.impl.DeviceImpl.setMeterDSID(DeviceImpl.java:268) ~[?:?]
	at org.eclipse.smarthome.binding.digitalstrom.internal.lib.manager.impl.DeviceStatusManagerImpl.checkDeviceConfig(DeviceStatusManagerImpl.java:634) ~[?:?]
	at org.eclipse.smarthome.binding.digitalstrom.internal.lib.manager.impl.DeviceStatusManagerImpl.access$8(DeviceStatusManagerImpl.java:620) ~[?:?]
	at org.eclipse.smarthome.binding.digitalstrom.internal.lib.manager.impl.DeviceStatusManagerImpl$PollingRunnable.run(DeviceStatusManagerImpl.java:282) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
`

Looking at the code, it seems that in onDeviceConfigChanged(), getting the DSMeterID fails in line 948

`super.updateProperty(DEVICE_METER_ID, device.getMeterDSID().getValue());`

and then throws an NPE and all devices go OFFLINE.
@MichaelOchel can you check this, cause it makes the Binding unusable.

**Comment by hmerk** [comment]
Hmmm, strange, I removed Karaf Webconsole and did not see this NPE last night. I will watch this for a few days and update on this issue.

**Comment by hmerk** [comment]
Indeed, removing Karaf Webconsole solved the problem, so I close this issue.

**Comment by hmerk** [comment]
Hmm, issue came back after 2 days and still,persists.
@MichaelOchel could you please have a look.
