### ISSUE TITLE
[test failures] OneWire TemperatureSensorThingHandlerTest.testRefresh

### ISSUE THREAD

**Issue by wborn** [eclipse/smarthome#6517]
Looks like besides #6070 there is another unstable OneWire test, see Travis https://api.travis-ci.org/v3/job/454858483/log.txt:

```
Running org.eclipse.smarthome.binding.onewire.internal.TemperatureSensorThingHandlerTest
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.031 sec <<< FAILURE! - in org.eclipse.smarthome.binding.onewire.internal.TemperatureSensorThingHandlerTest
testInitializationEndsWithUnknown(org.eclipse.smarthome.binding.onewire.internal.TemperatureSensorThingHandlerTest)  Time elapsed: 0.012 sec
testRefresh(org.eclipse.smarthome.binding.onewire.internal.TemperatureSensorThingHandlerTest)  Time elapsed: 0.015 sec  <<< FAILURE!
org.mockito.exceptions.verification.VerificationInOrderFailure: 

Verification in order failure
Wanted but not invoked:
bridgeHandler.readDecimalType(
    "00.000000000000",
    <any>
);
-> at org.eclipse.smarthome.binding.onewire.internal.TemperatureSensorThingHandlerTest.testRefresh(TemperatureSensorThingHandlerTest.java:90)
Wanted anywhere AFTER following interaction:
bridgeHandler.checkPresence(
    "00.000000000000"
);
-> at org.eclipse.smarthome.binding.onewire.internal.device.AbstractOwDevice.checkPresence(AbstractOwDevice.java:109)

	at org.eclipse.smarthome.binding.onewire.internal.TemperatureSensorThingHandlerTest.testRefresh(TemperatureSensorThingHandlerTest.java:90)


Results :

Failed tests: 
  TemperatureSensorThingHandlerTest.testRefresh:90 
Verification in order failure
Wanted but not invoked:
bridgeHandler.readDecimalType(
    "00.000000000000",
    <any>
);
-> at org.eclipse.smarthome.binding.onewire.internal.TemperatureSensorThingHandlerTest.testRefresh(TemperatureSensorThingHandlerTest.java:90)
Wanted anywhere AFTER following interaction:
bridgeHandler.checkPresence(
    "00.000000000000"
);
-> at org.eclipse.smarthome.binding.onewire.internal.device.AbstractOwDevice.checkPresence(AbstractOwDevice.java:109)

Tests run: 54, Failures: 1, Errors: 0, Skipped: 0
```

**Comment by wborn** [comment]
Can you have a look at this @J-N-K ?

The same tests failed again today while Travis was building https://github.com/eclipse/smarthome/pull/6650:

https://api.travis-ci.org/v3/job/465340184/log.txt:

```
dewPointTest(org.eclipse.smarthome.binding.onewire.internal.UtilTest)  Time elapsed: 0.001 sec
decimalTypeToBooleanListTest(org.eclipse.smarthome.binding.onewire.internal.UtilTest)  Time elapsed: 0.003 sec
convertAbsoluteHumidityTest(org.eclipse.smarthome.binding.onewire.internal.UtilTest)  Time elapsed: 0.001 sec
Running org.eclipse.smarthome.binding.onewire.internal.TemperatureSensorThingHandlerTest
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.063 sec <<< FAILURE! - in org.eclipse.smarthome.binding.onewire.internal.TemperatureSensorThingHandlerTest
testInitializationEndsWithUnknown(org.eclipse.smarthome.binding.onewire.internal.TemperatureSensorThingHandlerTest)  Time elapsed: 0.055 sec
testRefresh(org.eclipse.smarthome.binding.onewire.internal.TemperatureSensorThingHandlerTest)  Time elapsed: 0.005 sec  <<< FAILURE!
org.mockito.exceptions.verification.VerificationInOrderFailure: 

Verification in order failure
Wanted but not invoked:
bridgeHandler.readDecimalType(
    "00.000000000000",
    <any>
);
-> at org.eclipse.smarthome.binding.onewire.internal.TemperatureSensorThingHandlerTest.testRefresh(TemperatureSensorThingHandlerTest.java:90)
Wanted anywhere AFTER following interaction:
bridgeHandler.checkPresence(
    "00.000000000000"
);
-> at org.eclipse.smarthome.binding.onewire.internal.device.AbstractOwDevice.checkPresence(AbstractOwDevice.java:109)

	at org.eclipse.smarthome.binding.onewire.internal.TemperatureSensorThingHandlerTest.testRefresh(TemperatureSensorThingHandlerTest.java:90)


Results :

Failed tests: 
  TemperatureSensorThingHandlerTest.testRefresh:90 
Verification in order failure
Wanted but not invoked:
bridgeHandler.readDecimalType(
    "00.000000000000",
    <any>
);
-> at org.eclipse.smarthome.binding.onewire.internal.TemperatureSensorThingHandlerTest.testRefresh(TemperatureSensorThingHandlerTest.java:90)
Wanted anywhere AFTER following interaction:
bridgeHandler.checkPresence(
    "00.000000000000"
);
-> at org.eclipse.smarthome.binding.onewire.internal.device.AbstractOwDevice.checkPresence(AbstractOwDevice.java:109)


Tests run: 54, Failures: 1, Errors: 0, Skipped: 0
```

**Comment by J-N-K** [comment]
I‘ll have a look. But I must admit that I was never able to reproduce that one.
