### ISSUE TITLE
blukii temperature is incorrect (openHAB2)

### ISSUE THREAD

**Issue by Jak-o** [eclipse/smarthome#6532]
Hello,
I’m using the blukii binding for my “blukii Sensor Beacon Go 500”. Everythings works fine, BUT…
the temperature values are very confusing!

In plus degrees the values are shown correct:
17 = 17
16 = 16
15 = 15
…

but at zero degrees down the values change to different values like:
-1 = 255 
-2 = 254
-3 = 252
…

At first time I manage it with a MAP but is that the wanted and correct implementation of the blukii binding???

sensoren.items
`Number:Temperature      Aussen_temp        "Temperatur [%.0f %unit%]"       (Sensoren, Aussen)      { channel="bluetooth:blukii_beacon:hci0:xxx:temperature"}`

home.sitemap
`Text item=Aussen_temp icon="temperature"`

event.log

> 2018-11-17 07:29:09.379 [.ItemChannelLinkAddedEvent] - Link 'Aussen_temp-bluetooth:blukii_beacon:hci0:xxx:temperature' has been added.
> 2018-11-17 09:41:24.411 [vent.ItemStateChangedEvent] - Aussen_temp changed from 1.0 ℃ to 2.0 ℃
> 2018-11-17 10:12:19.438 [vent.ItemStateChangedEvent] - Aussen_temp changed from 2.0 ℃ to 3.0 ℃
> 2018-11-17 11:03:30.452 [vent.ItemStateChangedEvent] - Aussen_temp changed from 3.0 ℃ to 4.0 ℃
> 2018-11-17 12:03:32.528 [vent.ItemStateChangedEvent] - Aussen_temp changed from 4.0 ℃ to 5.0 ℃
> 2018-11-17 15:28:16.948 [vent.ItemStateChangedEvent] - Aussen_temp changed from 5.0 ℃ to 4.0 ℃
> 2018-11-17 16:03:17.009 [vent.ItemStateChangedEvent] - Aussen_temp changed from 4.0 ℃ to 3.0 ℃
> 2018-11-17 16:31:45.313 [vent.ItemStateChangedEvent] - Aussen_temp changed from 3.0 ℃ to 2.0 ℃
> 2018-11-17 17:18:56.946 [vent.ItemStateChangedEvent] - Aussen_temp changed from 2.0 ℃ to 1.0 ℃
> 2018-11-17 17:19:33.999 [vent.ItemStateChangedEvent] - Aussen_temp changed from 1.0 ℃ to 2.0 ℃
> 2018-11-17 17:19:47.168 [vent.ItemStateChangedEvent] - Aussen_temp changed from 2.0 ℃ to 1.0 ℃
> 2018-11-17 17:20:01.465 [vent.ItemStateChangedEvent] - Aussen_temp changed from 1.0 ℃ to 2.0 ℃
> 2018-11-17 17:20:33.529 [vent.ItemStateChangedEvent] - Aussen_temp changed from 2.0 ℃ to 1.0 ℃
> 2018-11-17 17:25:38.956 [vent.ItemStateChangedEvent] - Aussen_temp changed from 1.0 ℃ to 2.0 ℃
> 2018-11-17 17:26:13.984 [vent.ItemStateChangedEvent] - Aussen_temp changed from 2.0 ℃ to 1.0 ℃
> 2018-11-17 18:23:46.049 [vent.ItemStateChangedEvent] - Aussen_temp changed from 1.0 ℃ to 0.0 ℃
> 2018-11-17 19:16:34.956 [vent.ItemStateChangedEvent] - Aussen_temp changed from 0.0 ℃ to 255.0 ℃
> 2018-11-17 19:16:54.386 [vent.ItemStateChangedEvent] - Aussen_temp changed from 255.0 ℃ to 0.0 ℃
> 2018-11-17 19:17:24.256 [vent.ItemStateChangedEvent] - Aussen_temp changed from 0.0 ℃ to 255.0 ℃
> 2018-11-17 19:18:31.578 [vent.ItemStateChangedEvent] - Aussen_temp changed from 255.0 ℃ to 0.0 ℃
> 2018-11-17 19:31:03.907 [vent.ItemStateChangedEvent] - Aussen_temp changed from 0.0 ℃ to 255.0 ℃
> 2018-11-17 19:31:17.290 [vent.ItemStateChangedEvent] - Aussen_temp changed from 255.0 ℃ to 0.0 ℃
> 2018-11-17 19:31:51.901 [vent.ItemStateChangedEvent] - Aussen_temp changed from 0.0 ℃ to 255.0 ℃
> 2018-11-17 20:14:59.906 [vent.ItemStateChangedEvent] - Aussen_temp changed from 255.0 ℃ to 254.0 ℃
> 2018-11-17 21:16:59.840 [vent.ItemStateChangedEvent] - Aussen_temp changed from 254.0 ℃ to 253.0 ℃
> 2018-11-17 22:24:46.935 [vent.ItemStateChangedEvent] - Aussen_temp changed from 253.0 ℃ to 252.0 ℃
> 2018-11-17 22:49:05.530 [vent.ItemStateChangedEvent] - Aussen_temp changed from 252.0 ℃ to 253.0 ℃
> 2018-11-17 23:49:15.837 [vent.ItemStateChangedEvent] - Aussen_temp changed from 253.0 ℃ to 252.0 ℃
> 2018-11-17 23:52:12.658 [vent.ItemStateChangedEvent] - Aussen_temp changed from 252.0 ℃ to 253.0 ℃
> 2018-11-17 23:52:29.025 [vent.ItemStateChangedEvent] - Aussen_temp changed from 253.0 ℃ to 252.0 ℃
> 2018-11-18 00:28:30.427 [vent.ItemStateChangedEvent] - Aussen_temp changed from 252.0 ℃ to 251.0 ℃
> 2018-11-18 02:42:21.798 [vent.ItemStateChangedEvent] - Aussen_temp changed from 251.0 ℃ to 250.0 ℃
> 2018-11-18 03:52:31.128 [vent.ItemStateChangedEvent] - Aussen_temp changed from 250.0 ℃ to 249.0 ℃
> 2018-11-18 07:05:53.735 [vent.ItemStateChangedEvent] - Aussen_temp changed from 249.0 ℃ to 250.0 ℃
> 2018-11-18 07:08:46.108 [vent.ItemStateChangedEvent] - Aussen_temp changed from 250.0 ℃ to 249.0 ℃
> 2018-11-18 07:10:09.509 [vent.ItemStateChangedEvent] - Aussen_temp changed from 249.0 ℃ to 250.0 ℃
> 2018-11-18 07:32:13.045 [vent.ItemStateChangedEvent] - Aussen_temp changed from 250.0 ℃ to 249.0 ℃
> 2018-11-18 08:09:19.711 [vent.ItemStateChangedEvent] - Aussen_temp changed from 249.0 ℃ to 250.0 ℃
> 2018-11-18 08:22:39.794 [vent.ItemStateChangedEvent] - Aussen_temp changed from 250.0 ℃ to 251.0 ℃
> 2018-11-18 08:43:08.596 [vent.ItemStateChangedEvent] - Aussen_temp changed from 251.0 ℃ to 252.0 ℃
> 2018-11-18 09:04:45.432 [vent.ItemStateChangedEvent] - Aussen_temp changed from 252.0 ℃ to 253.0 ℃
> 2018-11-18 09:29:19.330 [vent.ItemStateChangedEvent] - Aussen_temp changed from 253.0 ℃ to 254.0 ℃
> 2018-11-18 09:49:22.264 [vent.ItemStateChangedEvent] - Aussen_temp changed from 254.0 ℃ to 255.0 ℃
> 2018-11-18 10:12:48.492 [vent.ItemStateChangedEvent] - Aussen_temp changed from 255.0 ℃ to 0.0 ℃

**Comment by maggu2810** [comment]
Please enable the debug logging for package `org.eclipse.smarthome.binding.bluetooth.blukii.handler` and post the "manufacturer data" you received from the device.

**Comment by Jak-o** [comment]
@maggu2810 
1. My Version:
199 │ Active   │  80 │ 0.10.0.oh230           │ org.eclipse.smarthome.binding.bluetooth.blukii

2. Do you want special entries from the manufacturer data or just some data like that:

2018-11-18 18:25:19.435 [DEBUG] [uetooth.blukii.handler.BlukiiHandler] - Manufacturer data: 4F 02 02 24 71 89 4D AF 2F 04 03 06 5E 0A 10 28 03 00 00 64 03 50

2018-11-18 18:30:23.007 [DEBUG] [uetooth.blukii.handler.BlukiiHandler] - Manufacturer data: 4F 02 02 24 71 89 4D AF 2F 04 03 06 5E 0A 10 28 03 00 00 64 03 40

2018-11-18 18:30:37.096 [DEBUG] [uetooth.blukii.handler.BlukiiHandler] - Manufacturer data: 4F 02 02 24 71 89 4D AF 2F 04 03 06 5E 0A 10 28 02 00 00 64 03 40

2018-11-18 18:32:45.775 [DEBUG] [uetooth.blukii.handler.BlukiiHandler] - Manufacturer data: 4F 02 02 24 71 89 4D AF 2F 04 03 06 5E 0A 10 28 02 00 00 64 03 30

2018-11-18 18:36:46.897 [DEBUG] [uetooth.blukii.handler.BlukiiHandler] - Manufacturer data: 4F 02 02 24 71 89 4D AF 2F 04 03 06 5E 0A 10 28 01 00 00 64 03 30

2018-11-18 18:37:03.997 [DEBUG] [uetooth.blukii.handler.BlukiiHandler] - Manufacturer data: 4F 02 02 24 71 89 4D AF 2F 04 03 06 5E 0A 10 28 01 00 00 64 03 20

2018-11-18 18:38:21.376 [DEBUG] [uetooth.blukii.handler.BlukiiHandler] - Manufacturer data: 4F 02 02 24 71 89 4D AF 2F 04 03 06 5E 0A 10 28 02 00 00 64 03 20

**Comment by Jak-o** [comment]
Can I do s.th. else to get the Version you need or is it not that relevant?

Yes I already thought you need temperature values under zero, but at the moment it is a little bit warmer. I hope for next night :)

**Comment by maggu2810** [comment]
With #6540 we can add tests easily...

To test it yourself you could use #6540 and something like that:

```Java
final BlukiiDataDecoder decoder = new BlukiiDataDecoder();

for (final byte[] data : new byte[][] {
        new byte[] { (byte) 0x4F, (byte) 0x02, (byte) 0x02, (byte) 0x24, (byte) 0x71, (byte) 0x89, (byte) 0x4D,
                (byte) 0xAF, (byte) 0x2F, (byte) 0x04, (byte) 0x03, (byte) 0x06, (byte) 0x5E, (byte) 0x0A,
                (byte) 0x10, (byte) 0x28, (byte) 0x03, (byte) 0x00, (byte) 0x00, (byte) 0x64, (byte) 0x03,
                (byte) 0x50 },
        new byte[] { (byte) 0x4F, (byte) 0x02, (byte) 0x02, (byte) 0x24, (byte) 0x71, (byte) 0x89, (byte) 0x4D,
                (byte) 0xAF, (byte) 0x2F, (byte) 0x04, (byte) 0x03, (byte) 0x06, (byte) 0x5E, (byte) 0x0A,
                (byte) 0x10, (byte) 0x28, (byte) 0x03, (byte) 0x00, (byte) 0x00, (byte) 0x64, (byte) 0x03,
                (byte) 0x40 },
        new byte[] { (byte) 0x4F, (byte) 0x02, (byte) 0x02, (byte) 0x24, (byte) 0x71, (byte) 0x89, (byte) 0x4D,
                (byte) 0xAF, (byte) 0x2F, (byte) 0x04, (byte) 0x03, (byte) 0x06, (byte) 0x5E, (byte) 0x0A,
                (byte) 0x10, (byte) 0x28, (byte) 0x02, (byte) 0x00, (byte) 0x00, (byte) 0x64, (byte) 0x03,
                (byte) 0x40 },
        new byte[] { (byte) 0x4F, (byte) 0x02, (byte) 0x02, (byte) 0x24, (byte) 0x71, (byte) 0x89, (byte) 0x4D,
                (byte) 0xAF, (byte) 0x2F, (byte) 0x04, (byte) 0x03, (byte) 0x06, (byte) 0x5E, (byte) 0x0A,
                (byte) 0x10, (byte) 0x28, (byte) 0x02, (byte) 0x00, (byte) 0x00, (byte) 0x64, (byte) 0x03,
                (byte) 0x30 },
        new byte[] { (byte) 0x4F, (byte) 0x02, (byte) 0x02, (byte) 0x24, (byte) 0x71, (byte) 0x89, (byte) 0x4D,
                (byte) 0xAF, (byte) 0x2F, (byte) 0x04, (byte) 0x03, (byte) 0x06, (byte) 0x5E, (byte) 0x0A,
                (byte) 0x10, (byte) 0x28, (byte) 0x01, (byte) 0x00, (byte) 0x00, (byte) 0x64, (byte) 0x03,
                (byte) 0x30 },
        new byte[] { (byte) 0x4F, (byte) 0x02, (byte) 0x02, (byte) 0x24, (byte) 0x71, (byte) 0x89, (byte) 0x4D,
                (byte) 0xAF, (byte) 0x2F, (byte) 0x04, (byte) 0x03, (byte) 0x06, (byte) 0x5E, (byte) 0x0A,
                (byte) 0x10, (byte) 0x28, (byte) 0x01, (byte) 0x00, (byte) 0x00, (byte) 0x64, (byte) 0x03,
                (byte) 0x20 },
        new byte[] { (byte) 0x4F, (byte) 0x02, (byte) 0x02, (byte) 0x24, (byte) 0x71, (byte) 0x89, (byte) 0x4D,
                (byte) 0xAF, (byte) 0x2F, (byte) 0x04, (byte) 0x03, (byte) 0x06, (byte) 0x5E, (byte) 0x0A,
                (byte) 0x10, (byte) 0x28, (byte) 0x02, (byte) 0x00, (byte) 0x00, (byte) 0x64, (byte) 0x03,
                (byte) 0x20 } }) {
    final BlukiiData blukiiData = decoder.decode(data);
    if (blukiiData == null) {
        System.out.println(String.format("Cannot decode data: %s", HexUtils.bytesToHex(data, " ")));
        continue;
    }

    System.out.println(String.format("Decode data: %s", HexUtils.bytesToHex(data, " ")));
    System.out.println(String.format("  battery: %d", blukiiData.battery));
    blukiiData.environment.ifPresent(environment -> {
        final String prefix = "  environment ";
        System.out.println(prefix + "temperature: " + environment.temperature);
        System.out.println(prefix + "humidity: " + environment.humidity);
        System.out.println(prefix + "pressure: " + environment.pressure);
        System.out.println(prefix + "luminance: " + environment.luminance);
    });
    blukiiData.accelerometer.ifPresent(accelerometer -> {
        final String prefix = "  accelerometer ";
        System.out.println(prefix + "tiltX: " + accelerometer.tiltX);
        System.out.println(prefix + "tiltY: " + accelerometer.tiltY);
        System.out.println(prefix + "tiltZ: " + accelerometer.tiltZ);
    });
    blukiiData.magnetometer.ifPresent(magnetometer -> {
        final String prefix = "  magnetometer ";
        System.out.println(prefix + "X: " + magnetometer.x);
        System.out.println(prefix + "Y: " + magnetometer.y);
        System.out.println(prefix + "Z: " + magnetometer.z);
    });
```

**Comment by maggu2810** [comment]
IMHO the temperature decoding doesn't make sense:

```Java
double temperature = (data[20] & 0xFF) + (data[21] & 0xFF) / 100000000;
```

* data[20] is interpret as unsigned. Should be signed if negative temperatures could be measured
* data[21] is divided by 100000000. Wouldn't 256 make more sense? If data[20] is the part in front of the decimal point and data[21] a fraction, I would assume a step size of 1/256...

**Comment by kaikreuzer** [comment]
> Can you please point me to the documentation / specification how the manufacturer data of "Blukii" is encoded?

I have a specification, but I am not sure whether I am allowed to publicly share it. But here's at least what it says about the temperature:

_"Darstellung Temperatur als Festkommazahl 8.8. 8 integer bit und 8 fractional bits."_

That's all, I'm afraid...

**Comment by maggu2810** [comment]
WRT my comment above, I assume the suggested temperature calculation should be "more correct" then the current one. WDYT?

**Comment by kaikreuzer** [comment]
Yes, we could give it a try. Would have to find my beacon for testing, though - otherwise we have to rely on @Jak-o...

**Comment by Jak-o** [comment]
So here are values under zero from another beacon:

2018-11-20 19:43:15.943 [DEBUG] [uetooth.blukii.handler.BlukiiHandler] - Manufacturer data: 4F 02 02 24 71 89 4D AF 8D 04 03 06 5B 0A 10 27 B0 00 00 14 F0 67

2018-11-20 19:43:31.943 [DEBUG] [uetooth.blukii.handler.BlukiiHandler] - Manufacturer data: 4F 02 02 24 71 89 4D AF 8D 04 03 06 5B 0A 10 27 AF 00 05 15 F0 27

2018-11-20 19:43:48.029 [DEBUG] [uetooth.blukii.handler.BlukiiHandler] - Manufacturer data: 4F 02 02 24 71 89 4D AF 8D 04 03 06 5B 0A 10 27 B0 00 28 17 F1 B7

2018-11-20 19:44:04.093 [DEBUG] [uetooth.blukii.handler.BlukiiHandler] - Manufacturer data: 4F 02 02 24 71 89 4D AF 8D 04 03 06 5B 0A 10 27 AE 00 00 1B F4 37

2018-11-20 19:44:20.180 [DEBUG] [uetooth.blukii.handler.BlukiiHandler] - Manufacturer data: 4F 02 02 24 71 89 4D AF 8D 04 03 06 5B 0A 10 27 AE 00 00 1F F5 97

2018-11-20 19:44:36.229 [DEBUG] [uetooth.blukii.handler.BlukiiHandler] - Manufacturer data: 4F 02 02 24 71 89 4D AF 8D 04 03 06 5B 0A 10 27 AE 00 00 23 F6 87

2018-11-20 19:44:54.321 [DEBUG] [uetooth.blukii.handler.BlukiiHandler] - Manufacturer data: 4F 02 02 24 71 89 4D AF 8D 04 03 06 5B 0A 10 27 AE 00 00 27 F7 47

2018-11-20 19:45:09.350 [DEBUG] [uetooth.blukii.handler.BlukiiHandler] - Manufacturer data: 4F 02 02 24 71 89 4D AF 8D 04 03 06 5B 0A 10 27 AE 00 00 27 F7 47

2018-11-20 19:45:24.419 [DEBUG] [uetooth.blukii.handler.BlukiiHandler] - Manufacturer data: 4F 02 02 24 71 89 4D AF 8D 04 03 06 5B 0A 10 27 AE 00 02 2F F9 47

2018-11-20 19:45:40.549 [DEBUG] [uetooth.blukii.handler.BlukiiHandler] - Manufacturer data: 4F 02 02 24 71 89 4D AF 8D 04 03 06 5B 0A 10 27 AE 00 02 35 FB 17

2018-11-20 19:45:56.618 [DEBUG] [uetooth.blukii.handler.BlukiiHandler] - Manufacturer data: 4F 02 02 24 71 89 4D AF 8D 04 03 06 5B 0A 10 27 AE 00 02 3B FD 07

2018-11-20 19:46:11.891 [DEBUG] [uetooth.blukii.handler.BlukiiHandler] - Manufacturer data: 4F 02 02 24 71 89 4D AF 8D 04 03 06 5B 0A 10 27 AD 00 02 40 FE 97

2018-11-20 19:46:27.924 [DEBUG] [uetooth.blukii.handler.BlukiiHandler] - Manufacturer data: 4F 02 02 24 71 89 4D AF 8D 04 03 06 5B 0A 10 27 AE 00 02 44 00 06

2018-11-20 19:46:44.022 [DEBUG] [uetooth.blukii.handler.BlukiiHandler] - Manufacturer data: 4F 02 02 24 71 89 4D AF 8D 04 03 06 5B 0A 10 27 AE 00 02 48 01 46

2018-11-20 19:47:00.087 [DEBUG] [uetooth.blukii.handler.BlukiiHandler] - Manufacturer data: 4F 02 02 24 71 89 4D AF 8D 04 03 06 5B 0A 10 27 AE 00 02 4A 02 66

2018-11-20 19:47:16.182 [DEBUG] [uetooth.blukii.handler.BlukiiHandler] - Manufacturer data: 4F 02 02 24 71 89 4D AF 8D 04 03 06 5B 0A 10 27 AE 00 02 4B 03 66

2018-11-20 19:47:32.254 [DEBUG] [uetooth.blukii.handler.BlukiiHandler] - Manufacturer data: 4F 02 02 24 71 89 4D AF 8D 04 03 06 5B 0A 10 27 AE 00 02 4C 04 46

2018-11-20 19:47:48.319 [DEBUG] [uetooth.blukii.handler.BlukiiHandler] - Manufacturer data: 4F 02 02 24 71 89 4D AF 8D 04 03 06 5B 0A 10 27 AE 00 02 4C 05 16

2018-11-20 19:48:04.425 [DEBUG] [uetooth.blukii.handler.BlukiiHandler] - Manufacturer data: 4F 02 02 24 71 89 4D AF 8D 04 03 06 5B 0A 10 27 AD 00 00 4C 05 D6

2018-11-20 19:48:20.511 [DEBUG] [uetooth.blukii.handler.BlukiiHandler] - Manufacturer data: 4F 02 02 24 71 89 4D AF 8D 04 03 06 5B 0A 10 27 AD 00 00 4C 06 86

2018-11-20 19:48:36.578 [DEBUG] [uetooth.blukii.handler.BlukiiHandler] - Manufacturer data: 4F 02 02 24 71 89 4D AF 8D 04 03 06 5B 0A 10 27 AD 00 00 4B 07 26

2018-11-20 19:48:52.760 [DEBUG] [uetooth.blukii.handler.BlukiiHandler] - Manufacturer data: 4F 02 02 24 71 89 4D AF 8D 04 03 06 5B 0A 10 27 AD 00 00 4B 07 C6

...hope that helps.

**Comment by Jak-o** [comment]
At a closer look i see that the new values are decimal, very good. 
The actual implementation seems to show only values like 4.0, 5.0 or 6.0 like in maggu2810’s third post!

**Comment by Jak-o** [comment]
I updated my system today and the sensors are working, but now i get the following error:

 2018-12-11 09:53:41.913 [ERROR] [me.binding.bluetooth.BluetoothDevice] - Failed to inform listener 'org.eclipse.smarthome.binding.bluetooth.blukii.handler.BlukiiHandler@9da474': null

java.lang.NullPointerException: null
	at org.eclipse.smarthome.binding.bluetooth.blukii.internal.data.BlukiiDataDecoder.decode(BlukiiDataDecoder.java:35) ~[?:?]
	at org.eclipse.smarthome.binding.bluetooth.blukii.handler.BlukiiHandler.onScanRecordReceived(BlukiiHandler.java:53) ~[?:?]
	at org.eclipse.smarthome.binding.bluetooth.BluetoothDevice.notifyListeners(BluetoothDevice.java:503) ~[?:?]
	at org.eclipse.smarthome.binding.bluetooth.bluez.BlueZBluetoothDevice.lambda$2(BlueZBluetoothDevice.java:139) ~[?:?]

I don't know, is it a openhab or eclipse problem?

**Comment by maggu2810** [comment]
Hi @Jak-o 

As written above:

> Please enable the debug logging for package `org.eclipse.smarthome.binding.bluetooth.blukii.handler` and post the "manufacturer data" you received from the device.

If the decoding contains an error, it should be easily to reproduce if we know the input data.

**Comment by Jak-o** [comment]
I'll try to log, but the error doesn't appear anymore. 
If I get the error again, i will post it with manufacturer data.

**Comment by maggu2810** [comment]
Thank you

**Comment by Jak-o** [comment]
Here some values...

2018-12-11 17:11:46.869 [DEBUG] [ukii.internal.data.BlukiiDataDecoder] - Decode Blukii data: 4F 02 02 24 71 89 4D AF 2F 04 03 06 5E 0A 10 27 95 00 00 64 04 10

2018-12-11 17:11:49.493 [DEBUG] [ukii.internal.data.BlukiiDataDecoder] - Decode Blukii data: 4F 02 02 24 71 89 4D AF 6E 04 03 06 5E 0A 10 27 9D 00 00 4E 06 B0

2018-12-11 17:12:49.838 [DEBUG] [ukii.internal.data.BlukiiDataDecoder] - Decode Blukii data: 4F 02 02 24 71 89 4D AF 8D 04 03 06 61 0A 10 27 9E 00 00 29 16 56

2018-12-11 17:13:41.915 [DEBUG] [ukii.internal.data.BlukiiDataDecoder] - Decode Blukii data: 4F 02 02 24 71 89 4D AF 6E 04 03 06 5E 0A 10 27 9C 00 00 4E 06 B0

2018-12-11 17:15:01.771 [DEBUG] [ukii.internal.data.BlukiiDataDecoder] - Decode Blukii data: 4F 02 02 24 71 89 4D AF 6E 04 03 06 5E 0A 10 27 9D 00 00 4E 06 B0

2018-12-11 17:15:01.801 [DEBUG] [ukii.internal.data.BlukiiDataDecoder] - Decode Blukii data: 4F 02 02 24 71 89 4D AF 2F 04 03 06 5E 0A 10 27 95 00 00 64 04 00

2018-12-11 17:15:15.869 [DEBUG] [ukii.internal.data.BlukiiDataDecoder] - Decode Blukii data: 4F 02 02 24 71 89 4D AF 2F 04 03 06 5E 0A 10 27 95 00 00 64 04 10

2018-12-11 17:15:28.607 [DEBUG] [ukii.internal.data.BlukiiDataDecoder] - Decode Blukii data: 4F 02 02 24 71 89 4D AF 8D 04 03 06 61 0A 10 27 9F 00 00 28 16 56

...hope that helps

**Comment by maggu2810** [comment]
@Jak-o I am interested in the last value in front of that exception. The working ones are not such interesting :wink:
