### ISSUE TITLE
[Hue] NPE when initializing a new light handler

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#6559]
Found this in my log when I approved a new hue light as a Thing:

```
java.lang.NullPointerException: null
        at org.eclipse.smarthome.binding.hue.handler.LightStateConverter.fromXYtoHSBType(LightStateConverter.java:239) ~[?:?]
        at org.eclipse.smarthome.binding.hue.handler.LightStateConverter.toHSBType(LightStateConverter.java:220) ~[?:?]
        at org.eclipse.smarthome.binding.hue.handler.HueLightHandler.onLightStateChanged(HueLightHandler.java:401) ~[?:?]
        at org.eclipse.smarthome.binding.hue.handler.HueLightHandler.onLightAdded(HueLightHandler.java:455) ~[?:?]
        at org.eclipse.smarthome.binding.hue.handler.HueBridgeHandler.registerLightStatusListener(HueBridgeHandler.java:419) ~[?:?]
        at org.eclipse.smarthome.binding.hue.handler.HueLightHandler.getHueClient(HueLightHandler.java:370) ~[?:?]
        at org.eclipse.smarthome.binding.hue.handler.HueLightHandler.initializeThing(HueLightHandler.java:127) ~[?:?]
        at org.eclipse.smarthome.binding.hue.handler.HueLightHandler.initialize(HueLightHandler.java:117) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor76.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
        at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) [101:org.eclipse.smarthome.core:0.10.0.201811171951]
        at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:53) [101:org.eclipse.smarthome.core:0.10.0.201811171951]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:?]
        at java.lang.Thread.run(Thread.java:745) [?:?]
```

**Comment by kaikreuzer** [comment]
Hm, I am failing to reproduce it - my bridge never reports a light to be in XY mode...

And looking at the code, I have no clue how an NPE could happen in that line at all (and yes, I was running the latest code).
@cweitkamp As you were the last working on that part of the code, any idea? If not, I'd be ok to close the issue again as not reproducible...

**Comment by kaikreuzer** [comment]
Ha, funny. Just after I wrote this comment, I had the exception in my console and was able to set a breakpoint - indeed `xy´ is null. I'll create a fix.

**Comment by cweitkamp** [comment]
Which bulb version did you discover? V2 or newer?

Do you think the "xy" is null because it was not reported by the Hue interface or because a problem occurred during parsing?

**Comment by kaikreuzer** [comment]
> Which bulb version did you discover? V2 or newer?

How do I tell? It is not a hue bulb, but one from Paul Neuhaus, which reports modelId "NLG_CCT_light_".

> Do you think the "xy" is null because it was not reported by the Hue interface or because a problem occurred during parsing?

Pretty sure because nothing was reported - the code doesn't look as if there could be a parsing error for this specific field.
