### ISSUE TITLE
Jetty fails with IllegalStateException on hosts with many cores

### ISSUE THREAD

**Issue by mhilbush** [eclipse/smarthome#6574]
On hosts with many cores (somewhere around 16 or more), Jetty throws an IllegalStateException when starting up. As the [webclient config parameters](https://github.com/eclipse/smarthome/blob/master/bundles/io/org.eclipse.smarthome.io.net/src/main/java/org/eclipse/smarthome/io/net/http/internal/WebClientFactoryImpl.java#L61) are buried in the code, there's no obvious way to figure out how to work around the problem (other than finding [my post on the forum](https://community.openhab.org/t/fix-for-jetty-error-when-running-on-host-with-many-cores/57449)).

```
16:25:43.381 [ERROR] [et.http.internal.WebClientFactoryImpl] - Could not start Jetty http client
java.lang.IllegalStateException: Insufficient configured threads: required=13 < max=10 for QueuedThreadPool[common]@75f3f957{STARTED,5<=5<=10,i=5,q=0}[ReservedThreadExecutor@16f08868{s=0/1,p=0}]
        at org.eclipse.jetty.util.thread.ThreadPoolBudget.check(ThreadPoolBudget.java:149) ~[?:?]
        at org.eclipse.jetty.util.thread.ThreadPoolBudget.leaseTo(ThreadPoolBudget.java:130) ~[?:?]
        at org.eclipse.jetty.util.thread.ThreadPoolBudget.leaseFrom(ThreadPoolBudget.java:175) ~[?:?]
        at org.eclipse.jetty.io.SelectorManager.doStart(SelectorManager.java:251) ~[?:?]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[?:?]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138) ~[?:?]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117) ~[?:?]
        at org.eclipse.jetty.client.AbstractConnectorHttpClientTransport.doStart(AbstractConnectorHttpClientTransport.java:64) ~[?:?]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[?:?]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138) ~[?:?]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117) ~[?:?]
        at org.eclipse.jetty.client.HttpClient.doStart(HttpClient.java:241) ~[?:?]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[?:?]
        at org.eclipse.smarthome.io.net.http.internal.WebClientFactoryImpl$2.run(WebClientFactoryImpl.java:258) ~[?:?]
        at org.eclipse.smarthome.io.net.http.internal.WebClientFactoryImpl$2.run(WebClientFactoryImpl.java:1) ~[?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at org.eclipse.smarthome.io.net.http.internal.WebClientFactoryImpl.createHttpClientInternal(WebClientFactoryImpl.java:244) ~[?:?]
        at org.eclipse.smarthome.io.net.http.internal.WebClientFactoryImpl.access$7(WebClientFactoryImpl.java:242) ~[?:?]
        at org.eclipse.smarthome.io.net.http.internal.WebClientFactoryImpl$1.run(WebClientFactoryImpl.java:218) ~[?:?]
        at org.eclipse.smarthome.io.net.http.internal.WebClientFactoryImpl$1.run(WebClientFactoryImpl.java:1) ~[?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at org.eclipse.smarthome.io.net.http.internal.WebClientFactoryImpl.initialize(WebClientFactoryImpl.java:209) ~[?:?]
        at org.eclipse.smarthome.io.net.http.internal.WebClientFactoryImpl.getCommonHttpClient(WebClientFactoryImpl.java:160) ~[?:?]
        at org.eclipse.smarthome.io.net.http.HttpUtil.executeUrlAndGetReponse(HttpUtil.java:194) ~[?:?]
        at org.eclipse.smarthome.io.net.http.HttpUtil.downloadData(HttpUtil.java:438) ~[?:?]
        at org.eclipse.smarthome.io.net.http.HttpUtil.downloadImage(HttpUtil.java:401) ~[?:?]
        at org.eclipse.smarthome.io.net.http.HttpUtil.downloadImage(HttpUtil.java:372) ~[?:?]
        at org.eclipse.smarthome.io.net.http.HttpUtil.downloadImage(HttpUtil.java:358) ~[?:?]
        at org.openhab.binding.squeezebox.internal.handler.SqueezeBoxPlayerHandler.lambda$0(SqueezeBoxPlayerHandler.java:419) ~[?:?]```

**Comment by kaikreuzer** [comment]
> Insufficient configured threads: required=13

Do you happen to know how Jetty calculates the minimal number based on the cores?
We could then set it accordingly in https://github.com/eclipse/smarthome/blob/master/bundles/io/org.eclipse.smarthome.io.net/src/main/java/org/eclipse/smarthome/io/net/http/internal/WebClientFactoryImpl.java#L173.

**Comment by mhilbush** [comment]
I tracked it as far as here, but didn't get to the actual calculation.
https://github.com/eclipse/jetty.project/blob/c7fc674846577bbdf33585638a42ea46e0a00768/jetty-util/src/main/java/org/eclipse/jetty/util/thread/ThreadPoolBudget.java#L148

**Comment by kaikreuzer** [comment]
What is weird is that the exception says `max=10`, while we set [max to 40](https://github.com/eclipse/smarthome/blob/master/bundles/io/org.eclipse.smarthome.io.net/src/main/java/org/eclipse/smarthome/io/net/http/internal/WebClientFactoryImpl.java#L174) and only min to 10 for the shared client.

I checked the code and it seems we are not mixing up min&max anywhere. So I have no idea, why it thinks that max should be limited to 10...?

**Comment by mhilbush** [comment]
And, I just changed `maxThreadsCustom` to 5 and it started up fine.

**Comment by kaikreuzer** [comment]
The bug seems to be [here](https://github.com/eclipse/smarthome/blob/master/bundles/io/org.eclipse.smarthome.io.net/src/main/java/org/eclipse/smarthome/io/net/http/internal/WebClientFactoryImpl.java#L218): It invariably creates and sets a new ThreadPool with `maxThreadsCustom` threads for the common client :-/

**Comment by kaikreuzer** [comment]
The treadpool that is created [here](https://github.com/eclipse/smarthome/blob/master/bundles/io/org.eclipse.smarthome.io.net/src/main/java/org/eclipse/smarthome/io/net/http/internal/WebClientFactoryImpl.java#L213) does not ever seem to be used :-(

**Comment by mhilbush** [comment]
Ugh. I can't believe I didn't spot that when reading through the code.

**Comment by kaikreuzer** [comment]
https://github.com/eclipse/smarthome/pull/6588 shoud fix it.

**Comment by mhilbush** [comment]
Thanks!

So, now that it's using the correct max of 40, the likelihood of throwing that error becomes greatly reduced, except if the host has **a lot of cores**.

**Comment by kaikreuzer** [comment]
Right and if you are running such a massively parallel machine, you are still free to add an individual configuration for the pool size.

**Comment by mhilbush** [comment]
Yep. While the likelihood of someone running into this is now very low, I'll update my forum post to be more explicit about which parameter needs to be changed.
