### ISSUE TITLE
[Homematic] Silvercrest HmIP-eTRV-B1 NPE / Missing Data

### ISSUE THREAD

**Issue by bennir** [eclipse/smarthome#6610]
Hello,

I am running openHAB 2.4.0~M6-1 with piVCCU 3.41.11-10 (CCU3).
Received my new Silvercrest (Lidl) thermostats today and connected them. They appeared in the PaperUI Inbox without problems, but some Channels do not display values correctly.

See here:
![image](https://user-images.githubusercontent.com/2631507/49330368-ee2e3680-f58d-11e8-8244-ee878539b2c8.png)

I set the Logging Level to trace for org.eclipse.smarthome.binding.homematic to try to find the real issue but don't have enough experience.

Error in Log, don't know if really connected to ACTUAL_TEMPERATURE:
```java
2018-12-01 17:08:57.404 [DEBUG] [ommunicator.AbstractHomematicGateway] - Received new (Double) value '20.2' for 'XXXX:1#ACTUAL_TEMPERATURE' from gateway with id '3014F711A061A7D8A9918A46'
2018-12-01 17:08:57.409 [ERROR] [ematic.handler.HomematicThingHandler] - null
java.lang.NullPointerException: null
        at org.eclipse.smarthome.binding.homematic.internal.converter.type.QuantityTypeConverter.fromBinding(QuantityTypeConverter.java:99) ~[191:org.eclipse.smarthome.binding.homematic:0.10.0.oh240M6]
        at org.eclipse.smarthome.binding.homematic.internal.converter.type.QuantityTypeConverter.fromBinding(QuantityTypeConverter.java:1) ~[191:org.eclipse.smarthome.binding.homematic:0.10.0.oh240M6]
        at org.eclipse.smarthome.binding.homematic.internal.converter.type.AbstractTypeConverter.convertFromBinding(AbstractTypeConverter.java:121) ~[191:org.eclipse.smarthome.binding.homematic:0.10.0.oh240M6]
        at org.eclipse.smarthome.binding.homematic.handler.HomematicThingHandler.updateChannelState(HomematicThingHandler.java:381) ~[191:org.eclipse.smarthome.binding.homematic:0.10.0.oh240M6]
        at org.eclipse.smarthome.binding.homematic.handler.HomematicThingHandler.updateDatapointState(HomematicThingHandler.java:355) ~[191:org.eclipse.smarthome.binding.homematic:0.10.0.oh240M6]
        at org.eclipse.smarthome.binding.homematic.handler.HomematicBridgeHandler.onStateUpdated(HomematicBridgeHandler.java:305) ~[191:org.eclipse.smarthome.binding.homematic:0.10.0.oh240M6]
        at org.eclipse.smarthome.binding.homematic.internal.communicator.AbstractHomematicGateway.lambda$1(AbstractHomematicGateway.java:742) ~[191:org.eclipse.smarthome.binding.homematic:0.10.0.oh240M6]
        at org.eclipse.smarthome.binding.homematic.internal.misc.DelayedExecuter.start(DelayedExecuter.java:65) [191:org.eclipse.smarthome.binding.homematic:0.10.0.oh240M6]
        at org.eclipse.smarthome.binding.homematic.internal.communicator.AbstractHomematicGateway.eventReceived(AbstractHomematicGateway.java:739) [191:org.eclipse.smarthome.binding.homematic:0.10.0.oh240M6]
        at org.eclipse.smarthome.binding.homematic.internal.communicator.server.RpcResponseHandler.handleEvent(RpcResponseHandler.java:98) [191:org.eclipse.smarthome.binding.homematic:0.10.0.oh240M6]
        at org.eclipse.smarthome.binding.homematic.internal.communicator.server.RpcResponseHandler.handleMethodCall(RpcResponseHandler.java:51) [191:org.eclipse.smarthome.binding.homematic:0.10.0.oh240M6]
        at org.eclipse.smarthome.binding.homematic.internal.communicator.server.RpcResponseHandler.handleMethodCall(RpcResponseHandler.java:68) [191:org.eclipse.smarthome.binding.homematic:0.10.0.oh240M6]
        at org.eclipse.smarthome.binding.homematic.internal.communicator.server.XmlRpcServer$ResponseHandler.handle(XmlRpcServer.java:126) [191:org.eclipse.smarthome.binding.homematic:0.10.0.oh240M6]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [84:org.eclipse.jetty.server:9.4.11.v20180605]
        at org.eclipse.jetty.server.Server.handle(Server.java:531) [84:org.eclipse.jetty.server:9.4.11.v20180605]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352) [84:org.eclipse.jetty.server:9.4.11.v20180605]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260) [84:org.eclipse.jetty.server:9.4.11.v20180605]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281) [75:org.eclipse.jetty.io:9.4.11.v20180605]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102) [75:org.eclipse.jetty.io:9.4.11.v20180605]
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118) [75:org.eclipse.jetty.io:9.4.11.v20180605]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333) [87:org.eclipse.jetty.util:9.4.11.v20180605]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310) [87:org.eclipse.jetty.util:9.4.11.v20180605]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168) [87:org.eclipse.jetty.util:9.4.11.v20180605]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126) [87:org.eclipse.jetty.util:9.4.11.v20180605]
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366) [87:org.eclipse.jetty.util:9.4.11.v20180605]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762) [87:org.eclipse.jetty.util:9.4.11.v20180605]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680) [87:org.eclipse.jetty.util:9.4.11.v20180605]
        at java.lang.Thread.run(Thread.java:748) [?:?]
``` 

CONTROL_MODE does not have any log output "Received new value"
BOOST_MODE (Bool) and ACTIVE_PROFILE (Int) receive values, don't throw errors, but are not displayed correctly. 

If you can lead me in some directions, I can help further identify the problems.

**Comment by bennir** [comment]
After Updating to 2.4.0 Milestone 7 the issue is resolved
