### ISSUE TITLE
[mqtt] Embedded broker: Client id length restriction

### ISSUE THREAD

**Issue by davidgraeff** [eclipse/smarthome#6753]
If the client id is too long, an exception is thrown:

```
2018-12-28 17:47:58.226 [ERROR] [quette.server.netty.NettyMQTTHandler] - Unexpected exception while processing MQTT message. Closing Netty channel. CId=null

java.lang.NullPointerException: null

	at io.moquette.server.netty.metrics.MQTTMessageLogger.logMQTTMessage(MQTTMessageLogger.java:54) ~[199:org.eclipse.smarthome.io.mqttembeddedbroker:0.10.0.oh240]

	at io.moquette.server.netty.metrics.MQTTMessageLogger.channelRead(MQTTMessageLogger.java:44) ~[199:org.eclipse.smarthome.io.mqttembeddedbroker:0.10.0.oh240]

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [199:org.eclipse.smarthome.io.mqttembeddedbroker:0.10.0.oh240]

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [199:org.eclipse.smarthome.io.mqttembeddedbroker:0.10.0.oh240]

	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [199:org.eclipse.smarthome.io.mqttembeddedbroker:0.10.0.oh240]

	at io.moquette.server.netty.metrics.MessageMetricsHandler.channelRead(MessageMetricsHandler.java:50) [199:org.eclipse.smarthome.io.mqttembeddedbroker:0.10.0.oh240]

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [199:org.eclipse.smarthome.io.mqttembeddedbroker:0.10.0.oh240]

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [199:org.eclipse.smarthome.io.mqttembeddedbroker:0.10.0.oh240]

	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [199:org.eclipse.smarthome.io.mqttembeddedbroker:0.10.0.oh240]

	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [199:org.eclipse.smarthome.io.mqttembeddedbroker:0.10.0.oh240]

	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297) [199:org.eclipse.smarthome.io.mqttembeddedbroker:0.10.0.oh240]

	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:350) [199:org.eclipse.smarthome.io.mqttembeddedbroker:0.10.0.oh240]

	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) [199:org.eclipse.smarthome.io.mqttembeddedbroker:0.10.0.oh240]

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [199:org.eclipse.smarthome.io.mqttembeddedbroker:0.10.0.oh240]

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [199:org.eclipse.smarthome.io.mqttembeddedbroker:0.10.0.oh240]

	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [199:org.eclipse.smarthome.io.mqttembeddedbroker:0.10.0.oh240]

	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [199:org.eclipse.smarthome.io.mqttembeddedbroker:0.10.0.oh240]

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [199:org.eclipse.smarthome.io.mqttembeddedbroker:0.10.0.oh240]

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [199:org.eclipse.smarthome.io.mqttembeddedbroker:0.10.0.oh240]

	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [199:org.eclipse.smarthome.io.mqttembeddedbroker:0.10.0.oh240]

	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [199:org.eclipse.smarthome.io.mqttembeddedbroker:0.10.0.oh240]

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [199:org.eclipse.smarthome.io.mqttembeddedbroker:0.10.0.oh240]

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [199:org.eclipse.smarthome.io.mqttembeddedbroker:0.10.0.oh240]

	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [199:org.eclipse.smarthome.io.mqttembeddedbroker:0.10.0.oh240]

	at io.moquette.server.netty.metrics.BytesMetricsHandler.channelRead(BytesMetricsHandler.java:51) [199:org.eclipse.smarthome.io.mqttembeddedbroker:0.10.0.oh240]

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [199:org.eclipse.smarthome.io.mqttembeddedbroker:0.10.0.oh240]

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [199:org.eclipse.smarthome.io.mqttembeddedbroker:0.10.0.oh240]

	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [199:org.eclipse.smarthome.io.mqttembeddedbroker:0.10.0.oh240]

	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359) [199:org.eclipse.smarthome.io.mqttembeddedbroker:0.10.0.oh240]

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [199:org.eclipse.smarthome.io.mqttembeddedbroker:0.10.0.oh240]

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [199:org.eclipse.smarthome.io.mqttembeddedbroker:0.10.0.oh240]

	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935) [199:org.eclipse.smarthome.io.mqttembeddedbroker:0.10.0.oh240]

	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:141) [199:org.eclipse.smarthome.io.mqttembeddedbroker:0.10.0.oh240]

	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645) [199:org.eclipse.smarthome.io.mqttembeddedbroker:0.10.0.oh240]

	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580) [199:org.eclipse.smarthome.io.mqttembeddedbroker:0.10.0.oh240]

	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497) [199:org.eclipse.smarthome.io.mqttembeddedbroker:0.10.0.oh240]

	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459) [199:org.eclipse.smarthome.io.mqttembeddedbroker:0.10.0.oh240]

	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886) [199:org.eclipse.smarthome.io.mqttembeddedbroker:0.10.0.oh240]

	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [199:org.eclipse.smarthome.io.mqttembeddedbroker:0.10.0.oh240]

	at java.lang.Thread.run(Thread.java:748) [?:?]
```

Because mqttLens by default uses a long client id, this need to be catched with a better error message or the client id length need to be increased.

**Comment by maggu2810** [comment]
Can you elaborate the current client ID length limits?
AFAIK the limit is defined by the MQTT specification itself.

**Comment by maggu2810** [comment]
Okay, I just looked at the specification for 3.1.1.

> The Server MUST allow ClientIds which are between 1 and 23 UTF-8 encoded bytes in length, and that contain only the characters
> "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ" [MQTT-3.1.3-5].

> The Server MAY allow ClientId’s that contain more than 23 encoded bytes. The Server MAY allow ClientId’s that contain characters not included in the list given above.
