### ISSUE TITLE
[expire] expire binding does not work with groups

### ISSUE THREAD

**Issue by Rossko57** [eclipse/smarthome#6781]
OH 2.4.0 stable

Expire binding does not configure for groups, rejects command.
It is legitimate to send commands to Group Items (although not updates)
A use case here would be to timeout a group of light switches, for example.

Sample Item
`Group gTestingX "test group [%s]" {expire="30s,command=ON"}`
Item with type specified
`Group:Switch gTestingS "test group [%s]" {expire="30s,command=ON"}
`
openhab.log
2019-01-02 23:25:58.911 [INFO ] [el.core.internal.ModelRepositoryImpl] - Refreshing model 'doors.items'
2019-01-02 23:25:58.957 [ERROR] [el.item.internal.GenericItemProvider] - Binding configuration of type 'expire' of item 'gTestingX' could not be parsed correctly.
org.eclipse.smarthome.model.item.BindingConfigParseException: The string 'ON' does not represent a valid command for item gTestingX
	at org.openhab.core.binding.internal.BindingConfigReaderDelegate.processBindingConfiguration(BindingConfigReaderDelegate.java:51) ~[?:?]
	at org.eclipse.smarthome.model.item.internal.GenericItemProvider.internalDispatchBindings(GenericItemProvider.java:397) ~[?:?]
	at org.eclipse.smarthome.model.item.internal.GenericItemProvider.internalDispatchBindings(GenericItemProvider.java:366) ~[?:?]
	at org.eclipse.smarthome.model.item.internal.GenericItemProvider.processBindingConfigsFromModel(GenericItemProvider.java:229) ~[?:?]
	at org.eclipse.smarthome.model.item.internal.GenericItemProvider.modelChanged(GenericItemProvider.java:432) ~[?:?]
	at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.notifyListeners(ModelRepositoryImpl.java:301) ~[?:?]
	at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.addOrRefreshModel(ModelRepositoryImpl.java:139) ~[?:?]
	at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.checkFile(FolderObserver.java:227) ~[?:?]
	at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.processWatchEvent(FolderObserver.java:291) ~[?:?]
	at org.eclipse.smarthome.core.service.WatchQueueReader.lambda$3(WatchQueueReader.java:323) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: org.openhab.model.item.binding.BindingConfigParseException: The string 'ON' does not represent a valid command for item gTestingX
	at org.openhab.binding.expire.internal.ExpireGenericBindingProvider$ExpireBindingConfig.<init>(ExpireGenericBindingProvider.java:172) ~[?:?]
	at org.openhab.binding.expire.internal.ExpireGenericBindingProvider.processBindingConfiguration(ExpireGenericBindingProvider.java:60) ~[?:?]
	at org.openhab.core.binding.internal.BindingConfigReaderDelegate.processBindingConfiguration(BindingConfigReaderDelegate.java:49) ~[?:?]
	... 16 more

2019-01-02 23:25:58.985 [ERROR] [el.item.internal.GenericItemProvider] - Binding configuration of type 'expire' of item 'gTestingS' could not be parsed correctly.
org.eclipse.smarthome.model.item.BindingConfigParseException: The string 'ON' does not represent a valid command for item gTestingS
 ... same error pattern snipped ...

**Comment by kaikreuzer** [comment]
This is an addon from https://github.com/openhab/openhab1-addons, so please report it there - thanks!

**Comment by Rossko57** [comment]
comment - (re created as https://github.com/openhab/openhab1-addons/issues/5751)
