### ISSUE TITLE
[digitalstrom] Firmware 1.15 introduced NPE with openHAB 2.4

### ISSUE THREAD

**Issue by vialkoje** [eclipse/smarthome#6798]
My digitalSTROM installation seems to have a size that makes the operation a bit Tricky and the Binding as the digitalSTROM server had pretty frequent hiccups. 

I managed to have it running more stable by reducing the poll frequencies as suggested by Michael Ochel in another post.

After upgrading the digitalSTROM server to firmware 1.15 it seems that something was changed that introduced a NPE somewhere in the context of the Temperature control manager.

[WARN ] [ommon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 
java.lang.UnsupportedOperationException: JsonNull
        at com.google.gson.JsonElement.getAsFloat(JsonElement.java:217) ~[?:?]
        at org.eclipse.smarthome.binding.digitalstrom.internal.lib.climate.jsonresponsecontainer.impl.TemperatureControlStatus.init(TemperatureControlStatus.java:81) ~[?:?]
        at org.eclipse.smarthome.binding.digitalstrom.internal.lib.climate.jsonresponsecontainer.impl.TemperatureControlStatus.<init>(TemperatureControlStatus.java:54) ~[?:?]
        at org.eclipse.smarthome.binding.digitalstrom.internal.lib.serverconnection.impl.DsAPIImpl.getApartmentTemperatureControlStatus(DsAPIImpl.java:1115) ~[?:?]
        at org.eclipse.smarthome.binding.digitalstrom.internal.lib.manager.impl.TemperatureControlManager.checkZones(TemperatureControlManager.java:170) ~[?:?]
        at org.eclipse.smarthome.binding.digitalstrom.internal.lib.manager.impl.TemperatureControlManager.<init>(TemperatureControlManager.java:151) ~[?:?]
        at org.eclipse.smarthome.binding.digitalstrom.internal.lib.manager.impl.TemperatureControlManager.<init>(TemperatureControlManager.java:130) ~[?:?]
        at org.eclipse.smarthome.binding.digitalstrom.handler.BridgeHandler$Initializer.run(BridgeHandler.java:166) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]

@MichaelOchel  might you have a chance to throw a glimpse on this topic ? I’d also try to fix it thouh as C-developer I‘m having a hard time getting the development and debugging environment up and running...

Regards Jens

**Comment by vialkoje** [comment]
Just as a short note - I managed to work around the issue by switching off temperature control in the digitalSTROM Server as I do not use the feature either way... now focusing again on the stability issues where the 2 year old dss 1GB Server resets hen there is too much workload...

**Comment by maggu2810** [comment]
@vialkoje  Please use triple backticks for code blocks / pre-formatted text.
