### ISSUE TITLE
[digitalstrom] Status of DigitalStrom Server Thing: CONFIGURATION_PENDING Checking configuration...

### ISSUE THREAD

**Issue by maxx92** [eclipse/smarthome#6817]
Hello. It's me again. The CONFIGURATION_PENDING message is again popping up. Plus following two error messages out of the log:

The first one seems to pop up when I was trying to find the server (I uninstalled the binding and reinstalled)

`2019-01-07 16:06:11.996 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 
java.lang.IllegalArgumentException: illegal IPv4 address
	at java.net.HostPortrange.<init>(HostPortrange.java:142) ~[?:?]
	at java.net.URLPermission$Authority.<init>(URLPermission.java:486) ~[?:?]
	at java.net.URLPermission.parseURI(URLPermission.java:454) ~[?:?]
	at java.net.URLPermission.init(URLPermission.java:170) ~[?:?]
	at java.net.URLPermission.<init>(URLPermission.java:166) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.URLtoSocketPermission(HttpURLConnection.java:1084) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1034) ~[?:?]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177) ~[?:?]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:162) ~[?:?]
	at org.eclipse.smarthome.binding.digitalstrom.internal.lib.serverconnection.impl.HttpTransportImpl.checkConnection(HttpTransportImpl.java:380) ~[?:?]
	at org.eclipse.smarthome.binding.digitalstrom.internal.lib.serverconnection.impl.DsAPIImpl.checkConnection(DsAPIImpl.java:695) ~[?:?]
	at org.eclipse.smarthome.binding.digitalstrom.internal.discovery.BridgeDiscoveryService$1.getThingUID(BridgeDiscoveryService.java:76) ~[?:?]
	at org.eclipse.smarthome.binding.digitalstrom.internal.discovery.BridgeDiscoveryService$1.createResult(BridgeDiscoveryService.java:61) ~[?:?]
	at org.eclipse.smarthome.binding.digitalstrom.internal.discovery.BridgeDiscoveryService$1.run(BridgeDiscoveryService.java:57) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]`

The second one is still persisting:

`2019-01-07 16:21:57.153 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 
java.lang.StringIndexOutOfBoundsException: String index out of range: 2
	at java.lang.String.substring(String.java:1963) ~[?:?]
	at org.eclipse.smarthome.binding.digitalstrom.internal.discovery.DiscoveryServiceManager.onDeviceAdded(DiscoveryServiceManager.java:200) ~[?:?]
	at org.eclipse.smarthome.binding.digitalstrom.internal.lib.manager.impl.DeviceStatusManagerImpl$PollingRunnable.run(DeviceStatusManagerImpl.java:345) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]`

So far, all digitalstrom devices are off-line, once more... 

As I uninstalled and reinstalled the binding I presume I use the latest.

@MichaelOchel: Can you please help?

**Comment by maggu2810** [comment]
Please use triple backticks for code blocks, multiline preformatted text, etc.
