### ISSUE TITLE
Installing OpenHAB2 development with Eclipse installer

### ISSUE THREAD

**Issue by JakobSpi** [eclipse/smarthome#6837]
When doing the development installation from the website https://www.openhab.org/docs/developer/development/ide.html i get an error in the eclipse installer. I choose Openhab Development and openhab Add-ons 2 
When starting the download and installation process i get this message with the error at the bottom:

[2019-01-11 19:30:10] Executing bootstrap tasks
[2019-01-11 19:30:10] Java(TM) SE Runtime Environment 1.8.0_191-b12
[2019-01-11 19:30:10] Product org.eclipse.products.epp.package.java.neon
[2019-01-11 19:30:10] Workspace C:\Users\Jakob\openhab2-master\ws
[2019-01-11 19:30:10] Project com.github.openhab2.1_infra.master
[2019-01-11 19:30:10] Project com.github.openhab2.2_openhab2.master
[2019-01-11 19:30:10] Project com.github.openhab2.3_openhab1.master
[2019-01-11 19:30:10] Project com.github.openhab2.4_zigbee.master
[2019-01-11 19:30:10] Project com.github.openhab2.5_zwave.master
[2019-01-11 19:30:10] Project com.github.openhab2.6_bacnet.master
[2019-01-11 19:30:10] Project com.github.openhab2.7_habpanel.master
[2019-01-11 19:30:10] Project com.github.openhab2.8_habmin.master
[2019-01-11 19:30:10] Project com.github.openhab2.9_esh.master
[2019-01-11 19:30:10] Project com.github.openhab2.10_core.master
[2019-01-11 19:30:10] Bundle org.eclipse.oomph.setup 1.10.0.v20180914-1031, build=3784, branch=d5b911e1f3bc20f8e0c54af3126d8150fbc53bdf
[2019-01-11 19:30:10] Bundle org.eclipse.oomph.setup.core 1.11.0.v20181203-0741, build=3784, branch=d5b911e1f3bc20f8e0c54af3126d8150fbc53bdf
[2019-01-11 19:30:10] Bundle org.eclipse.oomph.setup.installer 1.11.0.v20181107-1003, build=3784, branch=d5b911e1f3bc20f8e0c54af3126d8150fbc53bdf
[2019-01-11 19:30:10] Bundle org.eclipse.oomph.setup.p2 1.10.0.v20180706-1242, build=3784, branch=d5b911e1f3bc20f8e0c54af3126d8150fbc53bdf
[2019-01-11 19:30:10] Performing Workspace C:\Users\Jakob\openhab2-master\ws
[2019-01-11 19:30:10] Performing P2 Director (Eclipse IDE for Java Developers (Neon))
[2019-01-11 19:30:10] Offline = false
[2019-01-11 19:30:10] Mirrors = true
[2019-01-11 19:30:10] Resolving 32 requirements from 5 repositories to C:\Users\Jakob\openhab2-master\eclipse
[2019-01-11 19:30:10] Requirement org.eclipse.wst.xml_ui.feature.feature.group
[2019-01-11 19:30:10] Requirement org.eclipse.mylyn.java_feature.feature.group
[2019-01-11 19:30:10] Requirement org.codehaus.groovy.eclipse.feature.feature.group
[2019-01-11 19:30:10] Requirement org.eclipse.mylyn.git.feature.group
[2019-01-11 19:30:10] Requirement org.eclipse.pde.feature.group
[2019-01-11 19:30:10] Requirement org.eclipse.wst.jsdt.feature.feature.group
[2019-01-11 19:30:10] Requirement org.eclipse.wst.web_ui.feature.feature.group
[2019-01-11 19:30:10] Requirement epp.package.java [4.6.0,5.0.0)
[2019-01-11 19:30:10] Requirement org.eclipse.platform.feature.group [4.6.0,5.0.0)
[2019-01-11 19:30:10] Requirement org.eclipse.rcp.feature.group [4.6.0,5.0.0)
[2019-01-11 19:30:10] Requirement org.eclipse.buildship.feature.group
[2019-01-11 19:30:10] Requirement org.eclipse.egit.feature.group
[2019-01-11 19:30:10] Requirement org.eclipse.egit.mylyn.feature.group
[2019-01-11 19:30:10] Requirement org.eclipse.jdt.feature.group
[2019-01-11 19:30:10] Requirement org.eclipse.jgit.feature.group
[2019-01-11 19:30:10] Requirement org.eclipse.m2e.feature.feature.group
[2019-01-11 19:30:10] Requirement org.eclipse.m2e.logback.feature.feature.group
[2019-01-11 19:30:10] Requirement org.eclipse.mylyn.bugzilla_feature.feature.group
[2019-01-11 19:30:10] Requirement org.eclipse.mylyn.context_feature.feature.group
[2019-01-11 19:30:10] Requirement org.eclipse.mylyn.hudson.feature.group
[2019-01-11 19:30:10] Requirement org.eclipse.mylyn.ide_feature.feature.group
[2019-01-11 19:30:10] Requirement org.eclipse.mylyn.wikitext_feature.feature.group
[2019-01-11 19:30:10] Requirement org.eclipse.mylyn_feature.feature.group
[2019-01-11 19:30:10] Requirement org.eclipse.recommenders.mylyn.rcp.feature.feature.group
[2019-01-11 19:30:10] Requirement org.eclipse.recommenders.rcp.feature.feature.group
[2019-01-11 19:30:10] Requirement org.eclipse.recommenders.snipmatch.rcp.feature.feature.group
[2019-01-11 19:30:10] Requirement org.eclipse.oomph.setup.feature.group
[2019-01-11 19:30:10] Requirement org.eclipse.oomph.setup.jdt.feature.group
[2019-01-11 19:30:10] Requirement org.eclipse.oomph.setup.git.feature.group
[2019-01-11 19:30:10] Requirement org.eclipse.oomph.setup.workingsets.feature.group
[2019-01-11 19:30:10] Requirement org.eclipse.oomph.setup.projects.feature.group
[2019-01-11 19:30:10] Requirement org.eclipse.oomph.setup.pde.feature.group
[2019-01-11 19:30:10] Repository http://dist.springsource.org/snapshot/GRECLIPSE/e4.8
[2019-01-11 19:30:10] Repository http://download.eclipse.org/technology/epp/packages/neon
[2019-01-11 19:30:10] Repository http://download.eclipse.org/releases/neon/201705151400
[2019-01-11 19:30:10] Repository http://download.eclipse.org/oomph/updates/milestone/latest
[2019-01-11 19:30:10] Repository http://download.eclipse.org/egit/updates
[2019-01-11 19:30:12] Calculating requirements and dependencies.
[2019-01-11 19:30:14] Cannot complete the request.  Generating details.
[2019-01-11 19:30:14] ERROR: org.eclipse.equinox.p2.director code=10053 Cannot complete the install because one or more required items could not be found.
  at org.eclipse.oomph.util.OomphPlugin.coreException(OomphPlugin.java:280)
  at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl.resolve(ProfileTransactionImpl.java:425)
  at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl.commit(ProfileTransactionImpl.java:337)
  at org.eclipse.oomph.setup.p2.impl.P2TaskImpl.perform(P2TaskImpl.java:733)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3334)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3262)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3243)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3143)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:575)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:701)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
  ERROR: org.eclipse.equinox.p2.director code=0 Software being installed: artificial_root 1.0.0.v1547231412703
  ERROR: org.eclipse.equinox.p2.director code=0 Missing requirement: Java Development Tools Core 3.14.0.xx-201901101855-e48 (org.eclipse.jdt.core 3.14.0.xx-201901101855-e48) requires 'osgi.bundle; org.eclipse.core.resources [3.12.0,4.0.0)' but it could not be found
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: artificial_root 1.0.0.v1547231412703
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.codehaus.groovy.eclipse.feature.feature.group 0.0.0
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: artificial_root 1.0.0.v1547231412703
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.eclipse.jdt.feature.group 0.0.0
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: Groovy-Eclipse Compilerless feature 3.3.0.xx-201901101855-e48 (org.codehaus.groovy.compilerless.feature.feature.group 3.3.0.xx-201901101855-e48)
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.codehaus.groovy.headless.feature.feature.group [3.3.0.xx-201901101855-e48,3.3.0.xx-201901101855-e48]
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: Eclipse Groovy Development Tools 3.3.0.xx-201901101855-e48 (org.codehaus.groovy.eclipse.feature.feature.group 3.3.0.xx-201901101855-e48)
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.codehaus.groovy.compilerless.feature.feature.group [3.3.0.xx-201901101855-e48,3.3.0.xx-201901101855-e48]
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: Groovy-Eclipse Headless feature 3.3.0.xx-201901101855-e48 (org.codehaus.groovy.headless.feature.feature.group 3.3.0.xx-201901101855-e48)
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.codehaus.groovy.jdt.patch.feature.group [3.3.0.xx-201901101855-e48,3.3.0.xx-201901101855-e48]
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From Patch: org.codehaus.groovy.jdt.patch.feature.group 3.3.0.xx-201901101855-e48 Eclipse Java Development Tools 3.12.3.v20170301-0400 (org.eclipse.jdt.feature.group 3.12.3.v20170301-0400)
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.eclipse.jdt.core [3.14.0.xx-201901101855-e48,3.14.0.xx-201901101855-e48]

[2019-01-11 19:30:14] 

I want to create a Binding for openhab thats the reason i am doing this.

Help would be awesome,

Thanks
JS

**Comment by maggu2810** [comment]
Hi,
for multiline preformatted text please use triple backticks.

This is the issue tracker for the Eclipse SmartHome problem.
The setup instructions for ESH could be found here: https://www.eclipse.org/smarthome/documentation/development/ide.html

Problems of the openHAB IDE are out of scope that project.
Please use the openHAB issue tracker if there is a real problem or the openHAB community forum to request some support first.
