### ISSUE TITLE
Oomph Setup Install Fails

### ISSUE THREAD

**Issue by stack-head** [eclipse/smarthome#6893]
Following the instructions on how to setup a SmartHome development environment (https://www.eclipse.org/smarthome/documentation/development/ide.html) has started failing for me in the past week (it worked without issue before).
I've reattempted this after deleting .eclipse, .p2, and .maven
Also reproduced this same error in a clean vagrant environment.
This has only recently stopped working, I suspect the issue is with some kind of a remote update, but don't know eclipse well enough to troubleshoot further.

The error message I get:
```
Calculating requirements and dependencies.
Cannot complete the request.  Generating details.
ERROR: org.eclipse.equinox.p2.director code=10054 Cannot complete the install because of a conflicting dependency.
  at org.eclipse.oomph.util.OomphPlugin.coreException(OomphPlugin.java:280)
  at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl.resolve(ProfileTransactionImpl.java:425)
  at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl.commit(ProfileTransactionImpl.java:337)
  at org.eclipse.oomph.setup.p2.impl.P2TaskImpl.perform(P2TaskImpl.java:733)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3335)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3263)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3244)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3144)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:575)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:701)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
  ERROR: org.eclipse.equinox.p2.director code=0 Software being installed: artificial_root 1.0.0.v1553268619475
  ERROR: org.eclipse.equinox.p2.director code=1 Only one of the following can be installed at once: 
    ERROR: org.eclipse.equinox.p2.director code=0 Object Teams Development Tooling Core 3.17.0.OTDT_r273_201903120955 (org.eclipse.jdt.core 3.17.0.OTDT_r273_201903120955)
    ERROR: org.eclipse.equinox.p2.director code=0 Java Development Tools Core 3.14.0.xx-201903212139-e48 (org.eclipse.jdt.core 3.14.0.xx-201903212139-e48)
    ERROR: org.eclipse.equinox.p2.director code=0 Java Development Tools Core 3.17.0.v20190306-2240 (org.eclipse.jdt.core 3.17.0.v20190306-2240)
    ERROR: org.eclipse.equinox.p2.director code=0 Java Development Tools Core 3.14.0.v20180528-0519 (org.eclipse.jdt.core 3.14.0.v20180528-0519)
    ERROR: org.eclipse.equinox.p2.director code=0 Object Teams Development Tooling Core 3.14.0.OTDT_r270_201806120901 (org.eclipse.jdt.core 3.14.0.OTDT_r270_201806120901)
  ERROR: org.eclipse.equinox.p2.director code=1 Only one of the following can be installed at once: 
    ERROR: org.eclipse.equinox.p2.director code=0 Log View 1.2.200.v20180512-1206 (org.eclipse.ui.views.log 1.2.200.v20180512-1206)
    ERROR: org.eclipse.equinox.p2.director code=0 Log View 1.2.500.v20190218-0617 (org.eclipse.ui.views.log 1.2.500.v20190218-0617)
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: artificial_root 1.0.0.v1553268619475
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.codehaus.groovy.eclipse.feature.feature.group 0.0.0
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: artificial_root 1.0.0.v1553268619475
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.eclipse.pde.feature.group 0.0.0
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: artificial_root 1.0.0.v1553268619475
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.eclipse.platform.feature.group [4.11.0,5.0.0)
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: Groovy-Eclipse Compilerless feature 3.3.0.xx-201903212139-e48 (org.codehaus.groovy.compilerless.feature.feature.group 3.3.0.xx-201903212139-e48)
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.codehaus.groovy.headless.feature.feature.group [3.3.0.xx-201903212139-e48,3.3.0.xx-201903212139-e48]
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: Eclipse Groovy Development Tools 3.3.0.xx-201903212139-e48 (org.codehaus.groovy.eclipse.feature.feature.group 3.3.0.xx-201903212139-e48)
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.codehaus.groovy.compilerless.feature.feature.group [3.3.0.xx-201903212139-e48,3.3.0.xx-201903212139-e48]
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: Groovy-Eclipse Headless feature 3.3.0.xx-201903212139-e48 (org.codehaus.groovy.headless.feature.feature.group 3.3.0.xx-201903212139-e48)
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.codehaus.groovy.jdt.patch.feature.group [3.3.0.xx-201903212139-e48,3.3.0.xx-201903212139-e48]
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: JDI Debug UI 3.10.200.v20190226-0733 (org.eclipse.jdt.debug.ui 3.10.200.v20190226-0733)
    ERROR: org.eclipse.equinox.p2.director code=0 To: osgi.bundle; org.eclipse.jdt.core [3.15.0,4.0.0)
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: Eclipse Java Development Tools 3.17.0.v20190307-0500 (org.eclipse.jdt.feature.group 3.17.0.v20190307-0500)
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.eclipse.jdt.debug.ui [3.10.200.v20190226-0733,3.10.200.v20190226-0733]
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: Eclipse Plug-in Development Environment 3.13.100.v20180611-0826 (org.eclipse.pde.feature.group 3.13.100.v20180611-0826)
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.eclipse.ui.views.log [1.2.200.v20180512-1206,1.2.200.v20180512-1206]
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: Eclipse Plug-in Development Environment 3.13.400.v20190307-0943 (org.eclipse.pde.feature.group 3.13.400.v20190307-0943)
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.eclipse.jdt.feature.group [3.15.0,4.0.0)
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: Eclipse Platform 4.11.0.v20190307-0500 (org.eclipse.platform.feature.group 4.11.0.v20190307-0500)
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.eclipse.ui.views.log [1.2.500.v20190218-0617,1.2.500.v20190218-0617]
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From Patch: org.codehaus.groovy.jdt.patch.feature.group 3.3.0.xx-201903212139-e48 Eclipse Java Development Tools 3.17.0.v20190307-0500 (org.eclipse.jdt.feature.group 3.17.0.v20190307-0500)
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.eclipse.jdt.core [3.14.0.xx-201903212139-e48,3.14.0.xx-201903212139-e48]
```

Host System: Ubuntu 16.04
Apache Maven 3.3.9
OpenJDK-8 8u191-b12-2ubuntu0.16.04.1

**Comment by openhab-5iver** [comment]
Take a look at the link in #6883. The openHAB project reintegrated ESH into [openhab-core](https://github.com/openhab/openhab-core) and have continued development.

**Comment by stack-head** [comment]
Got it, thanks for the fast reply.  My oversight, will close issue.
