### ISSUE TITLE
Error in Eclipse IDE Installer with SmartHome-Runtime (for Eclipse SmartHome)

### ISSUE THREAD

**Issue by sidshinde19** [eclipse/smarthome#6910]
I am trying to install Eclipse IDE as per instructions given on Eclipse SmartHome web page for installing Eclipse IDE with SmartHome - Runtime Projects.

I have tried many times but am reveiving the following error:

Executing bootstrap tasks
Java(TM) SE Runtime Environment 1.8.0_151-b12
Product org.eclipse.products.epp.package.java.latest.released
Workspace C:\Users\User\smarthome-master\ws
Project org.eclipse.smarthome.core.master
Bundle org.eclipse.oomph.setup 1.14.0.v20190815-1111, build=4192, branch=1f649f65846dda3c4acf662cfece78df8bdb18d1
Bundle org.eclipse.oomph.setup.core 1.14.0.v20190705-1542, build=4192, branch=1f649f65846dda3c4acf662cfece78df8bdb18d1
Bundle org.eclipse.oomph.setup.installer 1.14.0.v20190823-0726, build=4192, branch=1f649f65846dda3c4acf662cfece78df8bdb18d1
Bundle org.eclipse.oomph.setup.p2 1.12.0.v20190704-1252, build=4192, branch=1f649f65846dda3c4acf662cfece78df8bdb18d1
Performing Workspace C:\Users\User\smarthome-master\ws
Performing P2 Director (Eclipse IDE for Java Developers (2019-06))
Offline = false
Mirrors = true
Resolving 40 requirements from 5 repositories to C:\Users\User\smarthome-master\eclipse
Requirement org.eclipse.wst.xml_ui.feature.feature.group
Requirement org.eclipse.m2e.feature.feature.group
Requirement org.eclipse.m2e.logback.feature.feature.group
Requirement org.eclipse.xtend.sdk.feature.group [2.14.0,2.15.0)
Requirement org.eclipse.xtext.sdk.feature.group [2.14.0,2.15.0)
Requirement org.eclipse.emf.mwe2.language.sdk.feature.group [2.9.1,2.10.0)
Requirement org.eclipse.emf.mwe2.runtime.sdk.feature.group [2.9.1,2.10.0)
Requirement org.codehaus.groovy.eclipse.feature.feature.group
Requirement org.eclipse.emf.sdk.feature.group
Requirement org.eclipse.mylyn.java_feature.feature.group
Requirement org.eclipse.mylyn.bugzilla_feature.feature.group
Requirement org.eclipse.mylyn.hudson.feature.group
Requirement org.eclipse.mylyn.git.feature.group
Requirement org.eclipse.pde.feature.group
Requirement org.eclipse.wst.jsdt.feature.feature.group
Requirement org.eclipse.wst.web_ui.feature.feature.group
Requirement epp.package.java [4.12.0,5.0.0)
Requirement org.eclipse.platform.feature.group [4.12.0,5.0.0)
Requirement org.eclipse.rcp.feature.group [4.12.0,5.0.0)
Requirement org.eclipse.buildship.feature.group
Requirement org.eclipse.eclemma.feature.feature.group
Requirement org.eclipse.egit.feature.group
Requirement org.eclipse.egit.mylyn.feature.group
Requirement org.eclipse.epp.mpc.feature.group
Requirement org.eclipse.jdt.feature.group
Requirement org.eclipse.jgit.feature.group
Requirement org.eclipse.mylyn.context_feature.feature.group
Requirement org.eclipse.mylyn.ide_feature.feature.group
Requirement org.eclipse.mylyn.wikitext_feature.feature.group
Requirement org.eclipse.mylyn_feature.feature.group
Requirement org.eclipse.tips.feature.feature.group
Requirement org.eclipse.oomph.setup.feature.group
Requirement org.eclipse.oomph.targlets.feature.group
Requirement org.eclipse.oomph.setup.targlets.feature.group
Requirement org.eclipse.oomph.setup.pde.feature.group
Requirement org.eclipse.oomph.setup.jdt.feature.group
Requirement org.eclipse.oomph.setup.git.feature.group
Requirement org.eclipse.oomph.setup.workingsets.feature.group
Requirement org.eclipse.oomph.setup.projects.feature.group
Requirement org.eclipse.oomph.setup.launching.feature.group
Repository http://dist.springsource.org/snapshot/GRECLIPSE/e4.8
Repository http://download.eclipse.org/releases/photon
Repository http://download.eclipse.org/technology/epp/packages/2019-06
Repository http://download.eclipse.org/releases/2019-06/201906191000
Repository http://download.eclipse.org/oomph/updates/milestone/latest
Fetching p2.index from http://download.eclipse.org/releases/photon/
Adding repository http://dist.springsource.org/snapshot/GRECLIPSE/e4.8
Adding repository http://download.eclipse.org/oomph/updates/milestone/latest
Fetching p2.index from http://download.eclipse.org/technology/epp/packages/2019-06/
Fetching p2.index from http://download.eclipse.org/releases/2019-06/201906191000/
Fetching p2.index from http://download.eclipse.org/releases/photon/
Fetching p2.index from http://download.eclipse.org/technology/epp/packages/2019-06/
Fetching p2.index from http://download.eclipse.org/releases/2019-06/201906191000/
Adding repository http://download.eclipse.org/releases/photon
Adding repository http://download.eclipse.org/releases/2019-06/201906191000
Adding repository http://download.eclipse.org/technology/epp/packages/2019-06
Fetching content.jar from http://dist.springsource.org/snapshot/GRECLIPSE/e4.8/ (13.62kB)
Fetching compositeContent.jar from http://download.eclipse.org/releases/photon/ (490B)
Fetching content.xml.xz from http://download.eclipse.org/technology/epp/packages/2019-06/
Fetching compositeContent.jar from http://download.eclipse.org/releases/photon/ (490B)
Fetching content.xml.xz from http://download.eclipse.org/releases/2019-06/201906191000/
Fetching content.xml.xz from http://download.eclipse.org/technology/epp/packages/2019-06/
Fetching content.xml.xz from http://download.eclipse.org/releases/2019-06/201906191000/
Fetching p2.index from http://download.eclipse.org/technology/epp/packages/photon/
Fetching compositeContent.jar from http://download.eclipse.org/oomph/updates/milestone/latest/ (440B)
Fetching content.xml.xz from http://download.eclipse.org/releases/2019-06/201906191000/
Fetching content.xml.xz from http://download.eclipse.org/technology/epp/packages/photon/
Fetching p2.index from http://download.eclipse.org/releases/photon/201806271001/
Fetching content.jar from http://download.eclipse.org/oomph/drops/milestone/S20190828-040519-1.14.0-M3/ (57.49kB)
Fetching p2.index from http://download.eclipse.org/releases/photon/201806271001/
Fetching content.jar from http://download.eclipse.org/oomph/drops/milestone/S20190828-040519-1.14.0-M3/ (57.49kB)
Fetching content.xml.xz from http://download.eclipse.org/releases/photon/201806271001/
Calculating requirements and dependencies.
**Cannot complete the request.  Generating details.
ERROR: org.eclipse.equinox.p2.director code=10054 Cannot complete the install because of a conflicting dependency.
  at org.eclipse.oomph.util.OomphPlugin.coreException(OomphPlugin.java:280)
  at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl.resolve(ProfileTransactionImpl.java:425)
  at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl.commit(ProfileTransactionImpl.java:337)
  at org.eclipse.oomph.setup.p2.impl.P2TaskImpl.perform(P2TaskImpl.java:758)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3824)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3752)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3733)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3626)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:582)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:708)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
  ERROR: org.eclipse.equinox.p2.director code=0 Software being installed: artificial_root 1.0.0.v1567243289756
  ERROR: org.eclipse.equinox.p2.director code=1 Only one of the following can be installed at once: 
    ERROR: org.eclipse.equinox.p2.director code=0 Java Development Tools Core 3.14.0.v20180528-0519 (org.eclipse.jdt.core 3.14.0.v20180528-0519)
    ERROR: org.eclipse.equinox.p2.director code=0 Java Development Tools Core 3.18.0.v20190522-0428 (org.eclipse.jdt.core 3.18.0.v20190522-0428)
    ERROR: org.eclipse.equinox.p2.director code=0 Java Development Tools Core 3.14.0.v201908301754-e48 (org.eclipse.jdt.core 3.14.0.v201908301754-e48)
    ERROR: org.eclipse.equinox.p2.director code=0 Object Teams Development Tooling Core 3.14.0.OTDT_r270_201806120901 (org.eclipse.jdt.core 3.14.0.OTDT_r270_201806120901)
    ERROR: org.eclipse.equinox.p2.director code=0 Object Teams Development Tooling Core 3.18.0.OTDT_r274_201906101736 (org.eclipse.jdt.core 3.18.0.OTDT_r274_201906101736)
  ERROR: org.eclipse.equinox.p2.director code=1 Only one of the following can be installed at once: 
    ERROR: org.eclipse.equinox.p2.director code=0 Log View 1.2.200.v20180512-1206 (org.eclipse.ui.views.log 1.2.200.v20180512-1206)
    ERROR: org.eclipse.equinox.p2.director code=0 Log View 1.2.600.v20190519-1034 (org.eclipse.ui.views.log 1.2.600.v20190519-1034)
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: artificial_root 1.0.0.v1567243289756
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.codehaus.groovy.eclipse.feature.feature.group 0.0.0
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: artificial_root 1.0.0.v1567243289756
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.eclipse.pde.feature.group 0.0.0
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: artificial_root 1.0.0.v1567243289756
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.eclipse.platform.feature.group [4.12.0,5.0.0)
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: Groovy-Eclipse Compilerless feature 3.5.0.v201908301754-e48 (org.codehaus.groovy.compilerless.feature.feature.group 3.5.0.v201908301754-e48)
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.codehaus.groovy.headless.feature.feature.group [3.5.0.v201908301754-e48,3.5.0.v201908301754-e48]
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: Eclipse Groovy Development Tools 3.5.0.v201908301754-e48 (org.codehaus.groovy.eclipse.feature.feature.group 3.5.0.v201908301754-e48)
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.codehaus.groovy.compilerless.feature.feature.group [3.5.0.v201908301754-e48,3.5.0.v201908301754-e48]
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: Groovy-Eclipse Headless feature 3.5.0.v201908301754-e48 (org.codehaus.groovy.headless.feature.feature.group 3.5.0.v201908301754-e48)
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.codehaus.groovy.jdt.patch.feature.group [3.5.0.v201908301754-e48,3.5.0.v201908301754-e48]
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: Eclipse Java Development Tools 3.18.0.v20190605-1800 (org.eclipse.jdt.feature.group 3.18.0.v20190605-1800)
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.eclipse.jdt.ui [3.18.0.v20190601-2139,3.18.0.v20190601-2139]
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: Java Development Tools UI 3.18.0.v20190601-2139 (org.eclipse.jdt.ui 3.18.0.v20190601-2139)
    ERROR: org.eclipse.equinox.p2.director code=0 To: osgi.bundle; org.eclipse.jdt.core [3.18.0,4.0.0)
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: Eclipse Plug-in Development Environment 3.13.100.v20180611-0826 (org.eclipse.pde.feature.group 3.13.100.v20180611-0826)
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.eclipse.ui.views.log [1.2.200.v20180512-1206,1.2.200.v20180512-1206]
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: Eclipse Plug-in Development Environment 3.14.0.v20190605-1800 (org.eclipse.pde.feature.group 3.14.0.v20190605-1800)
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.eclipse.jdt.feature.group [3.15.0,4.0.0)
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: Eclipse Platform 4.12.0.v20190605-1801 (org.eclipse.platform.feature.group 4.12.0.v20190605-1801)
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.eclipse.ui.views.log [1.2.600.v20190519-1034,1.2.600.v20190519-1034]
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From Patch: org.codehaus.groovy.jdt.patch.feature.group 3.5.0.v201908301754-e48 Eclipse Java Development Tools 3.18.0.v20190605-1800 (org.eclipse.jdt.feature.group 3.18.0.v20190605-1800)
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.eclipse.jdt.core [3.14.0.v201908301754-e48,3.14.0.v201908301754-e48]**

Took 15 seconds.
There are failed tasks.
Press Back to choose different settings or Cancel to abort.

I dont get this error if I dont select the SmartHome - Runtime project and am able to install the IDE with default settings.

Once while installing I had also received  an error dialogue saying "The following URl could not be downloaded: http://download.eclipse.org/oomph/drops/milestone/S20190828-040519-1.14.0-M3/"

Has anyone else received such an error and solved it? Is there a way around in which I could add the project repositories after I install the IDE with default settings?

**Comment by martinfogarty** [comment]
I am experiencing exactly the same problem as you. I have tried on two separate windows machines with the identical result.

**Comment by martinfogarty** [comment]
Is there any chance we can get some support on this? It is very difficult to be an advocate for ESH when the getting started instructions don't work! This is not the first time I have encountered problems like this when carrying out a "clean install" on a new machine.

**Comment by martinfogarty** [comment]
This is what I see: 

Executing bootstrap tasks
Java(TM) SE Runtime Environment 1.8.0_221-b11
Product org.eclipse.products.epp.package.java.latest.released
Workspace C:\Users\Martin\smarthome-master\ws
Project org.eclipse.smarthome.core.master
Bundle org.eclipse.oomph.setup 1.14.0.v20190815-1111, build=4222, branch=df1f9db2f1c3e575486f818cae17bfd35a376162
Bundle org.eclipse.oomph.setup.core 1.14.0.v20190705-1542, build=4222, branch=df1f9db2f1c3e575486f818cae17bfd35a376162
Bundle org.eclipse.oomph.setup.installer 1.14.0.v20190823-0726, build=4222, branch=df1f9db2f1c3e575486f818cae17bfd35a376162
Bundle org.eclipse.oomph.setup.p2 1.12.0.v20190704-1252, build=4222, branch=df1f9db2f1c3e575486f818cae17bfd35a376162
Performing Workspace C:\Users\Martin\smarthome-master\ws
Performing P2 Director (Eclipse IDE for Java Developers (2019-09))
Offline = false
Mirrors = true
Resolving 40 requirements from 5 repositories to C:\Users\Martin\smarthome-master\eclipse
Requirement org.eclipse.wst.xml_ui.feature.feature.group
Requirement org.eclipse.m2e.feature.feature.group
Requirement org.eclipse.m2e.logback.feature.feature.group
Requirement org.eclipse.xtend.sdk.feature.group [2.14.0,2.15.0)
Requirement org.eclipse.xtext.sdk.feature.group [2.14.0,2.15.0)
Requirement org.eclipse.emf.mwe2.language.sdk.feature.group [2.9.1,2.10.0)
Requirement org.eclipse.emf.mwe2.runtime.sdk.feature.group [2.9.1,2.10.0)
Requirement org.codehaus.groovy.eclipse.feature.feature.group
Requirement org.eclipse.emf.sdk.feature.group
Requirement org.eclipse.mylyn.java_feature.feature.group
Requirement org.eclipse.mylyn.bugzilla_feature.feature.group
Requirement org.eclipse.mylyn.hudson.feature.group
Requirement org.eclipse.mylyn.git.feature.group
Requirement org.eclipse.pde.feature.group
Requirement org.eclipse.wst.jsdt.feature.feature.group
Requirement org.eclipse.wst.web_ui.feature.feature.group
Requirement epp.package.java [4.13.0,5.0.0)
Requirement org.eclipse.platform.feature.group [4.13.0,5.0.0)
Requirement org.eclipse.rcp.feature.group [4.13.0,5.0.0)
Requirement org.eclipse.buildship.feature.group
Requirement org.eclipse.eclemma.feature.feature.group
Requirement org.eclipse.egit.feature.group
Requirement org.eclipse.egit.mylyn.feature.group
Requirement org.eclipse.epp.mpc.feature.group
Requirement org.eclipse.jdt.feature.group
Requirement org.eclipse.jgit.feature.group
Requirement org.eclipse.mylyn.context_feature.feature.group
Requirement org.eclipse.mylyn.ide_feature.feature.group
Requirement org.eclipse.mylyn.wikitext_feature.feature.group
Requirement org.eclipse.mylyn_feature.feature.group
Requirement org.eclipse.tips.feature.feature.group
Requirement org.eclipse.oomph.setup.feature.group
Requirement org.eclipse.oomph.targlets.feature.group
Requirement org.eclipse.oomph.setup.targlets.feature.group
Requirement org.eclipse.oomph.setup.pde.feature.group
Requirement org.eclipse.oomph.setup.jdt.feature.group
Requirement org.eclipse.oomph.setup.git.feature.group
Requirement org.eclipse.oomph.setup.workingsets.feature.group
Requirement org.eclipse.oomph.setup.projects.feature.group
Requirement org.eclipse.oomph.setup.launching.feature.group
Repository http://dist.springsource.org/snapshot/GRECLIPSE/e4.8
Repository http://download.eclipse.org/releases/photon
Repository http://download.eclipse.org/technology/epp/packages/2019-09
Repository http://download.eclipse.org/releases/2019-09/201909181001
Repository http://download.eclipse.org/oomph/updates/milestone/latest
Fetching p2.index from http://download.eclipse.org/releases/photon/
Adding repository http://download.eclipse.org/oomph/updates/milestone/latest
Fetching p2.index from http://download.eclipse.org/releases/2019-09/201909181001/
Fetching p2.index from http://download.eclipse.org/technology/epp/packages/2019-09/
Fetching p2.index from http://download.eclipse.org/releases/2019-09/201909181001/
Adding repository http://dist.springsource.org/snapshot/GRECLIPSE/e4.8
Adding repository http://download.eclipse.org/releases/2019-09/201909181001
Fetching content.jar from http://dist.springsource.org/snapshot/GRECLIPSE/e4.8/ (13.19kB)
Adding repository http://download.eclipse.org/technology/epp/packages/2019-09
Adding repository http://download.eclipse.org/releases/photon
Fetching compositeContent.jar from http://download.eclipse.org/releases/photon/ (490B)
Fetching content.xml.xz from http://download.eclipse.org/releases/2019-09/201909181001/
Fetching content.xml.xz from http://download.eclipse.org/technology/epp/packages/2019-09/
Fetching p2.index from http://download.eclipse.org/technology/epp/packages/photon/
Fetching compositeContent.jar from http://download.eclipse.org/oomph/updates/milestone/latest/ (440B)
Fetching content.xml.xz from http://download.eclipse.org/technology/epp/packages/photon/
Fetching content.xml.xz from http://download.eclipse.org/releases/2019-09/201909181001/
Fetching p2.index from http://download.eclipse.org/releases/photon/201806271001/
Fetching content.jar from http://download.eclipse.org/oomph/drops/milestone/S20190531-082923-1.13.0-M4/ (57.03kB)
Fetching content.xml.xz from http://download.eclipse.org/releases/photon/201806271001/
Calculating requirements and dependencies.
Cannot complete the request.  Generating details.
ERROR: org.eclipse.equinox.p2.director code=10054 Cannot complete the install because of a conflicting dependency.
  at org.eclipse.oomph.util.OomphPlugin.coreException(OomphPlugin.java:280)
  at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl.resolve(ProfileTransactionImpl.java:425)
  at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl.commit(ProfileTransactionImpl.java:337)
  at org.eclipse.oomph.setup.p2.impl.P2TaskImpl.perform(P2TaskImpl.java:758)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3824)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3752)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3733)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3626)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:582)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:708)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
  ERROR: org.eclipse.equinox.p2.director code=0 Software being installed: artificial_root 1.0.0.v1569576828049
  ERROR: org.eclipse.equinox.p2.director code=1 Only one of the following can be installed at once: 
    ERROR: org.eclipse.equinox.p2.director code=0 Java Development Tools Core 3.14.0.v20180528-0519 (org.eclipse.jdt.core 3.14.0.v20180528-0519)
    ERROR: org.eclipse.equinox.p2.director code=0 Object Teams Development Tooling Core 3.19.0.OTDT_r275_201909081329 (org.eclipse.jdt.core 3.19.0.OTDT_r275_201909081329)
    ERROR: org.eclipse.equinox.p2.director code=0 Java Development Tools Core 3.14.0.v201909251921-e48 (org.eclipse.jdt.core 3.14.0.v201909251921-e48)
    ERROR: org.eclipse.equinox.p2.director code=0 Object Teams Development Tooling Core 3.14.0.OTDT_r270_201806120901 (org.eclipse.jdt.core 3.14.0.OTDT_r270_201806120901)
    ERROR: org.eclipse.equinox.p2.director code=0 Java Development Tools Core 3.19.0.v20190903-0936 (org.eclipse.jdt.core 3.19.0.v20190903-0936)
  ERROR: org.eclipse.equinox.p2.director code=1 Only one of the following can be installed at once: 
    ERROR: org.eclipse.equinox.p2.director code=0 Log View 1.2.200.v20180512-1206 (org.eclipse.ui.views.log 1.2.200.v20180512-1206)
    ERROR: org.eclipse.equinox.p2.director code=0 Log View 1.2.700.v20190819-1015 (org.eclipse.ui.views.log 1.2.700.v20190819-1015)
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: artificial_root 1.0.0.v1569576828049
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.codehaus.groovy.eclipse.feature.feature.group 0.0.0
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: artificial_root 1.0.0.v1569576828049
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.eclipse.pde.feature.group 0.0.0
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: artificial_root 1.0.0.v1569576828049
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.eclipse.platform.feature.group [4.13.0,5.0.0)
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: Groovy-Eclipse Compilerless feature 3.5.0.v201909251921-e48 (org.codehaus.groovy.compilerless.feature.feature.group 3.5.0.v201909251921-e48)
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.codehaus.groovy.headless.feature.feature.group [3.5.0.v201909251921-e48,3.5.0.v201909251921-e48]
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: Eclipse Groovy Development Tools 3.5.0.v201909251921-e48 (org.codehaus.groovy.eclipse.feature.feature.group 3.5.0.v201909251921-e48)
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.codehaus.groovy.compilerless.feature.feature.group [3.5.0.v201909251921-e48,3.5.0.v201909251921-e48]
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: Groovy-Eclipse Headless feature 3.5.0.v201909251921-e48 (org.codehaus.groovy.headless.feature.feature.group 3.5.0.v201909251921-e48)
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.codehaus.groovy.jdt.patch.feature.group [3.5.0.v201909251921-e48,3.5.0.v201909251921-e48]
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: Eclipse Java Development Tools 3.18.100.v20190916-1045 (org.eclipse.jdt.feature.group 3.18.100.v20190916-1045)
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.eclipse.jdt.junit [3.11.500.v20190809-1613,3.11.500.v20190809-1613]
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: Java Development Tools JUnit support 3.11.500.v20190809-1613 (org.eclipse.jdt.junit 3.11.500.v20190809-1613)
    ERROR: org.eclipse.equinox.p2.director code=0 To: osgi.bundle; org.eclipse.jdt.core [3.18.0,4.0.0)
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: Eclipse Plug-in Development Environment 3.13.100.v20180611-0826 (org.eclipse.pde.feature.group 3.13.100.v20180611-0826)
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.eclipse.ui.views.log [1.2.200.v20180512-1206,1.2.200.v20180512-1206]
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: Eclipse Plug-in Development Environment 3.14.100.v20190916-1045 (org.eclipse.pde.feature.group 3.14.100.v20190916-1045)
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.eclipse.jdt.feature.group [3.15.0,4.0.0)
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: Eclipse Platform 4.13.0.v20190916-1323 (org.eclipse.platform.feature.group 4.13.0.v20190916-1323)
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.eclipse.ui.views.log [1.2.700.v20190819-1015,1.2.700.v20190819-1015]
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From Patch: org.codehaus.groovy.jdt.patch.feature.group 3.5.0.v201909251921-e48 Eclipse Java Development Tools 3.18.100.v20190916-1045 (org.eclipse.jdt.feature.group 3.18.100.v20190916-1045)
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.eclipse.jdt.core [3.14.0.v201909251921-e48,3.14.0.v201909251921-e48]

Took 6 seconds.
There are failed tasks.
Press Back to choose different settings or Cancel to abort.

**Comment by martinfogarty** [comment]
The install works if you select Proton as the Eclipse release rather than the latest which is the default.

**Comment by Hilbrand** [comment]
> Is there any chance we can get some support on this? It is very difficult to be an advocate for ESH when the getting started instructions don't work!

@sidshinde19  @martinfogarty In case you haven't noticed. But ESH is not being actively developed anymore. Continued development has been reintegrated back into openHAB. See also  https://github.com/eclipse/smarthome/pull/6883

**Comment by martinfogarty** [comment]
Thanks for the response. Shouldn't something be put on the main page https://www.eclipse.org/smarthome/  or the developer guide https://www.eclipse.org/smarthome/getting-started.html#developers to indicate this? Or maybe here https://github.com/eclipse/smarthome ?
