### ISSUE TITLE
Concurrent Modification Error

### ISSUE THREAD

**Issue by digitaldan** [eclipse/smarthome#820]
During startup I received this error, it's only happened once so its' probably hard to reproduce.

```
ENTRY org.eclipse.equinox.cm 4 0 2016-01-04 07:49:19.313
!MESSAGE 
!STACK 0
java.util.ConcurrentModificationException
    at org.eclipse.emf.common.util.AbstractEList$EIterator.checkModCount(AbstractEList.java:758)
    at org.eclipse.emf.common.util.AbstractEList$EIterator.doNext(AbstractEList.java:706)
    at org.eclipse.emf.common.util.AbstractEList$EIterator.next(AbstractEList.java:692)
    at org.eclipse.xtext.resource.SynchronizedXtextResourceSet$1$SynchronizedEIterator.next(SynchronizedXtextResourceSet.java:171)
    at org.eclipse.xtext.resource.SynchronizedXtextResourceSet$1$SynchronizedEIterator.next(SynchronizedXtextResourceSet.java:1)
    at com.google.common.collect.Iterators$7.computeNext(Iterators.java:644)
    at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
    at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
    at com.google.common.collect.Iterators$8.hasNext(Iterators.java:777)
    at com.google.common.collect.Lists.newArrayList(Lists.java:138)
    at com.google.common.collect.Lists.newArrayList(Lists.java:119)
    at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.getAllModelNamesOfType(ModelRepositoryImpl.java:156)
    at org.eclipse.smarthome.model.item.internal.GenericItemProvider.getAll(GenericItemProvider.java:123)
    at org.eclipse.smarthome.core.internal.items.ItemRegistryImpl.allItemsChanged(ItemRegistryImpl.java:74)
    at org.eclipse.smarthome.model.item.internal.GenericItemProvider.modelChanged(GenericItemProvider.java:399)
    at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.notifyListeners(ModelRepositoryImpl.java:200)
    at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.addOrRefreshModel(ModelRepositoryImpl.java:97)
    at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.checkFile(FolderObserver.java:240)
    at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.notifyUpdateToModelRepo(FolderObserver.java:169)
    at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.updated(FolderObserver.java:150)
    at org.eclipse.equinox.internal.cm.ManagedServiceTracker$1.run(ManagedServiceTracker.java:276)
    at org.eclipse.equinox.internal.cm.SerializedTaskQueue$1.run(SerializedTaskQueue.java:36)
```

**Comment by maggu2810** [comment]
Which JVM are you using?

**Comment by maggu2810** [comment]
I reported this already some time ago:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=479215

Are you using OpenJDK or the Oracle one?

**Comment by kaikreuzer** [comment]
I also saw this once today using Oracle JDK.

**Comment by digitaldan** [comment]
Oracle 8 on OS X

**Comment by maggu2810** [comment]
Add cross-reverence: eclipse/smarthome#502

**Comment by triller-telekom** [comment]
By looking at the function `org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.getAllModelNamesOfType(ModelRepositoryImpl.java` I see that @maggu2810 has cloned the list in a commit on 18.04.2016, see:

https://github.com/eclipse/smarthome/blob/master/bundles/model/org.eclipse.smarthome.model.core/src/main/java/org/eclipse/smarthome/model/core/internal/ModelRepositoryImpl.java#L168

@maggu2810 Since you also replied to this issue on that day, is there a reason why you didn`t close this issue?

**Comment by maggu2810** [comment]
> is there a reason why you didn`t close this issue?

I don't know anymore :wink:
I close it now.
