### ISSUE TITLE
Missing import in org.eclipse.smarthome.core

### ISSUE THREAD

**Issue by Tavalin** [eclipse/smarthome#836]
Received the following error and call stack:
```
Exception in thread "Squeeze Server Listener" java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
        at org.eclipse.smarthome.core.library.types.RawType.toString(RawType.java:46)
        at org.eclipse.smarthome.core.items.events.ItemEventFactory.createStateEvent(ItemEventFactory.java:219)
        at org.eclipse.smarthome.core.thing.internal.ThingManager$1.stateUpdated(ThingManager.java:139)
        at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.updateState(BaseThingHandler.java:270)
        at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.updateState(BaseThingHandler.java:291)
        at org.openhab.binding.squeezebox.handler.SqueezeBoxPlayerHandler.updateChannel(SqueezeBoxPlayerHandler.java:373)
        at org.openhab.binding.squeezebox.handler.SqueezeBoxPlayerHandler.coverArtChangeEvent(SqueezeBoxPlayerHandler.java:334)
        at org.openhab.binding.squeezebox.handler.SqueezeBoxServerHandler$SqueezeServerListener$17.updateListener(SqueezeBoxServerHandler.java:698)
        at org.openhab.binding.squeezebox.handler.SqueezeBoxServerHandler.updatePlayer(SqueezeBoxServerHandler.java:793)
        at org.openhab.binding.squeezebox.handler.SqueezeBoxServerHandler.access$7(SqueezeBoxServerHandler.java:776)
        at org.openhab.binding.squeezebox.handler.SqueezeBoxServerHandler$SqueezeServerListener.handleStatusMessage(SqueezeBoxServerHandler.java:694)
        at org.openhab.binding.squeezebox.handler.SqueezeBoxServerHandler$SqueezeServerListener.handlePlayerUpdate(SqueezeBoxServerHandler.java:472)
        at org.openhab.binding.squeezebox.handler.SqueezeBoxServerHandler$SqueezeServerListener.run(SqueezeBoxServerHandler.java:370)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter cannot be found by org.eclipse.smarthome.core_0.8.0.201601082233
        at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:432)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:345)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:337)
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 13 more
```

**Comment by Tavalin** [comment]
PR https://github.com/eclipse/smarthome/pull/837 raised.
