### ISSUE TITLE
Could not send Wemo device discovery java.net.BindException: Cannot assign requested address

### ISSUE THREAD

**Issue by carpenike** [eclipse/smarthome#838]
Hello all,

I reported this issue on the OH2 board (https://github.com/openhab/openhab-distro/issues/61) and they asked me to report it over here. Fresh install of OH2-Distro which was released yesterday and this comes up on every boot. I don't use WEMO so it's not a huge issue for me, just an annoyance in the logs.

Current System:

```
[_openhab@ha ~]$ cat /etc/redhat-release
CentOS Linux release 7.2.1511 (Core)

[_openhab@ha ~]$ java -version
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)
```

Logs:

```
13:08:19.149 [ERROR] [.wemo.discovery.WemoDiscoveryService] - Could not send Wemo device discovery
java.net.BindException: Cannot assign requested address
        at java.net.PlainDatagramSocketImpl.bind0(Native Method)[:1.8.0_65]
        at java.net.AbstractPlainDatagramSocketImpl.bind(AbstractPlainDatagramSocketImpl.java:94)[:1.8.0_65]
        at java.net.DatagramSocket.bind(DatagramSocket.java:392)[:1.8.0_65]
        at org.eclipse.smarthome.binding.wemo.discovery.WemoDiscoveryService.sendWemoDiscoveryMessage(WemoDiscoveryService.java:152)[145:org.eclipse.smarthome.binding.wemo:0.8.0.201601082233]
        at org.eclipse.smarthome.binding.wemo.discovery.WemoDiscoveryService.discoverWemo(WemoDiscoveryService.java:120)[145:org.eclipse.smarthome.binding.wemo:0.8.0.201601082233]
        at org.eclipse.smarthome.binding.wemo.discovery.WemoDiscoveryService.access$0(WemoDiscoveryService.java:118)[145:org.eclipse.smarthome.binding.wemo:0.8.0.201601082233]
        at org.eclipse.smarthome.binding.wemo.discovery.WemoDiscoveryService$1.run(WemoDiscoveryService.java:79)[145:org.eclipse.smarthome.binding.wemo:0.8.0.201601082233]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_65]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)[:1.8.0_65]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)[:1.8.0_65]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)[:1.8.0_65]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_65]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_65]
        at java.lang.Thread.run(Thread.java:745)[:1.8.0_65]
```

Thanks,
Ryan

**Comment by kaikreuzer** [comment]
@hmerk Could you have a look, please?

**Comment by hmerk** [comment]
@kaikreuzer 
This belongs to the old, non UPnP discovery, where we do our own SSDP discovery. The strange thing is, that I never got this errors in my environment, so a cannot reproduce locally.
We should push to move to the new binding version which will not have that discovery method any longer and this error will not occur any more.

**Comment by kaikreuzer** [comment]
Ok, makes sense, thanks.
So FTR: This issue will be automatically solved by https://github.com/eclipse/smarthome/pull/721
