### ISSUE TITLE
Hue binding: dimmer and switch items for brightness should move together

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#866]
For a Philips Living Colors Bloom light, I linked manually the brightness channel to a switch item and to a dimmer item.
When I set the dimmer to 0 (using the UI), the switch is not switch OFF and remains ON.
PS: note that it works well in openHAB 1.x.

**Comment by kaikreuzer** [comment]
Please state what UI you are using.
Also, please check if this is related to the hue binding (what your title suggest) or if this is also an issue if you do not have any link on your item.

**Comment by lolodomo** [comment]
I was using HABdroid.

**Comment by lolodomo** [comment]
I can see similar problem in Classic UI. If I use the color channel and the color picker to set brightness to 0, the switch linked to the brightness channel is not updated.
Maybe it is due to the fact that I should definitely not use the brightness channel for my hue lights ? You explained in another issue that I should use only Color channel even for playing with the brightness.
But why is there is brightness channel documented in this case and apparently even working with my lights ?

**Comment by kaikreuzer** [comment]
> But why is there is brightness channel documented

Could you please give me a reference? I am not aware of any brightness channels for color lights...

**Comment by lolodomo** [comment]
You're right on one point, I was able to define only one Color item and link it to the color channel.
```
Color LampeTeleviseurColor "Couleur Lampe TV"
```
Then I was able in my sitemap to use different elements for this item:
```
		Text label="Philips Hue" {
			Switch item=LampeTeleviseurColor
			Slider item=LampeTeleviseurColor
			Colorpicker item=LampeTeleviseurColor
		}
```
Doing that I was able to use the switch, the slider for brightness and the color picker.
But all this is buggy because iut seems there is no link between each of these controls. I can see it using Classic UI or HABdroid. I can even see that if I use the switch to switch ON the light, few seconds after, the switch is reset to OFF. Same thing for the slider.

One example of error I can see in my logs:
```
22:42:42.392 [WARN ] [eclipse.jetty.servlet.ServletHandler] - /classicui/app
java.lang.IllegalArgumentException: Value must be between 0 and 100
        at org.eclipse.smarthome.core.library.types.PercentType.validateValue(PercentType.java:46)[88:org.eclipse.smarthome.core:0.8.0.201601082233]
        at org.eclipse.smarthome.core.library.types.PercentType.<init>(PercentType.java:41)[88:org.eclipse.smarthome.core:0.8.0.201601082233]
        at org.eclipse.smarthome.core.library.items.DimmerItem.getStateAs(DimmerItem.java:104)[88:org.eclipse.smarthome.core:0.8.0.201601082233]
        at org.eclipse.smarthome.core.library.items.ColorItem.getStateAs(ColorItem.java:123)[88:org.eclipse.smarthome.core:0.8.0.201601082233]
        at org.eclipse.smarthome.ui.classic.internal.render.AbstractWidgetRenderer.getStateAsNumber(AbstractWidgetRenderer.java:192)[141:org.eclipse.smarthome.ui.classic:0.8.0.201601082233]
        at org.eclipse.smarthome.ui.classic.internal.render.SliderRenderer.renderWidget(SliderRenderer.java:59)[141:org.eclipse.smarthome.ui.classic:0.8.0.201601082233]
        at org.eclipse.smarthome.ui.classic.internal.render.PageRenderer.renderWidget(PageRenderer.java:166)[141:org.eclipse.smarthome.ui.classic:0.8.0.201601082233]
        at org.eclipse.smarthome.ui.classic.internal.render.PageRenderer.processChildren(PageRenderer.java:123)[141:org.eclipse.smarthome.ui.classic:0.8.0.201601082233]
        at org.eclipse.smarthome.ui.classic.internal.render.PageRenderer.processPage(PageRenderer.java:86)[141:org.eclipse.smarthome.ui.classic:0.8.0.201601082233]
        at org.eclipse.smarthome.ui.classic.internal.servlet.WebAppServlet.service(WebAppServlet.java:160)[141:org.eclipse.smarthome.ui.classic:0.8.0.201601082233]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)[71:org.eclipse.jetty.servlet:9.2.10.v20150310]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)[71:org.eclipse.jetty.servlet:9.2.10.v20150310]
        at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:70)[135:org.ops4j.pax.web.pax-web-jetty:4.2.3]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)[70:org.eclipse.jetty.server:9.2.10.v20150310]
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)[69:org.eclipse.jetty.security:9.2.10.v20150310]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)[70:org.eclipse.jetty.server:9.2.10.v20150310]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)[70:org.eclipse.jetty.server:9.2.10.v20150310]
        at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:271)[135:org.ops4j.pax.web.pax-web-jetty:4.2.3]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)[71:org.eclipse.jetty.servlet:9.2.10.v20150310]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)[70:org.eclipse.jetty.server:9.2.10.v20150310]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)[70:org.eclipse.jetty.server:9.2.10.v20150310]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)[70:org.eclipse.jetty.server:9.2.10.v20150310]
        at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:80)[135:org.ops4j.pax.web.pax-web-jetty:4.2.3]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)[70:org.eclipse.jetty.server:9.2.10.v20150310]
        at org.eclipse.jetty.server.Server.handle(Server.java:497)[70:org.eclipse.jetty.server:9.2.10.v20150310]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)[70:org.eclipse.jetty.server:9.2.10.v20150310]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)[70:org.eclipse.jetty.server:9.2.10.v20150310]
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)[62:org.eclipse.jetty.io:9.2.10.v20150310]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)[73:org.eclipse.jetty.util:9.2.10.v20150310]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)[73:org.eclipse.jetty.util:9.2.10.v20150310]
        at java.lang.Thread.run(Thread.java:744)[:1.8.0]
22:43:03.283 [INFO ] [smarthome.event.ItemCommandEvent    ] - Item 'LampeTeleviseurColor' received command 302.95081967213116,95.68627450980392,100
22:43:03.440 [INFO ] [marthome.event.ItemStateChangedEvent] - LampeTeleviseurColor changed from 124,0,0 to 302.95081967213116,95.68627450980392,100
22:43:04.530 [INFO ] [marthome.event.ItemStateChangedEvent] - LampeTeleviseurColor changed from 302.95081967213116,95.68627450980392,100 to 302,95,100
```

Another problem is that the UI controls are not initialized with the correct value at startup. If my light is ON with brightness at 100%, I would expect the switch to be ON and the slider to be at 100% rather than the switch OFF and the slider at 0.

When I play with the hue application to change color or brightness, I can see in the UI (classic UI or HABdroid) that the color is changed accordingly, but one time again only the color picker widget.

Sorry if all this is a little confused.

**Comment by polarathene** [comment]
@lolodomo ~~I'm still new to openHAB but it looks like you're connecting a Slider to Color item? I think the color item expects 3 values for HSB, or the slider is provided 3 values instead of it's 0-100 percent value.~~

I see you use hue, and perhaps the wiki docs confuse you [here](https://github.com/openhab/openhab/wiki/Hue-Binding#brightness-dimmer-items), Right under the heading it is talking about dimmer item for brightness and colour temperature, but the **example uses `Color` for item type not Dimmer!** As someone new to openHAB this might be hard to realize as a typo.

~~You will want to use separate item for brightness(Dimmer) and another for color(Color).~~

---

**Update:** I tried to create colour picker, slider and switch for my Hue lights to show example, but they would not respond, even with hue.cfg(not sure if it was used). After searching google I came across this [community post](https://community.openhab.org/t/hue-item-definition-openhab2/5471/6) and it shows example of how it works with OH2.

The [item wiki docs](https://github.com/openhab/openhab/wiki/Explanation-of-items#item-type) point out that `Color` can take on/off(Switch), percent(Slider) or HSB(Color). You need to specify the channel, you mention doing this but do not show it for your item config(did you do it via UI?), so I think when you reference the item, there is problem.

You can see examples here:
hue.items
```
Color  hue_light_color "Hue Light Color"  {channel="hue:LCT001:0017882a573e:18:color"}
Dimmer hue_light_dim   "Hue Light Dimmer" {channel="hue:LCT001:0017882a573e:18:brightness"}
Dimmer hue_light_temp  "Hue Light CT"     {channel="hue:LCT001:0017882a573e:18:color_temperature"}
```

hue.sitemap:
```
sitemap hue label="Hue Sitemap"
{
    Frame {
        Switch      item=hue_light_color   label="Hue Power"
        Colorpicker item=hue_light_color
        Slider      item=hue_light_color   label="Hue Brightness"
        Slider      item=hue_light_dim
        Slider      item=hue_light_temp
    }
}
```

All of these will work. The slider on Color is adjusting the B(brightness) channel. I am not sure if it is the same as sliding the colorpicker brightness slider which might send full HSB value to the bulb instead of brightness only like with Dimmer?

I've not looked into smarthome docs yet, but the openHAB wiki docs that I refer to are not as reliable when using OH2,  [wiki docs for hue](https://github.com/openhab/openhab/wiki/Hue-Binding#brightness-dimmer-items) for example show how item config used to be with no note for OH2 users about the change.

@kaikreuzer via both Paper UI and HABmin I am unable to see `Brightness` channel, only `Color`, `Color Temperature`, `Alert`, `Color Loop`(Although this should be effect as the command is open to more than 1 and I think it includes the Alert options?). I have not come across documentation on `things` and `channels` myself yet, although I've been using Github wiki which seems specific to OH1 mostly. The `Brightness` channel was referenced from the [community forums](https://community.openhab.org/t/hue-item-definition-openhab2/5471/2), I have verified that it works.

**Comment by kaikreuzer** [comment]
> via both Paper UI and HABmin I am unable to see Brightness channel, only Color,

There actually should not be a brightness channel, whenever there is already a Color channel. There is a bug in the hue binding, which will be cleaned with https://github.com/eclipse/smarthome/pull/1652. This PR also contains an enhanced README.md.

**Comment by madivad** [comment]
@kaikreuzer I'm wondering why you think there should be no brightness channel if a colour channel exists. I have the LCT001 Extended Colour lights and from my earliest usage of the API I have always been able to directly set the brightness channel ("bri") using JSON in Python.  

I'm having trouble finding the exact API reference (it seems they've had a shuffle around on the philips site), but under supported devices on this page ( https://developers.meethue.com/documentation/supported-lights ) you can see that: 

# the "extended color lights (1.5)" support:

> All attributes of 1.3 Color Temperature light and 1.4 Color light

# from 1.4 Color Light: 
> All attributes of **1.2** Dimmable light 
plus:
* colormode
* hue
* sat
* xy


# from 1.3 Color Temperature Light: 
> All attributes of **1.1** On/Off light
plus: 
* colormode
* ct (colour temperature)

# from 1.2 Dimmable Light:
> All attributes in **1.1** On/Off light
plus: 
* bri

# from 1.1: On/Off Light
(looking at only the **state object attributes**:
* reachable
* on
* transitiontime
* alert
* mode
* streaming

Listing all in one place: 
* reachable
* on
* transitiontime
* alert
* mode
* streaming
* bri
* colormode
* ct (colour temperature)
* hue
* sat
* xy

I personally have only ever used:
* on
* transitiontime
* bri
* hue
* sat

Sorry for the long post, it's turned into a bit of a reference for me. I realise I may be talking about something slightly different, but it seems a few projects drop "brightness" from color lights and I'm trying to work out why (when AFAICSee), it works for me in my own hacked together python automation setup.
