### ISSUE TITLE
Hudson build fails on Paper UI

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#919]
Since https://github.com/eclipse/smarthome/pull/873 had been merged, the build on Hudson fails due to proxy problems, see https://github.com/eclipse/smarthome/pull/873:
```
[INFO] o.h.m.e.h.MavenExecutionResultHandler - [1] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.27:bower (bower install) on project org.eclipse.smarthome.ui.paper: Failed to run task
[DEBUG] Closing connection to remote
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.27:bower (bower install) on project org.eclipse.smarthome.ui.paper: Failed to run task: 'bower install --config.proxy=http://proxy.eclipse.org:9898' failed. (error code 1) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.27:bower (bower install) on project org.eclipse.smarthome.ui.paper: Failed to run task
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: Failed to run task
	at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.execute(AbstractFrontendMojo.java:69)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
Caused by: com.github.eirslett.maven.plugins.frontend.lib.TaskRunnerException: 'bower install --config.proxy=http://proxy.eclipse.org:9898' failed. (error code 1)
	at com.github.eirslett.maven.plugins.frontend.lib.NodeTaskExecutor.execute(NodeTaskExecutor.java:59)
	at com.github.eirslett.maven.plugins.frontend.mojo.BowerMojo.execute(BowerMojo.java:42)
	at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.execute(AbstractFrontendMojo.java:67)
	... 21 more
```
@GradyD Could you please have a look?

**Comment by GradyD** [comment]
I've spent some time this afternoon looking into this and sadly I don't have a great answer. 

From what I can tell it appears to be a proxy issue. It appears `bower install` pulls from https://bower.herokuapp.com and since HTTPS is not allowed that could be the reason. Another possibility is that bower is using `git://` instead of HTTP(S) which could also be blocked. 

It appears that I can edit bower to point to HTTP but if it is using `git://` it requires `git config --global url."https://".insteadOf git://` to be ran to fix it. 

With the plan to remove bower already discussed and approved I will make that a priority and try to get bower removed ASAP. Looking at the bower file it looks like I should be able to convert all of those packages over pretty easily, the hope is that all of them exist on NPM. 

Thanks for raising this as a bug, I was not getting the email alerts otherwise I would have started on this sooner.

**Comment by GradyD** [comment]
Hey @kaikreuzer I was able to convert all of the bower packages over to npm. This should fix all of the issues with bower and provide successful builds again :+1:
