### ISSUE TITLE
automation: GenericCondition parsing error

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#950]
On startup an exception is thrown.
The exception is taken plase on parsing this file "./bundles/automation/org.eclipse.smarthome.automation.module.core/ESH-INF/automation/moduletypes/GenericCondition.json"

```text
10:45:37.587 ERROR o.e.s.a.i.c.p.ModuleTypeResourceBundleProvider[:228] - ModuleType parsing error!
org.eclipse.smarthome.automation.parser.ParsingException: [Module Type] com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 28 column 22 path $.conditions[0].configDescriptions[2].options

	at org.eclipse.smarthome.automation.parser.gson.internal.ModuleTypeGSONParser.parse(ModuleTypeGSONParser.java:53)
	at org.eclipse.smarthome.automation.internal.core.provider.ModuleTypeResourceBundleProvider.importData(ModuleTypeResourceBundleProvider.java:226)
	at org.eclipse.smarthome.automation.internal.core.provider.AbstractResourceBundleProvider.processAutomationProvider(AbstractResourceBundleProvider.java:315)
	at org.eclipse.smarthome.automation.internal.core.provider.AutomationResourceBundlesEventQueue.processBundleChanged(AutomationResourceBundlesEventQueue.java:330)
	at org.eclipse.smarthome.automation.internal.core.provider.AutomationResourceBundlesEventQueue.run(AutomationResourceBundlesEventQueue.java:154)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by maggu2810** [comment]
Perhaps solved by #949, will test it.
