### ISSUE TITLE
(Some) console commands broken on Karaf shell

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#984]
Doing a
```
smarthome:send DimmedLight 50
```
or
```
smarthome:update DimmedLight 50
```
results in
```
09:06:32.612 [ERROR] [apache.karaf.shell.support.ShellUtil] - Exception caught while executing command
java.lang.ArrayStoreException
	at java.util.ArrayList.toArray(ArrayList.java:408)[:1.8.0_40]
	at org.eclipse.smarthome.io.console.karaf.internal.CommandWrapper.execute(CommandWrapper.java:39)[98:org.eclipse.smarthome.io.console.karaf:0.8.0.b3]
	at org.apache.karaf.shell.impl.console.osgi.secured.SecuredCommand.execute(SecuredCommand.java:67)[48:org.apache.karaf.shell.core:4.0.3]
	at org.apache.karaf.shell.impl.console.osgi.secured.SecuredCommand.execute(SecuredCommand.java:87)[48:org.apache.karaf.shell.core:4.0.3]
	at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:480)[48:org.apache.karaf.shell.core:4.0.3]
	at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:406)[48:org.apache.karaf.shell.core:4.0.3]
	at org.apache.felix.gogo.runtime.Pipe.run(Pipe.java:108)[48:org.apache.karaf.shell.core:4.0.3]
	at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:182)[48:org.apache.karaf.shell.core:4.0.3]
	at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:119)[48:org.apache.karaf.shell.core:4.0.3]
	at org.apache.felix.gogo.runtime.CommandSessionImpl.execute(CommandSessionImpl.java:94)[48:org.apache.karaf.shell.core:4.0.3]
	at org.apache.karaf.shell.impl.console.ConsoleSessionImpl.run(ConsoleSessionImpl.java:270)[48:org.apache.karaf.shell.core:4.0.3]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_40]
```

**Comment by maggu2810** [comment]
Can you try this ones:
* smarthome:send DimmedLight "50"
* smarthome:update DimmedLight "50"

**Comment by kaikreuzer** [comment]
this works.

**Comment by kaikreuzer** [comment]
fixed by https://github.com/eclipse/smarthome/pull/986
